### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by roshan2004** [pypi/support#1050]
### PyPI Username

roshan2004

### Reason for request

I have lost the access to my pypi account as I lost my 2 factor authentication application after my phone died. Can you please reset my 2FA or issue a password reset so that I can regain access to my account. Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
