### ISSUE TITLE
Mass name squat by user: SrinivasChoudhury/

### ISSUE THREAD

**Issue by erikmannerfelt** [pypi/support#1101]
### PyPI user performing the mass project name squatting

https://pypi.org/user/SrinivasChoudhury/

### Additional information

I am actively working together with my colleagues on [geoutils](https://github.com/GlacioHack/GeoUtils), a tool for geospatial analysis of raster and vector data, and we want to publish it on pypi. I unfortunately found that the name was taken, and upon closer inspection, I found that the source was entirely empty! This is the content of `__init__.py` (the only python script) in `https://pypi.org/project/geoutils`:
```python
def geoutils():
    print('Thanks For Using Geoutils !!!')
def main():
    geoutils()
````
The same user has 9 other projects with *utils names, and have exactly the same one-liner description. I can only assume that they are empty as well. The project URLs point to GitHub repos that no longer exist.

I request for the project geoutils and possible all the other projects from the same user to be taken down so that we can publish our project.

Thank you in advance!

Kind regards,
Erik

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by erikmannerfelt** [comment]
Any news on this?

**Comment by yeraydiazdiaz** [comment]
Please open a PEP 541 for the `geoutils` project name to ensure the project name goes to you.

**Comment by erikmannerfelt** [comment]
Thank you for the response, @yeraydiazdiaz! I have now opened #1188 for this request.

**Comment by miketheman** [comment]
Closing in favor of the completed  PEP541 request.
