### ISSUE TITLE
PEP 541 Request: inary

### ISSUE THREAD

**Issue by examachine** [pypi/support#1109]
### Project to be claimed

`inaya`: https://pypi.org/project/inary

### Your PyPI username

`examachine`: https://pypi.org/user/examachine

### Reasons for the request

This is a license invalidating fork of pisi that has made it look like it was an original version rather than a fork, undermining the contributions of the original authors. The package uploader (zaryob on github I believe), sent some requests to the pisi package but then he apparently decided to fork it without our knowledge. My name and other authors' names have been conveniently erased from the source tree and the whole package is renamed, which we did NOT agree to. I am attaching what GPLv3 says about this. This is clearly an attempt at misrepresenting authorship and hijacking our development and we consider it an attack against PISI package manager and Pisi Linux distributions. They also uploaded an empty package again with a fake email to hijack the pisi name. 

We would like this package removed because it is a reckless attack against our authorship and reputations, and it also seems to  violate GPLv3 license.   All patches against pisi that work will be incorporated into pisi. It's already a small and working software, we do not condone rebranding efforts, but at any rate, they should have asked for our permission for a fork. It is arguable they met the conditions by naming where they branched from, but this is not the case, they just renamed some files and changed documentations to "own" the copyright which they certainly can't. They don't own the copyright. TUBITAK does. And they removed all of the original authors' names. This was a hijacking attempt and it is against the Turkish law to release software that disreputes original authors. It is also ethically quite wrong. They should be erasing this package and naming their software pisi-xyz which we will allow on the condition that they use the original AUTHORS files and copyright and authorship notices from the development branch without mangling file and directory names to make it look like they developed the software.

![gpl3_fork_2021-05-25_20-05-57](https://user-images.githubusercontent.com/587091/119540117-b8045300-bd95-11eb-933c-8c2a27ba6aca.jpg)

### Source code repositories URLs

https://github.com/examachine/pisi

### Contact and additional research

Package uses a fake email which is why we can't contact the author. The mails bounced. I had to ask on PISI linux groups to find out who he really is and it is quite offensive what he did.

https://github.com/Zaryob/inary

He has literally just translated some things to Turkish and made it look like they made a big contribution whereas that is not the case. We really should also report to github, this is a license violation. Unfortunately. They should have asked TUBITAK for a permission. We have received no such request as original authors. They have apparently sent some aggressive PR's to pisi linux too so they probably want to just overtake the projects, but giving their own names to forks is going too far, especially since they also uploaded a fake package to hijack the pisi name and then they also uploaded a version of pisi in which the authorship and naming is completely changed. They refer to "pisi existing as a brand" which makes no sense, pisi is a free software project, it is not a brand, perhaps pisi linux distribution can be considered one but it too is a free software project. Pisi is one of the unique tools of the pardus linux / pisi linux distribution, the latter is the community continuation of pardus linux. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by friberk** [comment]
PiSi package manager project belongs to the Scientific and Technological Research Council of Turkey (TUBITAK) and many other contributors like @examachine. In this regard, one can easily see that the mentioned Inary fork dims out the original developers and previous ownership which violates the GPLv3 license conditions. By comparing both of these repositories, the repository owned by @examachine and the Inary one,  it can be concluded that the names of the original authors have been deleted from the file headers and, therefore, this can be counted as an attempt in order to claim the ownership of PiSi project. I hope that this situation that opposes GNU philosophy will be taken into consideration, and the necessary action will be taken.

**Comment by examachine** [comment]
They claim their project is the best version of a GNU OS while completely misappropriating the whole distribution and renaming the package manager. That's like forking debian and calling it something else like zion entirely and renaming dpkg to  zpkg while erasing the author of the dpkg from the authors list, FWIW, I wrote around 85% of pisi and there are 3 primary authors, others did smaller patches. They didn't clearly denote where they forked from, the "official" pardus branch is out of date, and we have literally had to salvage the code from a subversion repository one of the teams tried to delete, this is all quite dodgy and they should not be allowed to abuse pypi with cloned software.

**Comment by yeraydiazdiaz** [comment]
Hello @examachine, PEP 541 includes as section about [intellectual copyright infringement](https://www.python.org/dev/peps/pep-0541/#intellectual-property-policy) that reads:

> Possibly-infringing packages should be reported to legal@python.org and counsel to the Python Software Foundation will determine an appropriate response. A package can be removed or transferred to a new owner at the sole discretion of the Python Software Foundation to address a claim of infringement.

I will place this request on hold until the PSF makes a decision.

**Comment by ambv** [comment]
@examachine, have you reached out to legal@python.org for this issue? If you don't need any other support, can we close this?

**Comment by examachine** [comment]
I have not reached out to legal@python.org and it's more of an ethical issue than legal but thank you for the advice I'll email them and have their opinion and let you know.
