### ISSUE TITLE
PEP 541 Request: AssimpCy

### ISSUE THREAD

**Issue by jsfrancal** [pypi/support#1113]
### Project to be claimed

`AssimpCy `: https://pypi.org/project/AssimpCy

### Your PyPI username

`jsfranco`: https://pypi.org/user/jsfranco

### Reasons for the request

Hi,

I would like to continue maintaining the AssimpCy project.

Following the PEP 541 list of criteria for determining abandoned projects:

- the owner jr-garcia isn't reachable; see below
- the author has not released any code on github since 2018 (as seen [here](https://github.com/jr-garcia?tab=overview&from=2018-12-01&to=2018-12-31))
- On [my fork of the project](https://github.com/jsfrancal/AssimpCy) I've added support for MacOS compilation that would benefit the community
- I have already contacted other fork authors with valuable contributions to see if they would merge in their contributions, and [had approval from Yves33](https://github.com/jr-garcia/AssimpCy/pull/6).
- I think it makes sense to claim the name rather than create a new named project fork with only delta maintenance improvements, to avoid useless name clutter; and the idea is that we would definitely credit the original author and welcome him back in if he shows up again.

Thank you for your attention. Best regards, Jean-Sébastien Franco.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/jr-garcia/AssimpCy/

### Contact and additional research

- the owner jr-garcia isn't reachable; several would be contributors (Yves33, CruzR, myself with login name jsfrancal on github) have ended up forking a copy after [submitted pull requests weren't met with a response](https://github.com/jr-garcia/AssimpCy/pulls). [My pull request](https://github.com/jr-garcia/AssimpCy/pull/4) is from March 2020. The author responded once to CruzR but the last one was in [February 2019](https://github.com/jr-garcia/AssimpCy/pull/2).
- I have searched his links and webpages listed on github and pypi ([assimp read the docs page](https://assimpcy.readthedocs.io/en/latest/), [blog](https://egdev.wordpress.com)), but none of them list an email address or means of contact. His blog was last updated in 2017.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @jsfrancal, I will start the reachability process with the current owner @jr-garcia, hopefully we will hear back soon and proceed with the transfer.

**Comment by jsfrancal** [comment]
Thanks! Any news from the reachability process?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by jr-garcia** [comment]
@yeraydiazdiaz I'd like to know how does this change affect me, exactly. Thanks.

**Comment by yeraydiazdiaz** [comment]
@jr-garcia it affects you in as much as you'd like to get involved in the project.

You were unresponsive up until today so as PEP 541 states I added @jsfrancal as an owner of the project. My involvement as a moderator stops there, if you are still interested in the project I'm sure you can collaborate with @jsfrancal to improve AssimpCy.

**Comment by jr-garcia** [comment]
That doesn't answer a lot, but ok -_-

**Comment by yeraydiazdiaz** [comment]
Maybe I misunderstood your question. What exactly do you want to know?

**Comment by jr-garcia** [comment]
Don't worry. I already read the PEP. 
BTW I think @jsfrancal failed to demonstrate at least one point:
**the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround;**
because **`to avoid useless name clutter;`** doesn't sound like a fully valid point to me. But since you already did it, 
¯\_(ツ)_/¯
