### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mukul-mehta** [pypi/support#1120]
### PyPI Username

`metamehta`

### Reason for request

I switched my phone and lost access to my old Google Authenticator accounts. I need help to restore my account, and setup 2FA using my new device.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
