### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by AmanOD** [pypi/support#1123]
### PyPI Username

AmanL04

### Reason for request

I uninstalled the 2FA app from my old phone, on reinstallation in new phone it did not have the old accounts.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
