### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by shlomibendavid** [pypi/support#1152]
### PyPI Username

`shlomi.ben.david`

### Reason for request

My phone which holds the authentication app was factory reset and now i can't login to my account (because i don't have the app)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
