### ISSUE TITLE
Mass name squat by user: LEGENDX22

### ISSUE THREAD

**Issue by penn5** [pypi/support#1179]
### PyPI user performing the mass project name squatting

https://pypi.org/user/LEGENDX22

### Additional information

The user has previously had repositories requested for transfer due to abuse. I have made repeated attempts to contact the user on Telegram. They said they would stop, and did indeed delete the malicious repositories, but evidently have gone back to their old ways with the upload of a new [piece of malware](https://pypi.org/project/Netflix-org/) four days ago.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Thanks, this has been removed. In the future, please follow the process here for reporting malware: https://pypi.org/security/
