### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by zalun** [pypi/support#1260]
### PyPI Username

zalun

### Reason for request

Lost 2FA authentication app and never created recovery codes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
