### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by brianmanderson** [pypi/support#1328]
### PyPI Username

brianmanderson

### Reason for request

I lost access to my 2FA after graduating from my previous institution >.<, any help would be greatly appreciated

Thank you,
Brian

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
