### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Ys-Prakash** [pypi/support#1353]
### PyPI Username

`prapandey031`

### Reason for request

I have lost access to the Google authenticator application as well as, I do not have recovery codes (I did not get them initially). I am working on a project (transcv, that is) and I highly require access to my PyPI account, as soon as possible. Please help.   

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
