### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by fbertsch** [pypi/support#1448]
### PyPI Username

fbertsch

### Reason for request

I'm unable to access my 2FA auth. I'm not sure I ever set one up. **Regardless I would like to just ensure that wlach is made owner of this project: https://pypi.org/project/mozilla-schema-generator/**

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
