### ISSUE TITLE
Project Limit Request: autonml - 1.5 GB

### ISSUE THREAD

**Issue by vedant-sanil** [pypi/support#1743]
### Project URL

https://pypi.org/project/autonml/

### Does this project already exist?

- [X] Yes

### New limit

1.5

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is an open release of CMU's AutoML initiative called AutonML, an extension of DARPA's DataDrivenDiscovery Program (https://datadrivendiscovery.org/). We are in the process of converting our codebase to be pip installed by the general machine learning community. 
As with any AutoML system, CMU's AutonML utilizes a wide variety of machine learning and deep learning solutions for automating our machine learning pipeline. Some of these deep learning models include ResNet 50 (an image featurizer), BERT classifier (text data) etc. We achieved excellent performance with these big machine learning models by providing static weight files which are pretrained weights for each model. Each weight file has a significant size, and all in all, encompasses about 1.2G. We provide 7 weight files for our largest DL models. We would like to add these weight files in our next release to support Automated ML solutions for various data types. 

We may request an additional size increase in the future if we add more models, but we don't anticipate that being required currently since our AutonML stack has a generous offering of models already. 

### How large is each release?

Current relesase: 

~ 83KB
Source tar files: 83KB

Future release with static files:
~ 1.2G
Source files: 83KB
Static Weight Files: 1.2G 

These are the names of seven static files we need to include in our project along with their sizes:

```
99M   autonml/static/0128cdfa3963288110422e4c1a57afe76aa0d760eb706cda4353ef1432c31b9c
276M  autonml/static/10086976245803799d9194e9a73d9b6c1549c71d1b80106f5cade5608a561f4b
45M   autonml/static/5c106cde386e87d4033832f2996f5493238eda96ccf559d1d62760c4de0613f8
370M  autonml/static/f82e4e519723fc7b2ff3761ea35600bdaf796fb7a4e62ee4c5591da7ffe48326
99M   autonml/static/bdc6c9f787f9f51dffd50d895f86e469cc0eb8ba95fd61f0801b1a264acb4819
99M   autonml/static/7011d39ea4f61f4ddb8da99c4addf3fae4209bfda7828adb4698b16283258fbe
237M  autonml/static/523e4e69e1d015393a1b0a441cef1d9c7659e3eb2d7e15f793f060a21b32f297
```

### How frequently do you make a release?

Roughly once every one month is our intention. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi, have you explored alternative ways to distribute these models?

**Comment by pradyunsg** [comment]
Closing given the lack of a response.

https://github.com/pypi/support/issues/1662#issuecomment-1129155834 has some context on the approaches that can be used to distribute large models, that aren't necessarily going to change across the various Python versions.
