### ISSUE TITLE
Project Limit Request: Huatuo - 1GB

### ISSUE THREAD

**Issue by easonforai** [pypi/support#1751]
### Project URL

https://pypi.org/project/Huatuo/

### Does this project already exist?

- [X] Yes

### New limit

1GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

this project provides chinese medical NER service which can recognize some entities in medical field,  it has been active for two days. When I upload .whl package,  Limit for project 'Huatuo' is 100 MB. 

### How large is each release?

~728 MB total

51.7 MB medical data
393 MB chinese bert model file
391 MB trained NER model file

### How frequently do you make a release?

Roughly once every half month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi, have you explored alternative ways to distribute these models?

**Comment by cmaureir** [comment]
It has been around one year, and there is no response from OP, so I'm closing this issue.
Please, if you believe it's still an important matter, feel free to comment here.
(Also, project limits are 10G, so the title and content seems to be incorrect)
