### ISSUE TITLE
PEP 541 Request: mal.py

### ISSUE THREAD

**Issue by Skylake-dev** [pypi/support#1800]
### Project to be claimed

https://pypi.org/project/mal.py

### Your PyPI username

`Skylake-dev`: https://pypi.org/user/Skylake-dev/

### Reasons for the request

I get the error "The name 'mal.py' is too similar to an existing project."

### Source code repositories URLs
The source code for my project
https://github.com/Skylake-dev/mal.py

### Contact and additional research

I looked up the name the closest i get are 
- `mal`: https://pypi.org/project/mal/   -- looks like it's abandoned by the owner EDIT: the project repository is archived and the author says the project is broken and no longer works
- `mal-python`: https://pypi.org/project/mal-python/  -- name claimed but never used, it's an inactive fork of another repository

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Skylake-dev, this is because of a feature added to Warehouse recently to reduce dependency confusion attacks. A @pypa/warehouse-admins may be able to help you but I'm not sure.

**Comment by Skylake-dev** [comment]
Hello @yeraydiazdiaz and thanks for your reply. Should i contact someone in particular or wait for them to see this issue?

**Comment by ewdurbin** [comment]
sorry for the long delay. if this is still desired, please respond.

**Comment by Skylake-dev** [comment]
Yes, i was just working on a new release

**Comment by ewdurbin** [comment]
'mal-py' released to 'Skylake-dev'.
