### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by AdrienR09** [pypi/support#1814]
### PyPI Username

AdrienR09

### Reason for request

Hello,

I lost my authentification application and the recovery code too. I would need to access to the library I just created but it is no longer possible. Can you help to get back this recovery code that I can login again to my account.

Cordially,

Adrien Rousseau

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
