### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by zwade** [pypi/support#1871]
### PyPI Username

zwad3

### Reason for request

Last august I destroyed my phone with the authenticator code, and sadly did not generate any backup codes. As a result I have no 2fa access, so no way to get to my account 😢 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
