### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by julianascencio** [pypi/support#1906]
### PyPI Username

`jascenciov`

### Reason for request

Hi team,
Unfortunately, I don't have access to my former institutional email: julian.ascencio@fe.uni-lj.si and this repository has been created with it: https://pypi.org/project/pvweathermaps/

Could you please re assign it to this email: julian.ascencio.vasquez@gmail.com

Thank you in advance,
Julian

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account and CC'd the requested email, please read the instructions and reply to proceed with recovery.

**Comment by julianascencio** [comment]
Hello, I didnt receive the email. Can you do it again?

**Comment by julianascencio** [comment]
I dont have the email with the instructions. Please resend

**Comment by ewdurbin** [comment]
I have resent as requested.
