### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Reggles44** [pypi/support#1915]
### PyPI Username

`Reggles`

### Reason for request

I've lost access to my 2FA device. I still have access to my account email and git repos where these projects were stored.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
