### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by alexpreynolds** [pypi/support#1941]
### PyPI Username

`areynolds`

### Reason for request

I'm in a bit of a Catch-22. I received an email about setting up 2FA, but it looks like I need 2FA set up to log into the site. 

At the moment I am unable to log into the site to change settings, without having 2FA set up.

I do not recall setting up 2FA, and a token is not available from the two 2FA apps I have on my phone. 

I'd like to keep maintaining existing and adding new scientific PyPi packages. Is there anyone who can help me preserve my username?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
