### ISSUE TITLE
PEP 541 Request: cert

### ISSUE THREAD

**Issue by synchronizing** [pypi/support#1947]
### Project to be claimed

`cert`: https://pypi.org/project/cert

### Your PyPI username

`synchronizing`: https://pypi.org/user/synchronizing

### Reasons for the request

User has claimed `cert` and various other PyPi projects with nothing in them other than a `README` stating "Develop soon." User has also claimed:

* `adsl`
* `kwai`
* `ida`
* `cover`
* `trends`
* `netease`
* `beta`
* `enc`
* `am`
* `break`
* `admin`
* `kol`
* `leetcode`
* `xposed`
* `refer`
* `zan`
* `edu`
* `dell`
* `del`
* `night`
* `bcc`
* `nick`
* `adidas`
* `ticket`
* `come`
* `ol`
* `cert`
* `ali`
* `cia`
* `media`
* `alive`
* `gbg`
* `Tyche`
* `Bellona`
* `employ`
* `figlet`
* `ollybd`
* `nintendo`
* `waf`
* `mikufans`
* `ipool`
* `ins`
* `gayhub`

### Maintenance or replacement?

Replacement

### Source code repositories URLs

None. There are no projects posted on `cert`. 

### Contact and additional research

I did not contact the owner of the repo. According to PEP541 "package name squatting is prohibited."

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Re-labeled to mass name squat.

**Comment by Kenny2github** [comment]
The packages seem to no longer be there. This issue can probably be closed.

**Comment by synchronizing** [comment]
It seems that all of the user's package was removed, but when trying to upload to any of the packages above the following error is given:

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                           
         The name '<PROJECT NAME>' isn't allowed. See https://pypi.org/help/#project-name for more information. 
```

**Comment by miketheman** [comment]
@synchronizing I'm going to close this, as the original issue has been resolved, and any individual names from this list can and have been requested and released.
