### ISSUE TITLE
PEP 541 Request: mlia ("name 'mlia' isn't allowed")

### ISSUE THREAD

**Issue by benkli01** [pypi/support#1979]
### Project to be claimed

`mlia`: https://pypi.org/project/mlia

### Your PyPI username

`diegor`: https://pypi.org/user/diegor/

### Reasons for the request

Our project name seems to be not allowed although there is no direct match when searching for the project name on pypi.org.
`400 The name 'mlia' isn't allowed. See https://pypi.org/help/#project-name for more information. `

Could you provide some background on the reason for the name collision and some guidance on how to resolve this issue please? 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

- To publish: https://review.mlplatform.org/plugins/gitiles/ml/mlia/+/refs/heads/main
- Current: Unknown, no entry on pypi.org.

### Contact and additional research

The reason for the name conflict is unknown.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've transferred `mlia` to `diegor`. This project was previously prohibited due to a dependency confusion attack -- please note that you will be unable to make a release of `mlia-0.1.0.tar.gz` but all other versions and distributions will be fine.

**Comment by benkli01** [comment]
Thanks for the very quick resolution @di! That is much appreciated. The upload worked perfectly now.
