### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dvdc** [pypi/support#1994]
### PyPI Username

'dyninc'

### Reason for request

Hi, I am a director of software engineering at OCI DNS (formerly Dyn). 

After Dyn was acquired by OCI, we shut down a lot of email addresses. This is making it difficult to recover this username. If you are able to provide the email address associated, we should be able to re-enable that email address temporarily to recover the dyninc account. We need to regain access, to make updates to the Dyn Python SDK. 

Any help you can provide, would be fantastic. Let me know if there's any verification you need from me. 

Thanks,
Dan VanderClock

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please email support@pypi.org, reference this issue, and we'll provide the email address associated with the account there.

**Comment by ewdurbin** [comment]
I see that this account has been recovered, closing.
