### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lmalina** [pypi/support#1996]
### PyPI Username

`lmalina`

### Reason for request

I have forgotten a password, and at the same time, I can no longer use the email address I created the account with lukas.malina@cern.ch.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please email support@pypi.org, reference this issue, and share the email address you'd like to use with this account to proceed with recovery.

**Comment by lmalina** [comment]
I have just emailed my address, referencing this issue.

**Comment by ewdurbin** [comment]
Contacted via the requested email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
