### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by paramsingh** [pypi/support#2020]
### PyPI Username

iliekcomputers

### Reason for request

* Lost my 2fa authentication app and the recovery token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
