### ISSUE TITLE
Project Limit Request: openvisus - 100 GB

### ISSUE THREAD

**Issue by scrgiorgio** [pypi/support#2038]
### Project URL

https://pypi.org/manage/project/openvisus

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[nogui](http://nationalsciencedatafabric.org/)

### How large is each release?

depends on OS

### How frequently do you make a release?

once a month 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @scrgiorgio :wave:
Can you provide more information about the project? What have you tried to reduce the wheel sizes or the amount of wheels? 
PS: if you could update the url (removing the /manage/ and update the title to replace PROJECT_NAME would be great)

**Comment by pradyunsg** [comment]
Closing this out due to lack of a response.
