### ISSUE TITLE
Mass name squat by user: cheatos

### ISSUE THREAD

**Issue by simonw** [pypi/support#2055]
### PyPI user performing the mass project name squatting

https://pypi.org/user/cheatos

### Additional information

I'm not sure if this is the right category: they've just published a whole bunch of very suspicious (I think spam) packages, but it's not name squatting as such.

Packages so far are:

- https://pypi.org/project/cash-app-free-money-glitch-v-7644/
- https://pypi.org/project/does-cash-app-give-free-money-v-8300/
- https://pypi.org/project/cash-app-free-money-code-2019-v-6215/
- https://pypi.org/project/cash-app-make-free-money-v-893/
- https://pypi.org/project/free-cash-app-accounts-with-money-v-914/

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by simonw** [comment]
Is there a different mechanism I can use for reporting spam?

**Comment by yeraydiazdiaz** [comment]
We don't have a specific template for spam but I believe this should be enough. An admin will need to take action I believe there's been similar incidents like this.

**Comment by ewdurbin** [comment]
this has been handled.
