### ISSUE TITLE
PEP 541 Request: kodiak-rure

### ISSUE THREAD

**Issue by davidblewett** [pypi/support#2060]
### Project to be claimed

`kodiak-rure`: https://pypi.org/project/kodiak-rure

### Your PyPI username

`davidblewett`: https://pypi.org/user/davidblewett

### Reasons for the request

The `kodiak-rure` package is a direct copy of my `rure` package: https://pypi.org/project/rure/ . It stems from this issue on my github repo: https://github.com/davidblewett/rure-python/issues/24 . The new package was uploaded solely for the purposes of distributing a binary wheel for M1 Macs. The folks that uploaded it didn't wait for my response on providing a binary wheel. Since this wheel contains a binary (originally intended for wrapping the Rust regex crate), it  is possible that the uploaded wheels have malicious content in them. I asked them to remove the package to avoid confusion with the canonical repo almost a week ago, but haven't had a response since.

I have not had time to maintain the original `rure` package, but I would prefer an orderly transfer of it to someone rather than it being hijacked.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/davidblewett/rure-python

### Contact and additional research

I asked for the package to be removed on June 29, 2022: https://github.com/davidblewett/rure-python/issues/24#issuecomment-1169997504 .

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @davidblewett, I don't think PEP 541 covers this scenario as its primary use case is the transfer of abandoned projects. 

That being said I will try to communicate with @chdsbd to see if he'd be willing to remove the project and/or contribute to `rure` to include the extra binary wheels.

**Comment by davidblewett** [comment]
@yeraydiazdiaz I asked him to take the wheels down on  June 29 and haven't heard anything back since.

**Comment by sbdchd** [comment]
I've updated the readme on the PyPi listing to prevent any confusion:

https://pypi.org/project/kodiak-rure/

**Comment by yeraydiazdiaz** [comment]
I'll close this as contact has been made and action was taken.
