### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by niccolotubini** [pypi/support#2140]
### PyPI Username

geoframe

### Reason for request

I lost my email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please email support@pypi.org referencing this issue and stating the email address you previously used as well as the email you'd like to use in order to proceed with account recovery.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account and CC'd the requested address, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Verification is complete, but the requested email address is in use by another account. We can either transfer the project(s) owned by the old account to that new account, or you can change the email address on the other account.
