### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by robert-assemblyai** [pypi/support#2145]
### PyPI Username

robot@assemblyai.com

### Reason for request

Hi there. I'm the Sr. Director of Solutions Engineering, we are trying to update the published packages, but the password reset for the email address on file is not working. The account is under 'robot@assemblyai.com'  Here is my LinkedIn for an additional verification step - https://www.linkedin.com/in/robmlove./

AssemblyAI packages on PyPI - https://pypi.org/search/?q=assemblyai

Thank you,
Robert Love
robert@assemblyai.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by robert-assemblyai** [comment]
Any update on this request? We would like to complete this update this week! August 12th

**Comment by ewdurbin** [comment]
Please attempt another password reset so we can determine if it is a deliverability issue on PyPI's side or something with your corporate mail servers.

**Comment by ewdurbin** [comment]
Closing due to lack of response.
