### ISSUE TITLE
File Limit Request: pytorch-gpu - 600 MB

### ISSUE THREAD

**Issue by ssbuild** [pypi/support#2164]
### Project URL

https://pypi.org/project/pytorch-gpu/

### Does this project already exist?

- [X] Yes

### New Limit

600 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

rebuilding the majar pytorch (https://github.com/pytorch/pytorch.git) with lastest cuda cudnn and nccl mkl 

### Reasons for the request

We're releasing for main pytorch gpu package and we're hitting the project size limit at only some whl package ,hope you can increased pytorch-gpu project size to 600 MB , and total size with 30G, I will do rarely upload.
We build pytorch using the environment as follow cuda 11.6 cudnn 8.4 nccl 2.12
tensorrt: 8.4 nvidia Compute Capability 6.0 6.1 7.0 7.5 8.0 8.6.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Is this an official release of Pytorch?

**Comment by pradyunsg** [comment]
Closing this out due to lack of activity. If this is still necessary, please comment here stating so and we'll reopen this. :)
