### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tyler-vane** [pypi/support#2193]
### PyPI Username

`juliehubs`

### Reason for request

User accepted a job with another company, and we don't have access to another secondary account to help administer access.  This request is submitted by our Systems Security Manager.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
juliehubs appears to be a personal account with no projects associated with it.

are you trying to regain access to the `withabound` User account?
