### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jwickfil7** [pypi/support#2199]
### PyPI Username

inspiredlp0

### Reason for request

When I try to log in to pypi, the 2fa authentication app doesn't seem to work (the otp 6-digit code appears, but it says different in pypi)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
