### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by SatyakiDe2019** [pypi/support#2234]
### PyPI Username

Satyaki.De

### Reason for request

I lost the 2FA authentication app during my mobile phone change. And I couldn't recall where I stored that recovered code. Can you please help me to recover it?

Let me know - if you need any more information.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by SatyakiDe2019** [comment]
I've uploaded the package using the credentials, but it looks like I cannot manage the package due to this. I need your help here.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by SatyakiDe2019** [comment]
Thanks, ewdurbin. I have some questions. I send a reply. Can you please let me know the answer?
