### ISSUE TITLE
PEP 541 Request: abenity

### ISSUE THREAD

**Issue by markroland** [pypi/support#2290]
### Project to be claimed

`abenity`: https://pypi.org/project/abenity

### Your PyPI username

`abenity`: https://pypi.org/user/abenity

### Reasons for the request

The project is abandoned and needs to be updated.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current: https://github.com/casbeebc/abenity-python
Replacement: https://github.com/Abenity/abenity-python

### Contact and additional research

- I emailed the owner on 9/16/2022 with no response
- I created a [github issue](https://github.com/casbeebc/abenity-python/issues/3) on 9/28/2022 with no response

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by markroland** [comment]
Is this being looked into? Thank you.

**Comment by yeraydiazdiaz** [comment]
Hello @markroland, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by markroland** [comment]
Hi @yeraydiazdiaz . Is there any update on this transfer? Thank you very much.

**Comment by markroland** [comment]
I'm closing this task. I have created the package at https://pypi.org/project/abenity/
