### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JPHammonds** [pypi/support#2294]
### PyPI Username

`JPHammonds`

### Reason for request

I do not have pypi in my authenticator app.  I do not remember setting up 2FA here and do not have backup codes for this.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
