### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by prljav** [pypi/support#2302]
### PyPI Username

`prljav`

### Reason for request

i didnt loose access to my email, i dont know my email! please help

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by prljav** [comment]
> Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

I forgot my email adress, how am i supposed to check it if i dont know it?

**Comment by Thespi-Brain** [comment]
Hi @prljav,

Following up regarding your issue, just letting you know that I am closing this issue since it has been open for 2 years. If you are still having trouble with your email address and account, feel free to create a new request, thanks.
