### ISSUE TITLE
PEP 541 Request: pagarmepy

### ISSUE THREAD

**Issue by robertons** [pypi/support#2305]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pagarmepy

### Your PyPI username

`USER_NAME`: https://pypi.org/user/robertons

### Reasons for the request

I believe the project is abandoned as it has been over 7 years since the user made any updates to GitHub and PyPi. I'm developing a new project and the user in question also used the paymepy and payme-py variations. The name of the project just pay me was not accepted by Pypi's policies

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/robertons/pagarmepy

### Contact and additional research

I sent 3 emails to the user requesting the transfer and got no response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @robertons, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
