### ISSUE TITLE
PEP 541 Request: sortme

### ISSUE THREAD

**Issue by sadfun** [pypi/support#2344]
### Project to be claimed

`sort-me`: https://pypi.org/project/sort-me

### Your PyPI username

`sortme`: https://pypi.org/user/sortme

### Reasons for the request

We are creating the API wrapper for [sort-me.org](https://sort-me.org) project and want to name it `sortme`. There is no python package named sortme, yet we are unable to upload package with such name on PyPI, because it's too similar to [`sort-me`](https://pypi.org/project/sort-me) – kind of school project with just some mainstream sorting algorithms.

We currently upload preview versions to [sortme-api](https://pypi.org/project/sortme-api/), but want to claim name `sortme`. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

We are ready for public wrapper release at GitHub, but gonna do it after claiming nice name for the package, so users don't have to reinstall this dependency under a new name. Current code can be found at [sortme-api](https://pypi.org/project/sortme-api/).

### Contact and additional research

I sent a mail describing situation to `sort-me` package author via email from pypi profile, but there is no response for a week.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @sadfun, given the limited functionality of the project I will consider it invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by arorayash905** [comment]
Hi @sadfun, I am not planning to work on my project any further. you can make an offer and I will release the project.

**Comment by sadfun** [comment]
Hi @arorayash905, what do you mean by offer?

**Comment by arorayash905** [comment]
Hi @sadfun, I meant monetary offer. even though I am not using this project as of now but I put my efforts and time in that. I just can't release it off.

**Comment by yeraydiazdiaz** [comment]
@arorayash905 the PyPI project name was given to you for free, yet you want to profit from publishing a project you abandoned more than a year ago and has very limited functionality and no actual users.

PyPI has a limited set of project names and it is up to us as a community to be mindful of our use of them, I suggest you reconsider your position.

**Comment by arorayash905** [comment]
I understand that project name is given to me for free and its inactive from a long time but I put my efforts and time in this project.

It also adds up in my CV and I teach some of my students giving example of this module. My students also takes this module as reference for their learnings.

Pardon me for making benefit from this, if that's not how it works.

**Comment by yeraydiazdiaz** [comment]
To be clear, PEP 541 states project cannot be transferred without the explicit constent of the owner if they are reachable. That being said,

> It also adds up in my CV and I teach some of my students giving example of this module. My students also takes this module as reference for their learnings.

You can still achieve this by pointing your students and prospective employers to [the project's GitHub repo](https://github.com/arorayash905/package), the only thing that would change would be the ability for someone to install your project from PyPI.

@sadfun, if you are not willing to pay @arorayash905 there is an option for admins to force the creation of your project as your intended `sortme` name. The downside is that some of your users may mistype the name and end up with the other project. Let me know if you'd like to take that route so I can inform an admin.

**Comment by sadfun** [comment]
@yeraydiazdiaz, thank you very much for protecting my interests! I appreciate that.

As you say above, you consider this project as **invalid** due to limited functionality. PEP 541 has a section about invalid projects:

> ### [Invalid projects](https://peps.python.org/pep-0541/#invalid-projects)
> A project published on the Package Index meeting ANY of the following is considered invalid and **will be removed** from the Index:
...
**project is name squatting (package has no functionality or is empty);**
...


If you need additional proofs that this project is name squatting, Yash is lying about this project's "usage". He says that the project is valued because "adds up in my CV", but his [publicly available CV](https://www.freelancer.co.ke/u/arorayash905/portfolio/yash-arora-9164434) doesn't have any links for sort-me. CV was updated 2 months after uploading sort-me, project was recently made, but even Yash decided that's not enough for CV.

So, I bet this situation falls more to deletion of nonsense project than to taking someone's name, so explicit consent not required here - moreover, the author immediately said that he agreed to give it only for money, which is clearly name squatting.

**Comment by di** [comment]
@sadfun, would `sortme` be preferable as a package name? If so, we can just release that to you.

**Comment by sadfun** [comment]
@di, `sortme` name is good option, yes. 
I wrote previous message because I'm afraid of mistyping by users, especially because our `sort-me.org` is written with dash too.

**Comment by sadfun** [comment]
@arorayash905, maybe I really haven't seen all of your CVs, but it still seems obvious that with statements like that you're still putting a price on an empty project so that demanding money to remove it doesn't sound so much like name squatting.

I replaced a few words in my post to be more correct (sorry if I that offended you), but my overall position remains the same: you are pretending that this project is not invalid in order to get money for removing it.

**Comment by arorayash905** [comment]
Its not only about CV @sadfun. CV is not the only thing I mentioned that puts value to me from this project. You should also maintain an ethical behaviour on such platforms instead of calling someone a liar or pretentious.

**Comment by sadfun** [comment]
@arorayash905 I already fixed "lying" word and don't see more ethical issues here. Project considered as invalid by moderator, I agreed with that, now I'm pointing to PEP 541 to finish this issue. What's wrong?
