### ISSUE TITLE
PEP 541 Request: csp

### ISSUE THREAD

**Issue by timkpaine** [pypi/support#2346]
### Project to be claimed

`csp`: https://pypi.org/project/csp/

### Your PyPI username

`timkpaine`: https://pypi.org/user/timkpaine

### Reasons for the request

- Project is part of a now-defunct platform
- No non-alpha releases
- Project maintainers contacted via email, no response
- Project maintainers pinged on GH, no response https://github.com/mcarter/csp/issues/2

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Original project repository seems to have been removed, here is the author and a few (defunct) adjacent projects
https://github.com/mcarter?tab=repositories

e.g. the specification: https://github.com/mcarter/csp
an example binding for twisted:  https://github.com/mcarter/csp_twisted

Replacement project is a stream processing library, here is the placeholder https://github.com/timkpaine/future-project

### Contact and additional research

I have emailed all listed maintainers and received no response from any of them. I have also attempted to contact via GH to no avail: https://github.com/mcarter/csp/issues/2

@mcarter @desmaj @bubbleboy14 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @timkpaine, it seems your project is a placeholder at the moment and thus is considered invalid. We do not transfer project preemptively, please open a new issue when the project is ready for publication.

**Comment by timkpaine** [comment]
> Hi @timkpaine, it seems your project is a placeholder at the moment and thus is considered invalid. We do not transfer projects preemptively, please open a new issue when the project is ready for publication.

im ready to transfer, project is renamed and ready to publish I just have to rename on GitHub and update the readme. Its Chicken and egg, if you say "we can do this now" im ready to publish right now (and then will adjust the GitHub project later), if you say "no go" then I can revert the GitHub back.

**Comment by yeraydiazdiaz** [comment]
As I mentioned the repo at the moment has no functionality which makes it invalid.

**Comment by timkpaine** [comment]
@yeraydiazdiaz what? that project has several thousand lines of completely functional, well tested python code

**Comment by yeraydiazdiaz** [comment]
Apologies, I saw the repo's name and single commit and opened a few files which happened to be empty so I assumed, as it has happened in other cases, that the project was simply a scaffold. I'm not sure what you mean be 'the inconsistency of application of the PEP-541' though.

Regardless I will start the reachability process for your request which can take up to 6 weeks.

**Comment by timkpaine** [comment]
> Apologies, I saw the repo's name and single commit and opened a few files which happened to be empty so I assumed, as it has happened in other cases, that the project was simply a scaffold. I'm not sure what you mean be 'the inconsistency of application of the PEP-541' though.
> 
> Regardless I will start the reachability process for your request which can take up to 6 weeks.

No problem, I always just take a pessimistic view and assume "this probably won't happen" as a lot of orgs have gotten more difficult to deal with name recycling (I'm mostly familiar with GitHub's changing policies, I think I've only ever dealt with namesquatting for pypi not 541 specifically so apologies if I was overly negative!). 

Let me know if there's anything else you need from me, I never heard anything from the authors on GH or email and it looks like that project is defunct and the urls are mostly routing to parked domains.

**Comment by timkpaine** [comment]
sorry to bother, I know you guys have a ton of stuff on your plates, just wondering if theres anything i can do to help out with this. Happy to help out in whatever capacity i can.

**Comment by timkpaine** [comment]
Sorry to bother, just circling back again, maintainer has never responded to me and I assume not to you either. Thanks again for all the work you do, please let me know if there's anything I can do to help!

@di @ewdurbin

**Comment by bubbleboy14** [comment]
Hello. Sorry for the late reply. I can't speak for the other devs, but it's
fine with me if you call your project csp.

**Comment by timkpaine** [comment]
@bubbleboy14 are you an owner on the pypi project? If you are, you can add me as an owner and I can reset everything (pypi name is timkpaine). Otherwise the pypi admins have to do it (part of which is trying to reach out to you folks via email, which we both have tried to do). Lmk if there's anyway I can help!

**Comment by bubbleboy14** [comment]
@timkpaine ok, you should be all set, happy coding!

**Comment by timkpaine** [comment]
@bubbleboy14 thanks so much!!
