### ISSUE TITLE
PEP 541 Request: napalm-huawei-vrp

### ISSUE THREAD

**Issue by codingnetworksb** [pypi/support#2348]
### Project to be claimed

`napalm-huawei-vrp`: https://pypi.org/project/napalm-huawei-vrp

### Your PyPI username

`codingnetworks`: https://pypi.org/user/codingnetworks

### Reasons for the request

I'm a maintainer of this project in GitHub and the only maintainer in Pypi it seems to have abandoned the project. It's not responding emails since January. I'm pushing new commits and created a new release but without a Maintainer permission i can't publish this release to Pypi.

Link to new release a want to publish:
https://github.com/napalm-automation-community/napalm-huawei-vrp/releases/tag/v1.1.0

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current repository and the one i'm maintaining and want to keep maintaining:
https://github.com/napalm-automation-community/napalm-huawei-vrp

### Contact and additional research

As you see in the following linked, i created an issue in the Github Project, on June 2022 to contact Locus Li , the main maintainer of napalm-huawei-vrp. Because i wanted to be a maintainer. I never received an answer.

https://github.com/napalm-automation-community/napalm-huawei-vrp/issues/17

I also tried by email. No answer:

![2022-10-30 15_19_52-NAPALM Huawei VRP Library - michadom21@gmail com - Gmail — Mozilla Firefox](https://user-images.githubusercontent.com/92046134/198897469-7606fa7f-d6c5-4153-99bb-9583b5277098.png)

A few weeks later i contacted Mircea Ulinic the owner of the NAPALM Community Collection and he made maintainer on Github.

I would like to publish new releases to Pypi, but it seems that Locus (https://pypi.org/user/locus/) is the only maintainer. 

Tried to find any other contact information in his blog https://www.byto.top/, but couldn't find any social media account or another email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @codingnetworksb, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
I've added `codingnetworks` as an owner of the project.
