### ISSUE TITLE
PEP 541 Request: django-generate-series-cte

### ISSUE THREAD

**Issue by jacklinke** [pypi/support#2350]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/django-generate-series-cte

### Your PyPI username

`USER_NAME`: https://pypi.org/user/jacklinke

### Reasons for the request

A new package ([django-generate-series-cte](https://pypi.org/project/django-generate-series-cte/)) based on one of mine ([django-generate-series](https://pypi.org/project/django-generate-series/)) has shown up on PyPI with code that appears to be non-malicious modification (potentially an improvement) of the original code.

I love that someone thought highly enough of my work to modify it, but the authorship of this modified package is ambiguous with my name, email, repo, original readme, etc still present.

My concern is that it may appear to others that the contents of this package are wholly mine, so that any code errors or future malicious changes might appear to be coming from me.

Additionally,

- The package owner's username (JMEdodgerEn2) is used nowhere else on the Internet.
- Their actual name on PyPI (Jamie Williams) is too generic to narrow down to a single person.
- There is no contact info provided for the package owner.
- The package includes only a wheel file, making access to the modified source difficult.

I have no way to contact the package owner, or that would have been my first step. I do not believe this package was added with malicious intent, but it could be changed to include malicious content in the future with my name and contact information still attached.

### Source code repositories URLs

- **django-generate-series-cte**: Unknown
- **django-generate-series**: https://github.com/jacklinke/django-generate-series/

### Contact and additional research

I tried searching for the package owner using username and actual name, but was unsuccessful.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jacklinke** [comment]
Any thoughts or resolution for this issue?

**Comment by yeraydiazdiaz** [comment]
Hi @jacklinke, this does not fall under the PEP 541 use case so it's a bit unclear to me the course of action to take.

What would be the ideal outcome for you? Would amending the author and a note on the README suffice?

**Comment by jacklinke** [comment]
Thank you @yeraydiazdiaz , I wasn't sure how else to address this. The proposed resolution sounds great.

**Comment by yeraydiazdiaz** [comment]
Looks like the owner of `django-generate-series-cte` deleted its only release so it's no longer available.
