### ISSUE TITLE
PEP 541 Request: vast

### ISSUE THREAD

**Issue by lava** [pypi/support#2352]
### Project to be claimed

`vast`: https://pypi.org/project/vast

### Your PyPI username

`tenzir`: https://pypi.org/user/tenzir

### Reasons for the request

For our telemetry database [VAST](https://github.com/tenzir/vast) we are working on creating new [python bindings](https://github.com/tenzir/vast/tree/master/python) which we would like to distribute as the `vast` package on PyPI.

The [existing package](https://pypi.org/project/vast) seems to be unused, with no content ever being published.since it has been registered 6 years ago.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current Project: No content

Intended Replacement: https://github.com/tenzir/vast/tree/master/python

### Contact and additional research

I did not see a way to contact the current owner, since there is no email contact listed in their PyPI profile and there is no project page or any other content at all. 

From their other projects I identified their GitHub handle to be @lahwran . There is no project repository to open an issue for this matter, and their commits on other repositories are using an `@noreply.github.com` email address, so tagging him in this issue seems to be the best way of making them aware of this request.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dominiklohmann** [comment]
I reached out to @lahwran via Email pointing them to this issue. What's the process here in case they do not respond?

**Comment by yeraydiazdiaz** [comment]
Hi @lava, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before transferring the project

**Comment by lahwran** [comment]
I'm not at vast anymore, haven't heard back from jake about this, there's nothing there, seems fine to me.

**Comment by lava** [comment]
@yeraydiazdiaz It seems like a week is passed, any objection to moving forward with this?

**Comment by lahwran** [comment]
I belatedly realized I can in fact simply log in and transfer ownership, which I've done. @jsbcannell speak now or forever be stuck with a different pypi name!

**Comment by lahwran** [comment]
Ah jake has responded to me now and would in fact like to use the package; I've asked him to comment here with details of his plans so y'all have an idea what to expect from vast.ai about this package name. He's asked me to transfer the package to him, so when he creates a pypi username, I'll do that transfer to him. Sorry for the confusion, lava and tenzir!

**Comment by jsbcannell** [comment]
Hello, we have a python [CLI script](https://github.com/vast-ai/vast-python) in github which was supposed to be packaged as vast so users can pip install vast instead of using vast.py.  I will create a pypi profile to take ownership of this project from lahwran to link it to our github.  Sorry for the confusion.

**Comment by yeraydiazdiaz** [comment]
Closing as contact has been made and seems there was a resolution to the request.
