### ISSUE TITLE
PEP 541 Request: KiTT

### ISSUE THREAD

**Issue by senges** [pypi/support#2358]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/KiTT

### Your PyPI username

`USER_NAME`: https://pypi.org/user/csenges

### Reasons for the request

I'm working an opensource project called kitt (see [senges/kitt](https://github.com/senges/kitt)). As I wanted to release it on pypi.org, I realized the package name was already claimed by [guyzmo/kitt](https://github.com/guyzmo/kitt).

However, I saw the latest project commit was from 10 years ago so I managed to get in touch with the author (@guyzmo) on twitter. After a quick chat, he said he was totally fine with the idea of transferring ownership if there was any convenient way of renaming his package to let me use it.

My project is for now distributed under the name `kitt-shell`.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

# New project
https://github.com/senges/kitt

# Current project
https://github.com/guyzmo/kitt

### Contact and additional research

We got in touch on Twitter ([@guyzmo](https://twitter.com/guyzmo)).

Author also asked a question regarding this name transfer on libera chat, but with no apparent success.

He gave me his email address (I won't link it publicly here for obvious privacy reasons), that means we can have a chat as well with someone regarding this if necessary.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by guyzmo** [comment]
Hello, I'm @guyzmo and I approve this request ☺ Basically, I'd be happy to have my package renamed kitt-mt (as it's a multitouch tool). The package is still working and useful, even if it's been 10 years, even if it's still in py2.

**Comment by yeraydiazdiaz** [comment]
Hi @senges, @guyzmo moderators cannot rename projects (and I believe neither can admins but I might be wrong) so you would have to change the name of the project in the repo and push to `kitt-mt` in PyPI.

Note that renaming the project might confuse some of your existing users although it seems there aren't that many non-mirror installations of KiTT according to https://pypistats.org/packages/kitt.

If you're still happy to go ahead with the transfer let me know.

**Comment by ambv** [comment]
Given that the author of the original package was reached, but wanted to retain the package on the index, we are unable to continue here.

As Yeray said, PyPI doesn't support project renaming. The original author would have to upload a new package under the name `kitt-mt`, and in this case we would be able to transfer the name `kitt`.

As it stands, `kitt-mt` was not uploaded by the original author so we cannot transfer `kitt`.

Given that a year passed, we're closing this. Sorry for the inconvenience.
