### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by stryngs** [pypi/support#2365]
### PyPI Username

`stryngs_42`

### Reason for request

Hello,

I am requesting help to gain access back to stryngs and stryngs_42.  I am the owner of both accounts but for stryngs no longer have the domain associated with it.  For stryngs_42 I have the username and password, but broke my phone and so have no ability to prove who I am with MFA.

If at all possible I would prefer to merge the two accounts as I had planned on pushing an update of airpwn-ng today and other code I have in my repo and want to make pip'able.

Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please open a separate account recovery request for the `stryngs` User.

`stryngs_42` has valid Account Recovery codes generated as of 2022-06-08. You should use one of these stored recovery codes to regain access to that account.

**Comment by stryngs** [comment]
I should have been more responsible with those codes.  Being as I want the user stryngs rather than stryngs_42, but also need to move the packages over what would you recommend?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by stryngs** [comment]
```
[<support@pypi.org>](mailto:support@pypi.org): host aspmx.l.google.com[172.253.122.27] said: 550-5.7.1
    [x.x.x.x] The IP you're using to send mail is not authorized to
    550-5.7.1 send email directly to our servers. Please use the SMTP relay at
    your 550-5.7.1 service provider instead. Learn more at 550 5.7.1
    https://support.google.com/mail/?p=NotAuthorizedError
    x10-20020ae9f80a000000b006bb81d694dfsi6280315qkh.656 - gsmtp (in reply to
    end of DATA command)
    ```
    I am not able to forward the email I received to support@pypi.org.  This is because you use Google as your MX and they are very anti-competitive.  The IP referenced above is a Digital Ocean droplet on a domain I currently have possession of.
    
    Is there a non Google email address I can correspond with?

**Comment by Thespi-Brain** [comment]
Hi @stryngs,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let me know. I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having issues, feel free to create another request. Thanks.

**Comment by Thespi-Brain** [comment]
Closing due to non response
