### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ArefMousakhani** [pypi/support#2371]
### PyPI Username

ArefMousakhani

### Reason for request

hi.
I don't have access to the authenticator app and I lost my recovery code

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
