### ISSUE TITLE
PEP 541 Request: cytomine-python-client

### ISSUE THREAD

**Issue by Steven-N-Hart** [pypi/support#2382]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/cytomine-python-client

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Steven-N-Hart

### Reasons for the request

I was the previous owner, but discontinued support, and ultimately deleted the project. As this code was related to software supported by a company, they have asked to transfer ownership of that code.  I would like them to be the maintainers.  I am no longer contributing. 

However, this seems to be deleted from my PyPi account, so I'm unable to manually transfer ownership to them.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The original source code has been deleted from GitHub:
https://github.com/Steven-N-Hart/Cytomine_GetAnnotation

The one to publish in its place:
https://github.com/cytomine/Cytomine-python-client

### Contact and additional research

I am the orignal owner, but would like to transfer to https://github.com/waliens

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by waliens** [comment]
Thank you for creating this ticket @Steven-N-Hart 

We would like to transfer the ownership to our user `cytomine` on PyPi.

I have attempted to create upload the package but got this output:

```
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: cytomine
Enter your password: XXX
Uploading cytomine-python-client-2.3.3.tar.gz
100%|....
51.7k/51.7k [00:01<00:00, 48.3kB/s]
Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'cytomine-python-client' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

**Comment by yeraydiazdiaz** [comment]
Hello @Steven-N-Hart, the project was placed in the prohibited names list. A @pypi/warehouse-admins should be able to release the project. Would you like to release it to your PyPI user or @waliens's?

**Comment by Steven-N-Hart** [comment]
@waliens<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwaliens&data=05%7C01%7CHart.Steven%40mayo.edu%7C7885d5048e764f09de7c08db0c6c3eb8%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638117431278825314%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3ovhlI1%2B4wen9NISGUqfcH%2B91IFjOrSPbO%2FX940kIAs%3D&reserved=0> will be fine. Thank you.

Steven Hart, Ph.D.
Senior Associate Consultant - Artificial Intelligence
Associate Professor of Biomedical Informatics
Division of Computational Pathology and AI
Department of Laboratory Medicine and Pathology
Mayo College of Medicine
Phone: 507-538-5288 | ***@***.******@***.***>
Mayo Clinic | 200 First Street SW | Rochester, MN 55905 | www.mayoclinic.org<http://www.mayoclinic.org/>

From: Yeray Díaz ***@***.***>
Sent: Saturday, February 11, 2023 2:12 PM
To: pypi/support ***@***.***>
Cc: Hart, Steven N., Ph.D. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [pypi/support] PEP 541 Request: cytomine-python-client (Issue #2382)


Hello @Steven-N-Hart<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSteven-N-Hart&data=05%7C01%7CHart.Steven%40mayo.edu%7C7885d5048e764f09de7c08db0c6c3eb8%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638117431278669102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VzjIS4DH9TXd%2BM4zvhbPc5hY5DNzfwz5NO6R85xAf%2BY%3D&reserved=0>, the project was placed in the prohibited names list. A @pypi/warehouse-admins<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forgs%2Fpypi%2Fteams%2Fwarehouse-admins&data=05%7C01%7CHart.Steven%40mayo.edu%7C7885d5048e764f09de7c08db0c6c3eb8%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638117431278669102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Su6VqY8u0sMxjUMKHPmrSaUyMGkazu4hKzKklyTx4sU%3D&reserved=0> should be able to release the project. Would you like to release it to your PyPI user or @waliens<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwaliens&data=05%7C01%7CHart.Steven%40mayo.edu%7C7885d5048e764f09de7c08db0c6c3eb8%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638117431278825314%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3ovhlI1%2B4wen9NISGUqfcH%2B91IFjOrSPbO%2FX940kIAs%3D&reserved=0>'s?

-

**Comment by waliens** [comment]
> Hello @Steven-N-Hart, the project was placed in the prohibited names list. A @pypi/warehouse-admins should be able to release the project. Would you like to release it to your PyPI user or @waliens's?

Dear @yeraydiazdiaz, thank you for your answer. It would be great if the name could be released to our company user `cytomine` (https://pypi.org/user/cytomine/).

**Comment by waliens** [comment]
Thank you very much !
