### ISSUE TITLE
PEP 541 Request: seaplane

### ISSUE THREAD

**Issue by tonilopezmr** [pypi/support#2383]
### Project to be claimed

`seaplane`: https://pypi.org/project/seaplane/

### Your PyPI username

`seaplane`: https://pypi.org/user/seaplane/

### Reasons for the request

Hi, I'm Toni Developer Experience Engineer at Seaplane Inc.

I'm responsible for some of the current Public Seaplane SDKs, and we released our product last month and publicly open source our current SDKs ([Rust](https://crates.io/crates/seaplane), Python, [JavaScript](https://www.npmjs.com/package/seaplane), and [CLI app](https://crates.io/crates/seaplane-cli)).

I saw in PyPI that `seaplane` package was already taken by Harrison but It wasn't updated from 4 years ago, so I tried to talk with him about the idea of changing the current package name or removing the package, and he didn't reply.

I'm recurring to this PEP 541, to be able to publish our Python SDK under `seaplane` package.

I hope all the information given in this request, It's enough, if you need more information, please contact me at toni@seaplane.io

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current Seaplane project: https://github.com/hwstovall/seaplane

For replacing this one: https://github.com/seaplane-io/seaplaneTo

### Contact and additional research

This is the email I sent to the Owner Harrison with his hwstovall@gmail.com, email which is on his pypi page and it seems his day-to-day email.

------------------------------------

From: Antonio López <toni@seaplane.io>
Date: Fri, Oct 21, 2022 at 2:17 PM
Subject: Python package seaplane 0.1.4
To: <hwstovall@gmail.com>

Hi Harrison, 

I'm Toni, dev experience engineer at Seaplane Inc ([seaplane.io](http://seaplane.io/)). We are about to release our SDK's and I wanted to name the package seaplane like the company. 

I saw the last version of the package was from 2018, and I'm wondering whether you could remove it if it is not being used, or if you could rename it, it would be perfect.

I'm looking forward to hearing from you.

Kind Regards,
Toni

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @tonilopezmr, I will now start the reachability process for your request which can take up to 6 weeks.

**Comment by tonilopezmr** [comment]
Thank you @yeraydiazdiaz !!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by tonilopezmr** [comment]
Thank you for your work @yeraydiazdiaz 🎉 🎉
