### ISSUE TITLE
PEP 541 Request: inflation

### ISSUE THREAD

**Issue by ecboghiu** [pypi/support#2388]
### Project to be claimed

`inflation`: https://pypi.org/project/inflation

### Your PyPI username

`ecboghiu`: https://pypi.org/user/ecboghiu

### Reasons for the request

The current project is a name squat. Inspecting the source code reveals an empty project with `print("this is a sample app")` being the only meaningful line of code.

Our project, hosted here:

https://github.com/ecboghiu/inflation

is a fully fledged project, with an associated scientic publication (https://arxiv.org/abs/2211.04483), a  [documentation website](https://ecboghiu.github.io/inflation/_build/html/index.html), proper testing, and it is the process of being [added to conda-forge](https://github.com/conda-forge/staged-recipes/pull/21103).

The name `inflation` is very fitting for our package and we would like to claim it, given that the current package is empty.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current project has no repository as far as I am aware.

The project to replace it has its repository here: https://github.com/ecboghiu/inflation

### Contact and additional research

I have sent an email at michael@terminallabs.com but with no reply. I got the email from https://terminallabs.com/contact-us/. I can send a copy of the sent message to a moderator  if needed.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @ecboghiu, I can confirm the project has no functionality and is therefore considered invalid. Invalid projects are to be deleted but we notify the current owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
