### ISSUE TITLE
PEP 541 Request: clocky

### ISSUE THREAD

**Issue by csm10495** [pypi/support#2390]
### Project to be claimed

`clocky`: https://pypi.org/project/clocky

### Your PyPI username

`csm10495`: https://pypi.org/user/csm10495

### Reasons for the request

I'm working on a new module and have named it clocky since I couldn't find an existing clocky on PyPI... though when trying to upload the module, i get:

         403 The user 'csm10495' isn't allowed to upload to project 'clocky'. See https://pypi.org/help/#project-name
         for more information.

... i can't seem to find any releases or information about why this name is unable to be taken.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

I don't know where the current project is.

My project (that would replace it) is: https://github.com/csm10495/clocky

### Contact and additional research

Google searched for "clocky" python... didn't find anything that looked like a uploaded module.

Searched clocky on pypi... couldn't find anything.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @csm10495, I can confirm the project has no releases and is therefore considered invalid. Invalid projects are to be deleted but we attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by csm10495** [comment]
Thanks!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
