### ISSUE TITLE
PEP 541 Request: blush

### ISSUE THREAD

**Issue by bschroeter** [pypi/support#2391]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/blush

### Your PyPI username

`USER_NAME`: https://pypi.org/user/bschroeter

### Reasons for the request

The original project was published in 2019 with little more than a LICENSE file in the repository. There has been nothing published or developed since and I've been unable to contact the author via an issue on the repository (https://github.com/alvations/blush/issues/1).

There is no email that I can find to contact the author.

The replacement project is a working implementation of an installable python package, as opposed to a lone LICENSE file.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

ORIGINAL = https://github.com/alvations/blush
REPLACEMENT = https://github.com/bschroeter/blush

### Contact and additional research

I've tried to reach out via Github issue, no response.

https://github.com/alvations/blush/issues/1

There is no email that I can find to contact them directly.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @bschroeter, I can confirm the project has no functionality and is therefore considered invalid. Invalid projects are to be removed but we contact the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer which is now complete.
