### ISSUE TITLE
PEP 541 Request: expander

### ISSUE THREAD

**Issue by Jack28** [pypi/support#2395]
### Project to be claimed

`expander`: https://pypi.org/project/expander

### Your PyPI username

`peekabooav`: https://pypi.org/user/peekabooav

### Reasons for the request

It is not clear why `The name 'expander' isn't allowed`.
The name is not part of the Python Standard Library or can be easily mistaken for an existing project or command line argument.
I would like to take the name to host our project.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

You can find our code repository at Github https://github.com/science-computing/expander

There doesn't seem to be an existing claim of the name that could interfere at least not visible to me.

### Contact and additional research

Not applicable

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Jack28** [comment]
Is there a way to know if there is progress or anyone looking into this issue?
I don't want to sound desperate but I'd literally do anything.
Have a great day and if I can help please let me know

**Comment by yeraydiazdiaz** [comment]
Hello @Jack28, the project was placed in the prohibited project names list, a @pypi/warehouse-admins should be able to release the name to you.

**Comment by ewdurbin** [comment]
'expander' released to 'peekabooav' on PyPI.
