### ISSUE TITLE
PEP 541 Request: pax

### ISSUE THREAD

**Issue by akbir** [pypi/support#2408]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pax

### Your PyPI username

`USER_NAME`: https://pypi.org/user/akbir

### Reasons for the request

Hi we are a set of researchers from [UCL DARK](https://dark.cs.ucl.ac.uk) and [Oxford FLAIR](https://foersterlab.com) hoping to publish a repo of research tools for Multi-Agent RL.

The existing package (Pax) which, we'd like to replace,  was uploaded (alpha) in 2003 and has not been updated since. 

We have also tried to reach out to the authors however there email address no longer exists.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Existing Repo: 
(Can not actually find!)

Our Repo: This is currently private and we'd love to share when we do the release - we are keen to have the name available for the official release. I'm happy to share individually with a moderator if necessary

### Contact and additional research

We have also tried to reach out to the authors however there email address no longer exists.

We reached out to lalo@laranja.org

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @akbir, I can confirm the project has a single release with no associated files and is therefore considered invalid. Invalid projects are to be removed but we contact the owner and allow one week for replies before proceeding with the transfer.

**Comment by lalomartins** [comment]
Hi, I'm the original author, you 100% have my blessing to take it over. The project is ancient history and was superseded by ZPT anyway. I'd say in this case there isn't even any point in adding a paragraph about the old project in the ‘if you're looking for…’ style. Best luck with your research.

**Comment by yeraydiazdiaz** [comment]
Thanks for the quick reply @lalomartins, transfer complete.

**Comment by akbir** [comment]
thanks!
