### ISSUE TITLE
PEP 541 Request: sqlfmt

### ISSUE THREAD

**Issue by tconbeer** [pypi/support#2411]
### Project to be claimed

`sqlfmt`: https://pypi.org/project/sqlfmt

### Your PyPI username

`tedconbeer`: https://pypi.org/user/tedconbeer/

### Reasons for the request

This is a follow-up to #1460 (which was opened a year ago).

A timeline of the facts:
1. April 1, 2020: HH-MWB published a completely empty package to the `sqlfmt` name as v 0.0.0. This was invalid from the start, and was blatantly name-squatting.
2.  July 12, 2021: I pushed the [first commit](https://github.com/tconbeer/sqlfmt/commit/50064f4bdfe15bc4fe767d6c031520b98cfd5f97) of my project.
3.  July 20, 2021: I registered sqlfmt.com
4. July 20, 2021: I contacted HH-MWB via the email listed on PyPI, asking to collaborate on the package (email below). I received no reply and emailed again July 26, 2021.
5. [November 8, 2021](https://pypi.org/project/shandy-sqlfmt/#history): I released v0.1.0 of my project under a different (worse) name, [`shandy-sqlfmt`](https://pypi.org/project/shandy-sqlfmt/). This v0.1.0 was already quite functional, and had a valid claim to a name on PyPI. If sqlfmt had not been name-squatted, I would have used sqlfmt as the package name on that date.
6. November 8, 2021: I opened #1460 on that same day. At that time:
    a. the sqlfmt package had only released 0.0.0, which was _completely_ empty, which made it invalid for name-squatting
    b. the package had not had a release in over a year, making it abandoned
    c. the maintainer was unreachable via email, and did not have another method of contact, since the linked github repo was incorrect or private
7. November 24, 2021: HH-MWB released v0.0.1, followed by v0.0.2 on November 25. These releases contained minimal functionality, simply wrapping another popular package, [sqlfluff](https://pypi.org/project/sqlfluff/).
8. December 5, 2021: #1460 was closed, citing the recent releases by HH-MWB.
10. August 3, 2022: I again emailed HH-MWB
9. I've continued to develop and release my project under the shandy-sqlfmt package name. The package has become a very popular CLI, [downloaded over 120k times](https://pepy.tech/project/shandy-sqlfmt) in the past 30 days. I also have a web UI and docs site at [sqlfmt.com](https://sqlfmt.com). The sqlfmt API is also used by the [dbt Cloud IDE](https://www.getdbt.com/blog/new-improved-cloud-ide/#code-formatter). My [sqlfmt repo](https://github.com/tconbeer/sqlfmt) has over 150 stars on Github.
11. HH-MWB has not cut an additional release to his sqlfmt package since v0.0.2, and has never responded to my inquiries.

Given the timeline above, I again assert that:
1. HH-MWB name-squatted on the sqlfmt package from at least April 1, 2020 - November 24, 2021, preventing me from rightfully using it on November 8, 2021.
2. The extremely minimal functionality of the sqlfmt package, coupled with its total inactivity from November 25, 2021 until today, as well as the non-responsiveness of its maintainer, qualify it as an abandoned project. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current sqlfmt project does not link to a public repository; the tarball from the most recent release is [here](https://files.pythonhosted.org/packages/1d/b6/54d9249944d3aa1bb1d36609f0ed1bf777bc6fb5e9203dab4f240e714c57/sqlfmt-0.0.2.tar.gz).
Previously the package linked to https://github.com/HH-MWB/sqlfmt, but that is a 404.
Currently the package lists its PyPI page as its homepage.

My project is located at https://github.com/tconbeer/sqlfmt

### Contact and additional research

HH-MWB's email address from PyPI is <redacted>.
https://github.com/HH-MWB does not include any contact information. That profile does not show any commits in 2022.
A Google search for the username and email address do not turn up anything meaningful, other than the Github profile.

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/705906/202512698-628d2bab-a6c8-4568-a7bb-db98807b4caa.png">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @tconbeer, I agree that the project has very limited functionality but it has _some_ functionality. As such I will start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back soon and proceed with the transfer.

**Comment by tconbeer** [comment]
Thank you, @yeraydiazdiaz !

**Comment by HH-MWB** [comment]
Hi @tconbeer and @yeraydiazdiaz, I just want to clarify something here:
1. The initiative for this package is to build a non-configurable SQL formatting tool that can provide one and only one way to format the SQL query. This idea was inspired by `black`.
2. As SQL is stable in its syntax and no one has reached out for any feature request or reporting bugs, I don't think it's needs to make some random changes just to show I'm maintaining it.
3. I'll be happy to take the ideas and start discussing what could be a better SQL format. However, I don't think it make much sense to reach out and just say "I want to take this name with my project".

**Comment by tconbeer** [comment]
@HH-MWB Thanks for getting back to me. I'd really like to discuss this with you, and I think if you're open to it we can find a solution that would benefit both of us. Can you please email me (my address is visible in the screenshots above) and I can send you a proposal or we can meet to discuss this?

**Comment by HH-MWB** [comment]
> @HH-MWB Thanks for getting back to me. I'd really like to discuss this with you, and I think if you're open to it we can find a solution that would benefit both of us. Can you please email me (my address is visible in the screenshots above) and I can send you a proposal or we can meet to discuss this?

No problem! If you are interested in discussing ideas and suggestions regarding `sqlfmt`, I would be more than happy to communicate with you via email using the address you provided in your original comment. If you already have a proposal you'd like to share, please do not hesitate to send it to me.

However, I would like to let you know that, at this moment, I am not planning to transfer `sqlfmt` as I am still using and maintaining it. Furthermore, some of my colleagues also depend on it, and this tool is functioning well.

Besides, if it's not too much trouble, would you kindly remove my email from this page? I am concerned that leaving it there could lead to my email being harvested and potentially used for spam purposes. Thank you for your understanding!

**Comment by tconbeer** [comment]
I've redacted your email here. I'll reach out next week

**Comment by yeraydiazdiaz** [comment]
Closing as contact has been made.
