### ISSUE TITLE
PEP 541 Request: ezweb

### ISSUE THREAD

**Issue by rtcq** [pypi/support#2426]
### Project to be claimed

`ezweb`: https://pypi.org/project/ezweb

### Your PyPI username

`rtcq`: https://pypi.org/user/rtcq

### Reasons for the request

I was maintaining the project from my old account and wanted to change my username. Since there is no option to do that in PyPI, I created a new account and deleted both the project and my old account. When I wanted to publish the project under the `ezweb` name, there is an error saying it is too similar to a project. what should I do now?

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/rtcq/ezweb

### Contact and additional research

I am the owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @rtcq, a @pypi/warehouse-admins would have to force the creation of the project and assign it to you.

For the record instead of deleting the project you should've added your new account as an owner of the project first, and then delete the old account.

**Comment by ewdurbin** [comment]
'ezweb' created/released to 'rtcq' on PyPI
