### ISSUE TITLE
PEP 541 Request: enchant

### ISSUE THREAD

**Issue by vinay-enchant** [pypi/support#2427]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/enchant

### Your PyPI username

`USER_NAME`: https://pypi.org/user/vinay-enchant

### Reasons for the request

A project named ```enchant``` does not exist on PyPI.  Attempts to upload a project named ```enchant``` results in the following error:

```
         The name 'enchant' isn't allowed. See https://pypi.org/help/#project-name for
         more information.
```

I represent [enchant.com](https://enchant.com) / [@enchant](https://twitter.com/enchant).  We hold several trademarks on the ```enchant``` brand.

We're building language bindings for our API's and would like to use our trademarked name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/enchant/enchant-python

### Contact and additional research

https://pypi.org/project/enchant

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @vinay-enchant, `enchant` was placed in the prohibited project names list, a @pypi/warehouse-admins should be able to release the name to you.

**Comment by ewdurbin** [comment]
'enchant' released to 'vinay-enchant' on PyPI.
