### ISSUE TITLE
PEP 541 Request: qsample

### ISSUE THREAD

**Issue by dpwinter** [pypi/support#2430]
### Project to be claimed

`qsample`: https://pypi.org/project/qsample

### Your PyPI username

`dpwinter`: https://pypi.org/user/dpwinter

### Reasons for the request

A project with the name `qsample` does not exist on PyPi. Attempt to upload a project with this name results in following error:
`The name 'qsample' isn't allowed. See https://pypi.org/help/#project-name for more information.`
I am a research assistent at the RWTH Institute for Quantum Information. We would like to use the name to publish a library for the physics community to allow efficient sampling of quantum error correction protocols.  

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Our project lives here: https://github.com/dpwinter/qsample

### Contact and additional research

Not applicable

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @dpwinter, `qsample` was placed in the prohibited project names list. A @pypi/warehouse-admins should be able to release the project name to you.

**Comment by ewdurbin** [comment]
'qsample' released to 'dpwinter' on PyPI.
