### ISSUE TITLE
PEP 541 Request: layman

### ISSUE THREAD

**Issue by frap129** [pypi/support#2431]
### Project to be claimed

`layman`: https://pypi.org/project/layman

### Your PyPI username

`frap129`: https://pypi.org/user/frap129

### Reasons for the request

`layman` is not an existing package, it is not similar in name to any package I can find, and it is not a part of the standard library. Unless there is some reason the name has been forbidden, I would like to use it for my project. 

Attempting to upload the package with twine returns
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'layman' isn't allowed. See https://pypi.org/help/#project-name for more
         information.
```

### Source code repositories URLs

https://github.com/frap129/layman

### Contact and additional research

I have searched PyPi for `layman` with no results or anything similar in name, as well as the standard library's web page. Searching Google, Bing, and Qwant for `python layman` only returns tutorials for "laymen" in the sense of someone unfamiliar with a subject.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by frap129** [comment]
Still waiting on this.

**Comment by yeraydiazdiaz** [comment]
Hi @frap129, `layman` was placed in the prohibited project names list. A @pypi/warehouse-admins should be able to release the project name to you.

**Comment by ewdurbin** [comment]
'layman' released to 'frap129' on PyPI.

**Comment by hartwork** [comment]
For the record, "layman" is also this notable Python-based software:
- https://sourceforge.net/projects/layman/
- https://wiki.gentoo.org/wiki/Layman
