### ISSUE TITLE
PEP 541 Request: asqlite

### ISSUE THREAD

**Issue by Rapptz** [pypi/support#2434]
### Project to be claimed

`asqlite`: https://pypi.org/project/asqlite

### Your PyPI username

`Rapptz`: https://pypi.org/user/Rapptz

### Reasons for the request

This package is actually an upload of my own package, which I had not uploaded to PyPI before. Authorship is set to me in the project page, but ideally I would rather claim the project than a third party.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/Rapptz/asqlite

### Contact and additional research

I couldn't find any contact information for the original author. I tried finding them on GitHub and Discord to no avail though. I could not find a publicly listed email address.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Rapptz, while I understand this is your code the project's description clearly states it's a fork which forces me to star a reachability process. This can take up to 6 weeks but hopefully the owner will reply soon and we can proceed with the transfer.

**Comment by Rapptz** [comment]
Thanks for initiating the process. The user has transferred ownership to me.
