### ISSUE TITLE
PEP 541 Request: ripe.atlas.dyndns

### ISSUE THREAD

**Issue by eakkutlu** [pypi/support#2436]
### Project to be claimed

`ripe.atlas.dyndns` : https://pypi.org/project/ripe.atlas.dyndns

### Your PyPI username

`robert-ripencc` : https://pypi.org/user/robert-ripencc

### Reasons for the request

Project has been mistakenly forgotten by us, and taken over by a security researcher to demonstrate "dependency confusion" attack. But after that the researcher deleted the package before transferring the ownership to us, and when we try now we are not able to.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/RIPE-NCC/atlas-dyndns/

https://pypi.org/project/ripe.atlas.dyndns/

### Contact and additional research

We are already in contact with the owner of the project via our private bug bounty program.
But since he deleted, he's also unable to help us with this request.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @eakkutlu, `ripe.atlas.dyndns` was placed in the prohibited project names list, a @pypi/warehouse-admins should be able to release the project name to you.

**Comment by eakkutlu** [comment]
Hello @yeraydiazdiaz, thank you for your update. Should I contact warehouse-admins, or are they also a part of this issue?

**Comment by ewdurbin** [comment]
'ripe-atlas-dyndns' released to 'robert-ripencc'.
