### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by llango** [pypi/support#2448]
### PyPI Username

ai.rontom

## Lost 2FA authentication app or security token
My computer's hard drive is broken and the contents stored in.pyirc are missing. The phone had already been replaced. I know my username and password. I can't find my recovery codes. 

You can see my information under this username(ai.rontom):

Author: [llango](mailto:rontomai@gmail.com)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
