### ISSUE TITLE
PEP 541 Request: every

### ISSUE THREAD

**Issue by aleksve** [pypi/support#2451]
### Project to be claimed

`every`: https://pypi.org/project/every

### Your PyPI username

`aleksve`: https://pypi.org/user/aleksve

### Reasons for the request

The currently uploaded project has no functionality and contains no working source code. It was labeled as "Reserved for future" in December 2021, and nothing happened since. The link to the project homepage returns a 404. I believe this makes it [invalid per PEP541](https://peps.python.org/pep-0541/#invalid-projects), and the project I want to replace it with will be a better contribution to the community. 

The current owner did not reply to my e-mail about transfer of ownership. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

* The currently uploaded project has no source code
* The source code of the project I intend to publish: https://github.com/aleksve/ischedule/tree/every

### Contact and additional research

* E-mailed the current owner on Nov 25, 2022, no reply received.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by aleksve** [comment]
Many if not all [projects assigned to the current owner](https://pypi.org/user/voilalex/) are frivolous. Looks like a mass squatting case.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project was name squatting which is not allowed, transfer complete.

**Comment by aleksve** [comment]
Thanks @yeraydiazdiaz !
