### ISSUE TITLE
PEP 541 Request: SemPy

### ISSUE THREAD

**Issue by amueller** [pypi/support#2457]
### Project to be claimed

`sempy`: https://pypi.org/project/sempy

### Your PyPI username

`t3kcit`: https://pypi.org/user/t3kcit

### Reasons for the request

Abandoned project, can't reach maintainer. The package is clearly abandoned, and the last activity has been over 11 years ago, and the package is labeled as "in pre-alpha state".

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The link to the original package is a dead link to bitbucket.
The project that we want to replace it with is not yet published.

I'm not sure if this satisfies the requirements of 541. The replacing project will be published by Microsoft, and the naming of the project depends on the availability of the name on pypi.

### Contact and additional research

I have mailed the owner twice over several weeks at the email address listed on the pypi package page.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by amueller** [comment]
Any news?

**Comment by yeraydiazdiaz** [comment]
Hello @amueller, I will now start the reachabilty process for your request which can take up to 6 weeks.

**Comment by amueller** [comment]
@yeraydiazdiaz Thank you!

**Comment by amueller** [comment]
@yeraydiazdiaz any news?

**Comment by ambv** [comment]
Since Yuray seems to no longer be involved, we will restart the reachability process.

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate this request and make a recommendation on the outcome and actions to be taken. Final determination will be made by the PyPI Administrators when our process is complete.

**Comment by encukou** [comment]
We could not reach the owner, and we consider the project abandoned per
[PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).
We recommend that the PyPI Administrators assign t3kcit as the new
owner of "sempy".

**Comment by ewdurbin** [comment]
`Owner` role on `sempy` Project granted to `t3kcit`
