### ISSUE TITLE
PEP 541 Request: figaro

### ISSUE THREAD

**Issue by sterinaldi** [pypi/support#2458]
### Project to be claimed

`figaro`: https://pypi.org/project/figaro

### Your PyPI username

`SteRinaldi`: https://pypi.org/user/SteRinaldi

### Reasons for the request

Dear moderators,

The `figaro` project currently published on PyPI has been last released in February 2014 and the listed homepage points to a generic empty landing page. The package itself contains only a `main.py` file that just prints very basic informations on the project and nothing more. Moreover, the description states that the project is in *concept stage*, and it does not contain the code for the proposed features. I believe that this makes the project both abandoned and invalid due to name squatting.

On the other hand [FIGARO](https://github.com/sterinaldi/FIGARO), the project of the same name I would like to publish, is an active project which is starting to gain popularity among the gravitational wave physics and astrophysics community.
We published two papers using this code ([paper 1](https://academic.oup.com/mnrasl/article-abstract/517/1/L5/6692889?redirectedFrom=PDF) and [paper 2](https://arxiv.org/abs/2209.07416)) and others are in preparation.
The same code is also being used by colleagues, some of which contacted me because the code they installed via `pip install figaro` was not working: the code was ribozz's.

I am therefore asking the maintainers to remove the existing package in order to free the name.

Kind regards,
Stefano Rinaldi

### Maintenance or replacement?

Replacement

### Source code repositories URLs

No repository available for ribozz's `figaro`. Source code downloaded from here: https://pypi.org/project/figaro/#files

My repository: https://github.com/sterinaldi/FIGARO

### Contact and additional research

![Screenshot 2022-12-02 at 21 50 45](https://user-images.githubusercontent.com/56389680/205384068-9441fa0b-41d6-4646-9385-cce5b94a64f8.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @sterinaldi, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
