### ISSUE TITLE
PEP 541 Request: mdal

### ISSUE THREAD

**Issue by runette** [pypi/support#2462]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/mdal

### Your PyPI username

`USER_NAME`: https://pypi.org/user/runette

### Reasons for the request

I am the maintainer of the Python Bindings for the MDAL project - part of the OSGEO collective. https://www.mdal.xyz/

We are in the process of publishing the bindings in PyPI. We wanted to use the mdal name - but that was taken by a small personal project.

We contacted the owner of the existing / previous package and he was happy to give up the name and removed the package (the email conversation is attached below.

We would like to take over the name

### Maintenance or replacement?

Replacement

### Source code repositories URLs

MDAL Project : https://github.com/lutraconsulting/MDAL

previous package : https://github.com/ynny-github/mdal

### Contact and additional research

I have talked to the previous owner - the conversation is as follows

[Gmail - PYPI Project MDAL.pdf](https://github.com/pypa/pypi-support/files/10167167/Gmail.-.PYPI.Project.MDAL.pdf)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @runette, there is no `mdal` project in PyPI, however, it's likely you are not able to upload it due the name being very close to another project `mdai`. I believe a @pypi/warehouse-admins would be able to bypass this limitation and release the name to you.

**Comment by runette** [comment]
There was an mdal but the previous owner deleted it and I assumed that the problem was that the governance was  not allowing the name to be re-used. 

How do I access @pypi/warehouse-admins ?

**Comment by yeraydiazdiaz** [comment]
You don't need to do anything else, admins monitor pypi-support and will release the name soon.

**Comment by ewdurbin** [comment]
'mdal' released to 'runette'.
