### ISSUE TITLE
PEP 541 Request: sphinxcontrib-openapi

### ISSUE THREAD

**Issue by stephenfin** [pypi/support#2463]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/sphinxcontrib-openapi

### Your PyPI username

`USER_NAME`: https://pypi.org/user/stephenfin

### Reasons for the request

I help maintain the *sphinx-contrib* organisation on GitHub. We had [a request](https://github.com/sphinx-contrib/github-administration/issues/30) a number of months ago to help maintain the sphinx-contrib/openapi project. I requested that they reach out to the author, https://github.com/ikalnytskyi, directly, which they [duly did](https://github.com/sphinx-contrib/openapi/issues/128), however we haven't heard anything back since. The project's dependencies are rather out-of-date but PRs have been proposed to fix these and it's simply a case of merging these. In the absence of https://github.com/ikalnytskyi I'd like to take over maintenance of this project and explore adding additional maintainers myself in short order. Since https://github.com/ikalnytskyi was happy to move the project to the shared GitHub organisation years ago, I suspect they would be okay with this.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/sphinx-contrib/openapi

### Contact and additional research

- https://github.com/sphinx-contrib/github-administration/issues/30
- https://github.com/sphinx-contrib/openapi/issues/128

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @stephenfin, it looks like @ikalnytskyi is active in GitHub, hopefully he can add you as a maintainer or owner.

**Comment by stephenfin** [comment]
Hey, I've emailed Ihor and pinged him a few times via GitHub mentions. No luck, unfortunately. I have been able to release packages since but only because he had already configured a GitHub Workflow with a PyPI token. Not a great long term strategy to be relying on though.

**Comment by ambv** [comment]
Since Yuray seems to no longer be involved, we will start the reachability process on our end.

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate this request and make a recommendation on the outcome and actions to be taken. Final determination will be made by the PyPI Administrators when our process is complete.

**Comment by ikalnytskyi** [comment]
Hello everyone,

I'm sorry for being unreachable for so long. Unfortunately, my priorities shifted, and I have neither desire nor time to maintain this project at the moment.

As I can see, there are no issues with publishing new releases, as the token I previously set up is still working fine.

Regardless, I just added @stephenfin as a co-owner on PyPI.

**Comment by stephenfin** [comment]
I got that invite. Thanks, @ikalnytskyi. I think we can close this now.
