### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by natashabatalha** [pypi/support#2467]
### PyPI Username

`natashabatalha`

### Reason for request

Lost access to email address. 

New username is `natasha.e.batalha`  
`pandexo.engine` https://test.pypi.org/project/pandexo.engine/ 
should be under `natasha.e.batalha` not the old account `natashabatalha`. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hi @natashabatalha. The user account is currently associated with an @gmail.com address. I'm also not finding a user account with the name `natasha.e.batalha`.

Can you please email support@pypi.org from the address you'd like to use for your account, including a link to this issue?
