### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by xulei890817** [pypi/support#2470]
### PyPI Username

wobushi110

### Reason for request

Lost access to email address
the old email is an Enterprise mail address
and the company has already shutdown and the address can not be accessed again

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please contact support@pypi.org from the address you would like associated with the account. Include a link to this issue for reference.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account and the requested email address, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. Email has been updated as requested for the account. You can proceed with a standard password reset to regain access.
