### ISSUE TITLE
PEP 541 Request: djehuty

### ISSUE THREAD

**Issue by roelj** [pypi/support#2471]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/djehuty

### Your PyPI username

`USER_NAME`: https://pypi.org/user/roelj

### Reasons for the request

I would like to publish [our project](https://github.com/4TUResearchData/djehuty) called `djehuty` to PyPi.
Please note this is my first time interacting with this procedure. If there is anything I should have done, then please let me know.

I believe the project has been abandoned, because:
1. The [project homepage](https://github.com/xica/djehuty) (Github) is gone.
2. The last release was on Oct 8, 2014
3. On Nov 16, 2022 I contacted the maintainer ([Satoshi Ebihara](https://github.com/succhiello)) at two e-mail addresses found in the Git commit log of a package by the same maintainer. (Last activity is 2017)

If I am mistaken and the project is in use, then I would like to withdraw this request, because I do not want to interfere with packages that are in use. It would, however, be great to not have to explain why the project name doesn't match the name on PyPi.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current project:
https://github.com/xica/djehuty (no longer exists)

The one I intent to publish in its place:
https://github.com/4TUResearchData/djehuty

### Contact and additional research

On Wednesday Nov 16, 2022 I contacted the maintainer ([Satoshi Ebihara](https://github.com/succhiello)) at two e-mail addresses found in the Git commit log of a package by the same maintainer.

I haven't received a reply.
I redacted the e-mail addresses to prevent misuse.

![Screenshot from 2022-12-12 15-07-33](https://user-images.githubusercontent.com/1129198/207066696-99ac7b72-7375-4538-bcf0-3edba60f8e8b.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by roelj** [comment]
On Dec 12, 2022 I contacted the general e-mail address of the company to which this repository seemed to belong.
I haven't received a reply.

Today, Jan 3, 2023, I contacted the company via their contact form on the website. I will await a reply.

Is there anybody from PyPi who could give a timeline on a possible resolution? Thank you!

**Comment by roelj** [comment]
As another follow-up: I haven't received a reply from my attempt to contact the company on Jan, 3, 2023.

**Comment by roelj** [comment]
As another follow-up: I haven't received a reply from my attempt to contact the company on Jan, 3, 2023.
Is there anybody from PyPi who could give a timeline on a possible resolution? Thank you!

**Comment by yeraydiazdiaz** [comment]
Hi @roelj, I will now start the reachability process for your request which can take up to 6 weeks.

**Comment by roelj** [comment]
Hi @yeraydiazdiaz Thank you!

**Comment by yeraydiazdiaz** [comment]
Tagging GitHub user @succhiello who has https://github.com/succhiello/djehuty in his repository list along with others with similar names.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
