### ISSUE TITLE
File Limit Request: onnx-clip - 400 MB

### ISSUE THREAD

**Issue by MBichurin** [pypi/support#2473]
### Project URL

https://pypi.org/project/onnx-clip/

### Does this project already exist?

- [X] Yes

### New Limit

400 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project contains everything required for the OpenAI's CLIP, but in ONNX, so that anyone can use CLIP without PyTorch. It is active since yesterday.

The README on the page explains how easy it is to use.

The problem is in the ONNX weights file which takes most of the memory space. When compressed, it remains almost the same size. (393MB -> 392MB). Currently, a place-holder is uploaded to PyPi instead.

It doesn't bundle other packages. The example data is present, but it is compressed and takes only 2MB.

### Reasons for the request

I don't expect the project size to increase in the future, as the weights are fixed and take most of the memory required.

The reason for the request is to fix this package so that anyone can use the actual model without PyTorch requirement.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Hello, is there a public repository associated with the project?

**Comment by MBichurin** [comment]
Hi @ewdurbin ! Thank you for your response

Yes, there is: https://github.com/lakeraai/onnx_clip
