### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Phornee** [pypi/support#2475]
### PyPI Username

'phornee'

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hello, I am noting that this user has a successful login using 2FA as of ~6 hours ago.

The user `phornee` also has valid recovery codes generated as of 2022-08-11 which should be used to regain access to the account in this scenario.
