### ISSUE TITLE
Project Limit Request: Gensim - 15 GB

### ISSUE THREAD

**Issue by piskvorky** [pypi/support#2481]
### Project URL

https://pypi.org/project/gensim/

### Does this project already exist?

- [X] Yes

### New limit

15

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Continued from https://github.com/pypa/pypi-support/issues/1315

We expect 15 GB to last us several years – we release Gensim once/twice a year, and each release is 500MB.

### How large is each release?

~500 MB total.

### How frequently do you make a release?

2x a year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Total size limit increased to 15.0 GiB
