### ISSUE TITLE
PEP 541 Request: iotics-grpc-client

### ISSUE THREAD

**Issue by KarimIotic** [pypi/support#2482]
### Project to be claimed

https://pypi.org/project/iotics-grpc-client/

### Your PyPI username

https://pypi.org/user/Iotics_Maintainer/

### Reasons for the request

Our former collegue Miroslav Sommer left the company and forgot to change the ownership of this project.
We are using now a new generic profile "Iotics_Maintainer" to own our projects and maintain them. This profile is associated with our admin account at admin@iotics.com to avoir repeating the same mistake.
Thank you for your help!

PS: If required, you can reach out to me via email at karim.tobich@iotics.com.

Karim Tobich
Security Officer

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/Iotic-Labs/iotics-grpc-client-py

### Contact and additional research

We did try to reach out to our former collegue but we where not successful.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Looks like this was transferred internally since `Iotics_Maintainer` is already an owner.
