### ISSUE TITLE
Can't change release description

### ISSUE THREAD

**Issue by artanokhov** [pypi/support#2485]
**Describe the issue**
I'm the maintainer of [openvino](https://pypi.org/project/openvino/) and [openvino_dev](https://pypi.org/project/openvino_dev) projects. 

Can you please help with changing description for
* https://pypi.org/project/openvino/2022.3.0/
* https://pypi.org/project/openvino_dev/2022.3.0/

We uploaded them with "pre-release note" we use for pre-releases. But for this 2022.3.0 release it should not be present.

I've tried to remove files at [test.pypi.org](https://test.pypi.org/project/openvino/2022.3.0/) and upload wheel with fixed description, but it doesn't help.

Could you please help and describe how can we update our release description for releases mentioned above?
Thanks in advance

**Comment by miketheman** [comment]
Hello!
My understanding is that you're describing the rendered content on the page like this one: https://pypi.org/project/openvino/2022.3.0/ - specifically the block that looks like this one?

<img width="791" alt="Screenshot 2023-01-04 at 2 22 50 PM" src="https://user-images.githubusercontent.com/529516/210633114-e83fac4f-52ce-4952-b933-3cee4d03e4a6.png">

The content in the file is part of the package's metadata - [described here in more detail](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata).

The only way I can currently think of in changing that content is to upload a new version of the package - possibly a post-release version (see [relevant PEP-440 section for more](https://peps.python.org/pep-0440/#post-releases)).

**Comment by artanokhov** [comment]
>specifically the block that looks like this one?
Yes, that's right.

We know about common way with pushing new release to update the meta information - but it will update also the version of the release. We would just like to avoid this for this specific release.

By the way, do you have any plans to implement this feature?
https://github.com/pypi/warehouse/issues/4816

Seems like it's not only 1-time request from your community.

**Comment by ewdurbin** [comment]
We do not have plans to implement metadata modification at this time.
