### ISSUE TITLE
PEP 541 Request: interceptor

### ISSUE THREAD

**Issue by nanx64** [pypi/support#2492]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/interceptor

### Your PyPI username

`USER_NAME`: https://pypi.org/user/nanx64

### Reasons for the request

I would like to publish a python lib for control flow intercepting, it will be used as a dependency of [my other _dag_ dataflow programming library](https://github.com/nanx64/dag).
I am currently using it on multiple data-processing-heavy projects of mine.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

New project repo (my project): https://github.com/nanx64/interceptor
Old project repo (abandoned project): https://github.com/zmsmith/interceptor

### Contact and additional research

I tried contacting the user over the email listed on PyPI: zachmsmith@gmail.com
The project has been inactive / abandoned since 2012 - there is only 1 version available: 0.0.1

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @nanx64, the project has almost no functionality so I'm considering it invalid. As such I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by carpetmaker** [comment]
Hey @yeraydiazdiaz, thank you for your effort! Are there any update(s) on this? If there were no replies from the owner whatsoever, can we proceed with the transfer?

**Comment by nanx64** [comment]
Hey @yeraydiazdiaz, thank you for your effort(s)! Is there any update on this? If there was no response from the current owner whatsoever, can we proceed with the transfer?

**Comment by nanx64** [comment]
Hey @yeraydiazdiaz, thank you for your effort(s)! Is there any update on this? If there was no response from the current owner whatsoever, can we proceed with the transfer?

**Comment by encukou** [comment]
We could not reach `zmsmith`, and we consider the project abandoned per
[PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).
We recommend that the PyPI Administrators assign nanx64 as the new
owner of "interceptor".

**Comment by ewdurbin** [comment]
`Owner` role on `interceptor` Project granted to `nanx64`
