### ISSUE TITLE
PEP 541 Request: hapy

### ISSUE THREAD

**Issue by afedynitch** [pypi/support#2495]
### Project to be claimed

`hapy`: https://pypi.org/project/hapy

### Your PyPI username

`a_fedynitch-121.a `: https://pypi.org/user/a_fedynitch-121.a

### Reasons for the request

The project name `hapy` is invalid as defined [here](https://peps.python.org/pep-0541/#invalid-projects) since it is clearly `name squatting`. All projects by the user [`pyndg`](https://pypi.org/user/pyndg/) are invalid and should be considered to be removed.

### Maintenance or replacement?

None

### Source code repositories URLs

The current project has no code. We plan to rename our current project [`impy`](https://github.com/impy-project/impy) into `hapy` if we manage to obtain the name.

### Contact and additional research

The owner didn’t leave any contact info and doesn’t seem to be a github user.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
