### ISSUE TITLE
PEP 541 Request: kilosort

### ISSUE THREAD

**Issue by marius10p** [pypi/support#2498]
### Project to be claimed

`kilosort`: https://pypi.org/project/kilosort

### Your PyPI username

`marius10p`: https://pypi.org/user/marius10p

### Reasons for the request

We think someone is holding the "kilosort" name because we cannot create a new package with that name. 

``` 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/           
         The name 'kilosort' isn't allowed. See https://pypi.org/help/#project-name
         for more information.  
```

There is only one software package called kilosort and I am the main developer for it:

https://github.com/MouseLand/Kilosort
https://proceedings.neurips.cc/paper/2016/hash/1145a30ff80745b56fb0cecf65305017-Abstract.html

### Maintenance or replacement?

None

### Source code repositories URLs

original:   N/A
new:        https://github.com/MouseLand/Kilosort

### Contact and additional research

We cannot determine the owner, or reason why the name is not allowed. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @marius10p, `kilosort` was placed in the prohibited project names list by a @pypi/warehouse-admins, I'll place it in the queue and they should be able to release the project to you shortly.

**Comment by carsen-stringer** [comment]
thank you so much for your help with this!

**Comment by marius10p** [comment]
Is there any update on this? Thanks for your help.

**Comment by ewdurbin** [comment]
Name released to marius10p on PyPI.
