### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by efimk-lu** [pypi/support#2502]
### PyPI Username

lumigo

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The user `lumigo` on PyPI has valid recovery codes generated as of 2022-07-03. These recovery codes should be used to regain access to the account.

**Comment by efimk-lu** [comment]
Hi, thank you for your response. Unfortunately, we don't have these recovery codes anymore. What can we do?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
