### ISSUE TITLE
Project Limit Request: pikepdf - 20 GB

### ISSUE THREAD

**Issue by jbarlow83** [pypi/support#2507]
### Project URL

https://pypi.org/project/pikepdf/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Library to read and write PDFs. Provides Pythonic bindings to the C++ QPDF library. 

Designated a "critical" project.

Active since 2017.

### How large is each release?

~100 MB total.

(3 operating systems) * (3 supported processor architectures) * (4-7 Python versions supported)  = ~30 wheels per release, each weighing in about 3 MB.

All wheels bundle libqpdf compiled for the target platform. This library is typically ~5 MB uncompressed depending on the platform, and is the main reason for the wheel size. Recent versions of this file are not usually installed by users so bundling is necessary. pybind11 is used for bindings, which does cannot use the (semi-)stable ABI, so the number of wheels cannot be reduced.

Windows wheels also bundle the relevant MSVC runtime required by libqpdf.

No example data is included. No other Python packages are included. 

Third party binaries are stripped. Old releases did not have stripped binaries, so some of these wheels are larger (~10 MB per wheel).

### How frequently do you make a release?

About once a month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the report @jbarlow83 :wave:
I've set the project limit for `pikepdf` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size, and maybe evaluate techniques like https://docs.python.org/3/c-api/stable.html for reducing the amount of wheels, hopefully it helps!
Have a nice week :)
