### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pmitros** [pypi/support#2513]
### PyPI Username

pmitros

### Reason for request

I lost access to my email address from my old job.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please contact support@pypi.org including the old address and a link to this issue. You should send the email from the new address you wish for the account to be associated with. You'll then be provided with instructions for verification.

**Comment by pmitros** [comment]
Thank you. I had done so at the time I filed this ticket (since I saw a similar comment on older tickets).

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account and the requested email address, please read the instructions and reply to proceed with recovery.
