### ISSUE TITLE
PEP 541 Request: academy

### ISSUE THREAD

**Issue by alphazwest** [pypi/support#2515]
### Project to be claimed

`academy`: https://pypi.org/project/academy

### Your PyPI username

`alphazwest`: https://pypi.org/user/alphazwest

### Reasons for the request

I would like to register and upload a package under the name `academy`. I am receiving the following error while trying to do so:

`The name 'academy' isn't allowed. See https://pypi.org/help/#project-name for more information.`

As far as I am aware, this error is displayed when there is a naming conflict with an existing package. A search of the PyPI.org registry and an attempted discovery of the direct project URL for such a project (https://pypi.org/project/academy/) reveals there is no such project. Additionally, I've attempted to `pip install academy` to which the following message is displayed:

```
ERROR: Could not find a version that satisfies the requirement academy (from versions: none)
ERROR: No matching distribution found for academy
```

I believe this request falls under PEP541 category of "Invalid Projects" as it meets the following criteria:

`- project is name squatting (package has no functionality or is empty)`

I hereby request my account be assigned the project `academy` such that I can upload my source code such that I am both the owner and maintainer of the project from here on.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

No source code is discoverable for the current project if one exists.
The source code for my project is located:
- PyPI here: [https://pypi.org/project/akademy/](https://pypi.org/project/akademy/) 
- GitHub: [https://github.com/alphazwest/akademy/](https://github.com/alphazwest/akademy/)

### Contact and additional research

I was unable to determine the possible owner of such a project and therefore have made no attempts at contact.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by alphazwest** [comment]
Following up on this -- happy to provide any additional information to make the process easier. Still getting the following error message when trying to upload the current project `akademy` under the desired (seemingly un-used, perhaps squatted, name) `academy`:

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'academy' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

**Comment by yeraydiazdiaz** [comment]
Hi @alphazwest, `academy` was placed in the prohibited project names list by a @pypi/warehouse-admins, I'll put it in the queue and they should be able to release it to you soon.

**Comment by ewdurbin** [comment]
Released to alphazwest on PyPI.

**Comment by gpauloski** [comment]
Hi @alphazwest, do you plan to publish to `academy`? If not, I'd like to use it to publish a package!
