### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by traviswheeler** [pypi/support#2517]
### PyPI Username

traviswheeler

### Reason for request

Lost 2FA authentication app or security token. When I upgraded to my new phone, I apparently didn't set up pypi in my authenticator. Also, it seems that I didn't set up an alternative method (like sms). That was dumb.

You can find me at wheelerlab.org, also https://www.pharmacy.arizona.edu/directory/profile/travis-john-wheeler-phd. The repo I'm trying to address right now is https://pypi.org/project/polyA/, which is tied to my group's github repo (https://github.com/TravisWheelerLab/polya). 

Thanks in advance for your help.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
