### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by freeloki** [pypi/support#2519]
### PyPI Username

ardic

### Reason for request

Lost 2FA authentication app or security token

My mail address is info@ardictech.com

Thanks in advance,

Best regards,

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Thespi-Brain** [comment]
Hi @freeloki,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by freeloki** [comment]
Hello @Thespi-Brain 
Thanks for the support. I logged the account and renewed 2FA. Best regards.

**Comment by Thespi-Brain** [comment]
Hi @freeloki,

Wonderful to hear that! Closing this issue.
