### ISSUE TITLE
PEP 541 Request: devpy

### ISSUE THREAD

**Issue by stefanv** [pypi/support#2521]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/devpy

### Your PyPI username

`USER_NAME`: https://pypi.org/user/sjvdwalt

### Reasons for the request

For quite a while now, SciPy development takes place via tool called `dev.py`. Recently, we generalized this tool into [devpy](https://github.com/scientific-python/devpy) for use by multiple projects; e.g., it is being used by NumPy, scikit-image, and soon others.

We would like to make the package available on PyPi, but the `devpy` package already exists.
The [last commit](https://github.com/sametmax/devpy/commit/66a150817644edf825d19b80f644e7d05b2a3e86) to that package was in March 2017.
None of the forks on Github have commits after 2017.
According to Github, there is only [one other repository](https://github.com/ksamuel/smit) dependent on it, last committed to in 2017.
A further Github code search only yielded the package import in datasets (e.g., pypi metadata dumps), not in active code.

The name is important to us because of its shared heritage with the SciPy tool. Since the package on PyPi is abandoned, we hope to reclaim it.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/scientific-python/devpy

### Contact and additional research

I tried to reach the owner via their commit email, as well as via [a Github issue](https://github.com/sametmax/devpy/issues/17), but have received no response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by stefanv** [comment]
It's been two weeks, so just a gentle ping to see if this has been seen by anyone.

**Comment by jarrodmillman** [comment]
Any update?

**Comment by stefanv** [comment]
I received the following email from the package owner (happy to share the full email with headers and all for verification):

```
From: lesametlemax
To: Stefan van der Walt
Subject: Re: Ownership of `devpy` package on pypi
Date: Wed, 22 Feb 2023 12:11:47 -0500

Hello,

Yes, I no prob.

Just tell me how to do that.

On 14/10/2022 19:55, "Stefan van der Walt" <stefanv@berkeley.edu> wrote:
> Dear sametmax,
> 
> We are busy packaging a tool, called dev.py, for configuring and building packages in the Scientific Python ecosystem (https://scientific-python.org).  This includes libraries like NumPy, SciPy, and scikit-image.
> 
> We would like to publish it under the name `dev.py` on pypi, but because the name is so similar to your package, we can't.
> 
> Since your project is inactive, would you consider giving us ownership to `devpy` on pypi?
> 
> Thank you for your consideration.
> 
> Best regards,
> Stéfan
```

I sent follow-ups on February 11 and 22, so far without another response.

**Comment by lwasser** [comment]
heya @pradyunsg ! i see that you've contributed to this repo before but also know that you have 8billion things to do. Who would be responsible for allowing ownership of a package name on pypi given there is approval from the developer / owner of the original devpy name. many thanks for the guidance here. :)

**Comment by stefanv** [comment]
I just received the following from the package owner:

> I changed my mind. I may need this name later.
>
> Have a nice day

Given them rescinding permission and the lack of response from pypi, I will close the issue and rename the package.

**Comment by stefanv** [comment]
The package has been renamed to [spin](https://github.com/scientific-python/spin)
