### ISSUE TITLE
File Limit Request: squishtest - 150 MB

### ISSUE THREAD

**Issue by lpqlpq** [pypi/support#2522]
### Project URL

https://pypi.org/manage/project/squishtest/

### Does this project already exist?

- [X] Yes

### New Limit

150MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

no

### Reasons for the request

package is too large

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @lpqlpq :wave: I checked the project on pypi and testpypi and I couldn't find it. Remember you need to create the project first, even if it's with a 0.0.0 version of an empty package.

Also, for context we really need to know about the project, please edit the 'About the project' so we can learn about 'squishtest'

Cheers!

**Comment by cmaureir** [comment]
Gentle ping @lpqlpq so you can provide the project's information.
Thanks!
