### ISSUE TITLE
PEP 541 Request: night

### ISSUE THREAD

**Issue by synchronizing** [pypi/support#2523]
### Project to be claimed

`night`: https://pypi.org/project/night

### Your PyPI username

`synchronizing`: https://pypi.org/user/synchronizing

### Reasons for the request

Package was deleted from the original user on #1947, but it remains locked. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: N/A
Replacement: https://github.com/synchronizing/night (will release as beta)

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @synchronizing, `night` was placed in the prohibited project names list by a @pypi/warehouse-admins, I'll put it in the queue and they should be able to release it to you soon.

**Comment by synchronizing** [comment]
Awesome, thank you @yeraydiazdiaz.

**Comment by synchronizing** [comment]
Hey @yeraydiazdiaz. The link to `pypi/warehouse-admins` is no longer working. Do you have a new link to keep track of the ticket? Thanks.
