### ISSUE TITLE
PEP 541 Request: gamera

### ISSUE THREAD

**Issue by FriedrichFroebel** [pypi/support#2524]
### Project to be claimed

`gamera`: https://pypi.org/project/gamera/

### Your PyPI username

`FriedrichFroebel`: https://pypi.org/user/FriedrichFroebel/

### Reasons for the request

The project currently has only one old binary Windows release file from 2012 for Python 2.7.

In the upstream repository, there is still ongoing development (https://github.com/hsnr-gamera/gamera-4/commits/master), so users would greatly benefit from the PyPI package being up-to-date as well (and having source distributions). This would include support for Python 3 and other operating systems as well.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The general download page is https://gamera.informatik.hsnr.de/download/index.html.

The current project appears to be a custom build of the deprecated Python 2 project at https://github.com/hsnr-gamera/gamera-3, while the intended replacement is the maintained Python 3 project at https://github.com/hsnr-gamera/gamera-4 (see above download page as well).

### Contact and additional research

There is no indication on how to contact the current project owner *Glass.Cube*. All links point to the upstream project, while the maintainers are not aware of the existing package: https://github.com/hsnr-gamera/gamera-4/issues/65#issuecomment-1385335936

In the aforementioned issue, the upstream maintainers are okay with me tackling this topic.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by FriedrichFroebel** [comment]
Are there any updates on this? It seems like the 6 weeks turned into 7 months.

**Comment by ambv** [comment]
Since Yuray seems to no longer be involved, we will restart the reachability process.

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate this request and make a recommendation on the outcome and actions to be taken. Final determination will be made by the PyPI Administrators when our process is complete.

**Comment by encukou** [comment]
We could not reach the owner, and we consider the project abandoned per
[PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).
We recommend that the PyPI Administrators assign FriedrichFroebel as the new
owner of "gamera".
