### ISSUE TITLE
PEP 541 Request: Kconfiglib

### ISSUE THREAD

**Issue by carlescufi** [pypi/support#2526]
### Project to be claimed

`Kconfiglib`: https://pypi.org/project/kconfiglib

### Your PyPI username

`zephyr-project`: https://pypi.org/user/zephyr-project/

### Reasons for the request

The original author of the widely used library Kconfiglib is no longer active or reachable. 
Since the Zephyr Project is a heavy user of Kconfiglib we have volunteered to take over the project and maintain it. In order to avoid having to rename it it would be great if we could take over the PyPI package.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current project: https://github.com/ulfalizer/Kconfiglib
Future home: https://github.com/zephyrproject-rtos/Kconfiglib

### Contact and additional research

We have tried contacting him for nearly 3 years using every means possible to no avail. This includes email, professional telephone number, GitHub mentions and even his personal phone number.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sjg20** [comment]
Just to add my support here as I have been trying to contact the original author also. There are unanswered PRs going back >2 years

https://github.com/ulfalizer/Kconfiglib/pulls

I have a PR that was raised a year ago.

https://github.com/ulfalizer/Kconfiglib/pull/112

This is a very useful project and it is important to move it to a new owner. We have identified someone is willing and able to maintain it:

https://github.com/jackrosenthal

Without this request being approved our only option is to rename the package, which will create a lot of confusion.

**Comment by carlescufi** [comment]
Dear pypi maintainers, can we get an update on this request, please?

**Comment by marc-hb** [comment]
I didn't find any "escalation" process at https://pypi.org/help/#project-name-claim

There is however a link to the obsolete distutils-sig mailing list: https://mail.python.org/archives/list/distutils-sig@python.org/thread/TINMM5LQKQTTJDVGC224RMG7JGPXL4MQ/

I think it has been moved to https://discuss.python.org/t/about-the-packaging-category/365

**Comment by marc-hb** [comment]
Scanning https://github.com/pypi/support/issues?q=sort%3Aupdated-desc+label%3A%22PEP+541%22+is%3Aclosed I found that @yeraydiazdiaz worked on a number of PEP 541 requests 2 weeks ago but unfortunately not this one :'-(

**Comment by marc-hb** [comment]
@yeraydiazdiaz could you or someone else please help with this?

[Zephyr](https://pypi.org/user/zephyr-project/) is an incredibly active and popular project with a spectacular track record. It's an official Linux Foundation project backed by some of the [largest companies in the industry](https://www.zephyrproject.org/project-members/). It's been called the "Linux of the embedded world" across the technical press. Could you or someone else please unblock it?

**Comment by CAM-Gerlach** [comment]
@di @ewdurbin

**Comment by yeraydiazdiaz** [comment]
Hi all, I will now start the reachability process for your request which can take up to 6 weeks. Thank you for gathering resources regarding the owner, hopefully we can get a response soon and proceed with the transfer.

**Comment by carlescufi** [comment]
Hi @yeraydiazdiaz wondering if the reachability process has completed. Thanks!

**Comment by carlescufi** [comment]
Hi @yeraydiazdiaz, bumping up this request, since it's now been well beyond 6 weeks since the last update. Thanks!

**Comment by str4t0m** [comment]
Has there been any progress regarding this request in the meantime?

**Comment by carlescufi** [comment]
@yeraydiazdiaz could you please update us on this issue? It's now been several months with no news.

**Comment by ambv** [comment]
Since Yuray seems to no longer be involved, we will restart the reachability process.

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate this request and make a recommendation on the outcome and actions to be taken. Final determination will be made by the PyPI Administrators when our process is complete.

**Comment by carlescufi** [comment]
@encukou it's now been a while since this process was started, is there a chance we can resolve this in the near future? Thanks in advance!

**Comment by encukou** [comment]
I'm sorry, but I don't know. It's up to the PyPI admins now.

**Comment by kartben** [comment]
@carlescufi have you reached out to [admin@pypi.org](mailto:admin@pypi.org) ?

**Comment by carlescufi** [comment]
> @carlescufi have you reached out to [admin@pypi.org](mailto:admin@pypi.org) ?

No, I have not. Do you want to do it yourself @kartben ?

**Comment by ewdurbin** [comment]
`Owner` role on `kconfiglib` Project granted to `zephyr-project`.
