### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by devoter-fyc** [pypi/support#2530]
### PyPI Username

`fyc`

### Reason for request

I used USB device as a 2FA authentication device and accidentally lost it.
Although I saved recovery codes, they are also lost and possibly deleted.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Thespi-Brain** [comment]
Hi @devoter-fyc,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
