### ISSUE TITLE
Project Limit Request Question: torch

### ISSUE THREAD

**Issue by izaitsevfb** [pypi/support#2532]
### Project URL

https://pypi.org/project/torch/

### Does this project already exist?

- [X] Yes

### New limit

n/a

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

PyTorch is a machine learning framework that accelerates the path from research prototyping to production deployment.

We recently increased the size limit per file (#2341, thank you!), but we are now trying to understand what other limits there may be and how we can track the current total size to avoid hitting them. Can you please provide us with information on the total project/channel size limit for `torch` package and the methods we can use to track it? Can we rely on https://pypi.org/stats/ for that?

Thank you!

Related issues:
* #2341 
* pytorch/pytorch#92089

### How large is each release?

[≈6gb](https://pypi.org/project/torch/#files)

### How frequently do you make a release?

≈3 times per year

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
> we are now trying to understand what other limits there may be and how we can track the current total size to avoid hitting them.

There's two.

You can see these on https://pypi.org/manage/project/torch/settings/. For pip, a project currently at default limits, it looks like:

<img width="464" alt="Screenshot 2023-01-25 at 19 23 19" src="https://user-images.githubusercontent.com/3275593/214666077-2bcdce5c-b2d3-474e-8b87-e1eeb1109e8e.png">
