### ISSUE TITLE
PEP 541 Request: well

### ISSUE THREAD

**Issue by skorokithakis** [pypi/support#2537]
### Project to be claimed

`well`: https://pypi.org/project/well

### Your PyPI username

`USER_NAME`: https://pypi.org/user/stavros

### Reasons for the request

I don't actually want the name `well`, I developed a cli utility for the Wii Balance Board that's called `weii` (pronounced "weigh"), and it seems the name is banned because it's confused with this package. The package seems like a weird form of namesquatting (all the author's packages I've seen contain exactly the same code), so I'd like to request the name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no repository for the existing one that I can see.

Mine is:

https://gitlab.com/stavros/weii

### Contact and additional research

I haven't contacted the author, as the account seems some sort of spam account, with the same package published on the same day multiple times under different names:

https://pypi.org/user/neilyio/

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @skorokithakis, a @pypi/warehouse-admins should be able to release the project name to you, I'll place it in a queue for them now.

**Comment by skorokithakis** [comment]
Thank you!

**Comment by ewdurbin** [comment]
name weii released to [stavros](https://pypi.org/user/stavros) on PyPI.
