### ISSUE TITLE
File Limit Request: nnabla - 300 MB

### ISSUE THREAD

**Issue by TomonobuTsujikawa** [pypi/support#2538]
### Project URL

https://pypi.org/project/nnabla

### Does this project already exist?

- [X] Yes

### New Limit

300MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

https://nnabla.org/

nnabla is a deep learning framework, and nnabla is base component for nnabla series.
We have been working since 2017 to create lightweight and fastest deep learning framework.
This nnabla project supports to train/inference on CPU environment, and GPU extension is available named as nnabla-ext-cuda.

### Reasons for the request

Network models of deep learning have become larger in recent years, and we found the large network cannot be handled well on Windows environment due to the limitation of third-party library.
So, we decided to migrate to use other component, but it resulted in increasing package size.
We would like to upload it now, and will consider reducing the size in the next version.
(So, we don't have a plan to increase total project size.)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the detailed report @TomonobuTsujikawa :+1: 
I've set the upload limit for `nnabla` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice week!
