### ISSUE TITLE
PEP 541 Request: Titta

### ISSUE THREAD

**Issue by marcus-nystrom** [pypi/support#2539]
### Project to be claimed

`titta`: https://pypi.org/project/titta

### Your PyPI username

`marcus-nystrom`: https://pypi.org/user/marcus-nystrom

### Reasons for the request

Upload to PyPI failed with `The name 'titta' isn't allowed`. I do not know for what reason this happened. Could you unblock the name?
(see https://github.com/marcus-nystrom/Titta/actions/runs/4014860048/jobs/6895891832)

There is a related package TittaPy made by my colleague, which titta uses as a backend and lists as a dependency. There should be no risk of confusion.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/marcus-nystrom/Titta

### Contact and additional research

n/a

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dcnieho** [comment]
@yeraydiazdiaz I too am awaiting release of this name. Its been half a year now. Could you or other contributors please release the name?

**Comment by ewdurbin** [comment]
Released to marcus-nystrom on PyPI.
