### ISSUE TITLE
PEP 541 Request: forklift

### ISSUE THREAD

**Issue by taleinat** [pypi/support#2540]
### Project to be claimed

`forklift`: https://pypi.org/project/forklift

### Your PyPI username

`taleinat`: https://pypi.org/user/taleinat

### Reasons for the request

The project named "forklift" is invisibly listed: Opening the project page returns 404. It appears to have not been active for a long time. As far as I can tell, it does not seem to be reserved to avoid collision with another existing project or some similar reason. Since there are no active releases for it, I cannot see any details about it, including its owner(s).

A project with that name is [registered on test.pypy.org](https://test.pypi.org/project/forklift/) by a different user, Guilherme Castelão. I contacted him to request transfer of the project, and he responded explaining that he abandoned the name back in 2016 since it was already claimed on pypi.org.

The name "forklift" would be perfect for a new project I am starting.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

I do not know anything about the existing project. Since it is invisibly listed, it is unlikely to be one of the few active projects of that name.

My new project has just been started: [github.com/taleinat/forklift](https://github.com/taleinat/forklift). I would like to use a name for this project that is available on pypi.org, hence my request at this early stage of the project.

### Contact and additional research

I've not been able to find contact details for the project owner.

I have contacted Guilherme Castelão, the owner of the project of the same name on test.pypi.org, and he says the project on pypi.org is not his, and has been "invisibly" listed on pypi.org since at least 2016.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @taleinat, `forklift` exists but has no releases which is why PyPI returns a 404, the project is thus invalid. The owner is @dstufft so hopefully he'll be able to transfer the project to you.

**Comment by encukou** [comment]
We are working to contact the owner to get a reply.

Disclaimer: We are providing support to the PyPI Administrators to validate this request and make a recommendation on the outcome and actions to be taken. Final determination will be made by the PyPI Administrators when our process is complete.

**Comment by encukou** [comment]
We could not reach @dstufft, and we consider the project abandoned per [PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).
We recommend that the PyPI Administrators assign taleinat as the new owner of "forklift".

**Comment by taleinat** [comment]
Thank you for following up!

I've since found an alternative name for my project, so I would no longer like to obtain owneship of this project name.
