### ISSUE TITLE
PEP 541 Request: chrombpnet

### ISSUE THREAD

**Issue by panushri25** [pypi/support#2542]
### Project to be claimed

`chrombpnet`: https://pypi.org/project/chrombpnet

### Your PyPI username

`USER_NAME`: https://pypi.org/user/anusri

### Reasons for the request

https://pypi.org/project/chrombpnet/ (shows error code 404) so i think it is unclaimed.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The sourse code is on github and not made public yet. Is this causing the issue? 

### Contact and additional research

None

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by FriedrichFroebel** [comment]
What is the actual issue here? There should be no need to file a PEP 541 request if you plan on uploading a completely new package, which seems to have worked in the meantime.
