### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mtb-beta** [pypi/support#2543]
### PyPI Username

mtb_beta

### Reason for request

Lost 2FA authentication app or security token.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The user `mtb_beta` has valid recovery codes generated as of 2022-03-09, those should be used to recover access to the account.

**Comment by mtb-beta** [comment]
Sorry.
The machine where I stored the recovery code has been damaged and cannot be rescued.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by mtb-beta** [comment]
@ewdurbin 

Thank you for your response. I have checked email and responded. Please confirm.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
