### ISSUE TITLE
PEP 541 Request: lighter

### ISSUE THREAD

**Issue by ibro45** [pypi/support#2544]
### Project to be claimed

`lighter`: https://pypi.org/project/lighter

### Your PyPI username

`ibro45`: https://pypi.org/user/ibro45

### Reasons for the request

The project hasn't been maintained since March 2018. The project is a simple, but outdated, PyTorch training loop.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/DavexPro/lighter
https://github.com/project-lighter/lighter/

### Contact and additional research
Contacted on 27 Jan 2023, no answer yet (19 Feb 2023).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by surajpaib** [comment]
Update: The owner has been contacted in this regard on 27th of Jan.

**Comment by ibro45** [comment]
@DavexPro would you please be willing to transfer the PyPi name?

**Comment by DavexPro** [comment]
Sorry, I don’t think so.

**Comment by yeraydiazdiaz** [comment]
Closing since, as described in PEP 541:

> Under no circumstances will a name be reassigned against the wishes of a reachable owner.
