### ISSUE TITLE
Project Limit Request: DepthAI - 20 GB

### ISSUE THREAD

**Issue by themarpe** [pypi/support#2546]
### Project URL

https://pypi.org/project/depthai/

### Does this project already exist?

- [X] Yes

### New limit

20GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Active since September, 2020.

The project is a native library with python bindings, and it carries large amount of wheels to support all platforms.

Preferably we'd switch over to abi3 wheels to reduce that number, but due to porting efforts, this isn't currently on the table.

The library is also expected to see some size increase as more features are going to be included in it soon. (but not by a bunch)

### How large is each release?

~350MB total

35 wheels at 10MB each + source tarball

### How frequently do you make a release?

On average once to twice per month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by themarpe** [comment]
Modified the size to 20GB - overshot by a bunch, no need for 100GB for some time:)

**Comment by cmaureir** [comment]
Hey @themarpe :wave: thanks for the detailed issue.
I've set the project limit for `depthai` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size, and maybe evaluate the limited api to avoid having too many wheels depending on Python versions https://docs.python.org/3/c-api/stable.html
Have a nice week!
