### ISSUE TITLE
File Limit Request: mc_providers- 120 MB

### ISSUE THREAD

**Issue by pgulley** [pypi/support#2547]
### Project URL

https://test.pypi.org/manage/project/mc-providers/releases/

### Does this project already exist?

- [X] Yes

### New Limit

125

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The project is a part of [ Mediacloud](https://search.mediacloud.org/), a research tool for investigating the content of large text corpora on the internet. This specific module is a breakout of our search-providers functionality

### Reasons for the request

The large package size is due to a ~100MB language model used to guess the language of text, which is necessary metadata for most applications. Including the model in the package repository is the simplest way of providing this functionality to our projects. 125 MB gives us plenty of room to grow in addition to hosting the language model, as we build out the functionality in the coming months. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I've increased the limit to 200 MB, on PyPI and TestPyPI. I imagine that'll serve to give you even more of a breathing room. :)
