### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by chrish** [pypi/support#2549]
### PyPI Username

chha

### Reason for request

Somehow forgot to transfer Pypi from MS Authenticator over to new phone a while a go, old phone has been whiped so no way to recover. This was a test account only, so not sure if I've added any additional info that will help with MFA recovery. 

regards
Chris

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
I'm unable to find a user with username `chha` on PyPI.
