### ISSUE TITLE
PEP 541 Request: memex 

### ISSUE THREAD

**Issue by nathanielCherian** [pypi/support#2550]
### Project to be claimed

`memex `: https://pypi.org/project/memex/

### Your PyPI username

`nathanielCherian`: https://pypi.org/user/nathanielCherian

### Reasons for the request

This namespace has been claimed almost 7 years ago yet there is no source code published for this project. When I try installing this package I get the following error
```
ERROR: Could not find a version that satisfies the requirement memex (from versions: none)
ERROR: No matching distribution found for memex
```

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The original source code was never published to pypi, nor on the author's github page. 

New Project: https://github.com/nathanielCherian/memexPyPI

### Contact and additional research

I have contacted the owner of the project on twitter 3 weeks ago and have not received any response.
<img width="292" alt="image" src="https://user-images.githubusercontent.com/55414597/214739340-0b41b38d-9be0-41f6-a3a6-13d487b43af2.png">

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @nathanielCherian, the project has a single release with no associated files and thus it's considered invalid. I will attempt contact with the owner and allow one week for replies before transferring the project.

**Comment by nathanielCherian** [comment]
Hey @yeraydiazdiaz, has there been any update for this? Thanks!

**Comment by chapmanjacobd** [comment]
> New Project: nathanielCherian/memexPyPI

the link should probably be https://github.com/nathanielCherian/memex

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate this request and make a recommendation on the outcome and actions to be taken. Final determination will be made by the PyPI Administrators when our process is complete.

**Comment by encukou** [comment]
Actually, it turns out that the project is now active again, and had a release recently.
So, it's no longer invalid. You'll need to contact the owner if you want to arrange a name transfer.
