### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by hentai-chan** [pypi/support#2552]
### PyPI Username

`hentaichan`

### Reason for request

Lost 2FA authentication app or security token (because I upgraded my cell phone and made a mistake while transferring my authenticator backup)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The `hentaichan` user on PyPI has valid recovery codes generated as of 2021-06-10, those should be used to recover access to the account.

**Comment by hentai-chan** [comment]
Unfortunately I also lost access to these keys as well sometime last year. I noticed this again while re-creating all my recovery keys for other accounts that are protected by 2FA, and this is the only account that has been gone missing without being noticed.

**Comment by Thespi-Brain** [comment]
Hi @hentai-chan,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
