### ISSUE TITLE
PEP 541 Request: Jet

### ISSUE THREAD

**Issue by antonio-leitao** [pypi/support#2554]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/jet

### Your PyPI username

`USER_NAME`: https://pypi.org/user/leitao

### Reasons for the request

Project has been abandoned for over 7 years. No commit both on Pypi nor github.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/entangly/jet/

### Contact and additional research

https://github.com/entangly/jet/issues/21

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by MarcoGorelli** [comment]
did you never manage to get this one transferred, in > 1 year?

that's not encouraging...

**Comment by MarcoGorelli** [comment]
Hi @encukou - just out of interest, are there any examples of cases when a PEP-541 request went through, and a candidate's demonstration of why a different name was not acceptable deemed satisfactory?

**Comment by encukou** [comment]
I think so, but it's quite rare, and there should be at least *some* explanation.
Sadly, I don't keep track of this, and I couldn't find the time to do the research from [closed issues](https://github.com/pypi/support/issues?page=2&q=is%3Aissue+is%3Aclosed+label%3A%22PEP+541%22).
