### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by shivanprasad** [pypi/support#2557]
### PyPI Username

'shivanprasad'

### Reason for request

Lost access to 2FA, I have access to my associated email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The `shivanprasad` user on PyPI has valid recovery codes generated as of 2022-05-11, these should be used to recover access to the account.

**Comment by shivanprasad** [comment]
I thought that I had them but I believe I overwrote them.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
