### ISSUE TITLE
PEP 541 Request: salt

### ISSUE THREAD

**Issue by ScriptAutomate** [pypi/support#2558]
### Project to be claimed

`PROJECT_NAME`: https://test.pypi.org/project/salt

### Your PyPI username

`USER_NAME`: https://test.pypi.org/user/saltbot

### Reasons for the request

We publish packages to the production pypi repository for `salt`, but are having difficulty publishing to `salt` on `test.pypi.org`. 

At the moment, `salt` is unlisted but seemingly reserved on `test.pypi.org`. When attempting a new upload, we receive the following error for our `saltbot` account that we'd like to use for publishing:

```
ERROR    HTTPError: 403 Forbidden from https://test.pypi.org/legacy/                                                                                                                 
         The user 'saltbot' isn't allowed to upload to project 'salt'. See https://test.pypi.org/help/#project-name for more information. 
```

> NOTE: I am selecting `Replacement` for the `Maintenance or replacement?` option because right now there is no publicly facing `salt` package on `test.pypi.org`, and we'd like to have ownership of the package for testing purposes.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/saltstack/salt

### Contact and additional research

We are meant to be the owners of `salt` on both `pypi.org` and `test.pypi.org`. At the moment, `salt` on `test.pypi.org` just seems to be hidden or other inaccessible. We are unable to publish.

I am `ScriptAutomate` on both GitHub, and PyPi, listed as one of the owners of `salt` on pypi.org:
- https://pypi.org/project/salt/
  - My user: https://pypi.org/user/ScriptAutomate/

We have a `saltbot` account as a maintainer on pypi.org, and would like the same for our `saltbot` account on test.pypi.org

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ScriptAutomate** [comment]
Hey! Would like to check-in in case there is additional information we can provide.

`salt` is listed as a `CRITICAL PROJECT` when logged in on pypi, so I'm uncertain if this may be related to it being unlisted and unavailable to publish to at the moment.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by s0undt3ch** [comment]
Thank You @yeraydiazdiaz!

**Comment by ScriptAutomate** [comment]
Thanks so much!
