### ISSUE TITLE
PEP 541 Request: dolphin

### ISSUE THREAD

**Issue by scottstanie** [pypi/support#2562]
### Project to be claimed

`dolphin`: https://pypi.org/project/dolphin

### Your PyPI username

`scott.stanie`: https://pypi.org/user/scott.stanie

### Reasons for the request

- The current pypi page for `dolphin` is empty. There is no code to download
- The homepage links to a broken github link: https://github.com/dolphin-cs/dolphin-python
- I received no email response from the developer listed

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no code or link to code for the current project.

The replacement project will come from here https://github.com/opera-adt/dolphin/ 

### Contact and additional research

I contacted the developer's email listed on pypi about two months ago. I received no reply.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/8291800/215641106-d4a50f56-cd42-4576-b56c-f1a33496213e.png">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by scottstanie** [comment]
Checking if there's any chance of getting this through:
The pypi project is completely empty, and you can't currently `pip install dolphin`. This seems like it falls under Name Squatting since this "package has no functionality or is empty".

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by ambv** [comment]
dolphin has been deemed invalid. Additionally, the owner did not
respond in a week.

We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `scott.stanie`.

**Comment by ewdurbin** [comment]
`dolphin` Project name released to `scott.stanie` User.
