### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lonkeknol** [pypi/support#2563]
### PyPI Username

`lonkeknol`

### Reason for request

I lost access to my 2fa authentication app and forgot to generate recovery codes. It would be great if you could assist me in recovering access to my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by FredKemp1** [comment]
Hello, I am a cybersecurity engineer and ethical hacker with an emphasis in account recoveries. I can handle this project. Please contact me for further details.

**Comment by lonkeknol** [comment]
I followed the instructions and replied to the email. Just to be sure, I'm replying here as well.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
