### ISSUE TITLE
PEP 541 Request: qconfig

### ISSUE THREAD

**Issue by kennyhml** [pypi/support#2565]
### Project to be claimed

qconfig`: https://pypi.org/project/qconfig/

### Your PyPI username

`kennyhml`: https://pypi.org/user/kennyhml/

### Reasons for the request

Making my own package that I intended to call qconfig, its not fully done yet but it's already quite useful. Unfortunately the name qconfig is already taken, and upon inspecting the package it is literally a single function that advertises his website, not a single line of actual code. It also doesnt seem to have changed since 2021.

I assure that my own package called qconfig would provide alot more utility than getting linked to a service provider.

Thanks!

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Currently active:

https://github.com/QsonLabs/open-qconfig-py

My own;
https://github.com/kennyhml/QConfig

### Contact and additional research

Look at his github I sent, he is registered as an enterprise, but with no members. I could not find a way to contact him.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by takluyver** [comment]
If you're only *planning* to call your project qconfig, I doubt it meets these criteria for reusing a name:

> - the candidate is able to demonstrate that the project suggested to reuse the name already exists and meets notability requirements;
> - the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround;

As for contacting the existing owner, you could try opening an issue on their Github repo? Or maybe there's an email address in git logs.

**Comment by cracker911181** [comment]
@takluyver please help me. Check my issue please.

https://github.com/pypi/support/issues/2570

**Comment by takluyver** [comment]
Please don't spam unrelated issues asking for attention. Even if I was in a position to help you (I'm not), that's inconsiderate behaviour.

**Comment by cracker911181** [comment]
Okey. Sorry

**Comment by kennyhml** [comment]
> 

So, do I need to upload the project on pypi under a different name for now? 
And why would I fork it? All his package does is refer to his own company, its literally a single function that will tell you to visit the company he founded, so hes just using it for advertisement. 

I went to the website he advertises and filled out a contact formula about the issue his package is causing me, so I should be able to reach him over that. Just a matter of whether he can be bothered to remove it, or not.

**Comment by takluyver** [comment]
Sorry, the bit about forking is a bit misleading here. The first point I quoted says that the project you want to replace it with should already exist and be 'notable' (exactly how notable isn't specified). The second point means 'and you can't reasonably rename it to something else'. A brand new project probably doesn't meet these requirements.

**Comment by cmaureir** [comment]
There are a few features of you code that can help to find an available name also, keep in mind there is a `qconfig` tool in Qt https://doc.qt.io/Boot2Qt/qt-configuration-tool.html which as a Qt user you understand that it might create confusion.

**Comment by kennyhml** [comment]
> Yup noted, but it doesnt do the same thing at all and it's also not something you actually import to use "in code". I dont really think its confusing and they also serve different purposes

**Comment by kennyhml** [comment]
> Well the project already exists and is ready to be uploaded to pypi, it works fine as I have been using it for many of my own programs. I have just been waiting for the "original" one to be removed. It is kind of a shame that I cant upload a useful tool to pypi just because someone has decided to slap an advertisement for his own company in it and leave it at that. Speaking of which I have still not gotten a reply back from the current "owner".

**Comment by larryhastings** [comment]
On the other hand, I'd argue that the current project is "squatting" the name:

From https://docs.npmjs.com/policies/disputes/#squatting :

> Package names are considered squatted if the package has no genuine function.

I assert that a package that only opens a web browser to the author's web site qualifies as having no genuine function.  And since package name squatting is against the PyPI terms of service, the request to transfer the name is reasonable.

**Comment by kennyhml** [comment]
> On the other hand, I'd argue that the current project is "squatting" the name:
> 
> From https://docs.npmjs.com/policies/disputes/#squatting :
> 
> > Package names are considered squatted if the package has no genuine function.
> 
> I assert that a package that only opens a web browser to the author's web site qualifies as having no genuine function. And since package name squatting is against the PyPI terms of service, the request to transfer the name is reasonable.

Thank you, that is exactly what I was trying to convey, maybe I didnt find good words for it. It sucks that I have to go through so many struggles to upload a valid package, just because someone misused it for advertising purposes.

**Comment by kennyhml** [comment]
Is there any hope for actions taken here? If not im going to try come up with something else, which kinda sucks because qconfig was a very good name for it. Its a shame that someone shamelessly uses pypi for advertising purposes, does not reply when confronted about it and somehow still gets away with it staying there. Sorry I know you guys probably have alot to do but its really frustrating because it seemed like such an obvious case to me.

**Comment by marc-h38** [comment]
While cybersquatting is much worse, "using it for many of my **own** programs" seems very light too.

**Comment by kennyhml** [comment]
> While cybersquatting is much worse, "using it for many of my **own** programs" seems very light too.

Sorry, could you elaborate what you mean? I was simply stating that I (as someone who deals with pyqt alot) make heavy use of the package, and that I am sure other pyqt users would benefit just as much from it. The reason I mentioned that is to emphasize that the package is already finished and working, and all I have been waiting for in the past weeks is for the current `qconfig` to be removed, because one of the arguments here was that my package must already exist and be usable!

**Comment by kennyhml** [comment]
Well ended up just calling it qtconfig, which means the import name will end up being different than the package name but whatever. Tired of waiting, pretty sad something so trivial wont be resolved. Thanks for everyones time!

**Comment by yeraydiazdiaz** [comment]
Thanks for your patience.
