### ISSUE TITLE
PEP 541 Request: epi

### ISSUE THREAD

**Issue by TheVincentWagner** [pypi/support#2576]
### Project to be claimed

`epi`: https://pypi.org/project/epi

### Your PyPI username

`TheVincentWagner`: https://pypi.org/user/TheVincentWagner

### Reasons for the request

The domain epi was claimed on test-pypi by Nathan Geffen (see below in the field "Contact and additional research").
He never claimed epi on pypi, still we are unable to publish our code under this domain.
The current pypi domain epi is therefore not actively used and uselessly squatted.
We would like to publish our project under epi, as our method is called Eulerian Parameter Inference.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no code for the current repository.
Our project can be accessed via https://github.com/Systems-Theory-in-Systems-Biology/EPI.

### Contact and additional research

We contacted Nathan Geffen ([nathangeffen@gmail.com](mailto:nathangeffen@gmail.com)), as he published a repository on the epi domain on test-pypi.
He does not intend to use the pypi domain epi.
We also could not find any other owner of the epi domain.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by ewdurbin** [comment]
`Owner` role on `epi` Project has been granted to `TheVincentWagner`
