### ISSUE TITLE
File Limit Request: OREAnalytics-Python - 600 MB

### ISSUE THREAD

**Issue by eehlers** [pypi/support#2578]
### Project URL

https://test.pypi.org/project/OREAnalytics-Python

### Does this project already exist?

- [X] Yes

### New Limit

600

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

> What the project is and how long it has been active.

ORE - Open Risk Engine
https://www.opensourcerisk.org/
10 years

> If you have made efforts to reduce the size of your PyPI releases, mention it here.

Stripped out all but the essential libs.  On Windows the file size is within the limit but on Linux the file size exceeds the limit.

> If you bundle other packages in your project, mention it here.

No other packages.

> If you bundle example data in your project, mention it here.

No example data.

### Reasons for the request

Requesting limit increase to allow upload of our Linux build which exceeds your limit.

Possible future changes:
- Eventually we would like to deploy these files to PyPi in addiiton to Test PyPi
- So far we have generated wheels for Windows and Linux, we still need to do it for MacOS and there is a possibility that those files could further exceed the size limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @eehlers :wave: thanks for the report.
I was looking at the current version you have and the largest wheel is around 50MB, there are some windows wheels as well there, but they are around 20MB, so I wanted to know if the huge increase is due to a new version? you are adding more things to the project? 
Can you maybe share a bit more info on why the sudden jump, and what are the bits that are increasing the size of the project?
Thank you!

**Comment by eehlers** [comment]
Hey @cmaureir thanks for getting back to me.

The new thing that we are adding is support for linux.  The wheels generated by the linux build are much larger than those generated by the Windows and MacOS builds.

Kind Regards,
Eric

**Comment by cmaureir** [comment]
> Hey @cmaureir thanks for getting back to me.
> 
> The new thing that we are adding is support for linux. The wheels generated by the linux build are much larger than those generated by the Windows and MacOS builds.

I see, did you identify why the size increases so much? I'm just trying to understand the jump  from 20MB and 50MB to 600 MB that you are requesting, we are talking about 30 times the size of the largest (macOS).

Maybe you can share the size of the linux wheels? I would expect they are around 100 MB, but I'm really curious.

**Comment by eehlers** [comment]
```
erik@laptop:~/quaternion/wheels$ ls -l
total 2042764
-rw-rw-r-- 1 erik erik  47273270 Feb  9 16:13 OREAnalytics_Python-1.8.3.2-cp310-cp310-macosx_10_9_x86_64.whl
-rw-rw-r-- 1 erik erik 487488355 Feb  8 10:50 OREAnalytics_Python-1.8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
-rw-rw-r-- 1 erik erik 487482399 Feb  9 10:53 OREAnalytics_Python-1.8.3.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
-rw-rw-r-- 1 erik erik  47274134 Feb 10 11:19 OREAnalytics_Python-1.8.3.2-cp38-cp38-macosx_10_9_x86_64.whl
-rw-rw-r-- 1 erik erik 487481539 Feb  9 11:04 OREAnalytics_Python-1.8.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
-rw-rw-r-- 1 erik erik  47273243 Feb  9 23:31 OREAnalytics_Python-1.8.3.2-cp39-cp39-macosx_10_9_x86_64.whl
-rw-rw-r-- 1 erik erik 487483059 Feb  8 19:42 OREAnalytics_Python-1.8.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

The macos files are 47MB, the linux files are 487MB.

**Comment by eehlers** [comment]
Hello Again,

_I have set the new limit on TestPyPI for OREAnalytics-Python to 600MB._

I am still having trouble uploading files, please see below.  The error message is vague but I suspect that there is still a problem with the file size.  The file size is 487MB.  Would it be possible for you to double check the limit?

```
$ ls -l OREAnalytics_Python-1.8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
-rw-rw-r-- 1 erik erik 487488343 Feb 21 19:32 OREAnalytics_Python-1.8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
$ python3 -m twine upload --repository testpypi OREAnalytics_Python-1.8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Uploading distributions to https://test.pypi.org/legacy/
Uploading OREAnalytics_Python-1.8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.5/487.5 MB • 02:23 • 3.3 MB/s
WARNING  Received "503: Service Unavailable"
```

**Comment by cmaureir** [comment]
I just double check and the limit is set to 600M, I'm not sure if the issue you are having is related to the wheel size, otherwise we would see a more clear error regarding the limit. I'd recommend you to open a new issue for that specific problem.
