### ISSUE TITLE
PEP 541 Request: clef

### ISSUE THREAD

**Issue by larryhastings** [pypi/support#2579]
### Project to be claimed

`clef`: https://pypi.org/project/clef

### Your PyPI username

`larry`: https://pypi.org/user/larry

### Reasons for the request

I believe the `clef` project has been abandoned.

Clef was a startup, which created a single-sign-on service for the internet--also called Clef--in 2013:

[https://en.wikipedia.org/wiki/Clef_(app)](https://en.wikipedia.org/wiki/Clef_(app))

The service was shut down in July 2017, and the company was sold; since then, *that* company has also been sold.  The Clef server code was never open-sourced.  As far as I know it's definitively, absolutely dead.

The `clef` project on PyPI is a client for the Clef service.  Its last commit was June 19, 2015, nearly eight years ago.

As far as I know the project is completely useless, because no server exists for this client to connect to.  The only utility I could imagine for the project would be as example code for writing your own network client, but it doesn't need to be a PyPI project for that.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The clef repo is here:

https://github.com/clef/clef-python

My replacement project is currently private.  If I get this name, I'll rename my private project to *clef* and publish with that name.  If it's absolutely necessary for me to publish my project before I can get the name, I can do that, though I was hoping to not have to bother.  (My last PEP 541 request was denied.)

### Contact and additional research

The owner of the `clef` project is Grace Wong, or `gwongz`.  I believe that at the time they were active on the `clef` project, they were an employee at the Clef startup.

I found a Gmail address for them and emailed them on November 20, 2022, asking if they'd transfer the name to me.  I received no reply.  I also tried their `coinbase.com` address on November 26 but that bounced.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ambv** [comment]
clef has been deemed invalid. Additionally, the owner did not
respond in a week.

We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by ewdurbin** [comment]
Should the project be deleted or transferred to the requesting user?

**Comment by ambv** [comment]
To clarify, we recommend the project be transferred to `larry`.

**Comment by ewdurbin** [comment]
`Owner` role for `clef` Project has been granted to `larry`.
