### ISSUE TITLE
File Limit Request: nvidia_dali_cuda120-1.22.0 - 350 MB

### ISSUE THREAD

**Issue by ankhikarmakar** [pypi/support#2580]
### Project URL

https://pypi.org/project/nvidia_dali_cuda120

### Does this project already exist?

- [X] Y

### New Limit

350 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Part of Nvidia component Dali

### Reasons for the request

The new wheel size exceeds existing limit i.e. 100 MB. In future too we might see increase in the size.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @ankhikarmakar :wave:
I checked on PyPi and TestPyPi and the project `nvidia_dali_cuda120` doesn't exist. Remember to create it first with a 0.0 release for example. Let me know when you have created the project.

**Comment by ankhikarmakar** [comment]
Hey @cmaureir ,
we have created an empty project space, please take a look at it https://pypi.org/project/nvidia-dali-cuda110/#description

**Comment by JanuszL** [comment]
@cmaureir - correction - https://pypi.org/project/nvidia-dali-cuda120/

**Comment by cmaureir** [comment]
Hello @ankhikarmakar and @JanuszL :wave:
I've set the upload limit for `nvidia_dali_cuda120` to 400 MB on PyPI. The project doesn't exist on TestPyPI so in case you need the update as well, let me know. Please be mindful of the frequency of releases at that size.
Have a nice Friday and weekend!

**Comment by JanuszL** [comment]
Thanks @cmaureir!
