### ISSUE TITLE
PEP 541 Request: master

### ISSUE THREAD

**Issue by jpedro** [pypi/support#2582]
### Project to be claimed

`master`: https://pypi.org/project/master

### Your PyPI username

`jpedro`: https://pypi.org/user/jpedro

### Reasons for the request

The existing project is abandoned.

My replacement code generates a deterministic password for a give service name, using sha256 as hashing algorithm.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Existing repo: The link is broken.

New repo: https://github.com/jpedro/master

### Contact and additional research

The listed email is broken.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the current owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by ewdurbin** [comment]
Should the project be deleted or transferred to the requesting user?

**Comment by ambv** [comment]
To clarify, we do recommend transferring the project to `jpedro`.
