### ISSUE TITLE
PEP 541 Request: iotawattpy

### ISSUE THREAD

**Issue by llamafilm** [pypi/support#2583]
### Project to be claimed

`iotawattpy`: https://pypi.org/project/iotawattpy/

### Your PyPI username

`agners`: https://pypi.org/user/agners/

### Reasons for the request

This project appears to abandoned. The last commit was over a year ago and the GitHub has 3 open pull requests. This primary use of this library is by Home Assistant, so it makes sense to place it under the home-assistant-libs organization. 

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Old: https://github.com/gtdiehl/iotawattpy
New: https://github.com/home-assistant-libs/iotawattpy

### Contact and additional research

I tried contacting the owner through a GitHub issue an also by email with no response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by llamafilm** [comment]
Email trying to contact the owner: 
<img width="712" alt="Screen Shot 2023-02-09 at 20 43 14" src="https://user-images.githubusercontent.com/3991046/218002723-c3dce5e9-a461-415f-b733-da484982fbc2.png">

**Comment by agners** [comment]
> ### Your PyPI username

Wrt "your"...

> 
> `USER_NAME`: https://pypi.org/user/agners/

Technically, that is my account, but I wasn't sure/aware how to trigger the ownership transfer. FWIW, I approve of this transfer :+1:

**Comment by yeraydiazdiaz** [comment]
Hi @agners, you can add @llamafilm as an owner in https://pypi.org/project/iotawattpy/collaboration/

**Comment by agners** [comment]
@yeraydiazdiaz how? I don't have access to the iotawattpy project.

What we are trying to do is transferring ownership from gregtd, as they are not responding.

All I am saying that the transfer requested by @llamafilm is to me (@agners here, and agners on PyPI). But I am also fine if the project gets transferred to @llamafilm, as long as someone who is responsive and we can continue the project :smile:

**Comment by yeraydiazdiaz** [comment]
Right, sorry, I thought you were the owner.

**Comment by agners** [comment]
What is the state of this request? Is there anything I or @llamafilm can/should do?

**Comment by MrStevenFeldman** [comment]
+1, from a random Home Assistant user who traced through there issues with this library hoping to contribute a fix only to discover that someone else made the easy fix, but it is blocked on the owner being MIA.

home-assistant-libs seems like a reasonable home for this library and will ensure it gets the support it deserves

**Comment by agners** [comment]
@yeraydiazdiaz anything we can do from our side to get thsi process going?

**Comment by agners** [comment]
Is there still a chance to get this going somehow?

**Comment by agners** [comment]
I've create a new project on PyPI at [ha-iotawattpy](https://pypi.org/project/ha-iotawattpy/). This can be closed from my perspective.

**Comment by encukou** [comment]
I'll close this. Sorry that we didn't get to it in time.
I guess the new name is now too widely used to try renaming again :(

**Comment by llamafilm** [comment]
@encukou I still think it would be helpful to go through with this transfer. This library is mostly just used by Home Assistant so it will be relatively easy to update it there.

**Comment by ambv** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
We could not reach the owner, and we consider the project abandoned per
[PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).
We recommend that the PyPI Administrators assign agners as the new
owner of "iotawattpy".

**Comment by ewdurbin** [comment]
`Owner` role on `iotawattpy` Project granted to `agners`
