### ISSUE TITLE
PEP 541 Request: testplan

### ISSUE THREAD

**Issue by bingenito** [pypi/support#2584]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/testplan

### Your PyPI username

`USER_NAME`: https://pypi.org/user/morganstanleyopensource

### Reasons for the request

This package is a clone of our project https://github.com/morganstanley/testplan published by a third party.  We are looking to now start publishing official releases.  The existence of this package masquerading as being our project introduces significant supply chain risk as it can introduce malicious behavior at any time that is not present in the official repository.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/morganstanley/testplan is the official project and you can see the published project is referencing this.  This is not published by our organization.

### Contact and additional research

We are unable to contact the maintainers since it is using our own contact and repository information.   Contact details of the user "hammerhead" are unavailable.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by kn-ms** [comment]
Hello Pypi folks, if our case is not strong enough to initiate this transfer, can you help to facilitate some conversation with the user hammerhead (https://pypi.org/user/Hammerhead/) The only project he owns (testplan) is referring to our own email address, so we could make any contact. Your registration process require an email address, can you at least contact hammerhead there, asking to contact us on eti-testplan@morganstanley.com to get this project transfer resolved?

Many thx
Krisztian

**Comment by ambv** [comment]
We're treating this as an (unintentional?) case of impersonation where the current owner of the package on PyPI is not a Morgan Stanley employee.

We're willing to recommend PyPI admins add [morganstanleyopensource](https://pypi.org/user/morganstanleyopensource) as an owner of the `testplan` package. However, before we do this, we need this user to:

1. have a verified `morganstanley.com` e-mail address on PyPI. While it is currently listed on your profile, it needs verification; and
2. have 2FA enabled.

@bingenito, @kn-ms please let us know when you completed those items.

Disclaimer: We are providing support to the PyPI Administrators to validate this request and make a recommendation on the outcome and actions to be taken. Final determination will be made by the PyPI Administrators when our process is complete.

**Comment by bingenito** [comment]
Hi @ambv, thanks for the follow-up.  I've enabled 2fa and I've verified the morganstanley.com email via profile settings for the morganstanleyopensource user.  Let me know if you need me to make it public.

**Comment by ambv** [comment]
We confirm the [morganstanleyopensource](https://pypi.org/user/morganstanleyopensource) PyPI account now has a verified e-mail address under the `morganstanley.com` domain with 2FA enabled. As such, we recommend the PyPI Admins assign morganstanleyopensource as the new
owner of the "testplan" project per [PEP 541](https://peps.python.org/pep-0541/). The package metadata is already pointing at Morgan Stanley and not the current owner of the package.

Disclaimer: We are providing support to the PyPI Administrators to validate this request and make a recommendation on the outcome and actions to be taken. Final determination will be made by the PyPI Administrators when our process is complete.

**Comment by ewdurbin** [comment]
`Owner` role for `testplan` Project granted to `morganstanleyopensource`
