### ISSUE TITLE
File Limit Request: fastdup - 250 MB

### ISSUE THREAD

**Issue by dbickson** [pypi/support#2590]
### Project URL

https://pypi.org/manage/project/fastdup

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Hello Pypi support, we have a popular FREE computer vision tool called fastdup, that hit the 150,000 installations in its first 7 months! Users are excited about us since we solve basic problems for curation of image repos like duplicate and outlier removal. Our engine is written in C++ and we want to release a windows version as well but we hit the 100M limit since on windows we have around 30 dependencies like opencv (4 dlls), libheif, onnxruntime etc. Will it be possible to increase our quota to 250 MB as we have a C++ engine that runs super efficient code and saves the users a lot of compute.

### Reasons for the request

We would like to continue helping our community of users by adding additional models like face detection, yolo into the free package and we hit the limit quota as our code base in C++ and needs many flavors for each OS like Mac m1, mac, centos, windows etc.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @dbickson :wave: thanks for the report.
I've set the upload limit for `fastdup` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
