### ISSUE TITLE
PEP 541 Request: snipeit

### ISSUE THREAD

**Issue by nathanmcguire** [pypi/support#2592]
### Project to be claimed

`snipeit`: https://pypi.org/project/snipeit

### Your PyPI username

`nathanmcguire`: https://pypi.org/user/nathanmcguire

### Reasons for the request

Project has been archived on GitHub.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Original: https://github.com/jbloomer/SnipeIT-PythonAPI

Replacement: https://github.com/SchoolOfTheOsage/snipeit

### Contact and additional research

I emailed the owner on February 13 regarding if a transfer would be considered. A response was received on February 13 of "Yes, that is fine. Just give myself and my company credit for my code as it was done and released under my company’s name “Cox Automotive Inc (Manheim)" was received. "

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jared-bloomer** [comment]
I approve this ownership transfer.

**Comment by jbloomer** [comment]
I approve this transfer

**Comment by yeraydiazdiaz** [comment]
@jared-bloomer @jbloomer you can add `snipeit` as an owner in https://pypi.org/project/snipeit/collaboration/

**Comment by jbloomer** [comment]
Done

**Comment by nathanmcguire** [comment]
Transfer has been completed.
