### ISSUE TITLE
PEP 541 Request: kcp

### ISSUE THREAD

**Issue by RealistikDash** [pypi/support#2594]
### Project to be claimed

`kcp`: https://pypi.org/project/kcp/

### Your PyPI username

`RealistikDash`: https://pypi.org/user/RealistikDash/

### Reasons for the request

The project this issue is referring to has had no code uploaded to it and is on version `0.0.0`, with no update since 2018. The original repository for the project (which is linked as its homepage) has also been deleted, alongside the original GitHub account. The name it occupies is a name of a web protocol (KCP), for which I have written an implementation for (currently on pypi under the name of kcp-py).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Original repository listed on PyPI (deleted): https://github.com/goawm/kcp-py
My replacement: https://github.com/RealistikDash/kcp.py

### Contact and additional research

Unable to find any information about the owner. The original GitHub account the project is pointing to has been removed.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
It looks like the PyPI project is now deleted too. Could you retry?

**Comment by RealistikDash** [comment]
Renamed. Thanks!
