### ISSUE TITLE
PEP 541 Request: wait-for-it

### ISSUE THREAD

**Issue by hartwork** [pypi/support#2595]
### Project to be claimed

`wait-for-it`: https://pypi.org/project/wait-for-it

### Your PyPI username

`sping`: https://pypi.org/user/sping

### Reasons for the request

Hello! :wave: 

The situation from my view is this:
- wait-for-it's [latest release on PyPI](https://pypi.org/project/wait-for-it/#history) is [broken for Python 3.11](https://github.com/clarketm/wait-for-it/pull/49), fixes are merged, and it takes a new release to PyPI to unblock people's upgrade to Python 3.11 including [my own](https://github.com/hartwork/jawanndenn/pull/662#issuecomment-1407815526) and @scastlara's (based on private mail exchange with him).
- Author @clarketm gave me Collaborator permissions on GitHub in the past as a result of my past contributions on the project (https://github.com/clarketm/wait-for-it/commits?author=hartwork), so I can push to the repository at the moment but not release to PyPI.
- I have been asking for a new release for ~3 months at https://github.com/clarketm/wait-for-it/issues/52 with pinging again and again, no reply.
- I reached out via e-mail directly also in case he ignores mail from the repository, but no reply.
- @clarketm's GitHub activity has automated but no human activity after 2021-09 to my eyes, see research below. 

To be clear, if @clarketm returns, I am more than happy to hand back the PyPI access back to him.

Thanks for your help and time with this PEP 541 process :pray: 

Best, Sebastian

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/clarketm/wait-for-it

## E-Mail
@clarketm has a Keybase page at https://keybase.io/clarketm with the same picture as his GitHub avatar. 
That leads to address `travis(dott)m(dott)clarke(att)gmail.com` for an address like this:
```console
# wget -O- https://keybase.io/clarketm/pgp_keys.asc 2>/dev/null | gpg --list-packets | grep @
```
I mailed @clarketm three times on that address (including not recently) and never got a reply from that address:
- 2020-11-24
- 2020-12-14
- 2023-01-30

I tried `travis.clarke(att)offerup.com` before that also on 2020-11-24 (same day but earlier) but I think I got some "mail delivery error" back then, cannot find a copy in my archive.

## GitHub activity
@clarketm's GitHub account has frequent commits on two repository from automation but the last GitHub activity I find that looks human is as far back as 2021-09 (see https://github.com/clarketm?tab=overview&from=2021-09-01&to=2021-09-30)

## Blog
@clarketm's blog has no posts since 2019-02, see https://blog.travismclarke.com/

## Work
@clarketm's profile says he works at Facebook/Meta. If you happen to work at Facebook/Meta or know someone who does and can ask to reach out to Travis M. Clarke internally, that would be great.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by hartwork** [comment]
Has anyone had a chance yet to try reach out to @clarketm and/or colleagues at meta/Facebook?

**Comment by hartwork** [comment]
Any thoughts?

**Comment by hartwork** [comment]
Any news?

**Comment by hartwork** [comment]
Any thoughts?

**Comment by hartwork** [comment]
@pypi anyone?

**Comment by encukou** [comment]
It looks like you now are a co-maintainer, and did publish a 2.2.2 release.

**Comment by hartwork** [comment]
@encukou I received permissions to upload and used them for 2.2.2, yes. The rest of the situation remains a complete mystery to me, I haven't heard a word outside the generated PyPI grant e-mail… Should we close the ticket?

**Comment by ambv** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
We could not reach the owner, and we consider the project abandoned *by them*
per [PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).

We recommend that the PyPI Administrators promote sping (currently a maintainer)
to be the **owner** of "wait-for-it".

**Comment by ewdurbin** [comment]
`Owner` role on `wait-for-it` Project granted to `spring`.
