### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by oiffrig** [pypi/support#2598]
### PyPI Username

`oiffrig`

### Reason for request

Lost 2FA authentication app or security token

Due to an issue with my password manager, I no longer have access to either the 2FA generator nor the recovery codes (the info was never saved, so no backups either...). Is there a way this could be reset? I still have access to all the e-mail addresses listed in my account, as well as to the account password, only the 2FA data has been lost.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
