### ISSUE TITLE
PEP 541 Request: mailtrap

### ISSUE THREAD

**Issue by leonid-shevtsov** [pypi/support#2599]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/mailtrap

### Your PyPI username

`USER_NAME`: https://pypi.org/user/mailtrap

### Reasons for the request

Hi! The project (under the this name) is declared abandoned on PyPi by the previous owner (@msztolcman). It has been renamed, specifically to avoid conflict with our service https://mailtrap.io. Now the project formerly known as Mailtrap on PyPi is maintained as [Sendria](https://pypi.org/project/sendria/).

We (the Mailtrap team) are currently developing integration libraries for many languages, including Python. So we want to release our official SDK under the `mailtrap` name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

current (it's now released as https://pypi.org/project/sendria/): https://github.com/msztolcman/sendria

ours: https://github.com/railsware/mailtrap-python. We have also released SDKs for [Ruby](https://github.com/railsware/mailtrap-ruby) and [NodeJS](https://github.com/railsware/mailtrap-nodejs).

### Contact and additional research

I tried to contact the owner by email, received no response. Perhaps @msztolcman will comment here.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by VladimirTaytor** [comment]
+1 🙏

**Comment by andrii-porokhnavets** [comment]
+1

**Comment by msztolcman** [comment]
Hi,

Is there any path to not concern any current users? I mean: there is still some installations of current `mailtrap` package (via https://pypistats.org/packages/mailtrap), and someone will be disappointed when his environment with old `mailtrap` tool will stop work, becuase he will install Mailtrap.io SDK instead. Is there any way to notify this users to switch to other tools before, or any other solution?

Maybe a solution would be to create `mailtrap-sdk` or `mailtrap-io` or similar for Mailtrap.io, and I will add any comments/informations whatever to README to notify if someone is looking for Mailtrap.io SDK where to find it?

I'm not very attached to this name, so if you will tell me "it shouldn't be your problem", or "you must to do this or this, and this will help", I'd be glad to tranfser mailtrap package to Mailtrap.io.

**Comment by leonid-shevtsov** [comment]
We will keep the original released version intact and release our library under version 2 (with an appropriate note about name inheritance.) Existing users should be able to continue using v1 without any problem.

**Comment by encukou** [comment]
It looks like you've resolved this with the (now former owner). Can this be closed?

**Comment by leonid-shevtsov** [comment]
Yes! Thanks for reminding me.
