### ISSUE TITLE
PEP 541 Request: scikit-time

### ISSUE THREAD

**Issue by fkiraly** [pypi/support#2601]
### Project to be claimed

https://pypi.org/project/scikit-time/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/fkiraly/

### Reasons for the request

`scikit-time` is an abandoned project that is frequently confused with `sktime`, a `scikit-learn`-like library for time series modelling.
Similar to `sklearn` and `scikit-learn` both being references to the widely popular machine learning library.

`scikit-time` should become an alias for `sktime`.

`scikit-time` has only one upload, a version 0.0.0, in 2018.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/sktime/sktime

I think `scikit-time` does not have a source code URL.

### Contact and additional research

I have attempted to contact the authors by email on Jan 11 (real names are Moritz Hoffmann and Martin Scherer at Berlin university). I have not received a reply.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by fkiraly** [comment]
I see there is now a project of the same name, so PEP 541 conditions are unlikely to be satisfied.

**Comment by fkiraly** [comment]
FYI @clonker, this would be much appreciated.

**Comment by fkiraly** [comment]
Update: I have reached @clonker in February, but he hasn't communicated a decision yet. I think it makes sense to track it here.

**Comment by fkiraly** [comment]
FYI @di, not sure if you get notified of issues that are re-opened, as opposed to opened.

**Comment by TonyBagnall** [comment]
hello, the name scikit-time is mixed up in a complex split in the core developers of the toolkit previously known as sktime. The owners of the scikit-time pypi had transferred scikit-time those no longer associated with Franz Kiraly. Kiraly then contacted the scikit-time  owners directly by phone and demanded they reverse the transfer so we cannot use it. Understandably, the current owners of scikit-time do not want to have anything to do with this conflict and reverted it to their current state. I can confirm they have responded to me on the issue recently and the project is not abandoned. I do not believe transferring this to Kiraly would be in the spirit of the PSF code of conduct. We are of the opinion scikit-time should be deprecated in the same way sktime pypi is being deprecated. 
https://github.com/mloning/sktime-deprecation/

**Comment by clonker** [comment]
I confirm that i have been in contact with both @TonyBagnall and @fkiraly . At least at the time of contact there was a project fork scikit-time (now differently named) and the original project sktime. As already described by Tony, i have no intention to get involved in the conflict around sktime and as a consequence kept the access to myself and a former colleague, neither of us in any way involved with sktime. That being said i have no immediate use for the pypi package - if it is clear what should happen with it I have no issues with implementing whatever change that may be, eg transferring ownership or a deprecated message linking to both projects.
I don't think I am the right person to make that decision though.

**Comment by fkiraly** [comment]
> Kiraly then contacted the scikit-time owners directly by phone and demanded they reverse the transfer so we cannot use it. 

This is a misrepresentation of the interaction, there was no demand or threat as your lines imply, @TonyBagnall, if this is intentional then this is highly dishonest.

To the best of my understanding:

The owners of `scikit-time` were misled by the splinter group of @TonyBagnal that they were representing `sktime`, and asked for transfer of the pypi project on those grounds.

After being pointed to the repository - then called `scikit-time` by @TonyBagnall and colleagues (which said clearly it was a fork) - they understood they were misled by @TonyBagnall and decided not to be involved in the conflict.
