### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by spark-brc** [pypi/support#2602]
### PyPI Username

`spark-brc`

### Reason for request

I lost my phone, which includes my 2FA authentication app and recovery code. I still have access to the e-mail addresses listed in my account, as well as to the account password; only the 2FA data has been lost.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `spark-brc` has valid recovery codes generated as of 2022-03-08 01:35:14.515444.

Please use those recovery codes to regain access to your account.

**Comment by spark-brc** [comment]
I appreciate your help, but I also lost the recovery code when I lost my phone.

**Comment by spark-brc** [comment]
I cannot regenerate recovery codes, and I don't know the current one. Also not have the Authy app because my mobile is lost.
After successful login, I have no other working option.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
