### ISSUE TITLE
PEP 541 Request: Khoj

### ISSUE THREAD

**Issue by debanjum** [pypi/support#2603]
### Project to be claimed

`Khoj`: https://pypi.org/project/khoj

### Your PyPI username

`debsingh`: https://pypi.org/user/debsingh

### Reasons for the request

- The pypi package has a single, non-downloadable release published ~10 years ago, in March 2013 [^1]
- Its [pypi landing page](https://pypi.org/project/kho) has no readme or usable links

[^1]: https://pypi.org/project/khoj/#history

### Maintenance or replacement?

Replacement

### Source code repositories URLs

- The current project does not provide any link to to its source code
- The new project to be published in it's place: https://github.com/debanjum/khoj

### Contact and additional research

I emailed the email address mentioned on the package pypi landing page but it does not exist anymore

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "Khoj" has been deemed invalid. Additionally, the owner did not
respond in a week. (The e-mail bounced.)
We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `debsingh`.

**Comment by debanjum** [comment]
Thanks for the update folks! Let me know if anything else is required from my side to complete the project transfer?

**Comment by ewdurbin** [comment]
`Owner` role for `khoj` Project granted to `debsingh`
