### ISSUE TITLE
PEP 541 Request: mtpy

### ISSUE THREAD

**Issue by kujaku11** [pypi/support#2608]
### Project to be claimed

`mtpy`: https://pypi.org/project/mtpy/

### Your PyPI username

`kujaku11`: https://pypi.org/user/kujaku11/

### Reasons for the request

The maintainer of mtpy Zhang01GA unfortunately passed away and was the sole owner of mtpy.  I am now the main contributor and maintainer and would like to claim mtpy for future releases.  

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/MTgeophysics/mtpy

### Contact and additional research

Unfortunately the original maintainer passed away.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable. (Unfortunately we can't verify that the current owner did pass away.)

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
We could not reach the owner, and we consider the project abandoned per
[PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).
We recommend that the PyPI Administrators assign kujaku11 as the new
owner of "mtpy".

**Comment by ewdurbin** [comment]
`Owner` role on `mtpy` Project granted to `kujaku11`
