### ISSUE TITLE
Account recovery request for testpypi

### ISSUE THREAD

**Issue by benHeid** [pypi/support#2611]
### PyPI Username

benheid

### Reason for request

Lost 2FA authentication app or security token only for testpypi.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA disabled and password reset on TestPyPI as the user/email on PyPI match.
