### ISSUE TITLE
Project Limit Request: PDFNetPython3 - 100 GB

### ISSUE THREAD

**Issue by rchennafi** [pypi/support#2613]
### Project URL

https://pypi.org/project/PDFNetPython3/

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a python wrapper for the apryse (formerly PDFTron) SDK libraries.  It has been active since 2020. We expect to continue doing a new release for every version we do. The package may also grow as new python versions are added.

https://docs.apryse.com/documentation/windows/get-started/python3/

I understand we may be uploading too much, so we are considering private hosting and are investigating how possible that is. For now we do need a limit increase to prevent us from deleting more older versions of packages.

### How large is each release?

Currently looks to be around 1.4 GB.

### How frequently do you make a release?

Every 6 weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! This is a substantial amount, that would put this project in the top 20 projects in size on PyPI (https://pypi.org/stats/).

- Have you considered publishing abi3 wheels?
- Have you considered dropping support for EoL Python versions?
- Have you considered if a lower limit would be workable for you?

**Comment by rchennafi** [comment]
> Have you considered publishing abi3 wheels?

Publishing abi3 wheels may help but I believe it may take some effort for us to execute that. For our next release we have already setup a private repo for usage with extra-index-url and plan to use it going forward. 

> Have you considered dropping support for EoL Python versions?

Unfortunately quite a few of our users require older versions, and our removal of one version from pypi already showed us that doing so would be difficult.

> Have you considered if a lower limit would be workable for you?

We were not aware of what the average size was on pypi, so our request does seem like a bit much. If you could, an increase to 15GB from 10GB would give us enough wiggle room while we do our private repository transition/updates and exploration. Would this be possible?

As an aside, is there some way for us to host the repo on pypi but have it redirect to our file server (S3)? Or are index urls the only way around this?
