### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by wnelson03** [pypi/support#2615]
### PyPI Username

keyauth

### Reason for request

I don't remember what my email address for https://pypi.org/user/keyauth/. I'm trying to get into the account and sent a forgot password request, I've checked my main email addresses I remember and I don't see a forgot password email.

I'm quite sure I made this, I just don't have the account saved in my password manager for whatever reason. I doubt someone else would make an account with my company name and first & last name.

I believe my IP address at the time would've come from this location: https://send.bitwarden.com/#ewSYOpcK00Wfg6-sAU5gag/nE8EMwuuVOaahW8CirHV8g (using this link so I can delete later for privacy reasons)

I'm the operator of the open-source authentication software https://github.com/KeyAuth. Here you can see projects on PyPi made for my software by other people https://pypi.org/project/keyauth/, https://pypi.org/project/keyauth-api/, https://pypi.org/project/keyauthy/

Here's a TXT record for verification that I own the `keyauth.com` domain https://mxtoolbox.com/SuperTool.aspx?action=txt%3apypi.keyauth.com&run=toolpage. Let me know if you need additional information, I'll try to provide anything necessary. Thank you for your time. I apologize for the inconvenience. Typically I store logins in my password manager and don't have issues like this, I'm not sure what happened this time. I'll make sure to have my PyPi login saved in the future.

Here's some email addresses I typically use, maybe I misspelled the email or something.

`william@nelsoncybersecurity.com`
`contact@nelsoncybersecurity.com`
`keyauth.com@gmail.com`

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The user is associated with support@keyauth.com.
