### ISSUE TITLE
File Limit Request: QUEST_ERAS - 300 MB

### ISSUE THREAD

**Issue by atribera** [pypi/support#2616]
### Project URL

https://pypi.org/project/quest-eras/

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is an application suite for energy storage analysis and evaluation tools developed by Sandia National Laboratories in Albuquerque, NM, USA. It has been active for a few days now. We have bundled example data in our project for the ease of implementation by the users. This project is funded by the US Department of Energy Office of Electricity and we are trying to reach as many people as possible with our tool. For more information please check out: https://github.com/snl-quest/snl-quest.  

### Reasons for the request

We have bundled example data in the latest version and are unable to upload it to the pypi website as we have hit the limit. The project size may increase in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @atribera :wave: thanks for the report.
I've set the upload limit for `quest-eras` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice end of the week :)
