### ISSUE TITLE
PEP 541 Request: Pysion

### ISSUE THREAD

**Issue by brunocbreis** [pypi/support#2617]
### Project to be claimed

`Pysion`: https://pypi.org/project/Pysion/

### Your PyPI username

`brunocbreis`: https://pypi.org/user/brunocbreis

### Reasons for the request

I believe the project Pysion is name squatting. The files in it are basically useless.

I want to submit my project that has the same name. It is a framework for using python to generate code that works for DaVinci Resolve Fusion (hence the name, pysion).

My project can be viewed on https://github.com/brunocbreis/pysion

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Original project: https://pypi.org/project/Pysion/ (no repository has been linked)

I intend to publish: https://github.com/brunocbreis/pysion

### Contact and additional research

The username that published the original project has not made available any contact information. They also only have 2 dummy projects on PyPI.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "Pysion" has been deemed invalid. Additionally, the owner did not
respond in a few weeks.
We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `brunocbreis`.
