### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by elenakrittik** [pypi/support#2619]
### PyPI Username

`weerdy15`

### Reason for request

I have lost 2FA auth app and recovery codes for it.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `weerdy15` has valid recovery codes generated as of 2022-04-02 16:15:10.762075.

Please use those recovery codes to regain access to your account.

**Comment by ItsAleph** [comment]
I stated in the original message that i have lost 2FA recovery codes for my account. Does that mean that the account is no longer recoverable and i'll need to create a new one (in this case, can the account be deleted so that i can use the same email for new account?)?

**Comment by elenakrittik** [comment]
Replied to email.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by elenakrittik** [comment]
Thanks!
