### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sadit** [pypi/support#2620]
### PyPI Username

`sadit`

### Reason for request

Recently, I had contacted by a person asking for a package name of an unmaintained package that I developed and published in Pypi before 2008. 

I tried to give the name but I did not remember my password. I tried to enter and use the recover password option but it sends me an email address to which I have no access anymore. 

2008-prev username is: `sadit` — email: sadit@lsc.fie.umich.mx
Current address: donsadit@gmail.com (if you can change the email to reset my password)
The package in question: https://pypi.org/project/SPyRO/
Github: https://github.com/sadit/

Thank you
Eric

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hi @sadit. I've confirmed that the email address in question is bouncing.

Please contact support at pypi dot org to proceed with account recovery.

**Comment by ewdurbin** [comment]
Contacted via requested email address, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
