### ISSUE TITLE
PEP 541 Request: asbestos

### ISSUE THREAD

**Issue by itsthejoker** [pypi/support#2621]
### Project to be claimed

`asbestos`: https://pypi.org/project/asbestos

### Your PyPI username

`spoton`: https://pypi.org/user/spoton

### Reasons for the request

We are trying to release a project by the name of `asbestos`, and it appears that the name has been registered, but no releases have been created. https://pypi.org/simple/asbestos/ 

We would like to release our project, https://github.com/SpotOnInc/asbestos, at this name.

### Maintenance or replacement?

None

### Source code repositories URLs

Our project is located at https://github.com/SpotOnInc/asbestos -- the name has no releases on PyPI.

### Contact and additional research

We cannot contact the owner because there is no visibility into who the owner is. The main search does not list the page, and we found it by going through /simple/ and searching there.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "asbestos" has been deemed invalid. Additionally, the owner did not
respond in a few weeks.
We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `spoton`.

**Comment by ewdurbin** [comment]
`Owner` role on `asbestos` Project granted to `spoton`
