### ISSUE TITLE
File Limit Request: pyserini - 250 MB

### ISSUE THREAD

**Issue by lintool** [pypi/support#2623]
### Project URL

https://pypi.org/project/pyserini/

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Pyserini is a Python toolkit for reproducible information retrieval research with sparse and dense representations. Among many features, it provides bindings to [Anserini](http://anserini.io/), which is a Java toolkit built around Lucene. See:

> Jimmy Lin, Xueguang Ma, Sheng-Chieh Lin, Jheng-Hong Yang, Ronak Pradeep, and Rodrigo Nogueira. [Pyserini: A Python Toolkit for Reproducible Information Retrieval Research with Sparse and Dense Representations.](https://dl.acm.org/doi/10.1145/3404835.3463238) Proceedings of the 44th Annual International ACM SIGIR Conference on Research and Development in Information Retrieval (SIGIR 2021), pages 2356-2362, July 2021.

According to PyPI stats, Pyserini is downloaded >1k times a week: https://pypistats.org/packages/pyserini

### Reasons for the request

A recently requested feature is the inclusion of the [ONNX runtime](https://onnxruntime.ai/) to support inference with neural networks (from the Java end). Including this in the [Anserini](http://anserini.io/) fatjar will exceed the limit of the Pyserini distribution. Hence, we are requesting an increase of the limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @lintool :wave: Thanks for the report :+1: 
I've set the upload limit for `pyserini` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice end of the week :)

**Comment by lintool** [comment]
Awesome, thanks so much!
