### ISSUE TITLE
File Limit Request: databricks-connect - 350 MB

### ISSUE THREAD

**Issue by sebastianhillig-db** [pypi/support#2625]
### Project URL

https://pypi.org/project/databricks-connect/

### Does this project already exist?

- [X] Yes

### New Limit

350 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Databricks Connect is a Spark client library that lets you connect your favorite IDE (IntelliJ, Eclipse, PyCharm, and so on), notebook server (Zeppelin, Jupyter, RStudio), and other custom applications to Databricks clusters and run Spark code.

### Reasons for the request

New release slightly exceeds previous limit of 280 MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @sebastianhillig-db :wave: thanks for the report.
I've set the upload limit for `databricks-connect` to 400 MB on PyPI. Please be mindful of the frequency of releases at that size, you are almost reaching the project limit.
Have a nice end of the week :)
