### ISSUE TITLE
PEP 541 Request: cic

### ISSUE THREAD

**Issue by nolash** [pypi/support#2626]
### Project to be claimed

`cic`: https://pypi.org/project/cic

### Your PyPI username

`lash`: https://pypi.org/user/lash

### Reasons for the request

I am part of the Grassroots Economics project (https://grassroots.org), who are prototyping and pioneering Community Inclusion Currencies, or CICs for short. Hence the interest in the "cic" project name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no source code repository for the current project. We would replace with a new repository (not yet written) that involve high-level entry-point to the CIC concepts. The closest match  would be:

https://git.grassecon.net/cicnet/cic-contracts

### Contact and additional research

Have tried contacting the current owner by email provided in other python packages, but they bounce.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nolash** [comment]
that's over two months now...

**Comment by nolash** [comment]
three months.

**Comment by nolash** [comment]
It's now been more than a year since I submitted this. Is there any chance of getting it processed?

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "cic" has been deemed invalid. Additionally, the owner did not
respond to our e-mail in a few weeks.
We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by nolash** [comment]
@encukou thank you. any chance of getting a notification when/if it's deleted?

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `lash`.

**Comment by ewdurbin** [comment]
`Owner` role on `cic` Project granted to `lash`.

**Comment by nolash** [comment]
@ewdurbin that is great news. thank you!
