### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by keyboard-slayer** [pypi/support#2627]
### PyPI Username

keyboard-slayer

### Reason for request

Hello I've lost my pypi password and the email linked to that account.

I think that my email is `dalcjor@libmail.eu`.

Can you help me please ?
Thanks in advance :)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hello @keyboard-slayer. The address in question is showing as deliverable. 

Thus we have contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by keyboard-slayer** [comment]
Hello @ewdurbin 

I won't be able to read the mail since the mail provider Libmail has discontinued their activities. Is there any other way ?

**Comment by Thespi-Brain** [comment]
Hi @keyboard-slayer,

I am following up regarding your request. Are you still having an issue regarding logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
