### ISSUE TITLE
File Limit Request: scikit-misc - 300 MB

### ISSUE THREAD

**Issue by has2k1** [pypi/support#2631]
### Project URL

https://pypi.org/project/scikit-misc

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

[scikit-misc](https://github.com/has2k1/scikit-misc) provides tools for data analysis and scientific computing. It has be active for 6.5 years.

### Reasons for the request

scikit-misc wheels are big because they use static linking against hard to install libraries like blas & lapack. 

The previous version was under 100MB because:
  1. It supported 3 versions of python py38, p39 & py310.
  2. Wheels for WindowsOS used dynamic linking

The upcoming version will be more than 100MB because:
  1. It will py38, py39, py310, py311 & py312 (as soon as it is released).
  2. Wheels for WindowsOs will use static linking [for](https://github.com/has2k1/scikit-misc/issues/12) [easy](https://github.com/has2k1/scikit-misc/issues/4) [installation](https://github.com/has2k1/scikit-misc/issues/16).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @has2k1 :wave:
I've set the upload limit for `scikit-misc` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
have a nice rest of the week!
