### ISSUE TITLE
PEP 541 Request: QMI

### ISSUE THREAD

**Issue by qraa** [pypi/support#2632]
### Project to be claimed

`QMI`: https://pypi.org/project/QMI

### Your PyPI username

`qraa`: https://pypi.org/user/qraa

### Reasons for the request

We believe this project abandoned because:

- One version (version 0.1) is created in 2014, since then no releases happened.
- The GitHub project belonging to the package is non existing.  
- The author of the package in PyPI does not reply to the email (email not existing anymore).  

Over the past couple of years we internally developed the QMI (Quantum Measurement Infrastructure) framework. We recently open-sourced the software, and intend to package the software via PyPI.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project refers to dead link:
https://github.com/HongSeokHwan/qmi

New intended repository:
https://github.com/QuTech-Delft/QMI

### Contact and additional research

I tried contacting the corresponding maintainer and author of the pypi package: https://pypi.org/user/madusin/, and forwared the mail to "shhong" who is listed as an author of [another package](https://pypi.org/project/krxholiday/) maintained by madusin. 

![Screenshot from 2023-02-24 17-11-03](https://user-images.githubusercontent.com/54939695/221233848-72d5ed42-6cc0-45e7-8557-8fb1d0ba23b6.png)

However, the mail was not delivered, indicating the email address is abandoned too.

![obfuscated](https://user-images.githubusercontent.com/54939695/221229181-509b0363-ac74-4801-93a0-f93fc7fa7987.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "QMI" has been deemed invalid. Additionally, we could not reach the owner.
We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `qraa`.

**Comment by ewdurbin** [comment]
`Owner` role on `qmi` Project granted to `qraa`.
