### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by HelioGuilherme66** [pypi/support#2635]
### PyPI Username

'HelioGuilherme66'

### Reason for request

- Lost 2FA authentication app or security token

Username and Password are OK
I have successfully released packages today at https://pypi.org/project/robotframework-ride/2.0rc1

Thank you for your assistance.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `HelioGuilherme66` has valid recovery codes generated as of 2020-03-12 22:14:19.889361.

Please use those recovery codes to regain access to your account.

**Comment by HelioGuilherme66** [comment]
@ewdurbin I cannot regenerate recovery codes, and I don'r know the current one. Also not having the Authy app because mobile is broken.
After successful login, I have no other working option:
![image](https://user-images.githubusercontent.com/2866630/222014777-85ad6249-7388-4e5c-a2b8-8b1fd1b98844.png)

**Comment by HelioGuilherme66** [comment]
@ewdurbin  It is now impossible for me to make a release of my project because Legacy release is not working.

As I said before, I don't have authentication application, nor API token, nor Recovery codes. I only know username and password.

Isn't there any way to reset, or send to me Recovery Codes?
 
Must I create a new account and request project owner to add me to project?

Thanks!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
