### ISSUE TITLE
Project Limit Request: concrete-compiler - 20 GB

### ISSUE THREAD

**Issue by youben11** [pypi/support#2637]
### Project URL

https://pypi.org/project/concrete-compiler/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It's a compiler that let's you define computation on encrypted data (computation happens encrypted using Fully Homomorphic Encryption). Both [Concrete-ML](https://github.com/zama-ai/concrete-ml) and [Concrete-Numpy](https://github.com/zama-ai/concrete-numpy) are based on it.

### How large is each release?

4 Linux wheels at ~ 60 MB
3 MacOS wheels at ~ 40 MB

The project has to include LLVM/MLIR, which makes it this big.

### How frequently do you make a release?

currently ~ 3 times / month, but we are thinking of reducing this to use the space more efficiently.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @youben11 :wave:
I tried to visit the homepage of the project, but it seems the project doesn't exist (or maybe it's private?) https://github.com/zama-ai/concrete-compiler is that a valid url?

**Comment by youben11** [comment]
Hey @cmaureir , yes it's currently private (should be opensource at some point)

**Comment by cmaureir** [comment]
ah, OK.
As a general advise, consider exploring the limited api, so you can avoid having one-wheel-per-python-version and can provide one wheel per platform: https://docs.python.org/3/c-api/stable.html
I've set the project limit for `concrete-compiler` to 20 GB on PyPI. Please be mindful of the frequency of releases.
Have a nice week!

**Comment by youben11** [comment]
That was quick, thanks! I honestly didn't know this is possible with binary python extensions. We will try to take advantage of this in later releases.

**Comment by youben11** [comment]
Hello @cmaureir, as you were the one suggesting making a wheel without minor version of python, I figured you might know how to do this. I've been looking around, and I couldn't find some options or a specific py implementation to use to generate a wheel that has `cp3-cp3` for example. Could you please point me to some docs that explains how to do this?
Thanks
