### ISSUE TITLE
PEP 541 Request (provisional): python-xmp-toolkit

### ISSUE THREAD

**Issue by zougloub** [pypi/support#2638]
### Project to be claimed

`python-xmp-toolkit`: https://pypi.org/project/python-xmp-toolkit/

### Your PyPI username

`zougloub`: https://pypi.org/user/zougloub

### Reasons for the request

As I was working on including pypy3 support of sympy & al on python packages on gentoo (https://bugs.gentoo.org/894030 since 2023-02-12 and more seriously since 2023-02-17), I realized that python-xmp-toolkit is an optional dependency of mainstream packages (eg. python-xmp-tooklit > pikepdf > cairo-cffi > matplotlib > mpmath > sympy), and it was failing its test suite.
As I was working on fixing this, I noticed that the github repository of the project got archived (on 2023-02-20).
I am currently trying to reach the maintainers (since 2023-02-21) and hopefully will close this issue soon, so please consider this as a provisional request for now.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Hopefully the current project can continue to exist: https://github.com/python-xmp-toolkit/python-xmp-toolkit
Failing that, my current fork is at https://github.com/exmakhina/python-xmp-toolkit

### Contact and additional research

On 2023-02-21 I opened an issue in my fork and highlighted the recent contributors and owners:
https://github.com/exmakhina/python-xmp-toolkit/issues/1

On 2023-02-27 I e-mailed an owner after having seen that he had recent activity on pypi:
https://pypi.org/user/lnielsen/

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
It looks like you now are a co-maintainer, and did publish a 2.0.2 release.
