### ISSUE TITLE
PEP 541 Request: aeon

### ISSUE THREAD

**Issue by aiwalter** [pypi/support#2639]
### Project to be claimed

`aeon`: https://pypi.org/project/Aeon

### Your PyPI username

`aiwalter`: https://pypi.org/user/aiwalter

### Reasons for the request

`Aeon` is an abandoned project with last release in 12. Mai 2015 and 3 stars on GitHub.

We are developing a framework for machine learning with time series data, currently named under the alias `scikit-time`. As the PyPI `scikit-time` is already taken we came up with the name `aeon` as suitable.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/scikit-time/scikit-time

### Contact and additional research

We tried to contact the "maintainer" of `Aeon` via mail and LinkedIn, without any response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by logicabrity** [comment]
Hello, project owner of Aeon here. I am not unresponsive, I was just not given enough time to reply after the initial contact on Friday afternoon.

The project is not abandoned, merely feature-complete. Still runs too. I'm happy to give up the name though, but there is no possibility to do that via the web interface. Could it be renamed to aeon-legacy, to match the name I have given it on GitHub now?

And:

> "maintainer"

Were the scare quotes really necessary?

**Comment by aiwalter** [comment]
thanks for response @logicabrity 

> Were the scare quotes really necessary?

Sorry was not meant like this, just wanted to emphasize that the project looked stale to me when looking at it. Can you try to add me as a maintainer/owner of the PyPI? I think that is how transitions works, there is no separate functionality for that afaik

**Comment by yeraydiazdiaz** [comment]
Hello @logicabrity, you can add `aiwalter` as an owner in https://pypi.org/manage/project/Aeon/collaboration/

There is no renaming functionality in PyPI, you would have to upload the project with the new name.

**Comment by aiwalter** [comment]
closing as handle got handed over. thx everybody!
