### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MattGal** [pypi/support#2640]
### PyPI Username

MattGal

### Reason for request

Lost 2FA authentication app or security token - I don't seem to have a PyPi auth app setup and I never generated recovery codes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
2FA reset complete after dropping roles on projects.
