### ISSUE TITLE
PEP 541 Request: docile

### ISSUE THREAD

**Issue by simsa-st** [pypi/support#2642]
### Project to be claimed

`docile`: https://pypi.org/project/docile

### Your PyPI username

`simsa-st`: https://pypi.org/user/simsa-st/

### Reasons for the request

The project contains only generic project files with no custom logic. It first appeared on github on Dec 8, 2019 with the last commit on Jan 9, 2020 and last pypi release on Dec 9, 2019 and it has 0 stars. The author is not responding to emails.

In contrast our project with the same name is actively developed, it has 25 stars and it is being used in a publicly available  research competition.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

current project: https://github.com/demangejeremy/docile

new project: https://github.com/rossumai/docile

### Contact and additional research

I have written three emails in the past 12 days to the author's email address listed on https://pypi.org/project/docile/. I didn't receive any response and the third email returned with "Address not found" because the domain couldn't be found.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "docile" has been deemed invalid. Additionally, the owner did not
respond in a few weeks.
We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `simsa-st`.

**Comment by ewdurbin** [comment]
`Owner` role on `docile` Project granted to `simsa-st`
