### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jaytrairat** [pypi/support#2644]
### PyPI Username

jaytrairat

### Reason for request

Lost 2FA authentication app and security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `jaytrairat` has valid recovery codes generated as of 2022-05-06 04:51:19.868793.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
Marking as abandoned. This issue will be closed in 7 days.
