### ISSUE TITLE
Upload Wheel to pypi Fails With "503: Service Unavailable"

### ISSUE THREAD

**Issue by eehlers** [pypi/support#2645]
**Describe the bug**

When I try to upload a wheel to pypi, it fails with "503: Service Unavailable"

**Expected behavior**

I would expect the upload to succeed.

**To Reproduce**
```
python -m twine upload --repository testpypi OREAnalytics_Python-1.8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Uploading distributions to https://test.pypi.org/legacy/
Uploading OREAnalytics_Python-1.8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
100% ---------------------------------------- 487.1/487.1 MB • 07:56 • 885.7 kB/s
WARNING  Received "503: Service Unavailable"
         Package upload appears to have failed. Retry 1 of 5.
```
**My Platform**

I have attempted the upload both from the DOS command line and from the linux command line.

**Comment by ewdurbin** [comment]
Hi @eehlers, Is this still reproducible? We're not seeing any associated errors or failures in our backend.

**Comment by eehlers** [comment]
Hello, Many thanks for getting back to me.  It fails every time I try it.  As I write this I am running a job which attempts 5 uploads and 2 of them have failed so far.  Searching other posts I see that some people have a problem with the upload timing out and I wonder if that might be the case here, our file is 487MB.

**Comment by ewdurbin** [comment]
Ah, just noticed the timing. I'm not surprised that uploads are failing as they are likely timing out at our loadbalancer. We're working on improving visibility at that layer.

Unfortunately for files that size, sufficient bandwidth is necessary to keep requests from timing out.

**Comment by eehlers** [comment]
Thank you very much for taking a look!
