### ISSUE TITLE
PEP 541 Request:`neptune` - Test PyPI

### ISSUE THREAD

**Issue by Raalsky** [pypi/support#2646]
### Project to be claimed

`PROJECT_NAME`: https://test.pypi.org/project/neptune/

### Your PyPI username

`USER_NAME`: https://test.pypi.org/user/neptune-deployer/

### Reasons for the request

We (Neptune Labs Inc. - https://neptune.ai/) are about to rename our package `neptune-client` to `neptune`. This was partially done and we currently maintain all the following packages:
- https://test.pypi.org/project/neptune-client/
- https://pypi.org/project/neptune-client/
- https://pypi.org/project/neptune/

with almost the same source code.

Mostly due to company ownership changes, we lost access to [Neptune](https://test.pypi.org/user/Neptune/) user and as a result, we're not able to maintain further the `neptune` package on **Test PyPI**.

We would like to transfer the ownership of both packages maintained by [Neptune](https://test.pypi.org/user/Neptune/) user to [neptune-deployer](https://test.pypi.org/user/neptune-deployer/).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Old -> Probably lost
New -> https://github.com/neptune-ai/neptune-client , same as for non-test PyPI `neptune` package

### Contact and additional research

There were probably several attempts to reset a password for "Neptune" user but it looks like the email domain is out of our ownership.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
Packages on Test PyPI should be given to the main PyPI owner with no red tape.

**Comment by ewdurbin** [comment]
neptune-deployer added as owner of Neptune on test.pypi.org
