### ISSUE TITLE
PEP 541 Request: `ott`

### ISSUE THREAD

**Issue by michalk8** [pypi/support#2647]
### Project to be claimed

`ott`: https://pypi.org/project/ott

### Your PyPI username

`ott`: https://pypi.org/user/ott

### Reasons for the request

This project has been abandoned for 4+ years (last release is on [17.01.2017](https://pypi.org/project/ott/#history)).

We (cc @marcocuturi) would like to reclaim this name for our project called [ott-jax](https://pypi.org/project/ott-jax/), which is under activate development. In the near future, we would like to expand our package to include additional backends (such as [PyTorch](https://pytorch.org/)) and we think it might be better to have these backends in the same codebase and use extra requirements (e.g., `ott[jax]` and `ott[torch]`), rather than maintaining 2 separate projects (e.g., `ott-jax` and `ott-torch`).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: https://github.com/entipck/Ott/
Replacement: https://github.com/ott-jax/ott/

### Contact and additional research

We have reached out to @scopatz, who in a private e-mail conversation confirmed that @entipck re-uploaded his [exofrills](https://github.com/scopatz/xo) repo under a new name and that @scopatz doesn't own the `ott` name on PyPI.
Unfortunately, we haven't been able to get a hold of @entipck, as there is no e-mail mentioned.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by michalk8** [comment]
@entipck could you please confirm whether you're willing to transfer the name `ott` to us?

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "ott" has been deemed invalid. Additionally, the owner did not
respond in a few weeks.
We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by michalk8** [comment]
Thanks a lot for the update! One question: will the project name be transferred to us or just deleted and made available for anyone to take it?

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `ott`.

**Comment by ewdurbin** [comment]
`Owner` role on `ott` Project granted to `ott`
