### ISSUE TITLE
Project Limit Request: semgrep - 15 GB

### ISSUE THREAD

**Issue by spencerdrak** [pypi/support#2648]
### Project URL

https://pypi.org/project/semgrep/

### Does this project already exist?

- [X] Yes

### New limit

15

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Semgrep is an open-source static analysis engine maintained by r2c and is a "critical project" on PyPI. We've now hit the 10Gb limit for release size. Unfortunately we're in the middle of a release and would like to continue this release, but we're unable to upload the rest of the assets for `1.14.0` due to this size limit. Semgrep has been active on PyPI since May, 2020.

We will be continuing to push releases out the door at approximately the same cadence - we can consider alternatives to decrease the size of each of the uploads, as well.

### How large is each release?

~75MB total

~25 MB each for three built distributions
~0.25MB for source bundles

We do not bundle example data, and we have not yet made efforts to reduce the size of our PyPI releases, but can consider doing so.

### How frequently do you make a release?

We release roughly once a week, sometime twice if hotfixes need to go out.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @spencerdrak :wave: thanks for the report.
I've set the project limit for `semgrep` to 15 GB on PyPI.
have a nice rest of the week

**Comment by spencerdrak** [comment]
Thanks so much!
