### ISSUE TITLE
PEP 541 Request: sentry-cli

### ISSUE THREAD

**Issue by asottile-sentry** [pypi/support#2650]
### Project to be claimed

`sentry-cli`: https://pypi.org/project/sentry-cli

### Your PyPI username

`getsentry`: https://pypi.org/user/getsentry

### Reasons for the request

it is currently being rejected:

> STDERR:twine: HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
> twine: The name 'sentry-cli' is too similar to an existing project. See https://pypi.org/help/#project-name for more information.

we own the packages which are being "confused" with it, `sentry` and `sentry-sdk`

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/getsentry/sentry-cli

### Contact and additional research

we are the owner :)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Done. I went ahead and processed this out-of-queue because this was the result of our typosquat prevention against https://pypi.org/project/sentrycli/ and not a true PEP 541 request.
