### ISSUE TITLE
PEP 541 Request: neural_network

### ISSUE THREAD

**Issue by AnhQuoc533** [pypi/support#2651]
### Project to be claimed

`neural_network`: https://pypi.org/project/neural_network

### Your PyPI username

`anhquoc`: https://pypi.org/user/anhquoc

### Reasons for the request

I want to upload my project under the name _neural-network_ on PyPi. However, it seems like someone has registered this project name with PyPi in 2016 and the project has been abandoned since then with no package for installation as well as no project description. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no link of source code repository included in the abandoned project, as the project has no description, no dowload files.
The project that I intend to publish: https://github.com/AnhQuoc533/neural-network

### Contact and additional research

The only contact information that is listed in the project is the owner's gmail. I have sent the owner an email and no response so far.

![image](https://user-images.githubusercontent.com/64084385/222535729-88225295-2e5f-445c-9642-dbd7ea4cd627.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
The project "neural_network" has been deemed invalid. Additionally, the owner did not
respond in a few weeks.
We recommend that the PyPI Administrators delete the project and make the
name available for registration.

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `anhquoc`.

**Comment by ewdurbin** [comment]
`Owner` role on `neural_network` Project granted to `anhquoc`.
