### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by psafont** [pypi/support#2653]
### PyPI Username

`psafont`

### Reason for request

I lost access this account because a password reset has been forced and I lost access to its primary email address. This address is managed by my previous employer as I forgot to change it to my personal email, like I did with the testpypi account: https://test.pypi.org/user/psafont/ as well as this github account: https://github.com/psafont

Please let me know what other information I can give you to demonstrate my identity and reset the account.

Thanks,
Pau

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact support@pypi.org, reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by psafont** [comment]
I've sent the email, thanks

**Comment by ewdurbin** [comment]
Confirmation complete. Email has been updated as requested and a password reset issued, you should be able to regain access to your account after completing the password reset.

**Comment by psafont** [comment]
Thanks!
