### ISSUE TITLE
PEP 541 Request: sibilant

### ISSUE THREAD

**Issue by andreabak** [pypi/support#2654]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/sibilant

### Your PyPI username

`USER_NAME`: https://pypi.org/user/abk16

### Reasons for the request

The name is currently being rejected, claiming it is not allowed, but without further information:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'sibilant' isn't allowed. See https://pypi.org/help/#project-name for more information.
```
On test.pypi.com it can be successfully uploaded (see [test project](https://test.pypi.org/project/sibilant/))
No other package seems to exist with the same name in the PyPI index.
I don't see any reason why this name would not be allowed.

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/andreabak/sibilant

### Contact and additional research

I am the owner of the project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by andreabak** [comment]
Any update on this? I've retried recently, but still same result. @di ? @ewdurbin ?

**Comment by ewdurbin** [comment]
Sibilant was on our prohibited project name list due to being used as part of a previous typo squatting campaign.

'sibilant' released to 'abk16'.
