### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by SamedZirhlioglu** [pypi/support#2656]
### PyPI Username

SamedZZZZ

### Reason for request

I have lost my phone. My keys are in that phone and now I can't get recovery codes and the authenticator application. So I need to recover my account now.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `SamedZZZZ` has valid recovery codes generated as of 2022-02-22 14:39:02.722394.

Please use those recovery codes to regain access to your account.

**Comment by SamedZirhlioglu** [comment]
Yes, codes can be valid but I can't find those. Because my old phone is broken with codes in it. i don't have access to those codes.

**Comment by SamedZirhlioglu** [comment]
Yes, codes can be valid but I can't find those. Because my old phone is broken with codes in it. i don't have access to those codes.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by SamedZirhlioglu** [comment]
Thanks for contact on e-mail. I replied already

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
