### ISSUE TITLE
Project Limit Request: pygame - 40 GB

### ISSUE THREAD

**Issue by illume** [pypi/support#2657]
### Project URL

https://pypi.org/project/pygame

### Does this project already exist?

- [X] Yes

### New limit

40GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

multi media, year 2000

### How large is each release?

64 binary wheels currently 500MB or so
removed debug data from binaries
removed some older pre-releases
stopped supporting still used but older pythons

### How frequently do you make a release?

different frequencies

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
x-ref https://github.com/pypi/support/issues/1456

I've bumped the limit to 40 GB. :)

**Comment by illume** [comment]
thank you
