### ISSUE TITLE
File Limit Request: pyg4ometry - 150 MB

### ISSUE THREAD

**Issue by stewartboogert** [pypi/support#2658]
### Project URL

https://pypi.org/project/pyg4ometry/

### Does this project already exist?

- [X] Yes

### New Limit

150 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project depends on and C and C++ library dependancies (compiled without debug or symbols). 

Bundled C/C++ 

- ROOT a data analysis framework for high energy physics 
- CGAL computational geometry algorithms library 
- OpenCASCASE (CAD libraries) 

Bundled data 

- Very little data (small test/example files) 
- Large number of python tests which also serve as documentation for users
- Insignificant compared to the libraries 

### Reasons for the request

The manylinux wheels are relatively large. The project is widely used by scientists but because the packaging and distribution via pypi is not yet working and so  a lot of support building the C/C++ library deps for linux. 

Effort will be put into separating the ROOT, CGAL and OpenCASCADE dependences to separate wheels. The python interfaces (via pybind11) are relatively complete but not at a state of maturity to publish as separate packages on pypi. This is on the roadmap and the package pyg4ometry will likely be split into 4 packages, for example

- pyg4ometry 
- pyROOT 
- pyCGAL
- pyOpenCascade  

Each probably having a manylinux wheel size of 30-40 Mbyte and be useful for other users who wish to have python interfaces to these packages. 

OpenCascade, CGAL and ROOT provide a lot of functionality which covers future development, additional libraries are probably not required for a couple of years.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @stewartboogert :wave: thanks for the report.
I've set the upload limit for `pyg4ometry` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice Sunday.
