### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by emeryberger** [pypi/support#2660]
### PyPI Username

`emeryberger`

### Reason for request

Lost 2FA app (had to get a new phone and lost all old authentications; switching to using USB keys).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by emeryberger** [comment]
This is *only* for TestPyPi - my account info is fine for PyPi. Thanks.

**Comment by ewdurbin** [comment]
test pypi account for emeryberger has had 2fa reset and password reset issued.
