### ISSUE TITLE
PEP 541 Request: fluke

### ISSUE THREAD

**Issue by manoss96** [pypi/support#2661]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/fluke

### Your PyPI username

`USER_NAME`: https://pypi.org/user/manos96

### Reasons for the request

I am getting the following error:

```
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/ 
The user 'manos96' isn't allowed to upload to project 'fluke'.
``` 

even though there doesn't seem to exist any other package of the same name. Is the name blacklisted for some reason, and if so, may I acquire it? I have currently uploaded my package under the name ``fluke-api``.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

My project's source code: https://github.com/manoss96/fluke

### Contact and additional research

No contact was attempted as project name doesn't seem to be occupied

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
We could not reach the owner, and we consider the project abandoned per
[PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).
We recommend that the PyPI Administrators assign manos96 as the new
owner of "fluke".

**Comment by ewdurbin** [comment]
`Owner` role on `fluke` Project granted to `manos96`.
