### ISSUE TITLE
PEP 541 Request: ccvm

### ISSUE THREAD

**Issue by KatieO4t1qbit** [pypi/support#2664]
### Project to be claimed

`ccvm`: N/A

### Your PyPI username

`katieolfert`: https://pypi.org/user/katieolfert/

### Reasons for the request

Hello!

Apologies if this was the incorrect issue type, but it seemed the most relevant.

I believe that the automated typosquatting-protection algorithm denied the name `ccvm` due to the similarity to `clvm`, however I don't believe this is a typo that a person would accidentally make. Is it possible to bypass this check and allow the name `ccvm` for my project?

Thanks!
Katie

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: N/A
New project: https://github.com/1QB-Information-Technologies/ccvm (will be made public soon, but we were hoping to get the package name confirmed first)

### Contact and additional research

I have been unsuccessful in finding a project with this name. I own the `ccvm` project on TestPyPI.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by fredp4t1qbit** [comment]
halp

**Comment by KatieO4t1qbit** [comment]
Please disregard. We have chosen a different name for our project (`ccvm-simulators`).
