### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by williamcroberts** [pypi/support#2668]
### PyPI Username

wcrobert

### Reason for request

Lost 2FA application 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `wcrobert` has valid recovery codes generated as of 2021-04-15 18:18:08.333472.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
Marking as abandoned. This issue will be closed in 7 days.

**Comment by williamcroberts** [comment]
> Marking as abandoned. This issue will be closed in 7 days.

Sorry @ewdurbin I was away for the whole month. I don't have those recovery codes. I am completely locked out.

**Comment by Thespi-Brain** [comment]
Hi @williamcroberts,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let me know, and I will start an account recovery process for you to reset your account, thanks!

**Comment by billatarm** [comment]
Yes I still need a recovery process

**Comment by Thespi-Brain** [comment]
Hi @williamcroberts,

In order for me to start the recovery process, we need a valid primary email address on your account. It looks like the one we have is bouncing. Please contact support@pypi.org with a new email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/2668). We will proceed from there. Thanks!

**Comment by williamcroberts** [comment]
Email sent

**Comment by Thespi-Brain** [comment]
Hi @williamcroberts,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by williamcroberts** [comment]
Can confirm recovery was successful, thank you!
