### ISSUE TITLE
PEP 541 Request: airplane

### ISSUE THREAD

**Issue by ericliuche** [pypi/support#2670]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/airplane

### Your PyPI username

`USER_NAME`: https://pypi.org/user/eric-airplane

### Reasons for the request

This project has been abandoned for 8 years ([last release](https://pypi.org/project/airplane/#history) and [last commit](https://github.com/C-Codes/Airplane/commits/master) were both back in 2015). 

We at [Airplane](https://airplane.dev) (cc @airplanedev) would like to reclaim this name for our project currently called [airplanesdk](https://pypi.org/project/airplanesdk/), which is under activate development. 

Our customers often write in with issues caused by them accidentally specifying `airplane` (the abandoned project) instead of `airplanesdk` (the project we publish) in their requirements. Being able to take the `airplane` package name would greatly improve the experience for our Python users.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: https://github.com/C-Codes/Airplane/
Replacement: https://github.com/airplanedev/python-sdk/

### Contact and additional research

We have attempted to reach the package owner over email at [chruss@gmx.de](mailto:chruss@gmx.de) multiple times with no response. The first time we reached out was two years ago in July 2021 and most recently a month ago in February 2023.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ericliuche** [comment]
Hi @yeraydiazdiaz, just wanted to check if there were any updates here. Thanks!

**Comment by ericliuche** [comment]
Bumping one more time

@yeraydiazdiaz @ewdurbin @cmaureir

**Comment by ericliuche** [comment]
Bumping again

@yeraydiazdiaz @ewdurbin @cmaureir

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `eric-airplane`.

**Comment by ewdurbin** [comment]
`Owner` role on `airplane` Project granted to `eric-airplane`.
