### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by xZett0** [pypi/support#2671]
### PyPI Username

`SirLez`

### Reason for request

Hi, i am a contributor to a python project called SAmino, recently the owner of that project has passed away due to the injuries he got from the earthquakes in turkey, and as it is his will i am required to delete his projects including the SAmino project , and i can't access his account, i know it is not the correct form to ask for such thing in but i couldn't find anything related to deceased people policy in your faq page, and i have contact to his family although its not direct and if you do not approve of my request then i understand 100% its because proof, i am hopeless without this request being approved, we already got a hold of his github account through his family and we were able to hide the projects raspertory and i wish we could have access to his gmail so we could delete his projects from his pypi account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please re-file as a PEP 541 request.
