### ISSUE TITLE
PEP 541 Request: battery

### ISSUE THREAD

**Issue by yunruse** [pypi/support#2673]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/battery

### Your PyPI username

`USER_NAME`: https://pypi.org/user/yunruse

### Reasons for the request

The package is clearly both abandoned and having only ever been intended for testing purposes. This is evidenced by the commit [Testing Pypi deployment done](https://github.com/keyurgolani/utilities-python/commit/743d26b226cd6ac48f2c333288411dff7c770066), which appears to copy from an online tutorial. This indeed was the most recent commit on Aug 4 2017. The download link, in any case, does not even work.

The package does what it implies – providing battery status – but in a rather flaky manner on macOS. The package I have developed in its place does the same and has been tested on a variety of operating systems and devices. (As noted, it is intended as a complement to `psutil`, which provides some overlapping behaviour).

As the original package was some form of testing on a tutorial, this is a replacement rather than a fork.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The original test project: https://github.com/keyurgolani/utilities-python

My intended replacement:
https://github.com/yunruse/battery
currently uploaded for use at:
https://pypi.org/project/battery-yunruse/

### Contact and additional research

I have emailed the owner's email (according to their GitHub profile) on the 3rd of March to politely request this, but have received no reply.

Thank you for your time! (I will admit this is a little scary to request, given how prominent the name is. I hope the package I've developed is useful!)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yunruse** [comment]
As per keyurgolani/utilities-python#1, the author of this package has allowed the name transfer and relinquished access to `battery` as requested.

However – I assume due to caching issues? – the name is still not available for upload. Would you be able to fix this? :s

Many thanks!

**Comment by yunruse** [comment]
Hi! The `battery` package is now completely available, its original owner having relinquished access. But I still get the following error; I assume it is still a lock in PyPI. Is it possible I could now have access? Many thanks!

```
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/                                         
         The user 'yunruse' isn't allowed to upload to project 'battery'. See                                  
         https://pypi.org/help/#project-name for more information. 
```

**Comment by encukou** [comment]
We've confirmed that the owner deleted the project with intent to relinquish access.

We recommend that the PyPI Administrators delete the project and make the
name available for registration.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by ambv** [comment]
To be clear, we recommend the project be transferred to `yunruse`.

**Comment by ewdurbin** [comment]
`Owner` role on `battery` Project granted to `yunruse`.
