### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tjdallman** [pypi/support#2675]
### PyPI Username

timdallman

### Reason for request

Hello.  I'm the mainter of the project https://pypi.org/project/snapperdb/
I have now moved organisation ahdn have lost access to the email address tim.dallman@phe.gov.uk
Please can I request account recovery.
May thanks,
Tim Dallman
t.j.dallman@uu.nl
https://www.uu.nl/staff/TJDallman

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Thespi-Brain** [comment]
Hi @tjdallman,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
