### ISSUE TITLE
PEP 541 Request: dodal

### ISSUE THREAD

**Issue by callumforrester** [pypi/support#2676]
### Project to be claimed

`dodal`: https://pypi.org/project/dodal

### Your PyPI username

`DiamondLightSource`: https://pypi.org/user/DiamondLightSource

### Reasons for the request

The name does not appear to be in use, my organisation (pypi username: DiamondLightSource) has a project with this name that we wish to publish.

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/DiamondLightSource/dodal

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by callumforrester** [comment]
I believe this is the same situation as another one of our projects, `pvi` encountered in https://github.com/pypi/support/issues/1558: it is in the list of prohibited names. The previous issue was solved by @yeraydiazdiaz

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
We could not reach the owner of `dodai`, and we consider the project abandoned per
[PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).

We recommend that the PyPI Administrators allow DiamondLightSource to register "dodal",
and remove the conflicting `dodai` project if necessary.

**Comment by ambv** [comment]
To be clear, the `dodai` (with `i`) project is currently invalid and can be deleted to free the conflict. We don't need it transferred.

**Comment by ewdurbin** [comment]
'dodal' released to 'DiamondLightSource'.
