### ISSUE TITLE
PEP 541 Request: n3d

### ISSUE THREAD

**Issue by alisterburt** [pypi/support#2678]
### Project to be claimed

`n3d`: https://pypi.org/project/n3d

### Your PyPI username

`alisterburt`: https://pypi.org/user/alisterburt

### Reasons for the request

I believe that the project has been abandoned (last commit and release in 2014) 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/grudko/n3d

### Contact and additional research

I have contact the maintainer both by [github issue](https://github.com/grudko/n3d/issues) and email over the last few weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
Per PEP-541: *Projects are never removed from the Package Index solely on
the basis of abandonment. Artifacts uploaded to the Package Index hold
inherent historical value.*

One of the [requirements for removal of an abandoned
project][pep-removal-abandoned] is:

* the candidate is able to demonstrate why a fork under a different name
  is not an acceptable workaround

If you have a new project, why can you not use a different name for it?

[pep-removal-abandoned]: https://peps.python.org/pep-0541/#removal-of-an-abandoned-project

**Comment by encukou** [comment]
I'll close the issue, please reopen (or open a new one) if you want to continue.
