### ISSUE TITLE
File Limit Request: aws-analytics-reference-architecture - 150 MB

### ISSUE THREAD

**Issue by vgkowski** [pypi/support#2681]
### Project URL

https://pypi.org/project/aws-analytics-reference-architecture/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It's an AWS CDK library that contains lots of various CDK Constructs. We are removing dependencies that can be removed like the "@aws-cdk/lambda-layer-kubectl-v22": "2.0.6"

### Reasons for the request

we recently added some capabilities to write data into multiple targets that requires clients and so increase size of the package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @vgkowski :wave: thanks for the report.
I've set the upload limit for `aws-analytics-reference-architecture` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice Sunday
