### ISSUE TITLE
PEP 541 Request: precondition

### ISSUE THREAD

**Issue by vlad17** [pypi/support#2682]
### Project to be claimed

`precondition`: N/A

### Your PyPI username

`vlad17`: https://pypi.org/user/vlad17

### Reasons for the request

I'm open sourcing preconditioning deep learning optimizers. Searching pypi, `precondition` is not taken.

However, it seems that attempting to publish a package with that name fails:

```
$ python3 -m twine upload  dist/*                                                                                
Uploading distributions to https://upload.pypi.org/legacy/
Uploading precondition-0.1.0-py3-none-any.whl                                                                                                                                
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.7/54.7 kB • 00:00 • 29.8 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                                                                              
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                                     
         The name 'precondition' isn't allowed. See https://pypi.org/help/#project-name for more information. 
```

It's unclear which of the reasons linked by the document above is blocking package name creation.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/google-research/precondition

### Contact and additional research

As far as I can tell, there is no `precondition` package.

There is a `preconditions` package, which quite unrelated to preconditioning optimizers in optimization. That package is about listing many precondition**s** for Hoare-logic enforcement. Here we are interested in the precondition**ed** gradient.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
The `preconditions` package looks like it still works with Python 3.10, and it seems it was recently dropped as a dependency of a reasonably popular package. It shouldn't be removed.

The worry here is that if `preconditions` is taken over by a malware peddler, users of `precondition` would be at risk if they misspell the name. If you're OK with that risk, we can recommend that PyPI admins allow you to use the name.


Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
If technically possible, we recommend that the name `precondition` is made available despite the clash with `preconditions`.

**Comment by ewdurbin** [comment]
'precondition' released to 'vlad17'.
