### ISSUE TITLE
PEP 541 Request: bonaparte

### ISSUE THREAD

**Issue by kaechele** [pypi/support#2683]
### Project to be claimed

`bonaparte`: https://pypi.org/project/bonaparte

### Your PyPI username

`kaechele`: https://pypi.org/user/kaechele

### Reasons for the request

The bonaparte project is currently invalid as there are no installable releases.
https://pypistats.org/search/bonaparte turns up empty as well. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project's git repository: https://github.com/gjcoombes/bonaparte (Error 404)
New project's git repository: https://github.com/kaechele/bonaparte

### Contact and additional research

I have tried contacting the current owner of the project (@gjcoombes)  both on the email address available through PyPI as well as an email address I found in `git log` of some of the other repositories the user has on GitHub and have received no reply.
My first attempt was on 2023-02-21 to an @gmail.com address found in a `git log`.
The second attempt was on 2023-03-03 to the @darkseas.com address used in PyPI. This email was undeliverable. I then tried the same email with @darkseas.org as that had been used in a `git log` as well but received no reply so far.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "bonaparte" has been deemed invalid. Additionally, the owner did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to kaechele.

**Comment by ewdurbin** [comment]
`Owner` role on `bonaparte` Project granted to `kaechele`
