### ISSUE TITLE
PEP 541 Request: pai

### ISSUE THREAD

**Issue by pitt-liang** [pypi/support#2686]
### Project to be claimed

`pai`: https://pypi.org/project/pai

### Your PyPI username

`alibaba-pai`: https://pypi.org/user/alibaba-pai

### Reasons for the request

Hello!

We want to publish a package named in `pai`, but twine responsed with 400 Bad request:

```plain

NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'pai' isn't allowed. See https://pypi.org/help/#project-name for more information.

```

We have search the Project in PyPI, seems the project doesn't exists.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The source code is not open source currently.
The old project can be found from here: https://pypi.org/project/alipai/#history

### Contact and additional research

The project seems doesn't exists ( or no release?) , visiting to https://pypi.org/project/pai reponsed with 'We looked everywhere but couldn't find this page'.  We couldn't found a existing author for the project `pai`.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner of the similarly named empty project `pal`.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The similarly named project "pal" has been deemed invalid. Additionally, the owner
agreed to delete it deletion.
We recommend that the PyPI Administrators delete the project `pal` so that the requested name “pai” becomes available.

**Comment by ambv** [comment]
To be clear, the project `pal` (with an `L`) is currently invalid so it can be deleted to resolve the name conflict. We do not need it transferred.

**Comment by ewdurbin** [comment]
'pai' released to 'alibaba-pai'.
