### ISSUE TITLE
PEP 541 Request: zcatalyst

### ISSUE THREAD

**Issue by navinkhumaar** [pypi/support#2687]
### Project to be claimed

`zcatalyst`: https://pypi.org/project/zcatalyst

### Your PyPI username

`zohocorporation`: https://pypi.org/user/zohocorporation

### Reasons for the request

We are in the process of publishing our package in PyPI. We want to publish our package by this name: zcatalyst, which resembles our brand name (Zoho Catalyst: https://catalyst.zoho.com/) but got the following error: 403 The user 'zohocorporation'  is not allowed to upload to project 'ZCatalyst'. Hence we request you to release the package name: zcatalyst for user: zohocorporation.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

N/A

### Contact and additional research

No previous PEP 541 request with package name 'zcatalyst' found.
Can't able to contact the user as package is not listed on PyPI.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "zcatalyst" has been deemed invalid. Additionally, the owner did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to zohocorporation.

**Comment by ewdurbin** [comment]
`Owner` role on `ZCatalyst` Project granted to `zohocorporation`
