### ISSUE TITLE
Project Limit Request: tensorrt - 15 GB

### ISSUE THREAD

**Issue by zeroepoch** [pypi/support#2689]
### Project URL

https://pypi.org/project/tensorrt/

### Does this project already exist?

- [X] Yes

### New limit

15

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

TensorRT has existed as a product for about 6 years. We've started to publish wheel files under the project name `tensorrt` about 6 months ago. For our most recent release (8.6.0) we were only able to publish some of the Python versions before hitting the project size limit. We are working on reducing the size significantly for future releases using a source package and a downloader inside. I'd like to request an increase so we can complete the posting of our current release.

### How large is each release?

The most recent release is ~800MB per Python version. The majority of this space is taken up by CUDA C++ libraries which support the Python bindings. We publish wheel files for Python 3.6 to Python 3.10. We are working to deduplicate the libraries in the next releases.

### How frequently do you make a release?

Roughly every few months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @zeroepoch :wave: thanks for the details.
I've set the project limit for `tensorrt` to 15 GB on PyPI.
Have a nice week
