### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by abraithwaite** [pypi/support#2690]
### PyPI Username

`abraithwaite`

### Reason for request

My alma mater decided to forcibly terminate old email accounts in a migration from gmail to o365 with 3 months notice in April last year and I missed it.  It's the email I was using for my pypi account, for which I've also forgotten the password.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.
