### ISSUE TITLE
PEP 541 Request: bears

### ISSUE THREAD

**Issue by adivekar-utexas** [pypi/support#2691]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/bears

### Your PyPI username

`USER_NAME`: https://pypi.org/user/adivekar

### Reasons for the request

I believe this project name can be released, for the following reasons:

- This project has not been updated in 6 years. 
- It also has only 2 commits.
- I tried emailing the maintainer, but their PyPi lists a no-reply email (`elbaro@users.noreply.github.com`). Their github profile is equally devoid of information: https://github.com/elbaro. I cannot find an actual person based on the username `elbaro`. 
- The only code file is `__init__.py`, which contains 60 lines of code (for a Pandas Dataframe alternative, of which several exist): https://github.com/elbaro/bears/blob/master/bears/__init__.py

I believe this project is unlikely to be updated, and the user has made it clear they do not wish to maintain it or engage in any communication. 

I feel the project name can thus be released.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: https://github.com/elbaro/bears

Replacement project I intend to publish: https://github.com/adivekar-utexas/bears

### Contact and additional research

I tried emailing the maintainer, but their PyPi lists a no-reply email (`elbaro@users.noreply.github.com`), so my email bounced back with a "this address does not exist".

Their github profile is equally devoid of information: https://github.com/elbaro. 

I suspect `elbaro` might be a squatter, as they have also squatted on: `tinder`, `ezel`. But I cannot be 100% sure about this.

I cannot find an actual person based on the username `elbaro`: it seems to also be the name for (i) a musician (ii) a Swiss watch brand.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by adivekar-utexas** [comment]
@alex @berkerpeksag @dstufft @cmaureir it's been a while...any update on this request?

**Comment by encukou** [comment]
Per PEP-541: *Projects are never removed from the Package Index solely on
the basis of abandonment. Artifacts uploaded to the Package Index hold
inherent historical value.*

One of the [requirements for removal of an abandoned project][pep-removal-abandoned] is:

* the candidate is able to demonstrate why a fork under a different name
  is not an acceptable workaround

If you have a new project, why can you not use a different name for it?

[pep-removal-abandoned]: https://peps.python.org/pep-0541/#removal-of-an-abandoned-project

**Comment by adivekar-utexas** [comment]
@encukou thanks for looking at this old request. I've provided the relevant reasoning below, happy to hear your thoughts no this.

### Which code will be placed in this repository?

The code was recently open-sourced under this [Amazon Science repo](https://github.com/amazon-science/synthesizrr/tree/main/src/synthesizrr/base/data/sdf) but we wish to organized it as its own package. 

This code (currently named ScalableDataFrame) implements a flexible dataframe format, which allows runtime switching between memory layouts while using the same Pandas API. It works for both edge devices (low-latency) and distributed clusters (billion-row datasets for ML).

### Why the name `bears`:

This name was chosen for strong brand-association:

- "bears" more closely matches naming conventions for "Pandas" dataframe alternatives, e.g. Polars project (ref. Polar Bears). 

- Bears (the animal) imply strength and resilience, characteristics we want to embody. We particularly implement complex data operations using distributed clusters (Ray + Dask) where resilience is a very important trait.

- As a name, "bears" is short and memorable; it stands out in the landscape of software libraries. Unlike more descriptive but mundane names, "bears" is likely to stick in users' memories, fostering a stronger brand identity going forward.


### Does the existing package hold inherent historical value?

I appreciate linking this rule, and on a whole it makes sense. In this particular situation, I would argue it does not:
- The implementation is incomplete.
- The project is not updated since 2017.
- The user has given strong indication that he does not want to be contacted (by providing a no-reply email). 

Based on this, it seems safe?


Happy to hear your thoughts no this.

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
We could not reach the owner, and we consider the project abandoned per
[PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).
We recommend that the PyPI Administrators assign adivekar as the new
owner of "bears".

**Comment by LucaCappelletti94** [comment]
Hi @adivekar-utexas, this is currently among the oldest open PEP 541 requests.
As I have some more recent such requests pending, I wanted to ask you whether the PyPi admins could resolve the name conflict, or whether it has been over a year since their last administrative work on PEP 541.

**Comment by miketheman** [comment]
@adivekar-utexas Thanks for your patience.
Upon evaluating this request, we have some outstanding questions:

1. Your PyPI account does not appear to be associated with Amazon Science, nor does your GitHub account - do you still work there?
2. The linked repository has nothing other than a scaffold and really cool bear image. Is there a different repository or pull request that shows the expected changes?
3. Do you still wish for this project to be transferred to your PyPI username, or to an account more generally used for Amazon Science projects?

**Comment by adivekar-utexas** [comment]
Hi @miketheman, thanks for getting back on this!

> Your PyPI account does not appear to be associated with Amazon Science, nor does your GitHub account - do you still work there?

I do still work there. We are supposed to use our personal Githubs for Amazon Science work. For example, I recently open-sourced a code repo under the Amazon Science Github: https://github.com/amazon-science/synthesizrr, and am working towards open-sourcing another repo in the coming few weeks.

> The linked repository has nothing other than a scaffold and really cool bear image. Is there a different repository or pull request that shows the expected changes?

We are planning to both refactor this code as the "bears" repository: https://github.com/amazon-science/synthesizrr/tree/main/src/synthesizrr/base/data/sdf/
- It  contains a self-contained dataframe wrapper, which allows easy switching between dataframe formats. As Pandas is the most popular dataframe library, we thought "bears" would be a fun name (details on naming mentioned [in my comment above](https://github.com/pypi/support/issues/2691#issuecomment-2199239356)). 
- This  dataframe wrapper does not really fit the theme of the rest of the repository, which is code for a research paper on synthetic dataset generation from Large Language models. 

We were planning to do this refactor as soon as the current request is resolved, as we want the repository to be pip-installable.

> Do you still wish for this project to be transferred to your PyPI username, or to an account more generally used for Amazon Science projects?

Please transfer it to my personal PyPI username:
- PyPI: https://pypi.org/user/adivekar
- TestPyPI: https://test.pypi.org/user/adivekar

**Comment by adivekar-utexas** [comment]
Hi @miketheman , hope we can drive this to closure soon :) As the other commenter said, it has been over a year since I opened this request.

**Comment by miketheman** [comment]
> I do still work there. We are supposed to use our personal Githubs for Amazon Science work.

Please add a verified company email address to this account so we can verify that connection, since there's no other way for that to be verified right now.
The project you shared shows an identical name, but not the same user account, not linked to confirm.

**Comment by adivekar-utexas** [comment]
@miketheman I have added my verified company email to my profile now (it's adivekar@amazon.com)

**Comment by miketheman** [comment]
@adivekar-utexas Please add the verified email to your PyPI profile to match

**Comment by adivekar-utexas** [comment]
<img width="1149" alt="Image" src="https://github.com/user-attachments/assets/4c304e55-455c-4b4a-bb40-65e93eadef9d" />


@miketheman Here's a screenshot of the confirmation email, if it helps.

**Comment by miketheman** [comment]
Added 'adivekar' as 'Owner' on 'bears'

**Comment by adivekar-utexas** [comment]
Thanks @miketheman !
