### ISSUE TITLE
File Limit Request: proteusPy - 300MB

### ISSUE THREAD

**Issue by suchanek** [pypi/support#2694]
### Project URL

https://pypi.org/project/proteusPy

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

package for display, manipulation and analysis of proteins structures. The test pyPi instances load fine, but not on pypi.org. The size is a reflection of the database, and is the smallest I can make it.

### Reasons for the request

I believe the overall size should be stable at this point. Thank you for your help! Eric Suchanek, phD.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @suchanek :wave: thanks for the information.
I've set the upload limit for `proteusPy` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice day :snake:
