### ISSUE TITLE
PEP 541 Request: rdflib (on test.pypi.org)

### ISSUE THREAD

**Issue by aucampia** [pypi/support#2695]
### Project to be claimed

`rdflib`: https://test.pypi.org/project/rdflib/

### Your PyPI username

`iwan.aucamp`: https://test.pypi.org/user/iwan.aucamp/

### Reasons for the request

I'm doing most of the releases for https://pypi.org/project/rdflib/ and I'm a maintainer there, but I want to be able to test the releases.

I have emailed the current owner of https://test.pypi.org/project/rdflib/ but he did not respond yet.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/RDFLib/rdflib

### Contact and additional research

I tried contacting the current maintainer of https://test.pypi.org/project/rdflib/ on the 5th of March, 2023.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
I see you are currently an owner of https://test.pypi.org/project/rdflib/. Presumably you sorted it out with the previous owner?

I'll close this. Sorry for the delay.
