### ISSUE TITLE
PEP 541 Request: path-util

### ISSUE THREAD

**Issue by tddschn** [pypi/support#2696]
### Project to be claimed

`path-utils`: https://pypi.org/project/path-util

### Your PyPI username

`USER_NAME`: https://pypi.org/user/teddysc

### Reasons for the request

I am requesting to release a new package named `path-utils` on PyPI. Upon conducting a search for available package names, I found that the name `path-utils` is currently unavailable for use. However, there is an abandoned package named `path-util` that is similar in name and purpose to the package I intend to release.

While there have been some releases for the `path-util` package in the past, the latest release was made over 3 years ago, indicating that the package has not been updated or maintained for a significant amount of time. Furthermore, the existing releases may not be compatible with newer versions of Python or other dependencies.

I believe that the name `path-utils` would be a more suitable and descriptive name for a package that provides utility functions for interacting with $PATH. I am committed to maintaining and updating my package regularly to ensure its compatibility with the latest versions of Python and dependencies.

Therefore, I kindly request to release my `path-utils` package on PyPI under the name `path-utils`, as I believe it would not cause confusion for users who are looking for a package with a similar name. I will ensure that my package is significantly different from the existing `path-util` package to avoid any confusion for users.

Thank you for your consideration of my request.

### Maintenance or replacement?

Replacement

## About path-util (abondoned):
- https://pypi.org/project/path-util/
- https://pypi.org/simple/path-util/
- https://github.com/eyalev/path-util

## About path-utils (the package name I want to use):
- https://github.com/tddschn/path-utils

### Contact and additional research

Please see https://github.com/eyalev/path-util/issues/1 .

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
Per PEP-541: *Projects are never removed from the Package Index solely on
the basis of abandonment. Artifacts uploaded to the Package Index hold
inherent historical value.*

Also, there are multiple projects with similar names: we'd need to deal  with [`pathutils`](https://pypi.org/project/pathutils) too, at least.

If you have a new project, why can you not use a different name for it?

[pep-removal-abandoned]: https://peps.python.org/pep-0541/#removal-of-an-abandoned-project
