### ISSUE TITLE
File Limit Request: ytsaurus-pyspark - 300 MB

### ISSUE THREAD

**Issue by Alexvsalexvsalex** [pypi/support#2699]
### Project URL

https://test.pypi.org/project/ytsaurus-pyspark/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Project is the forked pyspark (https://pypi.org/project/pyspark/). It contains same files with some little changes with specific extra functionality and the size is about the same as original package (.whl ~290Mb and .tar.gz ~290Mb).
We use it in our OS solution https://ytsaurus.tech/

### Reasons for the request

Pyspark is too large and our forked package cannot be uploaded at all, so we need additional limit for file size to be able to make a release.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Alexvsalexvsalex :wave: thanks for the report.
I've set the upload limit for `ytsaurus-pyspark` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
have a nice week!
