### ISSUE TITLE
PEP 541 Request: PyStats

### ISSUE THREAD

**Issue by DamnUi** [pypi/support#2701]
### Project to be claimed

`PyStats`: https://pypi.org/project/PyStats/

### Your PyPI username

`Noni`: https://pypi.org/user/Noni/

### Reasons for the request

Yes i believe the project has been abandoned as the last update to the pip web end is close to a year and after further digging into its (github repository)[https://github.com/marcizhu/PyStats] its evident that the project has not been updated for more then 2 years and would like this name due to my current project which might benefit a lot from this.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current code i want to replace the project with -https://github.com/DamnUi/PyStats/tree/Branch-before-major10
The abandoned project - https://github.com/marcizhu/PyStats

### Contact and additional research

After conduction my further research all his projects have not been updated in 8 Months, Regardless i have still sent him an email

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
Per PEP-541: *Projects are never removed from the Package Index solely on
the basis of abandonment. Artifacts uploaded to the Package Index hold
inherent historical value.*

One of the [requirements for removal of an abandoned project][pep-removal-abandoned] is:

* the candidate is able to demonstrate why a fork under a different name
  is not an acceptable workaround

If you have a new project, why can you not use a different name for it?

[pep-removal-abandoned]: https://peps.python.org/pep-0541/#removal-of-an-abandoned-project

**Comment by DamnUi** [comment]
Many people in my college are actively working on this project and know it by this name, not having this name on pypi would be disappointing to say the least, I understand that it has historical value but not at the cost of providing value in the present day

**Comment by encukou** [comment]
We have investigated the PyPI package, and saw that it has some meaningful functionality and it seems people are still actively using it. So, we cannot transfer the name to an unrelated project.
Consider picking a different name.
