### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by javaducky** [pypi/support#2703]
### PyPI Username

k6io

### Reason for request

Unsure of (or lost) access to email address.

Tried using the "Forgot password?" functionality but no one currently on the team is receiving a reset email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
simme [at] k6.io
