### ISSUE TITLE
File Limit Request: chdb - 200 MB

### ISSUE THREAD

**Issue by auxten** [pypi/support#2704]
### Project URL

https://pypi.org/project/chdb/

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

chDB is an in-process SQL OLAP Engine powered by ClickHouse

### Reasons for the request

The clickhouse binary is HUGE. as you can see on the [clickhouse release page](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.8.15.23-lts)
I tried my best to be smaller, but it sometimes still can not be compressed to 100MB

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @auxten :wave: thanks for the report.
I've set the upload limit for `chdb` to 200 MB on PyPI and TestPyPI. 
have a nice week!
