### ISSUE TITLE
PEP 541 Request: eigen

### ISSUE THREAD

**Issue by bjornaer** [pypi/support#2706]
### Project to be claimed

`eigen`: https://pypi.org/project/eigen

### Your PyPI username

`bjornaer`: https://pypi.org/user/bjornaer

### Reasons for the request

I see the stale project with no publication since it was opened about 1yr ago. We aimed to claim eigendata but it was taken 5 days ago

### Maintenance or replacement?

Replacement

### Source code repositories URLs

there is no source for the current project it is empty.

replacement code repo: https://github.com/eigendata/eigenrules

### Contact and additional research

I have not contacted the owner directly as they do not have a provided means of contact through pypi

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by bjornaer** [comment]
would love a review on this issue :(

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "eigen" has been deemed invalid. Additionally, the owner did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to bjornaer.

**Comment by nschloe** [comment]
@encukou eigen owner here. I uploaded a new version three weeks ago! Please review the decision.

**Comment by encukou** [comment]
OK. We will review next week.

Before the qualified people get to it, let me note that per the [acceptable use policy](https://policies.python.org/pypi.org/Acceptable-Use-Policy/), PyPI does not allow content that *uses obfuscation techniques to hide or mask functionality*.

**Comment by encukou** [comment]
Obfuscated packages (like `eigen` and `x21`) are now discussed at the PSF level, here: https://github.com/psf/policies/issues/18. Thanks for opening the issue.

The discussion can take a long time (PyPI admins are busy), and I do not know how it'll end: the package can be kept in place, or removed and the name blocked (to prevent surprises for existing users).

In neither case can we release the name. @bjornaer, you will unfortunately need to find a different name for your project.
