### ISSUE TITLE
Twine Upload to PyPI package not updating some files

### ISSUE THREAD

**Issue by nikolas-virionis** [pypi/support#2707]
**Describe the bug**

Basically, I have and maintain a package in PyPI called spotify-recommender-api. The problem is recent, about a month or so, and what I have been noticing is that some files that are available on the PyPI website as a tar.gz, the ones that appear on pip install are not the ones I publish. What I mean by that is, I upload the files, via twine (i know it is not the most recent way but I had this package for a while now) and the tar.gz it generates on my machine has different files from the ones after the upload is finished and the version changed which generates bugs in the code, since one file might use some function from another file but on PyPI the second file has not been updated
**Expected behavior**

The expected behavior would be for the files that I upload to be the same as the ones publicly available
**To Reproduce**

To be honest, I am not 100% sure, since it just happened and I could not understand the cause of this issue
**My Platform**

Linux Mint 20.x.x
**Additional context**

Github repo: https://github.com/nikolas-virionis/spotify-api
The package is currently having errors on initialization because of this issue, and my 3 last attempts to fix the issue were pointless and failed

**Comment by di** [comment]
Can you tell us what the difference is? Looking at https://inspector.pypi.io/project/spotify-recommender-api/3.9.3/packages/bb/bc/92811d0e65cbb054e368ccd0267a9031634e82be38003cd479d80403af00/spotify_recommender_api-3.9.3.tar.gz/, this looks pretty much the same as https://github.com/nikolas-virionis/spotify-api/.

Can you tell us how you're building, publishing and installing this? Specific commands that help us reproduce would be ideal.

**Comment by nikolas-virionis** [comment]
Interestingly you are right, but the weird part is that on line 50 of the file core.py, I recently changed the parameters from a and b (i know it was terrible readability) to song_a and song_b (that isn't great but is a bit better). 
And the error was that there were no parameters named song_a and song_b on the function when calling the function on the recommender.py file on line 291. 
And on my machine I fixed it by opening the file on the pip package path on Linux, the python3.8/site-packages/........., and there is was not updated. And I had already executed the pip install --upgrade spotify-recommender-api so it should be updated. 
Then I uninstalled the package and installed it and still, it was not updated on the file. 
Does it take a while to be updated, normally? 
But still, I just now, uninstalled again the package, and reinstalled it, and it is still with the a and b parameters instead of the song_a and song_b parameters, whereas on the tar.gz and github repo it is already song_a and song_b. 
The weird part is that on the recommender.py:291 it is updated, so the function call is updated but the function "creation" isn't

**Comment by di** [comment]
Again, can you tell us how you're building, publishing and installing this? What's the output of `pip freeze` for this project?

**Comment by nikolas-virionis** [comment]
basically, since the beginning of the package I do the changes, change the version on setup.py, then I run python3 setup.py sdist bdist_wheel (to be honest this was the command I saw at a tutorial back when I first published the package and I just been using it ever since) and this command generates the files, then I run twine upload dist/*
This is the way i always update the package, and until very recently i never had issues with it, but maybe something changed

**Comment by cmaureir** [comment]
Could it be that you your wheel creation process is using cache files? have you tried to run the same `bdist_wheel` command on a fresh virtual environment? or maybe you could try to use https://pypi.org/project/build/ 

You also mentions "errors" which errors? maybe you can drop the full log of the command
