### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by iurygregory** [pypi/support#2708]
### PyPI Username

iurygregory

### Reason for request

Hello everyone,

I lost access to my mobile phone where I used FreeOTP  for 2FA and I also don't have my recovery codes.
Thank you for your support.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by iurygregory** [comment]
@ewdurbin tks! Sorry for the delay on this, I've respond to your email already. Tyvm!

**Comment by Thespi-Brain** [comment]
Hi @iurygregory,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by iurygregory** [comment]
@Thespi-Brain hello, yes I''m still unable to login. I've answered the email from @ewdurbin on December 19th 2023, but I haven't got any updates regarding the next steps I would need to take.

**Comment by Thespi-Brain** [comment]
Hi @iurygregory,

Thanks for replying back. I have gone ahead and reset the 2FA, recovery codes, and password on your account. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by iurygregory** [comment]
@Thespi-Brain Thanks! I was able to reset my password and access my account!
