### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mattian7741** [pypi/support#2711]
### PyPI Username

pypi@mattian.com

### Reason for request

I am getting a "No user found with that username"

And if I do a forgot password, I get an email, am able to reset my password, but am not able to log in.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Your username is not your email address. It is mattian7741
