### ISSUE TITLE
PEP 541 Request: fow

### ISSUE THREAD

**Issue by meejah** [pypi/support#2713]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/fow

### Your PyPI username

`meejah`: https://pypi.org/user/meejah

### Reasons for the request

I cannot find the project `fow` at all, and was hoping to use it (well, _am_ using it so far) for a new project name.

I do not believe any of the points in https://peps.python.org/pep-0541/#how-to-request-a-name-transfer are true and followed all the checks.

(Even if the answer is "no, you can't have that name" it would have improved my user experience if there was a way to tell that somehow  way before I got to the `twine upload` step -- I thought I'd done my "due diligence" to figure out if this was a fine name for a new project. On the "test" PyPI infrastructure, creating this project under this name succeeded w/o error).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The new project will live at https://github.com/meejah/fow (if the name can be used) or at a different name if I can't. A first public revision has not yet been pushed.

### Contact and additional research

I cannot find a current owner, or current project.

I performed the other searches from the PEP 541 document.

Before choosing the name, I searched Debian repositories and the production PyPI (via search, and by typing in the appropriate URL). After choosing it and making a minimal packaging setup, I tried uploading to the "test" PyPI (which worked).

Thanks for your attention!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by meejah** [comment]
There is now code at https://github.com/meejah/fow if that makes a difference.

**Comment by encukou** [comment]
The project "fow" has been deemed invalid. It was deleted by the owner in 2016 so it is now empty.
I see you  have released the new project as [`fowl`](https://pypi.org/project/fowl/) now. Do you still want the name `fow`?

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by meejah** [comment]
Thanks for the followup.

No, it's too late I'll just leave it as "fowl" now

cheers,
meejah

**Comment by meejah** [comment]
That said, though, it would be nice if PyPI could be asked if a potential project-name will be accepted or not.

It appeared to me that "fow" would have been an acceptable choice, right up until I tried to actually release it as that. Having some way to discover this and avoid the work of pivoting to a new name would be nice.
