### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mharvilla** [pypi/support#2714]
### PyPI Username

`harvilm@gmail.com`

### Reason for request

I don't remember my username, can't find any way of retrieving it, and apparently can't log in without it. I've put my account email in the PyPI Username field above.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
markharvilla
