### ISSUE TITLE
PEP 541 Request: online

### ISSUE THREAD

**Issue by ntessore** [pypi/support#2715]
### Project to be claimed

`online`: https://pypi.org/project/online

### Your PyPI username

`ntessore`: https://pypi.org/user/ntessore

### Reasons for the request

The `online` name seems to be a project with no releases (project page gives 404 error, but user is not allowed to upload packages).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/ntessore/ostats

### Contact and additional research

I have tried to find a previously published `online` package without success, and have tried to find out if `online` is a protected name.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
The project "online" has been deemed invalid. It was deleted by the owner in 2020 so it is now empty.
I see you have released the new project as [online-stats](https://pypi.org/project/online-stats/) now. (In my opinion, that's a better name for the package.)
Do you still want the name `online`?

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by ntessore** [comment]
Thanks @encukou, I have come around to liking the new name as well. Sorry for not closing this issue sooner, as I had forgotten about it.
