### ISSUE TITLE
Project Limit Request: ray-cpp - 20 GB

### ISSUE THREAD

**Issue by zcin** [pypi/support#2716]
### Project URL

https://pypi.org/project/ray-cpp/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Ray is a unified framework for scaling AI applications. 
The reason for the additional size request is that we have hit the project-total size limit of 10GB on test Pypi. We'd like to increase the limit to 20 GB. 

### How large is each release?

~ 400 MB total

12 Linux wheels
3 Mac wheels
4 Windows wheels
Each roughly ~20MB

### How frequently do you make a release?

We expect to do releases every 6 weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I've bumped the limit as requested. Please be mindful of your release frequency. :)
