### ISSUE TITLE
PEP 541 Request: gauntlet

### ISSUE THREAD

**Issue by woop** [pypi/support#2718]
### Project to be claimed

`Gauntlet`: https://pypi.org/project/gauntlet

### Your PyPI username

`woop`: https://pypi.org/user/woop

### Reasons for the request

The project is not in use. I've confirmed this with the author/owner. He has just lost access to his account and can't release it. https://github.com/pypi/support/issues/2690

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no existing repository attached to this name.
The future repository will be hosted here, although this code is not representative yet: https://github.com/woop/gauntlet

### Contact and additional research

I've contacted the author on Linkedin. They are willing to release the name, but don't have access to Pypi any more. Please see  https://github.com/pypi/support/issues/2690

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abraithwaite** [comment]
Just deleted the project.  The account reset took a while and I forgot to release it after regaining access.  My bad!

@woop
