### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by iiPythonx** [pypi/support#2725]
### PyPI Username

`iiPython`

### Reason for request

Lost my entry for PyPI inside KeepassXC. I reset my password except my 2FA is still enabled so I'm locked out.  
No, I don't have my recovery codes. They were also kept inside KeepassXC.

If I can get a recovery email sent that bypasses 2FA then that would be ideal, otherwise I need to look into having the account deleted so I can snag the username for a new account.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `iiPython` has valid recovery codes generated as of 2022-11-01 18:14:56.809768.

Please use those recovery codes to regain access to your account.

**Comment by iiPythonx** [comment]
As mentioned, I don't have those recovery codes.  
Is there any way to get the account deleted via email then?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Email address associated with the account is bouncing.

Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by ewdurbin** [comment]
Confirmation complete. Email has been updated, 2FA has been reset, and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
