### ISSUE TITLE
File Limit Request: automatize - 300 MB

### ISSUE THREAD

**Issue by ttportela** [pypi/support#2729]
### Project URL

https://test.pypi.org/project/automatize/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The project is a new package for Data Mining of trajectory data. This is recently published tool for researchers and data analysts that won an award on the international conference in Mobile Data Management 2022. It is a tool to support users in a compilation of modules for running many classification methods, data preprocessing, results exploration and analysis.

I configured the project to exclude all unnecessary files.

### Reasons for the request

It is a 4-years work between three research institutions that become a big project, we expect that it will increase with cooperations in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
This was addressed in https://github.com/pypi/support/issues/2774
@ttportela for future requests, make sure you don't open the same issue twice :+1:
