### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by miroslavplese** [pypi/support#2730]
### PyPI Username

SurenderPawar

### Reason for request

Team member owning this account is no longer in the company and his email account has been deleted.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by miroslavplese** [comment]
@ewdurbin would you or anyone else from the PyPI team be able to assist?

**Comment by ewdurbin** [comment]
Confirmation complete. Email address has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
