### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mwhapples** [pypi/support#2732]
### PyPI Username

`mwhapples`

### Reason for request

Lost access to email address. I believe my account was associated to a users.berlios.de email address as the projects were hosted on berlios.de. However since the last publishing of packages berlios closed their project hosting and the email address no longer exists. I am getting back into python projects and soon will want to publish to pypi, ideally I would like to recover this user account, although I guess we could look at creating a new one.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by ewdurbin** [comment]
Confirmation complete. Email address has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
