### ISSUE TITLE
File Limit Request: ilp-r-em- 288 MB

### ISSUE THREAD

**Issue by Ivanlh20** [pypi/support#2733]
### Project URL

https://test.pypi.org/project/ilp-r-em

### Does this project already exist?

- [X] Yes

### New Limit

288

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

I have developed a suite of neural networks to perform restoration on various modalities for electron microscopy. It is not possible to reduce the size of the neural network models.

### Reasons for the request

 I have develop a suite of neural network to perform restoration on different modalities for electron mivcroscopy.
Each each size of the neural network is aroun 40MB and 8MB for its test data. I have 6 nueral nwtork which give you total size of 288MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Same as the other issue. Please create the project first. Thank you!
