### ISSUE TITLE
File Limit Request: `cupy-cuda{111,11x,12x}` - 150 MB

### ISSUE THREAD

**Issue by kmaehashi** [pypi/support#2735]
### Project URL

https://pypi.org/project/cupy-cuda12x/
https://pypi.org/project/cupy-cuda11x/
https://pypi.org/project/cupy-cuda111/

### Does this project already exist?

- [X] Yes

### New Limit

150 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[CuPy](https://docs.cupy.dev/en/latest/overview.html) is a NumPy/SciPy-compatible array library for GPU.

### Reasons for the request

We just released [v12.0.0](https://medium.com/cupy-team/released-cupy-v12-4497315e811e) today.  However, we are currently experiencing an issue with uploading the wheels, as one of them has a size of 101.03 MiB, slightly exceeding the current default limit of 100 MiB. Therefore, we humbly request an increase in the size limit to 150 MiB to allow uploading the package.

Thank you for your assistance and cooperation.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @kmaehashi :wave: thanks for the report.
I've set the upload limit for `cupy-cuda{111,11x,12x}` to 200 MB on PyPI. 
Have a nice Sunday!
