### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lehenbauer** [pypi/support#2736]
### PyPI Username

lehenbauer

### Reason for request

Have lost access to authentication device.  Recovery codes came after I set up the account.  I have a strong password and still have it.  I just need the two-factor turned off so I can login, or whatever you do to allow it.

Sorry, and thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by lehenbauer** [comment]
I cannot find the email.  I'm sorry.  Can you please resend?  Thanks.

**Comment by Thespi-Brain** [comment]
Hi @lehenbauer,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
