### ISSUE TITLE
Project Limit Request: suitesparse-graphblas - 20 GB

### ISSUE THREAD

**Issue by eriknw** [pypi/support#2737]
### Project URL

https://pypi.org/project/suitesparse-graphblas/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[`suitesparse-graphblas`](https://github.com/GraphBLAS/python-suitesparse-graphblas) provides the bindings to the C library SuiteSparse:GraphBLAS (https://github.com/DrTimothyAldenDavis/GraphBLAS). It is a high performance library for performing sparse linear algebra and is well suited for graph algorithms. `suitesparse-graphblas` is used by higher level wrappers [`python-graphblas`](https://github.com/python-graphblas/python-graphblas/) and [`pygraphblas`](https://github.com/Graphegon/pygraphblas). To show an example application, we are using GraphBLAS to implement a high-performance backend to [NetworkX](https://github.com/networkx/networkx/) called [`graphblas-algorithms`](https://github.com/python-graphblas/graphblas-algorithms) to accelerate NetworkX usage.

SuiteSparse:GraphBLAS (the C library) has been active more than 4 years, and `suitesparse-graphblas` for two years (before this, `python-graphblas` and `pygraphblas` each built wheels that included SuiteSparse:GraphBLAS).

CC @jim22k

### How large is each release?

Currently about 900MB for 18 wheels.

Each wheel is about 50MB. Our goal is to build wheels for every 64-bit platform that NumPy does. For example, today that would be these wheels:
```
cp311-cp311-win_amd64.whl
cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
cp311-cp311-macosx_11_0_arm64.whl
cp311-cp311-macosx_10_9_x86_64.whl
cp310-cp310-win_amd64.whl
cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
cp310-cp310-macosx_11_0_arm64.whl
cp310-cp310-macosx_10_9_x86_64.whl
cp39-cp39-win_amd64.whl
cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
cp39-cp39-macosx_11_0_arm64.whl
cp39-cp39-macosx_10_9_x86_64.whl
cp38-cp38-win_amd64.whl
cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
cp38-cp38-macosx_11_0_arm64.whl
cp38-cp38-macosx_10_9_x86_64.whl
pp38-pypy38_pp73-win_amd64.whl
pp38-pypy38_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pp38-pypy38_pp73-macosx_10_9_x86_64.whl
pp39-pypy39_pp73-win_amd64.whl
pp39-pypy39_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pp39-pypy39_pp73-macosx_10_9_x86_64.whl
```
This is 26 wheels. So, to support quarterly releases of three years of wheels, we need:
```
[26 wheels] * [50 MB / wheel] * [4 per year] * [3 years] = 13_800 MB
```
However, we are at the storage limit right now, so we need more wiggle room.

To save space, we may reduce the frequency of less commonly used wheels such as for pypy.

### How frequently do you make a release?

Expected frequency going forward is about 4 releases every year.

We have 33 releases in the last two years (for far fewer platforms)--we weren't considering storage usage!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @eriknw :wave: thanks for the report
It looks like a good use-case for implementing [Py_LIMITED_API](https://docs.python.org/3/c-api/stable.html) and avoid having too many wheels for your project. Maybe you can check it out.

I've set the project limit for `suitesparse-graphblas` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.

Have a nice Sunday!

**Comment by eriknw** [comment]
Thanks so much! We will definitely be mindful going forward and will look for ways to reduce our usage.
