### ISSUE TITLE
PEP 541 Request: xman

### ISSUE THREAD

**Issue by wolfhoundgelert** [pypi/support#2738]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/xman

### Your PyPI username

`USER_NAME`: https://pypi.org/user/gelert

### Reasons for the request

Hello!

I wanted to upload my project to PyPI under the name `xman`. Before it I checked that there was no project with the same name:
https://pypi.org/search/?q=xman

But when I tried to upload it, I got an error:
`Response from https://upload.pypi.org/legacy/:
         403 The user 'gelert' isn't allowed to upload to project 'xman'. See https://pypi.org/help/#project-name for more information.`

I found the reason here - https://github.com/pypi/warehouse/issues/4607 and checked https://pypi.org/project/xman/
I found the author (https://github.com/jacebrowning) and emailed him.

He generously deleted his abandoned project for me.
I managed to upload my `xman` project to test.pypi.org before, but I still can't upload my project to pypi.org getting another error:
`Response from https://upload.pypi.org/legacy/:
         400 The name 'xman' is too similar to an existing project. See https://pypi.org/help/#project-name for more information.`

How can I solve it?

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/jacebrowning - prev. athor of `xman`, jacebrowning@gmail.com

My proj (in progress) -  https://github.com/wolfhoundgelert/xman
andrey.polkanoff@gmail.com

### Contact and additional research

![image](https://user-images.githubusercontent.com/17844779/229217588-03536412-ec5f-4a1b-8a3d-8d0bc36406cb.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jacebrowning** [comment]
I confirm @wolfhoundgelert can have the namespace, if that helps. 😄

**Comment by wolfhoundgelert** [comment]
> This project name conflicts with https://pypi.org/project/x-man/. Projects should be transferred rather than deleted.

@ewdurbin Hey)

So, isn't there a way to restore the name that existed before the deletion? These 2 projects somehow lived together)

**Comment by ambv** [comment]
It's been a while. Are you still interested in the name `xman` that per newer PyPI policies conflicts with `x-man`? We could special-case this if strictly necessary, but in general we avoid such similar package names now.

**Comment by encukou** [comment]
I'll close. Feel free to reopen (or open a new issue) if you want us to look into this.
