### ISSUE TITLE
PEP 541 Request: ncpol2sdpa

### ISSUE THREAD

**Issue by peterjbrown519** [pypi/support#2742]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/ncpol2sdpa

### Your PyPI username

`USER_NAME`: https://pypi.org/user/peterjbrown519

### Reasons for the request

The owner of the package Peter Wittek, sadly went missing in a mountaineering incident several years ago and he is presumed to have died. I currently have the only maintained fork of this package on github and there have been several bug fixes since the package was last updated. Most of the emails I get from users are resolved by indicating they should install the fork rather than the latest pip version. I believe that it is also important, as this package is used in many scientific works, to avoid researchers using a buggy version (without noticing the bugs) and leading to suboptimal or worse, wrong results in their research articles. It would be important to update the pip version to stop this from happening. I have furthermore had requests from several scientists in the area who are building packages that rely on ncpol2sdpa and wish to list ncpol2sdpa as a dependency which is more awkward if you are listing a github fork rather than the official pip package.

It does not make sense, in my opinion, to release the fork under a different name. This is due to the fact that many research works cite the package directly and thus researchers reading older papers will always be directed to the buggy version. This is particularly a problem for PhD students who are unfamiliar with the surrounding literature and have no way of noticing a new package is available. 

My fork is several commits ahead of the current pip version and crucially, it contains fixes for critical bugs which include broken backwards compatibility with certain packages, and broken functionality that leads to crashes and much worse, potentially wrong results. 

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

My current fork of the project is https://github.com/peterjbrown519/ncpol2sdpa

### Contact and additional research

As mentioned above the author is sadly assumed to have died several years ago. You can find an article in memory of him at:

https://quantum-journal.org/in-memoriam-peter-wittek/

which is a well-known scientific journal in our field. I believe there are also several news articles about his disappearance. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by araujoms** [comment]
I'd like to second @peterjbrown519 's request. `ncpol2sdpa` is a widely used package in quantum information (including by me), and leaving it abandoned is damaging.

Furthermore, I knew Peter Wittek personally and can confirm that he died.

**Comment by encukou** [comment]
We could not reach Peter Wittek (the listed e-mail bounces, and searching for alternate contact info yielded only confirmation that he indeed passed away).
We consider the project abandoned per [PEP 541](https://peps.python.org/pep-0541/#abandoned-projects).
We recommend that the PyPI Administrators assign peterjbrown519 as the new
owner of "ncpol2sdpa".

**Comment by miketheman** [comment]
We have added `peterjbrown519` as an Owner to `ncpol2sdpa` project on PyPI.
We have removed `peterwittek` from the project to prevent any future abuse of the project.
