### ISSUE TITLE
PEP 541 Request: sashimi

### ISSUE THREAD

**Issue by solstag** [pypi/support#2743]
### Project to be claimed

`sashimi`: https://pypi.org/project/sashimi

### Your PyPI username

`solstag`: https://pypi.org/user/solstag

### Reasons for the request

I've been using this name for my project for a few years now (see for ex. <https://docs.cortext.net/sashimi/>). I've finally decided to polish and publish it on pypi, but found the name is being squatted.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

No source code is available for the current project, the link to github points to a 404 and the "package" has no functionality.

Source code for my project can be found here: <https://gitlab.com/solstag/sashimi>.

### Contact and additional research

I did not contact the owner since this is an invalid package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by solstag** [comment]
Ni! Hello folks. Any chance this may get some attention? It has now been another year and nothing has changed regarding the hoarding of the name. Cheers and thanks, ale .~´

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by solstag** [comment]
Ni! Understood. And thanks, I appreciate your work. .~´

**Comment by encukou** [comment]
Hello,
The project recently had a new release. Apparently the current owner wants to continue using it.
Unfortunately we can't transfer the project. You'll need to find another name.

**Comment by solstag** [comment]
Hello @encukou , @ambv 

I don't understand the decision, and I would like to request a more careful review.

The supposed "project" has been literally squatting the name for years and makes a "release" only after you folks contact the owner. As far as I can tell this is obviously and blatantly what PEP 541 exist to counter, not what it exists to validate.

Moreover, not that it should matter, but said release is pretty much a placeholder, as one can note by peeking at the supposed code in it.

Again, I would like to kindly request that my issue be reviewed with attention and respect for PEP 541.

Best regards, and at your disposal.

**Comment by encukou** [comment]
We won't be able to look at this for a month, but I'll re-open and we'll discuss afterwards.

I can add some explanation for *my* part of the evaluation.
The most relevant part of the PEP is here:

> The maintainers of the Package Index are not arbiters in disputes around *active* projects. [...] None of the following qualify for package name ownership transfer:
> [...]
> 2. User A owns a project X outside the Package Index. User B creates a package under the name X on the Index. After some time, User A wants to publish project X on the Index but realizes name is taken. This is true even if User A’s project X gains notability and the User B’s project X is not notable.

For name-squatting:

> A project published on the Package Index meeting ANY of the following is considered invalid and will be removed from the Index:
> [...]
> * project is name squatting (package has no functionality or is empty);

That applied for sashimi 0.0.0 (which only has `print('hi')`, and project structure/metadata).
The new releases have a “saliency model”. Whatever that is, and however incomplete/buggy it is, it does look like it has functionality.

**Comment by solstag** [comment]
Ni! Hi @encukou . Thanks for the reopen. I am aware of those details and have not requested a transfer based on having more notability.

As I said in my initial request over a year ago: "No source code is available for the current project, the link to github points to a 404 and the "package" has no functionality.". We both agree that this is a perfect fit to the definition of name squatting in PEP 541. And this has been the situation for 3 years, so it is not in any way a hasty judgement.

That the person pushes some couple hundred lines of broken code in response to being warned they've been caught squatting in no way changes the fact that the person was squatting when I placed my request, and remained squatting for over a year until the they learned there was a risk of losing the name.

In fact, this is exactly what you'd expect from a bad actor.

I understand that PEP 541 request must be handled carefully, and of course my view is going to be biased, but no matter how much effort I put I can't see any nuance in the present situation.

Thank you again for your attention, and best regards.

**Comment by encukou** [comment]
You're right thit this is borderline namesquatting, but our rules (PEP 541) don't allow removing this package: it has *some* functionality and the owner is active.

Please choose a different name for your project.

**Comment by solstag** [comment]
I would just like to note, for the record:
- PEP 541 says nothing about the owner being active, only about the project being active, which is not the case.
- The package had ZERO functionality at the time I placed this request and for YEARS after that. And it still has no actual functionality, even after you notified the owner, not that this should even matter.
- Therefore this is not borderline, this is very clear name squatting.
My feeling is that if there's some reason you folks don't want to apply PEP 541, you could just change the PEP or be honest about that.

**Comment by solstag** [comment]
I would just like to note, for the record:
- My request is not about the project being [abandoned](https://peps.python.org/pep-0541/#abandoned-projects), it is about it being [invalid](https://peps.python.org/pep-0541/#invalid-projects), so it's not about activity.
- The package had _zero_ functionality at the time I placed this request and for _years_ after that. And it still has no actual functionality, even after you notified the owner, not that this should even matter.
- Therefore, in my understanding, this is not borderline, this is very clear name squatting.

My feeling is that if there's some reason you folks don't want to apply PEP 541, you could just change the PEP or be open about that.

**Comment by ambv** [comment]
> My feeling is that if there's some reason you folks don't want to apply PEP 541, you could just change the PEP or be open about that.

You're responsible for your own feelings. The truth of the matter is that we have no horse in this race. We don't know you, we don't know the current maintainer of the current project. We are just trying to help. We will not be applying the PEP to any case that's not clear-cut in our eyes. There is much more possible damage from overzealous intervention compared to leaving a project on the package index that's not high value.

**Comment by solstag** [comment]
I see your point and I have always tried to communicate respectfully assuming that everyone has just been trying to help. I am naturally partial in the matter and I have little experience with PEP 541.

I did decide to spell out my feelings, after putting them in context and making it clear that's what they were. I consider it sometimes better to communicate than to hold our grudges to ourselves. I apologize if that came across as some sort of lack of respect for encukou's and your work.

Thanks for taking the time to respond
