### ISSUE TITLE
PEP 541 Request: Opus

### ISSUE THREAD

**Issue by VincentRPS** [pypi/support#2744]
### Project to be claimed

`Opus`: https://pypi.org/project/opus

### Your PyPI username

`VincentRPS`: https://pypi.org/user/VincentRPS

### Reasons for the request

This project has been abandoned and has not been updated since 2012. The project I made is a more modern recreation of this project.

NOTE: This project has been archived on [GitHub since 2020](https://github.com/svartalf/python-opus)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current Project: https://github.com/svartalf/python-opus
Replacement: https://github.com/VincentRPS/opus.py

### Contact and additional research

I have not attempted to contact the owner since they haven't been active since October.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ambv** [comment]
It's been a while. Are you still interested in the name `opus` on PyPI?

**Comment by VincentRPS** [comment]
> It's been a while. Are you still interested in the name `opus` on PyPI?

Thanks for the reminder! However, I'm no longer interested in this project name. The person who I was developing this for previously has since quit that project, so I feel putting this up would just keep it stale, which isn't obviously the goal. Thanks.
