### ISSUE TITLE
PEP 541 Request: plum

### ISSUE THREAD

**Issue by wesselb** [pypi/support#2745]
### Project to be claimed

`plum`: https://pypi.org/project/plum

### Your PyPI username

`wesselb`: https://pypi.org/user/wesselb

### Reasons for the request

Dear moderators,

On the simple listing, the name `plum` appears to be taken, but it does not show any releases: https://pypi.org/simple/plum/

For some strange reason, on the `pypi.org/project`, the name `plum` cannot be found: https://pypi.org/project/plum/

I am the primary maintainer of `plum-dispatch` ([PyPI](https://pypi.org/project/plum-dispatch/), [GitHub](https://github.com/beartype/plum)), and it would be really great to publish `plum-dispatch` under the name `plum`. The suffix `-dispatch` was added at the time because `plum` was not available.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There appears to be no source code for the current project.

Source code for the replacement project: https://github.com/beartype/plum

### Contact and additional research

I was unable to contact the current owner, because `plum` appears to not exist on PyPI: https://pypi.org/project/plum

We contacted the owner of the name `plum` on Test PyPI, but the owner of `plum` on Test PyPI is a different person. They also attempt to claim `plum` on the main PyPI index, but ran into the same issue as we did. Since then, they have settled on the name `plumpy`, and would be happy for us to claim the name `plum` on the main PyPI index.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ambv** [comment]
It's been a while. I see you adopted the name `plum-dispatch`. Are you still interested in the name `plum` on PyPI?

**Comment by wesselb** [comment]
@ambv Thanks for responding to this issue. :) Yes, I'm still interested in the name `plum` on PyPI.

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "plum" has been deemed invalid. Additionally, the owner did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to wesselb.

**Comment by ewdurbin** [comment]
Added 'wesselb' as 'Owner' on 'plum'

**Comment by wesselb** [comment]
Amazing. Thank you!
