### ISSUE TITLE
PEP 541 Request: Python Gimmicks (pygim)

### ISSUE THREAD

**Issue by Debith** [pypi/support#2747]
### Project to be claimed

`Python Gimmicks`: https://pypi.org/project/pygim

### Your PyPI username

`Debith`: https://pypi.org/user/Debith

### Reasons for the request

I am developing a library and want to release it on PyPI. It worked fine when I published part of the project under the name ‘pygim-common,’ but when I tried to release the ‘master’ project as ‘pygim,’ it failed because the names are too similar.

I was advised [here](https://discuss.python.org/t/too-similar-error-with-namespace-project/25552) to post this here as it might be conflicting with this: https://pypi.org/project/PyGLM/

Background:
I intend to use ‘pygim’ as the entry point for all other projects and ‘pygim-common’ as the main shared package with all other namespace projects. I understand that ‘pygim’ and ‘pygim-common’ have some similarities in their names, but how do I deal with this? I want it to be possible to install the main project by running ‘pip install pygim,’ which installs the common package at the same time, as well as the associated command-line interface later on.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/Debith/pygim

### Contact and additional research

-

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
Normally we'd push back against releasing this name, but given the [comment on Discuss](https://discuss.python.org/t/too-similar-error-with-namespace-project/25552/5), we assume an admin decision was already made and `Debith` was asked to file an issue provide the necessary info (PyPI username and such).

So, we recommend that PyPI admins assign the project name `pygim` to `@Debith`, or if that's not possible, make the name available.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by miketheman** [comment]
`pygim` has been released to user `Debith`
