### ISSUE TITLE
File Limit Request: pytorch-triton-rocm - 200 MB

### ISSUE THREAD

**Issue by dllehr-amd** [pypi/support#2753]
### Project URL

https://pypi.org/project/pytorch-triton-rocm

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

pytorch-triton-rocm is the ROCm implementation of [Triton ](https://github.com/ROCmSoftwarePlatform/triton)to be used for the [PyTorch](https://github.com/pytorch/pytorch) machine learning framework. Due to the nature of the ROCm platform, we currently have to build a separate build from the [triton](https://pypi.org/project/triton) pypi project.  In the future we look to eliminate this fracture, and release a single cohesive triton whl.

In the meantime, one of the key pieces we need to include in this whl is a ROCm linker `ld.lld`  Unfortunately this file alone is 80MB which limits how large our whl can be.  

We do not bundle other packages, however, we do include a few shared objects, and the aforementioned linker as they are required by triton to be able to compile and launch gpu kernels without requiring the entire ROCm codebase be installed.

I have tried to reduce the amount of files we include, but unfortunately 150MB is about as small as I can get the package at the moment.  I will strive to reduce this further, but we are on a deadline that can't wait for my exploration to continue.

### Reasons for the request

Due to the nature of the linker, we can't avoid this without building a separate pypi package to account for this single object.  

I do not expect the total size to increase beyond the 200mb requested limit.  

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dllehr-amd** [comment]
@cmaureir I apologize for pinging you on this issue, but this caught me unaware, and I have a few workloads that are held up getting a new whl over to pypi. Would you be able to review this request?  Thanks for your time!

**Comment by cmaureir** [comment]
Hey @dllehr-amd :wave: sorry I took some time off and I was catching up today with work things :)
I've set the upload limit for `pytorch-triton-rocm` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
