### ISSUE TITLE
PEP 541 Request: nes

### ISSUE THREAD

**Issue by albavilanova** [pypi/support#2754]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/nes

### Your PyPI username

`USER_NAME`: https://pypi.org/user/zrma

### Reasons for the request

We believe this package has been abandoned with time, since the last update was done back in 2014.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

We plan to replace https://pypi.org/project/nes/ by https://earth.bsc.es/gitlab/es/NES

### Contact and additional research

I tried contacting the user zrma in March with no success, see screenshot below:

![Screenshot from 2023-04-12 09-25-49](https://user-images.githubusercontent.com/56304139/231383515-eafd95f0-e27e-42f3-8504-01fec09a3727.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by albavilanova** [comment]
Hi! Is there any plan to remove this package? Thank you

**Comment by albavilanova** [comment]
Good morning, this package hasn't been updated since 2014 and we would like to get its name for our project. Is there anybody who can remove it? The owner does not respond to my emails. Thank you.

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
@albavilanova, could you provide *your* PyPI username? `zrma` is the current owner of the project.

**Comment by albavilanova** [comment]
Hi @encukou, my username is avilanova in PyPI. Thank you!

**Comment by encukou** [comment]
The project "nes" has been deemed invalid. Additionally, the owner did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to @avilanova.

**Comment by ewdurbin** [comment]
Added 'avilanova' as 'Owner' on 'nes'
