### ISSUE TITLE
PEP 541 Request: vicious

### ISSUE THREAD

**Issue by jaraco** [pypi/support#2755]
### Project to be claimed

`vicious`: https://pypi.org/project/vicious

### Your PyPI username

`jaraco`: https://pypi.org/user/jaraco

### Reasons for the request

`vicious` was registered once in 2016 and never used (squatted). I'd like to use the name for a VCS tooling library.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The original source code repository is just a stub https://github.com/vivisect/vicious. The code to go in its place is https://github.com/jaraco/hgtools.

### Contact and additional research

No attempts to contact the author have been made.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
The project "vicious" has been deemed invalid. Additionally, the owner did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to jaraco.

**Comment by ewdurbin** [comment]
Added 'jaraco' as 'Owner' on 'vicious'

**Comment by jaraco** [comment]
Thank you!
