### ISSUE TITLE
File Limit Request: tk-r-em - 200 MB

### ISSUE THREAD

**Issue by Ivanlh20** [pypi/support#2758]
### Project URL

https://pypi.org/manage/project/tk-r-em

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

I have developed a suite of six neural networks designed to perform image restoration for various electron microscopy modalities. Each network has a size of approximately 32 MB, and further reduction in size is not feasible.

### Reasons for the request

In the future, I plan to expand the project by adding more neural networks for image restoration, which may increase the overall size requirement to approximately 500 MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Ivanlh20 :wave: thanks for the report.
I've set the upload limit for `tk-r-em` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Additionally, I'd encourage you to look into other alternatives to provide the modules, like nltk does it, for example: https://www.nltk.org/data.html so then you don't need to worry about the size :)
have a nice week
