### ISSUE TITLE
File Limit Request: fbgemm-gpu - 500 MB

### ISSUE THREAD

**Issue by q10** [pypi/support#2760]
### Project URL

https://pypi.org/project/fbgemm-gpu/

### Does this project already exist?

- [X] Yes

### New Limit

500 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

FBGEMM_GPU (FBGEMM GPU kernel library) is a collection of high-performance CUDA GPU operator library for GPU training and inference.

fbgemm-gpu performs a large amount of code generation prior to compilation, which is why the built packages can be very large.

### Reasons for the request

The recent nightly builds have increased sizes, due to the increase in the size of its build dependencies. We will be investigating this and will work on reducing the binary size some time this year, but for now, we will need the PyPI size limit to be increase to accomodate the binary.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
The project is already in 300M and jumping into 500M will make the project reach the 10G project limit really fast. Is it really one binary that increases in size? have you explore having a dependency wheel to host it or to maybe download that component?

**Comment by q10** [comment]
Our library involves pre-generating a combinatorial number of kernels for the given data types (f32, f16, f8, i8, i16, i32), hardware properties (e.g. warp size, core count, etc), and algorithm properties (weighted, unweighted).  For a given operator, we can generate anywhere from 600 to 5000 unique functions, so it is not a surprise that the binary is this lrage.

That being said, we are working to have kernels be generated and compiled at runtime, but this is a big re-architecture of the library and the work for this would land at least a year or two from now, which is why we are asking for larger space at the moment.

We have separately filed https://github.com/pypi/support/issues/2761 to request for double storage capacity to 20GB, to help us with this.  We don't make releases often, but in the event that we do overfill the new 20GB limit, we will plan to prune out older versions of the library from PyPI
