### ISSUE TITLE
Project Limit Request: libroadrunner

### ISSUE THREAD

**Issue by luciansmith** [pypi/support#2763]
### Project URL

https://pypi.org/project/libroadrunner/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

I just hit the 10GB limit, and while I was able to delete some old releases this time that had been superseded within a week or two in its history, in the future, it would be great if we didn't hit the limit.  The file sizes are large because this is a binary project compiled with SWIG, so we need full binary releases for every combination of python version and OS we want to support, which is (at this point) 4 python versions (3.8->3.11) and 4 OSes (manylinux, win, macos amd64, and macos x86).

In general, this software is used by academics for simulation of their projects, and it is important for reproducibility to retain old versions of the software that were used to produce particular results.  There's a certain amount of thinning I can do, but if possible, I'd rather leave all used versions out there, so that previously-obtained scientific results can be precisely reproduced. 

### How large is each release?

$ ls -l libroadrunner-2.4.0-cp3*whl
-rwx------+ 1 Lucian None 88737553 Apr 14 14:20 libroadrunner-2.4.0-cp310-cp310-macosx_11_0_x86_64.whl
-rwx------+ 1 Lucian None 49981879 Apr 14 14:19 libroadrunner-2.4.0-cp310-cp310-manylinux2014_x86_64.whl
-rwx------+ 1 Lucian None 23835740 Apr 14 14:17 libroadrunner-2.4.0-cp310-cp310-win_amd64.whl
-rwx------+ 1 Lucian None 88737514 Apr 14 14:20 libroadrunner-2.4.0-cp311-cp311-macosx_11_0_x86_64.whl
-rwx------+ 1 Lucian None 49981854 Apr 14 14:18 libroadrunner-2.4.0-cp311-cp311-manylinux2014_x86_64.whl
-rwx------+ 1 Lucian None 23836277 Apr 14 14:17 libroadrunner-2.4.0-cp311-cp311-win_amd64.whl
-rwx------+ 1 Lucian None 88738435 Apr 14 14:19 libroadrunner-2.4.0-cp38-cp38-macosx_11_0_x86_64.whl
-rwx------+ 1 Lucian None 49982860 Apr 14 14:18 libroadrunner-2.4.0-cp38-cp38-manylinux2014_x86_64.whl
-rwx------+ 1 Lucian None 23836286 Apr 14 14:17 libroadrunner-2.4.0-cp38-cp38-win_amd64.whl
-rwx------+ 1 Lucian None 88737567 Apr 14 14:19 libroadrunner-2.4.0-cp39-cp39-macosx_11_0_x86_64.whl
-rwx------+ 1 Lucian None 49981427 Apr 14 14:18 libroadrunner-2.4.0-cp39-cp39-manylinux2014_x86_64.whl
-rwx------+ 1 Lucian None 23836567 Apr 14 15:37 libroadrunner-2.4.0-cp39-cp39-win_amd64.whl

### How frequently do you make a release?

It's varied, but a few times a year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @luciansmith :wave:
Have you tried the Limites API? https://docs.python.org/3/c-api/stable.html in that case you save the trouble of having 1-wheel-per-python-version, and you can provide 1 wheel that supports many python versions (per platform).
50G is a lot compared to other projects, I understand the motivation, but maybe 20G might do as well? what do you think?

**Comment by di** [comment]
Closing due to lack of response.

**Comment by luciansmith** [comment]
@di Should I re-submit, or re-open this issue?  Sorry for the delay.

**Comment by di** [comment]
I've increased the total project size for `libroadrunner` to 20GB, happy to revisit if/when that limit is reached again.

**Comment by luciansmith** [comment]
Thank you so much!
