### ISSUE TITLE
PEP 541 Request: ten

### ISSUE THREAD

**Issue by cfreal** [pypi/support#2765]
### Project to be claimed

`ten`: https://pypi.org/project/ten

### Your PyPI username

`cfreal`: https://pypi.org/user/cfreal

### Reasons for the request

The name seems unavailable, although the page returns 404.

As I try to create it: `403 The user 'cfreal' isn't allowed to upload to project 'ten'. See https://pypi.org/help/#project-name for more information`.

I successfully created a project on test.pypi.org (https://test.pypi.org/project/ten/), so I'm curious as to why it does not work here.

Regards,

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/cfreal/ten

### Contact and additional research

I am not aware of a current owner, just that the name seems reserved.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "ten" has been deemed invalid. Additionally, the owner did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to cfreal.

**Comment by ewdurbin** [comment]
Added 'cfreal' as 'Owner' on 'ten'
