### ISSUE TITLE
PEP 541 Request: coreai

### ISSUE THREAD

**Issue by coreaidev** [pypi/support#2767]
### Project to be claimed

`coreai`: https://pypi.org/project/coreai

### Your PyPI username

`coreai`: https://pypi.org/user/coreai

### Reasons for the request

There appears to be no evidence that this project ('coreai') exists.  Therefore, unable to reach the owner of a non-existant project.

Trying to publish a set of core ai training & inference utilities.

### Maintenance or replacement?

None

### Source code repositories URLs

There is no existing project being replaced.

The project I wish to publish is: https://github.com/coreaidev/coreai-python
Our website/API server is: https://www.coreai.dev (public face currently just redirects to github, backend APIs serve client library).

### Contact and additional research

I was able to publish to testpypi without issue.  Issue only arose when attempting to publish to production pypi.

```
$ python3 -m twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: coreai
Enter your password: 
Uploading coreai-0.0.1-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 kB • 00:00 • 15.6 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                              
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/                                                       
         The user 'coreai' isn't allowed to upload to project 'coreai'. See https://pypi.org/help/#project-name for more     
         information.
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by coreaidev** [comment]
cc @yeraydiazdiaz

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "coreai" has been deemed invalid. Additionally, the owners did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to coreai

**Comment by ewdurbin** [comment]
Added 'coreai' as 'Owner' on 'coreai'
