### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JoneSabino** [pypi/support#2769]
### PyPI Username

primerobot

### Reason for request

lost access to the email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by JoneSabino** [comment]
This account is related to a company where I'm the new manager. I saw that packages published in this account have vulnerabilities but we lost the email address to access the account and remove these packages.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Thespi-Brain** [comment]
Hi @JoneSabino,

I am following up regarding your request. Are you still having an issue regarding your email address and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
