### ISSUE TITLE
File Limit Request: deepview-predict - 250 MB

### ISSUE THREAD

**Issue by michaelshin** [pypi/support#2770]
### Project URL
https://pypi.org/project/deepview-predict/
https://test.pypi.org/project/deepview-predict/

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This project is part of a PyTorch profiler used by developers to optimize their GPU utilization and choose the best cloud provider instances. The predictor is used to predict the training runtime of a given PyTorch model and a given GPU. We have been developing over the past year and we are finally trying to release it on PyPI but running into file size limits.

The predictor and profiler are already separate code bases so there is not much more splitting that can be done for that.

### Reasons for the request

Each model used for the prediction takes up ~30MB and there are 4 of them making the total size of the wheel ~120MB. These are already compressed PyTorch models so there is not much more compression that can be done. I envision adding more models in the future to increase accuracy and to support new GPUs so 250MB was requested

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by michaelshin** [comment]
@cmaureir sorry to directly tag you, but could you take a look at this issue when you have the time? This issue is gating some of our releases. Thanks in advance!

**Comment by cmaureir** [comment]
Hey @michaelshin :wave: thanks for the report. No worries about the tagging.
I've set the upload limit for `deepview-predict` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
have a nice week
