### ISSUE TITLE
PEP 541 Request: yo

### ISSUE THREAD

**Issue by brenns10** [pypi/support#2772]
### Project to be claimed

`yo`: https://pypi.org/project/yo

### Your PyPI username

`brenns10`: https://pypi.org/user/brenns10

### Reasons for the request

The current project yo appears to be invalid according to [PEP 541](https://peps.python.org/pep-0541/#invalid-projects):

> project is name squatting (package has no functionality or is empty);

Currently it has one release (0.0.0) with no artifacts/contents, no URL to home page, etc. It is last updated in 2012.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: no source code repository found
Intended replacement: https://github.com/oracle-samples/yo

The intended replacement is just released open source, but will continue to be developed and maintained publicly. It's a command-line client for the OCI cloud service, and it's had the name "yo" (and entry-point name "yo") for the 2.5 years it's been used internally.

That said, if the request can't be granted, we can use an alternative PyPI name if necessary.

### Contact and additional research

I couldn't determine author information of the `yo` project directly: the author field of the project is not provided, and there's no source code repository for me to look through the metadata of.

The PyPI account [walterwefft](https://pypi.org/user/walterwefft/) owns several other projects on PyPI, some with author fields git source repositories.

I reached out via email yesterday to 5 addresses (I don't want to post them in public out of respect for privacy but would gladly provide them via private message. Two addresses were at Gmail and bounced. Two were at a parked domain with no MX records. One was at a domain which seems to redirect to another, but has a valid MX record. So far I've not received a response, but I'm happy to wait a bit still.

There were two Github accounts which seemed related to the PyPI account. @averagehuman and @podados. This template doesn't seem to create the @-mention, but if they would like to weigh in on the request, I would welcome that too!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by averagehuman** [comment]
Sorry, I'm a bad person! I'll try to retrieve  pypi login in the next day
or two and release this and any other packages. I did put in a request to
consolidate multiple accounts once upon a time and it was accepted but
never acted on in the end. In any case I don't claim the named package and
it can be assigned to requestor.

**Comment by brenns10** [comment]
Hi @averagehuman thanks so much for the reply and I absolutely did not mean to imply you were a bad person at all. We all have accounts and projects we created and maybe didn't follow up on 😄 My github is littered with them!

I appreciate your help on this when you do get the time!

**Comment by averagehuman** [comment]
No worries Stephen, all good. I added you as owner, is that ok? Then you
remove me as collaborator? Or if you prefer me to delete it, let me know.

All the best

Gerard

**Comment by brenns10** [comment]
That worked wonderfully, I accepted the invite and removed you as a collaborator. I really appreciate your quick response here. I'll close this issue on out!
Thank you!
Stephen
