### ISSUE TITLE
Undelete file request

### ISSUE THREAD

**Issue by Marco-Sulla** [pypi/support#2779]
Project: frozendict
File removed: frozendict-2.3.6.tar.gz

I removed by mistake the sdist package from
https://pypi.org/manage/project/frozendict/release/2.3.6/

Can you please restore it?

Sorry for the nuisance -.-

**Comment by di** [comment]
Sorry, we don't support 'undeleting' on PyPI. You should update your version number or make a [post release](https://peps.python.org/pep-0440/#post-releases).
