### ISSUE TITLE
Project Limit Request: OG-JPN - 210MB Roughly

### ISSUE THREAD

**Issue by Tatsuru-Kikuchi** [pypi/support#2780]
### Project URL

https://test.pypi.org/project/ogjpn/

### Does this project already exist?

- [X] Yes

### New limit

210 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

Overlapping-generations macroeconomic model for evaluating fiscal policy in Japan. 

### How large is each release?

210 MB in total.

### How frequently do you make a release?

Roughly once every 6 month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Tatsuru-Kikuchi :wave: thanks for the report.
I've set the upload limit for `ogjpn` to 300 MB on TestPyPI. Please be mindful of the frequency of releases at that size.
have a nice week!
