### ISSUE TITLE
File Limit Request: OG-JPN - 210 MB Roughly

### ISSUE THREAD

**Issue by Tatsuru-Kikuchi** [pypi/support#2781]
### Project URL

https://pypi.org/project/ogjpn/

### Does this project already exist?

- [X] Yes

### New Limit

210 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Overlapping-generations macroeconomic model for evaluating fiscal policy in Japan.

### Reasons for the request

210 MB in total.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Tatsuru-Kikuchi :wave: thanks for the report.
I've set the upload limit for `ogjpn` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice week!
