### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by moongoal** [pypi/support#2782]
### PyPI Username

`qafir`

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by moongoal** [comment]
Hi @ewdurbin the reason for this ticket is I lost access to the email address, so I'm certainly not going to be able to read your email or reply from there.

**Comment by ewdurbin** [comment]
The address did not bounce.

**Comment by moongoal** [comment]
To be honest I don't even know if openmailbox (the provider) is still alive as their site is not reachable. Yet the email account is very old and I lost the password for it, that's why I was redirected here by the pypi admin. Any chance for a different form of authentication?

**Comment by ewdurbin** [comment]
Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by ewdurbin** [comment]
Finally got a bounce, just to confirm.

**Comment by moongoal** [comment]
Thanks for the update. Yesterday I sent the email to the provided address as instructed and am waiting for their reply.

**Comment by ewdurbin** [comment]
Contacted via requested email address, please read the instructions and reply to proceed with recovery.

**Comment by moongoal** [comment]
Followed instructions and replied.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by moongoal** [comment]
Hi, I've been checking my inbox (and spam) for the past week but I have not yet received the password reset. Attempting a password recovery both with user name or email address results in a failure:

* Using the email address yields an error, "No user found with that username or email"
* Using the user name successfully sends the email but none is received

**Comment by ewdurbin** [comment]
I'm sorry. I blew it. Was in 2FA mode and did the wrong action. Email has been updated and new password reset issued.

**Comment by moongoal** [comment]
Received and reset. Thanks!
