### ISSUE TITLE
PEP 541 Request: isabl_cli

### ISSUE THREAD

**Issue by nickp60** [pypi/support#2784]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/isabl_cli

### Your PyPI username

`USER_NAME`: https://pypi.org/user/NickWaters

### Reasons for the request

I am a contributor to https://github.com/papaemmelab/isabl_cli.  A previous maintainer must have registered the package on pypi but no longer has access. 

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/papaemmelab/isabl_cli

### Contact and additional research

I contacted members of the team and no one knows who the owner would be, as the expected person does not have access either.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nickp60** [comment]
Hi, is there any info I am missing?

**Comment by encukou** [comment]
We are working to contact the owner (using contact info they have on PyPI).

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by nickp60** [comment]
Thanks for following up -- you can reach out to @juanesarango  for more info!

**Comment by encukou** [comment]
The current owner is juanesarango, who was able to recover their account, and asked to not transfer ownership.
