### ISSUE TITLE
PEP 541 Request: fit-tool

### ISSUE THREAD

**Issue by th1js** [pypi/support#2787]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/fit-tool/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/th1js

### Reasons for the request

I think the project is abandoned, I've reached out to the maintainer in all the ways I could come up with but without luck.

There are some typos in one example I wanted to tell the maintainer about.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current repo: https://bitbucket.org/stagescycling/python_fit_tool
I'll host on github

### Contact and additional research

reach out through e-mail and linked-in

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
Hello,
One of the ways to reach out would be sending a pull request to the project's current repository. Have you done that?

**Comment by encukou** [comment]
Hello,
Pull requests are an important way to reach out to project owners (and specifically to fix typos examples). Since it appears you haven't tried this yet, I'll close the issue.
Feel free to open a new one if you still cannot reach the owner.
