### ISSUE TITLE
File Limit Request: WildMeOrg / wildbook-ia - 200 MB

### ISSUE THREAD

**Issue by tsubramanian** [pypi/support#2789]
### Project URL

https://pypi.org/project/wildbook-ia/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

WBIA program for the storage and management of images and derived data for use in computer vision algorithms. It aims to compute who an animal is, what species an animal is, and where an animal is with the ultimate goal being to ask important why biological questions.

This project is the Machine Learning (ML) / computer vision component of the WildBook project: See https://github.com/WildMeOrg/. This project is an actively maintained fork of the popular IBEIS (Image Based Ecological Information System) software suite for wildlife conservation. The original IBEIS project is maintained by Jon Crall (@Erotemic) at https://github.com/Erotemic/ibeis. The IBEIS toolkit originally was a wrapper around HotSpotter, which original binaries can be downloaded from: http://cs.rpi.edu/hotspotter/

Currently the system is build around and SQLite database, a web GUI, and matplotlib visualizations. Algorithms employed are: convolutional neural network detection and localization and classification, hessian-affine keypoint detection, SIFT keypoint description, LNBNN identification using approximate nearest neighbors.

### Reasons for the request

We are working on making the size limit under control for future releases in Aug 2023, but the very next release would not be more than 200 MB

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @tsubramanian :wave: thanks for the information. 
I've set the upload limit for `wildbook-ia` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
I couldn't find the project on testpypi, so feel free to open a new issue if you need to use that domain.
Have a nice day :tada:

**Comment by tsubramanian** [comment]
@cmaureir Much Appreciated. Thank you!
