### ISSUE TITLE
PEP 541 Request: PyJWT

### ISSUE THREAD

**Issue by jpadilla** [pypi/support#2790]
### Project to be claimed

`PyJWT`: https://test.pypi.org/project/PyJWT/

### Your PyPI username

`jpadilla`: https://pypi.org/user/jpadilla

### Reasons for the request

I was surprised when https://test.pypi.org/project/PyJWT/ was owned by someone else while I own https://pypi.org/project/PyJWT/. I'm trying to setup trusted publisher on the TestPyPI instance but can't at the moment.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/jpadilla/pyjwt

### Contact and additional research

Reached out to @puneethrai but haven't heard back yet.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Handling this one out of band because this is for a TestPyPI project and doesn't require maintainer reachability.

@jpadilla, you are now the owner of `PyJWT` on TestPyPI.

**Comment by jpadilla** [comment]
@di thanks! ❤️
