### ISSUE TITLE
PEP 541 Request: bones

### ISSUE THREAD

**Issue by sizemore0125** [pypi/support#2793]
### Project to be claimed

`bones`: https://pypi.org/project/bones

### Your PyPI username

`sizemol`: https://pypi.org/user/sizemol

### Reasons for the request

The project was made in 2016 and there is nothing on the page.

### Maintenance or replacement?

replace

### Source code repositories URLs

I could not find a repo:
https://pypi.org/project/bones/

My proposed repo:
https://github.com/sizemore0125/bones

### Contact and additional research

I emailed Giles, but his email is invalid, so there is no way to get a hold of him.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by ewdurbin** [comment]
Added 'sizemol' as 'Owner' on 'bones'
