### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Tjstretchalot** [pypi/support#2794]
### PyPI Username

tjstretchalot

### Reason for request

I lost access to the 2FA authentication app or security token to this account several years back. I still have access to the email. I don't particularly care if I recover the exact pypi account, but I do need my new account (tjstretchalot2) able to push to at least pympanim as I [made an update](https://github.com/Tjstretchalot/pympanim/commit/55edc4bb25e7e7d4fbbcaba38bbde5b29575d65d)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
