### ISSUE TITLE
File Limit Request: aspose-ocr-python-net- 300 MB

### ISSUE THREAD

**Issue by Annushka34** [pypi/support#2797]
### Project URL

https://pypi.org/project/aspose-ocr-python-net/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

It's the first official release of the Aspose.OCR library (Aspose Pty)
https://products.aspose.com/ocr/python-net/
https://releases.aspose.com/ocr/python-net/

### Reasons for the request

Our library uses neural networks, and they have a big weight. They optimized as much as it was possible. These models are the main advantage of our libraries.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Annushka34 :wave: thanks for the details.
I've set the upload limit for `aspose-ocr-python-net` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size :tada:
