### ISSUE TITLE
Request to remove past releases: ivy

### ISSUE THREAD

**Issue by djl11** [pypi/support#2798]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/ivy

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ivyteam

### Reasons for the request

TL;DR: Darren Mulholland ([PyPi](https://pypi.org/user/dmulholland/), [GitHub](https://github.com/dmulholl)) has very kindly enabled us to take control of the [ivy package](https://pypi.org/project/ivy/) in PyPI, so that we can use it for our own [project](https://github.com/unifyai/ivy). However, we won't be able to re-use the same [version numbers](https://pypi.org/project/ivy/#history) after deleting all of the old releases. Now that we have gained ownership, can the version history be wiped **entirely** so that we can reuse the version numbers, without needing to add `.post1` to the end of several releases?

Broader context: rewinding a bit, I originally took some very bad legal advice from a trademark attorney in 2020, before creating [this official request](https://github.com/pypi/support/issues/722), where I've now removed my comments, but you can find then in the edit history. While our legal counsel still insists that this trademark infringement is viable grounds for name removal based on your [Intellectual property policy](https://peps.python.org/pep-0541/#intellectual-property-policy), I quickly felt very ashamed of this _hostile_ takeover attempt, and rightfully abandoned the approach entirely shortly after.

However, as mentioned above, Darren has now very kindly offered for us to claim the name `ivy` on PyPI, with his old static site generator now re-named to ark. This is something we're incredibly grateful for.

We're now exploring how to set up the new package for our project. Based on our experimentation, and it seems as though we can [kind of re-use the versions](https://stackoverflow.com/questions/21064581/how-to-overwrite-pypi-package-when-doing-upload-from-command-line/63944201#63944201), but with `post` then added to the end of all releases which existed previously. This doesn't seem to be the cleanest solution.

I would therefore like to kindly ask if you would consider some (hopefully light) admin intervention in order to remove this cached ivy [version history](https://pypi.org/project/ivy/#history) _entirely_ in this particular case, either before or after I have deleted the versions on my end?

Please let me know your thoughts on this request. I'm sure you get a ton of these requests which must be a nightmare to deal with, I'm sorry to add to the pile even further!

Thanks a lot for your time and consideration, very much appreciated.
Dan

### Maintenance or replacement?

Replacement

### Source code repositories URLs

previous: [ark](https://github.com/dmulholl/ark)
replacement: [ivy](https://github.com/unifyai/ivy)

### Contact and additional research

Darren and I have already reached an amicable arrangement, and I have obtained access to the project on PyPI already. This request is a bit different.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
Hello, and sorry for the delay.
This is not a PEP-541 request; it's a request to delete file entries so they can be uploaded with new content.
I am not qualified to make a decision here, but I don't think PyPI admins will be able to do this for you, for both technical and policy reasons.

**Comment by ambv** [comment]
> Now that we have gained ownership, can the version history be wiped entirely so that we can reuse the version numbers, without needing to add .post1 to the end of several releases?

This is impossible by design. Please use higher version numbers, like 7.x when you start publishing packages. For the same reason mypy used release versions like https://pypi.org/project/mypy/0.991/ before getting to 1.0. The previous project used 0.256 for the highest published version.
