### ISSUE TITLE
PEP 541 Request: bits

### ISSUE THREAD

**Issue by jtraub91** [pypi/support#2800]
### Project to be claimed

`bits`: https://pypi.org/project/bits

### Your PyPI username

`jtraub91`: https://pypi.org/user/jtraub91

### Reasons for the request

The project appears to be inactive or "name squatting" as there is no actual releases nor links to source code, only a "0.0.0 release" from April 14, 2015 with project description "UNKNOWN".

### Maintenance or replacement?

Replacement

### Source code repositories URLs

As indicated above, there are no links to source code for the current project at https://pypi.org/project/bits and I have found no links to source code otherwise.

The project I intend to replace it with is located here: https://github.com/jtraub91/bits

### Contact and additional research

I have contacted the current owner over a week ago, via email, asking if he would consider relinquishing ownership so that I may use it instead, but I have not received a response as of yet. I sent a follow-up email a week later, and likewise did not receive a response.

I've also sent a request to connect via LinkedIn so that I can send him a message there, but have been unable to connect there as well. The author _does_ appear to be a maintainer for other active project(s) and _does_ appear to have a GitHub account, so perhaps we can tag him here to contact him.

I do understand that a timespan of only about a week and a half from my first email without a response is not a terribly long time before kicking off this process, but given that the current project appears to be inactive and perhaps has never existed, I feel as though it makes sense to document my efforts here in order to expedite this process as much as possible. Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jtraub91** [comment]
Hey @jck, sorry to tag you here, but I've been trying to get in touch with you to see if you could transfer ownership of the [bits project on pypi](https://pypi.org/project/bits) to me so that I may use it for my project linked above. Considering the current project appears inactive, I hope this is not too much of an issue, and I would really appreciate it since I am hoping to start promoting it more publicly and I think a presence on pypi would greatly help that effort. Thanks for your time and consideration! Cheers 🍺

**Comment by jtraub91** [comment]
Can this request be expedited please, since the current project is invalid per [PEP 541](https://peps.python.org/pep-0541/#invalid-projects)? 🙏

**Comment by jtraub91** [comment]
@encukou sorry to bother, but tagging you hoping to get this request handled when possible 🙏

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project is now deleted. @jtraub91, you should be able to claim it. (Hopefully a conflicting name wasn't registered recently.)

**Comment by jtraub91** [comment]
Hi Petr,

Thank you so much!

Cheers,
Jason Traub

**Comment by encukou** [comment]
The project is now owned by jtraub91! Closing.
