### ISSUE TITLE
PEP 541 Request: wilma

### ISSUE THREAD

**Issue by P403n1x87** [pypi/support#2801]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/wilma

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Datadog

### Reasons for the request

~~~
Error uploading to repository: https://upload.pypi.org/legacy/ - Client error '400 The name 'wilma' isn't allowed. See https://pypi.org/help/#project-name for more information.' for url 'https://upload.pypi.org/legacy/'
For more information check: https://httpstatuses.com/400
~~~
but there doesn't seem to be any `wilma` projects on PyPI at the moment.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/DataDog/wilma

### Contact and additional research

No package with the same name, so no idea who else to get in contact with.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Hi @P403n1x87, I see that the public source code repository noted in your request has been archived.

Do you still have a use-case for this project name?

**Comment by P403n1x87** [comment]
Hi @ewdurbin. Thanks for getting in touch. This is currently not a priority. I see that the `prohibited project name` label was added so I guess that explains why I was not able to use that project name. Should I need to upload the project to PyPI I might choose a different project name.
