### ISSUE TITLE
PEP 541 Request: minivan

### ISSUE THREAD

**Issue by aismlv** [pypi/support#2802]
### Project to be claimed

minivan: https://pypi.org/project/minivan

### Your PyPI username

aismlv: https://pypi.org/user/aismlv

### Reasons for the request

* The project does not seem to exist and
* The name does not seem to be in the standard library
* It's not too similar to any existing project, based on a few searches
* It does not seem to be malicious

So possibly it has been claimed by someone but no releases were created?

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/aismlv/minivan

### Contact and additional research

I've previously published the package as `minivn` which might be too similar to "minivan". I tried to delete the previous release with that name now, but no success

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "minivan" has been deemed invalid. Additionally, the owner did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to aismlv.
