### ISSUE TITLE
File Limit Request: solar_system_ephemerides - 200 MB

### ISSUE THREAD

**Issue by mattpitkin** [pypi/support#2804]
### Project URL

https://pypi.org/project/solar-system-ephemerides/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is a package that contains solar system ephemeris files, a Python wrapper to access the files and a script to generate them from other sources. The ephemeris files are gzipped ascii files contain the position, velocity and acceleration of the Earth and Sun between the years 2000 and 2050 and various time increments. These file are primarily used in the search for continuous gravitational waves from pulsars by the LIGO Scientific Collaboration and Virgo Collaboration, where they are required to calculate the Doppler modulation of any signal. There are files for a variety of [JPL development ephemeris](https://en.wikipedia.org/wiki/Jet_Propulsion_Laboratory_Development_Ephemeris) versions, with different versions used by pulsar astronomy groups to define the positional information about individual pulsars. The use of bzip2 or xz could reduced the files sizes by ~20-30%, but would means that they would not be compatible with legacy software used by the collaborations, hence the need to gzipped versions at the moment. (In the future HDF5 versions may be produced and extra functionality added to read them added into collaboration software packages).

### Reasons for the request

The current version of the package has not been able to include all ephemeris versions that cover all those used within the pulsar community for defining pulsars positions. We would expect initially to add in one more version, which would increase the total package file size to 106 Mb. In the future we may need to add more (at a slow rate), but expect that this would not exceed 200 Mb over the period of the next decade. Updates that include new ephemeris files would likely be rare, on the order of once per 2-3 years at most.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @mattpitkin :wave: thanks for the report.
I've set the upload limit for `solar_system_ephemerides` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice week :)

**Comment by mattpitkin** [comment]
Thanks very much 😃
