### ISSUE TITLE
PEP 541 Request: ahsoka

### ISSUE THREAD

**Issue by Witchblade101** [pypi/support#2805]
### Project to be claimed

`ahsoka`: https://pypi.org/project/ahsoka

### Your PyPI username

`Witchblade101`: https://pypi.org/user/witchblade101

### Reasons for the request

No evidence of a project with this name on PyPI

Error trying to upload when running `twine upload --repository-url https://upload.pypi.org/legacy/ dist/*`

`WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         The user 'WItchblade101' isn't allowed to upload to project 'ahsoka'. See
         https://pypi.org/help/#project-name for more information.`

--verbose doesn't add much more clarity

`Uploading distributions to https://upload.pypi.org/legacy/
INFO     dist/ahsoka-0.0.1-py3-none-any.whl (30.8 KB)
INFO     dist/ahsoka-0.0.1.tar.gz (24.9 KB)
INFO     Querying keyring for username
Enter your username: __token__
INFO     Querying keyring for password
Enter your password:
INFO     username: __token__
INFO     password: <hidden>
Uploading ahsoka-0.0.1-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.9/34.9 kB • 00:00 • 47.3 MB/s
INFO     Response from https://upload.pypi.org/legacy/:
         403 The user 'WItchblade101' isn't allowed to upload to project 'ahsoka'. See
         https://pypi.org/help/#project-name for more information.
INFO     <html>
          <head>
           <title>403 The user 'WItchblade101' isn't allowed to upload to project 'ahsoka'. See
         https://pypi.org/help/#project-name for more information.</title>
          </head>
          <body>
           <h1>403 The user 'WItchblade101' isn't allowed to upload to project 'ahsoka'. See
         https://pypi.org/help/#project-name for more information.</h1>
           Access was denied to this resource.<br/><br/>
         The user &#x27;WItchblade101&#x27; isn&#x27;t allowed to upload to project &#x27;ahsoka&#x27;. See
         https://pypi.org/help/#project-name for more information.

          </body>
         </html>
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         The user 'WItchblade101' isn't allowed to upload to project 'ahsoka'. See
         https://pypi.org/help/#project-name for more information.`

No evidence project with this names exists (or has ever existed?)
Since the project doesn't exist, I cannot contact the owner.

`pip install ahsoka
ERROR: Could not find a version that satisfies the requirement ahsoka (from versions: none)
ERROR: No matching distribution found for ahsoka`

Various Google searches for combinations of "ahsoka, pip, pypi, python, module, package" eventually found a single hit:

https://www.roseindia.net/answers/viewqa/pythonquestions/35455-ModuleNotFoundError-No-module-named-ahsoka.html

and that looks like it's just generated by a bot.

The project is a data reduction pipeline for JWST reliant on the ATOCA algorithm (part of the inspiration for the name), being developed by astronomers at STScI, NASA, and several universities.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

No evidence of existing repository.

New repository: https://github.com/Witchblade101/ahsoka

### Contact and additional research

Only evidence found of a previous owner is the very suspicious website https://www.roseindia.net/answers/viewqa/pythonquestions/35455-ModuleNotFoundError-No-module-named-ahsoka.html

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "ahsoka" has been deemed invalid. Additionally, the owner did not
respond in a week.
We recommend that the PyPI Administrators transfer the project to Witchblade101.

**Comment by ewdurbin** [comment]
Added 'WItchblade101' as 'Owner' on 'ahsoka'
