### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by neubi4** [pypi/support#2808]
### PyPI Username

`t-systems-mms`

### Reason for request

Lost 2FA authentication app or security token

Hi,

unfortunately due to a sync issue of KeePass to our company file share we lost our 2FA Tokens and recovery codes for pypi.

We still have access to our mail and have the correct password. We also have an valid API Token which we are using to deploy our package to pypi.

Please help us to reset our 2FA.

Thanks in advance

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `t-systems-mms` has valid recovery codes generated as of 2022-08-17 11:54:25.503210.

Please use those recovery codes to regain access to your account.

**Comment by neubi4** [comment]
Hi @ewdurbin,

our recovery codes were in the same KeePass Entry which got lost. Do we have any other way to recover access to our account?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
