### ISSUE TITLE
File Limit Request: pypylon - 150 MB

### ISSUE THREAD

**Issue by basler-oss** [pypi/support#2809]
### Project URL

https://pypi.org/project/pypylon/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Hi all,

pypylon is a python wrapper for the camera SDK for Basler Cameras. 
It includes the pylon runtime binaries.

### Reasons for the request

pypylon includes runtime binaries to support Basler's CoaXpress(CXP) framegrabbers.
Unfortunately these binaries (*.dlls containing bytetcode for the framegrabbers) are roughly 400MB uncompressed and lead to a wheel size of ~106MB. 
I will discuss our strategy internally, but for now it would be great if you could raise the size limit.
Only windows wheels are affected

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @basler-oss :wave: thanks for the report.
I've set the upload limit for `pypylon` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week
