### ISSUE TITLE
PEP 541 Request: conda-package-handling

### ISSUE THREAD

**Issue by dholth** [pypi/support#2812]
### Project to be claimed

`conda-package-handling`: https://pypi.org/project/conda-package-handling

### Your PyPI username

`joeforker`: https://pypi.org/user/joeforker

### Reasons for the request

This project name doesn't appear to have been used on pypi.org but it produces an error on upload. It might be similar to my `conda-package-streaming` or it is just a well-known `conda` dependency. We intend to publish the real `conda-package-handling` on pypi in addition to its place in the conda ecosystem.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/conda/conda-package-handling

### Contact and additional research

I work for Anaconda, Inc.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jezdez** [comment]
@di Hey Dustin, we're not sure what's causing this issue, could you take a look at how `conda-package-handling` is being prevented from being uploaded? To the conda's team knowledge, it was never uploaded to PyPI before.

@dholth said it might be related to the name closeness to another project called `conda-package-streaming` that we also maintain? We're stumped how to unblock this and would really like to release on PyPI and on anaconda.org. Could we explicitly add this to the allow-list?

**Comment by dholth** [comment]
```
% twine upload dist/conda_package_handling-2.1.0-py3-none-any.whl --verbose
INFO     Using configuration from /Users/dholth/.pypirc
Uploading distributions to https://upload.pypi.org/legacy/
INFO     dist/conda_package_handling-2.1.0-py3-none-any.whl (20.1 KB)
INFO     username set from config file
INFO     password set from config file
INFO     username: __token__
INFO     password: <hidden>
Uploading conda_package_handling-2.1.0-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 kB • 00:00 • 77.5 MB/s
INFO     Response from https://upload.pypi.org/legacy/:
         400 The name 'conda-package-handling' isn't allowed. See
         https://pypi.org/help/#project-name for more information.
INFO     <html>
          <head>
           <title>400 The name 'conda-package-handling' isn't allowed. See
         https://pypi.org/help/#project-name for more information.</title>
          </head>
          <body>
           <h1>400 The name 'conda-package-handling' isn't allowed. See
         https://pypi.org/help/#project-name for more information.</h1>
           The server could not comply with the request since it is either
         malformed or otherwise incorrect.<br/><br/>
         The name &#x27;conda-package-handling&#x27; isn&#x27;t allowed. See
         https://pypi.org/help/#project-name for more information.


          </body>
         </html>
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'conda-package-handling' isn't allowed. See
         https://pypi.org/help/#project-name for more information.
```

**Comment by di** [comment]
This was reserved as part of #355, CC @encukou.

**Comment by jezdez** [comment]
Ah, interesting, thanks for CCing @encukou!

**Comment by encukou** [comment]
Yup, `@dholth` is a maintainer. Please let Anaconda people take the project!

Apologies for the delay.

**Comment by di** [comment]
Released to https://pypi.org/user/joeforker!
