### ISSUE TITLE
PEP 541 Request: tenpy

### ISSUE THREAD

**Issue by Jakob-Unfried** [pypi/support#2814]
### Project to be claimed

`tenpy`: https://pypi.org/project/tenpy

### Your PyPI username

`Jakob-Unfried`: https://pypi.org/user/Jakob-Unfried

### Reasons for the request

The project is abandoned;
- The owner is not reachable under the listed email `naoina@naniyueni.org`. In fact emails can not be delivered to that address, they time out.
- The last release is more than 12 years old
- The listed homepage `https://bitbucket.org/naoina/tenpy` no longer exists.

The project has not been updated in 12 (!) years and consists of under 1000 lines of code.
I therefore believe its notability and use to the python community is nil.

Our package, however, would benefit greatly from being on PyPI under the same name that is used everywhere else to refer to the package.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

 The current project lists a bitbucket page `https://bitbucket.org/naoina/tenpy`, but it no longer exists.

 I intend to publish this package: `https://github.com/tenpy/tenpy` in its place.

### Contact and additional research

The only contact information i could find online where the email and homepage listed on PyPI, both of which seem to not exist anymore.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by naoina** [comment]
@Jakob-Unfried I have invited you to tenpy project as an Owner. Please check your email. Thank you.

**Comment by Jakob-Unfried** [comment]
thank you! 🚀
