### ISSUE TITLE
PEP 541 Request: appsignal

### ISSUE THREAD

**Issue by unflxw** [pypi/support#2817]
### Project to be claimed

`appsignal`: https://pypi.org/project/appsignal

### Your PyPI username

`as_unflxw`: https://pypi.org/user/as_unflxw

### Reasons for the request

The project does not seem to currently exist. I am an AppSignal employee and we're trying to publish an AppSignal for Python integration, but we get an error saying `400 The name 'appsignal' isn't allowed.`

We've published the project successfully to TestPyPI.

### Maintenance or replacement?

None

### Source code repositories URLs

Current project: https://github.com/appsignal/appsignal-python
There doesn't seem to be a previous project.

### Contact and additional research

You can contact support@appsignal.com to verify that I am an AppSignal employee.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by unflxw** [comment]
I won't be available next week, but you can reach out to @tombruijn for any questions regarding this issue.

**Comment by tombruijn** [comment]
@di I was wondering if we're running into the typosquat prevention system when creating this package, similar to https://github.com/pypi/support/issues/2650.

When I [search for "appsignal"](https://pypi.org/search/?q=appsignal), I get this result:

> There were no results for 'appsignal' Did you mean '[aiosignal](https://pypi.org/search/?q=aiosignal)'?

Any help or guidance on how we should proceed is appreciated :)

**Comment by unflxw** [comment]
Hi @di, would you kindly take a look at this issue, or mention someone who could? We have been publishing for a while as `appsignal-beta`, but we'd really like to publish as `appsignal` instead for our `1.0` release.

**Comment by di** [comment]
The project name was prohibited due to being used in a dependency confusion attack.

Since this doesn't require maintainer reachability, I've gone ahead and handled this out of queue, https://pypi.org/user/as_unflxw can now publish https://pypi.org/project/appsignal.
