### ISSUE TITLE
PEP 541 Request: visionlab

### ISSUE THREAD

**Issue by anishathalye** [pypi/support#2818]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/visionlab

### Your PyPI username

`USER_NAME`: https://pypi.org/user/anishathalye

### Reasons for the request

- This is an [invalid project](https://peps.python.org/pep-0541/#invalid-projects) by the PEP 541 definition: the project is name squatting.
- The [user appears to be](https://pypi.org/user/netw0rkf10w/) name squatting 8 packages; all packages uploaded by this project are invalid per the PEP 541 definition.
- I have attempted to contact the author but have not received a response.

I am a maintainer of [cleanlab](https://github.com/cleanlab/cleanlab), a popular ML-related Python package. We have a number of other projects that we like to refer to as `____lab`, but we were forced to publish what we wanted to call "visionlab" using a [different name](https://github.com/cleanlab/cleanvision), because this package was name-squatted.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/cleanlab/cleanvision

### Contact and additional research

I emailed the package author on 4 May 2023 and have not received a response yet.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by anishathalye** [comment]
It has been long enough that we're committed to the name [cleanvision](https://github.com/cleanlab/cleanvision) now, so I withdraw my request to take over "visionlab".
