### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by EkramulHoque** [pypi/support#2820]
### PyPI Username

EkramHoque

### Reason for request

Hello,

I have made a mistake using the email address '[ekram.hoque@statcan.ca](mailto:ekram.hoque@statcan.ca)' for creating
the account. It should be '[ekram.hoque@statcan.gc.ca](mailto:ekram.hoque@statcan.gc.ca)'. Now I am unable to create/register.

Also I have added a secondary email which is '[ekramulhq26@gmail.com](mailto:ekramulhq26@gmail.com)'. Both email accounts are locked.

Can you please help?

Thanks

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
I cannot find a user account with the username `EkramHoque`.
