### ISSUE TITLE
Account recovery request - Two-factor authentication to my account

### ISSUE THREAD

**Issue by olabeno** [pypi/support#2829]
### PyPI Username

'Olabeno'

### Reason for request

Lost 2FA authentication app or security token.
I have lost access to my 2FA authentication method to generate authentication code to access my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
duplicate.
