### ISSUE TITLE
PEP 541 Request: Flask-Session (on Test PyPI)

### ISSUE THREAD

**Issue by davidism** [pypi/support#2830]
### Project to be claimed

`Flask-Session`: https://test.pypi.org/project/Flask-Session

### Your PyPI username

`davidism`: https://test.pypi.org/user/davidism

### Reasons for the request

I'm the owner on Main PyPI: https://pypi.org/project/Flask-Session, the project on Test PyPI appears to be a random user from 2016.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/pallets-eco/flask-session

### Contact and additional research

This is Test PyPI, and I already own the name on Main.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
Generally, test.PyPI projects should be transferred to the owner on the main PyPI instance with no red tape. In this case, the owner on main PyPI is now an organization, which AFAIK doesn't exist on test PyPI. I think transferring to the previous owner is the right thing to do.

I recommend that the **test.pypi** project `Flask-Session` be transferred to davidism.


Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by davidism** [comment]
I do have requests for those orgs on TestPyPI (to match PyPI) but understandably those have been on hold.

**Comment by ewdurbin** [comment]
Added 'davidism' as 'Owner' on 'Flask-Session' on test.pypi.org.
