### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by aliddell** [pypi/support#2833]
### PyPI Username

aliddell

### Reason for request

Lost 2FA authentication app or security token.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by aliddell** [comment]
I appear to no longer have access to this email account.

**Comment by aliddell** [comment]
@ewdurbin Thanks. What do you need from me?

**Comment by ewdurbin** [comment]
Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by ewdurbin** [comment]
Contacted via requested email address, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. Email has been updated, 2FA reset, and a password reset issued, you should be able to regain access to your account after completing the password reset.
