### ISSUE TITLE
PEP 541 Request: psutils

### ISSUE THREAD

**Issue by rrthomas** [pypi/support#2838]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/psutils

### Your PyPI username

`USER_NAME`: https://pypi.org/user/rrt

### Reasons for the request

I believe this name is currently blocked because it's a Fedora package name.

I am the upstream maintainer of PSUtils (PostScript utilities). The package was previously written in Perl, but I have rewritten it in Python, and would like to release a major new version with PDF support.

### Maintenance or replacement?

None

### Source code repositories URLs

PSUtils repository: https://github.com/rrthomas/psutils/

You can see the project history here going all the way back to when it was written in C!

### Contact and additional research

Since there is no current owner, I have not attempted to contact them. I am guessing that the name is reserved because it is a Fedora package name, as was the case with rpl, which I previously took over (#649) and still maintain on PyPI.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rrthomas** [comment]
@encukou, @di, you both seemed to be involved last time I asked to claim a Fedora package that had been auto-namesquatted (#649); can you help this time, please? I believe this case is identical: there's no current package for the name on PyPI, and I'm the upstream of the Fedora, Debian etc. package of the same name.

**Comment by encukou** [comment]
It's not reserved for the Fedora package. (For that it would have to be an existing *Python* package in Fedora.)
It's probably blocked for name similarity  with the widely popular [psutil](https://pypi.org/project/psutil/) package -- in general, common typos are a tasty target for malicious users.

Anyway, if it helps: I can confirm `@rrthomas` is upstream of the Fedora package, which dates back to 2004.
If it was up to me, I'd support unblocking the name.

**Comment by rrthomas** [comment]
Thanks, @encukou, I misunderstood the policy as blocking all PyPI names that matched a Fedora package. Thanks also for the confirmation. Last night I made my first Python release of psutils: https://github.com/rrthomas/psutils/releases/tag/v3.0 (I was going to choose a temporary name on PyPI and release there too, but of course there was a temporary moratorium on new package registration.)

**Comment by rrthomas** [comment]
Ping! I have been making regular releases under "pdfpsutils", but it would still be good to have the original name, as the different package name is causing confusion.

**Comment by kfogel** [comment]
+1 to what @rrthomas is requesting.  There is no danger of typo-attack here, since @rrthomas is well-known to be the legitimate upstream maintainer.  It would be easier for everyone if he could make PyPI releases under the expected and familiar name `psutils`.

**Comment by rrthomas** [comment]
Ping? This issue is still causing confusion to my users.

**Comment by rrthomas** [comment]
@Thespi-Brain could you please clarify whether the "prohibited project name" label means that there's no chance of my getting this name (e.g. because of confusion with the `psutil` package), or whether it still relates to the fact that it's a well-known project name in its own right?

**Comment by ewdurbin** [comment]
Hi @rrthomas, This project name was prohibited on PyPI in 2018 in response to malware/typosquatting attack targeting `psutil`.

Given the similarity to `psutil` on PyPI, I am going to put this in the queue for admin review.

**Comment by miketheman** [comment]
'psutils' released to 'rrt'.

**Comment by rrthomas** [comment]
Christmas has come early! Many thanks!

**Comment by kfogel** [comment]
Seconded here -- this will make life easier for many users of @rrthomas's package.  Thank you, @ewdurbin and @miketheman!
