### ISSUE TITLE
File Limit Request: up_ibacop - 120 MB

### ISSUE THREAD

**Issue by GiorgioBonardi** [pypi/support#2841]
### Project URL

https://pypi.org/project/up-ibacop/

### Does this project already exist?

- [X] Yes

### New Limit

120 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

As mentioned in the Acknowledgements section of the following [github repository](https://github.com/aiplan4eu/up-ibacop):

This library is being developed for the AIPlan4EU H2020 project (https://aiplan4eu-project.eu/) that is funded by the European Commission under grant agreement number 101016442.

It integrates the IBaCoP2 configurator, which is developed by Isabel Cenamor and Tomas de la Rosa and Fernando Fernandez. More information can be found at The IBaCoP Planning System: Instance-Based Configured Portfolios. PhD thesis, Universidad Carlos III de Madrid, 2016.

We tried our best to reduce the number of files needed but unfortunately the size of the project still exceeds the limit. 

### Reasons for the request

We have exceeded the size limit because we must include some executable files that cannot be compiled externally. Those files are included in the IBaCoP2 Configurator.

We don't expect that the size limit will increase in the future.

Best regards.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @GiorgioBonardi :wave:
I've set the upload limit for `up_ibacop` to 120 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :tada:
