### ISSUE TITLE
PEP 541 Request: const

### ISSUE THREAD

**Issue by ntessore** [pypi/support#2842]
### Project to be claimed

`const`: https://pypi.org/project/const

### Your PyPI username

`ntessore`: https://pypi.org/user/ntessore

### Reasons for the request

Project has been created 2016 with version 0.0.0 and no data.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: not given
Replacement: https://github.com/ntessore/const

### Contact and additional research

Contacted original package author via email on 13 May 2023. Based on their other PyPI package and profile picture, I believe the author may be @sijad on GitHub. I am opening this issue in the hope of getting in touch.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sijad** [comment]
I'm not interested to give that up due personal, privacy and security reasons.
thanks for your understanding 🙏

**Comment by ntessore** [comment]
No worries, thanks for getting in touch!
