### ISSUE TITLE
PEP 541 Request: opentelemetry-opencensus-shim

### ISSUE THREAD

**Issue by srikanthccv** [pypi/support#2844]
### Project to be claimed

`opentelemetry-opencensus-shim`: https://pypi.org/project/opentelemetry-opencensus-shim

### Your PyPI username

`opentelemetry`: https://pypi.org/user/opentelemetry

### Reasons for the request

Hello,

We have planned to publish a package named `opentelemetry-opencensus-shim`. We didn't reserve the name while we were still developing this. Meanwhile, someone else grabbed the name and appear to have published it with suspicious code. Our development effort towards the `opentelemetry-opencensus-shim` is completed, but we can't release it since we don't own the name. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The code repository for the current project is unknown. The pypi link takes you to https://github.com/kotko/bravado-decorators, but it seems to be private.

The code repository for the one we intend to publish is here https://github.com/open-telemetry/opentelemetry-python/tree/main/shim/opentelemetry-opencensus-shim

### Contact and additional research

The current owner of the said package reached out to the Technical Committee of the OpenTelemetry on Apr 16/18th, quoting they were inspired by https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610 and claimed the `opentelemetry-opencensus-shim` name as a part of the exercise since it was part of example [requirements.txt](https://github.com/open-telemetry/opentelemetry-python/blob/e9530c5c548d08a6aaa56268d103f9beb00cd002/docs/examples/opencensus-shim/requirements.txt#L4) but not taken on PyPI yet.

We, maintainers of OpenTelemetry (through TC of OTEL), have made several attempts to reach them and transfer ownership of the package to publish the legitimate code. We have not received any response. We request you to transefer the ownership.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by srikanthccv** [comment]
It has been quite some time. We would like to publish the legitimate package under the `opentelemetry` user (and eventually org). Can maintainers help us? @di @dstufft, maybe one of you can do this?

**Comment by ocelotl** [comment]
Hello, we need some help here, please @di @dstufft :slightly_smiling_face:
