### ISSUE TITLE
File Limit Request: tensorflow-federated - 120 MB

### ISSUE THREAD

**Issue by michaelreneer** [pypi/support#2845]
### Project URL

https://pypi.org/manage/project/tensorflow-federated

### Does this project already exist?

- [X] Yes

### New Limit

120

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

TensorFlow Federated (TFF) is an open-source framework for machine learning and
other computations on decentralized data. TFF has been developed to facilitate
open research and experimentation with Federated Learning (FL), an approach to
machine learning where a shared global model is trained across many
participating clients that keep their training data locally. For example, FL has
been used to train prediction models for mobile keyboards without uploading
sensitive typing data to servers.

Active for approximately 5 years.

### Reasons for the request

We ship a binary as part of the package. Currently the binary is 39 MB. We intend to make a change that will increase that size to 65 MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the report,
I've set the upload limit for `tensorflow-federated` to 120 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :tada:

**Comment by michaelreneer** [comment]
Thanks!
