### ISSUE TITLE
Project Limit Request: tensorflow-federated - 50 GB

### ISSUE THREAD

**Issue by michaelreneer** [pypi/support#2846]
### Project URL

https://github.com/tensorflow/federated

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

TensorFlow Federated (TFF) is an open-source framework for machine learning and
other computations on decentralized data. TFF has been developed to facilitate
open research and experimentation with Federated Learning (FL), an approach to
machine learning where a shared global model is trained across many
participating clients that keep their training data locally. For example, FL has
been used to train prediction models for mobile keyboards without uploading
sensitive typing data to servers.

Active for approximately 5 years.

### How large is each release?

We ship a binary as part of the package. Currently the binary is 39 MB. We intend to make a change that will increase that size to 65 MB.

### How frequently do you make a release?

Once a week.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks @michaelreneer, I can see that you haven't even reach 1G in your project, and the limit id 10G, but you are asking an increase to 50G.
I think it might be too early for such increase, is there any motivation of the request? It's usually understandable when a project is reaching the limit, but I think you have enough time for many releases at the moment.

**Comment by cmaureir** [comment]
Forgot to close this, but I'm glad you solved it :) have a nice rest of the week!
