### ISSUE TITLE
PEP 541 Request: prosper

### ISSUE THREAD

**Issue by shariq** [pypi/support#2848]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/prosper

### Your PyPI username

`USERNAME`: https://pypi.org/user/prosper

### Reasons for the request

Hi,

It [seems like this project was name squatted](https://github.com/pypi/support/issues/791), and is not available to register. Would it be possible to make it available?

We're a robotics company publishing an SDK for researchers to use to develop on our robots remotely. It would be quite nice if they could just `import prosper` to connect to a robot in the cloud, from a Jupyter notebook, with an API key! Making it very easy to get into robotics research :)

You can see a video of our system here, which got 500k views: https://twitter.com/shariq/status/1655631896766717952

### Maintenance or replacement?

Replacement

### Source code repositories URLs

We don't know which repository is pointed to by the current project.

Our current SDK is not yet published anywhere, as it's still under development. It will include features to connect to a robot, stream images and sensor data, send robot commands, and access telemetry.

### Contact and additional research

We wanted to contact the current name squatter ( https://github.com/pypi/support/issues/791 ) but we were unsuccessful at finding their contact details : https://pypi.org/user/Collie/

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
The name was indeed name-squatted, and removed+prohibited in 2022 in #724.

I recommend that the project `prosper` is released, and preferably transferred to the user `prosper`.


Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by ewdurbin** [comment]
'prosper' released to 'prosper'.
