### ISSUE TITLE
File Limit Request: savic_test - 800 MB

### ISSUE THREAD

**Issue by MihailoMartinovic** [pypi/support#2849]
### Project URL

https://test.pypi.org/project/savic-test/

### Does this project already exist?

- [X] Yes

### New Limit

800

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This is a project that is intended to be a Python package version of Stability Analysis Vitalizing Instability Classification (SAVIC) code that is available on GitHub at 

https://github.com/MihailoMartinovic/SAVIC

This code is a part of the series of papers, the first of which is published in The Astrophysical Journal 

https://iopscience.iop.org/article/10.3847/1538-4357/ac3081

while the second one is currently under review. It provides an automated access to a series of trained algorithms aiming to describe the stability of plasma waves in the interplanetary solar wind. Traditionally, this task is performed by complicated and computationally expansive plasma dispersion solvers, that are only available to specialized groups, while SAVIC makes this tool accessible to wide community. 

### Reasons for the request

The trained algorithms within the SAVIC software are large in size, but are necessary for having the code work as intended. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @MihailoMartinovic I checked the content of the repository and it seems there is no structure there to create a Python package (whl). Could it be that maybe the content is not uploaded yet? additionally, all the metadata in your test.pypi.org project seems to be a base project, and not the information of your project.

In case packaging is a new topic for you, there are a few tutorials here: https://packaging.python.org/en/latest/

Let me know if you have any question.

**Comment by MihailoMartinovic** [comment]
Dear Cristian,


I am not sure I understand your point; this is indeed the first time I create a package, but I did manage to successfully create it (along with whl that is created on my computer and uploaded as well) and install it from Anaconda Prompt using

python -m pip install --index-url https://test.pypi.org/simple/ --no-deps savic_test


I made a total of 27 versions, the last one being 0.3.3, and all of them starting 0.1.1 worked well, I was just adding new features. While adding those new features, I hit the 100 MB limit, and this is how I got to raise the issue.

So, my plan of action was to ask you to lift the limit for savic-test on test.pypi, and for savic on pypi, as there will be the permanent place for the 1.0 version. Then, we'll be updating savic in the future, and I intend to use savic-test as the testing ground.

Can you please help me with this, and/or point out if I made the some noobie-like error?

Thank you in advance!


Best,

Mihailo

**Comment by MihailoMartinovic** [comment]
Dear Cristian,


I am not sure I understand your point; this is indeed the first time I create a package, but I did manage to successfully create it (along with whl that is created on my computer and uploaded as well) and install it from Anaconda Prompt using

python -m pip install --index-url https://test.pypi.org/simple/ --no-deps savic_test


I made a total of 27 versions, the last one being 0.3.3, and all of them starting 0.1.1 worked well, I was just adding new features. While adding those new features, I hit the 100 MB limit, and this is how I got to raise the issue.

So, my plan of action was to ask you to lift the limit for savic-test on test.pypi, and for savic on pypi, as there will be the permanent place for the 1.0 version. Then, we'll be updating savic in the future, and I intend to use savic-test as the testing ground.

Can you please help me with this, and/or point out if I made the some noobie-like error?

Thank you in advance!


Best,

Mihailo

**Comment by cmaureir** [comment]
Hey @MihailoMartinovic 
The current state of your repository doesn't have any file that will generate the `.whl` that you mention.
There are no `.pyproject` files, nor `setup.py/cfg` files, so it still showing that doesn't have the proper structure to have such thing.

Running `pip install` doesn't create  wheels, refer to the tutorial that I mentioned, which explain the process step by step.

Once you manage to create the packages, the repo still shows only jupyter notebooks https://github.com/MihailoMartinovic/SAVIC which is not  really the point for a Python Package. The packages are for "pip install your_package" so later I can "import your_package" and use some functionality from it.

I have the feeling you are using a Python Package only to distribute a set of Jupyter Notebooks, which can be achieve by anyone else only by cloning your repository, without the need of a wheel.

Let me know if I can clarify something any further!

**Comment by MihailoMartinovic** [comment]
Hi,

I think there is a confusion here due to same names for package and NB repository. The repository on GitHib is not intended to be a Python Package, but rather just a set of notebooks. However, I am not asking for the memory extension for this repository, but rather for 

https://test.pypi.org/project/savic-test/

which does have the appropriate structure and is used for testing, and also for 

https://pypi.org/project/savic/

where I intend to launch the package once I get it in shape (even though it is not appropriately structured at this time). 

Does this clarify the confusion? 

Best,
Mihailo

**Comment by cmaureir** [comment]
Hello,

I see, then there is no project "yet". If that's the case, I'd recommend you to explore other ways of including large files like `nltk` does (for example) https://www.nltk.org/install.html#installing-nltk-data.

Having a  jump from 100 to 800 without a proper justification, and without knowing all the things you have explore to reduce the size of the wheel  doesn't sounds like a proper justification to me.

If you need any further guidance, or other options, let me know!

Cheers
