### ISSUE TITLE
File Limit Request: robotframework-AppiumSikuliLibrary - 300 MB

### ISSUE THREAD

**Issue by thinhdnn** [pypi/support#2850]
### Project URL

https://pypi.org/project/robotframework-AppiumSikuliLibrary

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

robotframework-AppiumSikuliLibrary: Combine appium v8 and sikuli to automate mobile testing.

### Reasons for the request

My jar file has size 176 MB. I need more to upload the file.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by thinhdnn** [comment]
After got approve for test PyPI. https://github.com/pypi/support/issues/2762#issuecomment-1539642660

**Comment by cmaureir** [comment]
Hey @thinhdnn the README and links of your project reference a base project, and not your application, so I cannot check any details on your project. Can you provide more information please?

**Comment by thinhdnn** [comment]
> 

I reuploaded my project. Please check again @cmaureir

**Comment by thinhdnn** [comment]
Hey @cmaureir , I added again.

**Comment by cmaureir** [comment]
> Hey @cmaureir , I added again.

thanks for that @thinhdnn 
I have one last question, checking the project's main page, it seems your project is a fork from https://github.com/rainmanwy/robotframework-SikuliLibrary  I really want to avoid that user in the future wanted to distribute his project and you having the name on PyPi.
Did you discuss with @rainmanwy about packaging the project from your fork?

**Comment by thinhdnn** [comment]
> > Hey @cmaureir , I added again.
> 
> thanks for that @thinhdnn I have one last question, checking the project's main page, it seems your project is a fork from https://github.com/rainmanwy/robotframework-SikuliLibrary I really want to avoid that user in the future wanted to distribute his project and you having the name on PyPi. Did you discuss with @rainmanwy about packaging the project from your fork?

I did not contact him, the fork distribution for the different solutions. His project did for a desktop app. My project combines his project, Sikuli snapshot, and Appium for mobile apps.

**Comment by cmaureir** [comment]
Hey @thinhdnn :wave: thanks for the information.
I've set the upload limit for `robotframework-AppiumSikuliLibrary` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:
