### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cybergoof** [pypi/support#2856]
### PyPI Username

`cybergoof`

### Reason for request

I have not logged in for a while, but would like to be more active.  It appears that my current 2fa is not the right one.  

If it helps with validation, my github user is cybergoof and I work at GitHub.

I do have access to my email, but I did not see an option to recover through email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by cybergoof** [comment]
Thanks

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
