### ISSUE TITLE
Project Limit Request: hail - 20 GB

### ISSUE THREAD

**Issue by danking** [pypi/support#2857]
### Project URL

https://pypi.org/project/hail/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[Hail](https://hail.is/) is an open-source, general-purpose, Python-based data analysis tool with additional data types and methods for working with genomic data.

The [first commit](https://github.com/hail-is/hail/commit/5e5daaacfe82d4b58130999978a7ce6e65719747) was on July 24 2015. It's [first PyPI release](https://pypi.org/project/hail/0.2/) was on May 19, 2018.

Hail [is widely used](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=%22GitHub.com%2Fhail-is%2Fhail%22&btnG=&oq=hail-i) in the genetics & genomics communities. I've removed all our "dev" versions, but we're still at 9GiB out of 10GiB. Our releases are ~130MiB (they include a rather large JAR file). This gives us ~7 releases before we run out of space.

I would really prefer not to delete old versions because this impedes replication in science. Another 10GiB gives us another ~78 releases. We release ~every two weeks. That gives us ~3 years before we need to consider deleting packages from 2018.

### How large is each release?

~130 MiB wheels due to a somewhat large JAR file. We are actively working to extricate ourselves from the JVM and move to native code (allowing us to depend on system libraries rather than bundling with our JAR), but this is a long-term project.

We do not bundle example data. We do not bundle other Python packages.

### How frequently do you make a release?

~every two weeks

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the report @danking :wave:
I've set the project limit for `hail` to 20 GB on PyPI. Please be mindful of the frequency of your releases.
Have a nice week :tada:
