### ISSUE TITLE
PEP 541 Request: adcraft

### ISSUE THREAD

**Issue by bitcloud2** [pypi/support#2860]
### Project to be claimed

`adcraft`: https://pypi.org/project/adcraft

### Your PyPI username

`bitcloud2`: https://pypi.org/user/bitcloud2

### Reasons for the request

I don't see any project by this name on PyPI, TestPyPI, or GitHub.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project I am attempting to publish: https://github.com/Mikata-Project/adcraft

### Contact and additional research

The project name `adcraft` was accepted on TestPyPI, but rejected on PyPI. I'm not finding a project of that name on PyPi. I wasn't able to find any projects by that name either on GitHub. I don't see any names that are similar or that this name would cause a conflict with. I don't know if there is something on my end that I messed up, but given it worked on TestPyPI, I was assuming it would also work on PyPI.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
'adcraft' released to 'bitcloud2'.
