### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by SoheilSalmani** [pypi/support#2864]
### PyPI Username

SoheilSalmani

### Reason for request

Hello, I lost my 2FA authentication app. I would like to use this PyPi account to publish my packages. Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Thespi-Brain** [comment]
Hi @SoheilSalmani,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by SoheilSalmani** [comment]
Hello @Thespi-Brain. Yes! I followed the instructions regarding my recovery codes, but I haven't received any response. Could you help me? I can forward the emails I've received, if needed.

**Comment by Thespi-Brain** [comment]
Hi @SoheilSalmani,

Thanks for replying back. Since the original instructions were sent almost a year ago, I have started a new account recovery process. These account recovery instructions should be similar to the ones your received before. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @SoheilSalmani,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
