### ISSUE TITLE
PEP 541 Request: pythonweb

### ISSUE THREAD

**Issue by highghlow** [pypi/support#2866]
### Project to be claimed

`pythonweb`: https://pypi.org/project/pythonweb

### Your PyPI username

`highghlow`: https://pypi.org/user/highghlow

### Reasons for the request

I used my library (pythonweb) in many of my projects and copied the file over and over again, but this approach is really bad and I decided to publish to pypi, but the name was already taken.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/highghlow/pythonweb

### Contact and additional research

I tried contacting the current project owner (james@pythonweb.org), but the mailer daemon returns an error when trying to send the email (Invalid mailbox). The whole owner account is abandoned (Last release was in 2016)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The project "pythonweb" has been deemed invalid. Additionally, the owner did not
respond in a week.

@highghlow, before we make a recommendation to the admins, let me ask: are you still interested in the name? I see that you registered [highghlow-pythonweb](https://pypi.org/project/highghlow-pythonweb/) but it's not been active for a year.

**Comment by highghlow** [comment]
> are you still interested in the name?

Yea, it's been so long that, no. I'm not
