### ISSUE TITLE
File Limit Request: gwemopt - 200 MB

### ISSUE THREAD

**Issue by mcoughlin** [pypi/support#2867]
### Project URL

https://pypi.org/project/gwemopt/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Both example data and configuration files for individual telescope systems are bundled in the install. The start of a recent observing run has meant the addition of a handful of new telescopes entering the project (https://www.ligo.caltech.edu/news/ligo20220123).

### Reasons for the request

gwemopt crossed over 100 MB in this latest release. I would not expect to go past 200 MB in a future release.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the report @mcoughlin :wave:
I've set the upload limit for `gwemopt` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week
