### ISSUE TITLE
Project Limit Request: httpstan - 30 GB

### ISSUE THREAD

**Issue by riddell-stan** [pypi/support#2869]
### Project URL

https://pypi.org/project/httpstan

### Does this project already exist?

- [X] Yes

### New limit

-50- 30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

httpstan is a companion package (backend) for pystan, a popular scientific computing package. Our releases are about 320 MB and we release about 5 times a year.

In the future, we do hope to add aarch64 releases -- hence the 50 GB request, to be safe.

Thank you for maintaining this service.

### How large is each release?

~320 MB

4 Linux versions (36 MB each), 4 macOS versions (44 MB each)

The package is large because it includes C++ source files (needed for runtime compilation) and one ~ 14MB compiled (OCaml) binary. We can't do anything about the binary but we have made efforts to reduce the amount of source files we distribute.

### How frequently do you make a release?

Roughly five times a year. Two major releases and some bugfix releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @riddell-stan with 50G you will enter the top 25 https://pypi.org/stats/ is there any reason for such large jump from 10 G to 50 G ? Have you explore ways to reduce the amount of wheels like the [Limited API](https://docs.python.org/3/c-api/stable.html) in order to have 1 wheel per OS?

**Comment by riddell-stan** [comment]
Thanks for the quick response.

re: 50G -- I was thinking about riscv and aarch64 wheels in the coming years. But if that is jumping the gun, 30G would be fine. Mainly, I'd like to be able to issue a bugfix release right now.

I do appreciate the need to keep storage costs low. I will look into the limited api. We use pybind11 and if pybind11 makes it easy to use the limited api, I think we could probably use it without too much fuss.

(If you want to give httpstan whatever is left of pystan's excess quota to keep the total allocated constant, that would be fine -- pystan will never make another release; httpstan replaces it.)

**Comment by riddell-stan** [comment]
For what it's worth, Stan, including httpstan, is sponsored by NumFOCUS. https://numfocus.org/project/stan

**Comment by cmaureir** [comment]
Hey @riddell-stan :wave:
I have set the project limit to 30G on PyPI for `httpstan`, but please try to search for other ways to reduce the size of the wheels/project because it will be a bit complicated to increase the total size again.
You could provide mechanism to download certain files after the setup like nltk does https://www.nltk.org/install.html#installing-nltk-data or maybe splitting the wheel in a couple or so.

But anyway, good luck with the new releases. have a nice weekend :)
