### ISSUE TITLE
PEP 541 Request: lmflow

### ISSUE THREAD

**Issue by SHUMKASHUN** [pypi/support#2873]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/lmflow/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ksshumab

### Reasons for the request

We are the owner of Github Project LMFlow (https://github.com/OptimalScale/LMFlow), however, the LMFlow project name is taken by someone else at (https://pypi.org/project/lmflow/), which has almost same project description to our project.
We believe this is not a simple name conflict, but a malicious registration for our intellectual property, as the following reason:
- there is no other project named `LMFlow` on GitHub.
- the project description on pypi is `LMFlow - An Extensible Toolkit for Finetuning and Inference of Large Foundation Models` which is almost same as our project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/OptimalScale/LMFlow

### Contact and additional research

There is no contact information on the homepage of the current owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by shizhediao** [comment]
Hi, is there any info I am missing? @ewdurbin 
Actually we (with @SHUMKASHUN ) are the owner of https://github.com/OptimalScale/LMFlow

Furthermore, we found that this person is a professional malicious squatter who has recently squatted on many well-known LLM code repositories. We should resist such behavior. We would really appreciate it if you can help.
Thanks!

**Comment by encukou** [comment]
The project "lmflow" has been deemed invalid.
We recommend that the PyPI Administrators transfer the project to ksshumab.

Additionally, the current owner, shadowwalker2718, is mass name squatting; we reccommend they be dealt with appropriately.

**Comment by shizhediao** [comment]
Hi @encukou,
Yes exactly. Thank you for your support!
May I ask if there is anything we should complete from our side? Or the PyPI Administrators will help us transfer the project to ksshumab?

Thanks!

**Comment by ewdurbin** [comment]
Added 'ksshumab' as 'Owner' on 'lmflow'

**Comment by shizhediao** [comment]
Thank you so much!
