### ISSUE TITLE
Project Limit Request: pypylon - 20 GB

### ISSUE THREAD

**Issue by stefanklug** [pypi/support#2874]
### Project URL

https://pypi.org/project/pypylon/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

pypylon is a python wrapper for the camera SDK for Basler Cameras.
It includes the pylon runtime binaries.

### How large is each release?

~900MB per release

6 Windows releases at ~106MB
6 Mac OS releases at ~17MB
18 linux releases at ~9MB

There is already some info on the relase size in this request to raise the release size limit: https://github.com/pypi/support/issues/2809
One question: We thought about deleting the rc releases from pypi to free space. On the other hand deleting existing releases from pypi seems bad practice and only a last resort for licensing issues etc. Any recommendations from your side?

### How frequently do you make a release?

No fixed schedule. Roughly 2-3 releases per year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @stefanklug :wave:
Maybe you can check the documentation about the Limited API https://docs.python.org/3/c-api/stable.html so you can reduce your wheels to one-per-platform, making it compatible to all the python versions you support.

IMHO deleting releases is a bad practice, but deleting RC releases shouldn't be a big deal. But that's my personal take.

I have set the project limit for `pypylon` to 20G on PyPI. Hopefully you have some time to check the Limited API, personally it really simplify things a lot once it's implemented :)

Have a nice weekend!

**Comment by stefanklug** [comment]
Hey @cmaureir,

thanks for the update. I'll ave a look at the Limited API. 
Unfortunately I still get an error in twine upload:
Response from https://upload.pypi.org/legacy/:                        
         400 Project size too large. Limit for project 'pypylon' total size is 
         10 GB. See https://pypi.org/help/#project-size-limit

Am I missing something?

**Comment by cmaureir** [comment]
Hey @stefanklug sorry about that, I think I forgot to click a button :) you can try now :)

**Comment by stefanklug** [comment]
@cmaureir Thank you very much. It works now...
