### ISSUE TITLE
Project Limit Request: essentia-tensorflow - 20 GB

### ISSUE THREAD

**Issue by dbogdanov** [pypi/support#2875]
### Project URL

https://pypi.org/project/essentia-tensorflow/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Essentia is an open-source C++ library with Python bindings for audio and music analysis. 

`essentia-tensorflow` includes algorithms for fast ML inference with TensorFlow, resulting in large binaries. The project is hosted on PyPI since 2020. Increasing the size limit to 20 GB will allow us to keep updating the wheels during the next several years (updates are infrequent).

### How large is each release?

291MB each Manylinux wheel (x86_64, CPython versions 3.6-3.11)
115.7MB each wheel for MacOS (x86_64, CPython versions 3.6-3.11)

### How frequently do you make a release?

Infrequently, similarly to previous history (11 releases in 3 years):
https://pypi.org/project/essentia-tensorflow/2.1b6.dev871/#history

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @dbogdanov :wave: thanks for the report. 
I think if you look at https://docs.python.org/3/c-api/stable.html you might find that enabling the limited API you will end up having one wheel per OS, reducing the current configuration.
Complementary, you could find a way to split the wheels a bit and maybe having a dependency that doesn't change much, in case you can put some binaries. 
But anyway, for the time being, I have set the new project limit of `essentia-tensorflow` to 20G.

Have a nice weekend!

**Comment by dbogdanov** [comment]
Thank you for suggestions, @cmaureir!
