### ISSUE TITLE
File Limit Request: naif-de440 - 120 MB

### ISSUE THREAD

**Issue by moeyensj** [pypi/support#2884]
### Project URL

https://pypi.org/project/naif-de440/

### Does this project already exist?

- [X] Yes

### New Limit

120 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`naif-de440` is designed to ship a binary data file known as "[Development Ephemeris (DE) version 440](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/)" that records the predicted positions of the planets in the Solar System. These development ephemeris files are created by the [Navigation and Ancillary Information Facility (NAIF)](https://naif.jpl.nasa.gov/naif/about.html) (a subdivision of NASA's Jet Propulsion Laboratory) and are used extensively by researchers in astronomy and astrodynamics to calculate the positions of the planets as a function of time for things such as asteroid discovery efforts, space mission planning, ephemeris calculation, etc.. The `naif-de440` package is designed to ship this file and provides a single variable that stores the path to the file on disk so it can be used with external packages such as `spiceypy`. However, the ephemeris file is 113 MB which exceeds the default PyPi file size limit. No other packages are bundled in this project. No example data is packaged. The only data contained in this package is the development ephemeris file and a script to fetch it for CI publishing actions. 

### Reasons for the request

The binary data file is 113 MB and cannot be compressed further. As it is such a fundamental data file that underpins a lot of research in astronomy and astrodynamics, we anticipate that having this package available on PyPi will be extremely beneficial to the community. We do not expect the size of this package to increase in the future as JPL generates new versions of the development ephemeris files only every few years. We anticipate creating new projects for each subsequent release of the development ephemeris files. 

Thank you for your consideration!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @moeyensj :wave: thanks for the detailed report.
I've set the upload limit for `naif-de440` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice Friday and weekend!

**Comment by moeyensj** [comment]
@cmaureir Thank you for the super fast turnaround!
