### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by holy-crusader-py** [pypi/support#2886]
### PyPI Username

holy_tanuki

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Boydtech7611** [comment]
Message https://instagram.com/boydtech761?igshid=NTc4MTIwNjQ2YQ== he’s the best on account recoveries

**Comment by holy-crusader-py** [comment]
Sus

**Comment by ewdurbin** [comment]
User `holy_tanuki` has valid recovery codes generated as of 2022-02-28 21:22:38.857028.

Please use those recovery codes to regain access to your account.

**Comment by holy-crusader-py** [comment]
I'm sorry but I don't have those recovery codes

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
