### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by darktohka** [pypi/support#2890]
### PyPI Username

darktohka

### Reason for request

I used a SoloKeys authentication key as 2FA. Unfortunately my SoloKeys USB broke off - the USB port itself has broken off the board. I can't use the key anymore, and I have not generated any recovery keys as far as i know.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
