### ISSUE TITLE
Project Limit Request: databricks-connect - 25 GB

### ISSUE THREAD

**Issue by vicennial** [pypi/support#2892]
### Project URL

https://pypi.org/project/databricks-connect/

### Does this project already exist?

- [X] Yes

### New limit

25 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Databricks Connect is a Spark client library that lets you connect your favorite IDE (IntelliJ, Eclipse, PyCharm, and so on), notebook server (Zeppelin, Jupyter, RStudio), and other custom applications to Databricks clusters and run Spark code.
The project has been active since 2019.

### How large is each release?

Each "total" release is ~1.2-1.4 GB. This includes releasing 5-6 individual versions at a time, each of which is around 250-300 MB.

### How frequently do you make a release?

Roughly once every 2-3 weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `databricks-connect` to 20 GB on PyPI. Happy to revisit again if/when you reach that limit.
