### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by benyaminpy** [pypi/support#2897]
### PyPI Username

benyaminpy

### Reason for request

As i said in issue #2766 i lost the access to the email account associated with the PyPi account.

Currently I’m not able to reset my password, because the email address registered with the account needs to be changed, then i will be able to reset the password.

You may change the email address to this, please.
`i65n6wbw3@mozmail.com`
### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The primary address on the account did not bounce, so we're unable to validate that this request is valid.

**Comment by benyaminpy** [comment]
> The primary address on the account did not bounce, so we're unable to validate that this request is valid.

The original email address is:
`benyamin@tutanota.de`

**Comment by ewdurbin** [comment]
Email address has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
