### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by oravi** [pypi/support#2901]
### PyPI Username

`oravidov`

### Reason for request

We can login to our account on Pypi using our username and password but unfortunately we lost access to our 2fa app and now that it's being enforced we can't deploy a new version to our package. 

We can successfully login using our username and password but can't pass the 2fa check and unfortunately didn't generate recovery codes. Is there anything we can do?

We can prove that we are the maintainers as we have access to the repository on Github. 
This is our repository - https://github.com/elementary-data/elementary and this is our python package - https://pypi.org/project/elementary-data/

Thanks for helping! any help will be greatly appreciated as we are blocked by this and can't push new versions of our package. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by oravi** [comment]
Thanks so much @ewdurbin! I've just replied to the email with the requested instructions. Please let me know if anything else is needed!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
