### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by HappyRay** [pypi/support#2903]
### PyPI Username

`happyray`

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `happyray` has valid recovery codes generated as of 2022-08-23 23:15:37.713854.

Please use those recovery codes to regain access to your account.

**Comment by HappyRay** [comment]
Thanks for looking into this. I searched again and finally found my recovery code. I was able to login using the recovery code.
