### ISSUE TITLE
PEP 541 Request: mlops

### ISSUE THREAD

**Issue by kacperpekalski** [pypi/support#2904]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/mlops

### Your PyPI username

`USER_NAME`: https://pypi.org/user/kacperxxx

### Reasons for the request

As far as I am concerned I think that this project has been abandoned due to the fact that the last modification was Oct 2, 2018 and version has been 0.1.1 since 2018. Another vital point is the fact that e-mail given by author is not valid since the given domain does not exist. There is no other option to find author of this package...

Last but not least reason is the fact that my friends and I have been creating MLOps project for our study, there is repo for our project https://github.com/kajetsz/mlops and we would like our package named on PyPI to be the same as on GitHub. We want to develop our project in the future also and update package on PyPI together with changes in our project. 

It is crucial for us to have the same name, since thanks to that our product could be complete in terms of retaining names.

There is also .png where I wanted to contact with package's owner but i was given message that domain does not exist.

![email](https://github.com/pypi/support/assets/59585352/75e5df0d-e77c-4f7f-9270-c636c9b42f65)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://libraries.io/pypi/mlops     old 

https://github.com/kajetsz/mlops/tree/main/library   our project

### Contact and additional research

![email](https://github.com/pypi/support/assets/59585352/d00c1a0c-8b7b-488a-a2eb-a3d3a2fcde09)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by directtt** [comment]
+1

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by encukou** [comment]
The current owner responded and said they want to keep maintaining the package.
This means we cannot reassign the name to you. Per PEP 541:
> Under no circumstances will a name be reassigned against the wishes of a reachable owner.

Please find a different name for your project.
