### ISSUE TITLE
File Limit Request: birdnetlib - 200 MB

### ISSUE THREAD

**Issue by joeweiss** [pypi/support#2912]
### Project URL

https://pypi.org/project/birdnetlib/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is the recommended Python library for [BirdNET-Analyzer](https://github.com/kahst/BirdNET-Analyzer). The project analyzes audio files and returns detections of more than 6,000 bird species.

### Reasons for the request

The project includes the two official BirdNET-Analyzer TensorFlow models. One of the models was recently expanded to detect 6,000 species of birds. This expanded model file pushed `birdnetlib` over the 100MB limit. 

I do not expect the project to exceed a 200MB in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @joeweiss :wave:
I've set the upload limit for `birdnetlib` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice rest of the week :tada:
