### ISSUE TITLE
File Limit Request: pmsm-pm-temp-predict - 1024 MB

### ISSUE THREAD

**Issue by OlexandrOhlashennyi** [pypi/support#2915]
### Project URL

https://pypi.org/project/pmsm-pm-temp-predict/

### Does this project already exist?

- [X] Yes

### New Limit

1024 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a university project, created for educational purposes. The idea behind it is an ML model to predict the temperature of the motor rotor.

### Reasons for the request

To solve the prediction issue, pre-trained regressors were made, but the current file size of saved model is 900MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @OlexandrOhlashennyi :wave:
can you share a URL of where the code is hosted? maybe a github repo?
Thanks!

**Comment by pradyunsg** [comment]
Closing this out, due to the lack of a response.
