### ISSUE TITLE
PEP 541 Request: humanize

### ISSUE THREAD

**Issue by hugovk** [pypi/support#2916]
### Project to be claimed

`humanize`: https://pypi.org/project/humanize

### Your PyPI username

`hugovk`: https://pypi.org/user/hugovk

### Reasons for the request

I'm the sole maintainer and already have "maintainer" access on PyPI, but not "administrator" access. I would like to ask for full admin access.

Background:

I took over maintenance of the project from the original author @jmoiron, 3.5 years ago:

* https://github.com/jmoiron/humanize/issues/85

The author gave me maintainer access to the project on PyPI. The last release had been in 2014,  since 2020 I've made 39 releases.

I would now like improve the security by setting up automated upload to PyPI via [Trusted Publishers](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/).

In the past I've also had need to "yank" a release (https://github.com/jmoiron/humanize/issues/242#issuecomment-982043670), but that's only possible as admin. I may also need to give access to more people in the future to ensure the project lives on.

See also: https://github.com/python-humanize/humanize/issues/3.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Originally: https://github.com/jmoiron/humanize
Now: https://github.com/python-humanize/humanize

### Contact and additional research

I was in touch with the author via email in Feb-Apr 2020 when I originally took over maintenance. See also https://github.com/jmoiron/humanize/issues/85.

I emailed in December 2021 and May 2023 to ask for PyPI admin access but didn't receive any reply.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by Thespi-Brain** [comment]
The Owner @jmoiron was unreachable and did not get back to us regarding the status of their project despite multiple attempts. Therefore, we consider the project abandoned per [PEP 541](https://peps.python.org/pep-0541/#abandoned-projects). I recommend that the PyPI Admins assign @hugovk as the new owner of **humanize**.

**Comment by ewdurbin** [comment]
Added 'hugovk' as 'Owner' on 'humanize'

**Comment by hugovk** [comment]
Thanks all for the help!
