### ISSUE TITLE
PEP 541 Request: agency

### ISSUE THREAD

**Issue by operand** [pypi/support#2917]
### Project to be claimed

`agency`: https://pypi.org/project/agency

### Your PyPI username

`operand`: https://pypi.org/user/operand

### Reasons for the request

This project appears unmaintained/abandoned. There were two quick releases in 2021 and nothing since.

The maintainer [tombulled](https://pypi.org/user/tbulled/) does have active projects but this does not appear to be one.

I'm using that name on an active project and would like to be able to publish as that name if possible.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

I could not find a source code repository for the existing `agency` project.

My project is here - https://github.com/operand/agency.

### Contact and additional research

I emailed the maintainer address "26026015+tombulled@users.noreply.github.com" but it bounced. Here is a screenshot:

<img width="500" alt="image" src="https://github.com/pypi/support/assets/307146/a0e165f4-21e6-46c9-8714-b283bb407993">

I also found the maintainer's GitHub account. There are two, one is archived, seen here:
https://github.com/search?q=tombulled&type=users

Neither of the accounts contained the `agency` project.

For all I can tell it does appear to be dead.

[edit] I realized after that I could just link him to this issue so I added a comment below.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by tombulled** [comment]
Hi @operand, yep not a problem at all. I don't believe PyPI lets me transfer the name to a specific person, but I can release the name so that it'll be free to claim. I'll do this for you now :slightly_smiling_face:

**Comment by yeraydiazdiaz** [comment]
@tombulled, you can transfer projects to a person by adding them as owners. Do not delete the project as that can cause problems during upload.

**Comment by tombulled** [comment]
@yeraydiazdiaz ah, thanks for the heads up - I'll try that

**Comment by tombulled** [comment]
No worries, glad that all went smoothly 🙂
