### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cyramic** [pypi/support#2919]
### PyPI Username

pughmds

### Reason for request

My 2FA was lost when my phone broke, and my recovery code isn't working and need to gain access to my Pypi account again. Is there a way to do this?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `pughmds` has valid recovery codes generated as of 2022-11-23 15:39:12.159885.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
>  my recovery code isn't working and need to gain access to my Pypi account again. Is there a way to do this?

Can you send a screenshot of the error (Please ensure the recovery code is not included)

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by cyramic** [comment]
Apologies, but I mean that my recovery code isn't working because I no longer have it due to my device breaking. I should have been clearer.

**Comment by cyramic** [comment]
Just following up on this. Is there a way to gain back access to the account even though I've lost the recovery codes?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
