### ISSUE TITLE
PEP 541 Request: ibm-code-engine-sdk

### ISSUE THREAD

**Issue by reggeenr** [pypi/support#2923]
### Project to be claimed

`ibm-code-engine-sdk`: https://pypi.org/project/ibm-code-engine-sdk

### Your PyPI username

`reggeenr`: https://pypi.org/user/reggeenr

### Reasons for the request

Hi there!

Unfortunately, we lost the ability to maintain our SDK package which is publish on PyPI as all owners and almost all maintainers left the company. In consequence, we don't have a access to the add new owners or publish a newer version of the package.

Package: https://pypi.org/project/ibm-code-engine-sdk/
Github source: https://github.com/IBM/code-engine-python-sdk

This support request is about adding myself as a new owner to the PyPI package.

Please let me know whatever verification you would like to perform or evidence you want to provide to proof that this is a legit request.

Best regards, Rico

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/IBM/code-engine-python-sdk

### Contact and additional research

All listed maintainers have left the company. Hence their corporate mail addresses, have been deactivated.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jjasghar** [comment]
I'd like to bump this too. We have a problem with code handoffs at IBM, and this one seems to have fallen through the cracks. Any chance we can get some eyes on this? 

Also IBM has a bunch of modules: 1,056 projects for "IBM" is there a standard process that we can help create with yall so when modules like this situation happens we can at least have someone who update/yank if needed?

**Comment by reggeenr** [comment]
Closing as it has been addressed with https://github.com/pypi/support/issues/4636
