### ISSUE TITLE
PEP 541 Request: autodataset

### ISSUE THREAD

**Issue by fostiropoulos** [pypi/support#2925]
### Project to be claimed

`autodataset`: https://pypi.org/project/autodataset/

### Your PyPI username

`fostiropoulos`: https://pypi.org/user/fostiropoulos/

### Reasons for the request

We want to release a package for our Repository: https://github.com/fostiropoulos/auto-dataset

to be installed as `autodataset` however the existing project published at pypi seems to be out-dated, not currently active or used by any as well as lack documentation and information. There is no open-source repository or author information attached to either.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

No repository for the current project was found. 

Replacement: https://github.com/fostiropoulos/auto-dataset

### Contact and additional research

I haven't been able to find owner information by any of their published packages.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by Thespi-Brain** [comment]
Hi @fostiropoulos,

The project owner **mli** responded to our email, indicating that they wish to keep the project. Projects are not transferred against the wishes of a reachable owner. Thank you.
