### ISSUE TITLE
File Limit Request: scancode-toolkit - 150 MB

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [pypi/support#2926]
### Project URL

https://pypi.org/project/scancode-toolkit/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

> If you have made efforts to reduce the size of your PyPI releases, mention it here.

We are compressing actively any file we can.
We also reduced the the number of license files bundled by two which limited the growth of the wheel size.

> If you bundle other packages in your project, mention it here.

we only vendored a temporary version of attrs to work around version conflicts in pickling

> If you bundle example data in your project, mention it here.

We are not bundling example data.

[scancode-toolkit](https://github.com/nexB/scancode-toolkit) is a leading code-scanning tool and has the most accurate license detection, and is widely used across the industry and open-source organizations. This project is in pypi for ~6 years and was open-source for longer.
Most of the size of scancode-toolkit comes from its database and index of licenses text and rules and its pre-built license model which supports one of the key feature. Bundling the pre-built model saves time and computing resources as it would require several minutes on each installation otherwise.
Since this is also a tool (and other tools which uses the library as dependency) used in CI, bundling this data and also the index saves valuable time and computing resources.

### Reasons for the request

We are failing the pypi upload for releases, see example here: https://github.com/nexB/scancode-toolkit/actions/runs/5245607033/jobs/9473653978#step:6:93

This is due to wheel size being ~108 MB currently. This will also expected to keep increasing slowly, maybe ~10percent increase every year, so the 150 MB limit we are asking should give us a couple of years more. This would also give us more time to work on reducing the file size.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by AyanSinhaMahapatra** [comment]
@cmaureir gentle ping, we are blocked on releasing critical bug fixes, and the file size is only ~8 percent over the limit currently, and we are requesting only a 50% percent increase in the file size limit for a widely used project. :smiley:

**Comment by cmaureir** [comment]
Hey @AyanSinhaMahapatra :wave: thanks for the detailed report!
I've set the upload limit for `scancode-toolkit` to 150 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice rest of the day! :snake:

**Comment by AyanSinhaMahapatra** [comment]
Thanks a lot @cmaureir!
