### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by erp12** [pypi/support#2931]
### PyPI Username

erp12

### Reason for request

The device with 2FA app broke beyond repair. I thought I had recovery codes setup (I even found some on file that I thought were associate with pypi) but apparently that is a bookkeeping error on my part because the pypi 2FA page during login shows the following message:

>You have not generated account recovery codes.
>
>If you lose access to your two factor methods, you may lose access to your account. [Get help with recovery codes.](https://pypi.org/help/#recoverycodes)

Any help in regaining access to the account or transitioning the 1 project under that account to a new account would be much appreciated. I'm happy to provide any alternative proof of my identity and/or the authenticity of this request you need. Thank you.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
