### ISSUE TITLE
Project Limit Request: dimod - 20 GB

### ISSUE THREAD

**Issue by arcondello** [pypi/support#2932]
### Project URL

https://pypi.org/project/dimod

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

dimod provides data structures for encoding problems for quantum, classical, and quantum-classical hybrid solvers. It also provides a shared API for said solvers.

The project has been active since 2017, so approximately 6 years.

We do not expect the size of each release to increase significantly in the future.

### How large is each release?

Each release is approximately ~220 MB.

We release binary wheels for linux/windows/osx on all currently support Python versions.
The manylinux2014 wheels are ~16MB each.
All other wheels are ~5MB
The source tarball is ~2.5 MB

The C++ parts of the project are currently implemented as a header-only library. In the future, we intend to change this and that should reduce the wheel size. However, due to the size of that effort and its effect on backwards compatibility we cannot do that right now.

We do not bundle other projects or examples with our project.

### How frequently do you make a release?

We release 1-2 times a month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by arcondello** [comment]
Edit: looking through the backlog of similar requests I have reduced the request from 25 to 20 to be consistent with other similarly sized projects.

**Comment by cmaureir** [comment]
Hey @arcondello :wave:
I've set the project limit for `dimod` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size, and maybe it's worth for you to explore the C++ dependency split.
Have a nice rest of the week :tada:

**Comment by arcondello** [comment]
Thank you!
