### ISSUE TITLE
Project Limit Request:BMTrain - 20 GB

### ISSUE THREAD

**Issue by MayDomine** [pypi/support#2933]
### Project URL

https://test.pypi.org/project/bmtrain/0.2.2/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

BMTrain is a distributed training package based on pytorch.it can support better technique to parallelize the model training in large-scaled cluster.

### How large is each release?
each release is about 0.8 GB
4 Linux Wheel at 180 MB
1 source tar ball at 10 MB

### How frequently do you make a release?

Monthly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @MayDomine  :wave:
Can you share the URL of where the project is hosted? maybe on github?
Thanks!

**Comment by MayDomine** [comment]
> Hey @MayDomine 👋 Can you share the URL of where the project is hosted? maybe on github? Thanks!

Hey, I am a main contributor of one distributed training framework based on torch.Here is my github link https://github.com/OpenBMB/BMTrain.The thing is we want to get rid of the denpendcy of torch while compiling.In order to make users easy to install our wheel, we decide to use the static link to use nccl library which makes our final wheel file oversized.

**Comment by cmaureir** [comment]
I'm happy to read that you are using an abi3 wheel to support many python versions with one wheel, it's usually what we recommend projects.

I have set the project limit for `BMTrain` to 20G on TestPyPi. Be mindful with releases at that size.
Have a nice rest of the week! :snake:

**Comment by MayDomine** [comment]
Sorry to bother you again, I also want to request the same size limit for pypi.org and i have updated the issue.

**Comment by MayDomine** [comment]
@cmaureir Please check the request again, really sorry to bother you .
