### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gonwi** [pypi/support#2936]
### PyPI Username

gonwi

### Reason for request

Lost 2FA authentification app and recovery codes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by gonwi** [comment]
Hi, 

I have lost access to the 2FA device for pypi and recovery key. Which has let me unable to upgrade this package that I maintain 
[Pypi package](https://pypi.org/project/brainrex/).

Do you have a process to recover the account?

Thanks

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by gonwi** [comment]
Replied. Thanks @ewdurbin

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
