### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by FiddlerRE** [pypi/support#2937]
### PyPI Username

fiddler

### Reason for request

Our company Fiddler Labs is a startup. One of our Ex-Fiddler employee had set up these project "Fiddler" and "Fiddler-Client". We currently have maintainer account "raghu_fiddler" which we have the password. We need PyPi team help to assume these project ownership. Or, provide a way to restore "fiddler" username. Appreciate your help. This is my email "rajesh@fiddler.ai"

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by FiddlerRE** [comment]
Hi PyPi support  We don’t know what is the primary email address that got your email. Is it possible to respond one of these ***@***.***@fiddler.aiOr, let me know if there is any other means, like my CEO sending this email, since one of the other request was to make the Fiddler AI as the organization of this account.ThanksRajeshOn Jun 25, 2023, at 5:39 AM, Ee Durbin ***@***.***> wrote:﻿
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by FiddlerRE** [comment]
Hi Pypi Support Team
 Any help in getting access to `fiddler` username (we don't know what is
the email address it is associated with) or ownership with `pypi fiddler
<https://pypi.org/project/fiddler/>` would be really helpful. Please let me
know.

Thanks
-Rajesh


Rajesh
Ekambaram
Director of Engineering

**Comment by DannyBrock** [comment]
@ewdurbin can you help here?  I am a colleague of Rajesh who opened this account recovery request.  Fiddler.ai has an older pypi.org project (project name == fiddler) that is confusing our customers (our current project == fiddler-client).  The "fiddler" project was set up a long time ago likely by an employee that is no longer with our company.  We're trying to reclaim ownership of it so we can remove it from pypi.org which will eliminate this continual source of confusion.  

If you can let us know what email address is associated with that project, we can route it to another employee that will be able to begin administering this orphaned project.  

Any consideration you can give this request would be greatly appreciated as we're completely stuck here.

Thanks,
Danny Brock, Director of Solution Engineering, Fiddler.ai
https://www.linkedin.com/in/dannybrock/

**Comment by FiddlerRE** [comment]
Hi Pypi support team,  
 Can you folks please help with this request? There are 3 projects Fiddler-Client, Fiddler, Fiddler-CLI that we don't have a way to manage since the manage button is grayed out for the maintainer. It would be grateful if you treat this request with some consideration. Or, tell us what is our process so that I can follow that and resolve this quickly.

**Comment by ewdurbin** [comment]
You're following the correct process. There is just limited time to circle back when the process falls out of band.

**Comment by ewdurbin** [comment]
The email address associated with the account successfully delivered. So we have no way to determine that the account is not in the control of the correct person. The most expedient way for you to handle this would be to ask the ex-employee to transfer ownership to your required user.

**Comment by FiddlerRE** [comment]
Hi ewdurbin, thanks for the quick response. Is it possible to let us know the email where this is successfully delivered? We are not sure who to contact. Or, is it possible to add a new fiddler email address? Since we have `fiddler` and `raghu_fiddler` has maintainers. We only have access to `raghu_fiddler`. So knowing the email address would help to contact the ex-employee.

**Comment by ewdurbin** [comment]
I see that `raghu_fiddler` User has been granted Owner privileges on the projects in question.

Closing this request as account recovery is no longer necessary.

**Comment by FiddlerRE** [comment]
Yes, I contacted few ex-employee and able to get hold off the owner. How we have more than one owner for our projects. Thanks @ewdurbin for checking. Appreciate it.
