### ISSUE TITLE
File Limit Request: mindspore-lite -- 300 MB

### ISSUE THREAD

**Issue by GiantTyrion** [pypi/support#2940]
### Project URL

https://pypi.org/project/mindspore-lite/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

MindSpore lite is a high-performance, lightweight open source reasoning framework that can be used to meet the needs of AI applications on mobile devices. MindSpore Lite focuses on how to deploy AI technology more effectively on devices. It has been integrated into HMS (Huawei Mobile Services) to provide inferences for applications such as image classification, object detection and OCR. MindSpore Lite will promote the development and enrichment of the AI software/hardware application ecosystem.

### Reasons for the request

Mindspore-lite is merging its backend-specifc packages to one unified package for linux , this will reduce the total space taken, but increase the size of a single package. Projects including mindspore-lite-ascend and mindspore-lite-gpu will then be removed to save storage space.
Could you please help increase the file size limit to 3-- MB per package? Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @GiantTyrion :wave:
Thanks for the detailed report!
I've set the upload limit for `mindspore-lite` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice rest of the week! :tada:
