### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by subroy13** [pypi/support#2941]
### PyPI Username

subroy13

### Reason for request

I remember my username and password, but lost the device with 2FA authentication app or security token. Last time I logged was long back and there was no recovery codes concept so I don't have any recovery codes generated. I need to update some fixes to one of my package in pypi.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by subroy13** [comment]
Instructions completed and replied back to the support email. Thanks!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by subroy13** [comment]
Thanks, I am able to access the account now.
