### ISSUE TITLE
PEP 541 Request: arelle

### ISSUE THREAD

**Issue by austinmatherne-wk** [pypi/support#2943]
### Project to be claimed

`arelle`: https://pypi.org/project/arelle

### Your PyPI username

`arelleteam`: https://pypi.org/user/arelleteam

### Reasons for the request

I am the primary maintainer of [Arelle](https://github.com/Arelle/Arelle), a Python-based project with over a decade of history. Utilized by regulatory agencies worldwide, end-users, and service providers, Arelle is a tool for viewing and validating financial filings. Until recently, we did not have an official PyPI package, leading many users to fork the project and upload it to PyPI themselves.

Most of these forks are not a significant issue, but there is one that has been causing confusion among users who wish to use recent versions of Arelle.

I have attempted to reach out to the email address listed on the project, but it is connected to a corporation that has [gone bankrupt](http://lendflo.com/) and is no longer operational. @Remi-Tuy @Przemek-Win

The project is using the name [arelle](https://pypi.org/project/arelle), which is trademarked, and hasn't received updates since 2018. We would like to assume ownership of this project to keep it updated and in sync with our official releases at [arelle-release](https://pypi.org/project/arelle-release/).

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Fork that's published under the name Arelle: https://github.com/FIBR-TECH/Arelle
Official fork of Arelle: https://github.com/Arelle/Arelle

### Contact and additional research

Email sent to the address published on the project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by austinmatherne-wk** [comment]
Hi PyPI team,

Is there anything I can do to help move this forward?

**Comment by Thespi-Brain** [comment]
The Owner @Przemek-Win was unreachable and did not get back to us regarding the status of their project despite multiple attempts. Therefore, we consider the project abandoned per [PEP 541](https://peps.python.org/pep-0541/#abandoned-projects). I recommend that the PyPI Admins assign @austinmatherne-wk as the new owner of **arrelle**.

**Comment by austinmatherne-wk** [comment]
Thank you again for the update.

**Comment by Przemek-Win** [comment]
@austinmatherne-wk @Thespi-Brain I would like to keep the same name for the project itself.  It is very short notice in terms of information on such a change.

**Comment by Thespi-Brain** [comment]
@Przemek-Win It was not short notice. We have been reaching out to you since September and have sent you multiple emails. But since it is your wish to keep the project, the project will still remain with you.
