### ISSUE TITLE
Project Limit Request: daisykit - 20 GB

### ISSUE THREAD

**Issue by vietanhdev** [pypi/support#2944]
### Project URL

https://pypi.org/project/daisykit

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[DaisyKit](https://daisykit.nrl.ai/) is an easy AI toolkit with face mask detection, pose detection, background matting, barcode detection and more.

**Source code:** <https://github.com/nrl-ai/daisykit>.

**Activation date:** Dec 2021.

**Reason to extend the project size:** This project contains binary files for daisykitsdk, OpenCV. We need to build the binary for as many Python versions, CPU architecture, and OSes as possible so that it can be easier for users to install and use it.
Currently, each release is ~1.8GB. However, in the future, we may support other CPU architectures, and it will cost even more spaces to store the packages.

**Update:** We find a way to reduce the binary size based on the suggestions from @cmaureir. In the meantime, we updated the request to 20GB, which is enough for ~10 releases.

### How large is each release?

~1.8GB in total.

~50MB for each linux package.
~25MB for each Windows package.
~65MB for each Apple silicon package.
~94MB for each Apple x86_64 package.

You can see the example of file sizes here: [https://pypi.org/project/daisykit/0.3.0.5/#files](https://pypi.org/project/daisykit/0.3.0.5/#files).

### How frequently do you make a release?

We make a release whenever a new feature or bugfix has been delivered. We plan to develop and release actively in the future, maybe 1 release/month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @vietanhdev :wave:
requesting 100G is really a long jump from 10G and will put your project into the top 20 https://pypi.org/stats/

Have you explore other techniques like using the Limited API https://docs.python.org/3/c-api/stable.html so you avoid having more than one package for python versions? that would reduce the size of each release by a lot.

Additionally, you could explore the option to have an universal wheel for macOS so you only release 1 instead of having one for silicon and x86_64

Let me know!

**Comment by vietanhdev** [comment]
Thank you for your suggestions! Let me try to reduce the package size first and request a smaller size.

**Comment by vietanhdev** [comment]
Hi @cmaureir !
Because reducing the package size takes some time, could I request 20GB limit in advance to have some more releases?
Thank you very much!

**Comment by cmaureir** [comment]
Hey @webknjaz :wave:
I've set the project limit for `daisykit` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice rest of the week :tada:

**Comment by webknjaz** [comment]
@cmaureir did you tag me by accident?

**Comment by cmaureir** [comment]
whoops! sorry @webknjaz  :) yeah, sorry for the wrong ping :pray: 

I meant @vietanhdev ;)
