### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by LeeeeT** [pypi/support#2946]
### PyPI Username

`LeeeeT`

### Reason for request

I lost my 2FA app and my recovery codes. I can still manage my account using API token, but I want to have access to the web interface on pypi.org.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `LeeeeT` has valid recovery codes generated as of 2022-02-26 17:37:14.161670.

Please use those recovery codes to regain access to your account.

**Comment by LeeeeT** [comment]
@ewdurbin As I said, I lost my recovery codes. Is there any other way to recover my account? Maybe via email?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
