### ISSUE TITLE
PEP 541 Request: checkmk-dev-tools

### ISSUE THREAD

**Issue by frans-fuerst** [pypi/support#2947]
### Project to be claimed

`checkmk-dev-tools`: https://pypi.org/project/checkmk-dev-tools/

### Your PyPI username

`Checkmk`: https://pypi.org/user/checkmk/

### Reasons for the request

I am the former and new maintainer - `checkmk-dev-tools` needs to be moved from my personal namespace https://pypi.org/user/frans.fuerst  to https://pypi.org/user/checkmk/ .
(If there is an easier way transfer maintainership without changing the project content / url, please let me know)

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

both new and former: https://github.com/Checkmk/checkmk-dev-tools

### Contact and additional research

Maintainer will be the same person

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
I see that both `frans.fuerst` and `checkmk` are owners of the project.
PyPI doesn't have per-user namespaces, there's nothing to move.
