### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ramanaditya** [pypi/support#2950]
### PyPI Username

ramanaditya

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `ramanaditya` has valid recovery codes generated as of 2020-12-30 04:02:41.092233.

Please use those recovery codes to regain access to your account.

**Comment by ramanaditya** [comment]
I no longer have access to the recovery codes. The mobile phone where every token and access modes were present is not accessible, and I cannot use those recovery codes. Kindly suggest any alternative method or kindly help me re-initiate the 2FA along with recovery codes.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ramanaditya** [comment]
I have created a branch on the source repository with the mentioned branch name, you can find it here: https://github.com/ramanaditya/email-service/tree/deWxuJEqFIkENPFn

**Comment by ramanaditya** [comment]
I have already replied to the Email Thread on July 1st.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
