### ISSUE TITLE
File Limit Request: h2o - 300 MB

### ISSUE THREAD

**Issue by mn-mikke** [pypi/support#2954]
### Project URL

https://pypi.org/project/h2o

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

H2O is an open-source machine learning framework. It exists for more than 8 years. The last release was published 2 months ago.

### Reasons for the request

The size of the artefact has risen after addressing internal vulnerabilities.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @mn-mikke :wave: thanks for the report.
I've set the upload limit for `h2o` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice rest of the week :tada:

**Comment by mn-mikke** [comment]
@cmaureir Thank you a lot!!!
