### ISSUE TITLE
PEP 541 Request: pytest-black

### ISSUE THREAD

**Issue by jaraco** [pypi/support#2960]
### Project to be claimed

`pytest-black`: https://pypi.org/project/pytest-black

### Your PyPI username

`jaraco`: https://pypi.org/user/jaraco

### Reasons for the request

The project has been abandoned as evidenced by the lack of response since Oct 2020 in both [Github](/shopkeep/pytest-black) and PyPI. I've reached out in https://github.com/shopkeep/pytest-black/issues/70, but given the lack of response in other issues, I'm not hopeful. I'd like to take over this project and maintain it.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/shopkeep/pytest-black/

### Contact and additional research

https://github.com/shopkeep/pytest-black/issues/70

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
We are working to contact the owner.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by Thespi-Brain** [comment]
The Owner was unreachable and did not get back to us regarding the status of their project despite multiple attempts. Therefore, we consider the project abandoned per [PEP 541](https://peps.python.org/pep-0541/#abandoned-projects). I recommend that the PyPI Admins assign @jaraco as the new owner of **pytest-black**.

**Comment by miketheman** [comment]
Added 'jaraco' as 'Owner' on 'pytest-black'
