### ISSUE TITLE
PEP 541 Request: messagebus

### ISSUE THREAD

**Issue by mardiros** [pypi/support#2962]
### Project to be claimed

`messagebus`: https://pypi.org/project/messagebus

### Your PyPI username

`mardiros`: https://pypi.org/user/mardiros

### Reasons for the request

The project messagebus has been reserved but there is no release yet.

I like to release my new project https://github.com/mardiros/messagebus here

 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

I don't know who own the name on pypi.org and I guess it is just squatting.

The source code of the package I want to host is already available at https://github.com/mardiros/messagebus

### Contact and additional research

I don't see any way to contact the current owner,
the url https://pypi.org/project/messagebus is raising a 404 http error.

By the way, if it is a reserved namespace for python.org, I am sorry for the lost of time.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Project **messagebus** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins remove the project and release the project name for future use.

**Comment by miketheman** [comment]
Added 'mardiros' as 'Owner' on 'messagebus'
