### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by seamile** [pypi/support#2964]
### PyPI Username

`Seamile`

### Reason for request

Lost 2FA authentication app.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by seamile** [comment]
I lost my phone a few months ago so my 2fa was also lost and I didn't create a recovery codes.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by seamile** [comment]
> Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

I'm sorry, I'm not sure what to reply. I haven't received any emails in my Gmail inbox.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
