### ISSUE TITLE
PEP 541 Request: xpp

### ISSUE THREAD

**Issue by iiPythonx** [pypi/support#2966]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/xpp

### Your PyPI username

`USER_NAME`: https://pypi.org/user/iiPython

### Reasons for the request

I don't think this fits perfectly into this issue category, however it's as close as I'm going to get.  
I'm trying to publish the package [xpp](https://github.com/iiPythonx/xpp) onto PyPI, however I get a 400 with the content "The name 'xpp' isn't allowed."

I'm not asking to get a transfer, since [xpp on PyPI](https://pypi.org/project/xpp) doesn't exist; so I'm assuming no project already has that name.  
My best guess is that it's deemed "too similiar" to [xp](https://pypi.org/project/xp), and if so then am I still able to get the name xpp or will I need to pick another one?

Additionally, xp hasn't been updated since January of 2021, with [most commits](https://github.com/druths/xp/commits/main) being 2017 or prior. I wouldn't count it as abandoned, but I don't think many people would be trying to install it, mistype, and then install xpp instead.

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/druths/xp
https://github.com/iiPythonx/xpp

### Contact and additional research

I have not attempted to contact the owner of xp as this isn't exactly a name dispute, I'm just trying to coin `xpp`.  
If it's too similiar and can't be changed, that's fine; I'll go with `xpplang`.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
'xpp' released to 'iiPython'.
