### ISSUE TITLE
Project Limit Request: vl-convert-python - 20 GB

### ISSUE THREAD

**Issue by jonmmease** [pypi/support#2967]
### Project URL

https://pypi.org/project/vl-convert-python/

### Does this project already exist?

- [X] Yes

### New limit

20GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

VlConvert is an optional dependency of the popular Altair Python visualization library. It provides static image export by embedding the Deno JavaScript runtime in the Python wheels.

### How large is each release?

Each release is ~500MB total (~20 MB per wheel, compiled for 5 architectures and 5 Python versions).

After hitting the 10GB limit I went through and deleted all of the release candidates that we had published, so we have a little breathing room now, but I expect to hit the limit again in a few months.

### How frequently do you make a release?

Once or twice or month

Thanks for considering!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @jonmmease :wave:
have you explore implementing the Limited API https://docs.python.org/3/c-api/stable.html to avoid having one wheel per python versions?

**Comment by jonmmease** [comment]
Hi @cmaureir, thanks for your response. Yes, since opening this issue I was able to switch to building abi3 wheels using the limited API, shared across Python versions.  So now each release is closer to 100MB.

With this improvement, we'd still appreciate a little bit more breathing room, but a limit increase to 12-15GB would now go a long way. Thanks for considering!

**Comment by cmaureir** [comment]
Thanks for your research and work @jonmmease :+1: 
I have set the new project limit for `vl-convert-python` to 15G on PyPI.
Have a nice rest of the week!
