### ISSUE TITLE
PEP 541 Request: box

### ISSUE THREAD

**Issue by waivek** [pypi/support#2968]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/box

### Your PyPI username

`USER_NAME`: https://pypi.org/user/waivek

### Reasons for the request

I get 403'd when I try to claim this via twine. Is it a forbidden word by the admins?

### Maintenance or replacement?

Replacement

### Source code repositories URLs

github.com/waivek/python_common

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @waivek,

We are working to contact the owner to determine if they're reachable and to make them aware that their project per PEP 541 policy is invalid. 

Disclaimer: We are providing support to the PyPI Administrators to validate this request and make a recommendation on the outcome and actions to be taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by Thespi-Brain** [comment]
Project **box** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by waivek** [comment]
Thank you for the update!

**Comment by miketheman** [comment]
Added 'waivek' as 'Owner' on 'box'

**Comment by waivek** [comment]
Thank you!
