### ISSUE TITLE
PEP 541 Request: ylog

### ISSUE THREAD

**Issue by iamlrk** [pypi/support#2969]
### Project to be claimed

`ylog`: https://pypi.org/project/ylog

### Your PyPI username

`iamlrk`: https://pypi.org/user/iamlrk

### Reasons for the request

Hello I can't find the package on Pypi. So, I thought I will use it. But seems like it is not available. I posted this on warehouse repo as an issue and was sent here. They informed me that the project name was previously prohibited by admin intervention. 

Hopefully this information is sufficient. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/iamlrk/ylog

### Contact and additional research

I can't contact the previous owner as the original one is hidden to me.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
I see that https://github.com/iamlrk/ylog now redirects to https://github.com/iamlrk/whylog with a corresponding PyPI project `whylog`. Do you still want the name `ylog`?

**Comment by iamlrk** [comment]
Hallo Durbin,

No I do not need the name `ylog` anymore.

Thank you!
