### ISSUE TITLE
PEP 541 Request: onnxscript

### ISSUE THREAD

**Issue by zooba** [pypi/support#2970]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/onnxscript

### Your PyPI username

`microsoft`: https://pypi.org/user/microsoft

### Reasons for the request

Appears the name has been blocked, potentially due to past typosquatting attempt?

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Our project: https://github.com/microsoft/onnxscript

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by justinchuby** [comment]
cc @abock @jcwchen

**Comment by zooba** [comment]
@di Wondering if you can bump this one as it doesn't require contacting an existing owner, and we want to publish under the name as soon as possible?

**Comment by jcwchen** [comment]
@di Thanks for looking into it. May we understand typically how long will the usual process take?

**Comment by BowenBao** [comment]
@di how to find out who is the exiting owner?

**Comment by justinchuby** [comment]
@di Would it be reasonable to consider the project invalid based on https://peps.python.org/pep-0541/#invalid-projects?

> (package has no functionality or is empty)

**Comment by justinchuby** [comment]
@di @yeraydiazdiaz @cmaureir

We here at Microsoft are planning for an upcoming release of the package. We think the current project is name squatting, based on https://peps.python.org/pep-0541/#invalid-projects ("project is name squatting (package has no functionality or is empty)").

Our project source is currently at https://github.com/microsoft/onnxscript for your reference. Could any of you help start the transfer process to transfer the name to `microsoft`: [pypi.org/user/microsoft](https://pypi.org/user/microsoft)? Much appreciated, thanks!

**Comment by justinchuby** [comment]
Thanks a lot @ewdurbin for your help! We truly appreciate it.

**Comment by zooba** [comment]
Thanks, Ee!
