### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by raditya1** [pypi/support#2971]
### PyPI Username

cossdk

### Reason for request

Dear PyPi admin,
 
We are part of IBM, using pypi for our python project under the username cossdk.
We have had changes in the management for this project, and lost track of who owned the application for 2FA associated with our account.
We do have username and password, can login successfully but are getting blocked on 2FA.
 
Could you please point us to see how can we reset 2FA? 
Without this help we are currently blocked and unable to use our account.
 
Thanks & Regards,
Aditya Raval
Manager, IBM Cloud Object Storage

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by raditya1** [comment]
Hello,

I did not get any email with instructions to any of my emails. The purpose
of this request is to reset 2FA as the original owner/requester has left
our company. Could you please help forward instructions to either this
email or to my company email ***@***.***?

Much appreciate your help.

Thanks & Regards,
Aditya Raval
Manager, IBM Cloud Object Storage

**Comment by IBMalok** [comment]
@ewdurbin - Could you please help us? we blocked with the release.

**Comment by raditya1** [comment]
@ewdurbin we are still needing your teams help here please. We are blocked for last 3 weeks. We will appreciate your help in prioritizing this request. This is impacting our production release. Thanks

**Comment by ewdurbin** [comment]
The address did not bounce, so it was successfully delivered somewhere.

Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by raditya1** [comment]
Ok, thank you - I will initiate that email. Thank you!

**Comment by ewdurbin** [comment]
Contacted via requested email address, please read the instructions and reply to proceed with recovery.
