### ISSUE TITLE
PEP 541 Request: abacus

### ISSUE THREAD

**Issue by epogrebnyak** [pypi/support#2973]
### Project to be claimed

`abacus`: https://pypi.org/project/abacus/

### Your PyPI username

`epo78`: https://pypi.org/user/epo78/

### Reasons for the request

The original Tornado helper project was uploaded in PyPI in 2014 and not updated since. It is also written in Python 2.

I wrote an e-mail to maintainer, will post if I get any feedback.

`abacus` makes a good name for a new project in accounting (started 3 years ago and actively maintained), new name can help profilerate open source tools in the accounting domain.  

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The orginal project is not updated since 2015 and written in python 2, reaching end of life itself. 

https://bitbucket.org/rit/abacus/src/master/

Here is a project I intend to publish:

https://github.com/epogrebnyak/abacus

Started about 3 years ago, actively maintained.

### Contact and additional research

Wrote an email to maintainer Rit Li, describing the request (2023-06-28)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rit** [comment]
@epogrebnyak I _was_ the original owner. The current owner is https://pypi.org/user/asteif/

**Comment by epogrebnyak** [comment]
To update the status: there are no contacts of current package owner, Adi Steif, last  update is in 2015.

**Comment by epogrebnyak** [comment]
Wrote an e-mail to Adi Steif using e-mail form here: https://www.bcgsc.ca/people/adi-steif

**Comment by epogrebnyak** [comment]
Current owner wrote back they want to keep a name for their project, so closing the issue.

**Comment by Thespi-Brain** [comment]
Closing issue since both new to-be-owner and previous owner worked it out themselves
