### ISSUE TITLE
File Limit Request: katrain - 150 MB

### ISSUE THREAD

**Issue by sanderland** [pypi/support#2977]
### Project URL

https://pypi.org/project/KaTrain/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is a popular open-source tool for analyzing go games with AI.
It includes executables and model files for "KataGo" to work out-of-the-box.

### Reasons for the request

However, the model it packages is severely out of date, confusing users, and causing a maintenance burden to the project and the upstream KataGo maintainer.
The latest model is ~95mb in size, up from the old ~35mb. Combined with some other files, the wheel is around 120Mb. Allowing some margin, I am requesting 150Mb.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @sanderland :wave: thanks for the report.
I've set the upload limit for `katrain` to 150 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice rest of the week!
