### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by EgogorGames** [pypi/support#2978]
### PyPI Username

EgogorGames

### Reason for request

Dear PyPi administration,

I lost the 2FA authentication app(because I bought a new phone and forgot to transfer the authenticator) and accidentally deleted the file where I stored recovery codes.
I have all other login credentials: email and password. 
Hope you can help me.

Thanks,
EgogorGames

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
