### ISSUE TITLE
Project Limit Request: PyMuPDF - 20 GB

### ISSUE THREAD

**Issue by julian-smith-artifex-com** [pypi/support#2980]
### Project URL

https://pypi.org/project/PyMuPDF/

### Does this project already exist?

- [X] Yes

### New limit

20GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

PyMuPDF is a long-standing and widely used Python binding for the MuPDF library.

We are about to transition to a new internal implementation, during which we will be releasing larger wheels then usual (20-30MB), containing the old and new implementations, so that users can initially opt in, and then later opt out of the new implementation.

After the transition, the wheel size will revert to the previous 10-15MB size.

### How large is each release?

Last release was 411 MB.

29 wheels, each 10-15MB:
    Python 3.7, 3.8, 3.9, 3.10, 3.11:
        manylinux: x86_64, aarch64
        windows: win32, win_amd64
        macos: x86_64, arm64

One sdist: 60 MB.

We make a special build of the embedded MuPDF to reduce stored fonts.

### How frequently do you make a release?

Approx every 1-3 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @julian-smith-artifex-com :wave:
Have you explore ways to reduce the amount of wheels per release and then reducing the overall size of your releases? Maybe you can check the Limited API https://docs.python.org/3/c-api/stable.html and with that you will only have
2 wheels for linux + 2 for windows + 2 for macOS (avoiding having 1 per python version as well).

Additionally, you can look into generating universal wheels for macOS, so then you have one for x86_64 and arm64.

**Comment by julian-smith-artifex-com** [comment]
Unfortunately the suggestions above don't help in this particular case.

* We have already reduced the embedded font files to a minimum.

* PyMuPDF uses SWIG, which cannot use Python's limited API.

* Most of the size of our wheels is from shared libraries, so a MacOS universal wheel would not reduce the overall size of a release, and would double the download from `pip install pymupdf`.

We have looked at splitting our releases in two wheels, one containing shared libraries that do not depend on the Python version, and a smaller wheel that contains Python version-specific code. This would save space and can be made to work locally, but the build+release process on github doesn't seem flexible enough - for example cibuiwheel cannot build two wheels and test them together.

It seems a false economy to adopt complicated and fragile technical workarounds for the sake of saving just a few GB of disk space.

Would it be possible to pay for a few GBs of extra disk space on pypi.org?

**Comment by JorjMcKie** [comment]
@cmaureir - I am another maintainer of this package.
As @julian-smith-artifex-co is on vacation, let me re-iterate that we are in a precarious situation:
We urgently need to publish the next version!
Following your ideas, we have re-configured our delivery configuration. This entails separating the largest binary part of the package (which is a Python version-agnostic shared library) in separate wheels. These wheels can be put in a separate PyPI package. They - by there very nature - also have a low change rate.
The platform- and Python version-specific wheels as a consequence are being reduced to 4 to 5 MB each, which will bring down our total version size across all platforms from over 400 MB to about 10% of that size.

I sincerely hope you will be able to open up a way for us to continue serving the community with new versions.

Thank you!

**Comment by cmaureir** [comment]
Hey there @julian-smith-artifex-com  and @JorjMcKie :wave:
sorry I was out a couple of weeks ago, and I was trying to catching up with work the past one.

I have set the project limit of `pymupdf` to 20G on PyPI.
Have a nice week :tada:

**Comment by JorjMcKie** [comment]
@cmaureir Thank you very much indeed! What a relief ...
