### ISSUE TITLE
Project Limit Request: aws-cdk.asset-awscli-v2 - 20 GB

### ISSUE THREAD

**Issue by rix0rrr** [pypi/support#2981]
### Project URL

https://pypi.org/project/aws-cdk.asset-awscli-v2/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It is a component package for the AWS CDK v2 that contains code that backs an AWS Lambda layer for IaC (if not in this package, the content would be include in the AWS CDK v2 package instead, which only moves the weight around, doesn't actually reduce it).

This package was accidentally being released every day. I have updated the automation to only release on meaningful updates, which should be far fewer than every day.

### How large is each release?

Every release is ~53MB.

It contains a data artifact that needs to be shipped to AWS CDK users, containing the AWS CLI in a format that can be loaded directly into a Lambda Layer.

### How frequently do you make a release?

Plan is to do it once every 2 weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @rix0rrr  :wave: thanks for the report.
I've set the project limit for `aws-cdk.asset-awscli-v2` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice rest of the week :snake:
