### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by CiaranWelsh** [pypi/support#2983]
### PyPI Username

ciaran.welsh

### Reason for request

The email address associated with the account has been deleted and I therefore cannot access my account. I am the author of a few packages, one of which is called pycotools3. I'd like to associate this account with my current email address. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
I have attempted to contact the primary email address and received a bounce notification.

Please email support@pypi.org from the address you would like to use, including a link to this issue, in order to proceed.

**Comment by Thespi-Brain** [comment]
Closing due to non response
