### ISSUE TITLE
Project Limit Request: Matplotlib - 50 GB

### ISSUE THREAD

**Issue by tacaswell** [pypi/support#2984]
### Project URL

https://pypi.org/project/matplotlib/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

We have been active from early 2000s and are a critical project.

As we contain c-extensions we ship a number of wheels.   Given the faster release cadence of CPython (meaning more supported versions of Python at any given time) and proliferation of supported platforms the number of wheels we publish may increase further.

### How large is each release?

~400 MB

We publish 40 wheels that are between 7 and 12 MB each and an sdist which is 38MB (the wheels do not contain binary artifacts for testing the sdist does).

### How frequently do you make a release?

Every 2-3 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @tacaswell :wave: thanks for the report.
I've set the project limit for `matplotlib` to 50 GB on PyPI. I'm certain that will keep the project safe for some time.
Have a nice rest of the week :tada:

**Comment by tacaswell** [comment]
Thank you for the prompt response and the limit increase!
