### ISSUE TITLE
File Limit Request: BMTrain - 200 MB

### ISSUE THREAD

**Issue by MayDomine** [pypi/support#2985]
### Project URL

https://test.pypi.org/project/bmtrain/0.2.2/
https://pypi.org/project/bmtrain/0.2.2/

### Does this project already exist?

- [X] Yes

### New Limit

500MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

BMTrain is a distributed training package based on pytorch.it can support better technique to parallelize the model training in large-scaled cluster.

### Reasons for the request

The thing is we want to get rid of the denpendcy of torch while compiling.In order to make users easy to install our wheel, we decide to use the static link of nccl library to compile our toolkit which makes our final wheel file oversized.The final singal wheel file will be 150mb each.And we have a multi-python version wheel.So I want to apply for 200MB maximum size limit  for each wheel file so that we can upload the wheel file then.
Our project has got about 300+ stars and turns out the efficient tool to deploy the model training easily.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by MayDomine** [comment]
@cmaureir

**Comment by di** [comment]
I've set the upload limit for `BMTrain` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
