### ISSUE TITLE
PEP 541 Request: fsw

### ISSUE THREAD

**Issue by bhushan-mohanraj** [pypi/support#2987]
### Project to be claimed

`fsw`: https://pypi.org/project/fsw

### Your PyPI username

`bhushan-mohanraj`: https://pypi.org/user/bhushan-mohanraj

### Reasons for the request

I do not currently see a project published at https://pypi.org/project/fsw. However, I have been unable to upload a project of the same name via `twine`.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: none.
Mine: https://github.com/bhushan-mohanraj/fsw.

### Contact and additional research

I could not contact the current owner because I do not see a project published at the given URL.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
'fsw' released to 'bhushan-mohanraj'.
