### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vprusso** [pypi/support#2988]
### PyPI Username

vprusso

### Reason for request

Lost 2FA authentication app or security token

I am unable to use a 2FA authenatication application to recover my account. I do not recall ever setting one up, so I'm not sure if I had done this on a prior device and forgotten about it or what, but I cannot login to my account. 

If I can provide any additional information, please let me know!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by vprusso** [comment]
Thank you @ewdurbin ! Branch has been created here: https://github.com/vprusso/scirate/tree/xnocdhzpkB6CxHVU
