### ISSUE TITLE
PEP 541 Request: depl

### ISSUE THREAD

**Issue by aaronsgithub** [pypi/support#2990]
### Project to be claimed

`depl`: https://pypi.org/project/depl

### Your PyPI username

`aaronspypi`: https://pypi.org/user/aaronspypi

### Reasons for the request

The package name `depl` was previously in use but never made it past an alpha release, and was archived on github.

I contacted the previous maintainer of the depl package via email, asking if they would be willing to release or transer ownership of the depl package.

I received a response saying they had deleted the package:

> Hi Aaron
> 
> I just deleted depl. Have fun :)
> 
> ~ *****

As the project has now been deleted from pypi following my request, I would like to claim the name :)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The "current" project has been deleted from pypi.

Work on the project I intend to publish is taking place here:
[https://github.com/aaronsgithub/depl](https://github.com/aaronsgithub/depl)

### Contact and additional research

I have received an email from the previous owner confirming deletion of the project which I can forward upon request.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by aaronsgithub** [comment]
Is the process for when a package is deleted from pypi documented anywhere?

I imagine the names of deleted packages are ringfenced to prevent a [left-pad](https://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm) type incident, but I couldn't find documented behaviour for what happens after a pypi package is deleted.

Pep 541 doesn't really state what happens in the case of a deleted package.

**Comment by di** [comment]
Handling this one out of queue because it's due to the ultranormalization filter and doesn't require maintainer reachability.

You should be able to publish to https://pypi.org/project/depl now.

**Comment by rainy-lang** [comment]
@di Hi Dustin, I had a similar issue where I wanted to claim the name "sgl". I got in touch with the previous owner who agreed to delete the package and allow me to take the name. But now I'm getting "The name is too similar to an existing project."
Could you take a look at #3271?
