### ISSUE TITLE
File Limit Request: leadtools - 400 MB

### ISSUE THREAD

**Issue by LEADTOOLSSupport** [pypi/support#2997]
### Project URL

https://pypi.org/project/leadtools/

### Does this project already exist?

- [X] Yes

### New Limit

400 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The project is the Python wrapper for the renowned LEADTOOLS SDK (https://www.leadtools.com/), which has been a professional and reliable software development kit in the market for over 30 years. In 2023, we are expanding the SDK's platform support, which currently includes .NET, Java, JavaScript, Android, and Apple, to encompass Python as well. Our goal is to upload a Wheel package containing the necessary wrappers, enabling developers to effortlessly install and utilize our Python binaries directly from PyPI.

### Reasons for the request

The wheel package is designed to allow our customers to access our software development kit via Python. Some of the binaries included are over 100MB each, which results in a total size between 250MB-300MB depending on the platform chosen. We support Windows, Linux, and MacOS on Python.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
This was resolved in https://github.com/pypi/support/issues/2826, please don't open duplicate issues.
