### ISSUE TITLE
PEP 541 Request: Extra

### ISSUE THREAD

**Issue by takluyver** [pypi/support#3002]
### Project to be claimed

`extra`: https://pypi.org/project/extra

### Your PyPI username

`takowl`: https://pypi.org/user/takowl

### Reasons for the request

The `extra` package does not exist, but uploads are blocked. Looking [on libraries.io](https://libraries.io/pypi/extra), it appears that a package was uploaded in 2019 and 2020 but has since been deleted; it's not clear if the author deleted it or if it was removed by admins.

We're using the name 'EXtra' for a group of related tools for working with data generated at [European XFEL](https://www.xfel.eu/) - the 'European XFEL Toolkit for Reproducible Analysis'. We already have the specific packages [EXtra-data](https://pypi.org/project/EXtra-data/) and [EXtra-geom](https://pypi.org/project/EXtra-geom/) on PyPI. We're now looking to publish a broader package with a collection of useful analysis routines, which we're hoping to call **EXtra**.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/European-XFEL/EXtra

### Contact and additional research

There is no current owner

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
'extra' released to 'takowl'.
