### ISSUE TITLE
File Limit Request: indico-fonts - 125 MB

### ISSUE THREAD

**Issue by ThiefMaster** [pypi/support#3004]
### Project URL

https://pypi.org/project/indico-fonts/

### Does this project already exist?

- [X] Yes

### New Limit

125 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The `indico-fonts` package contains binary font files for the LaTeX/PDF generation that's part of Indico (project links below).

- https://github.com/indico/indico
- https://pypi.org/project/indico
- https://getindico.io/

### Reasons for the request

We'd like to include CJK fonts (asian typesets - PR: indico/indico-fonts#3) in this package, and this increases the compressed size from about 25MB to 95MB. 
I'm requesting 125 MB instead of just e.g. 100 MB simply to have some space left.

Note that while the "main" indico package has frequent releases (it's a very actively developed and maintained project), this particular package has VERY few releases (it can easily go 5+ years without a new release) since it does not contain any code but just those data files.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ThiefMaster** [comment]
I just realized that we already have an increased limit (100MB) so this *should* work for the planned release, but we'd still appreciate the increase to have some space upwards in case we need to include another font one day

**Comment by di** [comment]
I've set the upload limit for `indico-fonts` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
