### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jllong-usgs** [pypi/support#3007]
### PyPI Username

jllong

### Reason for request

I don't recall setting up 2FA but it's asking me for an authenticator code. If I had set that up, it would have been with a device to which I no longer have access. I cannot locate any stored recovery codes either.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by di** [comment]
Closing per the user's request!
