### ISSUE TITLE
PEP 541 Request: jobs

### ISSUE THREAD

**Issue by larryhastings** [pypi/support#3013]
### Project to be claimed

`jobs`: https://pypi.org/project/jobs

### Your PyPI username

`larry`: https://pypi.org/user/larry

### Reasons for the request

User "hr" has been namespace-squatting the "jobs" package for ten years now.

The first and only "release" of the "jobs" package, version "0.0.1dev", was just over ten years ago, April 19 2013.  This release appears to contain no files.

(I don't quite understand this concept; I assumed PyPI releases had to have files associated with them.  But I can't figure out any way to download files from this project.  "pip3 install jobs" fails, the project has no statistics on "PyPI Stats", and PyPI itself never shows me a downloadable file.  I guess it really just has no files.)

There's no homepage for the project; the project description has an external link to a "roadmap" on GitHub, which is a dead link.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current project has no repositories.

I have a private repository, which I'm waiting to make public once I get a good name for it.  If necessary I can make this repository public.

### Contact and additional research

I emailed the owner a week ago via their PyPI-listed email address, asking if they'd transfer the package name to me. I received no reply.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by takluyver** [comment]
> I assumed PyPI releases had to have files associated with them.

I believe that's true for new releases now, but historically (before Warehouse) you could 'register' a package before uploading it, and that appears to be the case here. This does seem like a case of name squatting.

**Comment by Thespi-Brain** [comment]
Hi @larryhastings,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Disclaimer: Final determination will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
Project **jobs** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Added 'larry' as 'Owner' on 'jobs'
