### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tawnkramer** [pypi/support#3016]
### PyPI Username

tawnkramer

### Reason for request

My phone was dropped and screen broken. It was very expensive to fix so I bought a replacement. I have not been able to transfer the old Authenticator keys. So I’m not able to do 2fa with my Pypi account. Can you help me?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
