### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ananelson** [pypi/support#3020]
### PyPI Username

ananelson

### Reason for request

Hi, I don't recall setting up 2FA, and in any event I don't have an authenticator generator in any of my usual places, so I guess I'm locked out of pypi. I was logging in to transfer a project to a new maintainer as I am on parental leave and not active as a developer at the moment. Thank you.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ananelson** [comment]
Responded via email - thank you! :)

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
