### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by silviodarko** [pypi/support#3022]
### PyPI Username

lawliet.l.winchester@gmail.com

### Reason for request

**HELP**!

No username works, I try to create the username at: https://test.pypi.org/account/register/
or at: https://pypi.org/account/register/
 
It just doesn't work, I've tried more than 100 different names, I hope you can help me, I really need to advance in my college, please help me, or create an account for me.

my email is: lawliet.l.winchester@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
No account exists with this email address.
