### ISSUE TITLE
File Limit Request: typesense-server-wrapper - 120 MB

### ISSUE THREAD

**Issue by grantjenks** [pypi/support#3023]
### Project URL

https://pypi.org/project/typesense-server-wrapper

### Does this project already exist?

- [X] Yes

### New Limit

120 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is a small wrapper around the typesense-server binary. Typesense is a fast, typo-tolerant, keyword-based search engine.

The typesense-server binary is ~300 MB uncompressed. In the source tarball and wheel, it compresses down to ~111 MB. Compressing the binary further is unlikely.

### Reasons for the request

The reason to include the binary is to improve the developer experience and integration with third-party systems like Heroku, etc.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by grantjenks** [comment]
Previous attempt to upload: https://github.com/grantjenks/python-typesense-server-wrapper/actions/runs/5583693126/jobs/10204261373

**Comment by di** [comment]
I've set the upload limit for `typesense-server-wrapper` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
