### ISSUE TITLE
File Limit Request: sourcery - 200 MB

### ISSUE THREAD

**Issue by brendanator** [pypi/support#3024]
### Project URL

https://pypi.org/project/sourcery/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Sourcery is a IDE extension and CLI tool for reviewing Python code and suggesting refactorings to improve the quality of that code.

The project is built as a single executables for each OS (using Nuitka), whenever we add a new dependency it increases the size of the package, so we try to avoid this whenever possible.

### Reasons for the request

We need to add a large new dependency to it but it's taking us over the 100MB limit. I hope we won't go much over 100MB but am asking for 200MB just for some margin and to avoid ever needing to ask again

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @brendanator  :wave:
I've set the upload limit for `sourcery` to 200 MB on PyPI, I couldn't on TestPyPI because the project doesn't exist. Please create it if you still need it and open a new request.
Also please be mindful of the frequency of releases at that size. 
Have a nice week!
