### ISSUE TITLE
PEP 541 Request: glados

### ISSUE THREAD

**Issue by drjrm3** [pypi/support#3028]
### Project to be claimed

`glados`: https://pypi.org/project/glados

### Your PyPI username

`drjrm3`: https://pypi.org/user/drjrm3

### Reasons for the request

I am writing a `glados` application under MIT which wraps prometheus and uses `Turret`s to monitor specific metrics. I would like to use the `glados` project in PyPi but the current project using that name was released in Apr 20, 2020 and has not been updated since Jun 3, 2020 as per the github page.

I have reached out to the owner asking if they plan to maintain the project or if they can release it and have not heard back.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: https://github.com/zpriddy/GLaDOS

Replacement project: https://github.com/drjrm3/glados

### Contact and additional research

I have attempted to reach out to the owner and ask if they plan to continue maintenance or can release it and they have not responded.

I have thought about alternate titles for my repo but it is very much built on the "glados"  / "turret" relationship of `glados` deploying, using, and hearing from `turret`s and so believe that `glados` is the best name possible for this project as a nod to the 2007 Portal game.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @drjrm3,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Disclaimer: Final determination will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
Hi @drjrm3,

The project owner @zpriddy has responded back and they indicated that they wish to keep the project. Projects cannot be transferred against the wishes of a reachable party. Therefore, we are closing this issue.
