### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sophloire** [pypi/support#3030]
### PyPI Username

BrukerAFMiSoftware

### Reason for request

My name is Sophie Loire. I am a software engineer at Bruker Santa Barbara. I am managing the pypi account for nanoscope a toolbox created by my team. The 2 factor identification was linked to the Authenticator app on my phone which got lost due to memory issues. I had not yet setup recovery codes. 
We need to release a new version of our nanoscope toolbox as it currently does not support past 3.7.8 and it is out of support.

Please help me recover this account.

Thank you. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
