### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ScottDelbecq** [pypi/support#3039]
### PyPI Username

`s.delbecq`

### Reason for request

Hi, my 2FA authentification app (Google Authenticator) lost all my history of codes including PyPi. I also can't find my recovery codes and might have not ever generated any.
Thank you for your help.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `s.delbecq` has valid recovery codes generated as of 2022-02-23 07:23:46.686855.

Please use those recovery codes to regain access to your account.

**Comment by ScottDelbecq** [comment]
Thank you @ewdurbin but the issue is that I cannot find these recovery codes.
Hence, I cannot do anything from my user side to regain access right now.
What are the options?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
