### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by idling-mind** [pypi/support#3043]
### PyPI Username

idling-mind

### Reason for request

Lost 2FA authentication app.

my phone got reset automatically and lost the 2FA app (microsoft authenticator). I wanted to recover the accounts from the backup. however, the instructions on the app was not clear enough and I ended up overwriting the backup and lost all the 2FA codes. I am unable to find the re-covery codes as well!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by idling-mind** [comment]
hi, I could not locate those. That's the reason for this request.

**Comment by idling-mind** [comment]
Hi, Should I expect this to be resolved? or create a new account altogether?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by idling-mind** [comment]
Thankyou!
