### ISSUE TITLE
File Limit Request: stable-retro - 150 MB

### ISSUE THREAD

**Issue by MatPoliquin** [pypi/support#3044]
### Project URL

https://pypi.org/project/stable-retro

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Maintained fork of OpenAI's gym-retro.
Under this name project started late 2021.

It's a library for researchers that want to test their Machine Learning models on retro games.
Which means we have lots of data required to support hundreds of games (roms are not included of course, but we need save states)

It's hard to remove save states because that would go against being able to reproduce results in a consistent way which is very important for machine learning research

### Reasons for the request

Currently we are at 150MB and there is no way to reduce size without compromising the nature of the project
As we add support for more retro envs we will increase size

the original gym-retro has their size limit increased

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `stable-retro` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
