### ISSUE TITLE
File Limit Request: skyramp - 250MB

### ISSUE THREAD

**Issue by texmachina** [pypi/support#3045]
### Project URL

https://pypi.org/project/skyramp/

### Does this project already exist?

- [X] Yes

### New Limit

250MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Skyramp is a new testing toolset for devs that helps ensure services under development function as intended in production.

Website: https://www.skyramp.dev

### Reasons for the request

We don't expect a large increase in the near future for our package size. The reason for the large package size is that we are bundling multiple different architectures and OS combos of shared libraries into our package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @texmachina :wave:
I've set the upload limit for `skyramp` to 250 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
