### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Vincent-Stragier** [pypi/support#3046]
### PyPI Username

VincentS9

### Reason for request

Lost 2FA authentication app or security token.
I do not remember having configured the 2FA authentication app, but I'm requested to provide an authentication code.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `VincentS9` has valid recovery codes generated as of 2022-01-17 17:48:22.600919.

Please use those recovery codes to regain access to your account.

**Comment by Vincent-Stragier** [comment]
Thanks, I forgot about the recovery codes. I regained access now.
