### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by np84** [pypi/support#3048]
### PyPI Username

'nicop84'

### Reason for request

Dear PyPI Team,

I have lost my 2FA authentication app.

In fact, I do not even remember that I ever set up 2FA for pypi :(. I have a 2FA app that I use for "everything", but for unknown reason, it seems that I used a different app for pypi (and I do not have access to this app any more). 

It would be fantastic if you can help me to revocer my account. 
Thanks and best,
Nico

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
