### ISSUE TITLE
File Limit Request: lmdeploy - 200 MB

### ISSUE THREAD

**Issue by lvhan028** [pypi/support#3053]
### Project URL

https://pypi.org/project/lmdeploy/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

LMDeploy is a toolkit for compressing, deploying, and serving LLM, developed by the [MMRazor](https://github.com/open-mmlab/mmrazor) and [MMDeploy](https://github.com/open-mmlab/mmdeploy) teams. It has the following core features:

Efficient Inference Engine (TurboMind): Based on [FasterTransformer](https://github.com/NVIDIA/FasterTransformer), we have implemented an efficient inference engine - TurboMind, which supports the inference of LLaMA and its variant models on NVIDIA GPUs.

Interactive Inference Mode: By caching the k/v of attention during multi-round dialogue processes, it remembers dialogue history, thus avoiding repetitive processing of historical sessions.

Multi-GPU Model Deployment and Quantization: We provide comprehensive model deployment and quantification support, and have been validated at different scales.

Persistent Batch Inference: Further optimization of model execution efficiency.

### Reasons for the request

The size of LMDeploy prebuilt package is over 100MB. 
The size is going to increase as more and more features are developed.
Therefore, we apply for an extra 100MB of storage for uploading lmdeploy python package. 
We would greatly appreciate your kindness if our application can be approved. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @lvhan028 :wave:
I've set the upload limit for `lmdeploy` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
