### ISSUE TITLE
File Limit Request: spylizard - 500 MB

### ISSUE THREAD

**Issue by hbadi** [pypi/support#3054]
### Project URL

https://pypi.org/project/spylizard/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Spylizard is a python wrapper for sparselizard (a multiphysics simulation program).
The new release has an increase file size cause of share dynamic libraries now included in the python package.

### Reasons for the request

Hello,

I tried to uplodad the new 0.32 version of spylizard package which is now 51M (tar.gz) but i get the followin error : 
![image](https://github.com/pypi/support/assets/1440055/abcdd876-d574-48f5-8ae9-9e3a90e5b442)

Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
> The new release has an increase file size cause of share dynamic libraries now included in the python package.

Hi, can you explain what dynamic libraries you need to include in your releases and why?

**Comment by di** [comment]
Closing due to lack of response.
