### ISSUE TITLE
PEP 541 Request: plugin

### ISSUE THREAD

**Issue by SirRender00** [pypi/support#3062]
### Project to be claimed

`plugin`: https://pypi.org/project/plugin

### Your PyPI username

`emachi`: https://pypi.org/user/emachi

### Reasons for the request

1. ABANDONED
  a. No project homepage
  b. No discernible Github repo
  c. No email found
  d. No source distribution

```
pip3 install plugin
ERROR: Could not find a version that satisfies the requirement plugin (from versions: none)
ERROR: No matching distribution found for plugin
```

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Replacement: https://github.com/pyplugin/pyplugin 

### Contact and additional research

No email or project homepage available on pypi

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @SirRender00,

We are working to contact the owner to see if they're reachable and have sent them a courtesy message.

Disclaimer: Final determination will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
Project **plugin** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins delete the project and release the name for future use.
