### ISSUE TITLE
File Limit Request: yaoxing-ali - 300 MB

### ISSUE THREAD

**Issue by lwdoubles** [pypi/support#3066]
### Project URL

https://pypi.org/project/yaoxing-ali

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

the project is to release a software which optimizes Deep learning models training procedure

### Reasons for the request

Our whl packages include large static libraries and dynamic libraries, so we need to request additional limit

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
> the project is to release a software which optimizes Deep learning models training procedure

Hi, can you provide a more detailed description of what this project is? Do you have a source code repository with a README that you can share with us?

> Our whl packages include large static libraries and dynamic libraries, so we need to request additional limit

Can you explain what libraries need to be included in your releases, and why?
