### ISSUE TITLE
Project Limit Request: grpcio-tools - 100 GB

### ISSUE THREAD

**Issue by XuanWang-Amos** [pypi/support#3072]
### Project URL

https://pypi.org/project/grpcio-tools/

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

grpcio-tools is package that provides tools for working with gRPC, it can be used to generate Python stub code from `.proto` files, which makes it easier to develop gRPC clients and servers in Python.

It's been active for more than 5 years.

### How large is each release?

Each release is about ~200MB, containing only `.whl` files for all our supported python versions (Python 3.7-3.10 for now) and platforms.

### How frequently do you make a release?

Roughly every month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `grpcio-tools` to 100 GB on PyPI.
