### ISSUE TITLE
Account recovery request (on TestPyPI)

### ISSUE THREAD

**Issue by rayluo** [pypi/support#3083]
### PyPI Username

rayluo

### Reason for request

Lost 2FA authentication app or security token.

By the way, I have a matching account on PyPI which I have access to. Previously I did not pay enough attention to my TestPyPI account. I thought they share same TOTP, but apparently not. Please help reset my TestPyPI account. Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by rayluo** [comment]
Gentle ping to @ewdurbin to see if this can be reset on the ground that the user/email on PyPI match?

My projects' release procedure includes test shipping on TestPyPI. It this issue can be addressed therefore unblock my several pending releases, it would be great. Thanks for your consideration.

**Comment by ewdurbin** [comment]
2FA on test.pypi.org reset.
