### ISSUE TITLE
Change username to lowercase

### ISSUE THREAD

**Issue by wolph** [pypi/support#3086]
### PyPI Username

`WoLpH`

### Reason for request

I've changed my Github username (and username on other platforms) for many years already, but I noticed that my PyPI username is lagging behind so I was hoping that I could have my username changed here as well :)

To summarize, I'm trying to do a: `s/WoLpH/wolph/gi`

This request is similar to these two:
 - https://github.com/pypi/support/issues/73
 - https://github.com/pypi/support/issues/1230

Similar to issue #1230 I am forced to use a template so I chose this one as well.

Thanks in advance!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Done.

Note: Unfortunately it seem that these kinds of changes are no longer as easily accomplished, especially for users with many projects or a long history on PyPI. Changes to our schema have made it so the necessary update cascades through all JournalEntry objects for all Projects owned by the user. This update took quite some time to propagate.

**Comment by ewdurbin** [comment]
Second Note: It may take > 24 hours for this to be visible across all public pages of PyPI as caches clear.

**Comment by wolph** [comment]
Thank you very much @ewdurbin
