### ISSUE TITLE
PEP 541 Request: yardstick

### ISSUE THREAD

**Issue by wagoodman** [pypi/support#3090]
### Project to be claimed

`yardstick`: https://pypi.org/project/yardstick

### Your PyPI username

`wagoodman`: https://pypi.org/user/wagoodman

### Reasons for the request

I have a project (https://github.com/anchore/yardstick) that I'd like to publish under the name "yardstick" but the name is already taken by this project: https://pypi.org/project/yardstick/. The current package was created in 2015 and has no releases. The source repo for the current yardstick project (https://github.com/tundish/pyoncannon) has not seen an updated since 2016. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

My project that I intend to replace the current project: https://github.com/anchore/yardstick

Ultimately I'd like to transfer the name for this project to the `anchore` username: https://pypi.org/user/anchore/

The abandoned project (https://pypi.org/project/yardstick/):  https://github.com/tundish/pyoncannon

### Contact and additional research

Per PEP541, I've attempted to reach out to the current maintainers, however there is no email listed in any of the project material on PyPI or source repo. I've reached out in the project's source repo with issue 1 (https://github.com/tundish/pyoncannon/issues/1) with no reply so far (~> 6 weeks~ 9 months old, following the PEP guidelines).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by wagoodman** [comment]
Actually, I was reviewing the PEP 541 again, and noticed the section for [invalid projects](https://peps.python.org/pep-0541/#invalid-projects):

> project is name squatting (package has no functionality or is empty);

Given that there are [no releases for the existing yardstick project](https://pypi.org/project/yardstick/) it seems like this meets the definition of an invalid project -- @di @ewdurbin is this interpretation correct?

**Comment by Thespi-Brain** [comment]
Hi @wagoodman,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message. We will update you if we hear back from them.

**Comment by wagoodman** [comment]
Thanks, @Thespi-Brain !!

**Comment by wagoodman** [comment]
Any news yet @Thespi-Brain ?

**Comment by Thespi-Brain** [comment]
**yardstick** has been deemed invalid. Additionally, many attempts have been made to reach out to the owner, but no valid contact info was found. Owner has also not been active for many years. 

I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Added 'anchore' as 'Owner' on 'yardstick'
