### ISSUE TITLE
Project Limit Request: mypy - 20 GB

### ISSUE THREAD

**Issue by JukkaL** [pypi/support#3094]
### Project URL

https://pypi.org/project/mypy/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Mypy is a type checker for Python used by many open source projects. It's been in development since 2013. The total project size is expected to gradually increase over time as we make monthly releases and the codebase grows larger, but no big sudden increases are expected.

We might want to publish ARM Linux wheels at some point in the future, which would increase the project size somewhat.

### How large is each release?

About 200 MB total. ~20 binary wheels, around 10 MB each. The source distribution is 3 MB. 

We usually have wheels for all Python versions that haven't reached end-of-life (currently 3.8, 3.9, 3.10 and 3.11). We have wheels for Linux (musllinux_1_1_x86_64 and manylinux2014_x86_64), Windows (amd64 only) and macOS (arm64 and x64_64). 

We need binary wheels since we compile mypy to C extensions using mypyc. This improves performance significantly. We've done some work to reduce the size of the generated C code, but it's difficult to make things significantly smaller.

### How frequently do you make a release?

Roughly once to twice a month (including bugfix releases)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by timsoftgit** [comment]
the slackware package of mypy uses pypi for the source download because the github version is missing sub-projects source. unfortunately apparently due to space issues, the latest version is no longer available. It would be nice if this was resolved for the community.

**Comment by di** [comment]
I've increased the total project size limit for `mypy` to 20GB.
