### ISSUE TITLE
PEP 541 Request: Logbook (on test.pypi.org)

### ISSUE THREAD

**Issue by RazerM** [pypi/support#3096]
### Project to be claimed

`Logbook`: https://test.pypi.org/project/Logbook

### Your PyPI username

`RazerM`: https://test.pypi.org/user/RazerM

### Reasons for the request

I am an owner of Logbook on main PyPI: https://pypi.org/project/Logbook. The logbook package that was uploaded on test.pypi.org is not related to the one on pypi.org

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The project on test.pypi.org points to https://github.com/ibtehaz-shawon/LoggerProject which redirects to something else now.

The Logbook project as publish on pypi.org is at https://github.com/getlogbook/logbook

### Contact and additional research

I contacted the owner on 28 July 2023 without a response so far.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Added 'RazerM' as 'Owner' on 'Logbook' on test.pypi.org
