### ISSUE TITLE
PEP 541 Request: library

### ISSUE THREAD

**Issue by chapmanjacobd** [pypi/support#3100]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/library

### Your PyPI username

`USER_NAME`: https://pypi.org/user/xk3

### Reasons for the request

The `library` project seems to be abandoned. The version `0.0.0` in pypi (Jul 3, 2013) only contains a `NumbToString` class and not much else.

My project currently occupies the name `xklb` but it is not easy to pronounce. Switching to `library` would match the name of my project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

hmm I can't find the repo for the existing release but the source distribution is here: https://files.pythonhosted.org/packages/1b/7b/5707105d93658b4abf9d3b38fe23205f18b9474c67ab01fe059043619a6b/Library-0.0.0.tar.gz

Replacement: https://github.com/chapmanjacobd/library

### Contact and additional research

I tried reaching out to the owner via email on Sep 16, 2022. There was no reply:

```
MIME-Version: 1.0
Date: Fri, 16 Sep 2022 09:45:55 -0500
Message-ID: <CAAGO9LGaMGLOCZ3S5_dMwiormO=Do13RsR5mW9xu4-KmdNZw7w@mail.gmail.com>
Subject: pypi library
From: Jacob Chapman <chapmanjacobd@gmail.com>
To: alam.ybs@gmail.com
Content-Type: multipart/alternative; boundary="00000000000060517f05e8cc6b79"

--00000000000060517f05e8cc6b79
Content-Type: text/plain; charset="UTF-8"

hello namakukingkong,

it looks like your library package is inactive?
https://pypi.org/project/Library/

I would like to use that name for my package:
https://github.com/chapmanjacobd/library/

If you agree, the easiest way will be to add me ( https://pypi.org/user/xk3/
) as an owner of the library package in pypi

https://pypi.org/help/#request-ownership

Thanks for your consideration,
xk3

--00000000000060517f05e8cc6b79
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"auto">hello namakukingkong,<div dir=3D"auto"><br></div><div dir=
=3D"auto">it looks like your library package is inactive? <a href=3D"https:=
//pypi.org/project/Library/">https://pypi.org/project/Library/</a></div><di=
v dir=3D"auto"><br></div><div dir=3D"auto">I would like to use that name fo=
r my package: <a href=3D"https://github.com/chapmanjacobd/lb/">https://gith=
ub.com/chapmanjacobd/lb/</a></div><div dir=3D"auto"><br></div><div dir=3D"a=
uto">If you agree, the easiest way will be to add me ( <a href=3D"https://p=
ypi.org/user/xk3/">https://pypi.org/user/xk3/</a> ) as an owner of the libr=
ary package in pypi</div><div dir=3D"auto"><br></div><div dir=3D"auto"><a h=
ref=3D"https://pypi.org/help/#request-ownership">https://pypi.org/help/#req=
uest-ownership</a></div><div dir=3D"auto"><br></div><div dir=3D"auto">Thank=
s for=C2=A0your consideration,</div><div dir=3D"auto">xk3</div></div>

--00000000000060517f05e8cc6b79--
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by chapmanjacobd** [comment]
@ewdurbin ? it seems like you are the person I should talk to. :pray: thanks

**Comment by chapmanjacobd** [comment]
@di ?

**Comment by Thespi-Brain** [comment]
Hi @chapmanjacobd,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
Project **library** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Added 'xk3' as 'Owner' on 'Library'
