### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by baderdean** [pypi/support#3101]
### PyPI Username

bader

### Reason for request

Lost access to email address bader@tele2.fr and I'm not even sure this is the email linked to this account. Here attached a email that proof that I'm the same person.
[Python binding to libextractor using ctypes.eml.txt](https://github.com/pypi/support/files/12342247/Python.binding.to.libextractor.using.ctypes.eml.txt)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by Thespi-Brain** [comment]
Hi @baderdean,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
