### ISSUE TITLE
File Limit Request: modelpack - 500 MB

### ISSUE THREAD

**Issue by sebastient** [pypi/support#3104]
### Project URL

https://pypi.org/project/modelpack

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Framework for training vision-based ML models for detection, segmentation, attitude, and keypoints.

### Reasons for the request

The framework bundles pre-trained weights used for transfer learning.  We try to keep these focused but they're roughly 25MB for each of the core model configurations.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi, can you provide us with more details on what this project is? Do you have a source repository with a README or some other longer description of it?

**Comment by di** [comment]
Closing due to lack of response.

**Comment by sebastient** [comment]
Hi, sorry I missed the original message.  The project is closed-source, but the binary is published to PyPi and Docker.  Documentation is on our website.  

https://support.deepviewml.com/hc/en-us/categories/4417206905741-DeepView-ModelPack-AI-Middleware
