### ISSUE TITLE
PEP 541 Request: mtpy

### ISSUE THREAD

**Issue by kujaku11** [pypi/support#3107]
### Project to be claimed

mtpy`: https://pypi.org/project/mtpy

### Your PyPI username

`kujaku11`: https://pypi.org/user/kujaku11

### Reasons for the request

The original owner of the project Fei Zhang passed away and was the sole owner.  I'd like to take over as the owner and continue support of this project.  I am an administrator on the project I do not have PyPi ownership.  If there's any more information you need I'm happy to help.  

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The current URL is https://github.com/MTgeophysics/mtpy and that will continue to be the URL

### Contact and additional research

Unfortunately, the sole owner passed away and cannot be contacted.  Though I am an administrator on the project I do not have PyPi ownership. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @kujaku11,

Sorry to hear about the passing of the original owner of the project. It looks like however, that you were already made an Owner by PyPI admins. I am closing this issue, but feel free to open a new one if there are any more problems. Thanks.
