### ISSUE TITLE
Project Limit Request: h2o-pysparkling-2.3 - 15 GB

### ISSUE THREAD

**Issue by mn-mikke** [pypi/support#3109]
### Project URL

https://pypi.org/project/h2o-pysparkling-2.3

### Does this project already exist?

- [X] Yes

### New limit

15 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

h2o-pysparkling-2.3 is a project representing a pysparkling build for Apache Spark 2.3. Pysparkling integrates a distributed machine learning framework H2O-3 with Apache Spark (pyspark).

### How large is each release?

~220MB

### How frequently do you make a release?

One per month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
New limit: 15GB
