### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by NiekvanderLinden** [pypi/support#3110]
### PyPI Username

sendcloud

### Reason for request

Lost access to email address (tim@sendcloud.com). 

We created an alias but for some reason I do not receive the password recovery link on this alias. Other emails are received. Not sure how to continue here, technically speaking I do have access to the email but I'm not receiving the recovery link. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Looks like the resets were not successful as the address was placed on the Amazon SES global suppression list due to bouncing, so our email provider refuses to send to it.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
