### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by geethaab** [pypi/support#3113]
### PyPI Username

Twizzy

### Reason for request

My account is frozen after I uploaded my test package, It was my first time so I pasted setup.py in every folder idk if that's the reason but yes my account is old but my account got frozen and the package is unavailable now so I can't use my codes. I request the support team to unfreeze it asap.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Your account was flagged for uploading obfuscated code which appeared to be malware.

Example: https://inspector.pypi.io/project/pyward/3.0/packages/a1/6d/cf8cc7abc2f321e9a239208a1e5a99d775bbb0165cded3bd685ec2573212/pyward-3.0.tar.gz/pyward-3.0/pyward/__init__.py#line.1

PyPI does not allow such activity, and your account will remain frozen indefinitely.
