### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by nathanielford** [pypi/support#3115]
### PyPI Username

nathanielford

### Reason for request

I lost the device with the 2FA app on it. I have not accessed this account for some years, though I only have the one project I'm maintaining on it. I would like to deprecate that project (I am no longer maintaining it). If there is a process for re-acquiring access that would be great. I do have my normal access to GitHub, etc. so feel fairly confident I can authenticate who I am.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
