### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by KohnoseLami** [pypi/support#3117]
### PyPI Username

KohnoseLami

### Reason for request

I lost access to 2FA because my smartphone broke down.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by Thespi-Brain** [comment]
Hi @KohnoseLami,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let me know, and I will start an account recovery process for you to reset your account, thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
