### ISSUE TITLE
Project Limit Request: databend - 20 GB

### ISSUE THREAD

**Issue by sundy-li** [pypi/support#3118]
### Project URL

https://pypi.org/project/databend/

### Does this project already exist?

- [X] Yes

### New limit

20GB ~ 50GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Databend is a modern cloud data warehouse that empowers your object storage for real-time analytics.

### How large is each release?

~200MB 

### How frequently do you make a release?

We will update the release frequency to one or two releasers per month. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
Thanks for the decrease in frequency!

New limit: 20GB
