### ISSUE TITLE
PEP 541 Request: rq-dashboard

### ISSUE THREAD

**Issue by cjlapao** [pypi/support#3124]
### Project to be claimed

`rq-dashboard`: https://pypi.org/project/rq-dashboard/

### Your PyPI username

`cjlapao`: https://pypi.org/user/cjlapao

### Reasons for the request

While the project itself is not abandoned, the owners of the repo are no longer the maintainers. We own the GitHub repo, and we want to be able to push new versions of the package.

As you may see, we have a few newer versions
https://github.com/Parallels/rq-dashboard/releases
and also some open issues of people having a mismatch between what they can use in the PyPi and what we provide.

What we request is that the package in PyPi move to us so we can push the current version and also update our Ci/CD pipelines to further automate the changes.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/Parallels/rq-dashboard

### Contact and additional research

We contacted Vincent Driessen,

The owner of the project and he confirmed he no longer maintains it

![image](https://github.com/pypi/support/assets/17143029/a3188cb0-8953-4e81-9c54-a7e0e4fd4ad5)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @cjlapao,

I took a look into the project history and it looks like you are already listed as one of the Owners of this project. Are you still having any issues regarding project ownership or releasing new versions? Let me know, and we will go from there. If not, let me know either way and I will close this issue, thanks.

**Comment by cjlapao** [comment]
@Thespi-Brain Yes I am already the owner, as you can see this was requested more than an year ago
