### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by metaminux** [pypi/support#3130]
### PyPI Username

guillaume-masson

### Reason for request

Hello,

I'm the former CEO of META Information Technology (meta-it).
We published the package https://pypi.org/project/odooselenium/ from 2015 to 2017

Vauxoo would like to create a new package odoo-selenium, but has conflict, so they asked if we can transfer the old package (see https://github.com/pypi/support/issues/3128 and https://github.com/meta-it/odooselenium/issues/7)

I tried to reset my password, but don't receive the email.

Can you tell me how to regain access to my account ?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Emails to your address are soft-bouncing as there are no DNS records for the domain.

**Comment by ewdurbin** [comment]
Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by ewdurbin** [comment]
Confirmation complete. Email address has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
