### ISSUE TITLE
File Limit Request: malloy - 200 MB

### ISSUE THREAD

**Issue by gmaden** [pypi/support#3131]
### Project URL

https://pypi.org/project/malloy/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Malloy Project: https://malloydata.dev
Has been active for 1-2 years

We bundle binaries to support multiple platforms/architectures. 

We have attempted to reduce our size in a few ways, using compression, dependency pruning, and dropping targeted Mac arm64 executable since it is capable of using the x64 binary.

### Reasons for the request

We don't expect to reach the 200mb limit, but with the newest version bringing python closer to parity with the nodes version the package size is sitting at around 125mb. And this gives some buffer for adding an additional platform/architecture.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
New upload limit: 200MB
