### ISSUE TITLE
Project Limit Request: cmake - 50 GB

### ISSUE THREAD

**Issue by mayeut** [pypi/support#3135]
### Project URL

https://pypi.org/project/cmake

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

CMake is an open-source, cross-platform family of tools designed to build, test and package software

The CMake PyPI distribution has been active for almost 7 years.

### How large is each release?

~480 MB per release

source .tar.gz: 35.2 kB
3 windows wheels (x86_64, i686, arm64): ~100 MB
1 macOS wheel (universal2): ~48 MB
5 musllinux wheels (x86_64, i686, aarch64, ppc64le, s390x): ~140 MB
5 manylinux2014+ wheels (x86_64, i686, aarch64, ppc64le, s390x): ~133 MB
2 manylinux2010 wheels (x86_64, i686): ~51 MB

### How frequently do you make a release?

Roughly once a month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mayeut** [comment]
cc @jcfr, @henryiii

**Comment by jcfr** [comment]
Thanks @mayeut for putting this request  together :100:

We would be grateful if the PyPI admin would increase the limit :pray:

**Comment by KyleFromKitware** [comment]
CMake co-maintainer here. +1

Cc: @bradking @crascit @MarkaPola

**Comment by miketheman** [comment]
New total size limit: 50GB

**Comment by jcfr** [comment]
Thanks @miketheman :pray:
