### ISSUE TITLE
PEP 541 Request: snowflake

### ISSUE THREAD

**Issue by sfc-gh-bwarsaw** [pypi/support#3136]
### Project to be claimed

`snowflake`: https://pypi.org/project/snowflake

### Your PyPI username

`barrysf`: https://pypi.org/user/barrysf

### Reasons for the request

This is requesting a friendly transfer of the snowflake PyPI package name from Shaddi Hasan to Snowflake via Barry Warsaw's employee account.  Barry and Shaddi have been in communication about effecting this friendly transfer, and the process of migrating current consumers of `snowflake` is under way.  Once we have the planned transition completed, we request the transfer of ownership to take place.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: https://github.com/shaddi/snowflake

Replacement* project: https://github.com/snowflakedb/snowflake-connector-python

* note that this is the closest publicly released OSS repo we currently have.  We are working on a refactoring, at the end of which we will have a top level `snowflake` namespace package.

### Contact and additional research

Current owner: Shaddi Hasan <shaddi@vt.edu>

Shaddi and I are in email communication about the friendly transfer.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sfc-gh-bwarsaw** [comment]
Quick follow up that all conditions for the friendly transfer has been completed, and I believe that we are ready for the PyPI administrators to effect the transfer.  @shaddi to confirm.

**Comment by shaddi** [comment]
Yup, we’re good to go!

**Comment by ewdurbin** [comment]
@shaddi you can perform this transfer yourself by adding the Owner role to barrysf at https://pypi.org/manage/project/snowflake/settings/

**Comment by sfc-gh-bwarsaw** [comment]
The transfer has been completed.  Thank you all!
