### ISSUE TITLE
PEP 541 Request: easy_install — hijacked by russians — plz add to the blocklist

### ISSUE THREAD

**Issue by webknjaz** [pypi/support#3138]
### Project to be claimed

`easy_install`: https://pypi.org/project/easy_install

### Your PyPI username

`webknjaz`: https://pypi.org/user/webknjaz

### Reasons for the request

It seems as though this should be added to the list of forbidden project names. It was never shipped through PyPI and is now deprecated anyway. The corresponding legitimate repository is about to be archived: https://github.com/pypa/easy_install/issues/1.

cc @di @ewdurbin

### Maintenance or replacement?

None

### Source code repositories URLs

Should've been https://github.com/pypa/easy_install.

### Contact and additional research

The PyPI page has a description suggesting contacting the russian competitor of Google. I have downloaded the dists and verified that they only contain metadata, a harmless `setup.py` and don't bundle any executable code except for that one module.
The first release happened on Feb 8, 2023, the following release was on Feb 10, 2023. The only thing changed was a typo in the email address.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Given that it is explicitly published as a "placeholder package" it has been removed and prohibited from re-registration.

**Comment by webknjaz** [comment]
@ewdurbin thanks. I noticed that the account has over a thousand placeholders: https://pypi.org/user/yandex-bot/.

_“fun” note:_ some of their placeholders like zeliboba-deepspeed / zeliboba-deepspeed-2 have a derogatory reference typically used to insult the supporters of president Zelens'kyi.

I wonder if the ToS encourages such behaviors :thinking:

**Comment by ewdurbin** [comment]
> @ewdurbin thanks. I noticed that the account has over a thousand placeholders: https://pypi.org/user/yandex-bot/.

Yeah, there has been some push/pull on this over time. There's some balance between allowing such placeholders when they're relevant to a company name/brand versus having to respond to requests for prohibiting them via admin intervention.

> _“fun” note:_ some of their placeholders like zeliboba-deepspeed / zeliboba-deepspeed-2 have a derogatory reference typically used to insult the supporters of president Zelens'kyi.
> 
> I wonder if the ToS encourages such behaviors 🤔

@webknjaz if you note such issues please contact conduct@pypa.io per the PyPA/PyPI Code of Conduct information.
