### ISSUE TITLE
File Limit Request: srq-score-wheel - 300 MB

### ISSUE THREAD

**Issue by m-pushkar** [pypi/support#3139]
### Project URL

https://pypi.org/project/srq-score-wheel/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

Custom python function for organization

### Reasons for the request

Need to include large data files, thus large package

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
> https://pypi.org/project/srq-score-wheel/

This project does not have any releases at this time (I'm getting a 404 at this URL).

> Custom python function for organization
>
> Need to include large data files, thus large package

Could you provide more context for what this is for?
