### ISSUE TITLE
Project Limit Request: intel-extension-for-tensorflow-lib - 50 GB

### ISSUE THREAD

**Issue by Dboyqiao** [pypi/support#3141]
### Project URL

https://pypi.org/project/intel-extension-for-tensorflow-lib/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is an Intel owned project that we are planning to release in the next few weeks as part of our TensorFlow Optimizations and it'll be owned and maintained by this user: https://pypi.org/user/IntelAI/

### How large is each release?

~ 3.6 G

4 wheels x 94M,
4 wheels x 361M
4 wheels x 450M

### How frequently do you make a release?

Every 2-3 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
New total size limit: 50GB
