### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by itolosa** [pypi/support#3143]
### PyPI Username

itolosa

### Reason for request

Lost the access to my old email. It was from an old domain and it expired long time ago.

Package: https://pypi.org/project/orionx-api-client/
Repository: https://github.com/itolosa/orionx-api-client

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by itolosa** [comment]
Thanks! 🙏

**Comment by ewdurbin** [comment]
Confirmation complete. Email has updated, you should be able to regain access to your account after completing the password reset.
