### ISSUE TITLE
Project Limit Request: botocore - 45 GB

### ISSUE THREAD

**Issue by jonathan343** [pypi/support#3145]
### Project URL

https://pypi.org/project/botocore/

### Does this project already exist?

- [X] Yes

### New limit

45 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Botocore is a dependency of the AWS SDK for Python (boto3) and AWS CLI. This project was first released to PyPi on December 21, 2012. We are currently blocked from releasing due to project size.

### How large is each release?
**~22.5 MB total**

**Source Distribution**
botocore-1.31.38.tar.gz ~ 11.3 MB

**Built Distribution**
botocore-1.31.38-py3-none-any.whl ~ 11.2 MB

### How frequently do you make a release?

Usually every business day.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
Limit raised to 45GB.

**Comment by jonathan343** [comment]
Thank you!!
