### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by laurent-laporte-pro** [pypi/support#3147]
### PyPI Username

`laurent-laporte-pro`

### Reason for request

Dear PyPi Administrators,

I'm Laurent LAPORTE, and I've encountered an issue with my PyPi account. I've lost my security tokens and lack a valid TOTP application. I last accessed my PyPi account in late February, using a token.

I understand security is vital, and I apologize for any inconvenience. I kindly request your assistance in resolving this issue and providing guidance on recovering my account.

Thank you for your help.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `laurent-laporte-pro` has valid recovery codes generated as of 2023-02-10 19:10:52.977079.

Please use those recovery codes to regain access to your account.

**Comment by laurent-laporte-pro** [comment]
I am sorry, but I contact you because I also loose my recovery codes.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
