### ISSUE TITLE
File Limit Request: aiacc-nccl 2.17.1 - 200 MB

### ISSUE THREAD

**Issue by a550461053** [pypi/support#3151]
### Project URL

https://pypi.org/project/aiacc-nccl/

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

1. AIACC-NCCL is an AI-Accelerator communication framework for NVIDIA-NCCL. It implements optimized all-reduce, all-gather, reduce, broadcast, reduce-scatter, all-to-all,as well as any send/receive based communication pattern.It has been optimized to achieve high bandwidth on aliyun machines using PCIe, NVLink, NVswitch,as well as networking using InfiniBand Verbs, eRDMA or TCP/IP sockets.
2. AIACC-NCCL is the backend for AIACC/AIACC-Training package(well be upload).

### Reasons for the request

1. The size of this package has been reduced.
2. The size cannot be reduce for supporting different GPU arch.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! I've updated the per-file limit for `aiacc-nccl` to 200 MiB, on pypi.org.
