### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ManojSharma1997** [pypi/support#3152]
### PyPI Username

predator_97x3

### Reason for request

When I try to log in using  PyPI `username` and `password`, I receive an error message that states "Session Invalidated." I have verified that my username and password are correct, and I have also attempted to reset my password, It allows me to change the password but the issue persists.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Your account was frozen due to malware upload attempts and will not be restored.
