### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by HenraL** [pypi/support#3155]
### PyPI Username

Hanra

### Reason for request

Dear PyPi Administrators,

I'm Hanra, and I've encountered an issue with my PyPi account. I've lost my security codes and the device that contained my 2FA codes was stolen.

I understand security is vital, and I apologize for any inconvenience.
I kindly request your assistance in resolving this issue and providing guidance on recovering my account.

Thank you very much for your help.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `Hanra` has valid recovery codes generated as of 2022-08-15 19:21:22.562221.

Please use those recovery codes to regain access to your account.

**Comment by HenraL** [comment]
I informed that I lost the file during the dumpps my scool imposed. I do not have the file that stores them anymore.
Is there a way you can deactivate the 2FA or send them to me again?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by HenraL** [comment]
Thank you for the help you provided.
