### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tfagerlind** [pypi/support#3157]
### PyPI Username

`tfagerlind`

### Reason for request

I have no 2FA authentication app connected to pypi. I cannot explain why. I haven't logged in to pypi lately. I have a vague memory that I have enabled two factor authentication, and that I have used my Lastpass authenticator for that, but I think that it has lost the pypi account somehow and I'm not sure why. 

It worries me that I can't login since I am the maintainer of a pypi library called ["verso"](https://pypi.org/project/verso/), that needs an update ... I hope that you can help me.

Thanks in advance,
Tomas Fägerlind

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by tfagerlind** [comment]
Great! Thanks a lot!

**Comment by tfagerlind** [comment]
I have followed the instructions and is ready to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by tfagerlind** [comment]
Thank you so much!
