### ISSUE TITLE
PEP 541 Request: livecheck

### ISSUE THREAD

**Issue by Tatsh** [pypi/support#3160]
### Project to be claimed

`livecheck`: https://pypi.org/project/livecheck/

### Your PyPI username

`audvare`: https://pypi.org/user/audvare

### Reasons for the request

This project has not been updated since 2019. There is only one version and no updates since. Contacting the author email results in a bounce. The GitHub link on PyPI is dead. The code in the project is minimal and does not look like it gets used. I think the author forgot to delete the PyPI package.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: 404 at https://github.com/ask/livecheck
My project: https://github.com/Tatsh/livecheck

### Contact and additional research

Contacted by the author email which results in a bounced message.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @Tatsh,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by miketheman** [comment]
Added 'audvare' as 'Owner' on 'livecheck'
