### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rhdekker** [pypi/support#3162]
### PyPI Username

rhdekker

### Reason for request

Lost access to email address due to a reorganisation.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by ewdurbin** [comment]
Confirmation complete. Email has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
