### ISSUE TITLE
Project Limit Request: Robyn - 30 GB

### ISSUE THREAD

**Issue by sansyrox** [pypi/support#3163]
### Project URL

https://pypi.org/project/robyn/

### Does this project already exist?

- [X] Yes

### New limit

30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Robyn is a fast, async python web framework made using Rust.

### How large is each release?

~1600 MB

We have drop support for ibm and sun and the wheels for python3.7 will also not be generated. This will reduce the release size in future releases.

### How frequently do you make a release?

Twice, thrice every month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Limit increased to 30 GB on pypi.org (not test.pypi.org).

> ~1600 MB

Hmm... my math based on https://pypi.org/project/robyn/0.31.0/#files is that it's around 250-ish MB. That works out to 20,000 MB / 250 MB for a release / 3 per month = ~27 months.

With 20,000 MB / 1600 MB for a release / 3 per month gives you ~4 months before you need the limit increased again. If that's indeed the case, please do consider exploring [`abi3` wheels](https://cibuildwheel.readthedocs.io/en/stable/faq/#abi3) for this project as well, which would help increase the time before you need another bump. :)

**Comment by sansyrox** [comment]
Thank you @pradyunsg ! 😄
