### ISSUE TITLE
File Limit Request: MLB_SHOWDOWN_BOT - 300 MB

### ISSUE THREAD

**Issue by mgula57** [pypi/support#3166]
### Project URL

https://pypi.org/project/mlb-showdown-bot/

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Showdown Bot is a baseball card creation library that has been active since 2020. 

It depends on having high quality image assets available. I have upgraded the quality of many of the images causing an increase in package size. I have slightly reduced the size by removing redundant images.

### Reasons for the request

Many of the images in the package have been upgraded to higher quality, resulting in an increased package size. Currently the compressed tar file is around 124 MB. I am requesting 300 MB to account for potential image asset additions in the future. Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! I've updated the per-file size limit for `mlb-showdown-bot` to 300 MiB on pypi.org.

As a heads up: you're at 4.5 GiB out of 10 GiB on the overall project size (this can be seen on the manage page, on pypi.org).

**Comment by mgula57** [comment]
@pradyunsg Thank you! What are my options for managing the overall project size? Should I remove old releases or request larger overall project size?

**Comment by pradyunsg** [comment]
Both are approaches I've seen people take. I'd recommend deleting only pre-releases as such and requesting a limit increase a few weeks before you hit the limit.
