### ISSUE TITLE
PEP 541 Request: mops

### ISSUE THREAD

**Issue by VladimirPodolian** [pypi/support#3167]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/mops

### Your PyPI username

`USER_NAME`: https://pypi.org/user/pvladimir

### Reasons for the request

The requested project does not have any release version and page unavailable. I cannot publish new package with this name, so it seems like it taken with empty directory

### Maintenance or replacement?

None

### Source code repositories URLs

I don't think is there any repository for this package

### Contact and additional research

You can contact me at [vladimir.podolyan64@gmail.com](mailto:vladimir.podolyan64@gmail.com)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by VladimirPodolian** [comment]
@ewdurbin could you please help with it ?

**Comment by VladimirPodolian** [comment]
@ewdurbin still need your help. Thanks

**Comment by Thespi-Brain** [comment]
Hi @VladimirPodolian,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by VladimirPodolian** [comment]
@Thespi-Brain Hi! Thank you for the response. I appreciate it and still wish to use this project name, so I'll await the ticket resolution

**Comment by Thespi-Brain** [comment]
Project **mops** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Hello @VladimirPodolian 

Under `Source code repositories URLs` - we requested:
> Please provide code repositories for both the current project and the one you intend to publish in its place.

Can you share your repository that intends to replace this project?

**Comment by VladimirPodolian** [comment]
@miketheman Hi! Here is the GitHub repo, that I want to push in pypi under `mops` name: https://github.com/CustomEnv/dyatel

**Comment by miketheman** [comment]
Added 'PVladimir' as 'Owner' on 'mops'
