### ISSUE TITLE
File Limit Request: h2lib - 200 MB

### ISSUE THREAD

**Issue by madsmpedersen** [pypi/support#3169]
### Project URL

https://pypi.org/project/h2lib/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is a python interface to the aeroelastic wind turbine simulator HAWC2 from the Technical university of Denmark (https://www.hawc2.dk/)
The project contains the compiled HAWC2 as dll/so, as well as its dependencies (fortran, intel and intel mkl runtimes) which is important to make it work when run on different platforms in combination with other libraries compiled with different tool sets.
Furthermore, a few example and tests files are included - these are kept as small as possible.

### Reasons for the request

To deploy our tool in the most user fiendly way we need to be able to upload this package to PyPi including both the binary library as well as its dependencies.
The needed project size may increase in the future if we need to include larger example and test files or if the size of the dependencies increases

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! I've updated the per-file size limit for `h2lib` to 200 MiB on pypi.org.
