### ISSUE TITLE
PEP 541 Request: gcode-metadata

### ISSUE THREAD

**Issue by ondratu** [pypi/support#3173]
### Project to be claimed

`gcode-metadata`: https://pypi.org/project/gcode-metadata

### Your PyPI username

`mcbig`: https://pypi.org/user/mcbig

### Reasons for the request

I try to upload new gcode metadata library to reading (parsing) metadata from gcode. Bud pypi tell me about name problem:

```
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/                                                                                                     
The user 'mcbig' isn't allowed to upload to project 'gcode-metadata'. See https://pypi.org/help/#project-name for more information.
```

But no similar named package exist. Please can you help me, what is wrong?

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/prusa3d/gcode-metadata

### Contact and additional research

Ondřej Tůma (mcbig) - mcbig@zeropage.cz

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @ondratu,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
Project **gcode-metadata** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Added 'mcbig' as 'Owner' on 'gcode-metadata'
