### ISSUE TITLE
File Limit Request: PySpark - 350 MB

### ISSUE THREAD

**Issue by xuanyuanking** [pypi/support#3175]
### Project URL

https://pypi.org/project/pyspark/

### Does this project already exist?

- [X] Yes

### New Limit

350 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

PySpark is the Python API for Apache Spark, an open source, distributed computing framework and set of libraries for real-time, large-scale data processing. It has been active for ten years ([first commit](https://github.com/apache/spark/commit/886b39de557b4d5f54f5ca11559fca9799534280))

We include some examples with the size of 648K and data with the size of 640K.

### Reasons for the request

As the project progresses, new dependency jars are continuously added to it. It can be observed that in Apache Spark version 3.4.0, the size of this package has reached 296MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by xuanyuanking** [comment]
@di,
Apologies for reaching out to you directly. I noticed that you addressed a similar request related to limits a while ago ([link](https://github.com/pypi/support/issues/3104#issuecomment-1680745440)). Currently, this issue is blocking the release of Apache Spark 3.5.0. I was wondering if we could get some assistance from your side regarding this request. Thank you in advance!

**Comment by gatorsmile** [comment]
CC @cmaureir too

**Comment by pradyunsg** [comment]
Hi there!

Sorry about the slowness here -- this issue tracker is triaged by volunteers and things get processed as and when we have time to triage things. I've bumped the per-file limit to 400 MiB on pypi.org as well as test.pypi.org.

As a heads up: you're at 8.1 GiB / 10 GiB on pypi.org for the entire project (you can see this on the manage page for PyPI). [This](https://github.com/pypi/support/issues/new?assignees=&labels=limit+request&projects=&template=limit-request-project.yml&title=Project+Limit+Request%3A+PROJECT_NAME+-+00+GB) is the template for requesting a project-wide limit increase. :)

PS: For the future, typically @-mentions to volunteers who donate their free time to process these requests aren't appreciated.
