### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bsquizz** [pypi/support#3181]
### PyPI Username

`bsquizzato`

### Reason for request

2FA authentication device broke, no recovery codes available

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by bsquizz** [comment]
Thanks, I did not receive a reset email at this address within the last 2
hours. So I navigated to the login page and used "Forgot Password" to
attempt a reset. I just reset the password on my account but was still
prompted to enter a 2FA token. Are you certain 2FA was disabled on this
account? Thanks!


- Brandon

**Comment by ewdurbin** [comment]
I am so sorry! this has been completed. bsquizzato

**Comment by bsquizz** [comment]
Thanks! Got it now :)
