### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [pypi/support#3182]
### PyPI Username

`OS-C`

### Reason for request

I lost access to 2FA authentication app when I upgraded my phone over a year ago.  You can see my activities on GitHub as an active contributor to the ITR project, which we publish on PyPi.  I'm also a contributor to Pandas, Pint, and Pint-Pandas.

I will do better keeping my 2FA account information current.  I have no theory for storing recovery codes.

Thank you for your help!

work email: mtiemann@os-climate.org
personal email: mdtiemann@gmail.com
Wikipedia page: https://en.wikipedia.org/wiki/Michael_Tiemann

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `OS-C` has valid recovery codes generated as of 2022-04-14 13:38:18.098344.

Please use those recovery codes to regain access to your account.

**Comment by MichaelTiemannOSC** [comment]
Thanks for your speedy response.

I don't see any easy path to finding those codes.  Is there some other way to re-authenticate, or should we attempt to create a new account under a new username?  I do have valid GitHub credentials for both the OS-C and OS-Climate GitHub accounts, which are the projects developing the libraries we want to publish on PyPi.  We went a year without any release engineering support (hence the lost keys) but now we have releng support from the Linux Foundation.

**Comment by MichaelTiemannOSC** [comment]
I am sending an email to the person who helped us in the past.  It's evening in Europe right now, but we'll see if I get a response.

**Comment by MichaelTiemannOSC** [comment]
Good news and bad news...The bad news is that I cannot locate the recovery codes.  The good news is that we were able to invite the LinuxFoundation release engineering team to the ITR project independently of the OS-C PyPi user.

It would be nice to recover the OS-C PyPi user account.  If there's a way to authenticate that I'll turn it over to somebody better than me at maintaining passwords.  If not, it will remain a zombie account.  Thanks for any help you can provide.

**Comment by MichaelTiemannOSC** [comment]
Another ping.  Our friends at the Linux Foundation (https://pypi.org/user/lf-releng-pypi/) have the necessary credentials to continue updating OS-Climate repos, but it would be great for OS-Climate to have control over its own destiny as well.  Is there a way we can re-establish our credentials having lost the handle on the recovery codes from over a year ago?

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by MichaelTiemannOSC** [comment]
Thank you!!
