### ISSUE TITLE
File Limit Request: ro-legal-fl - 160 MB

### ISSUE THREAD

**Issue by senisioi** [pypi/support#3185]
### Project URL

https://pypi.org/project/ro-legal-fl/

### Does this project already exist?

- [X] Yes

### New Limit

160MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is a language module for Romanian that is specifically trained on legal documents and designed to be used with spacy. 
The trained models are SOTA, exceeding spacy official package benchmarks and being capable of identifying legal named entities.

### Reasons for the request

The module currently is not functional because I uploaded a broken version to have something there.
If you actually wish to test it, you may use the build artifacts: https://github.com/senisioi/rolegal/actions/runs/6206054184
The package is broken because it is missing the vocabulary trained on Romanian legal documents. This is something spacy requires to load the semantic representations of words. It is the main part that makes the project useful for Romanian legal language.
Having this package publicly will help people who wish to do NLP for Romanian and for legal document processing.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! I've updated the per-file size limit for `ro-legal-fl` to 200 MiB on pypi.org.
