### ISSUE TITLE
File Limit Request: CDPKit - 200 MB

### ISSUE THREAD

**Issue by seidelt** [pypi/support#3186]
### Project URL

https://pypi.org/project/CDPKit

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

CDPKit is an open-source cheminformatics toolkit implemented in C++ (see https://www.cdpkit.org for more information).  The toolkit serves as a basis for the development of novel cheminformatics methods and algorithms at the Department of Pharmaceutical Sciences/University of Vienna. Up to to now the toolkit was only used internally and we now want to make it accessible for a larger audience.

CDPKit has several external dependencies (boost libraries, cairo rendering library and their dependencies) which are included in the wheel files (as it should be). Unfortunately, the sizes of the built wheel files cannot be reduced without sacrificing valuable functionality that will be of interest for many users and/or decreasing usability.

### Reasons for the request

Some of the methods implemented in our toolkit rely on large databases containing chemical structure data which consume a considerable amount of space (e.g. the fragment library used for conformer generation, see: https://pubs.acs.org/doi/10.1021/acs.jcim.3c00563). For best performance and user experience (no separate installation of data files required) the databases are directly included in compiled binaries. Unfortunately, the 100 MB limit is exceeded by around 50 MB. 200 MB is more than currently needed but will already accommodate future developments that will increase file sizes further.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! I've updated the per-file size limit for `cdpkit` to 200 MiB on pypi.org.
