### ISSUE TITLE
Project Limit Request: torchserve-nightly - 20 GB

### ISSUE THREAD

**Issue by agunapal** [pypi/support#3192]
### Project URL

https://pypi.org/project/torchserve-nightly/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Yes, we push nightlies everyday.
I can't find a good way to delete the older files. I have been doing it manually.
If there is a way to delete this in bulk, that would solve the problem

### How large is each release?

24MB

### How frequently do you make a release?

Every day

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by agunapal** [comment]
Hi @cmaureir @pradyunsg Just checking if you need any more information to resolve this.

**Comment by pradyunsg** [comment]
Hi there!

> If there is a way to delete this in bulk, that would solve the problem

See https://pypi.org/project/pypi-cleanup/

---

I'm following https://github.com/pypi/support?tab=readme-ov-file#guidelines-for-upload-limit-requests and nightly releases are explicitly called out as a reason that limit requests are generally denied for:

> Upload limits are generally denied for the following reasons:
>
>    project makes nightly releases and/or is published frequently

Given that as well as your statement that a utility to delete releases in bulk would resolve the issue, I'm going to go ahead and close this out without any action.
