### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by digitalsleuth** [pypi/support#3193]
### PyPI Username

digitalsleuth

### This is for test.pypi.org only

My 2FA works fine on pypi.org, but does not work for test.pypi.org. I need to set up an API token for a project on testpypi but the project does not exist yet. The token I have from pypi.org in my normal account doesn't work for test.pypi.org.

Not sure if my 2FA is supposed to work on test.pypi.org or not, but either way, I can't seem to get an API key.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA has been reset on test.pypi.org for user `digitalsleuth`.
