### ISSUE TITLE
PEP 541 Request: pykalman

### ISSUE THREAD

**Issue by mbalatsko** [pypi/support#3196]
### Project to be claimed

`pykalman`: https://pypi.org/project/pykalman

### Your PyPI username

`mbalatsko`: https://pypi.org/user/mbalatsko

### Reasons for the request

The last release was in 2013, and yet the package has some bugs to fix. The author is not responsive on issues and PR in the original repo: https://github.com/pykalman/pykalman

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Original: https://github.com/pykalman/pykalman
My fork: https://github.com/pybardo/pykalman

I have already published a fork under a different name, but in https://github.com/sktime/sktime/pull/5277 it was mentioned that PEP 541 exists, and I believe it is a better way to go.

### Contact and additional research

Using issues and PRs and via email duckworthd@gmail.com, pykalman@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by fkiraly** [comment]
Just in case, it may make sense to ping @duckworthd, @gliptak, @nils-werner, @pierre-haessig, @jonathanng (all the contributors based on `pykalman` GitHub commit history)

**Comment by pierre-haessig** [comment]
Thanks for reaching me. In fact, I only used pykalman once for a short experiment back in 2015. Indeed Github remembers (better than I) that I made a contribution, but it was minor (fixing a docstring).

I didn't know of [PEP 541](https://peps.python.org/pep-0541/) before now, but it's good that this procedure exists.

Among the criteria for having an [Abandoned projects](https://peps.python.org/pep-0541/#abandoned-projects), it seems that the last two criteria are met (no releases, no repo activity).  Second, it appears to me that @mbalatsko has demonstrated the continued maintenance criteria of [Continued maintenance of an abandoned project](https://peps.python.org/pep-0541/#continued-maintenance-of-an-abandoned-project) with its forks https://github.com/pybardo/pykalman.

So, the only item which is not clearly validated to me is *"owner not reachable"* one. I see in the top message that emails were sent to:
-  pykalman@gmail.com (email from PyPI) and
- duckworthd@gmail.com (email given on https://www.stronglyconvex.com/about.html which is itself declared on https://github.com/duckworthd, so it's not an homonym),

but how long ago? Also, there is a @duckworthd [LinkedIn account](https://de.linkedin.com/in/dduckworth)  which may be worth trying to reach.

Final thought: if the PyPI ownership gets transfered, there would be still the issue of the documentation at https://pykalman.github.io/.

**Comment by fkiraly** [comment]
> Final thought: if the PyPI ownership gets transfered, there would be still the issue of the documentation at https://pykalman.github.io/.

Perhaps @duckworthd might be kind enough to transfer both pypi project and GitHub repo himself if he agrees that the original project is no longer maintained. That would solve the problem with the documentation, as well as the problem with the existing issues and bug reports potentially existing in two places.

**Comment by duckworthd** [comment]
Hi all,

Daniel here. Indeed, I lack the cycles to actively maintain this project,
and I'd be happy to pass the keys on to someone more active than I.

Daniel

Franz Király ***@***.***> schrieb am Sa., 23. Sept. 2023,
10:25:

**Comment by mbalatsko** [comment]
@duckworthd fantastic! I’d be happy to continue this package maintainance and development, as I have already started in the fork! And if you are ok with passing the keys to me, I believe that you don’t have to transfer GitHub repository, just making me admin would be enough. But on PyPI I’m not sure about shared ownership, I believe there transfer should be done. Both on GitHub and PyPI I have the same username: mbalatsko

**Comment by mbalatsko** [comment]
@duckworthd Daniel, do you think you will have time to get to it sometime?

**Comment by pykalman** [comment]
Hi @mbalatsko,

I have invited you to be a maintainer of this repo, the accompanying documentation repo, and the PyPI project. You are now a maintainer!

Daniel

**Comment by fkiraly** [comment]
@duckworthd, @pykalman, may I kindly request transfer to *me*?

`pykalman` is not a central dependency of `sktime`, but the hassle with multiple forks and releases is more work than me maintaining it and properly replying to issues and pull requests.

Attempts to contact current owners - now including @mbalatsko, who is unresponsive since almost half a year - are documented here: https://github.com/sktime/sktime/pull/6114

**Comment by fkiraly** [comment]
alright - well, closing this issue is *a* reaction.

In that case, kindly let me know if you need help maintaining `pykalman`.

**Comment by mbalatsko** [comment]
@fkiraly Unfortunately all transfer processes went on for too long and I never got permission to publish the package to Pypi. I have only a contributor role there. I wanted to add you as a contributor at least on Github, but it seems that I do not have permissions for it either, so you would need to wait for @duckworthd reaction. However, I'm sorry to be responsive for a long time and willing to help get some changes through faster. If you need to have some fix urgently as part of pykalman, I can add you as admin to pykalman-bardo, where you could merge it and get through to release.

**Comment by fkiraly** [comment]
> Unfortunately all transfer processes went on for too long and I never got permission to publish the package to Pypi. I have only a contributor role there.

Hm, but isn't that sufficient to publish a package? This is not a full transfer, it does not give access to the most destructive actions, but a maintainer position gives you the right to publish new versions: 
![image](https://github.com/pypi/support/assets/7985502/2a132530-1516-4e9e-9b35-9c132d7bb8f9)

> I have invited you to be a maintainer of this repo, the accompanying documentation repo, and the PyPI project. You are now a maintainer!

As a maintainer, you can review/merge PR and reply to issues. Perhaps @duckworthd wanted to see whether you are actually going to do that.

The first - imo pressing - thing to do would be to respond of authors of PRs, merge the python 3.11/3.12 fix (from either of multiple sources), and get started with some reviews?

**Comment by fkiraly** [comment]
> and I never got permission to publish the package to Pypi

I think this is an incorrect statement. I can see you being a maintainer on pypi, this allows you to publish new versions:
![image](https://github.com/pypi/support/assets/7985502/1cfcff1a-5066-41b1-89cf-f2d987be2ce1)

**Comment by mbalatsko** [comment]
Interesting that PyPi UI does not reflect at all that I can upload something. But you are probably right. Then I can reflect changes from bardo repository to main one. And then I'll be willing to give up all permissions as I'm no longer interested in maintenance. @fkiraly are there any other issues except Py 3.11/12 compatibility and `masked array are not supported in linalg.solve` you want to see resolved? I could include everything to one release

**Comment by fkiraly** [comment]
> @fkiraly are there any other issues except Py 3.11/12 compatibility and `masked array are not supported in `linalg.solve` you want to see resolved?

Well, for `sktime` these would be the ones - though you may like to have a look at the PR and check what the various other contributors are trying to merge?

**Comment by mbalatsko** [comment]
I'll find time for that by the end of the week and let you know

**Comment by fkiraly** [comment]
> And then I'll be willing to give up all permissions as I'm no longer interested in maintenance. 

In that case, I'd request a transfer to me, @duckworthd, @pykalman.

**Comment by fkiraly** [comment]
any update on this, @mbalatsko, @duckworthd, @pykalman?

**Comment by fkiraly** [comment]
To summarize state of discussion so far, @duckworthd, @gliptak, @nils-werner, @pierre-haessig, @jonathanng:

* @duckworthd (alias @pykalman) has said on Sep 23, 2023, that he'd be happy for keys to be passed on.
* @mbalatsko says he no longer has bandwith to maintain - he has also made no change to `pykalman` proper, or the corresponding `pypi` project.

I think the PEP 541 on "abandoned" is satisfied, since there hasn't been any communication by the still-current owners, @duckworthd, since October 2023, which is far beyond the waiting time period required in PEP 541.

Based on the above, I'd request a transfer to me.

As stated, I am happy to take on maintenance, and will ensure continued existence under permissive license, and backlog getting addressed.

**Comment by fkiraly** [comment]
Opened a new PEP 541 request: https://github.com/pypi/support/issues/4142

**Comment by Thespi-Brain** [comment]
Hi @fkiraly,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by duckworthd** [comment]
Hi all. I have made @mbalatsko and @fkiraly co-owners on PyPI. Does that suffice?

**Comment by fkiraly** [comment]
Thank you, @duckworthd, for replying after half a year.

I note you have added me a maintainer and not as admin, so this is not a proper transfer. I also have no maintainer credentials on the GitHub, which makes this insufficient for a proper handover.

I would be open to discuss the future of `pykalman` with you, but your behaviour raises red flags.

1. I think you have intentionally ignored me, and I see similar risks for any conversation between us or between you and the wider community. For instance, you replied within a day to @Thespi-Brain, so you *are* reading your emails, you just chose to intentionally ignore me specifically.

2. I interpret your reaction as follows: you want to keep `pykalman` in a dead state, but also prevent anyone else to take over maintenance. 
 
While `pypi` did not follow up, the most effective way to ensure this was ghosting, that is, intentionally ignoring me.

Now that @Thespi-Brain has started to follow up, the most effective way to ensure that `pykalman` stays dead is taking partial steps that are not sufficient, but look good on GitHub, to evoke frustration with potential maintainers, while trying to prevent a forced (but proper) handover carried out by `pypi`.

Whay do you say about this, @duckworthd? Do you commit to engage in a public conversation with the aim to hand over maintenance of the package? Given that you have replied to @Thespi-Brain, I will expect your replies within a day, as well, or will consider this conversation as intentionally stalled by you.

**Comment by fkiraly** [comment]
PS: a fully maintained fork of `pykalman` now exists within `sktime` and is distributed with `sktime`, here: https://github.com/sktime/sktime/tree/main/sktime/libs - this proves that we are willing and able to maintain `pykalman`, and actually doing it already since a while, in a sense.

There are hence no good technical reasons to keep `pykalman` dead, only commercial ones.

**Comment by duckworthd** [comment]
@fkiraly I will disregard your ill-mannered accusations and encourage you to consider the possibility that I was unaware of this discussion till I received @Thespi-Brain's email earlier today.

I have changed your and @mbalatsko's role to "Owner" on PyPI. I no longer have access to the https://github.com/pykalman/pykalman and direct you to @mbalatsko for matters concerning it.

**Comment by mbalatsko** [comment]
I'm not the owner of Github repository either, I do not have `Settings` tab in top menu. Also, feel free to opt me out of all activities in regard of this repository,
<img width="950" alt="image" src="https://github.com/user-attachments/assets/b06967cc-c97d-4944-9634-d743c18c3dc1">

**Comment by duckworthd** [comment]
I stand corrected. The recovery email for the repository was an old one I had forgotten about.

I have renamed Github user pykalman to @pykalman-dev, created a Github organization named pykalman, and transferred ownership of the repository to this new organization. I have further added @mbalatsko and @fkiraly to this repository and elevated their role in the organization to Admin. I trust this should unblock all further issues with ownership of the pykalman library.

**Comment by fkiraly** [comment]
> @fkiraly I will disregard your ill-mannered accusations and encourage you to consider the possibility that I was unaware of this discussion till I received @Thespi-Brain's email earlier today.

That possibility can safely be ruled out by your direct engagement with this conversation on September 23, 2023, see here: https://github.com/pypi/support/issues/3196#issuecomment-1732281727

> I no longer have access to the https://github.com/pykalman/pykalman 

Who is the owner of the GitHub then, according to the latest point in time where you knew one of the owners, @duckworthd?

**Comment by fkiraly** [comment]
> I have further added @mbalatsko and @fkiraly to this repository and elevated their role in the organization to Admin. I trust this should unblock all further issues with ownership of the pykalman library.

Thank you very much, @duckworthd, for your willingness to collaborate!

**Comment by fkiraly** [comment]
> I have further added @mbalatsko and @fkiraly to this repository and elevated their role in the organization to Admin.

I have just checked, so far you have added me to the organization. However, my role is not Admin.
We are both referring to this repo, correct?
https://github.com/pykalman/pykalman

**Comment by pykalman-dev** [comment]
I've set "Base permissions" for organization members to "Admin". Does that allow you to elevate your own permissions on the repository in question? You'll have to forgive my lack of familiarity with Github.

**Comment by fkiraly** [comment]
> I've set "Base permissions" for organization members to "Admin". Does that allow you to elevate your own permissions on the repository in question? You'll have to forgive my lack of familiarity with Github.

No, I believe this applies only for new repositories an organization member creates.

To give elevated access to an existing repository, you need to set these manually yourself.

1.
![image](https://github.com/user-attachments/assets/5a7737c7-d924-4bd4-9cc9-24392f4e0981)

2.
![image](https://github.com/user-attachments/assets/7419d726-ba37-4539-be99-1415c60c56a1)

**Comment by pykalman-dev** [comment]
I see it now. I have changed your role in the repository to "Owner".

![image](https://github.com/user-attachments/assets/7f13b25a-0322-4662-9380-cff37c1a5101)

I have further changed your role in the organization as "Owner".

![image](https://github.com/user-attachments/assets/17b2382b-8281-4595-a50b-9566ad81327a)

**Comment by fkiraly** [comment]
Thank you very much.

Given that you are no longer involved in maintenance, would you be ok with me downgrading everyone else to maintainer?

**Comment by pykalman-dev** [comment]
Fine by me.

**Comment by fkiraly** [comment]
Thanks, also and especially on behalf of the communtiy of users!
And, apologies for my harsh words. I should not have assumed.

I wish you all the best!

**Comment by fkiraly** [comment]
> I ask that you find at least one other individual to be co-owner for the organization & repository to prevent issues like this one from occurring again.

Of course. The plan would be to move this under the umbrella of packages maintained by `sktime`, given that a vendor fork is already maintained there, and to replace the vendor fork dependency by the actual dependency.

**Comment by fkiraly** [comment]
I believe we can close this issue then.

**Comment by duckworthd** [comment]
Excellent. It sounds like the library is in good hands. I thank you for your continued contributions to the open source scientific community. 

This issue is resolved on my end.

**Comment by mbalatsko** [comment]
@fkiraly I could close the issue, right?

**Comment by fkiraly** [comment]
@mbalatsko, yes - let us know if you want to be involved in maintenance, on `pykalman` or `sktime`. Otherwise this should be complete from the perspective of PEP 541.
