### ISSUE TITLE
Availability of from Ohio

### ISSUE THREAD

**Issue by chriseldredge** [pypi/support#3199]
Starting around 2023-09-20T18:40 UTC, we are encountering an unusually high number of connection timeouts when retrieving package assets from files.pythonhosted.org which appear to be isolated to Ohio.

Example error message in our logs:

    Connect to files.pythonhosted.org:443 [files.pythonhosted.org/151.101.145.55] failed: connect timed out

We are not seeing any connection errors in other US regions or around the world.

**Comment by ewdurbin** [comment]
I'm getting errors on ipv6 from us-east-2 via Fastly's CMH pop.

**Comment by ewdurbin** [comment]
```ewdurbin@<pypi bastion host>:~$ curl -v https://files.pythonhosted.org/
*   Trying 151.101.145.55:443...
*   Trying 2a04:4e42:22::311:443...
* Immediate connect fail for 2a04:4e42:22::311: Network is unreachable```

**Comment by ewdurbin** [comment]
@chriseldredge can you confirm if your "from Ohio" is indicative of AWS us-east-2?

**Comment by ewdurbin** [comment]
forcing ipv4 worked for a moment but is now bogus as well :(

**Comment by ewdurbin** [comment]
We'll file an issue with our CDN and would ask that you do the same with your network provider, @chriseldredge

**Comment by chriseldredge** [comment]
> @chriseldredge can you confirm if your "from Ohio" is indicative of AWS us-east-2?

Yes, us-east-2.

> any chance you can inspect the x-served-by header to surface what Fastly POP you're getting?

No headers available since the http request cannot proceed.

**Comment by shughes-uk** [comment]
We're also seeing a big increase in errors from us-east-2
```
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/d4/73/ccf02298d1982cd27c30b3ada3[50](https://github.com/coiled/platform/actions/runs/6253225312/job/16979254127#step:12:51)d9952800a38b45bb0cbdb7c7b0110edc/setuptools_scm-8.0.1-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffb72679d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

I havent see it affect anything

I haven't seen it affect anything but `files.pythonhosted.org` yet. I'll see if i can get that header as we are seeing some requests succeed.

**Comment by ewdurbin** [comment]
Thanks! Please file an issue with your AWS account indicating that access to services hosted on Fastly's `m.sni.global.fastly.net` endpoint are intermittent.

It is likely an AWS or Fastly routing issue... so we should pressure from both sides :)

**Comment by ewdurbin** [comment]
Ironically, PyPI itself is impacted as it is hosted in us-east-2 and we can't deploy anything that needs a new dependency, we're relying on our layer cache 😂.

**Comment by shughes-uk** [comment]
```
* Connected to files.pythonhosted.org (151.101.145.55) port 80 (#0)
  > GET / HTTP/1.1
  > Host: files.pythonhosted.org
  > User-Agent: curl/7.74.0
  > Accept: */*
  > 
* Mark bundle as not supporting multiuse
  < HTTP/1.1 403 SSL is required
  < Connection: close
  < Content-Length: 16
  < Server: Varnish
  < Retry-After: 0
  < Content-Type: text/plain; charset=UTF-8
  < Accept-Ranges: bytes
  < Date: Wed, 20 Sep 2023 20:40:21 GMT
  < X-Served-By: cache-cmh1290044-CMH
  < X-Cache: MISS
  < X-Cache-Hits: 0
  < X-Timer: S1695242421.309656,VS0,VE0
  < X-Frame-Options: deny
  < X-XSS-Protection: 1; mode=block
  < X-Content-Type-Options: nosniff
  < X-Permitted-Cross-Domain-Policies: none
  < X-Robots-Header: noindex
  < ```

This helpful? It took me two tries. Maybe just anecdata but the failure was an ipv6 address 
```
  * Immediate connect fail for 2a04:4e42:22::311: Network is unreachable
  *
```

**Comment by chriseldredge** [comment]
Fastly has confirmed an incident in us-east-2: https://www.fastlystatus.com/incident/376079

**Comment by ewdurbin** [comment]
Those are definitely the IPs for the service in question (m.sni.global.fastly.net). Smells like multicast routing goofiness.

We got an ack back from fastly support but no additional info.

**Comment by miketheman** [comment]
Fastly updated that they have routed around an impacted region. @chriseldredge can you confirm if you're still seeing errors?

**Comment by chriseldredge** [comment]
I've seen recovery. The last error I saw was at 2023-09-20T20:49:55Z.

**Comment by ewdurbin** [comment]
confirmed on our side as well.
