### ISSUE TITLE
PEP 541 Request: redox

### ISSUE THREAD

**Issue by mmabey** [pypi/support#3205]
### Project to be claimed

`redox`: https://pypi.org/project/redox/

### Your PyPI username

`mmabey`: https://pypi.org/user/mmabey

### Reasons for the request

I believe the `redox` project meets the criteria for an invalid project on the basis of name squatting. Only one release has been published and it only contains a single, empty `__init__.py` file.

I also believe the project meets the criteria for being abandoned on the basis of the PyPI listing not containing a homepage for the project, the absence of releases in the past 12+ months, and my inability to reach the listed maintainer (details below).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current project does not have a listed code repository.

The repository for the project I intend to publish is available at https://github.com/mmabey/pyredox

### Contact and additional research

I contacted the listed project maintainer on August 29, 2023 and have not heard back from them:

![image](https://github.com/pypi/support/assets/1606251/ee05bf86-12f2-49db-9505-e4b60ac26969)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mmabey** [comment]
@stereobutter, are you the owner of this PyPI listing? Is there any chance you would be willing to transfer ownership to me?

**Comment by Thespi-Brain** [comment]
Hi @mmabey,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
**redox** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Added 'mmabey' as 'Owner' on 'redox'
