### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by zemarchezi** [pypi/support#3206]
### PyPI Username

zemarchezi

### Reason for request

I lost the Two-factor authentication of my pypi Test account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA reset on test.pypi.org and a password issue reset.
