### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by huzaifa-57** [pypi/support#3212]
### PyPI Username

huzaifat65

### Reason for request

Lost 2FA authentication app or security token. I have lost my phone last week and when I bought one I can't see any code on Authenticator app. I also lost my recovery codes. Kindly recover my account.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `huzaifat65` has valid recovery codes generated as of 2023-09-07 13:09:10.245382.

Please use those recovery codes to regain access to your account.

**Comment by huzaifa-57** [comment]
I have lost them too. Please help me in that

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by huzaifa-57** [comment]
I hope you understand. If you need any type of verification. I can provide you with that
