### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by paddywwoof** [pypi/support#3213]
### PyPI Username

paddywwoof

### Reason for request

I'm probably being stupid but the instructions say I need to log in in order to get a QR code or number that I need in order to log in.

Can you point me in the direction of some useful help. I still obviously have the email address and know the password but I probably have a different phone from the one I might have had last time I uploaded the pi3d module to pypi.

I *really* *really* don't want to use the authenticator system. Is it possible to get a six digit number texted to my phone in the same way I do two factor with all my financial websites?

Paddy

PS I would like to get v2.50 of pi3d updated on pypi soon as I've moved the source on github already

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

2FA is only supported via TOTP application or Webauthn. SMS is not and will not be supported.

**Comment by paddywwoof** [comment]
@ewdurbin is this progressing as expected? I'm away at the moment so can't update PYPI but there are increasing reports from modules that have pi3d as a dependency i.e. picframe so I want to be able to act as soon as I get home.

All the best

Paddy

**Comment by paddywwoof** [comment]
I am assuming this thread is now dead and have opened a new request https://github.com/pypi/support/issues/3315

**Comment by paddywwoof** [comment]
Looking at the ousting issues this might still be alive so I will reopen!

**Comment by paddywwoof** [comment]
Hi, any chance of moving this along at all. https://github.com/tipam/pi3d is now on v2.51 and pypi is still on v2.49 and those upgrades are to cope with OS changes.

**Comment by paddywwoof** [comment]
I have eventually managed to sort this out. Finding then getting into my old phone. I now have recovery codes saved on this laptop and various other places. Is this really more secure?!
