### ISSUE TITLE
Project Limit Request: openvino - 30 GB

### ISSUE THREAD

**Issue by artanokhov** [pypi/support#3216]
### Project URL

https://pypi.org/project/openvino/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

OpenVINO™ is an open-source toolkit for optimizing and deploying AI inference. 
More info available by link https://github.com/openvinotoolkit/openvino.

### How large is each release?

~630 MB latest release
https://pypi.org/project/openvino/2023.1.0/#files
5 macos x86_64 wheels ~140 MB
5 macos arm64 wheels ~100 MB
4 manylinux arm64 wheels ~80 MB
5 manylinux x86_64 wheels ~170 MB
5 windows wheels ~ 140 MB

### How frequently do you make a release?

We have LTS releases that must be keeped 4 years(with patch-versions of it), our release schedule is going to be increased to 1 release per month(12 releases/year).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @artanokhov :wave:
You haven't reach the 10G limit for your project, and I consider a jump to 50G too large.
Would it be OK for you to increase to 20-30G for example?

Additionally, it might be worth for your project to explore the Limited API https://docs.python.org/3/c-api/stable.html so you can avoid having too many wheels per OS and python version, reducing your  release size a lot.

**Comment by artanokhov** [comment]
Hello, @cmaureir 
Thank you for the response - it's okay to go with 30G for now.


We will investigate possibility of usage of the Limited API in our builds, but we use pybind now that doesn't support Limited API

**Comment by pradyunsg** [comment]
I've bumped the limit to 30 GB, as requested in the most recent comment. Appreciate your patience here! :)
