### ISSUE TITLE
Project Limit Request: openvino-nightly - 25 GB

### ISSUE THREAD

**Issue by artanokhov** [pypi/support#3224]
### Project URL

https://pypi.org/project/openvino-nightly

### Does this project already exist?

- [X] Yes

### New limit

25

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

OpenVINO™ is an open-source toolkit for optimizing and deploying AI inference.
More info available by link https://github.com/openvinotoolkit/openvino.

### How large is each release?

~466 MB latest release (without manylinux arm64 wheels) 
4 windows wheels ~ 115 MB
4 manylinux x86_64 wheels ~ 145 MB
4 macos arm64 wheels ~ 86 MB
4 macos x86_64 wheels ~ 120 MB

### How frequently do you make a release?

The plan is to upload OpenVINO™ to this PyPI project on nightly basis, with rotation(remove old releases)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
The current project size is only 1.1 GiB, it would be better to revisit this when you are closer to the 10GiB limit unless you expect to hit that very soon.

Additionally, given that you plan to do "rotation" (i.e. remove old releases) you might not actually exceed the project size limit as a result, and this may be unnecessary?

**Comment by artanokhov** [comment]
Yeah, can close this now because of rotation

**Comment by artanokhov** [comment]
@di 
we want to update our rotation to ~1 month, because of user requests.
Currently I've changed it from 1 week to 2 weeks.

**Comment by artanokhov** [comment]
@di  @pradyunsg 
Could you please extend the project limit to 25 GB?

**Comment by artanokhov** [comment]
@di @pradyunsg
Folks, since there is no working solution to proceed with automatic rotation in PyPI, could you please extend the project limit?

**Comment by di** [comment]
I've set the total size limit for `openvino-nightly` to 25GB on PyPI and TestPyPI.
