### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by j-bennet** [pypi/support#3234]
### PyPI Username

`irinatruong`

### Reason for request

I lost 2FA authentication app or security token for test.pypi.org.

I'm able to log in to pypi.org, but not to test.pypi.org.

Please help.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
No user with username `irinatruong` is found on test.pypi.org.

**Comment by j-bennet** [comment]
@ewdurbin I provided an incorrect username. It should be `icherniavska`.

Please reopen the issue.

**Comment by ewdurbin** [comment]
Please open a new issue.

**Comment by j-bennet** [comment]
https://github.com/pypi/support/issues/3577
