### ISSUE TITLE
PEP 541 Request: mm

### ISSUE THREAD

**Issue by aivazis** [pypi/support#3240]
### Project to be claimed

`mm`: https://pypi.org/project/mm

### Your PyPI username

`aivazis`: https://pypi.org/user/aivazis

### Reasons for the request

It appears that the project is abandoned. It had a bit of activity between 8/15/2014 and 9/8/2014, but nothing since. The homepage link is broken. My attempts to reach the project maintainer did not get any response.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The PKG-INFO file in the most recent tarball mentions https://github.com/joeferraro/mm, which is a 404.

My replacement is hosted at https://github.com/aivazis/mm.

### Contact and additional research

I have tried to reach the contact person listed on the pipit page with no success, most recently on 10/6/2023. Here is a copy of that email.

[mm.pdf](https://github.com/pypi/support/files/12840937/mm.pdf)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @aivazis,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
Hi @aivazis,

The Owner has replied back and wishes to keep their project. Therefore, per [PEP 541 guidelines](https://peps.python.org/pep-0541/#reachability), we unfortunately cannot transfer it to you.
