### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mrintroverrt** [pypi/support#3243]
### PyPI Username

prasaanth2k

### Reason for request

I have lost my auth applictaion 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `prasaanth2k` has valid recovery codes generated as of 2023-08-17 14:33:39.443120.

Please use those recovery codes to regain access to your account.

**Comment by mrintroverrt** [comment]
Where I can get the code

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
