### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bsquizz** [pypi/support#3244]
### PyPI Username

`bsquizzato`

### Reason for request

Please see #3181 -- I have already verified the account ownership. However, as far as I can tell I never received a password reset email at the primary email address that I was contacted at. So I navigated to the login page and used "Forgot Password" to attempt a reset. I reset the password on my account but was still prompted to enter a 2FA token. It doesn't seem like 2FA has been disabled on this account. Still locked out and this was not fully resolved, so I need to re-open the issue. Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Duplicate #3181 bsquizzato
