### ISSUE TITLE
File Limit Request: bigdl-core-xe - 200 MB

### ISSUE THREAD

**Issue by Oscilloscope98** [pypi/support#3245]
### Project URL

https://pypi.org/project/bigdl-core-xe/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`bigdl-core-xe` is providing acceleration for LLM inference on Intel GPUs.  It has been active for two months.

### Reasons for the request

We request increase release size for `bigdl-core-xe` is because we added a new shared library (~60 MB) in our project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Oscilloscope98 :wave:
I've set the upload limit for `bigdl-core-xe` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week
