### ISSUE TITLE
Project Limit Request: Rasterio - 50 GB

### ISSUE THREAD

**Issue by sgillies** [pypi/support#3249]
### Project URL

https://pypi.org/project/rasterio/

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Rasterio is a foundational package for the GIS and remote sensing communites. It's used by many projects. We've been publishing wheels to PyPI for 9 years. Rasterio vendors over a dozen C libraries (gdal, geos, proj, tiff, curl, etc, along with supporting data) using the strategy pioneered by the numpy and scipy projects. After various optimizations, including library symbol stripping, wheels are 19-23 MB in size, depending on the platform. I expect that wheel sizes won't get significantly larger in future releases, 10-15% at most.

### How large is each release?

4 platforms x 5 versions of Python x 20 MB wheel size = ~400 MB per release. Most of this is C libraries and supporting data like cartographic projection databases and world geodetic data. The project is likely to add a 5th platform in 2024, so the future release size is ~500 MB.

### How frequently do you make a release?

About 10 times a year. A new 50 GB limit would allow ~60 releases (at the future 500 MB size) over the next 5-6 years.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `rasterio` to 50 GB on PyPI. Please be mindful of usage at that size!

**Comment by sgillies** [comment]
Thanks @di ! We're working to keep the wheels as small as we can and are being parsimonious about features and platforms.
