### ISSUE TITLE
File Limit Request: PySuperTuxKart2-Data - 637 MB

### ISSUE THREAD

**Issue by bpiwowar** [pypi/support#3252]
### Project URL

https://pypi.org/project/PySuperTuxKart2-Data

### Does this project already exist?

- [X] Yes

### New Limit

800MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is a new version of the Python interface for SuperTuxKart -- based on https://github.com/philkr/pystk -- but updated to the latest branch. To reduce the number of packages and their size, this package PySuperTuxKart2-Data only contains the data files from SuperTuxKart (for a given version). The PySuperTuxKart package will contain the library itself that allows controlling the game for e.g. reinforcement learning experiments.

### Reasons for the request

It might increase if the data files from SuperTuxKart increase.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @bpiwowar :wave:
have you explore other ways of getting the data from the user side?
You can see an example from the `nltk` package: https://www.nltk.org/install.html#installing-nltk-data

**Comment by bpiwowar** [comment]
Hi – I just took back the PySTK code, but obviously this would be a better solution; working on it, so we can close this.

**Comment by cmaureir** [comment]
Thanks for considering it @bpiwowar :+1:
