### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by drednout** [pypi/support#3258]
### PyPI Username

drednout.by

### Reason for request

Hi!

I've recently crashed my phone with 2FA auth application and then discovered that I don't have any backups of Auth application. 
I still able to upload packages using generated TWINE_PASSWORD, but can't login into https://pypi.org/ account.
Need assistance with providing some one-time backup code for login. I have access to my email and know password(1st factor) to my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `drednout.by` has valid recovery codes generated as of 2022-07-09 09:47:16.463425.

Please use those recovery codes to regain access to your account.

**Comment by drednout** [comment]
Hello, @ewdurbin !

Unfortunately, I can't find recovery codes on any of my devices. Are there any other options to restore access to the account?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by drednout** [comment]
Thanks a lot, @ewdurbin! Everything is OK for me. :+1: 

Have a great working week!
