### ISSUE TITLE
PEP 541 Request: minimax

### ISSUE THREAD

**Issue by minqi** [pypi/support#3259]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/minimax

### Your PyPI username

`USER_NAME`: https://pypi.org/user/minqi

### Reasons for the request

Hi there! We are researchers from Meta AI, DeepMind, and [University College London](https://ucldark.com/). We are planning to release a library for hardware-accelerated reinforcement learning algorithms in JAX, called `minimax`. In particular, this library is focused on _minimax_-regret automatic curriculum learning methods, and we believe this codebase can greatly expedite research progress in this important area.

We are requesting the transfer of the existing package name `minimax` to the PyPI account of the lead developer on this project. We believe our request for the transfer of `minimax` should qualify under the conditions outlined in PEP 541:
- The existing package `minimax`, which we hope to replace, has not been updated in over 19 months. The last update was on February 20, 2022. Moreover, the current package consists of only a single `.py` file containing a stub class (with no functionality currently implemented). 
- We have tried to contact the author, but have not received a response.

Based on the above, we believe the project qualifies as either "abandoned" or "invalid" (due to the contents being largely empty).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Existing repo: This repository no longer exists (the URL listed under the current package page results in a 404: https://github.com/bergurtareqtamimi/minimax_package)

Our intended replacement repository is currently private (under Meta AI) until release. Of course, we would love to share it once it is released, though ideally we can release it under the package name `minimax`. I can also share the codebase privately with a moderator.

### Contact and additional research

We have tried to reach out to the author of the current `minimax` package, but have not received a response. (We contacted bergurtamimi@gmail.com)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by minqi** [comment]
Hi, just checking in to see if any PyPI maintainer might be able to help us out? @di @yeraydiazdiaz

**Comment by Thespi-Brain** [comment]
Hi @minqi,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
**minimax** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Added 'minqi' as 'Owner' on 'minimax'
