### ISSUE TITLE
PEP 541 Request: elasticsearch-serverless

### ISSUE THREAD

**Issue by pquentin** [pypi/support#3261]
### Project to be claimed

`elasticsearch-serverless`: https://pypi.org/project/elasticsearch-serverless

### Your PyPI username

`quentinp`: https://pypi.org/user/quentinp

### Reasons for the request

As I was preparing the initial release of https://github.com/elastic/elasticsearch-serverless-python, I unfortunately made the GitHub project before uploading on PyPI. This gave time for an attacker to upload an invalid project unrelated to Elasticsearch Serverless which is a copy of another seemingly invalid package with the name changed: https://pypi.org/project/ec2-hibinit-agent/.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current project does not have source code available, to the best of my knowledge.

https://github.com/elastic/elasticsearch-serverless-python

### Contact and additional research

I was not able to contact the uploader because I don't have contact information. The contact information in the Author-email is obviously fake. Per https://inspector.pypi.io/project/elasticsearch-serverless/119.4.6/packages/79/ac/9d01b5e8bf1a9e815835e0be2525af65bd35465d9879176512bcbab19867/elasticsearch-serverless-119.4.6.tar.gz/elasticsearch-serverless-119.4.6/PKG-INFO, it is `cccccallofduty@fffacebook.com`.

The other package of https://pypi.org/user/david-aws/ also seems fake, and was likely uploaded after https://github.com/aws/amazon-ec2-hibinit-agent/blob/master/setup.py was made public. This is probably the reason the author is named "david-aws", to make it seem more legit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
sniping with a typosquat isn't really a 541 its more abuse, so in this case given the timing and garbage contents of the project, this has been released. unfortunately you will not be able to re-use the file names uploaded already.

**Comment by pquentin** [comment]
Thank you, really appreciate the help here. :pray:
