### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by yrevar** [pypi/support#3263]
### PyPI Username

yrevar

### Reason for request

IIRC I have not generated "account recovery codes" for this account. I'm unable to login as it now requires such codes for authentication. I have access to my email. I'd like to know how to setup 2FA on this account. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by yrevar** [comment]
I am currently seeing the email from PyPI titled "Migrate to API tokens for uploading to PyPI." The email indicates that my account has two-factor authentication (2FA) enabled. However, after checking my authenticator apps, I cannot locate any authentication codes for PyPI. To set up the authenticator app or generate new codes, I would need to log in first, which in turn requires an authentication code. Essentially, I am locked out of my account.

**Comment by yrevar** [comment]
Can someone define "significant amount of time" for me?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by yrevar** [comment]
Thanks for your attention. I have not received any email related to this matter, aside from an update regarding our ongoing conversation. I attempted to search my mailbox using the query "pypi" but was unsuccessful in locating the email you are highlighting. Could you kindly confirm the delivery status or provide guidance on an alternative method for searching?

**Comment by ewdurbin** [comment]
sorry, the automation tooling i'm adapting to process these requests more rapidly incorrectly created new conversations as originating from you, not from our systems. a new email has been sent.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by yrevar** [comment]
Thanks!
