### ISSUE TITLE
PEP 541 Request: holidays [Test PyPI]

### ISSUE THREAD

**Issue by arkid15r** [pypi/support#3264]
### Project to be claimed

`holidays`: https://test.pypi.org/project/holidays

### Your PyPI username

`arkid15r`: https://test.pypi.org/user/arkid15r

### Reasons for the request

Please note it's **not** PyPI but the **Test PyPI** request -- no action is needed for https://pypi.org/project/holidays/

As a project maintainer of [Python Holidays](https://github.com/vacanza/python-holidays) package I'd like your help with a name retention issue:

I'm requesting a transfer of https://test.pypi.org/project/holidays/ to my account as we want to have an ability to test our PyPI publishing process. The current [owner](https://github.com/s-weigand) does not belong to our organisation and did not respond to multiple email messages I sent to the email address I had found. 

This situation is a result of the current owner's (tagging @s-weigand) help with [setting up a CI/CD](https://github.com/vacanza/python-holidays/pulls?q=is%3Apr+is%3Aclosed+author%3As-weigand) a couple years ago (thank you for your help!).

Thank you for maintaining PyPI/Test PyPI!

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/vacanza/python-holidays

### Contact and additional research

The current owner contact attemtps:
  - emailed s.weigand.phy[at]gmail.com Oct 7, 2023
  - emailed s.weigand.phy[at]gmail.com Oct 11, 2023

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by arkid15r** [comment]
Oh wow, thank you so much @Thespi-Brain 
I'm so happy @psf finally hired somebody to take care of this pile of tickets!

**Comment by s-weigand** [comment]
@arkid15r I followed the instructions in the email and added you as owner of `holidays` on  `test.pypi.org`. I saw that  you are a maintainer of the upstream project and also on prod PyPI. Sorry for blocking it on the test server I simply forgot about it after doing my CI tests :sweat_smile:

**Comment by arkid15r** [comment]
Thank you @s-weigand, I've accepted the invitation.

@Thespi-Brain I'm closing this issue as it has been resolved.
