### ISSUE TITLE
python-docx (testpypi only)

### ISSUE THREAD

**Issue by scanny** [pypi/support#3265]
### PyPI Username

`scanny`

### Reason for request

This is on `testpypi` only, everything is fine for `python-docx` on `pypi`.

Another user claimed this accidentally when trying an upload. I found him on linkedin and he has since released the name, but it has not become available again yet.

Can I get this name on `testpypi` so I can test new packages without a temporary project rename?

---

Hi Kazuki,

Any chance you're the kzinmr who is listed as the maintainer on this project on [test.pypi.org](http://test.pypi.org/)?
https://test.pypi.org/user/kzinmr/ 

I'm the author of python-docx and wanted to use [test.pypi.org](http://test.pypi.org/) to test new releases before publishing them, which is what I'm doing now.

Any chance you could release that project (I think it's deleting it from your project page) so I can claim it?

That way I don't have to rename the project to get it up on [test.pypi.org](http://test.pypi.org/) :)

Best,
Steve

SEP 25 Kazuki Inamura sent the following message at 6:46 AM
[View Kazuki’s profile](https://www.linkedin.com/in/ACoAACTZ3P4Bw_XJYNgDzCXHET4g73hIwVF8Syk)Kazuki Inamura
[Kazuki Inamura ](https://www.linkedin.com/in/ACoAACTZ3P4Bw_XJYNgDzCXHET4g73hIwVF8Syk) 6:46 AM
Hi Steve

I've removed the project (https://test.pypi.org/project/python-docx).
Sorry for having reserved the namespace. I assumed the domain is not public.
I've just tried to release the wheel files on pypi to conduct an experiment for running python-docx on Pyodide.

Best regard,
Kazuki

SEP 28 Steve Canny sent the following messages at 10:38 AM
[View Steve’s profile](https://www.linkedin.com/in/ACoAAAC1BskBFkEmBOYRz_EciZMeSPeR7FDVPxI)Steve Canny
[Steve Canny ](https://www.linkedin.com/in/ACoAAAC1BskBFkEmBOYRz_EciZMeSPeR7FDVPxI) 10:38 AM

Thank you so much Kazuki!! :)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA reset on test.pypi.org for user scanny.

**Comment by scanny** [comment]
Hi @ewdurbin, unfortunately this was not what I needed, my account worked fine (and does again now after re-establishing my credentials and 2FA :)

What I need is ownership of the `python-docx` project on TestPyPI. That name had been "taken" by someone else for transient purposes and now is no longer available to the actual `python-docx` core package (which I am the author of).

Is that something you can help me with or perhaps do I need to create a new issue or apply a different tag or something?

**Comment by scanny** [comment]
By the way, thank you so much for your work with Python! :)
