### ISSUE TITLE
PEP 541 Request: fms

### ISSUE THREAD

**Issue by JRosenkranz** [pypi/support#3270]
### Project to be claimed

`fms`: https://pypi.org/project/fms/

### Your PyPI username

`JRosenkranz`: https://pypi.org/user/JRosenkranz

### Reasons for the request

I believe the project may have been abandoned or is not being used as it has not been updated since 2012. I contacted the owner and he suggested I follow the guide for transfer here. Currently, we have the name ibm-fms (only in pypi), however it will be easier for our users to find us with the name fms as that is what it is being called in most locations.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current project: https://github.com/jcbagneris/fms
The new project: https://github.com/foundation-model-stack/foundation-model-stack

### Contact and additional research

I contacted the owner by email and he said "I am ok for you to use the name fms" and "I can confirm to whoever needs it that I am ok for my project to be archived/deprecated under a new name and for you to reuse the initial "fms" name." 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jcbagneris** [comment]
Hello there,

I am the owner of the project https://github.com/jcbagneris/fms
which on pypi is https://pypi.org/project/fms/

I confirm that:

- I agree for @JRosenkranz to use "fms" as a project name for his own project, currently named "ibm-fms"
- my "fms" project might be archived under the name "fms-jcb" as it is no longer used/active.

Thanks

**Comment by Thespi-Brain** [comment]
Hi @jcbagneris and @JRosenkranz,

Wonderful. I recommend that the PyPI Admins assign @JRosenkranz as the new owner of **fms**.

**Comment by miketheman** [comment]
@jcbagneris Thanks for chiming in with your approval.

> * my "fms" project might be archived under the name "fms-jcb" as it is no longer used/active.

Once ownership is transferred, the new owner may retain the older releases or remove them at their discretion. There ought to be little to no harm to keeping these older releases as part of the original project for those who are looking for it, but it won't be immediately apparent or evident, rather they would have to find the releases in the Release History for the project.

Renaming projects is not something PyPI is designed to perform, and would require you to re-upload the project under the new name.

If you are content with that situation, please re-confirm that this is fine with you, and we will process the transfer. Alternately, you may log into PyPI and transfer the project to the new owner yourself.

**Comment by jcbagneris** [comment]
I confirm that the transfer of the ownership to @JRosenkranz  is ok for me, please process it.
In addition, I think that there is no point for them to retain the older releases of the original fms project.

For your information, the repo of "my fms" on github is now available under the name [fms-jcb.](https://github.com/jcbagneris/fms-jcb)

**Comment by miketheman** [comment]
Added 'JRosenkranz' as 'Owner' on 'fms'
