### ISSUE TITLE
PEP 541 Request: Transfer of pytlsd

### ISSUE THREAD

**Issue by iago-suarez** [pypi/support#3272]
### Project to be claimed

`pytlsd`: https://pypi.org/project/pytlsd

### Your PyPI username

`iago-suarez`: https://pypi.org/user/iago-suarez

### Reasons for the request

I am the original author of this library. I developed this wrapper around the original LSD method in 2021 during my stay at ETH Zürich. The images, text, and code in the repository were created by me. 

I appreciate the work done by @ibaiGorordo in packaging the library and making it available in PyPi. However, I keep developing it in collaboration with @rpautrat, and since we do not own the PyPi repository we are blocked now without the possibility to maintain the package.

Therefore, we request the immediate transfer of the repository to my account iago-suarez from where we plan to keep maintaining it.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

My original repository:
https://github.com/iago-suarez/pytlsd

My colaborator @rpautrat repository:
https://github.com/rpautrat/pytlsd

@ibaiGorordo fork:
https://github.com/ibaiGorordo/pytlsd

### Contact and additional research

[Gmail - Transfer of pytlsd repository.pdf](https://github.com/pypi/support/files/12910077/Gmail.-.Transfer.of.pytlsd.repository.pdf)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by iago-suarez** [comment]
Dear PyPI admins,

Could you please take actions on this issue. It is really important for us and I see no progress.

Best,
Iago.

**Comment by Thespi-Brain** [comment]
Hi @iago-suarez,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message. Thanks.

**Comment by ibaiGorordo** [comment]
Sorry for the troubles, I just saw the mail. I invited you to the pypi project as owner. Once you join, I will remove myself from it.

**Comment by iago-suarez** [comment]
Sorry, it took me some days to restore the access to my PyPi account and the link has expired. Could you send me the invite again?

Best,
Iago.


El 5 dic 2024, a las 2:08, Ibai Gorordo ***@***.***> escribió:

﻿

Sorry for the troubles, I just saw the mail. I invited you to the pypi project as owner. Once you join, I will remove myself from it.

**Comment by Thespi-Brain** [comment]
Hi @iago-suarez and @ibaiGorordo, 

It looks like you have invited the other to be the project owner. Are you still having any other issues regarding ownership?

**Comment by iago-suarez** [comment]
I’ve just accepted the invitation.

Thank you all for taking care.
Cheers,
Iago.
