### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kwinkunks** [pypi/support#3273]
### PyPI Username

agile.geoscience

### Reason for request

Hi,

I have lost access my Google Authenticator device (I have it, but it is broken and beyond repair). I do not have recovery codes for this account (of course I do for my *other* organizations). Anyway, I can access & update the projects from my user `kwinkunks`, but I cannot administrate them.

My goal is to move the `gio` project to another organization, `softwareunderground` (which I am also admin of, and can access). I've just moved the project's repo: https://github.com/softwareunderground/gio

Thanks for any assistance you can offer, and sorry for the trouble.

Kind regards,
Matt

PS I was the founder/CEO of Agile, but the company is now closed, so I need to move its repos to other orgs. https://agilescientific.com/

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `agile.geoscience` has valid recovery codes generated as of 2023-03-17 11:30:15.366584.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by codelhf** [comment]
Please also help me restore my account. Thank you very much @ewdurbin
