### ISSUE TITLE
File Limit Request: rendercv - 150 MB

### ISSUE THREAD

**Issue by sinaatalay** [pypi/support#3276]
### Project URL

https://pypi.org/project/rendercv/

### Does this project already exist?

- [X] Yes

### New Limit

150 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

I just released RenderCV yesterday, but it is a project I have always had in my mind for two years. It's a Python package that creates a CV in PDF format by reading a YAML file.

To generate PDF files, I use LaTeX. However, I would like to be the project standalone (i.e., I want users to refrain from installing LaTeX since it would repel them). Therefore, I must publish the required LaTeX binaries with the project. Initially, it was around 500 MB, but carefully, I got rid of all the files that were not required. But for this project to work, I need at least 150 MB.

### Reasons for the request

LaTeX binaries and some other LaTeX files are required for the project. They need 150 MB of space.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @sinaatalay :wave:
I've set the upload limit for `rendercv` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week! :tada:
