### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ttyamada** [pypi/support#3278]
### PyPI Username

t.yamada

### Reason for request

Lost 2FA authentication app.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `t.yamada` has valid recovery codes generated as of 2021-02-23 12:39:57.960917.

Please use those recovery codes to regain access to your account.

**Comment by ttyamada** [comment]
Thank you for issue the code,  but the code format doesn't match the requested format.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
