### ISSUE TITLE
PEP 541 Request: application

### ISSUE THREAD

**Issue by danpascu** [pypi/support#3282]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/application

### Your PyPI username

`USER_NAME`: https://pypi.org/user/danpascu

### Reasons for the request

I am the maintainer of the `python-application` project (https://pypi.org/project/python-application). When I first published it I used the debian naming convention (put `python-` in front of the name), but that is unnecessary on pypi. Later my users reported that they were having problems installing it, because they tried to use `pip install application` which installed something else. I checked on pypi and noticed that there was this project called `application` that looks to me like some test someone made to check out how uploading to pypi works.

I would like to publish my project under the name `application` instead to avoid user confusion and the name redundancy of having `python-` in front of it. I ask for the `application` name to be transferred to me for the following reasons:

1. is a better name for my existing project `python-application` that avoids user confusion.
2. the project that uses the name currently (`application`) seems abandoned.
3. the project seems to be a test someone made to check how pypi works (it contains no useful code other than a `hello world` written with flask).
4. the project is the only project of that user, which created the pypi account on the same day he uploaded this test and has never touched since (19 Feb 2019).
5. the project has no useful metadata (all fields are listed as UNKNOWN), so I cannot find this person to ask them to release the name as they have provided no email address, author or homepage and neither has the account any email address associated with it.
6. The project contains 1 function that returns `Hello world!`, and 3 small classes that total around 20 lines of code. It doesn't look like anything useful that should have been published.

Overall it all looks like a test someone made and now the name is locked.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

I do not have the source code of the existing `application` project as it was not written by me and the author has not provided a homepage for it. In order to check it's content, I downloaded the source release they provided on pypi from the `Download files` section of the project page and checked the code from there.

The project I intend to publish in its place is `python-application` (https://pypi.org/project/python-application) which can be found here: https://github.com/AGProjects/python-application

### Contact and additional research

I could not contact the author of `application` as he has not provided an email address or homepage with the project, neither does he have an email address attached to his account. I opened this ticket as a last resort as there is no way for me to get in touch with him.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @danpascu,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
**application** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Added 'danpascu' as 'Owner' on 'application'
