### ISSUE TITLE
PEP 541 Request: pyoptions

### ISSUE THREAD

**Issue by Mr-Elysium** [pypi/support#3284]
### Project to be claimed

pyoptions: https://pypi.org/project/pyoptions

### Your PyPI username

jonathan.he2s: https://pypi.org/user/jonathan.he2s

### Reasons for the request

I believe this project to be abandoned or otherwise, because no pypi projects for pyoptions exists and. Doing 
```
pip install pyoptions
```
yields nothing. There exists a pyoption package, and I contacted its owner directly, but no owner of the pyoptions package was found by me.

When trying to upload my own package under the pyoptions name it does yield and error:
```
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/                                                                                        
         The user 'jonathan.he2s' isn't allowed to upload to project 'pyoptions'. See https://pypi.org/help/#project-name for more information.
```

### Maintenance or replacement?

Replacement

### Source code repositories URLs

I could not find any source code for the original pyoptions libraray, since I am pretty sure it does not exist.
My source code can be found at: https://github.com/Mr-Elysium/pyoptions/

### Contact and additional research

I was unable to find source code for the original pyoptions package and as such also no owner. I did find a owner of the pyoption package and I contacted them directly to see if they would be open to swapping names with me, but pyoptions is my preference.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @Mr-Elysium,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
**pyoptions** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 

I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
@Mr-Elysium I can see that you've already established `pyoption` and more recently `pystockoptions` - is this request still necessary?

**Comment by Mr-Elysium** [comment]
> [@Mr-Elysium](https://github.com/Mr-Elysium) I can see that you've already established `pyoption` and more recently `pystockoptions` - is this request still necessary?

Hi, thank you. Yes I would still like the name ```pyoptions```, once I have published the package under that name I will release the other two.

**Comment by miketheman** [comment]
Added 'jonathan.he2s' as 'Owner' on 'pyoptions'
