### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by damiengueho** [pypi/support#3285]
### PyPI Username

damien28

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by damiengueho** [comment]
I haven't had the chance to set up 2FA and haven't received any recovery codes.

<img width="1006" alt="Screenshot 2023-11-28 at 7 14 58 PM" src="https://github.com/pypi/support/assets/65455967/470f0267-2435-4071-9703-8008e780536e">

**Comment by damiengueho** [comment]
Hoping to bump this. I've seen that that some Account Recovery Issues created before and after Oct 19 have started to see paths to resolution. Hope this one hasn't been skipped/forgot in between. If there's anything I can do to help, please let me know. Thanks! @ewdurbin @dstufft

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
