### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by PaulMathon** [pypi/support#3286]
### PyPI Username

p.mathon@criteo.com

### Reason for request

I can't login to pypi.org using my email address and I forgot my username. How can I find it from my email address? p.mathon@criteo.com

Thank you,

Paul

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
criteo-marketing
