### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by samjrholt** [pypi/support#3288]
### PyPI Username

`samjrholt`

### Reason for request

I still have access to my email address but unfortunately my phone broke and I could not transfer my 2FA authentication information to my new phone. I no longer have access to my 2FA app.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by josyb** [comment]
Excuses to have bothered you; I found the *recovery codes* and used this to login and updated the Authenticator app for use with PyPi

**Comment by samjrholt** [comment]
@josyb I think you may be commenting on the wrong issue

**Comment by josyb** [comment]
Excuses.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
