### ISSUE TITLE
File Limit Request: aspose-cad - 250 MB

### ISSUE THREAD

**Issue by Vitalii-Kornyliuk** [pypi/support#3289]
### Project URL

https://pypi.org/project/aspose-cad/

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project introduces working with CAD files and enables:
1. convert one CAD format to another CAD format
2. convert CAD format to raster format
3. create a CAD file
4. Edit CAD file etc
The first release of this python project appeared in 2022 and continues to evolve, adding new formats and improving functionality

### Reasons for the request

At the moment, our release for Linux takes up 180 MB, and for Windows it has almost reached the maximum allowed size also in the future the size of the package may increase, taking into account the appearance of new functionality and new versions of python

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Vitalii-Kornyliuk :wave:
Thanks for the report, I have set the upload limit for `aspose-cad` to 250M on PyPI.
Have a nice week
