### ISSUE TITLE
File Limit Request: tensorflow-tpu - 365 MB

### ISSUE THREAD

**Issue by kanglant** [pypi/support#3292]
### Project URL

https://pypi.org/project/tensorflow-tpu

### Does this project already exist?

- [X] Yes

### New Limit

365 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

tensorflow-tpu is project for TensorFlow release builds on TPUs.

TensorFlow is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices.

Originally developed by researchers and engineers from the Google Brain team within Google's AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains. TensorFlow is licensed under [Apache 2.0](https://github.com/tensorflow/tensorflow/blob/master/LICENSE).

### Reasons for the request

tensorflow-tpu contains wheels built from TensorFlow TPU release builds. 

Due to the ongoing addition of new features, the size of the tensorflow-tpu wheel has increased to 317 MB. To accommodate anticipated future growth, we are requesting a file size limit exemption of 365 MB, which would provide an additional 50 MB of room.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @kanglant :wave: thanks for the report.
I've set the upload limit for `tensorflow-tpu` to 400 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice Thursday!
