### ISSUE TITLE
File Limit Request: pmpc - 300 MB

### ISSUE THREAD

**Issue by rdyro** [pypi/support#3297]
### Project URL

https://pypi.org/project/pmpc/

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Python-interface Particle Sequential Convex Programming Model Predictive Control (SCP PMPC) interface.

This is non-linear dynamics finite horizon Model Predictive Control (MPC) solver with consensus optimization capability, support for arbitrary constraints and arbitrary cost.

### Reasons for the request

The solver needs to be distributable to many devices (hence my desire to use PyPI, since PyPI is awesome), but the solver is written in Julia.

I want to be able to distribute the solver to users who don't have Julia installed and I want to be able to distribute fully precompile Julia images to avoid precompilation time, which is long for a medium Julia library like this one.

I built wheels that bundle the statically compiled Julia libraries for immediate execution. However, the Julia precompiled library is large, about 350 MB for the custom image and 200 MB for Julia standard libraries. Compressed, the wheel takes up about 220 MB of space.

Hence, I'm asking for an upload limit increase to 300 MB to be able to bundle precompiled Julia binaries.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @rdyro :wave:
I've set the upload limit for `pmpc` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week

**Comment by rdyro** [comment]
Thank you, I'll keep the release frequency to a minimum!

Have a good week!
