### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by il-dat** [pypi/support#3302]
### PyPI Username

dat@infinitelambda.com

### Reason for request

I can't remember `Username` in order to login.
I have tried to use email but it didn't work though.

Could you please help me out here? 
Thanks a lot

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
adrien.boutreau
