### ISSUE TITLE
PEP 541 Request: SQUID

### ISSUE THREAD

**Issue by evanseitz** [pypi/support#3304]
### Project to be claimed

`SQUID`: https://pypi.org/project/SQUID

### Your PyPI username

`evanseitz`: https://pypi.org/user/evanseitz

### Reasons for the request

The project name SQUID doesn't appear to be in used, but I am unable to claim it.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://pypi.org/project/squid-nn

https://github.com/evanseitz/squid-nn

### Contact and additional research

Since the domain is not actually taken, I am unsure who to contact for this request.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @evanseitz,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
**SQUID** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 

I recommend that the PyPI Admins release the name for future use.

**Comment by miketheman** [comment]
Added 'evanseitz' as 'Owner' on 'squid'
