### ISSUE TITLE
Project Limit Request: projen - 30 GB

### ISSUE THREAD

**Issue by mrgrain** [pypi/support#3308]
### Project URL

https://pypi.org/project/projen/

### Does this project already exist?

- [X] Yes

### New limit

30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[projen](https://github.com/projen/projen#projen) is a CLI and library to define and maintain complex project configuration through code. As opposed to existing templating/scaffolding tools, projen is _not_ a one-off generator. To modify a project setup, users interact with rich strongly-typed class and execute projen to update their project configuration files.

projen was [first released](https://www.npmjs.com/package/projen/v/0.1.0) in Nov 2020, with its [first Python release](https://pypi.org/project/projen/0.14.0/) in Jan 2021.

projen is a project [owned and maintained by AWS](https://github.com/projen) and critical to many of our teams workflows.

Due to the project's nature of having to bundling its runtime dependencies, we expect the release size to increase moderately when new dependencies are required. We are very carful and selective about adding additional dependencies, and expect the package size to stay below 5MB in the foreseeable future.

### How large is each release?

The last published release of projen was 3.7 MB

projen is a [jsii](https://aws.github.io/jsii/) project. I.e. it is an application developed in TypeScript for Node.js and uses a toolchain to generate executable Python bindings. (You might be more familiar with the [AWS CDK](https://pypi.org/project/aws-cdk-lib/) which uses the same approach.)

The published artifact contains the Python bindings and a copy of the Node.js app.
Due to the nature of jsii packages, the Node.js bundle contains a number of javascript runtime dependencies.

We have identified that previously the documentation was included in this artifact and removed it. https://github.com/projen/projen/pull/3025
This reduced the compressed Python artifact by ~0.2MB

### How frequently do you make a release?

This project was released daily to ensure the bundled dependencies are always up to date. 
However we have identified an issue, causing us to erroneously release when only irrelevant dependencies (e.g. for the test system) got updated. This issue was addressed in https://github.com/projen/projen/pull/3041

The project follows a continuous release philosophy, but with the above issue addressed, we are expecting around 5-20 releases per month (instead of the previous 35-55).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @mrgrain :wave: thanks for the report.
I've set the project limit for `projen` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice Thursday
