### ISSUE TITLE
intel-tensorflow - need 10GB addition to the current project to release TF2.14

### ISSUE THREAD

**Issue by justkw** [pypi/support#3318]
### Project URL

https://pypi.org/project/intel-tensorflow-avx512/

### Does this project already exist?

- [X] Yes

### New limit

20GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is the intel optimization for tensorflow project, and we release avx512 wheels with various Python version

### How large is each release?

~250MB per Python version, currently python 3.9, 3.10, and 3.11 are supported, so total of ~750MB per release.  If more python version is supported, then we need additional ~250MB for each Python version.

### How frequently do you make a release?

Roughly quarterly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Limit on PyPI bumped to 20 GB.
