### ISSUE TITLE
PEP 541 Request: gdw

### ISSUE THREAD

**Issue by dougthor42** [pypi/support#3319]
### Project to be claimed

`gdw`: https://pypi.org/project/gdw

### Your PyPI username

`dougthor42`: https://pypi.org/user/dougthor42

### Reasons for the request

I'm unable to tell if this project exists. A [search of `pypi`](https://pypi.org/search/?q=gdw) returns no results so I'm unable to determine who the current owner is (PEP 541 step 1 "Try to contact the current owner(s) directly").

### Maintenance or replacement?

None

### Source code repositories URLs

New project: https://github.com/dougthor42/gdw

Current project: unknown.

### Preamble

"gdw" stands for "Gross Die per Wafer" (gross as opposed to _net_ die per wafer) and is a common initialism used in the semiconductor processing industry.

I'm not married to the name `gdw` - if it's decided that the name is invalid for a legitimate reason, I can easily come up with something new. I just want to make sure I try grabbing it before spending the time and effort to rename it 😆.

### Contact attempts and additional research.

I'm unable to determine who the current owner of https://pypi.org/project/gdw is.

+ A direct link (https://pypi.org/project/gdw) to the project returns a 404
+ A search of pypi (https://pypi.org/search/?q=gdw) returns no exact matches and only 4 partial matches:
  + `gdw-find-duplicate-files`
  + `gdrivewrapper`
  + `gdwrapper`
  + `gdwrap`

> The project name conflicts with a Python Standard Library module from any major version from 2.5 to present.

It doesn't seem like `gdw` has any near-matches with the stdlib. The most likely near-matches are `pdb`, `bdb`, or `dbm`, but in 
my opinion none of those are close enough to be easily confused

> The project name is too similar to an existing project and may be confusable.

It's possible that `gdw` is confusable with other names (https://pypi.org/search/?q=dw&o=) like `dw` or `dgw` or `dwg`. I

**It seems like this is the most likely case.** Can someone confirm this? 

> The project name has been explicitly prohibited by the PyPI administrators.

I think this is unlikely.

> The project name has been registered by another user, but no releases have been created.See How do I claim an abandoned or previously registered project name?

I'm not sure how to determine if this is the case, given that a direct link to the name returns a 404.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @dougthor42,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
Project **gdw** has been deemed invalid. Additionally, many attempts have been made to reach out to the owner, but no valid contact info was found. Owner has also not been active for many years.

I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Added 'dougthor42' as 'Owner' on 'GDW'
