### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jdamascenojm** [pypi/support#3320]
### PyPI Username

jdamasceno

### Reason for request

Lost acess tô email adress 
My email adress is jdamasceno.jm@gmail.com
I paid my assignature, help me pleasy.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by jdamascenojm** [comment]
I paid my assign and canot work please help me

**Comment by ewdurbin** [comment]
Please email support@pypi.org from the address you would like associated with the account. Please include a link to this GitHub Issue as well as the address previously associated with the account.

**Comment by Thespi-Brain** [comment]
Hi @jdamascenojm,

I am following up regarding your request. Are you still having an issue regarding updating your email address and logging in? Let me know, and please send your preferred email to support@pypi.org. I will keep this issue open for another week unless I hear from you earlier, thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
