### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lordskyzw** [pypi/support#3322]
### PyPI Username

`lordskyzw`

### Reason for request

Lost 2FA authentication app and security tokens but  still have my email account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by lordskyzw** [comment]
I don’t have them

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
