### ISSUE TITLE
Project Limit Request: HUMAnN - 1 GB

### ISSUE THREAD

**Issue by ljmciver** [pypi/support#3323]
### Project URL

https://pypi.org/project/humann/

### Does this project already exist?

- [X] Yes

### New limit

1

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

1 Gb should be large enough that it will cover future increases too.

HUMAnN is a tool for functional profiling of metagenomics data. Due to updates in the tool that incorporate new versions of databases (which have increased in size) the HUMAnN package and its data files have also increased in size. 

### How large is each release?

We have migrated some data files that were included in the package in prior versions to individual archives to be installed after the pypi package to try to reduce the size of the new pypi package.

The last release was ~ 100 MB. We expect this release to be under 250 MB. We request 1 Gb to allow for increases in future releases. 

### How frequently do you make a release?

Approximately every quarter.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ljmciver** [comment]
Hi @cmaureir , I wanted to get your input on this request. If it is too large I think we could fit our package in 200 MB max. I set the request to 1 Gb as the template was in Gb. Please give me feedback when you have time. 

Thank you in advance for your help!
Lauren

**Comment by pradyunsg** [comment]
The project size limit is 10 GB at this time. Did you intend to request a per-file limit increase to 200 MB / 1 GB?

**Comment by ljmciver** [comment]
Hi @pradyunsg , Thank you for your response! I had no idea the project size limit was that large for HUMAnN. Where do I go to check the project size limit for PyPI packages? How large is the HUMAnN per-file limit? I think our largest file is now just under 100MB. 

Thanks again!
Lauren

**Comment by cmaureir** [comment]
The default values for file upload limit is 100MB, and Project limit is 10GB.
It seems that the request is not necessary from your messages. Feel free to open a new request when necessary :)
