### ISSUE TITLE
Project Limit Request: av - 20 GB

### ISSUE THREAD

**Issue by jlaine** [pypi/support#3324]
### Project URL

https://pypi.org/project/av

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

PyAV provides Pythonic bindings to the FFmpeg libraries. It is a dependency of a fairly large number of a projects, and is flagged as a "critical project" on PyPI.

Building FFmpeg and its dependencies is a complex endeavour and takes a *long* time, so that expecting our users to build the library from source is unrealistic. When we tried this in the past, the issue tracker was constantly clogged up with requests for help building the package.

We therefore provide binary wheels which ship FFmpeg and several codec libraries. While the size of each wheel has remained almost constant, our efforts to supports as many platforms as possibles and all non-EOL Python versions has increased the number of wheels we produce.

### How large is each release?

Each release weighs in at around 1GB, with 40 wheels of about 25MB each.

The source tarball weighs 2.5MB.

I am trying to reach out to the former maintainer of PyAV (who has full ownership over the project) so that we can delete some old releases - but in the meantime our latest release (with Python 3.12) wheels is blocked so help would be highly appreciated.

I am aware that Cython very recently added some support for the Python limited ABI and will investigate how we can leverage it to reduce the size of future builds.

### How frequently do you make a release?

Around twice a year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Thank you for filling out the template for this issue properly! It's appreciated! ❤️ 

And, I've bumped the limit for this project to 20 GB.

**Comment by jlaine** [comment]
> And, I've bumped the limit for this project to 20 GB.

Thank you very much!
