### ISSUE TITLE
PEP 541: volunteering to help clear out the request queue

### ISSUE THREAD

**Issue by jzohrab** [pypi/support#3328]
### Project to be claimed

`PROJECT_NAME`: n/a

### Your PyPI username

`USER_NAME`: jzohrab

### Reasons for the request

Hello, I'm following up on the closed issue #842 , and am looking to contribute.

Today there are 229 requests in the queue, per https://github.com/pypi/support/issues?q=is%3Aopen+is%3Aissue+label%3A%22PEP+541%22

Issue #842 says that the queue is handled by volunteers, but I couldn't see a link on how to volunteer to help clear things out.

There are many requests that appear to be very simple, and these are likely cluttering the queue, e.g.:

* 3319  - no matching project
* 3326 - dead project since 2011 (disclaimer: I opened this one :-) )
* 2939 - empty useless project
* 2576 - "epi" published on testpypi but not on pypi - but the original PEP 541 request poster seems to have published another package, "eulerpi" , so this pep can likely be closed.

Note: Some requests appear to be somewhat more complicated, at first glance (e.g., 2673 - owner agreed, still not cleared? 2584 - some malware?) so I wouldn't want to comment on those until the easy stuff is cleared.

At the very least, getting rid of the obvious chaff would be a good step.  Optionally, perhaps there is some mechanism to flag _very_ simple PEP requests so that qualified/vetted/trusted volunteers can take over.

Cheers and thank you,
Jeff

### Maintenance or replacement?

None

### Source code repositories URLs

n/a

### Contact and additional research

n/a

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @jzohrab,

Appreciate your offer to volunteer, but we now have a full time staff (me) to tackle these cases. Even if something "seems" simple, when it comes to PEP 541 stuff it is actually not, and we are working to make sure we do the utmost due diligence to resolve the backlog. If you are interested in volunteering, there are lots of other ways to get involved with PyPI and I encourage you to do so, thanks.

**Comment by jzohrab** [comment]
Thanks @Thespi-Brain .  I still feel it would be useful to have volunteers at least help with gathering/classifying the "cruft" requests, but that's just me, and if the pypi team prefers a different way, that's how it will be.  Cheers and best wishes with taming the queue!
