### ISSUE TITLE
Project Limit Request: nnabla-ext-cuda110 - 20 GB

### ISSUE THREAD

**Issue by TomonobuTsujikawa** [pypi/support#3332]
### Project URL

https://pypi.org/project/nnabla-ext-cuda110/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

nnabla is a deep learning framework, and `nnabla-ext-cuda*` is CUDA extension of nnabla.
We have been working since 2017 to create lightweight and fastest deep learning framework.

Now we're in the release process, but we have noticed that new wheels could not be uploaded because the capacity of `nnabla-ext-cuda110` has almost full.
So, we would like to increase the project total size.

### How large is each release?

We have 8 packages for each release, and the wheel size is ~90MB.
* We support 2 OS - Linux and Windows.
* We support 4 python - v3.7 to v3.10.

### How frequently do you make a release?

once every 2 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by TomonobuTsujikawa** [comment]
@cmaureir san
Sorry for bother you, but could you please increase the limitation for this ticket and #3333?
Now we're in release process and stuck it because we cannot upload wheels.

**Comment by pradyunsg** [comment]
I've bumped the limit to 20 GB for this project.

There's no need to @-mention people here -- it isn't going to speed things up. This issue tracker is mostly handled by volunteers, so the backlog is worked through somewhat slowly. We tend to triage these tickets in bulk, when we have the free time to do so.
