### ISSUE TITLE
File Limit Request: ncbi-refseq-accession-offsets - 200 MB

### ISSUE THREAD

**Issue by kislyuk** [pypi/support#3334]
### Project URL

https://github.com/taxoniq/taxoniq

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Taxoniq is a package that indexes the National Center for Biotechnology Information Genbank databases and bundles a compact local search index of this data for fast access.

### Reasons for the request

The size of the Genbank database has grown so that these files no longer fit within the limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
> ### Project URL
> 
> [taxoniq/taxoniq](https://github.com/taxoniq/taxoniq)

The link requested was for https://pypi.org/project/ncbi-refseq-accession-offsets. I've bumped the limit for that project to 200 MB. :)
