### ISSUE TITLE
Project Limit Request: casadi - 40 GB

### ISSUE THREAD

**Issue by jgillis** [pypi/support#3336]
### Project URL

https://pypi.org/project/casadi/

### Does this project already exist?

- [X] Yes

### New limit

40 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

CasADi is a framework for algorithmic differentiation and nonlinear constrained optimization, used by thousands of engineers ( https://link.springer.com/article/10.1007/s12532-018-0139-4 ) both in academia and industry.
One might argue we are the Python counterpart to Julia's Jump framework.
We provide interfaces to a lot of solvers.

The first release was in 2010, and there is no end in sight for our development plans.

### How large is each release?

* why are our releases big?
 We bundle solver dependencies, letting the engineers focus on math and application domain expertise as opposed to fighting build systems.
* why do we retain old releases?
  1. A sizeable portion of users is PhD students working on (shared) lab/hardware setups. The setups have a large inertia to get updated. It is very common to see ubuntu 18.04 systems and python 2.7/3.5 in the wild. When the lab PI makes a new hire and a new generation of students arrives, it is very convenient if the work of the older students is still functional.
  2. Nonconvex optimization is fragile by nature, depending on solver implementation details. For debugging, it is very useful to compare against older releases
  3. Still, we did a very careful cleanup sweep at the start of this year
 * why do you release often? 
   Solvers are a hot topic. There is a lot of development going on. Still, we don't have a release frenzy, and don't expect to jump in frequency in the future.

### How frequently do you make a release?

5 times a year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Thanks for filling out the issue template fully, and providing all the details! It's appreciated! ❤️

I've bumped the limit to 40 GB as requested.
