### ISSUE TITLE
Not getting verification mail

### ISSUE THREAD

**Issue by SDcodehub** [pypi/support#3339]
**Describe the bug**
Not receiving testpypi verification mails. checked spam folder not present, added another mail same result

**Expected behavior**
Should receive mail for verification in mail box

**To Reproduce**
create account and verify your mail id

**My Platform**
Not receiving testpypi verification mails. checked spam folder not present, added another mail same result

**Additional context**

**Comment by di** [comment]
Hi, what is your username or email? I see no user named 'SDcodehub' on TestPyPI.

**Comment by SDcodehub** [comment]
hi my username is sagardesai.

primary email was ***@***.***, however, did not get
a verification call. **checked spam as well. can use help here.

changed primary to ***@***.*** my secondary email. got verification
and working.

thanks
Sagar Desai

**Comment by di** [comment]
Looks like you made a typo, `sagardesaee@gamail.com` instead of `sagardesaee@gmail.com`. I've changed it for you, you should be able to verify it now.
