### ISSUE TITLE
File Limit Request: pyvqnet - 300 MB

### ISSUE THREAD

**Issue by kevzos** [pypi/support#3345]
### Project URL

https://pypi.org/project/pyvqnet/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is start from 2022.04.
The project is maintained by originqc,https://originqc.com.cn/en/index.html.
The project provides tools for quantum machine learning for students and researchers.
This is the documents of api: https://readthedocs.org/projects/whc-vqnet20-tutorial-en/

### Reasons for the request

The newer version of the project includes new library that support gpu, which will increase the file sizes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @kevzos :wave:
I've set the upload limit for `pyvqnet` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:
