### ISSUE TITLE
Stuck! Wrong primary email

### ISSUE THREAD

**Issue by rjalexa** [pypi/support#3346]
### PyPI Username

rjalex

### Reason for request

I have mistakenly entered bob@isagog.pi as my primary email and of course will never receive a confirmation email there. I see no way of deleting/restetting/changing the primary email. Tried adding a second email (which is valid) but I never get the verification email there, maybe its waiting to verify the primary?

I tried registering a new username with the right primary email but it does not let me sice there are too many pending requests for my IP address.

So I'm utterly stuck. Help please.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Primary email address updated.
