### ISSUE TITLE
File Limit Request: C4dynamics - 300 MB

### ISSUE THREAD

**Issue by C4dynamics** [pypi/support#3347]
### Project URL

https://pypi.org/project/c4dynamics/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Hi, 
C4dynamics is an open source project for the development of system with dynamics in Python (Matlab immigrants).
It has ran on GitHub for above a year but it became necessary to allow installation via pip.
https://github.com/C4dynamics/C4dynamics. 
We have excluded the examples folder and any unnecessary files, but all the files still sum up to 242MB.
I publish about C4dynamics at linkedin at https://www.linkedin.com/in/ziv-meri/ and we are a small community of active contributors. 

### Future prediction

Currently we cant help reduce it more but we have a plan in later versions to change the architecture and reduce the total size significantly (adding 3rd party required installation and making use in their features by the appropriate API).

### Two words of appreciation

Thank you for the important work you do! 

### Reasons for the request

It's our first upload to PyPi. After clean of any unnecessary file, we still need some extra MB space to upload all the files. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @C4dynamics :wave:
I've set the upload limit for `c4dynamics` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend! :tada:

**Comment by C4dynamics** [comment]
Hey @cmaureir, thank you!
Have a great year! 🎉
BTW what's a plausible frequency for that size and in general?

**Comment by cmaureir** [comment]
It's up to you @C4dynamics :) as long as you don't hit the project limit (10 GB) too soon.
If you have release cycles that are not nightly or weekly, you might be on a safe path
