### ISSUE TITLE
File Limit Request: TPU-MLIR - 300 MB

### ISSUE THREAD

**Issue by luluman** [pypi/support#3348]
### Project URL

https://pypi.org/project/tpu-mlir/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[TPU-MLIR](https://github.com/sophgo/tpu-mlir) is an advanced Machine Learning Intermediate Representation (MLIR) project, specifically optimized for TPU (Tensor Processing Unit) architectures. This project has been actively maintained since its inception in March 2022. It represents a significant effort towards bridging the gap between high-level ML models and low-level TPU hardware execution, facilitating more efficient and effective deployment of machine learning models.

In preparation for PyPI distribution, we have taken substantial measures to minimize the package size, ensuring it aligns with PyPI's constraints. Our efforts include:

1. **Removing Non-Essential Components:** We have eliminated binary models and raw data that contributed significantly to the package size.

2. **Dependency Optimization:** Our team has carefully scrutinized the project's dependencies, retaining only those crucial for functionality. This effort has substantially reduced the package footprint.

3. **Internal MLIR Package Development:** Recognizing the substantial size of the official MLIR Python package (146MB), we have developed our own streamlined version. This custom MLIR package is considerably more compact, approximately 61MB, contributing effectively to the overall size reduction.

Our commitment to maintaining a lean and efficient package underscores our dedication to the Python community and the principles of efficient software distribution.

### Reasons for the request

TPU-MLIR is an open-source tool designed to support multiple generations of TPU hardware (1684, 1684x, 1688, sg2260, cv18xx), and it is compatible with various machine learning frameworks including ONNX, PyTorch, Caffe, TensorFlow, and PaddlePaddle. The project's aim is to provide an 'out-of-the-box' solution for users, allowing for a seamless integration within the Python ecosystem without requiring privileged system access for installation.

### Key features of TPU-MLIR include:

1. **Support for Multiple TPU Generations:** The tool is engineered to be compatible with various generations of TPU hardware, necessitating comprehensive libraries and dependencies to ensure broad functionality.

2. **Framework Compatibility:** TPU-MLIR supports a wide range of machine learning frameworks. This versatility is a core feature but also contributes to the package size due to the required libraries and dependencies for each framework.

3. **Python Ecosystem Integration:** To ensure easy and accessible installation, all required packages and dependencies are contained within the Python ecosystem, avoiding the need for system-level installations by users.

4. **Inference Framework:** TPU-MLIR includes an inference framework capable of running MLIR models and others used by Sophgo hardware, contributing to the overall size of the package.

Given the comprehensive nature of TPU-MLIR, the size of our package exceeds the standard limit on PyPI. The larger size is essential to maintain the functionality and user-friendliness of our tool. We have made every effort to reduce the size, including developing a custom, streamlined MLIR Python package and removing non-essential components.

### Future Release Sizes

As TPU-MLIR continues to evolve, we anticipate further development and support for new TPU generations and machine learning frameworks. This will inevitably increase the size of our releases and the total project size. Our goal remains to provide the most efficient and comprehensive tool for TPU-MLIR users while adhering to PyPI's guidelines.

We respectfully request an increase in the size limit to 300M to accommodate the current and future needs of the TPU-MLIR project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by luluman** [comment]
Hi @cmaureir , I am seeking assistance regarding a file size limit increase for my project on PyPI. We have a monthly release schedule, and our current wheel package, as seen in the [v1.5-beta.0 release of sophgo/tpu-mlir on GitHub](https://github.com/sophgo/tpu-mlir/releases/tag/v1.5-beta.0), is approximately 221MB, though the original size is around 600MB. Your prompt attention and feedback on this matter would be greatly appreciated.

Thank you in advance for your help!
Matt

**Comment by cmaureir** [comment]
Hey @luluman :wave:
I've set the upload limit for `tpu-mlir` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:
