### ISSUE TITLE
Name block request: freethreading, free-threading

### ISSUE THREAD

**Issue by hroncok** [pypi/support#3350]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/freethreading
`PROJECT_NAME`: https://pypi.org/project/free-threading

### Your PyPI username

N/A

### Reasons for the request

See https://discuss.python.org/t/naming-the-python-binary-when-disable-gil-is-set/34052/14

I'd like the names "freethreading" and "free-threading" to be blocked on PyPI so when we name the Fedora's nogil Python 3.13 package that way, it will not clash with a future project of the same name.

Let me know if this is a reasonable request.

### Maintenance or replacement?

None

### Source code repositories URLs

N/A

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by hroncok** [comment]
(Note that this is not exactly PEP 541, because the project doe snot exist yet, but the issues here did not allow me a free form.)

**Comment by encukou** [comment]
Should `freethreading` we blocked as well?

**Comment by hroncok** [comment]
Preferably yes.

**Comment by hroncok** [comment]
Actually, the name without the dash is what I want to use in Fedora
 I must have brainfarted when creating this issue. Let's block both anyway.

**Comment by gpshead** [comment]
blocking these from being used makes sense to me.

**Comment by hroncok** [comment]
Considering [the name has been set now](https://github.com/python/steering-council/issues/221#issuecomment-1841593283), can somebody please move this forward?

**Comment by ewdurbin** [comment]
freethreading (and implicitly free-threading) are blocked from registration.

**Comment by hroncok** [comment]
Thank You!
