### ISSUE TITLE
No way to amend a wrong unverified primary email

### ISSUE THREAD

**Issue by rjalexa** [pypi/support#3352]
**Describe the bug**
I registered on Pypi (user rjalex) but a neuron misfired and entered a wrong non existent email (bob@isagog.pi the correct one should end in com) of course this is unverified and will never get a verification email.
I tried adding a second valid email but this never gets a verification email probably since the primary is unverified.
I tried creating a new userid but I get an error message saying I have too many registration attempts open.
I cannot delete the second valid email.
So I am utterly stuck registering on PyPI :(

**Expected behavior**
Why couldn't change/delete the primary unverified email in case of an error/typo?

**To Reproduce**
Try registering with a non existant email which of course will remian unverified.
Try adding a second good email and try to verify that. It will tell you need to
verify the primary FIRST, so you're stuck with the wrong, undeletable, unmodifiable wrong primary email.

**My Platform**
MacOS Sonoma, Brave browser but I guess this is totally irrelevant.

**Additional context**
May the Force be with you. Thanks

**Comment by di** [comment]
I see a verification email sent to your secondary `@gmail.com` address that is marked as delivered by that mailserver. Perhaps you missed it due to a filter, or it went to spam?

In the event of a typo, you should be able to:
* add a second email
* verify that email
* make that email your primary email
* delete the typo'd email

**Comment by di** [comment]
The email is from `noreply@pypi.org` with the subject `[PyPI] Email verification`. I see a second one was just delivered a few minutes ago as well.

**Comment by rjalexa** [comment]
Thank you so much. Thanks to your help we're a step ahead :) I did find the two emails in an obscure Spam (not Junk) folder. Clicked on the verification link but sadly I get: "You must verify your **primary** email address before you can perform this action." So it looks as if the primary was wrong and never verified you're stuck as I am :(

**Comment by rjalexa** [comment]
Oooops sorry, I refreshed the page and I could elect the backup email as primary. All good now. Take care. Thanks
