### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tarekziade** [pypi/support#3362]
### PyPI Username

tarek

### Reason for request

I've changed phones, and my backup crashed for the TOTP recovery codes. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by tarekziade** [comment]
I know I have valid recovery codes generated in the system but I don't have them anymore, so I would need a reset, thanks

**Comment by ewdurbin** [comment]
User `tarek` has valid recovery codes generated as of 2023-05-26 22:32:01.742040.

Please use those recovery codes to regain access to your account.

**Comment by tarekziade** [comment]
I said on Dec 2 I don't have those codes anymore... I added this information here so you would not ask me and we would spare a round-trip...

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by tarekziade** [comment]
I have received the email asking me to create a branch on an *archived* repository, which is impossible.
I created the branch on another project's repository I also own and is not archived -- and send back the name of the project along with the branch URL by email

**Comment by ewdurbin** [comment]
It is not _impossible_ but is a little unreasonable. Our automation just checks for a 200 on repository URLs when finding a validation target.

I've re-issued the request for a repository that is confirmed not to be archived. Note that self-selecting what repository is used for validation kinda defeats the purpose of the validation.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
