### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by arkneid** [pypi/support#3364]
### PyPI Username

arkneid

### Reason for request

I Lost the 2FA authentication app and recover token.
I need to access to my account to update a project.

Can you help me?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by arkneid** [comment]
How is this issue?

**Comment by ewdurbin** [comment]
User `arkneid` has valid recovery codes generated as of 2023-08-15 21:57:01.799605.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
