### ISSUE TITLE
Project Limit Request: nautobot - 20 GB

### ISSUE THREAD

**Issue by glennmatthews** [pypi/support#3365]
### Project URL

https://pypi.org/project/nautobot

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Nautobot is a Django-based Network Source of Truth and Network Automation Platform.

The project has been active since late 2020 with the first published release in February 2021.

Release sizes may increase somewhat in the future as we're looking at adding a new UI framework to the project, although we should be able to reduce some other release size overhead in compensation (see also below)

### How large is each release?

Currently about 90 MB per release, including Python code, HTML templates and embedded documentation, and static files such as minified CSS and JS libraries that the project requires. Because it is often installed in "airgapped" environments, the project cannot have page content that links to web-hosted resources (JS, CSS, fonts) but instead must include those in the package as static files.

Now that I'm aware that PyPI has a project size limit we'll be making some concerted efforts to reduce the release size - I've already identified a couple of likely easy wins in our documentation that should let us reduce it by about 20 MB or so, but that of course will only apply to future releases. We are also planning to go into PyPI and delete old alpha/beta/RC versions of the project to free up some amount of space.

### How frequently do you make a release?

Roughly every two weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Thank you for filling out the template for this issue properly! It's appreciated! ❤️

I've bumped the limit to 20 GB as requested.
