### ISSUE TITLE
Project Limit Request: symengine - 30 GB

### ISSUE THREAD

**Issue by isuruf** [pypi/support#3369]
### Project URL

https://pypi.org/project/symengine/

### Does this project already exist?

- [X] Yes

### New limit

30GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

SymEngine is a fast symbolic manipulation library written in C++
and with python bindings. We have been releasing sources since 2016
and wheels since 2017.

### How large is each release?

Each release is about 1.3GB because of the 34 wheels and each wheel bundle
shared libraries from GMP, MPFR, MPC, FLINT, ARB and link statically to LLVM
libraries.

### How frequently do you make a release?

Once or twice a year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Thank you for filling out the template for this issue properly! It's appreciated! ❤️

I've bumped the limit to 30 GB as requested. Please consider looking into generating abi3 wheels (i.e. using the stable Python ABI), which would enable reduction in the number of wheels produced. :)

**Comment by isuruf** [comment]
Thanks. I'll have a look at abi3 wheels. Cython should support it right?

**Comment by pradyunsg** [comment]
Yes, I believe they added support relatively recently.
