### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by DavidHostler** [pypi/support#3370]
### PyPI Username

`david.hostler@equo.ai`

### Reason for request

This email address was deactivated for the time being, and need access to regain ability to update my code.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
No username was found for `david.hostler@equo.ai` on pypi.
