### ISSUE TITLE
PEP 541 Request: nornir-ipfabric

### ISSUE THREAD

**Issue by ghost** [pypi/support#3372]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/nornir-ipfabric

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ipf-solution-architecture

### Reasons for the request

Project has not been updated in 2+ years.  As the vendor of IP Fabric we would like to claim ownership in order to officially support this plugin and provide new features and bug fixes as they arise now that we have a development team.  Changing the name of the product will not follow the naming conventions of all other plugins listed at https://nornir.tech/nornir/plugins/.

We would like to host the code in our GitLab which enables our customers to open confidential issues in order for us to receive log files with sensitive information securely and provides the repo with our secured version control monitored by our IT department.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current: https://github.com/routetonull/nornir_ipfabric
New: https://gitlab.com/ip-fabric/integrations/nornir_ip_fabric

### Contact and additional research

We contacted the owner however after 4 months we still have not received the transfer of ownership preventing us to publish a new package for our customers.  See attached email.

[email.pdf](https://github.com/pypi/support/files/13369769/email.pdf)

---------- Forwarded message ----------
From: gp <[gp.boarina@gmail.com](mailto:gp.boarina@gmail.com)>
Date: 17 Jul 2023 at 7:44 AM +0100
To: Cristian Cordero <[cristian.cordero@ipfabric.io](mailto:cristian.cordero@ipfabric.io)>
Cc: Justin Jeffery <[justin.jeffery@ipfabric.io](mailto:justin.jeffery@ipfabric.io)>, Alexander Gittings <[alexander.gittings@ipfabric.io](mailto:alexander.gittings@ipfabric.io)>, Pete Crocker <[pete.crocker@ipfabric.io](mailto:pete.crocker@ipfabric.io)>
Subject: Re: I: IP Fabric Nornir Integration
Hello guys,
thank you for your patience, I was on vacation and then busy with a very challenging project, hence the delay in replying.

I have no objection to assigning you ownership of the pypi package, as I don't have the resources to keep it up to date. 
Do you anticipate any kind of compensation related to this transition?
 
I am pleased that this project has a future within the network automation ecosystem, I believe IP Fabric is a product that solves many problems and I am pleased to be able to make my small contribution to making it more widely known.
 
I will update my blog to inform readers of the change of ownership of the package upon completion.
 
Best regards, 

 
Gian Paolo

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Closing because noticed the issue requester is a "ghost" account X_X
