### ISSUE TITLE
PEP 541 Request: jwql

### ISSUE THREAD

**Issue by BradleySappington** [pypi/support#3384]
### Project to be claimed

`jwql`: https://pypi.org/project/jwql

### Your PyPI username

`BradSappington`: https://pypi.org/user/BradSappington

### Reasons for the request

Current repo owner https://test.pypi.org/user/bourque/ no longer has access to the email affiliated with this test.pypi account, so cannot transfer ownership.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

I will continue using the same repository:
https://github.com/spacetelescope/jwql

### Contact and additional research

We have directly contacted the current owner by text who confirmed he no longer has access to his email associated with this account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @BradleySappington,

It looks like you are the project owner for both the main PyPI and the Test.PyPI accounts. Are there any additional issues you are facing regarding this or is it okay to close?

**Comment by BradleySappington** [comment]
This is now resolved, thanks!
