### ISSUE TITLE
PEP 541 Request: bioio-tifffile

### ISSUE THREAD

**Issue by griffinfujioka** [pypi/support#3385]
### Project to be claimed

`bioio-tifffile`: https://pypi.org/project/bioio-tifffile

### Your PyPI username

`aicspypi`: https://pypi.org/user/aicspypi

### Reasons for the request

We are working on setting up Github as a trusted publisher for the bioio-tifffile, however at the "Add a new pending publisher" form [here](https://pypi.org/manage/account/publishing/) we are running into an error "This project name is already in use”. 

I am told from some of the developers on the team that `bioio-tifffile` was used as a prototype in the early days of the project, so the suspicion is we may be running into an issue because of that. 

For what it's worth, the bioio developers who are requesting the trusted publisher setup are @SeanLeRoy and @evamaxfield

![iScreen Shoter - 20231121142129919](https://github.com/pypi/support/assets/1392832/04005339-df3a-4d79-b9a1-4db42c360b78)

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/bioio-devs/bioio-tifffile

### Contact and additional research

We all have some association with Allen Institute for Cell Science: 
* @griffinfujioka 
* @SeanLeRoy
* @evamaxfield

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cgohlke** [comment]
@griffinfujioka The `bioio-tifffile` project should now be available.
