### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by austensen** [pypi/support#3390]
### PyPI Username

`m.austensen@gmail.com`

### Reason for request

I still have access to the email, and was able to do password recovery, but I don't know my username and can't log in with just email. Can you either let me know the username, or just help me to delete the account so I can create a new one? Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
no username `m.austensen@gmail.com` exists on PyPI.
