### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jessedp** [pypi/support#3393]
### PyPI Username

[jessedp]

### Reason for request

I don't remember setting up 2FA for this account (I *just* did my test.pypi one), yet I'm being asked for a TOTP code. The login screen also says my account hasn't generated recovery codes, because I don't remember doing that or saving them anywhere either.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by jessedp** [comment]
Sorry, found the recovery codes and forgot to close this.
