### ISSUE TITLE
Project Limit Request: nvidia-cudnn-cu11 - 50 GB

### ISSUE THREAD

**Issue by pluh-nv** [pypi/support#3402]
### Project URL

https://pypi.org/project/nvidia-cudnn-cu11/

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project stores the Python Wheel installer format for cuDNN: https://developer.nvidia.com/cudnn

As cuDNN continues to make monthly release, we expect the size of this project to grow in the future.

### How large is each release?

Each release is around 1400 MB. Each release contains compiled binaries of the cuDNN library for both Linux (700 MB) and Windows (700 MB). 

### How frequently do you make a release?

Roughly every month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rgommers** [comment]
> Each release is around 1400 MB. Each release contains compiled binaries of the cuDNN library for both Linux (700 MB) and Windows (700 MB).

Hi @pluh-nv, you are currently using only on the order of 5 GB of space, and if it grows by 1.4 GB/month, your 100 GB request here covers 6 years of needs. That seems a bit over the top - please consider a more modest size request. Based on what I've seen approved for large packages with GPU content, it seems 30 GB or max 50 GB would be more reasonable.

**Comment by pluh-nv** [comment]
Hi @rgommers Noted. I've lowered the request to 50GB.

**Comment by rgommers** [comment]
Thanks. Hopefully an admin will come along and approve your request soon. It seems reasonable to me now.

**Comment by johnnynunez** [comment]
any new news?

**Comment by di** [comment]
I've set the total size limit for `nvidia-cudnn-cu11` to 50GB on PyPI.

**Comment by jhalabi-nv** [comment]
Thanks @di for following up!
