### ISSUE TITLE
h2o-pysparkling-2.4 - 15 GB

### ISSUE THREAD

**Issue by krasinski** [pypi/support#3404]
### Project URL

https://pypi.org/project/h2o-pysparkling-2.4/

### Does this project already exist?

- [X] Yes

### New limit

15

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It's an integration between Apache Spark (including pyspark) and h2o-3 (Open source machine learning engine)
Started in 2018, active for many years now.

### How large is each release?

~200MB total

### How frequently do you make a release?

once or twice a month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
Limit raised to 15GB.
