### ISSUE TITLE
Project Limit Request: bigdl-core-xe - 100 GB

### ISSUE THREAD

**Issue by Oscilloscope98** [pypi/support#3406]
### Project URL

https://pypi.org/project/bigdl-core-xe/

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`bigdl-core-xe` is providing acceleration for LLM inference on Intel GPUs. It has been active for four months.

### How large is each release?

~200MiB total

Our each release contains 3 wheels (~66MiB) for different python versions (3.9-3.11). Each wheel contains a shared library around 60MiB.

### How frequently do you make a release?

We make a release nightly for pre-released versions.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Oscilloscope98** [comment]
> > We make a release nightly for pre-released versions.
> 
> From https://github.com/pypi/support#guidelines-for-upload-limit-requests:
> 
> > Upload limits are generally denied for the following reasons:
> > 
> > * project makes nightly releases and/or is published frequently
> 
> I'm not an admin, but this request does not seem reasonable to me (in general because of nightlies, and especially as a new project with few users).
> 
> Please consider hosting your nightlies elsewhere and only publishing regular releases on PyPI. This is what a large majority of established projects (e.g., NumPy, PyTorch, JAX, SciPy, Matplotlib, etc.) with nightly builds that take up a lot of space do.

Thank you for the advise :)

**Comment by di** [comment]
Closing per the reason listed in https://github.com/pypi/support/issues/3406#issuecomment-1908004111.
