### ISSUE TITLE
PEP 541 Request: dvcx

### ISSUE THREAD

**Issue by jonburdo** [pypi/support#3409]
### Project to be claimed

`dvcx`: https://pypi.org/project/dvcx

### Your PyPI username

`jonburdo`: https://pypi.org/user/jonburdo

### Reasons for the request

The project page https://pypi.org/project/dvcx does not exist and does not appear to be registered but I am unable to register as a trusted publisher for it or push to it with twine using a token. I would like the project name `dvcx` on behalf of Iterative ( https://github.com/iterative ). We have the project `dvc` and would like `dvcx` for a separate but related project.

I suspect the reason `dvcx` is unavailable is maybe because it's so similar to `dvc`. Since we manage both projects we will make the distinction clear in our documentation and maintain responsibility for both.

On the trusted publisher form at https://pypi.org/manage/account/publishing/ I get:

> This project name is already in use

With `twine upload` I get:
```
WARNING  Error during upload. Retry with the --verbose option for more details.                                                                                                                           
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/                                                                                                                                    
         The user 'jonburdo' isn't allowed to upload to project 'dvcx'. See https://pypi.org/help/#project-name for more information.   
```

### Maintenance or replacement?

None

### Source code repositories URLs

current: There is none
new: https://github.com/iterative/dql

### Contact and additional research

No current project

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jonburdo** [comment]
It turns out that this project name was registered even though the page was empty - seemingly due to an unsuccessful upload attempt. I was able to find the project owner and figure it out.

**Comment by gattia** [comment]
@jonburdo - how did you figure out it was registered? I am looking to add a library called pymskt but I am getting the same rejections you receive. 

It looks like there is a similar pypi called pymsk (but based on your example, it seems like it shouldn't be blocking me?). If I search for pymskt on pypi, I only get mention of it in another library that I'm the owner but that is completely unrelated (https://pypi.org/search/?q=pymskt).

**Comment by jonburdo** [comment]
@gattia Unfortunately I wasn't able to get any info from PyPI itself. In my case, it turned out that someone in our organization had already registered the project name and had forgotten. They eventually realized that they had ownership of the project after I was asking around.

I think a project name could be reserved without the project showing up if someone registers a trusted publisher for the project, or possibly if someone attempts a release but it fails for some reason, but I'm not exactly sure.

**Comment by gattia** [comment]
Thanks for the feedback!
