### ISSUE TITLE
File Limit Request: insideopt-seeker - 500 MB

### ISSUE THREAD

**Issue by meinolf71** [pypi/support#3412]
### Project URL

https://pypi.org/project/insideopt-seeker/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

we provide an optimization solver and are about to hit the upload limit. We want to avoid that we cannot upload bug fixes 

### Reasons for the request

we provide an optimization solver and are about to hit the upload limit. We want to avoid that we cannot upload bug fixes 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
Your most recent release shows under 30MB per file - can you explain the need for 500MB?

https://pypi.org/project/insideopt-seeker/0.1.1/#files

**Comment by di** [comment]
Closing due to lack of response.
