### ISSUE TITLE
File Limit Request: quarchpy - 275 MB

### ISSUE THREAD

**Issue by SBQuarch** [pypi/support#3413]
### Project URL

https://pypi.org/project/quarchpy/

### Does this project already exist?

- [x] Yes

### New Limit

275MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Hello, I manage quarchpy, quarch technologies python API to our equipment that does fault injection and power testing on drives and other technologies. We use python for test automation and we ship Quarch Power Studio and Quarch Instrument Server (QPS and QIS) jars in with quarchpy. 
They have been built using java 8 and in an effort to upgrade to java 21 we have taken the parts from java 21 jre needed to run our application but we need one for each OS. windows, mac and linux based. 
A full JRE for each is around 330mb and when we packaged each in with quarchpy it totaled 1gb.
Since then we have managed to strip it down to around 60mb each. 180mb total and with quarchpy (with QPS and QIS) we reach 255mb.
The error i get when trying up upload is:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         File too large. Limit for project 'quarchpy' is 100 MB. See https://pypi.org/help/#file-size-limit for more
         information.
```

And info log passed out shows the wheel is 201mb:
dist\quarchpy-2.1.14.dev21-py2.py3-none-any.whl (201.0 MB)

### Reasons for the request

I would like to have the project size increased to the current size +10% for future development. I don't think it should grow much bigger but space for additional development should be accounted for. 
I don't know if the limit of on the project size or the wheel size so please accept my request based on either of the two measurements. 
Current size project = 250mb -> Requesting 275mb
Current size wheel 201mb -> Requesting 220mb 

This change will allow users to run our java application with j21 improvements and solve some problems users were seeing with different java versions.
Many thanks,
Stuart.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @SBQuarch :wave:
I've set the upload limit for `quarchpy` to 300 MB on PyPI only because it doesn't exist on Test PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:

**Comment by SBQuarch** [comment]
Hello @cmaureir we have done some further development on our java application and the filesize is 350mb, can I request the quarchpy project size limit be updated to 450mb.
We are looking at hosting dev releases elsewhere, so only public releases will be uploaded to pypi. This is in line with your comment of "Please be mindful of the frequency of releases at that size."
Thank you,
Stuart.
