### ISSUE TITLE
PEP 541 Request: rhubarb

### ISSUE THREAD

**Issue by Elkasitu** [pypi/support#3415]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/rhubarb

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Elkasitu

### Reasons for the request

The project `rhubarb` doesn't exist, I suppose that the reason why `twine` won't let me upload to PyPI under the name `rhubarb` is due to typosquatting (compared to e.g. `rhubarbe`, however there's several other existing projects that could be considered as typos for the same project (e.g. `rhubarb-py` and `rhubarbpy`), and the same project was seemingly [available](https://test.pypi.org/project/rhubarb/) on PyPI's test instance.

Are the typosquatting checks not performed on test PyPI?

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/RedHatProductSecurity/rhubarb

### Contact and additional research

.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @Elkasitu,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Elkasitu** [comment]
@Thespi-Brain Sorry, could you clarify which project maintainer is being reached out to?

I am not advocating for replacing any existing PyPI packages, but to have rhubarb exist alongside other packages with similar name in spite of typosquatting checks.

**Comment by Thespi-Brain** [comment]
Hi @Elkasitu,

This project does exist, but there is nothing in it, so per PEP 541 guidelines, I had reached out to the creator of this empty package informing them that this constitutes as name squatting and therefore an invalid project.

**Comment by Thespi-Brain** [comment]
**rhubarb** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 

I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Added 'Elkasitu' as 'Owner' on 'rhubarb'
