### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by C-o-m-o-n** [pypi/support#3416]
### PyPI Username

comon

### Reason for request

I have lost access to 2FA authentication app , security token and recovery codes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `comon` has valid recovery codes generated as of 2022-12-19 23:53:57.711223.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by C-o-m-o-n** [comment]
> Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
> 
> PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

I succesfully recovered my PyPI account. Thank you for the help
