### ISSUE TITLE
Project Limit Request: Jaxlib - 50 GiB

### ISSUE THREAD

**Issue by yashk2810** [pypi/support#3417]
### Project URL

https://pypi.org/project/jaxlib/

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Jaxlib is XLA library for JAX.

Every couple of releases of the jaxlib package, we need to delete the previous releases so that we have space for new releases. We archive all of our builds on GCP and store GPU builds on GCP only installable via (pip install -f).

The builds we upload on PyPI are non-cuda wheels and mac wheels and windows wheels.

Every couple of releases, we need to delete old releases because 20 GB is not enough for us anymore.

I had filed a request previously https://github.com/pypi/support/issues/1304 where you bumped the limit to 20GB but I am asking for another bump :)

### How large is each release?

1.4 GB per release

Windows wheel - 46.8 MB
Linux x86 wheel - 79.5 MB
Linux aarch64 wheel - 69.1 MB
Mac arm64 wheel - 66.3 MB
Mac x86 wheel - 84.0 MB

We release the above wheel for each python version we support which are py3.9, py3.10, py3.11, py3.12.

### How frequently do you make a release?

Roughly every month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rgommers** [comment]
Admins, it'd be great to approve this request. I believe it's valid and necessary. JAX already does whatever it can to limit the space its releases take, and the JAX team having to delete older releases from PyPI to make space for newer ones is a really bad situation. In case you don't know JAX: it's one of the most popular numerical computing and deep learning libraries.

**Comment by MichaelHudgins** [comment]
@di are you able to assist with this?  Having to delete release jaxlib packages from pypi can cause some disruption to projects depending on it?

**Comment by di** [comment]
I've set the total size limit for `jaxlib` to 50GB on PyPI.
