### ISSUE TITLE
Project Limit Request: nvidia-cublas-cu12- 30 GiB

### ISSUE THREAD

**Issue by ethanhs** [pypi/support#3420]
### Project URL

https://pypi.org/project/nvidia-cublas-cu12

### Does this project already exist?

- [X] Yes

### New limit

30GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is the Python wheel installer for cuBLAS https://developer.nvidia.com/cublas

We expect to add additional wheels for aarch64 in the coming months, so we wanted to request the size increase early on to avoid any issues.

### How large is each release?

Each wheel is 400-450MB, due to including the compiled cuBLAS binary libraries, and we expect to have at least 3 wheels going forward.

### How frequently do you make a release?

Releases are made roughly monthly.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Same here @ethanhs :wave: 
I have set `nvidia-cublas-cu12` project limit to 30GB
Cheers
