### ISSUE TITLE
PEP 541 Block Request: python-freethreading, python3-freethreading

### ISSUE THREAD

**Issue by sethmlarson** [pypi/support#3424]
### Project to be claimed

python-freethreading, python3-freethreading, nogil

### Your PyPI username

N/A

### Reasons for the request

Follow-up from https://github.com/pypi/support/issues/3350 and [this suggestion on Discourse](https://discuss.python.org/t/project-names-blocked-on-pypi-to-avoid-name-collision-for-downstream-free-threaded-python-distributions/40412/3?u=sethmlarson), these names were requested to be blocked in addition to the name `freethreading` without the `python[X]-` prefixes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
python-freethreading, python3-freethreading, nogil have been prohibited.
