### ISSUE TITLE
PEP 541 Request: getIP

### ISSUE THREAD

**Issue by alphaO4** [pypi/support#3427]
### Project to be claimed

`getIP`: https://pypi.org/project/getIP

### Your PyPI username

`AlphaO4`: https://pypi.org/user/AlphaO4

### Reasons for the request

Hello
I want to upload a package, called getIP, that will return the local or public IPv4 or IPv6. 
As per rule PEP541, the project that currently uses the name getIP seems to be project squatting. 
The first and only commit was done in 2015, which was empty. 
Also the Homepage URL is non existent, consiting of a bunch of %2A's.

With kind Regards
AlphaO4

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current Project (There is no GitHub linked): https://pypi.org/project/getip/
Replacement Project: https://github.com/alphaO4/getIP/

### Contact and additional research

While I have written the linked foxmail email, I have low confidence that the maintainer will answer. 
This is because the current foxmail.com website dosn't allow for any kind of webmail login (Both from a European IP and from a Hongkong one), and seems to only be the Download platform for a Mail-Client developt by Tencent.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @alphaO4,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by alphaO4** [comment]
Awesome! Thank you so much!

**Comment by Thespi-Brain** [comment]
**getip** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 

I recommend that the PyPI Admins release the name for future use.

**Comment by miketheman** [comment]
Added 'AlphaO4' as 'Owner' on 'getip'
