### ISSUE TITLE
File Limit Request: Factor-World - 200 MB

### ISSUE THREAD

**Issue by dtch1997** [pypi/support#3431]
### Project URL

https://test.pypi.org/project/factor-world/0.1.1/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The project contains a benchmark for investigating generalization in visual robotic manipulation. It builds on the MetaWorld repositories and implements controllable factors of variation including lighting, object positions, and object textures. 

### Reasons for the request

Part of the aim of the package is to enable environment generation with different textures. The textures consist of 228 total PNG files, which take up about 150 Mb. Currently I have implemented only 50% of the full range of visual textures in the `0.1.1` release, and would like to implement all of them in an upcoming release. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @dtch1997 :wave:
I've set the upload limit for `factor-world` to 200 MB on TestPyPI only, because it doesn't exist on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:
