### ISSUE TITLE
File Limit Request: aspose-ocr-python-java - 500 MiB

### ISSUE THREAD

**Issue by Annushka34** [pypi/support#3435]
### Project URL

https://pypi.org/project/aspose-ocr-python-java/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

It's the first official release of the Aspose.OCR library (Aspose Pty) for Python via Java project

### Reasons for the request

Our library uses neural networks, and they have a big weight. They optimized as much as it was possible. These models are the main advantage of our libraries.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Annushka34** [comment]
May I kindly request any updates on this matter, please?

**Comment by rgommers** [comment]
See https://github.com/pypi/support/issues/3250#issuecomment-1908020370.

**Comment by di** [comment]
I've set the upload limit for `aspose-ocr-python-java` to 500 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
