### ISSUE TITLE
Account recovery (or deletion) request - whichever is easier

### ISSUE THREAD

**Issue by jkollat** [pypi/support#3436]
### PyPI Username

jkollat

### Reason for request

Lost 2FA authentication codes in authenticator app due to purchase of a new device and I do not have my backup codes. I apologize for this oversight and definitely realize the important of storing these backup codes.

I'm actually just trying to take down one PyPi package that I have posted called "DiscoveryDV": https://pypi.org/project/DiscoveryDV/. **If it is simpler to just delete this package and delete my account so that I can set up a new account from scratch, this would solve my problem.**  Thank you very much for your help!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `jkollat` has valid recovery codes generated as of 2020-03-13 13:54:54.545431.

Please use those recovery codes to regain access to your account.

**Comment by jkollat** [comment]
@ewdurbin I no longer have access to the recovery codes. Are you able to just delete my account so that I can create a new one? I mostly want the https://pypi.org/project/DiscoveryDV/ project removed from PyPi because it is no longer up to date and I no longer have access to the account I used to create this project.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
