### ISSUE TITLE
Project Limit Request: ddtrace - 120 GiB

### ISSUE THREAD

**Issue by mabdinur** [pypi/support#3438]
### Project URL

https://pypi.org/project/ddtrace/

### Does this project already exist?

- [X] Yes

### New limit

120

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is the official Python APM client for Datadog.

The project has been active on PyPI since 2017.

We currently support a broad range of operating systems, and Python versions. Since we have C-extensions we try to build and publish for as many systems as we can so our customers avoid needing to install our build dependencies.

I expect the size of the wheel/binaries we build to slowly grow over time as we support new python versions and platforms.

Last year, we opened https://github.com/pypi/support/issues/2483 to increase the size limit of our package from 20GB to 60GB. We expected this increase to give us one year of runway. After 11 months and 20 days we once again reached the size limit.

### How large is each release?

Each release is ~200MB. 

#### Files sizes in ddtrace v2.3.0 (latest release)

Total Size: 173.6MB

<details>
<summary>du -sh *</summary>
<br>
<pre>
3.1M	ddtrace-2.3.0-cp310-cp310-macosx_11_0_universal2.whl
2.1M	ddtrace-2.3.0-cp310-cp310-macosx_11_0_x86_64.whl
3.9M	ddtrace-2.3.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
2.0M	ddtrace-2.3.0-cp310-cp310-manylinux_2_17_i686.manylinux2014_i686.whl
4.0M	ddtrace-2.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
3.0M	ddtrace-2.3.0-cp310-cp310-musllinux_1_1_aarch64.whl
2.5M	ddtrace-2.3.0-cp310-cp310-musllinux_1_1_i686.whl
3.1M	ddtrace-2.3.0-cp310-cp310-musllinux_1_1_x86_64.whl
2.3M	ddtrace-2.3.0-cp310-cp310-win32.whl
2.4M	ddtrace-2.3.0-cp310-cp310-win_amd64.whl
3.1M	ddtrace-2.3.0-cp311-cp311-macosx_11_0_universal2.whl
2.1M	ddtrace-2.3.0-cp311-cp311-macosx_11_0_x86_64.whl
2.0M	ddtrace-2.3.0-cp311-cp311-manylinux_2_17_i686.manylinux2014_i686.whl
4.0M	ddtrace-2.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
3.0M	ddtrace-2.3.0-cp311-cp311-musllinux_1_1_aarch64.whl
2.5M	ddtrace-2.3.0-cp311-cp311-musllinux_1_1_i686.whl
3.1M	ddtrace-2.3.0-cp311-cp311-musllinux_1_1_x86_64.whl
2.3M	ddtrace-2.3.0-cp311-cp311-win32.whl
2.4M	ddtrace-2.3.0-cp311-cp311-win_amd64.whl
3.1M	ddtrace-2.3.0-cp312-cp312-macosx_11_0_universal2.whl
2.1M	ddtrace-2.3.0-cp312-cp312-macosx_11_0_x86_64.whl
3.9M	ddtrace-2.3.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
1.9M	ddtrace-2.3.0-cp312-cp312-manylinux_2_17_i686.manylinux2014_i686.whl
4.0M	ddtrace-2.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
3.0M	ddtrace-2.3.0-cp312-cp312-musllinux_1_1_aarch64.whl
2.5M	ddtrace-2.3.0-cp312-cp312-musllinux_1_1_i686.whl
3.1M	ddtrace-2.3.0-cp312-cp312-musllinux_1_1_x86_64.whl
2.4M	ddtrace-2.3.0-cp312-cp312-win_amd64.whl
2.1M	ddtrace-2.3.0-cp37-cp37m-macosx_11_0_x86_64.whl
3.9M	ddtrace-2.3.0-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
2.0M	ddtrace-2.3.0-cp37-cp37m-manylinux_2_17_i686.manylinux2014_i686.whl
4.0M	ddtrace-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
3.0M	ddtrace-2.3.0-cp37-cp37m-musllinux_1_1_aarch64.whl
2.5M	ddtrace-2.3.0-cp37-cp37m-musllinux_1_1_i686.whl
3.1M	ddtrace-2.3.0-cp37-cp37m-musllinux_1_1_x86_64.whl
2.2M	ddtrace-2.3.0-cp37-cp37m-win32.whl
2.4M	ddtrace-2.3.0-cp37-cp37m-win_amd64.whl
3.1M	ddtrace-2.3.0-cp38-cp38-macosx_11_0_universal2.whl
2.1M	ddtrace-2.3.0-cp38-cp38-macosx_11_0_x86_64.whl
3.9M	ddtrace-2.3.0-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
2.0M	ddtrace-2.3.0-cp38-cp38-manylinux_2_17_i686.manylinux2014_i686.whl
4.0M	ddtrace-2.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
3.0M	ddtrace-2.3.0-cp38-cp38-musllinux_1_1_aarch64.whl
2.5M	ddtrace-2.3.0-cp38-cp38-musllinux_1_1_i686.whl
3.1M	ddtrace-2.3.0-cp38-cp38-musllinux_1_1_x86_64.whl
2.3M	ddtrace-2.3.0-cp38-cp38-win32.whl
2.4M	ddtrace-2.3.0-cp38-cp38-win_amd64.whl
3.1M	ddtrace-2.3.0-cp39-cp39-macosx_11_0_universal2.whl
2.1M	ddtrace-2.3.0-cp39-cp39-macosx_11_0_x86_64.whl
3.9M	ddtrace-2.3.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
2.0M	ddtrace-2.3.0-cp39-cp39-manylinux_2_17_i686.manylinux2014_i686.whl
4.0M	ddtrace-2.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
3.0M	ddtrace-2.3.0-cp39-cp39-musllinux_1_1_aarch64.whl
2.5M	ddtrace-2.3.0-cp39-cp39-musllinux_1_1_i686.whl
3.1M	ddtrace-2.3.0-cp39-cp39-musllinux_1_1_x86_64.whl
2.3M	ddtrace-2.3.0-cp39-cp39-win32.whl
2.4M	ddtrace-2.3.0-cp39-cp39-win_amd64.whl
6.4M	ddtrace-2.3.0.tar.gz
</pre>
</details>

We vendor a few dependencies and have a few data files, but the bulk of our package is pre-built binaries specifically for our code.

### How frequently do you make a release?

At ~200MB per release an increase to 120GB would buy us about a year of space. We are currently looking into strategies to avoid frequently asking for package limit increases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
Limit increased on PyPI.

**Comment by brettlangdon** [comment]
@miketheman thank you for the quick response!
