### ISSUE TITLE
File Limit Request: aspose-ocr-python-cpp - 500 MiB

### ISSUE THREAD

**Issue by figor0** [pypi/support#3441]
### Project URL

https://pypi.org/project/aspose-ocr-python-cpp/0.0.0/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

https://products.aspose.com/ocr/cpp/
The new project will be the result of porting C++ to Python.

### Reasons for the request

Our library uses neural networks, and they have a big weight. They optimized as much as it was possible. These models are the main advantage of our libraries.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rgommers** [comment]
See https://github.com/pypi/support/issues/3250#issuecomment-1908020370.

**Comment by di** [comment]
I've set the upload limit for `aspose-ocr-python-cpp` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size.
