### ISSUE TITLE
File Limit Request: lingua-language-detector - 200 MiB

### ISSUE THREAD

**Issue by pemistahl** [pypi/support#3442]
### Project URL

https://pypi.org/project/lingua-language-detector/

### Does this project already exist?

- [X] Yes

### New Limit

200 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Hi, my project is a natural language identification library. It bundles somewhat large pre-trained models which allow for a much better identification accuracy than comparable libraries. The models are currently stored as Brotli-compressed json files which is the best data compression ratio I could find. Every other combination of data format and compression method produce even bigger files. The wheel size for the current release is around 75 megabytes with support for 75 languages.

### Reasons for the request

I'm planning to add support for more languages to the library. If I do so, this will increase the file size significantly and hit the 100 MiB limit quickly. That is why I kindly ask you to please increase the file size limit to 200 MiB. This new limit would be sufficient for a pretty long time.

Thank you very much in advance.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @pemistahl :wave:
I've set the upload limit for `lingua-language-detector` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:

**Comment by pemistahl** [comment]
Awesome! :) Thanks a lot, @cmaureir. Have a nice weekend, too, and a good start into the new year.
