### ISSUE TITLE
File Limit Request: Omnitux - 200 MB

### ISSUE THREAD

**Issue by dododevs** [pypi/support#3443]
### Project URL

https://test.pypi.org/project/Omnitux/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The project is a port of an old game for educational purposes. It was written for Python 2 and is no longer maintained by the original developers. The original project page is available [here](https://omnitux.sourceforge.net/index.en.php). This port is not endorsed by the original developers, but instead by the [FUSS project](https://fuss.bz.it/), alongside which it has been used for years in support of kids' education and which would like to further provide the possibility to install it and use it.
PyPi has been chosen over other distribution means, as it can easily be used on multiple platforms and automatically manages dependencies. The game bundles examples and game data (images as jpg, sounds as mp3 and others) which must be provided in the same package.

### Reasons for the request

The bundle size is not expected to grow in the future. Game data shall be contained in a single package as post-installation retrieval would require deeper restructuring of the code and independent data hosting, which are not (at this time) feasible.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dododevs** [comment]
Hi! Any news on this? Thank you :)

**Comment by cmaureir** [comment]
Hey @dododevs :wave:
Thanks for the detailed report.

The project doesn't exist on PyPI, only on Test PyPI, so I have updated the file limit only on Test PyPI to 200MB. In case you want it on PyPI, please open a new request.
Have a nice weekend :tada:
