### ISSUE TITLE
Project Limit Request: lingua-language-detector - 20 GiB

### ISSUE THREAD

**Issue by pemistahl** [pypi/support#3444]
### Project URL

https://pypi.org/project/lingua-language-detector/

### Does this project already exist?

- [X] Yes

### New limit

20 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Hi, my project is a natural language identification library. It bundles somewhat large pre-trained models which allow for a much better identification accuracy than comparable libraries. The project started as a pure Python implementation but since version 2.0.0 I provide Python extension modules for the [Rust implementation](https://github.com/pemistahl/lingua-rs) of my library because it is much faster and consumes less memory.

I'm currently providing extension modules for CPython >= 3.8 and for PyPy >= 3.8. A single release currently consumes 3.7 GiB on PyPI which will hit the project size limit quickly. That's why I have yanked the releases 2.0.0 and 2.0.1 and only provide wheels for the current release 2.0.2. I could drop support for CPython 3.8 and PyPy 3.8 which would save 1 GB. Dropping wheels for 32bit architectures would save another 825 MiB. But the project size problem persists.

### How large is each release?

~ 3.7 GiB total

- 24 wheels for Linux at ~75 MiB (i686, aarch64, x86_64)
- 16 wheels for MacOS at ~75 MiB (arm64, x86_64)
- 10 wheels for Windows at ~75 MiB (win32, amd64)

### How frequently do you make a release?

That depends on the project size limit I'm granted. I'm planning to make releases with support for new languages. I think a new major release every two or three months is realistic. Minor releases for bug fixes would probably occur more often but then I would probably yank older minor releases after a period of time and then remove the wheel files from PyPI. But the space on PyPI should suffice to hold at least three or four major releases so that users of my library do not become annoyed if I have to yank previous releases quickly due to the project size limit.

Thank you very much in advance.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @pemistahl :wave:
I have set the project limit to 20GB, cheers!

**Comment by pemistahl** [comment]
Awesome! :) Thanks a lot, @cmaureir.
