### ISSUE TITLE
Project Limit Request: nucliadb-node-binding - 20 GB

### ISSUE THREAD

**Issue by vangheem** [pypi/support#3445]
### Project URL

https://pypi.org/project/nucliadb-node-binding/

### Does this project already exist?

- [X] Yes

### New limit

20GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

NucliaDB is an open source AI Search database. This pypi project is the python bindings to the rust component of this project.

We will work on pruning older versions as well as providing less builds on platforms in order to preserve disk usage; however, it would be helpful to have a little more space.

### How large is each release?

Each wheel is ~6-12mb

but we release to around 18 platforms

### How frequently do you make a release?

It depends. It can be multiple times a week but some weeks nothing.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @vangheem :wave:
I've set the project limit for `nucliadb-node-binding` to 20 GB on PyPI.
Have a nice weekend :tada:
