### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tylere** [pypi/support#3446]
### PyPI Username

`Tyler.Erickson`

### Reason for request

I have lost access to my previous work email address (tylere@google.com). The account associated with this email is the sole owner of the project [earthengine-jupyter](https://pypi.org/project/earthengine-jupyter/).

I would like to transfer ownership of this project [earthengine-jupyter](https://pypi.org/project/earthengine-jupyter/) to my personal email address (tylerickson@gmail.com) and PyPI account (`Tyler.Erickson`). The four maintainer accounts for the project should remain unchanged. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by sgreenberg** [comment]
Hello - I lead Earth Engine's Developer Relations team; Tyler was previously part of our team when he owned the tylere@google.com email address. We support this transition. Please let me know what we can do to help make it happen. Thank you!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by tylere** [comment]
The account recovery procedure didn't resolve the original reason for the request... I am unable to access the project [earthengine-jupyter](https://pypi.org/project/earthengine-jupyter/) because of have lost access to my previous work email. Can the ownership be transferred to my personal account (Tyler.Erickson)? Alternatively, could one or more of the maintainers be promoted to project owner?

**Comment by ewdurbin** [comment]
You'll need to file a project name request regarding project ownership roles.
