### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by aurynn** [pypi/support#3448]
### PyPI Username

`aurynn`

### Reason for request

I left the company I was working for at the time I made this account, well over a decade ago at this point, and, for obvious reasons, I can't exactly get access to the recovery emails.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by aurynn** [comment]
Oh, sorry, I missed this reply. Have sent email. Thank you!

**Comment by ewdurbin** [comment]
Primary email address updated and password reset issued. Please proceed with the password reset, verify your new primary email address, and you should be good to go.
