### ISSUE TITLE
Name block request: example-package-YOUR-USERNAME-HERE

### ISSUE THREAD

**Issue by jeanas** [pypi/support#3453]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/example-package-your-username-here

### Your PyPI username

`USER_NAME`: https://pypi.org/user/jeanas

### Reasons for the request

The PUG's [tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/) uses this name. Obviously, the intent is that `YOUR-USERNAME-HERE` should be replaced, but it's easy to forget that while trying to do things quickly, or to misunderstand it if you're not a native English speaker. If I registered this package on PyPI or TestPyPI, I'm sure it would get downloads. I think this name should be blocked.

### Maintenance or replacement?

None

### Source code repositories URLs

N/A

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @jeanas,

It looks like someone has already taken this name as a project name but since it's empty, it is considered to be name squatting. We have reached out to this user and have sent them a courtesy message.

**Comment by Thespi-Brain** [comment]
**example-package-YOUR-USERNAME-HERE** has been deemed invalid. Additionally, many attempts have been made to reach out to the owner, but no valid contact info was found. Owner has also not been recently active.

I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Prohibited Project Name 'example-package-your-username-here'
