### ISSUE TITLE
PEP 541 Request: gradunwarp (Fedora reservation)

### ISSUE THREAD

**Issue by effigies** [pypi/support#3455]
### Project to be claimed

`gradunwarp`: https://pypi.org/project/gradunwarp

### Your PyPI username

`cjmarkie`: https://pypi.org/user/cjmarkie

### Reasons for the request

gradunwarp is a long-standing Python package that has existed as a git repository and not pushed to PyPI: https://github.com/Washington-University/gradunwarp

I have been helping  them update their builds so that they can push wheels (https://github.com/Washington-University/gradunwarp/pull/15) and make the installation process simpler for users. After setting up the infrastructure, they have released (https://github.com/Washington-University/gradunwarp/releases/tag/1.2.2), but I have found that we cannot push to PyPI because the name is reserved.

In #355 @encukou, reserved this for gradunwarp to avoid conflicts with Fedora. Looking at https://packages.fedoraproject.org/pkgs/python-gradunwarp/python3-gradunwarp/index.html, this is the same package. I request that the package be unblocked, and I can upload the generated packages.

I'm happy to make @encukou an admin so he can ensure that this is not done in a way that conflicts with Fedora packaging.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/Washington-University/gradunwarp

### Contact and additional research

The current owners are responsive on their repository, but they maintain this package as part of a larger pipeline, and primarily work in C. They have been willing to accept help in this matter. cc @coalsont, I don't know if you have a PyPI account, but I think it would be sensible for you to be an admin on the package.

I am a maintainer of several neuroimaging Python packages, and have been helping them here.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
This is indeed the same gradunwarp as in Fedora, and I see that many infrastructure-related commits from @effigies have been merged to it.
@di, could you please release the name?

---

> I'm happy to make @encukou an admin

Thanks for the offer, but I'll pass, as I don't know the software. My main concern is that the gradunwarp name isn't used for an unrelated new project. New versions are fine, even if they pose challenges for Fedora :)

**Comment by effigies** [comment]
@di Just a bump in case this fell through the cracks. I'm not in a rush, but just saw another PEP 541 request and it reminded me to check on the status of this one.

**Comment by effigies** [comment]
@ewdurbin It looks like you performed the blacklisting in https://github.com/pypi/support/issues/355#issuecomment-621834283. Are you able to release the name?

Apologies if this is pestering, but it looks like this project is going to be making another release soon, so I would like to make sure the package infrastructure is ready when they do.

**Comment by effigies** [comment]
@encukou Not really sure what to do here. It seems that your sign-off was what was needed, but the backlog here is so high that mentions aren't reaching the people with access. Would it make sense to post to https://discuss.python.org/, or would that be bad form?

**Comment by encukou** [comment]
Unfortunately, [the discussion is stuck there as well](https://discuss.python.org/t/pypi-account-recovery-process-triaging-on-halt/43422).
I feel powerless.

**Comment by effigies** [comment]
@di Can I ping you on this? I see some other Fedora reservations were released since I opened this.

**Comment by Thespi-Brain** [comment]
Recommending PyPI admins release the name to @effigies due to prior history.

**Comment by miketheman** [comment]
'gradunwarp' released to 'cjmarkie'.

**Comment by effigies** [comment]
Thanks @miketheman!
