### ISSUE TITLE
Lost two factor authentication application, device, and recovery codes

### ISSUE THREAD

**Issue by mdily** [pypi/support#3456]
### PyPI Username

qi.sun

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `qi.sun` has valid recovery codes generated as of 2023-11-13 07:05:32.998677.

Please use those recovery codes to regain access to your account.

**Comment by mdily** [comment]
the recovery code has used and I forgot those recovery codes

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
