### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by infinitewarp** [pypi/support#3459]
### PyPI Username

doppler_dev

### Reason for request

Lost access to email address.

I need access to whatever account currently owns the project `drf-insights-pagination` (https://pypi.org/project/drf-insights-pagination/). I don't know if `doppler_dev` is the correct PyPI username here; but `doppler_dev@redhat.com` does successfully trigger the `Reset email sent` message. This account was registered by a former Red Hat employee, and we do not have access to the credentials they used for this account.

Unfortunately, Red Hat's email system changed since this PyPI account was registered several years ago, and `doppler_dev@redhat.com` is no longer a valid address, but `doppler-dev@redhat.com` is valid. Note the `-` instead of `_` in the name. The working `doppler-dev@redhat.com` email (with the `-`) is already listed as the `drf-insights-pagination`'s public author address.

I have access to `doppler-dev@redhat.com`, and if a sysadmin here wants to use that to verify my identity, I can reply from my own Red Hat email address. Thanks in advance!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
email address was updated with -, please proceed with password reset to complete recovery.
