### ISSUE TITLE
Project Limit Request: semgrep - 50 GB

### ISSUE THREAD

**Issue by amchiclet** [pypi/support#3464]
### Project URL

https://pypi.org/project/semgrep/

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Semgrep is a code analysis tool that is widely used to helps users detect security bugs. (https://github.com/semgrep/semgrep)

It has been active since 2020. We are continuing to grow and still have users using older versions of the tool.

Our most recent release size total was ~170MB. As we support more architectures and add more functionality to the product, we expect the release sizes to be increased in the future.

### How large is each release?

As of the most recent version
* ~170 MB total
  * Source ~34MB
  * Binary
    * Linux aarc64 ~37MB
    * MacOSX arm64 ~34MB
    * MacOSX X86_64 ~29MB
    * Any ~35MB

We build a native binary for each architecture and ship it with the Python wheels.

### How frequently do you make a release?

We release once a week.

Assuming the release size grows up to ~300MB per release as we support more architectures. Then an additional 15GB would give us another year. We are asking for an additional 35GB to cover at least 2 years with some wiggle room.

We will also discuss how to reduce the release size as well.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by underyx** [comment]
Note semgrep has 'critical project' designation:

![CleanShot 2023-12-21 at 11 42 20@2x](https://github.com/pypi/support/assets/1060436/c8614354-e346-4fbb-b90d-d1d5df1123fc)

**Comment by cmaureir** [comment]
Hey @amchiclet :wave:
I've set the project limit for `semgrep` to 50 GB on PyPI.
Have a nice weekend :tada:
