### ISSUE TITLE
File Limit Request: cognica-server - 200 MB

### ISSUE THREAD

**Issue by cozyhous** [pypi/support#3468]
### Project URL

https://pypi.org/project/cognica-server/

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Cognica is a versatile OLTP database capable of storing and retrieving Key-Value, Document, Time Series, and Vector Data. It is designed to be easily installed and operate smoothly within a Python environment, with a package that is structured for lightweight operation.

### Reasons for the request

Various tokenizers were needed for full-text search, and BLAS libraries for high-speed operations in vector search, as well as dependencies like Kafka for CDC (Capture Data Change) to configure the DBMS. Efforts were made to minimize dependencies to reduce storage capacity, transmission costs, and time, aiming to lighten the package. However, reducing it to below 100MB was not easy.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @cozyhous :wave:
I've set the upload limit for `cognica-server` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:
