### ISSUE TITLE
File Limit Request: intel-extension-for-transformers - 130 MB

### ISSUE THREAD

**Issue by VincyZhang** [pypi/support#3470]
### Project URL

https://pypi.org/project/intel-extension-for-transformers

### Does this project already exist?

- [X] Yes

### New Limit

130

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Intel® Extension for Transformers is an innovative toolkit to accelerate Transformer-based models, especially for Large Language Models (LLMs). We have made effort to reduce the size, but we can't manage to reduce it to 100MB per each file.

### Reasons for the request

This is a major release of our project, we really need to guarantee the functionality of the project. And we expect our release sizes/total project size to increase in the future

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @VincyZhang :wave:
I've set the upload limit for `intel-extension-for-transformers` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:
