### ISSUE TITLE
File Limit Request: bio-mate - 300 MB

### ISSUE THREAD

**Issue by yulitao-byte** [pypi/support#3479]
### Project URL

https://test.pypi.org/project/bio-mate/

### Does this project already exist?

- [X] Yes

### New Limit

300 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

bio-mate is a JupyterLab extension for bioinformatics.
It was open source on GitHub at Oct 19 2023.

### Reasons for the request

Recently the project integrated many graph-making tools(20+). And some tools have built-in sample data files, some have helper font files which are around 20~40MiB. After inspecting these helper files, I think those are necessary for the users, and they can't be simply removed.

So I request an additional limit(300MiB, the file is 145MiB for pending 0.3.0). Thanks for your reading.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @yulitao-byte :wave:
I've set the upload limit for `bio-mate` to 300 MB on TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:
