### ISSUE TITLE
Project Limit Request: Aspose PDF Python Via Cpp darwin arm64 - 0.5 GiB

### ISSUE THREAD

**Issue by rteliuk** [pypi/support#3483]
### Project URL

https://pypi.org/project/Aspose-PDF-Python-Via-Cpp-darwin-arm64/

### Does this project already exist?

- [X] Yes

### New limit

0.5 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It's the first official release of the Aspose PDF Python Via Cpp

### How large is each release?

~200Mb total for each platforms (Windows x64, Linux x64, MacOSX i386 and MacOSX arm64)

### How frequently do you make a release?

~ 1 release per month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rgommers** [comment]
Please close this (see https://github.com/pypi/support/issues/3484#issuecomment-1907949309 for why).
