### ISSUE TITLE
Project Limit Request: Aspose PDF Python Via Cpp darwin x86-64 - 0.5 GiB

### ISSUE THREAD

**Issue by rteliuk** [pypi/support#3484]
### Project URL

https://pypi.org/project/Aspose-PDF-Python-Via-Cpp-darwin-x86-64/

### Does this project already exist?

- [X] Yes

### New limit

0.5 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It's the first official release of the Aspose PDF Python Via Cpp

### How large is each release?

~200Mb total for each platforms (Windows x64, Linux x64, MacOSX i386 and MacOSX arm64)

### How frequently do you make a release?

~ 1 release per month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @rteliuk :wave:
Is there any reason you created projects per platform rather than just have 'Aspose-PDF-Python-Via-Cpp' ?
maybe to avoid the project limit with all your releases? same question apply for https://github.com/pypi/support/issues/3483 https://github.com/pypi/support/issues/3482 and  https://github.com/pypi/support/issues/3481

Side note: I tried a few links from your README, like https://products.aspose.com/pdf/python-cpp/ and they don't seem to work. Do you have an updated URL for the project?

**Comment by rteliuk** [comment]
Hello @cmaureir,
Sorry for the delay with the answer.

We split the packages for the 4 platforms (Windows/Linux/MacOSX(x86-64)/MacOSX(arm64)) because all of them contain the binary modules and we decided that for example, the end user for Windows does not need to have binaries for the other platforms and vise versa.
Also, it will make the package more lightweight for loading via the network.

Regarding the incomplete page on the links from README, it was updated, all other links will be also updated soon.

Thank you.

**Comment by rteliuk** [comment]
@cmaureir Hi Cristián, 
Sorry for disturbing you.
Please process our request, when you will have time for that.
Thank you.

**Comment by rgommers** [comment]
> We split the packages for the 4 platforms (Windows/Linux/MacOSX(x86-64)/MacOSX(arm64)) because all of them contain the binary modules and we decided that the end user for Windows does not need to have binaries for the other platforms and vise versa.

@rteliuk I'm afraid you are using wheels in an incorrect way. The filename on https://pypi.org/project/Aspose-PDF-Python-Via-Cpp-darwin-x86-64/1.0/#files ends in `py3-none-any.whl`. Those `none-any` tags have to do with the content of your binary - you should put `x64_64` in there, and not in the project name.

I recommend that you do the following:
1. close all four of your limit requests on this issue tracker
2. assess how reasonable it is to distribute your closed-source commercial product on PyPI to begin with (my guess is: not so much)

If you do want to continue here after step 2, then:

3. learn about how binary wheels work,
4. choose a new project name, and upload all of your platform-specific wheels there
5. once things are in good shape, open a new limit request with as much detail as possible
