### ISSUE TITLE
Upload Limit Request: Data-studio - 200 mb

### ISSUE THREAD

**Issue by shreesha-j** [pypi/support#3485]
### Project URL

https://pypi.org/manage/projects/data-studio

### Does this project already exist?

- [X] Yes

### New limit

200mb

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

the project is about the annotation tool

### How large is each release?

it is 100 mb 

### How frequently do you make a release?

not that frequently

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @shreesha-j  there is an inconsistency with the title and the body of your request.
The default project limit is 10GB and the file limit is 100MB. On the title you ask for a project limit of 500M and in the body for a 200MB. 
Do you mean perhaps for a file size of 200?

**Comment by shreesha-j** [comment]
Yes my file size exceeded the 100 mb limit I need to be more that 100 mb

**Comment by shreesha-j** [comment]
200 mb for the file size will be the best

**Comment by shreesha-j** [comment]
any update

**Comment by cmaureir** [comment]
Hey @shreesha-j I have raised the upload limit for `data-studio` to 200MB. Please be mindful with frequent releases at that size.
Cheers!

**Comment by shreesha-j** [comment]
Thanks a lot.
