### ISSUE TITLE
Project Limit Request: maria - 1 GB

### ISSUE THREAD

**Issue by thomaswmorris** [pypi/support#3491]
### Project URL

https://pypi.org/project/maria/

### Does this project already exist?

- [X] Yes

### New limit

1 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a simulator for radio telescopes being developed by the European Southern Observatory (ESO), to help with forecasting and designing observations. It has been active for around a year. The current file size is 105 MB and may get larger in the future as we add more functionality, but should stay under a GB. 

### How large is each release?

Slightly over 100MB at the moment. Most of this is in binary files that store weather data, atmospheric spectra, astronomical data, etc. for different observatories across the world. The files have been downsampled and compressed as much as possible. 

### How frequently do you make a release?

The code is fairly stable now, so not more than once a month. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @thomaswmorris the default file upload size is 100MB, and the default project size is 10GB, so you shouldn't have a problem, but it might be that this is more related to the package size? Could you please clarify is you refer to that one.
Thanks!

**Comment by thomaswmorris** [comment]
> Hey @thomaswmorris the default file upload size is 100MB, and the default project size is 10GB, so you shouldn't have a problem, but it might be that this is more related to the package size? Could you please clarify is you refer to that one. Thanks!

Oops, yes I meant the package size; the binary is over 100MB. How could I increase the size limit?

**Comment by cmaureir** [comment]
Hey @thomaswmorris sorry, but I couldn't understand your answer.
I asked if you meant the "package size" and you said yes, meaning the request is 1GB for a package, but later you said "the binary is over 100MB" is that 1000MB maybe and not 100 ? if that's the case, I'd say that you'd need to find a different strategies in order to ship a 1GB wheel, could it be possible to split maybe? this is mainly motivated that because the project limit is 10G, you will be unable to have more than 10 releases.

**Comment by di** [comment]
I've set the upload limit for `maria` to 200 MB on PyPI. I think that's what you need -- if you exceed this in the future, we are happy to revisit.
