### ISSUE TITLE
Project Limit Request: lxml - 25 GB

### ISSUE THREAD

**Issue by scoder** [pypi/support#3494]
### Project URL

https://pypi.org/project/lxml/

### Does this project already exist?

- [X] Yes

### New limit

25

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

lxml has long been one of the most downloaded packages on PyPI and is widely used in the web and data world, both manually and as an important dependency in many applications. You've probably heard of it.

I'm considering to add more platform targets for binary wheels, which would increase the size of a release even further.

### How large is each release?

Each release is about 500MiB these days, each of the ~100 binary wheels 4-8MiB. The binary wheels bundle relatively large external C libraries so that users don't have to install them manually on their side (or live with outdated versions).

I have deleted older pre-releases but the size per release has only become large in later years with the improved platform support for binary wheels, so deleting older releases won't help much.

I've also noticed that it's real work to bulk-delete alpha-releases, for example. Deleting only the released files (or some of them) is practically impossible through the web interface. Even deleting one release at a time and confirming the deletion is really cumbersome. I understand why that is, but in combination with the per-project size limit, it's a real annoyance.

### How frequently do you make a release?

Irregularly, 3-10 times a year. 15GiB more space should last for another 4-5 years, at which point deleting older releases is probably a relevant option (and has hopefully become easier to do by then).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by scoder** [comment]
I made two new releases since I posted this request. The preceding one had already failed during the wheel upload, which then made me send this request. The next one failed as well, again with an incomplete wheel upload, and I didn't upload the last one at all, knowing ahead of time that it wouldn't work either. It's now left as an "unofficial" non-PyPI release.

The fact that maintainers are highly likely to run into the size limits at a point where their users see an incomplete release already, thus leading to build failures world-wide, seems unnecessarily disruptive. I'm sure there's a better way to impose limits than deliberately breaking the world.

**Comment by cmaureir** [comment]
Hello @scoder :wave:
I have set the project limit for `lxml` to 25GB.

I agree that some other changes can be made, either to PyPI's interface, to somehow notify that the project limit is being reached, or even with a warning from `twine` if the total upload size is going over the current limit could be a good idea, but I'm not certain how easy those changes could be made.

I'm trying to react as fast as I can wrt project/file limit requests, it's unfortunate you had partial releases, I hope you can somehow fix them now that the project has a new limit.

**Comment by scoder** [comment]
Thank you!
