### ISSUE TITLE
Project Limit Request: Pygame-CE - 20 GB

### ISSUE THREAD

**Issue by MyreMylar** [pypi/support#3497]
### Project URL

https://pypi.org/project/pygame-ce/

### Does this project already exist?

- [X] Yes

### New limit

20GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a a fork of pygame made after the owner of the pygame pypi name banned all the other active pygame contributors. It effectively is the version of pygame that is kept up to date - but we don't own the name on PyPI.

We have been up and running for a year now, and as you can see from us hitting the size limit have made many releases in that time. It would be nice to be able to support a history of older releases for older versions of python and for tracking down regressions in functionality. It also seems likely to me that original upstream pygame does not have the 10GB limit.

### How large is each release?

~850MB

This size per release is just because we have to support so many different platform distributions with C extensions & dependencies (SDL etc).

Now we've discovered this limit (midway through a release) that we were previously unaware of we're going to go back and delete some of the old dev releases that are less important. 

### How frequently do you make a release?

About every three months for a public release. We also do more frequent developer releases, usually one or two between each major release.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by MyreMylar** [comment]
I have lowered the limit increase request in the hope that might make it easier to grant.

**Comment by Starbuck5** [comment]
We've now had to delete two of our dev releases to make way for new releases, which sucks. It feels like deleting part of our history. Users could've pinned them and been using them.

**Comment by di** [comment]
I've set the total size limit for `pygame-ce` to 20GB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by Starbuck5** [comment]
Thank you Dustin!
