### ISSUE TITLE
File Limit Request: AeroSCOPE - 300 MB

### ISSUE THREAD

**Issue by ScottDelbecq** [pypi/support#3502]
### Project URL

https://pypi.org/project/aeroscope/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

AeroSCOPE provides a tool to explore a compiled dataset of aviation fuel consumption and emissions.

### Reasons for the request

At the moment we have to reduce the dataset to large aircraft and their associated routes. Increasing the package size limit to 300 MB would enable us to include all aircraft and routes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @ScottDelbecq :wave:
I've set the upload limit for `aeroscope` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
