### ISSUE TITLE
File Limit Request: openspg-knext - 300 MB

### ISSUE THREAD

**Issue by baifuyu** [pypi/support#3506]
### Project URL

https://pypi.org/project/openspg-knext

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Dear PyPI developers,

We are currently open-sourcing a Knowledge Graph project, with the GitHub repository accessible at https://github.com/OpenSPG/openspg. Our server-side is developed in Java, while the client-side is written in Python. It is necessary for us to integrate a knowledge construction engine as well as a knowledge reasoning engine on the client side, which has led us to include a JAR file within our PyPI package. Consequently, our package size has surpassed the 100 MB limit.

We kindly request a temporary size increase to 300 MB for our package. We plan to store these JAR files using alternative methods in the future and not include them in the PyPI package. We are very grateful and look forward to your response.

### Reasons for the request

We plan to store these JAR files using alternative methods in the future and not include them in the PyPI package. We are very grateful and look forward to your response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @baifuyu :wave:
I've set the upload limit for `openspg-knext` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
