### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jvdev15** [pypi/support#3507]
### PyPI Username

`Lauterbach`

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by jvdev15** [comment]
2FA device and recovery codes were lost.

**Comment by ewdurbin** [comment]
User `Lauterbach` has valid recovery codes generated as of 2023-03-21 15:53:35.510399.

Please use those recovery codes to regain access to your account.

**Comment by jvdev15** [comment]
Hello ewdurbin,

the recovery codes were lost too due to an oversight. Any way we can reset everything by using the associated E-Mail?

**Comment by jvdev15** [comment]
@ewdurbin Is it possible to reset the account using the associated E-Mail?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
