### ISSUE TITLE
Project Limit Request: Panda3D - 100 GB

### ISSUE THREAD

**Issue by rdb** [pypi/support#3508]
### Project URL

https://pypi.org/project/Panda3D
https://www.panda3d.org/
https://github.com/panda3d/panda3d/

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Panda3D is a C++ game engine with Python bindings that has a history dating back to the early 90s but has been open-source since 2002. It is the most well-known and popular 3D game engine using Python, and has been used in a number of commercial games, notably Disney's Pirates of the Caribbean Online, but is also used for visualisation and simulation. It is a large project because it has many features and contains various supporting tools, with support for a broad range of platforms and Python versions.

So far I have dealt with the size limit by deleting older releases, particularly less stable ones, but this is not preferred as users may be relying on those older releases.

### How large is each release?

50-60 MiB per wheel (macOS is twice as much), about 75 wheels per release because the stable ABI is not sufficient for our needs.

The distribution includes the files and libraries needed to import the extension libraries, alongside some command-line tools that are useful for developing simulations and games using the engine.

We are working on reducing the size of the main distribution for future versions, by dropping support for older Python versions, and splitting off some included tools into a separate project.

### How frequently do you make a release?

1-4x per year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total size limit for `Panda3d` to 60GB (up from 30GB) on PyPI. Feel free to file a new issue if/when you reach this limit again.
