### ISSUE TITLE
File Limit Request: IronPdf - 135 MB

### ISSUE THREAD

**Issue by djrecipe** [pypi/support#3510]
### Project URL

https://pypi.org/project/IronPdf/

### Does this project already exist?

- [X] Yes

### New Limit

135

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

IronPdf is a commercial PDF editing and HTML to PDF solution.

https://ironpdf.com/

We have a bunch of NuGet downloads.

### Reasons for the request

IronPdf uses CEF (aka Chrome) to accomplish HTML to PDF. Including all of the native assemblies for a given platform means we need approximately 135MB per wheel file.

Currently we just upload a wheel file which requires runtimes to be downloaded on first time the library was imported. It would be nice if we could upload wheel files which already include the native dependencies.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @djrecipe :wave:
I've set the upload limit for `ironpdf` to 150 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!

**Comment by djrecipe** [comment]
@cmaureir woo-hoo!
