### ISSUE TITLE
PEP 541 Request: glmnetpy

### ISSUE THREAD

**Issue by jonathan-taylor** [pypi/support#3513]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/glmnetpy

### Your PyPI username

`USER_NAME`: https://pypi.org/user/jetaylor74

### Reasons for the request

This package name does not seem to be used on `pypi`.

This package is a wrapper written (along with myself) original authors of popular R package `glmnet`. There are already two existing packages on pypi with `glmnet` in the name (none by original authors).

This request is being made in advance of a subsequent release of a Python package that has near identical functionality with the R package (of which two existing packages do not).

Authors of R package do not support or endorse either `glmnet` or `pyglmnet`.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/jonathan-taylor/glmnetpy

### Contact and additional research

I don't see this package on `pypi` so there are no owners.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jonathan-taylor** [comment]
Wondering if there is something on this end I have to do to get this moving. Maybe I didn't fill out enough of the forms?

**Comment by Thespi-Brain** [comment]
Hi @jonathan-taylor,

It looks like there is another [package](https://pypi.org/project/glmnet-py/) with the exact name (and very similar functionality) to your package which is why unfortunately, your request can't be granted.
