### ISSUE TITLE
PEP 541 Request: pyRdfa3

### ISSUE THREAD

**Issue by prrvchr** [pypi/support#3516]
### Project to be claimed

`pyRdfa3`: https://pypi.org/project/pyRdfa3

### Your PyPI username

`prrvchr`: https://pypi.org/user/prrvchr

### Reasons for the request

Hi,
I would like to maintain the pyPdf3 package which is no longer maintained. I contacted Ivan the former manager to ask if this was possible. I'm waiting for his answer.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

[pyRdfa3 on Github site](https://github.com/prrvchr/pyrdfa3)
[pyRdfa3 on Test Python Package Index](https://test.pypi.org/project/pyRdfa3/3.6.2/)

### Contact and additional research

 I just contacted Ivan the former owner of pyRdfa3 to ask if this was possible to transfert.
I'm waiting for his answer.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by iherman** [comment]
As the previous maintainer and original author of the pyRdfa3 project, I confirm that intend to transfer the pyRdfa3 project to @prrvchr.

**Comment by prrvchr** [comment]
Thank Ivan...

**Comment by prrvchr** [comment]
Ok, account has been retrieved, and the transfer done... I close.
