### ISSUE TITLE
Account recovery request: hms_kmp

### ISSUE THREAD

**Issue by netsettler** [pypi/support#3517]
### PyPI Username

`hms_kmp`

### Reason for request

When I left Harvard Medical School (HMS) recently, I lost access to my email as Kent_Pitman@hms.harvard.edu (pypi account hms_kmp), so I can't do a password reset. I do still have access to Duo so can access my 2FA token.

I'd like to change the email to netsettler@nhplace.com, which I do still have access to, mostly so that I can go through my hms_kmp account and make sure to transfer ownership of HMS-related repos to people who are still at HMS.

I'm not sure how you prefer to establish my identity. Maybe that I have the 2FA token is enough. But also, you can see that the submitr repository is owned by hms_kmp and that that repo comes from https://github.com/smaht-dac/submitr which has my github identity netsettler as one of its contributors. I see my github icon next to this issue, so maybe you have that connected already but if not, I do have access to the github account (which had multiple emails) so if you send verification to its associated email, netsettler@nhplace.com, you can perhaps tell I'm the maintainer.

If you have some other preferred mechanism, that's fine, too.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by netsettler** [comment]
Oh, duh. I see this issue is opened at github so that's why it recognized me. :)

Anyway, thanks in advance for your help when you get to it.

**Comment by ewdurbin** [comment]
Hi, since you have valid 2FA enabled I have updated the primary email address on the account.

You can now perform a password reset, verify the address, and login using 2FA to recover your account.
