### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by willkessler** [pypi/support#3523]
### PyPI Username

willkessler

### Reason for request

I configured google authenticator for TestPypi, and got recovery codes for it as well. I created an API key and  I pushed my files to testPiPy without problem. Then I went to log into production at  pypi.org. It's now asking to authenticate with a code. However, I never actually configured 2FA with the production site (yet). When I use the value from Authenticator that I set up for TestPiPy, of course it doesn't work. How can I fix this? 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by willkessler** [comment]
Hello, I followed the instructions and replied to the other email. Thank
you.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
