### ISSUE TITLE
PEP 541 Request: oxygen

### ISSUE THREAD

**Issue by Daniel-Considine** [pypi/support#3527]
### Project to be claimed

`oxygen`: https://pypi.org/project/oxygen

### Your PyPI username

`dc16`: https://pypi.org/user/dc16

### Reasons for the request

The author published "oxygen" in Feb 2016 as an empty project with no package/code with it, seemingly as a test example of publishing a project to PyPI. There have been no updates to it since it was published. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no github/code repo provided for the current oxygen project. There is also no associated github repo for the user, https://github.com/ahlfors, which is an active account. 

We would like to replace the project using the name oxygen for: 
https://github.com/opentargets/genetics_etl_python
This is a package for genetics analysis and methods, incorporating Open Targets Genetics pipelines and data-structures in one unified framework. 

### Contact and additional research

We have emailed the owner at the listed email address, ahlforslee@gmail.com, on 16/01/2024. 
We think this package meets the definition of invalid, as per https://peps.python.org/pep-0541/#invalid-projects

> project is name squatting (package has no functionality or is empty)

Would this speed up the process of package name transfer? 

Best, 
Open Targets Team

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by Daniel-Considine** [comment]
@ewdurbin 
Sorry for the tag, but I've seen you action reports previously for name squatting. Does this particular answer meet that definition?

**Comment by Daniel-Considine** [comment]
@di @webknjaz @pradyunsg @ewdurbin @jamadden @hugovk @ewjoachim @VikramJayanthi17 @docyx

**Comment by Daniel-Considine** [comment]
@di @webknjaz @pradyunsg @ewdurbin @jamadden @hugovk @ewjoachim @VikramJayanthi17 @docyx
does pypi have any plans in the future to start removing name-squatters?

**Comment by webknjaz** [comment]
@Daniel-Considine yes, and there's a PyPI support person now that is going through the accumulated backlog queue, be patient. I'd like to also point out that spamming people with mentions is impolite and is certainly unhelpful. Many people mentioned already get insane amounts of notifications and wouldn't be in a position to do anything here anyway.

**Comment by Daniel-Considine** [comment]
@webknjaz Thank you for a quick response. 
All due respect, but two mentions over a year is not spam, and is evidently the only way to actually get a response. 
There is no listed contact, and all previous attempts to contact anyone were ignored. 
Perhaps update the page to include an actual contact and the news that someone is actually working on the backlog. 
Cheers 👍

**Comment by webknjaz** [comment]
It might be spam for people receiving thousands of notifications. It's just a tiny spam-contribution to a bigger picture 🤷‍♂️
Having to fight spam, many people and up disabling notifications which is likely why you're going to get a response when someone going through the queue gets to it.

FWIW, I don't have a commit bit here to update anything. Nor am I involved in the support activities. So for me, it's absolute spam as it's not related to what I do even a little and I didn't subscribe to getting pings.

**Comment by Daniel-Considine** [comment]
>  and I didn't subscribe to getting pings.
<img width="380" alt="image" src="https://github.com/user-attachments/assets/0b69db73-352f-4717-8aa2-99d94a4457f1">


> P.S. Apparently, there's a project board @ https://github.com/orgs/pypi/projects/3 that you could probably watch for the progress.

Appreciated.

**Comment by Thespi-Brain** [comment]
Hi @Daniel-Considine,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
**oxygen** has been deemed invalid. Additionally, the owner did not respond back regarding the status of their project. 
I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by Thespi-Brain** [comment]
Package owner finally responded back and wishes to keep name and release project so as not to name squat, issue status pending package owner's input.

**Comment by Thespi-Brain** [comment]
It has been over a year and the original user is still name squatting. @Daniel-Considine, are you still in need of this name? Let me know.

**Comment by Daniel-Considine** [comment]
Hi @Thespi-Brain, thanks for the response. 

To be honest it's very unlikely we will use the name now as we've been using a different name for over 2 years for our project. As a matter of principle it would be nice if you stripped the name from the squatter though, to avoid rewarding this behaviour.
