### ISSUE TITLE
File Limit Request: twinbooster - 900 MB

### ISSUE THREAD

**Issue by maxischuh** [pypi/support#3528]
### Project URL

https://pypi.org/project/twinbooster/

### Does this project already exist?

- [X] Yes

### New Limit

900

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

I have excluded all non-fundamental files. Unfortunately, to make the package useful two models need to be included for its use. There are no other files required.

### Reasons for the request

This project is a contribution on the field of chemistry and ML in chemistry. The goal is to make propriety prediction available to all users as easy as possible. Therefore, it is necessary to include the base-models. In the future additional files may be added, if requested by reviewers.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
It looks like you've been able to work around this by [distributing the models separately](https://github.com/maxischuh/TwinBooster/blob/8e961a29cde05ba3b047da285bc34f57e0ba9ffc/twinbooster/scripts/downloader.py#L9-L41), is this still needed?
