### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by yinsn** [pypi/support#3530]
### PyPI Username

yin.cheng

### Reason for request

I hope this message finds you well. My name is yin.cheng and I am writing to seek assistance regarding an issue with my two-factor authentication (2FA). Recently, I had to change my computer . Unfortunately, in the process, I lost access to my two-factor authentication setup. This has prevented me from accessing my account as I no longer have the necessary 2FA codes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `yin.cheng` has valid recovery codes generated as of 2022-09-10 13:50:08.742044.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by yinsn** [comment]
Dear Ee Durbin,

Thank you for your swift response and assistance regarding my account recovery request for the PyPI username 'yin.cheng'. I appreciate the clear instructions provided for verification through a GitHub branch.

Unfortunately, I must inform you that the 'rsdiv' project repository mentioned in your email was developed by me during my tenure at Smartnews. Since my departure from the company, I no longer have the necessary permissions to create branches or make any changes to the repository.

Given these circumstances, I kindly request if it would be possible to utilize an alternative method for verification. I am eager to suggest any personal repositories or other forms of verification that may meet your criteria for proving ownership of the email address ycheng_sjtu@foxmail.com and associated PyPI account.

I understand the importance of maintaining strict security protocols and am willing to comply with any reasonable alternative verification process you suggest. My aim is to ensure a smooth and secure recovery of my PyPI account while adhering to your guidelines.

Thank you for considering my situation. I look forward to your guidance on the next steps.

Best regards,

Yin Cheng

**Comment by Thespi-Brain** [comment]
Hi @yinsn,

Thanks for completing the verification process. Your 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
