### ISSUE TITLE
PEP 541 Request: PureMVC

### ISSUE THREAD

**Issue by saadshams** [pypi/support#3532]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/PureMVC

### Your PyPI username

`USER_NAME`: https://pypi.org/user/saadshams

### Reasons for the request

The project has been abandoned since 2011, last version 1.2

I'm the principal maintainer and the author of the PureMV ports at [link](https://github.com/orgs/PureMVC/people) and recently took over the maintenance and upgrade of the port to use the latest version of Python.

My other repositories at PureMVC, to name a few:
JavaScript Multicore: https://github.com/PureMVC/puremvc-js-multicore-framework

Go Standard: https://github.com/PureMVC/puremvc-go-standard-framework
Go Multicore: https://github.com/PureMVC/puremvc-go-multicore-framework

Swift Standard: https://github.com/PureMVC/puremvc-swift-standard-framework
Swift Multicore: https://github.com/PureMVC/puremvc-swift-multicore-framework

CSharp Standard: https://github.com/PureMVC/puremvc-csharp-standard-framework
CSharp Multicore: https://github.com/PureMVC/puremvc-csharp-multicore-framework

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

It will be an upgrade to the current port to use the latest features of Python.

We maintain two kinds of ports for each language: standard and multicore.

The one in question is the standard port and once the pip name is transferred, I will create an additional new package to distribute the multicore version.

Original Repo: https://github.com/PureMVC/puremvc-python-standard-framework

Work in Progress Repos:
Standard: https://github.com/saadshams/puremvc-python-standard-framework (existing pip, maintain/update)
Multicore: https://github.com/saadshams/puremvc-python-multicore-framework (new to pip)

### Contact and additional research

The email to the current owner bounced back as he's no longer active on the project: toby.de.havilland@puremvc.org

![Screen Shot 2024-01-16 at 5 57 10 PM](https://github.com/pypi/support/assets/703661/7e54811e-06c6-49cf-857d-664c09586093)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by saadshams** [comment]
Hi, 

I have been waiting on it for long time, and updated version is complete and ready to be replaced.

Repo: https://github.com/saadshams/puremvc-python-multicore-framework

**Comment by Thespi-Brain** [comment]
Hi @saadshams,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by saadshams** [comment]
@Thespi-Brain Thank you. The owner added me to the PyPI.
