### ISSUE TITLE
Project Limit Request: pulumi-azure-native - 60 GB

### ISSUE THREAD

**Issue by danielrbradley** [pypi/support#3533]
### Project URL

https://pypi.org/project/pulumi-azure-native/

### Does this project already exist?

- [X] Yes

### New limit

60 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project contains SDKs modelling all resources available in Azure. Therefore, we produce nightly releases with automated updates.

We currently have 30GB assigned, which have been exhaused. We could delete older pre-release versions, but it would appear this could be disruptive if any users are pinned to older pre-release versions.

Since introducing wheels in October, our release size has approximately trippled. I calculate that an additional 30gb would give us nearly another year of releases.

### How large is each release?

~93.3mb:
- 35.0 MB source
- 58.3 MB wheel

### How frequently do you make a release?

Roughly once per day.

For reference, here's the previous limit request: https://github.com/pypi/support/issues/2067

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mjeffryes** [comment]
Bumping this issue. This is blocking our ability to distribute regular updates to the Azure API.

**Comment by mjeffryes** [comment]
@cmaureir apologies for the direct ping, but it looks like you may be the most active on these limit request tickets? 

We've been culling older pre-release versions of our package in order to continue to deliver sdk updates, but we're banging against this ceiling often and running out of pre-releases to cull.

**Comment by di** [comment]
I've set the total size limit for `pulumi-azure-native` to 60 GB on PyPI.
