### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by the-praxs** [pypi/support#3541]
### PyPI Username

praxs

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `praxs` has valid recovery codes generated as of 2023-10-16 16:27:55.461971.

Please use those recovery codes to regain access to your account.

**Comment by the-praxs** [comment]
> User `praxs` has valid recovery codes generated as of 2023-10-16 16:27:55.461971.
> 
> Please use those recovery codes to regain access to your account.

I lost my recovery codes as well.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by the-praxs** [comment]
https://github.com/the-praxs/DeFiLlama-Curl/pull/5

Added the recovery request with this PR
