### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ykzzyk** [pypi/support#3546]
### PyPI Username

pumpkin_q

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ykzzyk** [comment]
how to get the authentication code? I don't remember the process of setting up an app to get the code.

**Comment by ewdurbin** [comment]
closing as duplicate of #3531
