### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JoelBender** [pypi/support#3547]
### PyPI Username

`Joel.Bender`

### Reason for request

In spite of your valiant efforts to encourage me to do the right thing and add 2FA to my account, I failed to do so last year.  Please reset my account to something like "new user" so the next time I log in I can add 2FA and then an API token.  Thank you for your outstanding work.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `Joel.Bender` has valid recovery codes generated as of 2023-12-12 02:14:11.083670.

Please use those recovery codes to regain access to your account.

**Comment by JoelBender** [comment]
I have GitHub recovery codes and the GitHub mobile application on my iPhone that I have verified that I can use to access my GitHub account, but I do not have an authentication application associated with my PyPI account and no record of having created the recovery codes you mentioned.  Assuming I could find one, attempting to use a recovery code displays an error **Invalid or expired two factor login.**

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by JoelBender** [comment]
Thank you, instructions received and followed, please proceed.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
