### ISSUE TITLE
File Limit Request: DLPacker - 300 MB

### ISSUE THREAD

**Issue by nekitmm** [pypi/support#3548]
### Project URL

https://pypi.org/project/dlpacker/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is based on my research paper from 3 years ago, some people use it in their projects and want an easy installable project for easier deployment.

The problem is that it's based on a deep learning model and I have to include the weights (solutions like Google Drive don't work, too frequent downloads blocked it).

### Reasons for the request

Including my model weights in the project, 300 Mb is more than enough, this old project is unlikely to be frequently updated.

Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @nekitmm :wave:
I've set the upload limit for `dlpacker` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend!

**Comment by nekitmm** [comment]
@cmaureir Thank you!
