### ISSUE TITLE
Project Limit Request: QuantLib - 20 GB

### ISSUE THREAD

**Issue by lballabio** [pypi/support#3551]
### Project URL

https://pypi.org/project/QuantLib/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

QuantLib is a C++ financial library (see https://www.quantlib.org) started in May 2000.
It's been on PyPi since March 2017, first as QuantLib-Python (until 2019) then as QuantLib.

The wheels wrap and bundle the C++ library.  In the past couple of years, we increased the number of architectures we're covering, resulting as of now in more than 1GB per release.

### How large is each release?

As mentioned above, the C++ library is bundled in the wheels.
I'm taking care to strip all debug information to reduce size.

~1250 MB total

14 Windows wheels at ~170 MB (~50 MB PyPy 3.8-3.10, ~120 CPython 3.8-3.12)
14 OS X wheels at ~ 220 MB (~60 MB PyPy, ~160 MB CPython)
27 manylinux wheels at ~ 540 MB (~240 MB PyPy, ~300 MB CPython)
15 musllinux wheels at ~300 MB (CPython only)

### How frequently do you make a release?

Every third month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @lballabio :wave:
I've set the project limit for `quantlib` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size and maybe explore the option to use Python's limited API https://docs.python.org/3/c-api/stable.html
Have a nice weekend!
