### ISSUE TITLE
Project Limit Request: casatools - 30 GB

### ISSUE THREAD

**Issue by vsuorant** [pypi/support#3552]
### Project URL

https://pypi.org/project/casatools/

### Does this project already exist?

- [X] Yes

### New limit

30GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

CASAtools is a self-contained python module that provides the tools from the CASA (Common Astronomy Software Applications) http://casa.nrao.edu/ project. 

There Python project has been active since May 2021.

### How large is each release?

~1GB total. Two different Python versions, two Linux variants and one Macos variant. We are hoping to drop the oldest Linux variants soon, which should bring the total package size to ~ 600MB, but we are not quite there yet.

### How frequently do you make a release?

Approximately every three months. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by vsuorant** [comment]
Is there a way to know/estimate how long these requests take to process? Is there anything we can do to expedite processing this request on our side?

**Comment by cmaureir** [comment]
Hey @vsuorant :wave:
Long time without reading some CASA related work :telescope: 
I've set the project limit for `project` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice weekend!

**Comment by vsuorant** [comment]
Thank you very much!
