### ISSUE TITLE
Project Limit Request: aws-pdk -  20 GB

### ISSUE THREAD

**Issue by agdimech** [pypi/support#3558]
### Project URL

https://pypi.org/project/aws-pdk/

### Does this project already exist?

- [X] Yes

### New limit

20Gb

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The PDK is a library or CDK/Projen constructs that is distributed to NPM/Maven and PYPI. We release in a full CD manner and as such whenever a commit occurs, this results in a PYPI release. We have not had any issues with npm/maven with regard to 'project sizes'. What is the recommended way to proceed as eventually we will hit the upper bound of the 20Gb limit?

### How large is each release?

~20Mb (recently optimized)

### How frequently do you make a release?

Full CD - so whenever code is merged.

we are open to changing this for PYPI - just need your recommendation.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by agdimech** [comment]
Hi - just wanted to see if we can get an update on this one please as this is starting to affect some of our customers?

**Comment by dbryson** [comment]
Also checking in here as an affected customer.  I see there are '3 tasks done', is there any way this can be a bit less opaque?

**Comment by agdimech** [comment]
Can I please get an update on this ticket as it has been over a month and customers are still impacted?

**Comment by agdimech** [comment]
@cmaureir - sorry to ping you directly but am getting desperate now and noticed you have been actively working on tickets as of late. Could you please take a look at this when you can?

**Comment by rgommers** [comment]
(I'm not an admin, so this is just advice)

> Full CD - so whenever code is merged.

From the README:
```
Upload limits are generally denied for the following reasons:

    project makes nightly releases and/or is published frequently
```

You are asking for an extra 40 GB, which is quite excessive when a single release is only 20 MB in total. Your request is unlikely to be accepted in its current form I believe. You can do 50 releases of your project with a 1 GB increase, so asking for more than an extra 5 GB does not seem reasonable.

**Comment by cmaureir** [comment]
Hey @agdimech :wave:
I've set the project limit for `aws-pdk` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend! :snake:
