### ISSUE TITLE
Project Limit Request: aspose-ocr-python-net - 30 GB

### ISSUE THREAD

**Issue by Annushka34** [pypi/support#3559]
### Project URL

https://pypi.org/project/aspose-ocr-python-net/

### Does this project already exist?

- [X] Yes

### New limit

30 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Information about Aspose.OCR library (Aspose Pty)
https://products.aspose.com/ocr/python-net/
https://releases.aspose.com/ocr/python-net/
Our project is quite large in size as it includes neural networks, which cannot be hosted as an external resource since they are our internal development and a core value of the library. We distribute our package across various target platforms, and each release takes up a considerable amount of space.

### How large is each release?

300 Mb for one platform *  5 platforms ~ 1.5 Gb

### How frequently do you make a release?

One per month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rgommers** [comment]
> Our project is quite large in size as it includes neural networks, which cannot be hosted as an external resource since they are our internal development and a core value of the library. 

See https://github.com/pypi/support/issues/3250#issuecomment-1908020370.
