### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vicLim88** [pypi/support#3561]
### PyPI Username

`limw0144`

### Reason for request

Lost both recovery code and authentication code, as I have reset my mobile device and I could not link my account to any authentication app. As such, I am stuck at the `Two-factor authentication` page.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by vicLim88** [comment]
I have also lost my recovery code

**Comment by vicLim88** [comment]
Hi thanks for looking into my issue.

Unfortunately I have lost my recovery code as well. Is there any other way which I can recover ?

**Comment by Thespi-Brain** [comment]
Hi @vicLim88,

I am following up on your issue: are you still having trouble regarding your recovery codes and logging in? Let me know and I will start an account recovery process for you. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
