### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jeankobeis** [pypi/support#3563]
### PyPI Username

johnny_kobeis@live.com

### Reason for request

i've change my cell phone and lost my 2FA, i was using microsot authenticator

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
No user with that username or email found on pypi.org.
