### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by nisaac21** [pypi/support#3568]
### PyPI Username

nisaac21

### Reason for request

I have lost access to the recovery codes and authentication app because my computer device was wiped due to malfunctioning. While there were recovery codes generated in September 2023, I cannot access them anymore and will need help to recover my account. Please email me new recovery codes, or the ones generated, or some other way to log back into my account. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `nisaac21` has valid recovery codes generated as of 2023-09-01 19:40:54.728527.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
