### ISSUE TITLE
PEP 541 Request: deepeval

### ISSUE THREAD

**Issue by penguine-ip** [pypi/support#3574]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/deepeval

### Your PyPI username

`USER_NAME`: https://pypi.org/user/penguineip

### Reasons for the request

I need owner permission on the project which belongs to our company. Previous maintainer (with owner permission) is no longer working on it (for over a year now) and couldn't login to his account. The two of us started the project, and at the time of his departure he couldn't login to his account.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/confident-ai/deepeval

### Contact and additional research

Talked to the other maintainer (with owner permission), he lost access to his pypi account (couldn't log in) when he left last year. Documents can be provided on request.
Last contribution to our company's repo was over a year ago. (bottom left)
<img width="829" alt="Screenshot 2024-10-22 at 11 39 44 PM" src="https://github.com/user-attachments/assets/bb6e8530-a84e-49b1-a9f5-cf1039095d13">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by penguine-ip** [comment]
Hey PyPi team (@ewdurbin), can I please get some eyes on this issue? Thanks!

**Comment by penguine-ip** [comment]
Hi @dstufft, may I please have an update on this request / anything I'm missing?

**Comment by penguine-ip** [comment]
Also maybe @yeraydiazdiaz is still active?

**Comment by woodruffw** [comment]
Hi @penguine-ip. I saw your thread via the issue you filed on Warehouse, but please understand: there is a significant backlog with minimal maintainer resources, and there are requests being triaged ahead of yours. Pinging individual PyPA members is unlikely to help, since the overwhelming majority can't perform these triaging steps.

It's not uncommon for PEP 541 requests to take over a month to be fully triaged. Yours has only been open for two weeks, so please try and be patient.

**Comment by penguine-ip** [comment]
@woodruffw I see, thanks for the reassurance, was just worried this is an abandoned issues thread, thanks for the work.

**Comment by penguine-ip** [comment]
hey @woodruffw, I'm wondering should I be expecting something soon? Or is it already being handled internally and I should just wait for the results?

**Comment by penguine-ip** [comment]
Hey @woodruffw and @ewdurbin, I wanted to follow up to see if it has been fully triaged. Let me know if there is anything I can do. Thanks.

**Comment by woodruffw** [comment]
@penguine-ip Per https://github.com/pypi/support/issues/3574#issuecomment-1937629116, I don't have the ability to triage this further. There's no need to post an update each month; pinging individual PyPA members will **not** accelerate the triage process here. Please be patient, and wait for someone with triage abilities to respond.

**Comment by penguine-ip** [comment]
Hey @woodruffw, I've tried waiting but I think from the past requests its increasing likely that without some sort of involvement this will never get resolved. Unlike other projects this is actually my company, what we do for a living and I'm talking about an ownership transfer not a simple name change. I really hope you can point me in the right direction even if you can't resolve this issue.

**Comment by woodruffw** [comment]
@penguine-ip Per the previous comments, there is no "involvement" I can provide here. This probably isn't the answer you're looking for, but the *only* thing you can do here is wait for your point in the triage queue. That queue is steadily being burned down now that there's someone doing triage full-time; you can see that in https://github.com/pypi/support/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aclosed.

**Comment by ewdurbin** [comment]
Hi @penguine-ip, sorry that this has been a frustrating experience for you.

William is right, there is someone working full time for the PSF now to address this backlog in the order that they were submitted.

In the meantime, you may want to contact the existing Owner of the project. I note in PyPI's event log that they have successfully logged since this request was filed.

**Comment by penguine-ip** [comment]
Hey @woodruffw and @ewdurbin thanks for your attention, kind reassurance, and acknowledging this is really important to us. 

Also thanks for bringing up the fact that the Owner has logged in since, I'm not sure if there is good faith to help but I will surely reach out. Thanks again.

**Comment by penguine-ip** [comment]
Hey @ewdurbin @woodruffw , the issue has been resolved and the original owner kindly transferred the ownership. Thanks for pointing out the login history! Going to close this now.
