### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by j-bennet** [pypi/support#3577]
### PyPI Username

icherniavska

### Reason for request

I lost 2FA authentication app or security token for test.pypi.org.

I'm able to log in to pypi.org, but not to test.pypi.org.

Please help.

Related: https://github.com/pypi/support/issues/3234.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA reset for test.pypi.org user icherniavska
