### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Seluj78** [pypi/support#3578]
### PyPI Username

seluj78

### Reason for request

It seems like bitwarden hasn't saved my 2FA key and I never generated the security tokens for recovery (or at least I don't have them saved anywhere)... So I am locked out of my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Seluj78** [comment]
Done, thank you very much !

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
