### ISSUE TITLE
PEP 541 Request: pigeonsai

### ISSUE THREAD

**Issue by birajsilwal** [pypi/support#3581]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pigeonsai

### Your PyPI username

`USER_NAME`: https://pypi.org/user/birajsilwal

### Reasons for the request

Hello, 

I mistakenly deleted the project pigeonsai instead of transferring ownership. The project was originally owned by username ariaattar (aria@pigeonsai.com) and we just wanted to transfer the project to username pigeonsai (info@pigeonsai.com). My username is birajsilwal (biraj@pigeonsai.com). 

I tried to upload the same project with an increase in version number but gave me ```This filename has already been used, use a different version.```

This package is currently used by our users so, after the recovery, the project will continue with an increase in version number.

Is there any possibility of recovering the project under pigeonsai username (preferably)? Even if we can create the project under the original username ariaattar that would be helpful. Thank you. 

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/pigeonsai/sdk/tree/main/python

### Contact and additional research

Yes, we both work on the same startup. 

original author: aria@pigeonsai.com (username - ariaattar)
me: biraj@pigeonsai.com (username - birajsilwal)
future author: info@pigeonsai.com (username - pigeonsai)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pigeonsai** [comment]
Just adding a comment to support birajsilwal
