### ISSUE TITLE
PEP 541 Request: pagerduty

### ISSUE THREAD

**Issue by Deconstrained** [pypi/support#3589]
### Project to be claimed

`PROJECT_NAME`: [pagerduty](https://pypi.org/project/pagerduty/)

### Your PyPI username

`USER_NAME`: 

* [Deconstrained](https://pypi.org/user/Deconstrained)
* [lnxchk](https://pypi.org/user/lnxchk)

### Reasons for the request

* The library has not had any releases in over ten years
* The owner of the GitHub repository linked on the PyPI project page did not respond to my attempt to contact them using the email address given in their GitHub profile.
* [PagerDuty Inc.](https://www.pagerduty.com) actively maintains the popular and de-facto standard Python client for its public APIs under a different name ([pdpyras](https://pypi.org/project/pdpyras/)) and wishes to take ownership of the `pagerduty` project name. 
* I am the lead contributor of `pdpyras` along with @lnxchk and we are both employed by PagerDuty (last updated 2024-07-25). The repository will be owned by the `PagerDuty` org as `pdpyras` currently is.

### Maintenance or replacement?

Replacement; we are planning to rebuild our existing client library around a different HTTP client and make some much needed class naming changes, and then (if we are granted ownership of the project) release it under the library name `pagerduty`, before finally deprecating `pdpyras`.

### Source code repositories URLs

The repository of the current project (404): http://github.com/samuel/python-pagerduty

The repository of the project that will eventually take its name: https://github.com/PagerDuty/python-pagerduty (a repository that will start as a clone of https://github.com/PagerDuty/pdpyras)

### Contact and additional research

The email address given on the [project page](https://pypi.org/project/pagerduty/), `samuel@playhaven.com`, is unreachable (the domain `playhaven.com` has no `MX` records).

The owner of the project was assumed to be the GitHub user `samuel` based on the URL given as the project homepage on the PyPI project page (http://github.com/samuel/python-pagerduty).

The email address I used for contact is (as shown on their GitHub profile): `samuel@descolada.com`.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Deconstrained** [comment]
I should add, Mandi Walls (@lnxchk on both GitHub and PyPI, who helps review and release pdpyras) will be co-owner of the project.

**Comment by Thespi-Brain** [comment]
Hi @Deconstrained and @lnxchk,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Deconstrained** [comment]
👋 Thank you so much! We received invitations to join the project.
