### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by imcjp** [pypi/support#3590]
### PyPI Username

imcjp

### Reason for request

I hope this message finds you well. I am writing to request assistance with regaining access to my PyPI account with the username "imcjp". Unfortunately, I have encountered a barrier upon attempting to log in, as the system is prompting me to "Enter authentication code," and I have realized that I have lost access to my authentication code.

This situation is quite urgent, as the account in question is integral to our production and business operations. Therefore, the inability to access my account is causing significant disruptions.

Could you kindly contact me at my registered email address, jpingcai@163.com, with instructions on how to restore my login capabilities?

I understand the importance of maintaining strict security protocols and appreciate any steps that need to be taken to verify my identity and facilitate the recovery of my account.

Thank you for your prompt attention to this matter. I am looking forward to your swift response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `imcjp` has valid recovery codes generated as of 2024-01-26 04:08:29.525899.

Please use those recovery codes to regain access to your account.

**Comment by imcjp** [comment]
How do I get "recovery codes"? I don't seem to have received an email about it? Please send the information to "jpingcai@163.com". Thank you very much.

**Comment by imcjp** [comment]
Can you please reset my account to allow me to skip the "Enter authentication code" to log in. Thank you

**Comment by ewdurbin** [comment]
Hi @imcjp, recovery codes were generated when you enrolled in 2FA and you were instructed to store them securely for precisely this situation.

Account recovery requests for users with valid recovery codes like yours are our lowest priority requests since you have been provided with a self service option. We estimate that our backlog of valid recovery code requests will begin being addressed by March 2024.

**Comment by imcjp** [comment]
@ewdurbin Can you please tell me roughly when you will be able to restore my account, I hope I can log in without authentication code or recovery codes. Thank you!

**Comment by imcjp** [comment]
@ewdurbin hello

**Comment by imcjp** [comment]
@ewdurbin I am writing to express my deep frustration and concern regarding the inability to directly log into my PyPI account. This situation has caused significant disruption to my work and projects, and I urgently require a resolution.

Could you please inform me when my account will be restored to full functionality, allowing for direct login access? The lack of communication and clarity on this matter has been exceedingly disappointing. I expect a prompt and definitive timeline for when I can anticipate regaining access to my account.

Thank you for your immediate attention to this critical issue.

**Comment by imcjp** [comment]
Can you restore my account? Losing my account is having a serious impact on my work.@ewdurbin

**Comment by Thespi-Brain** [comment]
User was able to login and was assisted with generating new recovery codes
