### ISSUE TITLE
File Limit Request: LMDeploy - 30GB

### ISSUE THREAD

**Issue by lvhan028** [pypi/support#3592]
### Project URL

https://pypi.org/project/lmdeploy/

### Does this project already exist?

- [X] Yes

### New Limit

30000

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/   Project size too large. Limit for project 'lmdeploy' total size is 10  GB. See https://pypi.org/help/#project-size-limit

### Reasons for the request

30GB

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by lvhan028** [comment]
Hi, @cmaureir 
Is there any update?

**Comment by cmaureir** [comment]
Can you add more information about the project? you just added the error message on that section

**Comment by lvhan028** [comment]
Sure @cmaureir 
This project is about LLM quantization, inference and serving. The github repo is: https://github.com/InternLM/lmdeploy
It contains lots of C++ and CUDA code. It supports both LInux-x86_64, Linux-aarch64 and Windows platforms.

**Comment by lvhan028** [comment]
@cmaureir would appreciate it if this request could be accepted. 
Is there anything I can do? Feel free to ask

**Comment by lvhan028** [comment]
This issue used the wrong template.
