### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ayobbebar** [pypi/support#3594]
### PyPI Username

stratoscale

### Reason for request

We dont know what email it was registred with and we need to transfer the owner to another user under our domain stratoscale domain . 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
ravid at stratoscale.com
