### ISSUE TITLE
File Limit Request: onnxruntime-training - 400 MiB

### ISSUE THREAD

**Issue by baijumeswani** [pypi/support#3595]
### Project URL

https://pypi.org/project/onnxruntime-training/

### Does this project already exist?

- [X] Yes

### New Limit

400 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Efforts have been made to remove the support for older cuda architectures that are no longer relevant thereby reducing the package size.

### Reasons for the request

The `onnxruntime-training` package contains several AI training related cuda kernels that increase the size of the package. These kernels are necessary for running training with the ONNX Runtime AI framework on a range of CUDA devices.
As noted above in the section above, we have already tried to reduce the package size by removing support for older CUDA architectures and will continue to do so going forward.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sophies927** [comment]
@cmaureir would you mind taking a look at this request? We are hoping to get it approved to move forward w/ a release as soon as possible. Thank you!

**Comment by YUNQIUGUO** [comment]
Hey @cmaureir  gentle ping again - anything that could expedite the process would be much appreciated.!

**Comment by baijumeswani** [comment]
tagging @di as well in case @cmaureir is out. Any chance we could have this approved today?
This is currently blocking our release.

**Comment by baijumeswani** [comment]
Ping! Would really appreciate some help on this. Any chance we could get this approved today?

**Comment by cmaureir** [comment]
Hey @baijumeswani :wave:
I've set the upload limit for `onnxruntime-training` to 400 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :tada:
