### ISSUE TITLE
PEP 541 Request: python-json-logger

### ISSUE THREAD

**Issue by nhairs** [pypi/support#3607]
### Project to be claimed

`python-json-logger`: https://pypi.org/project/python-json-logger

### Your PyPI username

`nhairs`: https://pypi.org/user/nhairs

### Reasons for the request

This project seems unmaintained with the author [madzak](https://pypi.org/user/madzak/) having disappeared from most internet presence.

Another maintainer is listed [peritus](https://pypi.org/user/peritus/) - however based on [their GitHub profile](https://github.com/peritus) looks like they are on hiatus from software development.

Given that there are [~32M downloads / month](https://pypistats.org/packages/python-json-logger) of this project I think it is better to ensure that it is maintained rather than forking and releasing under a new name.

I would like to take over maintenance of this project.

Update 2024-07-27: I think it's worth noting that [Debian has moved to using my fork of the project](https://salsa.debian.org/python-team/packages/python-pythonjsonlogger/-/commit/3e5b761ae864d9a234c8ace36f7097bb6eb50c07)

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current: https://github.com/madzak/python-json-logger
New: https://github.com/nhairs/python-json-logger

#### GitHub

- Last release / issue / PR interaction was Feb 2023
  - There are many outstanding issues / PRs
- [Have raised an issue](https://github.com/madzak/python-json-logger/issues/187) on the GH repository

##### Email

I've attempted to contact Zak via the email listed on their GitHub profile
![image](https://github.com/pypi/support/assets/9976336/01e7d251-88d2-4abd-83d7-77b737b08e44)

##### Web

- Their website http://www.madzak[.]com does not appear up
- Searching for their social media:
  - X / Twitter appears empty https://twitter[.]com/zakzajac https://twitter[.]com/madzak
  - LinkedIn does not show recent activity https://www.linkedin[.]com/in/zakaria-zajac/

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nhairs** [comment]
Hi there,

Is there any update / ETA for this request?

As an update of my own, I've forked the original project and am engaging the community: https://github.com/nhairs/python-json-logger/issues/1

**Comment by simonpercivall** [comment]
Please shut this request down. Not the least given the recent `xz` debacle, someone taking over a very popular package feels _very dangerous_.

**Comment by nhairs** [comment]
> Please shut this request down. Not the least given the recent `xz` debacle, someone taking over a very popular package feels _very dangerous_.

To avoid needlessly splitting the discussion I've responded to @simonpercivall [on this issue](https://github.com/madzak/python-json-logger/issues/187#issuecomment-2063454214).

**Comment by cunla** [comment]
Hi, I would like to participate in maintaining this project.

**Comment by sagittarian** [comment]
Is there any progress on this?  The request should either be granted so that users can install the new version, or denied so that the maintained version can be published under a different name.

**Comment by nhairs** [comment]
Hi @Thespi-Brain,

I was wondering if there was an ETA for this request to be looked at?

There are quite a number of people waiting on the outcome of this request.

**Comment by nhairs** [comment]
Hi @encukou,

I've notice you providing support on some PEP 541 requests and was wondering if you'd be able to take a look at this issue.
(I understand that you can't complete the full request just carry out the basic triage and contacting of maintainers).

**Comment by encukou** [comment]
Sorry, that's what I'm doing but I was instructed to go strictly in order.

**Comment by nhairs** [comment]
> Sorry, that's what I'm doing but I was instructed to go strictly in order.

@encukou make sense - all good :)

If you're able to provide a ETA that would be appreciated, but also understandable if you aren't able/willing to.

**Comment by virajkanwade** [comment]
Waiting for this!

**Comment by Thespi-Brain** [comment]
Hi @nhairs,

Thanks for your patience. We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by nhairs** [comment]
Thanks @Thespi-Brain - `@madzak` has transferred ownership of the PyPI project to me.

Although I received access to the project I've not had any communication from them. If possible would you be able to share any response from them or their email so I can get in touch? (This should probably be done privately over email rather than in public as to avoid leaking personal information).

I'd like to be able to thank them and ask if they had any instructions - I'd like to be respectful in taking over the project, but also understand if they just want to "lob it over the fence" to me.

For everyone else: development will continue at [nhairs/python-json-logger](https://github.com/nhairs/python-json-logger).
