### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by xk2013** [pypi/support#3608]
### PyPI Username

SmallWaterSnake

### Reason for request

I lost 2FA authentication key device.
Can I recovery my account and change my username to "xk2013"?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `SmallWaterSnake` has valid recovery codes generated as of 2023-04-13 11:36:01.991275.

Please use those recovery codes to regain access to your account.

**Comment by xk2013** [comment]
> User `SmallWaterSnake` has valid recovery codes generated as of 2023-04-13 11:36:01.991275.
> 
> Please use those recovery codes to regain access to your account.

I lost my recovery codes, What can I do?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
