### ISSUE TITLE
Account recovery

### ISSUE THREAD

**Issue by nimasmi** [pypi/support#3610]
### PyPI Username

`nimasmi`

### Reason for request

- Lost 2FA security token
- Lost recovery codes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `nimasmi` has valid recovery codes generated as of 2022-03-02 16:09:18.223042.

Please use those recovery codes to regain access to your account.

**Comment by Thespi-Brain** [comment]
Hi @nimasmi,

I was following up regarding your request. Are you still having issues regarding logging in to your account due to losing access to your recovery codes? Let me know, and I will start an account recovery process for you, thanks!

**Comment by nimasmi** [comment]
Yes, thanks for chasing. I still do not have the recovery codes, and my original 2FA device is lost.

**Comment by Thespi-Brain** [comment]
Hi @nimasmi,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @nimasmi,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
