### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gcc-bug** [pypi/support#3613]
### PyPI Username

coldcat_gold

### Reason for request

I changed my mobile phone, but I can log in to pypi.org(this website's authentication code is generated in ios setting password), but cannot log in to test.pypi.org.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA reset for `coldcat_gold` user on test.pypi.org.
