### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by LinaresToine** [pypi/support#3615]
### PyPI Username

alinares

### Reason for request

Lost access to API tokens and two factor authentication method

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `alinares` has valid recovery codes generated as of 2023-08-10 19:48:21.037401.

Please use those recovery codes to regain access to your account.

**Comment by LinaresToine** [comment]
Thanks. I opened this issue precisely because I lost access to those codes.

I would appreciate it if I could regain access to it.

Thanks

**Comment by Thespi-Brain** [comment]
Hi @LinaresToine,

I was following up regarding your issue. Are you still having issues regarding your recovery codes? Let me know, and I will start an account recovery process to reset them, thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response

**Comment by LinaresToine** [comment]
Hello @ewdurbin @Thespi-Brain may I please get the new tokens? Apologies for the lack of response before
