### ISSUE TITLE
File Limit Request: grpcio - 110 MB

### ISSUE THREAD

**Issue by gnossen** [pypi/support#3616]
### Project URL

https://pypi.org/project/grpcio

### Does this project already exist?

- [X] Yes

### New Limit

110MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

grpcio is the 69th most downloaded package on PyPi. It is an open source messaging/RPC framework built on top of a C extension shared with the C++ implementation of gRPC and is a dependency of several machine learning frameworks.

### Reasons for the request

We recently found that the armv7 artifacts for our 1.61.0 release crept beyond the 100MB limit:

```
-rw-r----- 1 rbellevi primarygroup 102M Feb  6 13:08 ./grpcio-1.61.0-cp310-cp310-linux_armv7l.whl
-rw-r----- 1 rbellevi primarygroup 102M Feb  6 13:08 ./grpcio-1.61.0-cp311-cp311-linux_armv7l.whl
-rw-r----- 1 rbellevi primarygroup 103M Feb  6 13:08 ./grpcio-1.61.0-cp312-cp312-linux_armv7l.whl
-rw-r----- 1 rbellevi primarygroup 101M Feb  6 13:08 ./grpcio-1.61.0-cp37-cp37m-linux_armv7l.whl
-rw-r----- 1 rbellevi primarygroup 102M Feb  6 13:08 ./grpcio-1.61.0-cp38-cp38-linux_armv7l.whl
-rw-r----- 1 rbellevi primarygroup 102M Feb  6 13:08 ./grpcio-1.61.0-cp39-cp39-linux_armv7l.whl
```

We are currently working on:

1. Reducing the size of these artifacts
2. Introducing a regression test to ensure that we don't creep beyond the limit again.

But for reasons of build reproducibility and commit synchronization with other gRPC languages, we either need an exception to upload these slightly over-the-limit the artifacts or we need to skip 1.61.0 entirely and wait for a 1.61.1 with the fixes mentioned above. We would appreciate any help you can provide on this.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @gnossen :wave:
I've set the upload limit for `grpcio` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :dancers:
