### ISSUE TITLE
File Limit Request: kungfu-core - 150 MiB

### ISSUE THREAD

**Issue by dongkeren** [pypi/support#3618]
### Project URL

https://pypi.org/project/kungfu-core/

### Does this project already exist?

- [X] Yes

### New Limit

150 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Over the past six years, we have been dedicated to developing a sophisticated quantitative trading engine, which can be accessed at [Kungfu Trader](https://github.com/kungfu-origin/kungfu). The centerpiece of our project is kungfu-core, a powerful core engine predominantly authored in C++. It features a Python binding interface, catering to the majority of our user base who compose their trading strategies in Python. This design choice harnesses Python's simplicity for strategy development while leveraging the core engine's C++ efficiency to handle low-latency tasks critical for rapid order execution.

### Reasons for the request

The C++ component of our kungfu-core is a testament to sophistication, which, upon compilation, results in a substantial library file (.so/.dll). For instance, on a Linux system, the library sizes are as follows:

❯ ls -lh build/Release
Permissions  Size  User  Date Modified  Name
.rw-r--r--    304B  root  6 Feb  10:22   kungfubuildinfo.json
.rwxr-xr-x   339MB  root  6 Feb  10:12   libkungfu.so
.rwxr-xr-x    96MB  root  6 Feb  10:22   libnode.so.93
.rw-r--r--    183B  root  6 Feb  10:22   libnodebuildinfo.json
.rwxr-xr-x    18MB  root  6 Feb  10:15   pykungfu.cpython-39-x86_64-linux-gnu.so

Despite our best efforts to optimize and reduce the footprint, the compiled libraries remain sizeable. Consequently, the generated wheel (whl) file is also quite large:

❯ ls -lh build/python/dist
Permissions  Size  User  Date Modified  Name
.rw-r--r--   105MB  root  6 Feb  10:22   kungfu-2.6.13a9-cp39-cp39-linux_x86_64.whl

Looking forward, we plan to integrate new features, such as embedded algorithms, into the core. These enhancements are anticipated to increase the library size further. We would greatly appreciate assistance with expanding the size limit on PyPI to accommodate our growing package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @dongkeren :wave:
I've set the upload limit for `kungfu-core` to 200 MB on PyPI (the project didn't exist on TestPyPI). Please be mindful of the frequency of releases at that size.
Have a nice weekend :sun_with_face:
