### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gsheni** [pypi/support#3623]
### PyPI Username

`featurelabs-bot`

### Reason for request

We are the maintainers of the premium primitives package (https://pypi.org/project/premium-primitives/).
We use an account (https://pypi.org/user/featurelabs-bot/) to publish our releases but we seem to have forgotten the password.
We cannot reset the password via email because since we got acquired by Alteryx, our old email addresses stopped working.
Would you be able to add myself (gsheni) and Nate (n8parsons) to this project as Owners? If you look at our profiles you will see that we are already owners on other Alteryx packages and we maintain to the source code on GitHub (https://github.com/alteryx/premium_primitives).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please contact support @ pypi.org referencing this issue (include a link) from the new email address you would like to have associated with the `featurelabs-bot` user.

**Comment by thehomebrewnerd** [comment]
> Please contact support @ pypi.org referencing this issue (include a link) from the new email address you would like to have associated with the `featurelabs-bot` user.

@ewdurbin Email has been sent

**Comment by gsheni** [comment]
> > Please contact support @ pypi.org referencing this issue (include a link) from the new email address you would like to have associated with the `featurelabs-bot` user.
> 
> 
> 
> @ewdurbin Email has been sent

Thanks Nate!

**Comment by thehomebrewnerd** [comment]
@ewdurbin Just wanted to follow up to see if there are any additional steps needed from our end. I sent the email as requested, but have not received any response.

**Comment by ewdurbin** [comment]
Contacted via requested email address, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by thehomebrewnerd** [comment]
@ewdurbin No password reset information has been received. Are you sure this is complete?

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by thehomebrewnerd** [comment]
@ewdurbin Sorry to be a pest here, but I did not receive any information on how to reset the password. Was the email address associated with the account also changed as requested?
