### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by fnixdev** [pypi/support#3628]
### PyPI Username

fnixdev

### Reason for request

I had my account hacked and the attacker added a 2-factor authentication code to my account, I was able to recover the password but I want to remove the 2-factor authentication code.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `fnixdev` has valid recovery codes generated as of 2024-02-09 19:02:41.897496.

Please use those recovery codes to regain access to your account.

**Comment by miketheman** [comment]
Admin note: I had disabled this user account after an account takeover, which is why there are valid codes that they cannot use.
