### ISSUE TITLE
Project Limit Request: cadquery-ocp - 30 GB

### ISSUE THREAD

**Issue by jmwright** [pypi/support#3631]
### Project URL

https://pypi.org/project/cadquery-ocp/

### Does this project already exist?

- [X] Yes

### New limit

30GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

cadquery-ocp makes Python wheels available for the OpenCASCADE CAD kernel bindings that the CadQuery CAD API relies on. cadquery-ocp has been active on PyPI since May 2022, and the parent project CadQuery has been on PyPI since April 2013. We are dropping support for Python 3.8 in future releases and so we will not be uploading those wheel files, but we are trying to add ARM64 Linux and MacOS wheels as well, so the overall size of each release will increase.

### How large is each release?

~2.1GB total currently. That includes Python 3.8-3.12 wheels for Linux x86_64, Windows and MacOS (non-ARM64). In the future we want to make Python 3.9-3.12 available for Linux x86_64, Linux aarch64, Windows, MacOS and MacOS ARM64. The current wheel sizes range between 88MB and 185MB. Some of our wheels bundle the VTK package for a size increase of about 50MB, and this is done because of a libstdc++ version compatibility issue. We will be working to stop bundling VTK and move to using their wheels as a dependency, but we do not yet have an ETA on when we will be able to accomplish this.

### How frequently do you make a release?

Our release cadence follows (but somewhat lags) the release schedule of the OpenCASCADE CAD kernel, which has been ranging between 3 and 6 months per release.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `cadquery-ocp` to 30 GB on PyPI.

**Comment by jmwright** [comment]
Thank you.
