### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by doutriaux1** [pypi/support#3633]
### PyPI Username

doutriaux1

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by doutriaux1** [comment]
Just in the interest of time, let me make it clear that if I ever had recovery token, I do not have access to them any longer

**Comment by ewdurbin** [comment]
User `doutriaux1` has valid recovery codes generated as of 2022-02-25 16:19:37.435330.

Please use those recovery codes to regain access to your account.

**Comment by doutriaux1** [comment]
@ewdurbin as mentioned in the comments above yours I do not have these. What is the path forward now?

**Comment by Thespi-Brain** [comment]
Hi @doutriaux1,

I am following up regarding your issue. Are you still having trouble logging in due to lost recovery codes? Let me know, and I will start an account recovery process for you to reset your account, thanks!

**Comment by doutriaux1** [comment]
@Thespi-Brain yes my laptop with the keys on it is gone so I have no way to get back into the account. Any help desperately wanted!

**Comment by Thespi-Brain** [comment]
Hi @doutriaux1,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @doutriaux1,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
