### ISSUE TITLE
PEP 541 Request: go2rpm

### ISSUE THREAD

**Issue by gotmax23** [pypi/support#3636]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/go2rpm

### Your PyPI username

`USER_NAME`: https://pypi.org/user/gotmax23 and https://pypi.org/user/eclipseo

### Reasons for the request

I believe this package name was blocked by the Fedora Python SIG to prevent package collisions, as the name was used in Fedora packages, but the project was never published to PyPI.

```
Running: ('twine', 'upload', 'dist/go2rpm-1.10.0.tar.gz', 'dist/go2rpm-1.10.0-py3-none-any.whl')
Uploading distributions to https://upload.pypi.org/legacy/
Uploading go2rpm-1.10.0-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 kB • 00:00 • 1.5 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'go2rpm' isn't allowed. See https://pypi.org/help/#project-name for more information.
Command '['twine', 'upload', PosixPath('dist/go2rpm-1.10.0.tar.gz'),
PosixPath('dist/go2rpm-1.10.0-py3-none-any.whl')]' returned non-zero exit status 1.
```

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://pagure.io/GoSIG/go2rpm/

### Contact and additional research

@eclipseo and I maintain the go2rpm project as part of the Fedora Golang SIG, and I'd like to start publishing the project to PyPI to resolve https://pagure.io/GoSIG/go2rpm/issue/23.

/cc @encukou @hroncok @mikelolasagasti @eclipseo

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by hroncok** [comment]
I approve.

**Comment by mikelolasagasti** [comment]
As `go2rpm` user and contributor (minimal) I also approve this request.

**Comment by gotmax23** [comment]
@encukou, @di, can either of you help with this?

**Comment by encukou** [comment]
I confirm that this is the Fedora package.
@di, can you release the name?

I'm sorry for the delay.

**Comment by di** [comment]
The users `gotmax23` and `eclipseo` are now owner of the `go2rpm` project on PyPI.
