### ISSUE TITLE
File Limit Request: NMMA - 300 MiB

### ISSUE THREAD

**Issue by sahiljhawar** [pypi/support#3637]
### Project URL

https://pypi.org/project/nmma

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

[NMMA](https://www.nature.com/articles/s41467-023-43932-6) is a Nature published state-of-the-art code to analyse Gravitational Waves and Electromagentic signals. We are constantly improving our code to introduce more physics and statisics while keeping best coding practices in mind. Until the previous release our file size was under the limit but due to reccent updates in our tests, CI/CD pipeline and data needed for the tests we are exceeding the size limits as a result the tarball of the project is not getting uploaded on PyPi which will possibly hamper the community usage. Along with test data we also ship some other astrophysical data which is needed when one starts with NMMA. The core developers are already working to make the data file size small in order to be compliant with other computing resources. However, this will take a while due to a number of checks and balances and to be free from any compatibility issues.

### Reasons for the request

Atleast for the next few (2-3) releases we are expecting that our project size will increase slightly, however we will try to keep it under control. But as of now we really need some extra limit to succesfully publish the updates on PyPi.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sahiljhawar** [comment]
@cmaureir Any updates on this?

**Comment by cmaureir** [comment]
Hey @sahiljhawar :wave:
I've set the upload limit for `nmma` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week! :partying_face:
