### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by afiune** [pypi/support#3641]
### PyPI Username

alannix-lw

### Reason for request

Lost 2FA authentication app

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `alannix-lw` has valid recovery codes generated as of 2023-03-10 17:47:42.877450.

Please use those recovery codes to regain access to your account.

**Comment by afiune** [comment]
@ewdurbin Thank you for your answer, unfortunately I no longer have access to those recovery codes and, when I try to log in to create new ones, I need my MFA authentication code, which I also don't have.

![Screenshot 2024-03-22 at 1 40 25 PM](https://github.com/pypi/support/assets/5712253/7dd5677e-c698-4345-8f76-028734d1ea24)

How can I regain access? I do have username and password, but not MFA or recovery codes.

**Comment by afiune** [comment]
FYI - What we are trying to do is remove the version 4.0.0 from our SDK project that we released by mistake:

![Screenshot 2024-03-22 at 1 44 59 PM](https://github.com/pypi/support/assets/5712253/b0c51537-1bed-4d4c-b475-28f7b2141e84)

**Comment by Thespi-Brain** [comment]
Hi @afiune,

I am following up regarding your issue. Are you still having trouble logging in? Let me know, and I will start an account recovery process to reset your recovery codes and 2FA. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
