### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by capitan-ariete** [pypi/support#3643]
### PyPI Username

Shimoku

### Reason for request

I've lost my phone, I just realized I didn't save the 2FA in my Google Auth account and I cannot access Pypi

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `Shimoku` has valid recovery codes generated as of 2023-11-22 12:39:26.631475.

Please use those recovery codes to regain access to your account.

**Comment by Thespi-Brain** [comment]
Hi @capitan-ariete,

I was following up regarding your issue. Are you still having trouble regarding your PyPI account recovery codes? Let me know, and I will start an account recovery process to reset them, thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
