### ISSUE TITLE
PEP 541 Request: calcpy

### ISSUE THREAD

**Issue by idanpa** [pypi/support#3648]
### Project to be claimed

`calcpy`: https://pypi.org/project/calcpy

### Your PyPI username

`idanp`: https://pypi.org/user/idanp

### Reasons for the request

The project is empty.
There is only one empty version from September 2019.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project is empty (links to non-existing repo -[zhiqingxiao/calcpy](https://github.com/zhiqingxiao/calcpy).
I intend to publish in its place [idanpa/calcpy](https://github.com/idanpa/calcpy)

### Contact and additional research

The owner is @zhiqingxiao, tried to contact him by email few times in the past 12 months, and in github by mentioning him in this [issue](https://github.com/idanpa/calcpy/issues/1). Haven't got any answer so far.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ZhiqingXiao** [comment]
Thanks for notifying me of this name conflict. The PyPi project `calcpy` is in use. Could @idanpa consider an alternative PyPi project name? Thanks.

**Comment by idanpa** [comment]
ok

**Comment by idanpa** [comment]
I believe @ZhiqingXiao is name squatting the repo. 
Boilerplate code was added to the repo only after opening this issue here (after 5 years of ownership during which the package being empty). 
9 months have passed, no further activity on the repo and it is still not clear what it is for.

Beside this repo, I see @ZhiqingXiao holds many other repositories with generic names that are empty and left unused since 2019
	https://pypi.org/project/stoch
	https://pypi.org/project/deepmeta
	https://pypi.org/project/drl
	https://pypi.org/project/metarl
	https://pypi.org/project/metalearning
	https://pypi.org/project/nas
	https://pypi.org/project/learnpy
	https://pypi.org/project/stochasticprocess
	https://pypi.org/project/zhiqing
	https://pypi.org/project/treebank
	https://pypi.org/project/bayinf
	https://pypi.org/project/tfprob
	https://pypi.org/project/gymagent
	https://pypi.org/project/symmatrix
	https://pypi.org/project/symmat
	https://pypi.org/project/symtensor

The only reason why
	https://pypi.org/project/calcpy 
is not empty, is this issue. It was put in "use" only after opening this issue and I believe it is name squatting too

@ZhiqingXiao could you please free calcpy?

**Comment by Thespi-Brain** [comment]
Hi @idanpa,

Since the original owner for calcpy has told you the project is still in use, per [PEP 541 rules](https://peps.python.org/pep-0541/#reachability) unfortunately we cannot transfer it to you. I took a look into the other projects of this user and some of them are not "empty" per se, but if you strongly feel that they are namesquatting, you can create a different issue regarding that. Thanks.

**Comment by idanpa** [comment]
@ZhiqingXiao, could you please answer here or to any of my emails? 
Do you have any plans for calcpy usage?
See name squatting in [PEP 541](https://peps.python.org/pep-0541).
