### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tanloong** [pypi/support#3649]
### PyPI Username

tanloong

### Reason for request

Lost both 2FA authentication app and recovery token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `tanloong` has valid recovery codes generated as of 2022-08-20 08:10:43.849831.

Please use those recovery codes to regain access to your account.

**Comment by tanloong** [comment]
I loss the recovery code, is it possible to get another one?


I have the API token for one of my Pypi projects, can I recover my account using that?

---Original---
From: "Ee ***@***.***&gt;
Date: Fri, Feb 23, 2024 23:59 PM
To: ***@***.***&gt;;
Cc: "Tan, ***@***.******@***.***&gt;;
Subject: Re: [pypi/support] Account recovery request (Issue #3649)




 
User tanloong has valid recovery codes generated as of 2022-08-20 08:10:43.849831.
 
Please use those recovery codes to regain access to your account.
