### ISSUE TITLE
PEP 541 Request: python-djvulibre

### ISSUE THREAD

**Issue by FriedrichFroebel** [pypi/support#3650]
### Project to be claimed

`python-djvulibre`: https://pypi.org/project/python-djvulibre

### Your PyPI username

`FriedrichFroebel`: https://pypi.org/user/FriedrichFroebel

### Reasons for the request

The original project has been archived by its owner on GitHub and currently does not install cleanly after `Cython>=3` has been released.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current project: https://github.com/jwilk-archive/python-djvulibre
My fork: https://github.com/FriedrichFroebel/python-djvulibre

### Contact and additional research

The original repository has been archived in October 2022 after the author decided to retire from maintaining the package: https://github.com/jwilk-archive/python-djvulibre/issues/23 In the same step, the *ocrodjvu* project has been retired as well: https://github.com/jwilk-archive/ocrodjvu/issues/46

I am still using *ocrodjvu* and *python-djvulibre* and thus decided to provide a Python 3 port of *ocrodjvu* on PyPI. As *ocrodjvu* depends on *python-djvulibre*, this complicates maintenance without me having access to the *python-djvulibre* project - the only way is to publish and use *python-djvulibre* with another name. Since the release of Cython 3, direct installations of *python-djvulibre* are broken due to insufficient version pinning.

I already tried to contact Jakub, the author and previous maintainer, about this on 2023-01-15 and 2023-03-05 through private e-mail, but never received a reply. On 2023-07-28, I asked publicly at the corresponding issue inside my fork (https://github.com/FriedrichFroebel/python-djvulibre/issues/11), but there has been no reaction on it as well until now.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @FriedrichFroebel,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
Hi @FriedrichFroebel,

The owner of the project has replied back and they do not wish to transfer their project. So, per [PEP 541 rules](https://peps.python.org/pep-0541/#reachability), unfortunately, we cannot approve your request.
