### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jay-sign** [pypi/support#3653]
### PyPI Username

jaysingh

### Reason for request

I am unable to access the authentication app or security token associated with my account. However, I do have access to the email linked to this account. Could you please assist me in recovering access to my account?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `jaysingh` has valid recovery codes generated as of 2023-02-05 10:30:00.495401.

Please use those recovery codes to regain access to your account.

**Comment by Thespi-Brain** [comment]
Hi @jay-sign,

I am following up regarding your issue. Are you still having trouble logging in? Let me know, and I will start an account recovery process for you to reset your account, thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
