### ISSUE TITLE
PEP 541 Request: gramps (Fedora reservation)

### ISSUE THREAD

**Issue by Nick-Hall** [pypi/support#3654]
### Project to be claimed

`gramps`: https://pypi.org/project/gramps

### Your PyPI username

`gramps-project`: https://pypi.org/user/gramps-project

### Reasons for the request

I believe that this project name has been reserved for us.

https://gramps-project.org

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/gramps-project/gramps

### Contact and additional research

No current owner.  The project name is on a banned list.

If possible, would someone also look into our application for an organization account.  I applied for one on 1 Aug 2023.

Thanks for reserving this name for us.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Nick-Hall** [comment]
@encukou I'm letting you know about this as suggested.

**Comment by Nick-Hall** [comment]
@encukou Is there any more information you need from us in order to progress this?

**Comment by Nick-Hall** [comment]
How do we get our project name released? Should I email the support team instead?

**Comment by encukou** [comment]
I confirm that @Nick-Hall is the owner of the Fedora package.
@di, can you release the name?

I'm sorry for the delay.

**Comment by di** [comment]
The user `gramps-project` is now owner of the `gramps` project on PyPI.

**Comment by Nick-Hall** [comment]
Excellent! Thanks for getting this transferred.
