### ISSUE TITLE
PEP 541 Request: `airbyte`

### ISSUE THREAD

**Issue by aaronsteers** [pypi/support#3661]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/airbyte

### Your PyPI username

`USER_NAME`: https://pypi.org/user/airbyte-engineering

### Reasons for the request

TL;DR: We are writing to request a deletion of file names under the `airbyte` project. We can certify that these file names were never used or advertised to users - and their publication was a mistake made by a third party which is not part of Airbyte company. If PyPi could please delete any file names with a version greater than `0.2.1`, this will free us to continue publication of our release.

# Background

I represent the company "Airbyte" and this is in regards to the PyPi library named `airbyte`. We discovered an issue last week when we were preparing to launch our new `PyAirbyte` offering, under the name `airbyte`, which we believed was available to us.

We discovered that one of the companies consulting for us (`Speakeasy`) had mistakenly set up their own test publish pipelines to publish to the `airbyte` project name. This was an error on their part, and the library they were publishing was actually intended to publish as `airbyte-api` - and if fact it was dual-publishing to both project names, under different version numbers. We contacted the vendor and they have deleted their project. We now have taken ownership of this project name but we are blocked from publishing any further versions due to the error:

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         This filename has already been used, use a different version. See      
         https://pypi.org/help/#file-name-reuse for more information.  
```

While we understand there are good reasons for file names to not be deleted in normal circumstances, we hope that in this case an exception can be made.

Thank you for your consideration.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://www.github.com/airbytehq/PyAirbyte

### Contact and additional research

Please see note above. We successfully contacted the previous owner when we realized the mistake. We've also confirmed with them that there are no users of the prior-published versions - they were purely published in error as a test pipeline that was perhaps incorrectly set up at first and never disabled afterwards.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @aaronsteers,

Can you please clarify some more info? If you are already the owner of the project, then even if there are some trailing files, then you should be able to delete them yourself. Or, are you asking us to delete any files/projects from the other vendor that *might* be left over? We don't arbitrarily go ahead and delete stuff from the repo. 

I also noticed a new release of your project has just come out, so wanted to confirm if you are still having this issue, thanks.
