### ISSUE TITLE
Project Limit Request: Panel - 25 GB

### ISSUE THREAD

**Issue by philippjfr** [pypi/support#3673]
### Project URL

https://pypi.org/project/panel/

### Does this project already exist?

- [X] Yes

### New limit

25 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Panel is an open-source Python library that lets you easily build powerful tools, dashboards and complex applications entirely in Python. It has been around for about 5 years and receives about 700k downloads on PyPI a month.

### How large is each release?

Each release currently is about 50 MB which includes a `tar.gz` bundle and a `whl`.

In order for Panel to be useable in an offline context we have to bundle a variety of JS libraries into the package.

### How frequently do you make a release?

We make dev releases a few times a month and actual release every month or two.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by MarcSkovMadsen** [comment]
Ah. This is why Panel `dev` docs currently cannot display properly.
