### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by drateeb** [pypi/support#3679]
### PyPI Username

ateeb

### Reason for request

my mobile phone was snatched on gunpoint; I had to buy a new one. If I had the last one I would have transferred the apps and had access to the two-factor authentication app. Now the situation is different, I do not have that access anymore. My mistake is that I did not save recovery codes, but if I can get my access back I will do that. I am ready to verify through my email and my phone that it is the read Dr. Ateeb who owns this account. It is very important for me because I have hosted EasyDataPy library on my account which helps people download data from state bank of Pakistan's database in Python for data analysis. I shall be thankful if you can help me get my account back. 
Kind Regards,
Dr. Ateeb Syed

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `ateeb` has valid recovery codes generated as of 2024-01-03 16:15:48.473511.

Please use those recovery codes to regain access to your account.

**Comment by Thespi-Brain** [comment]
Hi @drateeb,

I am following up regarding your issue. Are you still having trouble logging in due to lost 2FA and recovery codes? Let me know and I will start an account recovery process for you. Thanks.

**Comment by Thespi-Brain** [comment]
Closing due to non response
