### ISSUE TITLE
File Limit Request: hashcat - 130 MB

### ISSUE THREAD

**Issue by bannsec** [pypi/support#3680]
### Project URL

https://pypi.org/project/hashcat/

### Does this project already exist?

- [X] Yes

### New Limit

130

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Project has been active since 2020, though broken for a few years due to the size issue. I wasn't aware of a process to allow the higher size limit until today so hoping to get things back on track.

The project itself is a deployment of the hash testing tool hashcat. It's very useful to have this deployable via pip since it both allows easy deployment and sets up paths via the entrypoint. I have no control over the size unfortunately as it's bundled from hashcat's official release.

### Reasons for the request

Potentially? If they bundle more functionality into the tool it might grow, but i have no idea if/how much that would be.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @bannsec :wave:
I've set the upload limit for `hashcat` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend! :mammoth:
