### ISSUE TITLE
File Limit Request: leda - 200 MB

### ISSUE THREAD

**Issue by yanovs** [pypi/support#3681]
### Project URL

https://pypi.org/project/leda/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

leda is a python library that converts Jupyter notebooks into static HTML reports. It was first released as an open-source PyPI project in December 2022.

In order to have confidence that code changes don't yield subtle changes in report output, we include reference HTML outputs that we test against in the integration test suite. Unfortunately, these reference outputs take up a significant amount of space in the sdist file. (Note that since this is only needed for testing, we don't include these files in the wheel.)

During the integration tests, there's a output cleaning process that I tried to apply before saving, but it made no significant difference to the size of the sdist.

### Reasons for the request

We'd like to upload an sdist that a user could run integration tests against.

Right now, there are 5 bundles and ~3 variants we test against, but the number of reference files can change as we update compatibility with new versions of plotting libraries, python versions, etc.

Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @yanovs :wave:
I've set the upload limit for `leda` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend! :national_park:

**Comment by yanovs** [comment]
Thanks so much, appreciate it!
