### ISSUE TITLE
File Limit Request: sumo-experiments - 600 MiB

### ISSUE THREAD

**Issue by JulesBompard** [pypi/support#3682]
### Project URL

https://pypi.org/project/sumo-experiments/

### Does this project already exist?

- [X] Yes

### New Limit

600

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The sumo-experiments library implements a python interface for the Simulation of Urban MObility (SUMO) software. It also implements various agents to control intersections within a simulation. 

### Reasons for the request

My wheel file is very heavy since I integrated tensorflow. It is now around 600 MiB (80 before) and I need this new size limit to upload it to Pypi.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `sumo-experiments` to 600 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by JulesBompard** [comment]
Thanks a lot
