### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jiyuuchc** [pypi/support#3684]
### PyPI Username

`jiyuuchc`

### Reason for request

Lost 2FA authentication app (on cell phone). 

I don't have a recovery code.

I can still access my email and I can still upload package with API token. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `jiyuuchc` has valid recovery codes generated as of 2023-11-15 19:47:28.912158.

Please use those recovery codes to regain access to your account.

**Comment by jiyuuchc** [comment]
*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

I found my recovery code and was able to log in again. Thanks and you can close this.


________________________________________
