### ISSUE TITLE
Project Limit Request: light-curve - 20 GB

### ISSUE THREAD

**Issue by hombit** [pypi/support#3686]
### Project URL

https://pypi.org/project/light-curve/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Library for time-series feature extraction in astronomy.

### How large is each release?

Currently ~600MB, but future releases will be reduced to ~300MB due to replacement of individual CPython versions with ABI3-compatible wheels. Individual wheels are ~5MB, due to bundled FFTW, GSL and ceres-solver, x86_64 wheels are ~20 MB due to Intel MKL instead of FFTW.

### How frequently do you make a release?

Roughly every one-two months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @hombit :wave:
I've set the project limit for `light-curve` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :snake:
