### ISSUE TITLE
Project Limit Request: aws-pdk - 50 GiB

### ISSUE THREAD

**Issue by agdimech** [pypi/support#3688]
### Project URL

https://pypi.org/project/aws-pdk/

### Does this project already exist?

- [X] Yes

### New limit

50Gb

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The PDK is a library or CDK/Projen constructs that is distributed to NPM/Maven and PYPI. We release in a full CD manner and as such whenever a commit occurs, this results in a PYPI release. We have not had any issues with npm/maven with regard to 'project sizes'. What is the recommended way to proceed as eventually we will hit the upper bound of the 50Gb limit?

### How large is each release?

20Mb

### How frequently do you make a release?

everytime a code change is merged into mainline (~3 times per week).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi, we've already increased the project size limit to 20GB in https://github.com/pypi/support/issues/3558, and you're only at 10.9 GB at the moment.

> everytime a code change is merged into mainline (~3 times per week).

As mentioned in https://github.com/pypi/support/issues/3558#issuecomment-1978637269, this is too frequent for a project of this size, and looking at https://pypi.org/project/aws-pdk/ you're actually making multiple releases per day (four today alone). We recommend either reducing the frequency of releases, or reducing the distribution size.

Once you've done either of these, and gotten close to the current 20GB limit, please feel free to open a new request, but until then the limit will stand as-is.
