### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kristyhoran** [pypi/support#3692]
### PyPI Username

kristyhoran

### Reason for request

Lost 2FA authentication app and codes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `kristyhoran` has valid recovery codes generated as of 2023-12-13 05:49:42.504156.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Thespi-Brain** [comment]
Hi @kristyhoran,

I am following up regarding your issue. Are you still having trouble regarding your 2FA and recovery codes? It looks like you were recently able to successfully log in, which is great. I will keep this issue open for another week unless I hear from you earlier, thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
