### ISSUE TITLE
File Limit Request: cuda-quantum - 200 MiB

### ISSUE THREAD

**Issue by bmhowe23** [pypi/support#3693]
### Project URL

https://pypi.org/project/cuda-quantum/

### Does this project already exist?

- [X] Yes

### New Limit

200 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

CUDA Quantum is a comprehensive framework for quantum programming. It has been active on PyPi for >6 months, and we are adding significant new features in our upcoming release related to more-native-feeling Python language support for quantum programming using the LLVM/MLIR infrastructure.

### Reasons for the request

Our per-wheel file size for our previous release (0.6.0) was approx 60 MB, and with our new Python language features (that heavily use MLIR for JIT compilation), we are exceeding 100 MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @bmhowe23 :wave:
I've set the upload limit for `cuda-quantum` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :swimmer:

**Comment by bmhowe23** [comment]
Hi @cmaureir - was this change made for TestPyPI, too, or do I need to submit a separate request for that?

**Comment by bmhowe23** [comment]
The reason I ask is that I am unexpectedly getting these errors:
```
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         File too large. Limit for project 'cuda-quantum' is 100 MB. See https://test.pypi.org/help/#file-size-limit for more information.
```
