### ISSUE TITLE
Project Limit Request: thonny-subway-surfers - 1.6 GB

### ISSUE THREAD

**Issue by McBigBob** [pypi/support#3695]
### Project URL

https://pypi.org/project/thonny-subway-surfers/

### Does this project already exist?

- [X] Yes

### New limit

1.6 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is an extension for the Thonny IDE that allows users to enjoy Subway Surfers gameplay alongside their code editor. As of the application date, the project has been active for 1 day. 

The current PyPi version is non-functional due to a dependency on a .gif file required for its operation. Unfortunately, the .gif file is currently too large for inclusion. The GitHub version of this release is working.

### How large is each release?

~1449 MiB total. 1x wheel at ~745 MiB, due to bundled .gif file. The source tarball is at ~745 MiB.

### How frequently do you make a release?

Once every 6 months or when a bug is reported.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rgommers** [comment]
> The current PyPi version is non-functional due to a dependency on a .gif file required for its operation. Unfortunately, the .gif file is currently too large for inclusion. The GitHub version of this release is working.

@McBigBob can you implement a downloader to download the large data file(s) after installing the package from PyPI? This is the recommended way to handle large data files. You can have a look at how for example scikit-learn (with custom code) or scikit-image (via the `pooch` package) handle data files. 

Wheels of 745 MB because of bundled images or other data files are quite unlikely to be acceptable.

**Comment by McBigBob** [comment]
> @McBigBob can you implement a downloader to download the large data file(s) after installing the package from PyPI? This is the recommended way to handle large data files. You can have a look at how for example scikit-learn (with custom code) or scikit-image (via the `pooch` package) handle data files.


@rgommers Yes, I was thinking the same. I implemented a download feature in the new release.


> Wheels of 745 MB because of bundled images or other data files are quite unlikely to be acceptable.

Worth a try at least :D 
I think I will close this issue then.

**Comment by rgommers** [comment]
Thank you!
