### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by uchchwhash** [pypi/support#3697]
### PyPI Username

uchchwhash

### Reason for request

Lost 2FA app/security token (I don't remember getting any recovery codes, maybe I haven't set up my 2FA yet?)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by uchchwhash** [comment]
In case it was not clear in the ticket, I do not have recovery codes.

I am confident I would not have to reach out if I had the recovery codes.

**Comment by uchchwhash** [comment]
My PyPI log in page, when it asks for two-factor authentication, says:

You have not generated account recovery codes.

Which I believe is correct. Let me know what I can do to expedite this process.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
