### ISSUE TITLE
Project Limit Request: https://pypi.org/project/nvidia-dali-cuda110/ - 50 GiB

### ISSUE THREAD

**Issue by JanuszL** [pypi/support#3698]
### Project URL

https://pypi.org/project/nvidia-dali-cuda110/

### Does this project already exist?

- [X] Yes

### New limit

50 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The NVIDIA Data Loading Library (DALI) is a library for data loading and pre-processing to accelerate deep learning applications. It provides a collection of highly optimized building blocks for loading and processing image, video and audio data. It can be used as a portable drop-in replacement for built in data loaders and data iterators in popular deep learning frameworks.

Although it is new to PyPI (August 2022) it has existed for more than 5 years already.

### How large is each release?

300 MB for aarch64 + 500 for x86 wheel

### How frequently do you make a release?

Roughly every month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total size limit for `nvidia-dali-cuda110` to 50 GB on PyPI.

**Comment by JanuszL** [comment]
Thanks @di.
