### ISSUE TITLE
Project Limit Request: Aspose PDF CPP for Python - 10 GB

### ISSUE THREAD

**Issue by rteliuk** [pypi/support#3704]
### Project URL

https://pypi.org/project/aspose-pdf-cpp-for-python/

### Does this project already exist?

- [X] Yes

### New limit

10GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It's an official release of Aspose PDF Cpp https://docs.aspose.com/pdf/cpp/ for Python 
https://products.aspose.com/pdf/python-cpp/
Aspose.PDF it's a library that enables developers to create, read, and manipulate PDF documents without using Adobe Acrobat.
The Python wrapper allows to use of this library from Python.
At this moment the releases will be available for Windows (x64) Linux (x86_64) and MacOSX (x64, arm64) platforms.

### How large is each release?

At this moment we have releases for 4 platforms: Windows (x64) Linux (x86_64) and MacOSX (x64, arm64)
Each of them is ~200-250Mb.
So the total size is ~1Gb

### How frequently do you make a release?

~ 1 release per 1-2 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @rteliuk :wave:
by default the projects have a 10GB limit.
so in case you required a diff increase, feel free to open a new request.
