### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sunshinexcode** [pypi/support#3705]
### PyPI Username

AgoraIO

### Reason for request

Due to a colleague's departure from the company, and the failure to hand over account passwords and email, we have lost access to the account and cannot retrieve it. We hope to continue using the AgoraIO account and hereby apply to recover the email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by plutoless** [comment]
it would also help if we can know the email address.

**Comment by ewdurbin** [comment]
wangzhi@agora.io

**Comment by sunshinexcode** [comment]
We have changed our email. When uploading packages, it reports error 403: New uploads are temporarily disabled. See https://pypi.org/help/#admin-intervention for more information.

**Comment by ewdurbin** [comment]
That's not related to your specific account, it is in response to a malware campaign. Closing as i see you've regained access otherwise.

**Comment by sunshinexcode** [comment]
thanks
