### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by wangzy1982** [pypi/support#3716]
### PyPI Username

wangzy1982

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by wangzy1982** [comment]
I have also lost my Recovery Codes.

**Comment by Thespi-Brain** [comment]
Hi @wangzy1982,

I am following up regarding your request. Are you still having issues regarding your lost recovery codes? Let me know, and I will start an account recovery process for you to reset your account, thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response
