### ISSUE TITLE
File Limit Request: Rofunc - 200 MB

### ISSUE THREAD

**Issue by Skylark0924** [pypi/support#3724]
### Project URL

https://pypi.org/project/rofunc/

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Rofunc package focuses on the Imitation Learning (IL), Reinforcement Learning (RL) and Learning from Demonstration (LfD) for (Humanoid) Robot Manipulation. It provides valuable and convenient python functions, including demonstration collection, data pre-processing, LfD algorithms, planning, and control methods. We also provide an Isaac Gym-based robot simulator for evaluation. This package aims to advance the field by building a full-process toolkit and validation platform that simplifies and standardizes the process of demonstration data collection, processing, learning, and its deployment on robots. The project was created in 2022 and already has 1100+ commits and 280+ stars in GitHub.

### Reasons for the request

The recent package with more functions exceeds the 100MB limitation, and I must update this new release to pypi recently.
![Snipaste_2024-03-09_22-47-42](https://github.com/pypi/support/assets/24936522/469bcad3-6d46-4290-8450-887aecf063cd)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Skylark0924 :wave:
I've set the upload limit for `rofunc` to 200 MB on PyPI.
Have a great week :snake:

**Comment by Skylark0924** [comment]
> Hey @Skylark0924 👋 I've set the upload limit for `rofunc` to 200 MB on PyPI. Have a great week 🐍

Thanks a lot!!!
