### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by 7astro7** [pypi/support#3726]
### PyPI Username

rollo

### Reason for request

Hi, I've lost access to my 2FA authentication app. Can you help me recover my account please?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Thespi-Brain** [comment]
Hi @7astro7,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
