### ISSUE TITLE
Project Limit Request: aws-psycopg2 - 01 GB

### ISSUE THREAD

**Issue by AbhimanyuHK** [pypi/support#3729]
### Project URL

https://pypi.org/project/aws-psycopg2/

### Does this project already exist?

- [X] Yes

### New limit

1 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

From 2019 project available on public.

Combining all OS supporting into single package, this makes more bulk.

### How large is each release?

~200 MB Total

all OS

### How frequently do you make a release?

~4 per years

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
The limit per project is 10GB, so you should be fine. Let us know if you have other request in the feature.
