### ISSUE TITLE
`TestPyPi` account recovery request

### ISSUE THREAD

**Issue by nawtrey** [pypi/support#3731]
### PyPI Username

`nawtrey`

### Reason for request

Lost 2FA authentication app

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Missed that this was for test.pypi.org, I've just gone ahead and reset it.
