### ISSUE TITLE
PEP 541 Request: py360convert

### ISSUE THREAD

**Issue by BrianPugh** [pypi/support#3734]
### Project to be claimed

`py360convert`: https://pypi.org/project/py360convert

### Your PyPI username

`BrianPugh`: https://pypi.org/user/brianpugh

### Reasons for the request

3 years ago the author updated the readme to include:

> A new library including more fuctionality for 360 is under contruction by my colleague. This repo will be depreciated then.

AFAIK, no replacement repo has been created.

2 years ago, I opened a [github issue](https://github.com/sunset1995/py360convert/issues/16) requesting a new pypi release for bugfixes that have been merged in, but not released to pypi. No response.

2 weeks ago, I directly emailed the author the following (email not provided here to help protect his privacy, but can be found from his resume on his personal website):

> Hello!
I was wondering if you could add me as a maintainer to your py360convert repo (both on github, and on pypi)? Just a few minor things need some TLC and a new release on pypi. I have a lot of experience in maintaining python projects, you can check my profile below. Thanks!
https://github.com/BrianPugh
https://pypi.org/user/BrianPugh/
Sincerely,
Brian

If ownership is transferred to me, intend to merge a few existing maintenance PRs and release version(s) to pypi.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Original:
https://github.com/sunset1995/py360convert

New:
https://github.com/BrianPugh/py360convert

### Contact and additional research

Original author's website: https://sunset1995.github.io

He seems busy with some very impressive work at Nvidia.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @BrianPugh,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by sunset1995** [comment]
Hi @BrianPugh and @Thespi-Brain,

Sorry for missing the email. I have add BrianPugh as the maintainer of the pypi and collaborator as the github project. Please let me know if there is anything needed from my side to make this project more useful.

Thanks.

**Comment by BrianPugh** [comment]
Thank you!

**Comment by BrianPugh** [comment]
@sunset1995 can you give me more permissions on both github and PyPI? I'd like to generate a pypi token and add it as a secret for github actions. Thanks!
