### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Yourswear** [pypi/support#3742]
### PyPI Username

598223770

### Reason for request

I set up 2FA yesterday according to the online tutorial, but in that tutorial only helped with the configuration, but did not care about the subsequent login, and I did not save the recovery code, and I could not log in today

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Yourswear** [comment]
I need to use pypi recently, and I hope to get help soon.

**Comment by Yourswear** [comment]
> 用户具有截至 2024-03-13 11：50：27.204091 生成的有效恢复代码。`598223770`
> 
> 请使用这些恢复代码重新获得对您帐户的访问权限。
> 
> 注意：这是自动回复。一般而言，存在有效恢复代码的恢复请求将在发送此回复后 3-4 周内处理。

Unfortunately due to previous focus on setting up 2FA, I didn't save the recovery code

**Comment by Thespi-Brain** [comment]
Hi @Yourswear,

I am following up regarding your issue. Are you still having trouble logging in due to lost recovery codes? Let me know, and I will start an account recovery process for you to reset your account, thanks!

**Comment by Yourswear** [comment]
Yes, the account is still unrecoverable due to the fact that I didn't quite understand how to do it when I first started using it resulting in the loss of the recovery code



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 19, 2024 04:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pypi/support] Account recovery request (Issue #3742)




 
Hi @Yourswear,
 
I am following up regarding your issue. Are you still having trouble logging in due to lost recovery codes? Let me know, and I will start an account recovery process for you to reset your account, thanks!

**Comment by Thespi-Brain** [comment]
Hi @Yourswear,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @Yourswear,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
