### ISSUE TITLE
Project Limit Request: PyBoy - 50 GB

### ISSUE THREAD

**Issue by Baekalfen** [pypi/support#3757]
### Project URL

https://pypi.org/project/pyboy/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Game Boy emulator written in Python. Active for 5 years.

I don't expect releases to increase in size, but I hope to keep making new releases

### How large is each release?

~~Because of the new musllinux wheel having a size of 30MB, a~~ A release becomes around ~~450MB~~ 150MB. I don't bundle anything outside of the PyBoy source code.

### How frequently do you make a release?

Maybe 10-20 times a year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Baekalfen** [comment]
Is it possible to quickly get the limit increased just slightly (500MB or more)? There's a fatal bug in the newest version that I cannot deploy a fix for.

**Comment by Baekalfen** [comment]
I've tried to shrink the binary size as much as I can, by removing .c files that are normally included. This possibly gives a 50% improvement.

**Comment by Baekalfen** [comment]
Wheels are reduced to roughly 5MB, by removing debugging info. This impedes troubleshooting, but I need to deploy.

Still more issues creep up, and I've had to delete old versions of PyBoy on PyPi to deploy fixes. This is not optimal.

**Comment by Baekalfen** [comment]
I've updated the initial post. A release is now estimated at 100MB. This is about a handful of binary wheels for each of Windows, Mac and Linux to support the most recent versions of Python.

**Comment by Baekalfen** [comment]
@di sorry to tag you, but this is causing a lot of issues for the project, and I was told you might be able to help

**Comment by Baekalfen** [comment]
@cmaureir I'm terribly sorry to bother you. I can see you've closed the last limit-request tickets.

I'm getting a little desperate with this. I'm getting a lot of complaints about my package being broken, and I've run out of options to fix it without deploying.

**Comment by cmaureir** [comment]
Hey @Baekalfen :wave:
the problem with issues like this ones, is that the jump from 10GB to 50GB is a lot in term of the amount of projects and sizes that we have around, so they need a more detailed analysis.
I bumped the limit from 10G to 20G in case you are still blocked, but I would like to consider requesting a lower limit or agree with 20G as the new limit, so we can close the issue.
Cheers!

**Comment by Baekalfen** [comment]
> Hey @Baekalfen 👋 the problem with issues like this ones, is that the jump from 10GB to 50GB is a lot in term of the amount of projects and sizes that we have around, so they need a more detailed analysis. I bumped the limit from 10G to 20G in case you are still blocked, but I would like to consider requesting a lower limit or agree with 20G as the new limit, so we can close the issue. Cheers!

20GB might be fine for now. I looked through similar issues, and I couldn't tell if there were any guidelines for limits.

Maybe that's something to add for the template? I.e. do you want maintainers to create a new issue every 3 years, or as I assumed, is it just a stopgap to avoid abuse by anonymous users.

**Comment by cmaureir** [comment]
I'd prefer for you to to open issues after X years to be honest. Project changes very often, and the situation could be very different.
There are no guidelines for how much the increase will be, because each project is different, and the use cases might be more suitable to different approaches of distributing the data within the wheel. As long as the people argument the mechanisms that have not worked to distribute not-so-heavy wheels, or less wheels, there is room to discuss the situation.

Feel free to open a new issue if you reach the project limit and we can continue our discussion.
Have a nice week :snake:
