### ISSUE TITLE
File Limit Request: angry_magpie - 101 MB

### ISSUE THREAD

**Issue by parkukkyu0815** [pypi/support#3776]
### Project URL

https://pypi.org/project/angry-magpie/

### Does this project already exist?

- [X] Yes

### New Limit

204

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The latest version of Buffalo is utilizing OpenBLAS, but there have been errors during build time due to not accounting for OpenBLAS initially. Consequently, I have modified the build process to consider OpenBLAS and made adjustments so that OpenBLAS can be used without requiring system-level installation permissions. This updated version has been uploaded to the project repository.

### Reasons for the request

I'm currently working with a library that requires OpenBLAS to function. Unfortunately, I don't have system privileges to install OpenBLAS on this machine. To circumvent this issue, I've included the OpenBLAS shared libraries within my library. However, I've encountered a file limit restriction. Could you kindly assist in adjusting this limit to accommodate my needs? Your help would be greatly appreciated.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @parkukkyu0815 :wave:
I've set the upload limit for `angry-magpie` to 250 MB on PyPI. Be mindful with releases at that size.
Have a nice week :snake:
