### ISSUE TITLE
PEP 541 Request: codec

### ISSUE THREAD

**Issue by connorlurring** [pypi/support#3777]
### Project to be claimed

`codec`: https://pypi.org/project/codec

### Your PyPI username

`connorl`: https://pypi.org/user/connorl

### Reasons for the request

There is no code in the published library beyond the setup file, and there has been no contributions in the last 9 years.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: https://github.com/metagriffin/codec
Replacement: https://github.com/codec-hq/codec-py

### Contact and additional research

I have tried to contact @metagriffin (https://github.com/metagriffin) through their publicly available email, but received no reply.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by metagriffin** [comment]
hi connor,

my apologies for not responding to your email -- we've been busy this past couple months.

unfortunately, the "codec" package does exist (in a private repository), which we do intend to move into the public domain.

fyi, the replacement package is just as empty.

cheers,
mg

**Comment by Thespi-Brain** [comment]
Hi @connorlurring and @metagriffin,

It sounds like @metagriffin is still maintaining the project, so, per [PEP 541 rules](https://peps.python.org/pep-0541/#reachability), unfortunately, we cannot approve your request.
