### ISSUE TITLE
File Limit Request: triton-xpu - 250 MiB

### ISSUE THREAD

**Issue by pbchekin** [pypi/support#3780]
### Project URL

https://pypi.org/project/triton-xpu/

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is an Intel fork (https://github.com/intel/intel-xpu-backend-for-triton) of Triton project (https://github.com/openai/triton) that adds support for Intel GPUs. We are planning to make a release in the next couple of weeks.

### Reasons for the request

Currently the size of each wheel ~ 200MiB (raw size ~ 500MiB) and potentially will grow for future releases. The wheel size is less than the existing limit of 100MiB. We are not planning to make releases frequently. Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by aregm** [comment]
@cmaureir - who can review this and approve it?

**Comment by aregm** [comment]
@cmaureir - ping?

**Comment by aregm** [comment]
@webknjaz @pradyunsg @di @dstufft - can anyone help us here?

**Comment by webknjaz** [comment]
@aregm spamming random people with mentions is not going to make somebody handling the queue prioritize this over older requests. You'll have to wait.

**Comment by cmaureir** [comment]
Hey @pbchekin  :wave:
I've set the upload limit for `triton-xpu` to 250 MB on PyPI .
Sorry for the delayed response, but this last couple of months I have been busy with other projects.
Cheers!
