### ISSUE TITLE
PEP 541 Request: kafka-python

### ISSUE THREAD

**Issue by wbarnha** [pypi/support#3785]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/kafka-python

### Your PyPI username

`USER_NAME`: https://pypi.org/user/wbarnha

### Reasons for the request

I, and the other maintainer have been trying to reach the original author of the library since September and he has been unresponsive since December. I made a fork at `kafka-python-ng` to facilitate supporting releases in the meantime.

There have been no releases from the project for almost four years, and it is still a core dependency for many projects. The project is currently incompatible with newer versions of Python, which I added support for. Despite adding a proper CI/CD pipeline as the original author requested, we have been unable to get underway with creating a new release. It would be appreciated if the administrators of PyPi could assist with this migration.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

I currently have maintainer access for https://github.com/dpkp/kafka-python and I configured the CI/CD workflow to publish releases once proper permissions are granted.
I forked the project at https://github.com/wbarnha/kafka-python-ng to release changes in the meantime.

### Contact and additional research

I am willing to forward the email chain with the maintainers regarding PEP 541 discussion.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dpkp** [comment]
I own the kafka-python account and do not agree to PEP 541 request. We can continue to manage project maintenance w/o forcible transfers. Thanks.

**Comment by honglei** [comment]
> I own the kafka-python account and do not agree to PEP 541 request. We can continue to manage project maintenance w/o forcible transfers. Thanks.

It seems the update for pypi has been paused for many years. Hope for updates. @dpkp
