### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by diegobit** [pypi/support#3793]
### PyPI Username

ait-it

### Reason for request

The email associated to the account was deactivated and I don't have the password anymore. I need either to access the account in order to change the email, or to have the email changed (with another one, possibly under the same domain) so that I can do the automatic recovery process. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by ewdurbin** [comment]
Contacted via requested address, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by ewdurbin** [comment]
Sorry I used the wrong canned response :)

Your email address on the account has been updated to the one requested. Please follow the password reset email sent and verify your email address to regain access to the account.
