### ISSUE TITLE
File Limit Request: CoRE-MOF - 250 MiB

### ISSUE THREAD

**Issue by fxcoudert** [pypi/support#3795]
### Project URL

https://pypi.org/project/CoRE-MOF/

### Does this project already exist?

- [X] Yes

### New Limit

250 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This package is for scientific software (materials discovery) and includes an internal dataset of optimised materials structures, inherent to the working of its discovery code. The database has been heavily curated and compressed in order to bring it to absolute minimal size, which is currently at ~150 MB. It will grow slightly over time, therefore I added some margin for this in the requested size limit.

We do not expect overly frequent releases, maybe once or twice a year at most, and therefore the total quantity of data will not be huge.

### Reasons for the request

Right now, I am testing a first release on TestPyPI, but when that works the same issue will be encountered in production PyPI. Therefore I am asking for an increase on both indexes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by fxcoudert** [comment]
I'd like to gently ping this. Two releases (2014.1 and 2019.1) were uploaded, but the file current limit is preventing me to publish the 2024.1 release.

**Comment by cmaureir** [comment]
Hey @fxcoudert :wave:
I've set the upload limit for `CoRE-MOF` to 250 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :+1:
