### ISSUE TITLE
Account login prompting for 2factor but I never set it up

### ISSUE THREAD

**Issue by briglx** [pypi/support#3799]
### PyPI Username

briglx

### Reason for request

Login page is asking me to Enter authentication code. However, I've never configured two-factor on the main site. I just configured it today on the test site.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
TOTP 2FA was enabled on your account `2022-02-08 22:35:07.319016 UTC` and a confirmation email was sent to your email address, shortly before a token named `github_cicd` was configured for the `srpenergy` project from the same source ip address and session. Not _recalling_ that you configured 2FA is wholly different than not having set it up.

Regardless, contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by briglx** [comment]
Created a branch

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
