### ISSUE TITLE
Project Limit Request: LMDeploy - 30 GiB

### ISSUE THREAD

**Issue by lvhan028** [pypi/support#3800]
### Project URL

https://pypi.org/project/lmdeploy/

### Does this project already exist?

- [X] Yes

### New limit

30GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

LMDeploy is a toolkit for compressing, deploying, and serving LLM. It has the following core features:

- Efficient Inference: LMDeploy delivers up to 1.8x higher request throughput than vLLM, by introducing key features like persistent batch(a.k.a. continuous batching), blocked KV cache, dynamic split&fuse, tensor parallelism, high-performance CUDA kernels and so on.

- Effective Quantization: LMDeploy supports weight-only and k/v quantization, and the 4-bit inference performance is 2.4x higher than FP16. The quantization quality has been confirmed via OpenCompass evaluation.

It has been activated since July 2023.

LMDeploy has been published 24 times. The total size of its PyPI packages is over 10 GB. And we have to remove the old versions to make new room for the latest release. But, this is not a long-term solution. 

Besides, as new features are continuously added to lmdeploy, the PyPI package size continues to grow, potentially reaching over **150 MB** after some pull requests are merged.

We would be extremely grateful if our request could be granted.

### How large is each release?

The total size of a release is 600+MB.
The files are listed below:
| filename                                            | size    |
|-----------------------------------------------------|---------|
| lmdeploy-0.2.6-cp38-cp38-manylinux2014_x86_64.whl   | 91.4 MB |
| lmdeploy-0.2.6-cp39-cp39-manylinux2014_x86_64.whl   | 91.4 MB |
| lmdeploy-0.2.6-cp310-cp310-manylinux2014_x86_64.whl | 91.4 MB |
| lmdeploy-0.2.6-cp311-cp311-manylinux2014_x86_64.whl | 91.4 MB |
| lmdeploy-0.2.6-cp38-cp38-win_amd64.whl              | 62 MB   |
| lmdeploy-0.2.6-cp39-cp39-win_amd64.whl              | 61.9 MB |
| lmdeploy-0.2.6-cp310-cp310-win_amd64.whl            | 62 MB   |
| lmdeploy-0.2.6-cp311-cp311-win_amd64.whl            | 62 MB   |

### How frequently do you make a release?

Twice a month. We'll change the frequency to once a month when it hits v0.3.0

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by lvhan028** [comment]
Hi, @cmaureir could you please help review this issue?
would appreciate it if this request could be accepted.
If there is anything that I can do, feel free to ask

**Comment by lvhan028** [comment]
Hi, @cmaureir 

We have been working very hard to reduce the size of the binary package, and we have also reduced the frequency of releases, even deleting the earlier versions to make free room. 
However, due to the introduction of Python 3.12, we have to make another package for it. 
What's more, with more and more CUDA kernels being added to optimize the inference performance of the Large Language Model (LLM), the binary package will inevitably become larger and larger. 
To ensure the smooth release of the project, please help us increase the total capacity of the project. Thank you very much.

**Comment by cmaureir** [comment]
Hey @lvhan028 :wave:
Sorry for the delay, I was busy with other community duties.
I've set the project limit for `LMDeploy` to 30 GB on PyPI.
Have a nice week :snake:

**Comment by lvhan028** [comment]
Hi, @cmaureir, thank you so much!
