### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by thejcannon** [pypi/support#3804]
### PyPI Username

thejcannon

### Reason for request

2FA that I set up doesn't seem to be working?

I'm using the app and the PyPI account, but the codes keep getting rejected 😭

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by thejcannon** [comment]
I haven't gotten an email (joshdcannon@gmail.com) yet. Maybe that's a clue 😨

**Comment by thejcannon** [comment]
Still nothing 🫤

I checked inbox, all the little categories, spam, then searched as well for good measure.

**Comment by ewdurbin** [comment]
I sent it again, including a BCC to another gmail account to confirm deliverability and see confirm that it made it (to my gmail inbox).

**Comment by thejcannon** [comment]
Yes success! 

Thank you so much again, will get the ball rolling ASAP

**Comment by Thespi-Brain** [comment]
Hi @thejcannon,

Good news, thanks for completing the verification process. Your 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset. Thanks.

**Comment by thejcannon** [comment]
Y'all are the absolute best ❤️
