### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kjappelbaum** [pypi/support#3811]
### PyPI Username

kjappelbaum

### Reason for request

Lost access to primary email address. I want to set my other email as primary. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The primary email address on the account has been updated to be the existing verified secondary email address, since we can confirm that your existing primary was unverified due to hard bounce.
