### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by marcantonio** [pypi/support#3812]
### PyPI Username

`marcantonio`

### Reason for request

Sorry if this is the wrong forum. I haven't been able to login via two different accounts all day. I don't see maintenance reported. Can you help me out?

Every time I try to login from https://pypi.org/account/login/ I get redirected back to https://pypi.org. The Login link is still in the upper right hand corner. If I click Login again, I am taken to https://pypi.org/account/login/ again, but this time there is a big red banner at the top of the page that says "Session invalidated".

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by marcantonio** [comment]
Updated with more info.

**Comment by jqiuyin** [comment]
+1
same problem

**Comment by marcantonio** [comment]
Resolved here: https://github.com/pypi/warehouse/issues/15711.
