### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mazzalab** [pypi/support#3814]
### PyPI Username

mazzalab

### Reason for request

My profile was hacked. I've received three emails confirming the creation of backup codes, recovery code use, and two-factor authentication enabling.
I cannot enter my profile anymore.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
We have frozen your account. Please contact security@pypi.org regarding this matter.
