### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by BALOGHBence** [pypi/support#3816]
### PyPI Username

BenceBalogh

### Reason for request

The registered email address is invalid and does not exist anymore. I would have to verify a nonexistent email address to be able to add another one.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
We're showing your account as fully setup and with a verified email address and 2FA enabled with a successful login _after_ this ticket was filed.

Are you still requiring support on this issue?

**Comment by Thespi-Brain** [comment]
Hi @BALOGHBence,

I am following up regarding your request. Are you still having an issue regarding your email address and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by BALOGHBence** [comment]
Hi. Thanks for reaching out 🙏 All is good now, the issue can be closed.

**Comment by Thespi-Brain** [comment]
Closing, issue resolved!
