### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by alydersen** [pypi/support#3818]
### PyPI Username

alydersen

### Reason for request

My primary address is unverified and I no longer work at that company. My secondary is verified but I can't do anything (including making the secondary my primary) until I've verified my primary. Please help me rectify this problem.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Your primary address has been updated to be your (previously) secondary address. Since your secondary address was verified and 2FA is enabled on your account.
