### ISSUE TITLE
Project Limit Request: cx_Freeze - 20 GB

### ISSUE THREAD

**Issue by marcelotduarte** [pypi/support#3819]
### Project URL

https://pypi.org/project/cx-Freeze/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Create standalone executables from Python scripts, with the same performance and is cross-platform.
https://github.com/marcelotduarte/cx_Freeze
The project is active for more than 15 years. I've been the maintainer since 2020.

### How large is each release?

~450 MiB total, 22 Linux wheels (supporting x86_64, ppc64le, aarch64) at 12-15MiB, 10 Windows wheels at ~2.1MiB, 8 macOS wheels at ~19MiB. The source tarbal is ~2.9 MB.

### How frequently do you make a release?

Roughly once a month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @marcelotduarte :wave:
I've set the project limit for `cx-Freeze` to 30 GB on PyPI.
Have a nice week :dancers:

**Comment by marcelotduarte** [comment]
Hi @cmaureir Thank you!!!
