### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by grockious** [pypi/support#3821]
### PyPI Username

grockious

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by grockious** [comment]
Thank you @ewdurbin for looking into this

**Comment by ewdurbin** [comment]
Please email support@pypi.org from the email address you would like associated with your account, we'll use that email to proceed with verification. Include a link to this Github issue in the body of the email.

**Comment by Thespi-Brain** [comment]
Hi @grockious,

I have initiated an account recovery process for you at the email address that you have requested. Please follow the instructions to that email and reply to it and we will proceed from there. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @grockious,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
