### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by shohanursobuj** [pypi/support#3823]
### PyPI Username

ShohanurSobuj

### Reason for request

Someone have access to my account and added two-factor authentication
Lost 2FA authentication app or security token

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
As you say this was an unauthorized access, your account has been frozen. Please contact security@pypi.org regarding this matter.
