### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by christer** [pypi/support#3824]
### PyPI Username

`hcs`

### Reason for request

Lost access to email address

and have no validated e-mail connected to my pypi account.

I was about to delete/deprecate all three my projects.
It's not optimal but if you prefer you can remove my account and all three packages instead of recovering the account.

Regards

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please email support@pypi.org from the email address you'd like associated with the account we'll proceed with verification using that address. Please include a link to this GitHub issue in the body of the URL.

**Comment by Thespi-Brain** [comment]
Hi @christer,

I have initiated an account recovery request at the email address that you have provided. Please follow the instructions and reply to that email and we will proceed from there. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @christer,

Thanks for completing the verification process. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
