### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sc2automation** [pypi/support#3825]
### PyPI Username

blizzard

### Reason for request

Lost access to email address

This is a company account for Blizzard Entertainment used in maintaining the PyPi package `s2protocol`
https://pypi.org/project/s2protocol/#history

Unfortunately an employee who is no longer with us had registered the Primary email address as their personal yahoo account. 🤦 We're unable to push updates until this is resolved.

Methods available for authentication:
- I can authenticate by emailing from our organization domain.
- I am also using a company-owned Github account (under Blizzard github org) to open this Issue.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by sc2automation** [comment]
We have also now sent an email referencing this issue to `support@pypi.org`, using the email address we would like to be set as the new primary.

**Comment by Thespi-Brain** [comment]
Hi @sc2automation,

We have set your preferred email as the primary one for the account. You should be able to login and verify the primary email address. Let us know if you have any other issues. Thanks.
