### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by wxnc-haffi** [pypi/support#3827]
### PyPI Username

gsci-pypi

### Reason for request

Registered email is not verified and company it belonged to no longer exists, ownership of repositories was transferred to another entity in 2023 but pypi account was overlooked at the time.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi,

Please email support@pypi.org to provide a new email address that you would like associated with your account. Please reference this link for the github issue as well: https://github.com/pypi/support/issues/3827. Thanks

**Comment by Thespi-Brain** [comment]
Hi @wxnc-haffi,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @wxnc-haffi,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
