### ISSUE TITLE
Project Limit Request: concrete-python - 20 GB

### ISSUE THREAD

**Issue by BourgerieQuentin** [pypi/support#3828]
### Project URL

https://pypi.org/project/concrete-python/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Concrete is an open source framework which simplifies the use of Fully Homomorphic Encryption (FHE).

FHE is a powerful cryptographic tool, allowing computation to be performed directly on encrypted data without needing to decrypt it. With FHE, you can build services that preserve privacy for all users. FHE also offers ideal protection against data breaches as everything is done on encrypted data. Even if the server is compromised, no sensitive data is leaked.

The concrete-python package is the python frontend that allows python developers to turns python programs into their FHE equivalent.

### How large is each release?

~680MB : (macos arm64 (50 MB) + macos x86_64 (50MB) + linux x86_64 (70MB)) * 4 python version 3.8/9/10/11

### How frequently do you make a release?

At least one every three month + some minor version and/or rc

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by BourgerieQuentin** [comment]
Hello, any updates for that?

**Comment by cmaureir** [comment]
Hey @BourgerieQuentin :wave:
I've set the project limit for `concrete-python` to 20 GB on PyPI.
Have a nice week :100:

**Comment by BourgerieQuentin** [comment]
Thanks a lot :rocket:
