### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JamesFraserLogan** [pypi/support#3832]
### PyPI Username

JamesFraserLogan

### Reason for request

Hello,

My name is James and I forgot to enable 2fa and got busy with work. I can't log into my account now to enable 2fa and I couldn't figure out how to do so after browsing the FAQ.

Thanks very much for your time.

Best Regards,

-James

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @JamesFraserLogan,

It looks like you did have 2FA enabled on September 30, 2023. Please try to login again using either your 2FA or recovery codes. Thanks.

**Comment by JamesFraserLogan** [comment]
Hi thanks so much for the reply! I thought I got back to you but I did not,
my apologies.

It was 100% my fault, I heavily use one authenticator for work and I forgot
I use my google one for personal projects.

Again, I really appreciate the time you spent and wish I could buy you guys
coffee/doughnuts for your hard work.

Best Regards,

-James Logan

**Comment by Thespi-Brain** [comment]
Hi, 
Glad to hear you were able to resolve the issue. Appreciate the coffee/doughnuts offer!
