### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Saikyo0** [pypi/support#3834]
### PyPI Username

MrSanchez0

### Reason for request

Lost 2FA authentication app and security token because i got my phone stolen and didnt backup any codes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Saikyo0,

I have initiated an account recovery process and it is being sent to the primary email address associated with your account. Please follow the instructions in the email and reply to it. We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @Saikyo0,

Good news, thanks for completing the account verification process. Your 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset. Thanks.
