### ISSUE TITLE
File Limit Request: sling-mac-universal - 200 MB

### ISSUE THREAD

**Issue by flarco** [pypi/support#3835]
### Project URL

https://pypi.org/project/sling-mac-universal/

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Sling is a CLI tool that extracts data from a source storage/database and loads it in a target storage/database. The python package is actually a wrapper around the original tool made in GoLang. So the binaries are embedded in the pypi package upon release.

This is regarding the mac platform specific package.

See https://slingdata.io

### Reasons for the request

I don't foresee requesting more size increases in the near future. The package has been bordering 100MB for a while now, and has just passed this threshold due to code updates. It's at 105MB now. I am requesting 200MB as a large buffer.

See release workflow failure here: https://github.com/slingdata-io/sling-python/actions/runs/8569916388/job/23486784154
See setup.py here: https://github.com/slingdata-io/sling-python/blob/main/sling_base/sling-mac-universal/setup.py

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by flarco** [comment]
Hi @cmaureir  could you please help with increasing the project limit? We are unable to release the new version due to this.

**Comment by flarco** [comment]
Hi @di or @webknjaz could you please help with increasing the file limit? We are unable to release the new version due to this.

**Comment by webknjaz** [comment]
@flarco no, and spamming random people on the internet won't help this request to be prioritized. You'll have to wait for your turn.

**Comment by flarco** [comment]
@webknjaz thanks for the response. I guess it's about being connected. This issue (https://github.com/pypi/support/issues/3717), for example, was approved in 1 day. So there's not really a concept of a line/turns (it seems), since others have been waiting for months. That's just a long wait time for production usage. Just some friendly feedback. Thanks for all your work.

**Comment by webknjaz** [comment]
Some volunteers handle this. I don't think the order is random. The amount of people who can do this is limited. I don't have such access. Though, the PSF is looking to hire some help soon: https://blog.pypi.org/posts/2024-03-20-announcing-a-pypi-support-specialist/.

**Comment by cmaureir** [comment]
Hey @flarco :wave:
I've set the upload limit for `sling-mac-universal` to 200 MB on PyPI .
Sorry for the delayed response, but this last couple of months I have been busy with other projects.
Cheers!
