### ISSUE TITLE
Project Limit Request: torch - 300-500 GB

### ISSUE THREAD

**Issue by atalman** [pypi/support#3836]
### Project URL

https://pypi.org/project/torch/

### Does this project already exist?

- [X] Yes

### New limit

300-500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

PyTorch is a Python package that provides two high-level features:

Tensor computation (like NumPy) with strong GPU acceleration
Deep neural networks built on a tape-based autograd system
You can reuse your favorite Python packages such as NumPy, SciPy, and Cython to extend PyTorch when needed.

Our trunk health (Continuous Integration signals) can be found at [hud.pytorch.org](https://hud.pytorch.org/ci/pytorch/pytorch/main).

### How large is each release?

6GB

### Current limits

Project size: 139.7 GiB
Project total size limit: 160.0 GiB 

Limit will be reached within 3 releases (in 3 month)

### How frequently do you make a release?

Once a Month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by atalman** [comment]
cc @malfet @seemethere

**Comment by malfet** [comment]
I have an idea how one can decrease a size of each release: by separating python independent and python dependent part of the package

**Comment by atalman** [comment]
@malfet yes let us start working on that, this should also makes it easier for building the packages

**Comment by atalman** [comment]
After release 2.3
Project size: 144.8 GiB
Project total size limit: 160.0 GiB [(request an increase)](https://pypi.org/help/#project-size-limit)

**Comment by atalman** [comment]
After deleting *.post2 releases.

Current limit on pypi:
Project size: 141.4 GiB
Project total size limit: 160.0 GiB

**Comment by DEKHTIARJonathan** [comment]
Hi @cmaureir, if you could help to get the ball moving, it would be immensely useful

**Comment by atalman** [comment]
Hi Pypi team we have found a solution to cut size of the package. However we need to have another package hosted from pypi. Please address these issues:
https://github.com/pypi/support/issues/4378
https://github.com/pypi/support/issues/4379

**Comment by cmaureir** [comment]
Hello @atalman @DEKHTIARJonathan @malfet 
I've set the project limit for `torch` to 300 GB on PyPI. Please be mindful this is now one of the largest projects on PyPI, but I understand how important is for the Python ecosystem.
I would appreciate you can keep this in mind for future releases, and see if other options to split the package further on, or explore the Python Limited API to reduce the amount of wheels for each release.

Have a nice week :100:
