### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jnelson16** [pypi/support#3837]
### PyPI Username

`quantgov`

### Reason for request

Lost access to primary email address (oliver@quantgov.org)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jnelson16,

I have initiated an account verification process at the email that you have provided us. Please follow the instructions to that email and reply to it and we will go from there. Thanks

**Comment by Thespi-Brain** [comment]
Hi @jnelson16,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
