### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by H-xiaoH** [pypi/support#3838]
### PyPI Username

HxiaoH

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @H-xiaoH,

I have initiated an account recovery process and it is being sent to the primary email associated with your account. Please follow the instructions in that email and reply to it. We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @H-xiaoH,

Thanks for proceeding with the verification request. Your 2FA has been reset and a password reset issued and you should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
