### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by beriksson3** [pypi/support#3840]
### PyPI Username

energyincities

### Reason for request

I don't think we set up a 2FA authentication app or security token. Also, I am not sure to which email address this account is linked. If the email address is energyincities@gmail.com, then we still have access to that email account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by beriksson3** [comment]
Any update on this?

**Comment by Thespi-Brain** [comment]
Hi @beriksson3

It looks like this account belongs to Ralph Evins based on https://pypi.org/user/energyincities/. Please reach out to Ralph for access and/or transferring the account since the email address appears to be associated with Ralph. Thanks

**Comment by Thespi-Brain** [comment]
Hi @beriksson3,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by beriksson3** [comment]
Hello,

Yes, I am still not able to log it. Can you help me reset the password and recovery keys, etc. I don't know if Ralph knows the password or recovery codes.


Bryan



________________________________

**Comment by beriksson3** [comment]
Sorry, I never saw this email!


Bryan



________________________________

**Comment by Thespi-Brain** [comment]
Hi @beriksson3,

Can you please provide some more clarification regarding why you are trying to log into Ralph's account? Thanks.

**Comment by beriksson3** [comment]
I no longer work for Ralph, so you can close this ticket.


Bryan



________________________________
