### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by seanrcollings** [pypi/support#3841]
### PyPI Username

`seanrcollings`

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @seanrcollings,

Please contact support@pypi.org with an email address that you would like associated with your account and please reference this link (https://github.com/pypi/support/issues/3841). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @seanrcollings,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @seanrcollings,

Thanks for completing the verification process. The verification was successful! I have updated your primary email address and reset your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
