### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Jakson992** [pypi/support#3843]
### PyPI Username

Yevhenii

### Reason for request

I cant to login and cant reset a pasword.my e-mail addres is yevheniipetrenko92@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Jakson992,

Please contact support@pypi.org with the email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/3843). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @Jakson992,

I am following up regarding your request. Are you still having an issue regarding email address? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
