### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by AndreScaffidi** [pypi/support#3850]
### PyPI Username

andre_scaffidi

### Reason for request

My old institution deleted the email address associated with my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @AndreScaffidi,

Please email support@pypi.org with the email address that you would like associated with your account and we will proceed from there. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @AndreScaffidi,

Also, please reference this issue https://github.com/pypi/support/issues/3850 in your email to us. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @AndreScaffidi,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
