### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rdnve** [pypi/support#3856]
### PyPI Username

rdnve

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @rdnve,

I have initiated an account recovery process for you and an email is being sent to the primary email associated with your account. Please follow the instructions in that email and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @rdnve,

Thanks for completing the verification process. Your 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset. Thanks.

**Comment by rdnve** [comment]
Hello @Thespi-Brain,

Thank you very much! <3
