### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mballance** [pypi/support#3858]
### PyPI Username

mballance

### Reason for request

I lost access to the PyPi 2FA account on my phone, and hadn't generated recovery codes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @mballance,

We have initiated a recovery process for your account. The recovery process email was sent to your primary email address. Please follow the instructions in the recovery process email and reply to that email. We will go from there. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @mballance,

Thanks for going through the verification process. The 2FA on your account has been reset and a password reset issued, and you should be able to regain access to your account after completing the password reset. Thanks!
