### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by machshev** [pypi/support#3860]
### PyPI Username

`machshev`

### Reason for request

Lost 2FA authentication app.
My phone died and I've since moved to cloud backed 2FA to avoid the issue of a single device point of failure again. But I'm stuck right now... no recovery codes available. I'm not sure if these were initially generated or not, but I've refreshed my machine since then and don't have access to them.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @machshev,

We have initiated a recovery process for you and have sent an email to your primary email address associated with the account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @machshev,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
