### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by flopp** [pypi/support#3861]
### PyPI Username

`flopp`

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @flopp,

I have initiated your request and have sent you an email. Please proceed with the instructions sent there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @flopp,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
