### ISSUE TITLE
PEP 541 Request: django-bootstrap-email

### ISSUE THREAD

**Issue by jhthompson** [pypi/support#3864]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/django-bootstrap-email/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/jhthompson

### Reasons for the request

I was able to contact the current maintainer of the project, but he said he was unable to restore his PyPI access. He granted me permission to contact PyPI directly to transfer the name since he has abandoned the project.

I would technically be "replacing" the source code, but the library would still be doing the same thing - taking HTML with Bootstrap classes and performing the necessary compilation steps to get it to render correctly across email clients.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: https://github.com/kpekarov/django-bootstrap-email
Replacement: https://github.com/jhthompson/django-bootstrap-email

### Contact and additional research

Successfully contacted current owner. Emails below:

> Hi Kirill,
> 
> I've recently been working on a Python port of the Ruby bootstrap-email project, and I was hoping to publish a Django template tag to PyPi that uses it with the name "django-bootstrap-email".
> 
> I noticed that you currently have that package name (https://pypi.org/project/django-bootstrap-email/), and if you're no longer using it I was wondering if it would be possible to transfer that project over to me?
> 
> Thanks,
> Jeremy Thompson

> Hi Jeremy
> 
> Sorry, looks like I can't restore access to it.

> No worries, thanks for getting back to me! If the project is inactive, would you be fine with me contacting PyPi to request a transfer of the name?
> 
> Jeremy

> sure

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @jhthompson,

We are working to contact the owner to confirm that they have wanted to transfer this project to you as a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
The Owner has gotten back to us and has confirmed that they wish to have their project transferred. 

I recommend that the PyPI Admins assign @jhthompson  as the new owner of **django-bootstrap-email**.

**Comment by miketheman** [comment]
Added 'jhthompson' as 'Owner' on 'django-bootstrap-email'
