### ISSUE TITLE
Project Limit Request: Flet - 20 GB

### ISSUE THREAD

**Issue by FeodorFitsner** [pypi/support#3865]
### Project URL

https://pypi.org/project/flet/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Flet is a UI framework for Python powered by Flutter.

### How large is each release?

~200 MB.

### How frequently do you make a release?

Once a month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @FeodorFitsner a jump from 10G to 50G looks a bit large.
Due to the release sizes, you will roughly have 2.4 per year, so even with 20G (as new limit) you have enough time to see how the project evolves.

What do you think we set it to 20G?

Let me know!

**Comment by FeodorFitsner** [comment]
Thank you for looking into that!

20GB sounds reasonable - thank you!

**Comment by cmaureir** [comment]
Set to 20GB then.
Have a nice week @FeodorFitsner :+1:
