### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by simontorres** [pypi/support#3866]
### PyPI Username

storres

### Reason for request

My primary email no longer exists. I have a validated secondary email and I would like to setup that one as primary.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by simontorres** [comment]
How significant the amount of time can be?  :'(

**Comment by Thespi-Brain** [comment]
Hi @simontorres,

We have updated your primary email address on your account to the verified one. You should be able to have access with no issues. Thanks.

**Comment by simontorres** [comment]
Thanks a lot for recovering my account. I know you are short of staff so I really appreciate that you took the time to restore my account. Thank once more.
