### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mikkeloscar** [pypi/support#3869]
### PyPI Username

mikkeloscar

### Reason for request

I don't recall setting up 2FA for PyPI. I may have but then I have lost both recovery codes and 2FA app/token.

Can you help me reset 2FA so I again can gain access?

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @mikkeloscar,

I have initiated a recovery request for you and an email has been sent at the primary email address associated with your account. Please follow the instructions and reply to that email and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @mikkeloscar,

Thanks for completing the verification process. Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset. Thanks.

**Comment by mikkeloscar** [comment]
Thanks a lot! It worked! I now again have access to my pypi account 🙏
