### ISSUE TITLE
File Limit Request: wxPythonMeticy - 300 MB

### ISSUE THREAD

**Issue by jmoraleda** [pypi/support#3874]
### Project URL

https://pypi.org/project/wxPythonMeticy/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

wxPythonMeticy is an early access release of wxPython including bug fixes and new features not yet released in the stable distribution. 

[wxPython](https://wxpython.org/) has been active for more than 10 years. The stable release of wxPython at 
https://pypi.org/project/wxPython is on a slow release cycle to PyPI, which prompts many users to simply download wheels from the [nightly snapshot builds](https://wxpython.org/Phoenix/snapshot-builds/).

`wxPythonMeticy` is intended to provide a curated form of early access alternative to the nighly builds, that also allows easier installation as well as full-fledged dependency management as provided by PyPI.

### Reasons for the request

Currently the stable wxPython only adds windows and mac binary wheels. We want to start including manylinux wheels. These wheels require several c/c++ libraries and the total wheel size exceeds 200MB. 

In order to limit the overall space consumed by this early-access version we are taking two actions:

* We plan to keep very few versions available (at most three) and yank and delete older versions, since there is little reason for having an old version of an early access release available for download.
* We intend to limit the versions of python we upload (at most the latest three major ones)  compared to the stable distribution in the spirit of this being an early-access release.

This is an example of the files we want to include in a typical full deployment of wxPythonMeticy:
```
wxPythonMeticy-2024.4.11.0-cp311-cp311-manylinux_2_31_x86_64.whl            (217.1 MB) 
wxPythonMeticy-2024.4.11.0-cp312-cp312-manylinux_2_31_x86_64.whl            (217.3 MB) 
wxPythonMeticy-2024.4.11.0-cp311-cp311-macosx_10_10_universal2.whl          (23.8 MB)                                                              
wxPythonMeticy-2024.4.11.0-cp312-cp312-macosx_10_10_universal2.whl          (23.8 MB)                                  
wxPythonMeticy-2024.4.11.0-cp311-cp311-win32.whl                            (11.6 MB)                                                                  
wxPythonMeticy-2024.4.11.0-cp312-cp312-win32.whl                            (11.6 MB)        
wxPythonMeticy-2024.4.11.0-cp311-cp311-win_amd64.whl                        (13.6 MB)    
wxPythonMeticy-2024.4.11.0-cp312-cp312-win_amd64.whl                        (13.6 MB)    
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @jmoraleda :wave:
I've set the upload limit for `wxPythonMeticy` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size, because you might reach your project limit at some point.
Have you explore other ways to reduce the size of the packages? complementary, you could study the possibility to use the Limited API https://docs.python.org/3/c-api/stable.html in order to reduce the amount of wheels.
Have a nice day 🚀
