### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by yassine20011** [pypi/support#3880]
### PyPI Username

yassine6801

### Reason for request

Lost access to the email address 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @yassine20011,

Please contact support@pypi.org to give us the email address that you would like to have associated with your account. We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
@yassine20011 Also, please refer to this issue https://github.com/pypi/support/issues/3880 in your reply email as a reference to expedite recovery. Thanks

**Comment by yassine20011** [comment]
Ok thank you

**Comment by Thespi-Brain** [comment]
Hi @yassine20011,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by yassine20011** [comment]
Done. Thank you.

**Comment by Thespi-Brain** [comment]
Hi @yassine20011,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
