### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Tomade** [pypi/support#3881]
### PyPI Username

`Tomade`

### Reason for request

Lost 2FA authentication app and security codes! :/ I could reset my password, but now I can't get past the 2FA check. Can you please help? Thank you.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Tomade,

Thanks for your patience. We need to do a bit more research on how to best proceed with your request and we will get back to you shortly.

**Comment by Thespi-Brain** [comment]
Hi @Tomade,

I did some more research and I reset your login and 2FA. You should be able to login and re-set up your 2FA and recovery codes. I will close this issue, but do let us know if you have any more issues, and we can proceed with a new issue. Thanks!

**Comment by Tomade** [comment]
Awesome, thank you so much - I’m good on both Pypi and the test site now.

— Danilo
