### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Mcublog** [pypi/support#3884]
### PyPI Username

ViacheslavK

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Mcublog,

Please contact support@pypi.org with an email address that you would like to be associated with your account and please reference this link (https://github.com/pypi/support/issues/3884). We will proceed from there. Thanks!

**Comment by Mcublog** [comment]
Hi @Thespi-Brain,

Done, sent an email.

**Comment by Thespi-Brain** [comment]
Hi @Mcublog,

Thanks for completing the verification process. The verification was successful! Your email has been updated, and your 2FA has been reset. A password reset has been issued as well. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
