### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by swaschke** [pypi/support#3885]
### PyPI Username

'swaschke'

### Reason for request

Lost access to my email adress 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @swaschke, 

Please contact support@pypi.org with an email address that you would like to have associated with your account and please reference this link (https://github.com/pypi/support/issues/3885). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @swaschke 

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @swaschke,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
