### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by niyue** [pypi/support#3890]
### PyPI Username

`yanhuangdata`

### Reason for request

I received the verification mail for my primary email address (yni@yanhuangdata.com) on year 2021, however, I forgot to click the link to verify the primary email address at that time.

And I tried to setup an auth token for package publishing recently, and it is required to verify the primary email address. I am not able to receive the verification mail for my email address (yni@yanhuangdata.com). 

PyPi website listed that the verification email was sent, however, I am not able to receive the new verification email (and I checked the junk mail box as well). 

Could you please help? Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @niyue,

I checked your account history, and it looks like the email you have provided bounced. Do you have an alternate email address that you would like your account to be associated with? If so, please send that email to support@pypi.org and we will proceed with your account recovery from there. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @niyue,

I am following up regarding your request. Are you still having an issue regarding email address? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by niyue** [comment]
@Thespi-Brain I still have the issue, and I sent an email to [support@pypi.org](mailto:support@pypi.org) previously (on July 18th, 2024 after receiving your response here) via my company email address (yni@yanhuangdata.com) but didn't hear any reply later.

How should I proceed to address this issue? Thanks.

**Comment by Thespi-Brain** [comment]
Hi @niyue,

Yes, I replied back to you asking you to provide another email address, because the .gmail address you provided cannot be used as it is associated with another account. Please send another email to support@pypi.org with an alternate email address that isn't associated with any other PyPI account, thanks.

**Comment by Thespi-Brain** [comment]
Hi @niyue,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @niyue,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
