### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by BobVon** [pypi/support#3891]
### PyPI Username

BobVon

### Reason for request

Hi I've lost access to my 2FA authentication app.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @BobVon,

I have reset your account. You should be able to login and re-setup your 2FA authentication. Let us know if you have any more issues. Thanks.
