### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ccooder** [pypi/support#3892]
### PyPI Username

Aishah

### Reason for request

- Lost 2FA authentication app and lost recovery codes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ccooder** [comment]
Damn it, when will you be able to fix it for me? I’m in a hurry to use my account, or you guys can develop a way to retrieve your account. Damn it.

**Comment by Thespi-Brain** [comment]
Hi @ccooder,

Thanks for your patience. I have initiated an account recovery process and an email is being sent to the address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by ccooder** [comment]
I have already pushed a branch with name which you mailed me

**Comment by Thespi-Brain** [comment]
Hi @ccooder,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
