### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jeanku** [pypi/support#3899]
### PyPI Username

simutil

### Reason for request

1. Lost access to email address
2. no 2FA authentication

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jeanku,

I was unable to find an account with the username that you provided. Is there another username that you think could have been associated with the account? Please let us know and we will proceed from there.

**Comment by jeanku** [comment]
yes, you are right
the account name is:   nbltrust

**Comment by Thespi-Brain** [comment]
Hi @jeanku,

I am following up regarding your request. Are you still having an issue regarding your account's email address? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
