### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lirsacc** [pypi/support#3900]
### PyPI Username

thread-eng

### Reason for request

Lost access to email address.
2FA never setup.

Context: 

This was the account used for the company behind thread.com which went into administration, after which the IP was acquired by Marks And Spencer. The account has been neglected through that process and is now locked. 

We maintain control of the GitHub organisation (https://github.com/thread) which I am a part of still and holds the public packages that are released on PyPI but we have now lost access to the email, although we maintain control of the domain. 

Happy to provide proof / documentation as needed, just a bit unclear on what would help.

Thanks!
Charles Lirsac

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by lirsacc-mns** [comment]
I can't close this myself but it can be.

While we thought getting email working again would take much longer / possibly not be feasible we've actually recovered access for now and can manage the account again. Sorry for the noise.

**Comment by Thespi-Brain** [comment]
Hi @lirsacc, 

That's great to hear that you have recovered access. I will go ahead and close this case.

**Comment by schneiderfelipe** [comment]
Hey @Thespi-Brain! In #4116 I have a similar, but "opposite", issue: I have full access to my e-mail (I have even changed my PyPI password just fine!), but I still can't upload a new version of a library...
