### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by quantology** [pypi/support#3903]
### PyPI Username

`enkratic`

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @encukou,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/3903). We will proceed from there. Thanks!

**Comment by encukou** [comment]
Hi @quantology,
I assume that mention was meant for you :)

**Comment by Thespi-Brain** [comment]
Hi @quantology,

I am following up regarding your request. Are you still having an issue regarding your account's email address? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
