### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by george-moses-accuweather** [pypi/support#3906]
### PyPI Username

george_moses

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @george-moses-accuweather ,

I was unable to find an account associated with the username you provided. Is there another username you think might have used? Let us know and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @george-moses-accuweather,

I am following up regarding your request. Are you still having an issue regarding your account's email address? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
