### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by RobbeNeirynck** [pypi/support#3909]
### PyPI Username

RobNeiry

### Reason for request

I developed some software during an internship at BioLizard, a data science consultancy company. Unfortunately, I made the mistake of creating my PyPi account using my temporary email from BioLizard (robbe.neirynck@lizard.bio). Now that my internship has ended, this email address is no longer active. When logged in to PyPi, I receive the following error message: 'Error: You must verify your primary email address before you can perform this action.' I would like to update my email address to the one I use on GitHub (robbe.neirynck1@hotmail.com). I have recovery codes and access to the authenticator app for further verification if necessary.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @RobbeNeirynck,

I took a look at your account and it looks like you were able to add your preferred email address yourself and verify it, which is great! Would you like me to go ahead and close this issue? Let us know! Thanks.

**Comment by RobbeNeirynck** [comment]
You can indeed close this issue, thx!
