### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Jayclifford345** [pypi/support#3911]
### PyPI Username

jclifford345

### Reason for request

Since moving company, I have lost access to this account. I need to regain access to make my old colleagues maintainers of the project. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Jayclifford345,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/3911). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @Jayclifford345,

I am following up regarding your request. Are you still having an issue regarding accessing your account? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Jayclifford345** [comment]
Hi @Thespi-Brain, sorry for the no reply on this. Everything was recovered by using the original email. Thank you for your time.
