### ISSUE TITLE
Project Limit Request: itk-numerics - 50 GB

### ISSUE THREAD

**Issue by thewtex** [pypi/support#3913]
### Project URL

https://pypi.org/manage/project/itk-numerics/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

We are a large scientific project. We expect 50 GB to be sufficient for many years.

### How large is each release?

We try to keep sizes down, delete old release candidates, but we need a project size increase. We support many platforms. We are putting in a best effort to keep sizes down, including using the Stable ABI in the most recent release.

We provide macOS, Linux, and Windows wheels. x86_64 for all platforms and ARM for macOS and Linux.

Python 3.8+. With the next release, Python 3.11+ use the Stable ABI (3.11 is required for Buffer Protocol Support). Wheels are ~50MB. 

### How frequently do you make a release?

Roughly 3 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @thewtex :wave:
I've set the project limit for `itk-numerics` to 50 GB on PyPI and TestPyPI. 
Have  a nice week :rocket:

**Comment by thewtex** [comment]
@cmaureir thank you!! 🙏
