### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by daolf** [pypi/support#3916]
### PyPI Username

Daolf

### Reason for request

My account was link to this email address: pierre@daolf.com

Unfortunately I lost access to this domain name and to this email address. How can I switch to another email address 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @daolf,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/3916). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @daolf,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @daolf,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
