### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vmoens** [pypi/support#3918]
### PyPI Username

vincent.moens

### Reason for request

Lost access to my PyPI account. 
I have security tokens for twine uploads but I don't know what 2FA to use to login.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @vmoens,

I took a look at your account and your request. You have different types of 2FA set up, so you should be able to use either method and login. Could you please clarify your issue a bit more? That way, I can help solve your issue better. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @vmoens,

I am following up regarding your request. Are you still having an issue regarding logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!
