### ISSUE TITLE
Project Limit Request: pylance - 20 GB

### ISSUE THREAD

**Issue by wjones127** [pypi/support#3920]
### Project URL

https://pypi.org/project/pylance

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

pylance is a library for writing and querying the Lance file format. It supports SQL and vector search.

Our binary size isn't expected to increase meaningfully, but it's possible we might release binaries for additional platforms in the future, which could increase the binary size.

### How large is each release?

~ 140MB right now. We have 5 binaries and each is about 22MB.

Our project is written in Rust and includes the DataFusion SQL engine in the binary.

### How frequently do you make a release?

1-4 times per week. We will look into ways we can reduce this. Possible move to monthly releases with nightly builds hosted elsewhere.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @wjones127 :wave:
I've set the project limit for `pylance` to 20 GB on PyPI.

Have a nice day :snake:
