### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by idkarn** [pypi/support#3921]
### PyPI Username

`lonebug`

### Reason for request

Some time ago I lost access to my email address. Unfortunately I didn't save my account password, so I can't log in to my account and change my mail. I have several ways to prove ownership of the account:
1. My only package links to this account's repository
2. I can provide details of the update history of the package version
3. I have only logged into the account from one device

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @idkarn,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/3921). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @idkarn,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @idkarn,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
