### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by CZW-1122** [pypi/support#3922]
### PyPI Username

xtn

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by CZW-1122** [comment]
你好，我因为第一次使用并没有使用 Google Authenticator 绑定所以无法使用app的验证码，我使用了恢复代码登录也不可以

Hello, because I didn't bind with Google Authenticator when using the app for the first time, I cannot use the verification code. I also tried to log in using the recovery code but it didn't work.

**Comment by Thespi-Brain** [comment]
Hi @CZW-1122,

In order to initiate your account recovery, your projects need to have public repos. Otherwise, there is a 7 day waiting period after the account recovery process is initiated as a security precaution. Let us know how you would like us to proceed. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @CZW-1122,

I am following up regarding your request. Are you still having an issue regarding logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
