### ISSUE TITLE
PEP 541 Request: stratis-cli (Fedora reservation)

### ISSUE THREAD

**Issue by mulkieran** [pypi/support#3925]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/stratis-cli

### Your PyPI username

`USER_NAME`: https://pypi.org/user/mulkieran

### Reasons for the request

There was a Fedora reservation for this project, but the project was never released on PyPI. See https://github.com/pypi/support/issues/355. It has been released continuously in Fedora for several years. See https://src.fedoraproject.org/rpms/stratis-cli.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

There is only one project at https://github.com/stratis-storage/stratis-cli.

### Contact and additional research

I am one of the current owners of the project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mulkieran** [comment]
@encukou Can you sign off on this, please?

**Comment by encukou** [comment]
I can confirm that @mulkieran is the owner of stratis-cli in Fedora; the name should be released.
@di: ping, as per [the Discourse thread](https://discuss.python.org/t/pypi-as-a-project-repository-vs-name-registry-a-k-a-pypi-namesquatting-e-g-for-fedora-packages/4045/23).

**Comment by di** [comment]
Released.
