### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by thrzl** [pypi/support#3926]
### PyPI Username

`mikeyb3`

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @thrzl,

I looked into your account and didn't find any with the username that you provided. However, I did find an account with the same username as your GitHub one. Did you want to try logging in using that username and see if you can get access? If not, we will proceed with alternate steps. Thanks!

**Comment by thrzl** [comment]
Hello, my apologies; the username i put was incorrect. The correct username is `mikeyb`.

**Comment by Thespi-Brain** [comment]
Hi @thrzl,

I am following up regarding your request. Are you still having an issue regarding your account's email address? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
