### ISSUE TITLE
Organizations support

### ISSUE THREAD

**Issue by mr-shekhar** [pypi/support#3931]
### PyPI Username

`nuxeo`

### PyPI Organization name

`Hyland`

### Description of issue

We are unable to reset the password for user `nuxeo`. We are not receiving any password reset mail on maintainers-python@nuxeo.com
The mail id should be maintainers-python@nuxeo.com, as we need to validate the primary-email address for the deployment from [Nuxeo Github](https://github.com/nuxeo/nuxeo-python-client/actions/runs/8749502957/job/24011288299)
```
"HTTPError: 400 Bad Request from
https://upload.pypi.org/legacy/
User 'nuxeo' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See
https://pypi.org/help/#verified-email
for more information.".
``` 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by swetayadav1** [comment]
@encukou Will you help us on this issue as we are stuck with our release

**Comment by encukou** [comment]
Sorry, I am not a PyPI admin so I can't help with this.

**Comment by Thespi-Brain** [comment]
Hi @mr-shekhar and @swetayadav1,

Thanks for your patience. We need to do some more research on your account to proceed with the best course of action. We will get back to you shortly. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @mr-shekhar,

Thanks for your patience as we took a closer look at your account. As part of our account verification process, please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/3931). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @mr-shekhar,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @mr-shekhar,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
