### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by logyca** [pypi/support#3935]
### PyPI Username

tecnologiaeinformacion@logyca.com

### Reason for request

My account was canceled I think due to inactivity. and I was doing an upgrade and creating new related packages and I need to recover the project https://pypi.org/project/logyca/ and the account.

Please help me

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @logyca,

I took a look at your account and it still exists, it has not been canceled. Your PyPI username for the account is actually the same as your GitHub username and not your email address. According to the most recent account history, it looks like you were able to successfully login which is great! Let me know if you are having any other login issues and I will keep this issue open for another week unless I hear from you earlier. Thanks!

**Comment by Thespi-Brain** [comment]
Closing since user didn't get back with any new issues/troubles
