### ISSUE TITLE
Project Limit Request: tccli - 100 GB

### ISSUE THREAD

**Issue by HS-Gray** [pypi/support#3936]
### Project URL

https://pypi.org/project/tccli/

### Does this project already exist?

- [X] Yes

### New limit

100GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

tccli (Tencent Cloud Command Line Interface) is a unified tool for managing Tencent Cloud resources.
It integrates all Tencent Cloud products that support TencentCloud API, and allows you to configure and manage the products. 
It is is active since April, 2018.

### How large is each release?

～15MiB total

### How frequently do you make a release?

Roughly once every day

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @HS-Gray :wave:
The jump from the default 10G to 100G seems a lot.
Would you be OK with a reduced increase to 20-30G instead?
also, have you consider to adopt a different release cycle? daily packages might fill any project limit very fast.

Let me know

**Comment by HS-Gray** [comment]
> Hello @HS-Gray 👋 The jump from the default 10G to 100G seems a lot. Would you be OK with a reduced increase to 20-30G instead? also, have you consider to adopt a different release cycle? daily packages might fill any project limit very fast.
> 
> Let me know

Thank you for your response. Daily release for our project is necessary. But we could clear old package to free space. Is there any interface or other tool for us to delete old package automaticlly? If there's none available, increase to 20-30G is acceptable.

**Comment by cmaureir** [comment]
Got it @HS-Gray 
I have set the new project limit to 30 GB on PyPI.

I'm not aware of any tool to automate that process sadly.
In case you reach a new limit in the future, you can open a new issue so we can continue our discussion.

Have a nice week :snake:
