### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sunavlis** [pypi/support#3937]
### PyPI Username

`harvesters`

### Reason for request

We are working on the handover of the _Harvesters_ project.
Unfortunately, we can not access the **Test PyPI** account anymore because we lost access to email address.

Could you update the e-mail address of the **Test PyPI** account to the Primary e-mail address from the PyPI account? 

Thanks

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @sunavlis,

We are taking a look at your request and doing some research. We will get back to you shortly. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @sunavlis,

I went ahead and updated your primary email address in your Test.PyPI account to match the primary email address on your PyPI account. You should be able to have access to the test account now. Do let me know if you have any other issues. Thanks!

**Comment by sunavlis** [comment]
@Thespi-Brain Thank you very much for your work. I'm now able to login on Test PyPI.
