### ISSUE TITLE
Project Limit Request: cdktf-cdktf-provider-google-beta - 30 GB

### ISSUE THREAD

**Issue by xiehan** [pypi/support#3938]
### Project URL

https://pypi.org/project/cdktf-cdktf-provider-google-beta/

### Does this project already exist?

- [X] Yes

### New limit

30 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[CDK for Terraform](https://cdk.tf) is an open source library that allows you to provision infrastructure through Terraform using native programming languages (TypeScript, Python, Java, C# and Go) as an alternative to HCL. CDKTF users can make use of any/all Terraform providers in their projects. As a convenience and performance optimization, we make certain providers available as [pre-built providers](https://developer.hashicorp.com/terraform/cdktf/concepts/providers#install-pre-built-providers), where we generate the bindings for each language ahead of time and publish them as installable packages for users. `cdktf-cdktf-provider-google-beta` is one such package, which essentially wraps the existing [Google Beta Provider](https://registry.terraform.io/providers/hashicorp/google-beta/latest) with Python bindings to allow it to be used in a CDKTF project.

CDKTF itself has been available in alpha since summer 2020 and went GA on August 1, 2022. We started publishing pre-built providers like `cdktf-cdktf-provider-google-beta` in early 2022. We don't expect individual release sizes to increase significantly in the future, but we do need to be able to continue to publish a weekly release for the foreseeable future, and are currently butting up against the 10GB project size limit.

See the following for previous requests we've had to make for other packages in our ecosystem:
- pypi/support#2332
- pypi/support#2333
- pypi/support#2334

The Google Beta provider is the next-biggest provider we have that hadn't yet obtained a project size limit increase.

### How large is each release?

The `.tar.gz` file is about 14MB and the `.whl` is about 15MB in size. The project size is as minimal as can be; we're not aware of any way to significantly reduce the bundle size.

### How frequently do you make a release?

We do a release when one of the following is true:
- The underlying Terraform provider is updated, which typically happens once a week
- The CDKTF library is updated, which happens on average once a month

There was previously a bug where a new release would be published anytime _any_ underlying dependency was updated, but [we fixed that](https://github.com/cdktf/cdktf-provider-project/commit/7efd53d7448b0a6b1d08d9c3d4b44ba47c97b656) in late 2022 so the above logic holds true for all releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mutahhir** [comment]
👋🏽 Just wanted to quickly bump this issue up. We're unable to publish new versions of the provider. Would really appreciate it if someone could take a look 🙏🏽

**Comment by cmaureir** [comment]
Hey @xiehan :wave:
I've set the project limit for `cdktf-cdktf-provider-google-beta` to 30 GB on PyPI.
Have a nice week :snake:
