### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by k6w** [pypi/support#3939]
### PyPI Username

FAYEZ

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @k6w,

I have taken a look at your account and I have reset your 2FA and recovery codes. You should be able to login as usual. I am closing this ticket, but if you have any more issues, feel free to open a new issue and reach out. Thanks!
