### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by v1v** [pypi/support#3943]
### PyPI Username

elastic-apm-team

### Reason for request

Lost access to the primary email address.

We configured another email, which it's already verified but it cannot be changed to `primary`, as shown in the 

<img width="816" alt="image" src="https://github.com/pypi/support/assets/2871786/3837d738-9f0a-49e3-8c84-1850afbc6874">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @v1v,

I took a look at your account and there are quite a few verified email addresses associated it. Please contact support@pypi.org with an email address that you would like to be the primary one and please reference this link (https://github.com/pypi/support/issues/3943). We will proceed from there. Thanks!

**Comment by v1v** [comment]
Thanks, we managed to get access to the primary email somehow. I'll close this now
