### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kennedyreiS2** [pypi/support#3945]
### PyPI Username

kennreis

### Reason for request

Aplicativo de autenticação 2FA e token de segurança perdido

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @kennedyreiS2,

I took a look at your account and I have reset the 2FA and recovery codes. You should be able to login and set up new 2FA and recovery codes. Let us know if you have any more issues with a new request. Otherwise, I am closing this one. Thanks!
