### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kuyugama** [pypi/support#3947]
### PyPI Username

kuyugama

### Reason for request

Lost access to email address. I deleted email address kuyugamas@gmail.com and created new - mail.kuyugama@gmail.com. But, i forgot to change the email address on pypi.org

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @kuyugama,

Please contact support@pypi.org with the email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/3947). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @kuyugama,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @kuyugama,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by kuyugama** [comment]
> Hi @kuyugama,
> 
> Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

Hi, thanks for your work❤️
