### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tijko** [pypi/support#3948]
### PyPI Username

tijko

### Reason for request

Email address was incorrect

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by tijko** [comment]
To provide some context.  It was merely a matter of having entered a minor typo (although I was next to positive that the email address I provided was input correctly).  The address currently is close but not right and I have no way of "verifying" my account because the confirmation email goes to the wrong address that I do not have access to.

**Comment by Thespi-Brain** [comment]
Hi @tijko,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/3948). We will proceed from there. Thanks!

**Comment by tijko** [comment]
Great, I'll send that out shortly.

Thank you

**Comment by Thespi-Brain** [comment]
Hi @tijko,

Thanks for sending over your preferred email address. I have updated your account and made that email your primary. Please make sure that you can login and set up 2FA and recovery codes. Let me know if you have any more issues. Thanks!

**Comment by tijko** [comment]
Awesome, I appreciate the follow through and I will test this shortly.

**Comment by Thespi-Brain** [comment]
Hi @tijko,

I am following up regarding your request. Are you still having an issue regarding logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
