### ISSUE TITLE
File Limit Request: PyQt6-WebEngine-Qt6 - 120 MB

### ISSUE THREAD

**Issue by philthompson10** [pypi/support#3949]
### Project URL

https://pypi.org/project/PyQt6-WebEngine-Qt6/

### Does this project already exist?

- [X] Yes

### New Limit

120

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is the packaging as a wheel of the Qt6 web-engine library. It is a dependency of the PyQt6-WebEngine Python bindings. The project was created on Oct 3rd 2021 and this is the 21st release.

### Reasons for the request

Each release is likely to be slightly larger than previous ones. With this release the macOS on Intel wheel has exceeded the 100M limit. The macOS on ARM, Linux and Windows wheels are currently just under the limit and have been successfully uploaded to PyPI. An increase to 120M should give adequate headroom for future releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @philthompson10 :wave:
I've set the upload limit for `PyQt6-WebEngine-Qt6` to 200 MB on PyPI.
Have a great week! :tada:
