### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lgelite** [pypi/support#3954]
### PyPI Username

jhoony

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [ ] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @lgelite,

Thanks for your patience. In order for us to initiate an account recovery process, we need to have a current project link to your repo. The project link associated with your account is unfortunately not showing up with anything. Please provide/attach a current link to your account and we will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @lgelite,

I am following up regarding your request. Are you still having an issue regarding your 2FA and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
