### ISSUE TITLE
PEP 541 Request: stopwordstr

### ISSUE THREAD

**Issue by metinoktayd** [pypi/support#3955]
### Project to be claimed

`PROJECT_NAME`: stopwordstr

### Your PyPI username

`USER_NAME`: https://pypi.org/user/meto.ai/

### Reasons for the request

python -m twine upload dist/*

Enter your API token: 'API KEY'

WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more
         information.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/metinoktayd/StopWords-Turkish-Language

### Contact and additional research

https://github.com/metinoktayd/StopWords-Turkish-Language

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @metinoktayd,

Can you please clarify the reasons for your PEP 541 request? Is the project not maintained by anyone at the moment? Is this project abandoned? If this is an existing project, did you try to contact the owner? More clarification is needed before I can proceed with your request, thanks.
