### ISSUE TITLE
Project Limit Request: RDKit - 30 GB

### ISSUE THREAD

**Issue by kuelumbus** [pypi/support#3962]
### Project URL

https://pypi.org/project/rdkit/

### Does this project already exist?

- [X] Yes

### New limit

30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project
A collection of chemoinformatics and machine-learning software written in C++ and Python. New Python versions add ~ 150 MiB 

### How large is each release?

~ 700 MiB total. 10 Linux wheels at ~ 33 MiB, 5 Windows wheels at ~ 21 MiB, 10 MaxOS wheels at ~ 28 MiB.

### How frequently do you make a release?

~ 5 times a year

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by hechth** [comment]
+1 on this issue - actually quite many packages depend on this so would be great if this could be solved soon. Thanks so much!

**Comment by nrontsis** [comment]
+1

**Comment by phytophreak** [comment]
+1

**Comment by kuelumbus** [comment]
@cmaureir and the PyPI team, could you please take a look at this?

**Comment by cmaureir** [comment]
Hey @nrontsis :wave:
Sorry for the delay. I've set the project limit for `RDKit` to 30 GB on PyPI.
Have a great week :rocket:
