### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by alexander-kazanski** [pypi/support#3969]
### PyPI Username

i.go.by.ak

### Reason for request

I accidentally miss typed my email. I missed the "i" it should be atheists.rock55@gmail.com not athests.rock55@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @alexander-kazanski,

I looked into your account and updated your email address. You should be able to log in, but let me know if you are still having issues. I will keep this issue open for a week unless I hear from you earlier with any updates. Thanks!

**Comment by alexander-kazanski** [comment]
Thank you, I am able to sign in.

**Comment by Thespi-Brain** [comment]
Wonderful, I am closing the issue!
