### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by k6w** [pypi/support#3971]
### PyPI Username

Fayez

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Duplicate issue, duplicate to https://github.com/pypi/support/issues/3939. Closing this one.
