### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cpflat** [pypi/support#3977]
### PyPI Username

cpflat

### Reason for request

Lost access to email address

My primary email address was already disabled several years ago.
There is another (non-primary) available email address which is already verified, but PyPI still prevents any actions.
The website says "Verify your email or add a new address.", but it seems there is no way to add a new address or change the primary address.

I would like to request to make the secondary email address (sat@3at.work) to a primary one.
I believe it would be the easiest way.

Thank you in advance.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @cpflat,

Thanks for sending over your preferred email address. We do have an account verification process that is required before we update your primary email, so please send over your preferred email to support@pypi.org and please reference this link (https://github.com/pypi/support/issues/3977). We will proceed from there. Thanks!

**Comment by cpflat** [comment]
Hi @Thespi-Brain,

Thank you for your response.
I sended an email from sat@3at.work (the expected primary address) to support@pypi.org about the information.

**Comment by Thespi-Brain** [comment]
Hi @cpflat,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @cpflat,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
