### ISSUE TITLE
Project Limit Request: agixt - 20 GB

### ISSUE THREAD

**Issue by Josh-XT** [pypi/support#3982]
### Project URL

https://pypi.org/project/agixt/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

AGiXT is an AI agent automation framework. It has been active for over a year. https://github.com/Josh-XT/AGiXT

### How large is each release?

Around 84MB

### How frequently do you make a release?

It depends on how many bugs I miss after I make a release. Usually once or twice a week unless bugs get into releases and a new release is made to fix them. In those cases, I might have several releases in a day when that happens.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Josh-XT :wave:
I've set the project limit for `agixt` to 20 GB on PyPI.
have a great week :tada:
