### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Ethosa** [pypi/support#3984]
### PyPI Username

Ethosa

### Reason for request

I losed access to email that was used in my PyPi account, but I can't change email to new (social.ethosa@gmail.com) until my old email will be verified.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Ethosa,

Thanks for sending over your preferred email in this issue. We do have an account verification process as due diligence so please contact support@pypi.org with your preferred email address and please reference this link (https://github.com/pypi/support/issues/3984). We will proceed from there. Thanks!

**Comment by Ethosa** [comment]
@Thespi-Brain

I send mail to support@pypi.org

**Comment by Thespi-Brain** [comment]
Hi @Ethosa,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @Ethosa,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
