### ISSUE TITLE
Account recovery request - MatHatter

### ISSUE THREAD

**Issue by MatHatter** [pypi/support#3985]
### PyPI Username

MatHatter

### Reason for request

Lost access to email address mfok@stevens.edu. My email is quiksilver67213@yahoo.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by MatHatter** [comment]
the reason is because it was for school and they don't maintain it after you graduate.

**Comment by MatHatter** [comment]
let me know if you need anything more from me.

**Comment by Thespi-Brain** [comment]
Hi @MatHatter,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact support@pypi.org with your preferred email address and reference this link (https://github.com/pypi/support/issues/3985). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @MatHatter,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @MatHatter,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by MatHatter** [comment]
Hi,
Thank you, what do I need to do to do password reset? Just go to the website and request a new password using ***@***.***?
Thank you,
Mathew


Sent from Yahoo Mail for iPhone


On Friday, December 6, 2024, 8:20 PM, thespibrain ***@***.***> wrote:




Hi @MatHatter,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
