### ISSUE TITLE
Project Limit Request: onnxruntime-gpu - 30 GB

### ISSUE THREAD

**Issue by sophies927** [pypi/support#3986]
### Project URL

https://pypi.org/project/onnxruntime-gpu/

### Does this project already exist?

- [X] Yes

### New limit

30 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

ONNX Runtime is a cross-platform runtime accelerator for machine learning models and has been active since 2018.

We have hit the 20GB limit in our 1.17.3 release, which only contains partial files for the full release.
Increasing limit by 30GB should support all future releases in the upcoming years.

### How large is each release?

Each release is 1.5-2 GB, which contains builds for a number of different supported architectures as the product is cross-platform.

### How frequently do you make a release?

Roughly one major release every 3 months + occasional patch releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jywu-msft** [comment]
@cmaureir, would it be possible to process this request and also https://github.com/pypi/support/issues/4085 ?
we've recently had to delete old packages which unfortunately has impacted users e.g. https://github.com/microsoft/onnxruntime/issues/20737
thank you!
there's also a slight tweak to this request. the new limit should be 50GB, if it's increased by 30GB.  That would allow us to support future releases for several years.

**Comment by cmaureir** [comment]
Hey @jywu-msft :wave:
I have set the project limit for `onnxruntime-gpu` to 30GB on PyPI.
will address the other issue as well :+1: 
Have a nice week :dancers:
