### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ManiMozaffar** [pypi/support#3989]
### PyPI Username

mani_mozaffar

### Reason for request

I have access to my email address, but i lost my 2fa and recovery code. I didn't have my "recovery codes" at all.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ManiMozaffar** [comment]
Hey @ewdurbin, sorry for tagging, I'mm maintainer of some open source repos, isn't there some way to automate this workflow? because as far I know next step would be an email sent to my email address. Or connect pypi account to github? that would be very useful for recovery process.

**Comment by Thespi-Brain** [comment]
Hi @ManiMozaffar,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by ManiMozaffar** [comment]
Hi thanks :) Responded to the email.

Rgards

**Comment by Thespi-Brain** [comment]
Hi @ManiMozaffar,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
