### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by brunofaria1322** [pypi/support#3992]
### PyPI Username

bfaria

### Reason for request

Hi, I've just registered on the Test Pypi website. After registering, I noticed that I misspelled my e-mail address. Now, I can't add a new email or verify the misspelled email, since it doesn't exist. I cant even delete my account! 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @brunofaria1322,

We need to do some more research regarding your Test PyPI account. We will get back to you shortly, thanks for your patience!

**Comment by Thespi-Brain** [comment]
Hi @brunofaria1322,

I am following up regarding your request. Are you still having an issue regarding your account's email address? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
