### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mbuttner** [pypi/support#3994]
### PyPI Username

maren.buettner

### Reason for request

Primary email address has been deactivated. Secondary email address could be verified. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by mbuttner** [comment]
Hi there, 
I still cannot do anything with my PyPI account. My **primary** e-mail address has been deactivated. I have a **verified** secondary e-mail address, but I have no option to switch to the secondary e-mail address. Please help!

**Comment by mbuttner** [comment]
I would really like to update my package as it is a dependency for other projects, see https://github.com/scverse/pytometry/issues/69

**Comment by Thespi-Brain** [comment]
Hi @mbuttner,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](url) with your preferred email address and reference this link (https://github.com/pypi/support/issues/3994). We will proceed from there. Thanks for your patience!

**Comment by Thespi-Brain** [comment]
Hi @mbuttner,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @mbuttner,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
