### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jtiosue** [pypi/support#3999]
### PyPI Username

`jiosue`

### Reason for request

Lost access to email address

I have a project "qubovert" on PyPI (https://pypi.org/project/qubovert/, source https://github.com/jtiosue/qubovert). I am unable to edit anything because I no longer have access to my old email. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jtiosue,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/3999). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @jtiosue,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @jtiosue,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
