### ISSUE TITLE
Project Limit Request: OpenDAL - 100 GB

### ISSUE THREAD

**Issue by Xuanwo** [pypi/support#4001]
### Project URL

https://pypi.org/project/opendal/

### Does this project already exist?

- [X] Yes

### New limit

100 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

[OpenDAL](https://github.com/apache/opendal) offers a unified data access layer, empowering users to seamlessly and efficiently retrieve data from diverse storage services. Our goal is to deliver a comprehensive solution for any languages, methods, integrations, and services.

The package [opendal](https://pypi.org/project/opendal/) is the python binding for this project. We are taking following actions to reduce the release size:

- Build target to `abi3`
- Remove not supported python versions
- Split into different packages.

But we can expect the project size will keep growing in the future.

### How large is each release?

Our last successful release have 42 files, the total size is almost 2GiB. They includes:

52MiB per artifacts * python versions (cpython 3.6 to cython 3.12, pypy) * platforms (linux, macos, windows) * arch (x86, aarch, ...)

### How frequently do you make a release?

Once or twice per month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Xuanwo :wave:
A jump from the default 10G to 100G is a lot.
Would you be OK with an increase to 20-30G ?
Because you are already working on the abi3 target, the amount of wheels will be reduced in the future, so you might now reach a larger project size like you are currently facing.

Let me know

**Comment by cmaureir** [comment]
Got it @Xuanwo 
I have set the new project limit of `opendal` on PyPI and TestPyPI to 30 GB.
Have a nice week :snake:

**Comment by Xuanwo** [comment]
> Got it @Xuanwo 
> 
> I have set the new project limit of `opendal` on PyPI and TestPyPI to 30 GB.
> 
> Have a nice week :snake:

Thanks!
