### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jeremystretch** [pypi/support#4006]
### PyPI Username

jeremystretch

### Reason for request

Hi, it appears that I'm unable to update my primary email address as the old email is unreachable. I just need to designate the new email address as primary for the account and delete the old one. Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jeremystretch,

As part of our security protocols, please contact support@pypi.org with your preferred/new email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4006). We will proceed from there. Thanks!

**Comment by jeremystretch** [comment]
:+1: Done!

**Comment by Thespi-Brain** [comment]
Hi @jeremystretch, 

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @jeremystretch,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
