### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mgautierfr** [pypi/support#4010]
### PyPI Username

`mgautierfr`

### Reason for request

I've lost 2FA authentication and security token.
In fact, I not even sure I've configured one. Or it was so old that I've forget about it.

I still have access to my email address.

Thanks for your help.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @mgautierfr,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by mgautierfr** [comment]
Thanks @Thespi-Brain 

Instructions in the mail followed and I have reply to it.

**Comment by Thespi-Brain** [comment]
Hi @mgautierfr, 

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by mgautierfr** [comment]
Everything ok now. Thank you !
