### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gwwerner** [pypi/support#4013]
### PyPI Username

reply_pro

### Reason for request

Lost access to email address martin.ronquillo@replypro.io. I would like to change it to backend@engineering.replypro.io.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by gwwerner** [comment]
I do have access to some 2FA recovery codes.

**Comment by Thespi-Brain** [comment]
Hi @gwwerner,

Thanks for sending over your preferred email in this issue. However, we do have an account verification process as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4013). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @gwwerner,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @gwwerner,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
