### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by TarjinderSingh** [pypi/support#4014]
### PyPI Username

tsingh

### Reason for request

Lost access to email address. I can log into the account, but cannot add a new email address or set up new methods of authentication.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @TarjinderSingh,

Please contact support@pypi.org with a new email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4014). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @TarjinderSingh,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by TarjinderSingh** [comment]
I pushed a new branch to the required repo. Thank you!

**Comment by Thespi-Brain** [comment]
Hi @TarjinderSingh,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
