### ISSUE TITLE
PEP 541 Request: Rename ibisml to ibis-ml

### ISSUE THREAD

**Issue by deepyaman** [pypi/support#4015]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/ibis-ml

### Your PyPI username

`USER_NAME`: https://pypi.org/user/deepyaman

### Reasons for the request

Hello!

I have recently taken over development of IbisML, which was previously a work-in-progress library. A colleague (existing maintainer of [`ibisml` ](https://pypi.org/project/ibisml)) added me as a maintainer, so there's no transfer of ownership required.

We would like to rename the project to `ibis-ml` (the package itself has already been renamed to be imported as `ibis_ml` on GitHub), to align with how we name projects across the Ibis ecosystem, and also to avoid people pronouncing it as one word. However, I can't publish a package named `ibis-ml`, as it is too similar to an existing project. The comment from @di on https://discuss.python.org/t/are-the-names-for-deleted-projects-retained-on-pypi/29384/4 also makes me believe that deleting `ibisml` from PyPI myself will not solve this.

Is it possible for somebody to rename `ibisml` to `ibis-ml` on PyPI, or to delete `ibisml` fully so as to clear my publishing a new `ibis-ml` package? I don't care if the existing releases become unavailable (as they would have in the case of deletion).

Thank you!

Best regards,
Deepyaman

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/ibis-project/ibis-ml

### Contact and additional research

Other owners have already been contacted, and I have been added as an owner.

The only semi-consistent alternative I can think of to this would be to have people `pip install IbisML` and get the package named `ibis_ml`, but I really don't want to introduce a weird camel capitalization just because I can't hyphenate the project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by raulcd** [comment]
@cmaureir can you help us with this?

**Comment by di** [comment]
Hi, since `ibis-ml` was being blocked only due to the presence of `ibisml`, I've made the name available to `deepyaman` for publishing and you should see it in your lists of projects now.

Note that PyPI does not support renaming existing projects, the best course forward is to leave the old project in place and publish future releases at the new project name. You might also want to make one last release of `ibisml` that has a dependency on `ibis-ml`. More details are here: https://stackoverflow.com/questions/61363534/whats-the-recommended-way-of-renaming-a-project-in-pypi

**Comment by deepyaman** [comment]
Thank you, this is ideal!

> Note that PyPI does not support renaming existing projects, the best course forward is to leave the old project in place and publish future releases at the new project name. You might also want to make one last release of `ibisml` that has a dependency on `ibis-ml`. More details are here: https://stackoverflow.com/questions/61363534/whats-the-recommended-way-of-renaming-a-project-in-pypi

Will make sure to do so.
