### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by akaszynski** [pypi/support#4016]
### PyPI Username

`pyvista`

### Reason for request

I need to have our primary email address switched to pyvista@gmail.com.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @akaszynski,

I took a look at your account and it looks like you were already able to update your primary email, which is awesome! Are you having any other login/access issues? I will keep this issue open for another week just in case. Let me know, thanks!

**Comment by akaszynski** [comment]
Got this figured out. You can close this.
