### ISSUE TITLE
Request for Account Recovery Assistance

### ISSUE THREAD

**Issue by siddharthdis** [pypi/support#4018]
### PyPI Username

siddharthdis

### Reason for request

I am experiencing difficulty accessing my PyPI account due to challenges with two-factor authentication (2FA). Despite numerous attempts, I am unable to generate the necessary passkeys, resulting in login failures. As PyPI is integral to my work and project contributions, resolving this issue promptly is crucial. Therefore, I kindly request assistance with either disabling 2FA temporarily or resetting my account credentials. This will enable me to regain access and continue utilizing PyPI effectively. I assure you of my commitment to account security and will take necessary precautions once access is restored. Your prompt assistance in this matter would be greatly appreciated

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @siddharthdis,

I have initiated an account recovery process to help with the 2FA recovery and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @siddharthdis,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
