### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by DinoThor** [pypi/support#4020]
### PyPI Username

DinoThor

### Reason for request

Wrong email used in the register form
Need to be: aaron.raya.lopez@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @DinoThor,

I took a look at your account, and it seems like you were able to update your email address to your preferred one, which is great! I am closing this issue, but if you have any other login issues, let us know. Thanks!
