### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Javierunal16** [pypi/support#4028]
### PyPI Username

Javierunal16

### Reason for request

Dear PyPI team,

My phone broke a few weeks ago, so I lost my authentication app as well as my recovey codes (my backups failed). I urgently need to acess my account since I need to update a package for an upcoming scientific article review. Please let me know what can be done to recover acess to my account.

Best,

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Javierunal16,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
