### ISSUE TITLE
PEP 541 Request: lcm

### ISSUE THREAD

**Issue by nosracd** [pypi/support#4031]
### Project to be claimed

`lcm`: https://pypi.org/project/lcm

### Your PyPI username

`Nosracd`: https://pypi.org/user/Nosracd

### Reasons for the request

As described on [the project page](https://pypi.org/project/lcm/), it is based on [a fork](https://bitbucket.org/frostlab/lcm) of the [official LCM project](https://github.com/lcm-proj/lcm). Also it appears to be abandoned because:

- It is not based on the most recent release
- It hasn't been pushed to in several months
- I've tried contacting the maintainers and haven't been able to get response

I am one of the maintainers of the official LCM project and would like to claim the PyPi LCM project so I can upload updated packages, based on the most recent release with compatibility for more recent versions of Python and OSes.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The current repository is this fork: https://bitbucket.org/frostlab/lcm/commits/branch/master
I intend to replace it with the upstream: https://github.com/lcm-proj/lcm

### Contact and additional research

On March 13 2024 I sent an email to Easton Potokar (eastonpots@byu.edu is the address listed for him on BYU's website) since [his profile](https://pypi.org/user/contagon/) is listed as an LCM maintainer on PyPi.

On April 25 2024 I sent an email to Joshua Mangelson (mangelson@byu.edu), since he [is listed under the contact info](https://frostlab.byu.edu/) for FRoSt Lab at BYU.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nosracd** [comment]
@di, pinging you because it looks like you usually handle these. Do you need anything more from me in order to complete this? Thanks in advance for your help!

**Comment by Thespi-Brain** [comment]
Hi @nosracd,

I took a look into this project and it looks like you are already an Owner? If your PEP 541 request is fulfilled, let me know and I will go ahead and close it, thanks.
