### ISSUE TITLE
File Limit Request: `aphrodite-engine` - 500 MB

### ISSUE THREAD

**Issue by AlpinDale** [pypi/support#4036]
### Project URL

https://pypi.org/project/aphrodite-engine

### Does this project already exist?

- [X] Yes

### New Limit

500 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Aphrodite Engine is an LLM inference library. The biggest contributor to the wheel size is the compiled binaries for the CUDA kernels.

### Reasons for the request

We have a lot of compiled CUDA kernels that need to be packaged, which inflates the wheel size. We expect the wheel size to grow to 500 MiB within the next few months, but unlikely to increase more than that. It's difficult to reduce the size without cutting down on functionality and support for older GPU architectures.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @AlpinDale :wave:
I've set the upload limit for `aphrodite-engine` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size, and explore other ways of distributing the kernels so they don't inflate the size of each package.
Have a nice week :tada:
