### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by shadi-attarha** [pypi/support#4037]
### PyPI Username

sattarha

### Reason for request

Hi, my authentication app (TOTP) has been deleted, and I lost access to my account. can you please help me to recover it 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @shadi-attarha,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by shadi-attarha** [comment]
Thanks. I replied to that email and confirmed my request to restart my PyPi
account.

Thanks
Shadi

**Comment by Thespi-Brain** [comment]
Hi @shadi-attarha,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
