### ISSUE TITLE
Project Limit Request: pypowsybl - 50 GiB

### ISSUE THREAD

**Issue by HugoKulesza** [pypi/support#4040]
### Project URL

https://pypi.org/project/pypowsybl/

### Does this project already exist?

- [X] Yes

### New limit

50GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

PyPowSyBl is a python library for power grid modelling and simulation. It is a python binding for the [PowSyBl](https://www.powsybl.org/) framework. 

It has been active since the beginning of 2021. 

### How large is each release?

Each wheel has a size of around 50MB. It consists almost entirely of a compiled native library to use powsybl. 

Since the release is done for 5 Python versions and 3 platforms (Windows, Mac, Linux), each release is ~750MB. 

We want in the future to add builds for arm64 infrastructure that would bring the total size of each release to ~1GB. 

### How frequently do you make a release?

Releases are done around every 2 months, not including potential corrective releases that sometimes must be done after normal releases. In general, at least 8 to 10 releases are done every year. 

50GB of space would then allow us to have around 5 years of releases stored at the same time (even with the upsized releases with arm64 builds). 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jmertic** [comment]
Hi @HugoKulesza - seeing if there is anything more you need from us to process this - thank you!

**Comment by cmaureir** [comment]
Hello @HugoKulesza :wave:
I've set the project limit for `pypowsybl` to 50 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
