### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Dynamic-Mobile-Security** [pypi/support#4042]
### PyPI Username

DynamicMobileSecurity

### Reason for request

Lost access to email address dynam1c.m0b1l3@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Dynamic-Mobile-Security** [comment]
Hi! 

Any updates?

**Comment by Thespi-Brain** [comment]
Hi @Dynamic-Mobile-Security,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4042). We will proceed from there. Thanks!

**Comment by Dynamic-Mobile-Security** [comment]
Hi!

Send an email to that address from my new email assosiated with my account!

Waiting for your response. Thank you!

**Comment by Dynamic-Mobile-Security** [comment]
Sorry, missclick on "Close button"

**Comment by Thespi-Brain** [comment]
Hi @Dynamic-Mobile-Security,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @Dynamic-Mobile-Security,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
