### ISSUE TITLE
File Limit Request: Hilton_Elite_Dev - 000 MB

### ISSUE THREAD

**Issue by HiltoneliteDev** [pypi/support#4044]
### Project URL

https://pypi.org/manage/unverified-account/?next=%2Fmanage%2Fprojects%2F

### Does this project already exist?

- [X] Yes

### New Limit

Na

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

I just want to correct my sign up email corrected. It should be Terryhiltonbusiness@mail.com
Not Terryhiltonbusiness@gmail.com

### Reasons for the request

I'm new and someone should do something about making this whole operationorw user friendly. Its to difficult just to chane a email before it verification. Slow down productively and discouraged people

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by HiltoneliteDev** [comment]
Apologies for the incorrectly grammar. I was irritated and typing fast

**Comment by cmaureir** [comment]
Hey @HiltoneliteDev :wave:
you used the wrong template for this request. File another issue with the correct one please, this is for file requests.
