### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mitsh** [pypi/support#4049]
### PyPI Username

mit

### Reason for request

my yubikey broke and I don't have recovery codes. could you please help with that so I can access my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @mitsh,

I have reset your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. I will still keep this issue open for another week, unless I hear from you earlier. Thanks.

**Comment by mitsh** [comment]
Thank you @Thespi-Brain! I've managed to login my account.
