### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by thja-pml** [pypi/support#4050]
### PyPI Username

`thja`

### Reason for request

Lost access to email address (due to change of workplace)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @thja-pml,

I took a look at your account and it seems like you were able to add an alternate, primary email address successfully, which is awesome. Are you still having issues logging in? Let me know, thanks!

**Comment by thja-pml** [comment]
All sorted now thank you.

**Comment by Thespi-Brain** [comment]
Wonderful, I am closing the issue!
