### ISSUE TITLE
Project Limit Request: transformer-engine-cu12 - 20 GiB

### ISSUE THREAD

**Issue by ksivaman** [pypi/support#4052]
### Project URL

https://pypi.org/project/transformer-engine-cu12/

### Does this project already exist?

- [X] Yes

### New limit

20 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

TransformerEngine is a library for accelerating Transformer models on NVIDIA GPUs, including using 8-bit floating point (FP8) precision on Hopper and Ada GPUs, to provide better performance with lower memory utilization in both training and inference.

Although it is new to PyPI (May 2023), it has existed as an open source project on GitHub since 28th September 2022.

### How large is each release?

1 wheel each for aarch64 and x86, roughly 350MB per wheel for a total of 700 MB.

### How frequently do you make a release?

Monthly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @ksivaman :wave:
I've set the project limit for `transformer-engine-cu12` to 20 GB on PyPI.
Have a nice week :snake:
