### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by thegreekgoat98** [pypi/support#4056]
### PyPI Username

thegreekgoat98

### Reason for request

Unfortunately, while giving my mail, I have given @gmil.com instead of gmail.com. Now I cannot get code to verify my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @thegreekgoat98,

It looks like you were able to successfully create another account with the correct email. I will close this issue as resolved, but do let me know if there are any other login troubles. Thanks.
