### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Quan666** [pypi/support#4063]
### PyPI Username

quan666

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via email address on the account, but received a bounce notification.

Confirmation steps were sent to the requested address, please read the instructions and reply to proceed with recovery.

**Comment by Quan666** [comment]
> Contacted via email address on the account, but received a bounce notification.
> 
> Confirmation steps were sent to the requested address, please read the instructions and reply to proceed with recovery.

Hello, what should I do next? I didn't receive the confirmation step, where did it go? I can't log in to my pypi account now, why is that?

**Comment by Quan666** [comment]
> Contacted via email address on the account, but received a bounce notification.
> 
> Confirmation steps were sent to the requested address, please read the instructions and reply to proceed with recovery.

I have confirmed following the required steps, thank you.

**Comment by Thespi-Brain** [comment]
Hi @Quan666,

Thanks for confirming the verification process. Your preferred email address has been added to the account. A password reset has also been issued. Please go through the password reset process and you should be able to login using your preferred email address. Let us know if you have any more issues. Thanks.
