### ISSUE TITLE
Project Limit Request: Ctranslate2 - 50 GB

### ISSUE THREAD

**Issue by minhthuc2502** [pypi/support#4067]
### Project URL

https://pypi.org/project/ctranslate2/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This is a C++ and Python library for efficient inference with Transformer models. It has been active since 2018. It is one of most powerful framework for the inference of Transformer models.

### How large is each release?

~2GB in total. ~200 MB for Linux release for each python version (3.8, 3.9, 3.10, 3.11, 3.12), so ~1GB in total for all version. ~150 MB for Windows release for each python version, so 0.75 GB and ~50 MB for Macos release for each python version, so 0.25 GB.

### How frequently do you make a release?

Once every 2 months or more.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by minhthuc2502** [comment]
Hello @cmaureir , Can you see if our project can upgrade the limit size? The project has been active since 2018 so we exceeds 20 GB. I appreciate your help. Thank you a lot in advance.

**Comment by cmaureir** [comment]
Hey @minhthuc2502 :wave:
I've set the project limit for `ctranslate2` to 50 GB on PyPI and TestPyPI. Please be mindful of the frequency of releases and your new project limit.
Have a nice week :rocket:

**Comment by minhthuc2502** [comment]
Thank you for your help. Have a nice week!!!
