### ISSUE TITLE
File Limit Request: cuda-quantum - 200 MiB

### ISSUE THREAD

**Issue by bmhowe23** [pypi/support#4069]
### Project URL

https://pypi.org/project/cuda-quantum/

### Does this project already exist?

- [X] Yes

### New Limit

200 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

**This is actually a clone of #3693. That request was approved, but when trying to upload our latest release (0.7.1) to TestPyPI, it is rejecting it for the file size even though it is only 105 MB, which is less than the previously approved limit of 200 MB.**

Copied from prior request:
_CUDA Quantum is a comprehensive framework for quantum programming. It has been active on PyPi for >6 months, and we are adding significant new features in our upcoming release related to more-native-feeling Python language support for quantum programming using the LLVM/MLIR infrastructure._

### Reasons for the request

**This is actually a clone of #3693. That request was approved, but when trying to upload our latest release (0.7.1) to TestPyPI, it is rejecting it for the file size even though it is only 105 MB, which is less than the previously approved limit of 200 MB.**

Copied from prior request:
_Our per-wheel file size for our previous release (0.6.0) was approx 60 MB, and with our new Python language features (that heavily use MLIR for JIT compilation), we are exceeding 100 MB._

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by bmhowe23** [comment]
This is the error message that is being shown:
```bash
$ python3 -m twine upload --repository testpypi cuda_quantum-0.7.1-cp310-cp310-manylinux_2_28_x86_64.whl
Uploading distributions to https://test.pypi.org/legacy/
Uploading cuda_quantum-0.7.1-cp310-cp310-manylinux_2_28_x86_64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.8/105.8 MB • 00:17 • 7.4 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         File too large. Limit for project 'cuda-quantum' is 100 MB. See https://test.pypi.org/help/#file-size-limit for more information.
```

As mentioned above, #3693 says that we should've already been approved for 200 MB.

**Comment by bmhowe23** [comment]
I tried uploading our latest release (0.7.1) to pypi.org despite it not working on test.pypi.org, and it worked, so it seems like our problem is limited to test.pypi.org.

**Comment by cmaureir** [comment]
Hey @bmhowe23 :wave:
I've set the upload limit for `cuda-quantum` to 200 MB on TestPyPI.
have a nice week :tada:
