### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MaharavanSundaram** [pypi/support#4073]
### PyPI Username

boschsensortec

### Reason for request

Subject: Auto enable 2FA authentication 

Hello Team,

We had a pypi account (**boschsensortec**) and we were trying to push the package in GitHub public repository automatically to pypi with help of wotkflow script in Github

Since we had token as a secret variable in Github public repository, token has been disabled and 2FA has been automatically enabled.

Our deploy process is blocked, we were unable to deploy into Pypi manually as well in the same package name

Please try to retrieve the account asap!

Account name: boschsensortec
Python package: https://pypi.org/project/coinespy/

Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by MaharavanSundaram** [comment]
Hello @ewdurbin  Can you help on this ?
Its blocking our deploy process

**Comment by MaharavanSundaram** [comment]
Hello @ewdurbin  , Can you help on this and retrieve our account?

**Comment by Thespi-Brain** [comment]
Hi @MaharavanSundaram,

We need to do some more research on your account as part of our account recovery process. We will get back to you shortly. Thanks for your patience.

**Comment by MaharavanSundaram** [comment]
> Hi @MaharavanSundaram,
> 
> We need to do some more research on your account as part of our account recovery process. We will get back to you shortly. Thanks for your patience.

Thank you @Thespi-Brain

**Comment by MaharavanSundaram** [comment]
Hello @Thespi-Brain 
Good afternoon!
Can you provide any update regarding this issue?

Thank you!

**Comment by Thespi-Brain** [comment]
Hi @MaharavanSundaram,

Thanks so much for your patience. In order to start the account recovery process to reset your 2FA and recovery codes, your account needs to have a valid/active link to a public repo of your project. But I understand that since you were unable to deploy the public repo, what I can offer as a workaround is for you to send an email to support@pypi.org confirming your intent to reset your 2FA and recovery codes with a link to this issue (https://github.com/pypi/support/issues/4073). 

There will be a 7 day wait period from that email as part of our verification/security policy, after which we will go ahead and reset your account and go from there. Thanks!

**Comment by MaharavanSundaram** [comment]
> Hi @MaharavanSundaram,
> 
> Thanks so much for your patience. In order to start the account recovery process to reset your 2FA and recovery codes, your account needs to have a valid/active link to a public repo of your project. But I understand that since you were unable to deploy the public repo, what I can offer as a workaround is for you to send an email to [support@pypi.org](mailto:support@pypi.org) confirming your intent to reset your 2FA and recovery codes with a link to this issue (#4073).
> 
> There will be a 7 day wait period from that email as part of our verification/security policy, after which we will go ahead and reset your account and go from there. Thanks!

As per your suggestion , I have sent the mail to [support@pypi.org](mailto:support@pypi.org) to reset my 2FA and recovery codes for the registered mail. Thank you!
So

**Comment by MaharavanSundaram** [comment]
> Hi @MaharavanSundaram,
> 
> Thanks so much for your patience. In order to start the account recovery process to reset your 2FA and recovery codes, your account needs to have a valid/active link to a public repo of your project. But I understand that since you were unable to deploy the public repo, what I can offer as a workaround is for you to send an email to [support@pypi.org](mailto:support@pypi.org) confirming your intent to reset your 2FA and recovery codes with a link to this issue (#4073).
> 
> There will be a 7 day wait period from that email as part of our verification/security policy, after which we will go ahead and reset your account and go from there. Thanks!



> Hi @MaharavanSundaram,
> 
> Thanks so much for your patience. In order to start the account recovery process to reset your 2FA and recovery codes, your account needs to have a valid/active link to a public repo of your project. But I understand that since you were unable to deploy the public repo, what I can offer as a workaround is for you to send an email to [support@pypi.org](mailto:support@pypi.org) confirming your intent to reset your 2FA and recovery codes with a link to this issue (#4073).
> 
> There will be a 7 day wait period from that email as part of our verification/security policy, after which we will go ahead and reset your account and go from there. Thanks!

I have sent the mail as per your suggestion to reset 2FA and  recovery codes with registered mail id. So please initiate the process.
Thanks!

Can you help to re-open the ticket since issue has not been fixed

**Comment by Thespi-Brain** [comment]
Hi @MaharavanSundaram,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
