### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by statsmaths** [pypi/support#4077]
### PyPI Username

`statsmaths`

### Reason for request

I no longer have access to the email account listed as a "primary account" ( taylor.arnold@acm.org ). I have access to the other email that is listed in my account ( tarnold2@richmond.edu ), which I just verified, as well as my username+password. Yet, I cannot figure out how to change the tarnold2@richmond.edu address to be the primary one for the account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by statsmaths** [comment]
Hello, I'm checking to see if there is any update on this request. Thank you!

**Comment by Thespi-Brain** [comment]
Hi @statsmaths,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4077). We will proceed from there. Thanks!

**Comment by statsmaths** [comment]
Excellent, thank you. Just sent an email from my preferred email address.

**Comment by Thespi-Brain** [comment]
Hi @statsmaths,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @statsmaths,

Thanks for completing the verification process. The verification was successful! I have updated your primary email address. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
