### ISSUE TITLE
File Limit Request: ScaleLLM - 300 MB

### ISSUE THREAD

**Issue by guocuimi** [pypi/support#4081]
### Project URL

https://pypi.org/project/scalellm/

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[ScaleLLM](https://pypi.org/project/scalellm/) is a cutting-edge inference system engineered for large language models (LLMs). 

### Reasons for the request

In order to get SOTA performance, we have to rewrite gpu kernels in ScaleLLM. The recent GPU kernel rewrite contribute a lot of binary size to this project. Due to the package size limit of 100MB, we have to disable some optimizations and functionalities. We kindly request an increase in the package size limit to 300MB for this CUDA-based package. thanks 

Over time, we would expect more size increase in the future as we introduce more kernel optimizations. Thanks for your help.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @guocuimi :wave:
I've set the upload limit for `scalellm` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :+1:
