### ISSUE TITLE
File Limit Request: pco - 300 MB

### ISSUE THREAD

**Issue by Excelitas-PCO** [pypi/support#4084]
### Project URL

https://pypi.org/project/pco

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This is the python SDK wrapper for controlling PCO cameras in python

### Reasons for the request

As we now support Windows, Linux AMD64 and Linux Arm64 all in one package, we also need to provide the relevant underlying libraries for all those platformes packaged inside the wheel, thus the size of the wheel increased quite a bit since the beginning

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dkirchhoefer** [comment]
When can we expect this to be done?

**Comment by Excelitas-PCO** [comment]
Again trying to gently push this forward as our customers are waiting for the new release
