### ISSUE TITLE
Project Limit Request: onnxruntime-training - 20 GiB

### ISSUE THREAD

**Issue by sophies927** [pypi/support#4085]
### Project URL

https://pypi.org/project/onnxruntime-training/

### Does this project already exist?

- [X] Yes

### New limit

20 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

ONNX Runtime is a cross-platform runtime accelerator for machine learning models and has been active since 2018.

We have hit the 10GB limit in our 1.18.0 release, and increasing the limit to 20GB should support all future releases in the upcoming years.

### How large is each release?

Each release is ~1000-1200 MB, which contains builds for a number of different supported architectures since the product is cross-platform.

### How frequently do you make a release?

~4-5 times per year

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @sophies927 :wave:
I've set the project limit for `onnxruntime-training` to 20 GB on PyPI.
Have a nice week :partying_face:

**Comment by sophies927** [comment]
Thank you so much!
