### ISSUE TITLE
File Limit Request: bigdl-core-xe-21 - 200 MB

### ISSUE THREAD

**Issue by Oscilloscope98** [pypi/support#4088]
### Project URL

https://pypi.org/project/bigdl-core-xe-21/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`bigdl-core-xe-21` is providing acceleration for LLM inference on Intel GPUs. It has been active for five months.

### Reasons for the request

We request increase release size for `bigdl-core-xe-21` is because we are adding new shared libraries for kernels in our project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Oscilloscope98 :wave:
I've set the upload limit for `bigdl-core-xe-21` to 200 MB on PyPI.
have a nice week :+1:
