### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by norabelrose** [pypi/support#4090]
### PyPI Username

norabelrose

### Reason for request

I misplaced my Yubikey and all of my account recovery codes are being rejected as "invalid," for some unknown reason.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @norabelrose,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by norabelrose** [comment]
Thank you! I just responded to the email.

I should mention that the email incorrectly stated that "there are no projects with public source code repositories associated with your account," which is untrue since the [concept-erasure](https://pypi.org/project/concept-erasure/) library has code available [here](https://github.com/EleutherAI/concept-erasure).

**Comment by Thespi-Brain** [comment]
Hi @norabelrose,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
