### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Pbatch** [pypi/support#4098]
### PyPI Username

'Pbatch'

### Reason for request

Not receiving verification emails so cannot verify account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Pbatch,

I took a look into your account and according to the logs, a verification email was sent to the primary email address associated with your account. Could you please confirm and send your primary email address at support@pypi.org? Please reference this (https://github.com/pypi/support/issues/4098) in that email as well. We will go from there, thanks!

**Comment by Pbatch** [comment]
I think the email server was broken at the time I was trying to verify.

It worked today!

Thank you :)
