### ISSUE TITLE
Project Limit Request: Pillow-Heif - 14 GB

### ISSUE THREAD

**Issue by bigcat88** [pypi/support#4099]
### Project URL

https://pypi.org/project/pillow-heif/

### Does this project already exist?

- [X] Yes

### New limit

14 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

In the future, I hope that the correct support plugin system will be added to the libheif, and I will be able to move large bundled libraries (libaom/x265) into separate projects.
But I do not expect this to happen this year or at leat in near 5 months..

### How large is each release?

~300-400 MB total. One linux/windows wheel ~ 8 MB size, macOS wheel - 4 MB.

Bundled libraries: libheif, libde265, x265, libaom

### How frequently do you make a release?

1-2 releases every 3 months

Problem that during development 2 years ago, releases was much frequent, I tried to remove all old non important releases, but it is not enough.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @bigcat88 :wave:
I've set the project limit for `Pillow-Heif` to 14 GB on PyPI.
have a nice week :100:

**Comment by bigcat88** [comment]
thank you a lot :)
