### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by hesslee** [pypi/support#4101]
### PyPI Username

[hesslee]

### Reason for request

During my first registering my account, I input a wrong email address by my typo mistake.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by hesslee** [comment]
I mistakenly entered hess.lee70@gamil.com
my correct email address is hess.lee70@gmail.com

**Comment by Thespi-Brain** [comment]
Hi @hesslee,

I took a look at your account and it seems like you were able to successfully create an alternate account with the correct email address, which is great. I am closing this case, but if you are having any other login issues, let me know!
