### ISSUE TITLE
File Limit Request: quspin-extensions - 300 MiB

### ISSUE THREAD

**Issue by weinbe58** [pypi/support#4105]
### Project URL

https://pypi.org/project/quspin-extensions/

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[QuSpin](https://github.com/QuSpin/QuSpin) is a Python package I developed during my PhD and released it formally back in ~2016. The package is used for the simulation of complex quantum many-body systems using exact diagonalization methods. We have 2 publications about the package and it is used in many academic papers.

For the lifetime of the package we have avoided any kinds of automation for publishing the package, we simply have built the code locally on our machines and hosted the package on Anaconda. 

We are trying to split up the package into smaller components, `quspin-extensions` being a very big part of the code base. Most of the reason for the large binaries are due to the use of cython which was a design choice I made before I had much experience with python C-extensions. For the most part the binaries fit the 100 MB limit with the exception of Linux which for some reason has binaries +200MB in size. kind

### Reasons for the request

 In recent years I have not had much time to maintain the code which has meant the community around QuSpin has suffered a bit because I have not been able to work on this project. I was able to automate the build of the C++ extensions which should enable better support long term for the project by decoupling the packaging of the pure Python and C++ components. I do not see many updates occurring to this package, other than the occasional bug fix and rebuild for minor version updates to the NumPy C-API. 
 
 Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by weinbe58** [comment]
Actually on second thought I'll just split up the extensions across multiple packages.

**Comment by weinbe58** [comment]
After trying to split it up there are components that still exceeds the size limit of 100 MB so I think to make my life easier just having a single package would be much better so I am re-opening this request.

**Comment by weinbe58** [comment]
cc: @mgbukov @markusschmitt

There is a final size limit for the binaries PyPi accepts by default so we will need to wait for the limit to be increased before proceeding with the refactor.

**Comment by cmaureir** [comment]
Hey @weinbe58 :wave:
I've set the upload limit for `quspin-extensions` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size, and maybe keep exploring the package split approach.
Have a nice week :snake:
