### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by arnauqb** [pypi/support#4109]
### PyPI Username

arnauq

### Reason for request

I registered an academic email address and now I have lost access to it.

It should be easy to verify that I own the projects in the account:

https://pypi.org/user/arnauq/

https://github.com/arnauqb

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @arnauqb,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4109). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @arnauqb,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @arnauqb,

Thanks for completing the verification process. The verification was successful! I have updated your primary email address. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by arnauqb** [comment]
thank you very much!
