### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cabouman** [pypi/support#4110]
### PyPI Username

`cabouman`

### Reason for request

Apparently, 2FA has been set up in my account, but I don't recall ever setting it up. So I have no recovery codes.
I'm not sure how this happened. I do have access to pypi.org, and I recently set up the 2FA there, which works fine.

My email addresses are Charles.Bouman@gmail.com and I also receive emails at bouman@purdue.edu .

Other people who can vouch for my authenticity are:

> G Buzzard greg.buzzard@gmail.com and buzzard@purdue.edu

> S J Kisner sjkisner@gmail.com and sherman.kisner@highperformanceimaging.com

Sorry for the hassle.
Charlie Bouman

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @cabouman,

Thanks for providing details regarding your account. I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @cabouman,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
