### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Pseudomanifold** [pypi/support#4111]
### PyPI Username

brieck

### Reason for request

I have lost access to the e-mail address (bastian@rieck.ru) since I let the domain expire as a form of protest against the invasion of Ukraine.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Pseudomanifold** [comment]
Thanks, sent an e-mail!

**Comment by Thespi-Brain** [comment]
Hi @Pseudomanifold,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Pseudomanifold** [comment]
Thanks a lot! I have sent an e-mail to the support team.

**Comment by Thespi-Brain** [comment]
Hi @Pseudomanifold,

Thanks for completing the verification process. The verification was successful! I have updated your primary email address. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
