### ISSUE TITLE
Project Limit Request: imgui_bundle - 30 GB

### ISSUE THREAD

**Issue by pthom** [pypi/support#4114]
### Project URL

https://pypi.org/project/imgui-bundle/

### Does this project already exist?

- [X] Yes

### New limit

30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Dear ImGui Bundle It's a framework that enables to easily develop Python or C++ application, using [Dear ImGui](https://github.com/ocornut/imgui). 

It bundles many sister libraries from the ecosystem of Dear ImGui: many many widget, a plotting library, a markdown renderer, a node editor, an image analysis tool, a vector drawing library, portable file dialogs, etc.

As such, it is an excellent library for jump-starting an application in Python, with sophisticated tools and widgets.  However, the number of native libraries which are present means that releases are a bit heavy.

The best way to discover it is to open its [online emscripten demonstration](https://traineq.org/ImGuiBundle/emscripten/bin/demo_imgui_bundle.html), and its [documentation](https://pthom.github.io/imgui_bundle/introduction.html) 

---

### How large is each release?

**Summary of uploaded files**

Here is the file list of the latest release (1.3.0). It includes a source distribution and binary packages for several platforms. 

```
imgui_bundle-1.3.0-cp310-cp310-macosx_11_0_arm64.whl (20.3 MB)
imgui_bundle-1.3.0-cp310-cp310-macosx_11_0_x86_64.whl (28.6 MB)
imgui_bundle-1.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27.6 MB)
imgui_bundle-1.3.0-cp310-cp310-musllinux_1_1_x86_64.whl (29.2 MB)
imgui_bundle-1.3.0-cp310-cp310-win_amd64.whl (39.4 MB)
imgui_bundle-1.3.0-cp311-cp311-macosx_11_0_arm64.whl (20.3 MB)
imgui_bundle-1.3.0-cp311-cp311-macosx_11_0_x86_64.whl (28.6 MB)
imgui_bundle-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27.6 MB)
imgui_bundle-1.3.0-cp311-cp311-musllinux_1_1_x86_64.whl (29.2 MB)
imgui_bundle-1.3.0-cp311-cp311-win_amd64.whl (39.4 MB)
imgui_bundle-1.3.0-cp312-cp312-macosx_11_0_arm64.whl (20.3 MB)
imgui_bundle-1.3.0-cp312-cp312-macosx_11_0_x86_64.whl (28.8 MB)
imgui_bundle-1.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27.7 MB)
imgui_bundle-1.3.0-cp312-cp312-musllinux_1_1_x86_64.whl (29.2 MB)
imgui_bundle-1.3.0-cp312-cp312-win_amd64.whl (39.4 MB)
imgui-bundle-1.3.0.tar.gz (36.8 MB)
```

**Efforts to reduce the size**
I did an important effort to reduce the size of each release: 

- See release https://pypi.org/manage/project/imgui-bundle/release/0.8.8/ which did occupy 668MB
- And compare to release https://pypi.org/manage/project/imgui-bundle/release/1.3.0/ which occcupies 472MB (and targets more platforms)

**Bundling other packages**

As mentioned in the introduction, my library bundles many sister libraries from the ecosystem of Dear ImGui (many many widget, a plotting library, a markdown renderer, a node editor, an image analysis tool, a vector drawing library, portable file dialogs, etc.). These libraries are native libraries. I do not bundle other Python packages. 

**Bundling of example data**
I do bundle example data in the project as my library provides its own tutorial (which is actually the example you can see online in the [Emscripten version](https://traineq.org/ImGuiBundle/emscripten/bin/demo_imgui_bundle.html))

### How frequently do you make a release?

Roughly once every three months. 
I had to reduce the frequency of releases, and to remove some older releases due to the fact that I did already hit the limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @pthom :wave:
I've set the project limit for `imgui_bundle` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size, and maybe explore ways of reducing the amount of wheels by using the Python Limited API https://docs.python.org/3/c-api/stable.html
Have a nice week :tada:

**Comment by pthom** [comment]
Thanks a lot !!!
