### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by roiding** [pypi/support#4115]
### PyPI Username

roiding

### Reason for request

My primary account: dingran@ran-ding.ga. 
For reasons that are well known, the.ga domain name has been withdrawn and a change of primary address is requested

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by roiding** [comment]
I want to change it to maodoulove19950815@gmail.com

**Comment by roiding** [comment]
It looks like my issue is about to be dealt with.
My code repository is https://github.com/roiding/chromedriver-autoupdate.This verifies that I am the owner of the pypi repository.
Please help me change the main account to: maodoulove19950815@gmail.com

**Comment by roiding** [comment]
I have sent you an email through the email address I want to change, please confirm

**Comment by Thespi-Brain** [comment]
Hi @roiding,

Thanks for sending over your preferred email, and thanks for your patience. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by roiding** [comment]
thanks for your help.
i have replyed your email

**Comment by Thespi-Brain** [comment]
Hi @roiding,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued, and your primary email address has been updated. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
