### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by schneiderfelipe** [pypi/support#4116]
### PyPI Username

schneiderfelipe

### Reason for request

For some reason my 2FA authentication app (Google Authenticator) is giving codes that don't work and I have never generated recovery codes before. It's been a long time since I lastly logged in. I have perfect access to my e-mail address (I just attempted to change passwords and everything went OK).

It's just that the 2FA auth application does not work for some reason 🤔. I realised the issue when preparing to upload a new version of an application (overreact, see [PyPI](https://pypi.org/project/overreact/) and [GitHub](https://github.com/schneiderfelipe/overreact)).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by schneiderfelipe** [comment]
Maybe that's related to #3895?

**Comment by Thespi-Brain** [comment]
Hi @schneiderfelipe,

Thanks for the info. This may just be an issue of where we need to reset your 2FA. I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by schneiderfelipe** [comment]
Hey @Thespi-Brain!

> This may just be an issue of where we need to reset your 2FA.

Very likely!

> I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

I just got the e-mail and followed the instructions, thank you!

**Comment by Thespi-Brain** [comment]
Hi @schneiderfelipe,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by schneiderfelipe** [comment]
@Thespi-Brain I have just done it all: reset my password, got the recovery codes, etc. But when I configured 2FA, the very first 6-digit code didn't work ("Invalid TOTP code. Your device time may be out of sync.")!

**Comment by Thespi-Brain** [comment]
Hi @schneiderfelipe,

I took a look at your account and the logs are showing me that your 2FA was actually not configured. :-( I would try again to set up the 2FA and maybe try a different authentication app to do so.
