### ISSUE TITLE
File Limit Request: tensorflow_recommenders_addons - 300 MB

### ISSUE THREAD

**Issue by rhdong** [pypi/support#4126]
### Project URL

https://pypi.org/project//recommenders-addons

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

tensorflow_recommenders_addons(_gpu) is widely used extend package for the RecSys industrial. It is an additional utils and helpers to extend TensorFlow when build recommendation systems on CPU/GPU clusters, contributed and maintained by SIG Recommenders.

### Reasons for the request

We intend to merge the GPU support of`tensorflow_recommenders_addons_gpu` into `tensorflow_recommenders_addons`, which requires the `tensorflow_recommenders_addons` can support larger files like `tensorflow_recommenders_addons_gpu`. 300MB could reserve enough space for future use in this project.
Many thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @rhdong :wave:
I've set the upload limit for `recommenders-addons` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice week :dancers:
