### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jobingeo** [pypi/support#4128]
### PyPI Username

jobingeorge

### Reason for request

Lost 2FA authentication app. Kindly recover the test pypi account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jobingeo,

I have initiated an account recovery process for your Test.PyPI account and an email is being sent to the primary email address associated with your Test.PyPI account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @jobingeo,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued for your Test.pypi account. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
