### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rmkane** [pypi/support#4129]
### PyPI Username

`rmkane`

### Reason for request

Incorrect primary email address

When registering my account, I mistyped my email address.  
Here is the correct email: `rmkane@proton.me`

**Note:** This is a brand new account, so I cannot verify by email, set up 2FA, or generate recovery codes until my email has been corrected. This issue should be trivial to resolve, since it does not involve 2FA.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by miketheman** [comment]
This issue has been resolved.
