### ISSUE TITLE
File Limit Request:  jpl-small-bodies-de441-n16 - 650 MiB

### ISSUE THREAD

**Issue by akoumjian** [pypi/support#4130]
### Project URL

https://pypi.org/project/jpl-small-bodies-de441-n16/

### Does this project already exist?

- [X] Yes

### New Limit

650 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Very similar request to https://github.com/pypi/support/issues/2884

jpl-small-bodies-de441-n16 is designed to ship a binary data file known as sb441-n16 (Small Body Ephemeris for 16 most massive asteroids corresponding to DE441). These files are created by NASA's JPL and are used extensively by researchers in astronomy and astrodynamics to calculate the positions of massive bodies as a function of time for things such as asteroid discovery efforts, space mission planning, ephemeris calculation, etc..

The jpl-small-bodies-de441-n16 package is designed to ship this file and provides a single variable that stores the path to the file on disk so it can be used with external packages such as spiceypy or assist. However, the ephemeris file is 615.8 MB which exceeds the default PyPi file size limit. No other packages are bundled in this project. No example data is packaged. The only data contained in this package is the development ephemeris file and a script to fetch it for CI publishing actions.

### Reasons for the request

The binary data file is 615.8 MB and cannot be compressed further. As it is such a fundamental data file that underpins a lot of research in astronomy and astrodynamics, we anticipate that having this package available on PyPi will be extremely beneficial to the community. We do not expect the size of this package to increase in the future as JPL generates new versions of the development ephemeris files only every few years. We anticipate creating new projects for each subsequent release of the development ephemeris files.

Thank you, once again, for your consideration.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @akoumjian :wave:
I've set the upload limit for `jpl-small-bodies-de441-n16` to 650 MB on PyPI. Please be mindful of the frequency of releases at that size, otherwise you will hit the project limit (10GB) very soon.
Have a nice week :+1:

**Comment by akoumjian** [comment]
@cmaureir Thank you so much! Hopefully just the one release.
