### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by aiznk** [pypi/support#4131]
### PyPI Username

`narupo`

### Reason for request

Dear staff.

I was lost access to primary email address. And that email address (primary) not verified on pypi.org. But I can login to pypi.org with my username and password. But I can't manage projects because email address was not verified. I need to change primary email address.

My primary email address (lost access): narupo.glab@gmail.com

Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by aiznk** [comment]
fix typo: `pypy.org` -> `pypi.org`

**Comment by Thespi-Brain** [comment]
Hi @aiznk,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4131). We will proceed from there. Thanks!

**Comment by aiznk** [comment]
Thanks response. 
I send email. Best regards.

**Comment by Thespi-Brain** [comment]
Hi @aiznk,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
