### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tolgabalper** [pypi/support#4134]
### PyPI Username

TolgaBalper

### Reason for request

I accidentally typed my email wrong so now I cannot verify my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @tolgabalper,

Can you please confirm what your correct email address should be at support@pypi.org? Please reference this issue link (https://github.com/pypi/support/issues/4134) in the email as well, and we will go from there. Thanks!

**Comment by tolgabalper** [comment]
I have sent the email.

**Comment by Thespi-Brain** [comment]
Hi @tolgabalper,

Thanks for confirming your preferred email. I have updated your email and also reset your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
