### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by avneeshchaudhary** [pypi/support#4139]
### PyPI Username

avneesh

### Reason for request

Lost 2FA authentication app and security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @avneeshchaudhary,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
