### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by captainawesome78** [pypi/support#4140]
### PyPI Username

shaik_naveed

### Reason for request

Lost 2FA authentication app or security token and recovery codes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by captainawesome78** [comment]
Hi Team, any update on the account recovery

**Comment by kiasar** [comment]
@captainawesome78 Hi
Has your account recovered? 
I just want to know how long it usually takes.

**Comment by captainawesome78** [comment]
Hi @kiasar , it is not recovered yet, didn't hear back anything from them, I don't know how much time it typically takes

**Comment by Thespi-Brain** [comment]
Hi @captainawesome78,

Thanks for your patience. I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @captainawesome78,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
