### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Susmigo** [pypi/support#4145]
### PyPI Username

`lonewolf09`

### Reason for request

Lost 2FA authentication app and recovery codes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Susmigo** [comment]
Any progress on this ?

**Comment by kiasar** [comment]
@Susmigo Hi
Has your account recovered? 
I just want to know how long it usually takes.

**Comment by Thespi-Brain** [comment]
Hi @Susmigo,

I have reset your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. I will keep this issue open for another week just in case, unless I hear from you earlier. Thanks.

**Comment by Susmigo** [comment]
Thanks a lot @Thespi-Brain for providing the support.

Hence closing this issue
