### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ch-ahindura** [pypi/support#4148]
### PyPI Username

`tergite`

### Reason for request

- Lost access to email address (There was a typo in the primary email address actually)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ch-ahindura,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4148). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ch-ahindura,

Thanks for sending in your preferred/correct email address. I have updated your primary and email and reset your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
