### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by unbohn** [pypi/support#4151]
### PyPI Username

nbohn

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @unbohn,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4151). We will proceed from there. Thanks!

**Comment by unbohn** [comment]
Thanks, @Thespi-Brain ! Just sent the email.

**Comment by Thespi-Brain** [comment]
Hi @unbohn,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
