### ISSUE TITLE
Project Limit Request: quarchpy- 1 GiB

### ISSUE THREAD

**Issue by SBQuarch** [pypi/support#4159]
### Project URL

https://pypi.org/project/quarchpy/

### Does this project already exist?

- [X] Yes

### New limit

1

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

QuarchPy is a python package designed to provide an easy-to-use API which will work seamlessly over any connection option: USB, Serial and LAN. With it, you can create your own scripts for controlling Quarch devices - without having to worry about the low-level code involved with communication.

The package contains all prerequisites needed as a single PyPI project, which can be installed from the python online repository using PIP. This makes it easy to install and update, while also providing you with full access to the source code if you want to make changes or additions.

QuarchPy can also communicate to the device via QIS (Quarch Instrument Server), QPS (Quarch Power Studio), or simply using Python scripts. Both QIS and QPS are included with the QuarchPy Package - they are ready to use (Java and drivers may also be needed).

It is increasing due to java libs being packaged with it for QPS and QIS.

### How large is each release?

We have stripped back the java libs to only the necessary libs, and we only ship one jar that works with windows, linux and mac OS.

### How frequently do you make a release?

once every 2 months

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @SBQuarch :wave:

By default, each project has a 10G limit, are you maybe referring to Upload Size per wheel?
Also, have you consider creating packages that can provide certain parts of the project?
for example, you can have quarchpy as a package that depends on quarchpy-core quarchpy-java-libs, etc so then you don't rely on a big file (just an idea).

Let me know!

**Comment by SBQuarch** [comment]
Hi @cmaureir, sorry, yes I meant wheel file size. 
I saw people requesting larger than 10gb and thought we would not need more that 1gb max, but now i see it was project size they were requesting and not file size. 
I don't need 1GB file size but as i thought people were asking for 10gb 1gb seemed reasonable. I'm looking for 500MB file size please.

Currently we have a wheel size of 350MB because we included java libs to support our .jar applications inside quarchpy. 
We need 3 copies of these libs, for each major OS, win, mac, linux, which is causing the large file size. The rest of the project is less than 50MB without the jar and libs. Creating a quarchpy-core and java-libs might be a good idea but the java libs would have the same issue of needing >300MB wheel size limit. 

Do you know if the pip install command can run custom code after the initial install. This way I could check the OS the user is on and download only the lib files needed for that OS and not others. We could potentially host the lib files somewhere separate to pypi and download them after the install but I'd like the user to not have to run any additional commands. The goal is to have "pip install quarchpy" install all that they need to automate our equipment.

**Comment by SBQuarch** [comment]
Is there any update on this please?
We have:
Project settings
Project size: 9.1 GiB
Project upload limit: 300.0 MiB [(request an increase)](https://pypi.org/help/#file-size-limit)
Project total size limit: Default (10.0 GiB) [(request an increase)](https://pypi.org/help/#project-size-limit)
![Image](https://github.com/user-attachments/assets/58b6207d-b41a-41d7-837d-5c86100580a2)

Which means will can only do 2/3 more released (depending on how that 9.1GiB is rounded)

Can i request we have a Project Size doubled to 20GiB and Project upload limit increased to 500MiB.
Many thanks.

**Comment by cmaureir** [comment]
Hello @SBQuarch :wave:
I have set your project to have a 20G project limit and 500M wheel size limit.
We usually request these requests on separate issue, but I understand you might still be waiting for this.
Please try to explore new ways of distributing your package, it really will help you to have a download process in order to get the files that are not related to your module itself like the jars.
Have a nice weekend!
