### ISSUE TITLE
File Limit Request: paddlepaddle-gpu - 900 MiB

### ISSUE THREAD

**Issue by DDDivano** [pypi/support#4166]
### Project URL

https://pypi.org/project/paddlepaddle-gpu

### Does this project already exist?

- [X] Yes

### New Limit

900 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

PaddlePaddle is an open-source deep learning platform that has been actively developed and maintained since its inception in 2016. The platform includes a comprehensive set of tools and libraries to support deep learning research and industrial applications.

github：https://github.com/PaddlePaddle

### Reasons for the request

We have made significant efforts to optimize and reduce the size of our PyPI releases. However, the following factors necessitate an increase in the size limit:

Additional CUDA Architectures Support: In this release, we have added support for additional CUDA architectures, specifically the Hopper series with SM90 architecture. This enhancement is essential for leveraging the latest hardware capabilities but has contributed to the increase in package size.
CINN Support: We have also included support for the CINN (Compiler Infrastructure for Neural Networks) , which adds to the functionality and performance of PaddlePaddle, but also increases the package size.
Given these considerations, the current size limit of 800 MiB is no longer sufficient to accommodate the growth and expansion of the platform. Increasing the size limit to 900 MiB will allow us to continue delivering a robust and fully-featured deep learning platform without compromising usability or functionality.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @DDDivano :wave:
I've set the upload limit for `paddlepaddle-gpu` to 900 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
