### ISSUE TITLE
Project Limit Request: xFormers - 30 GiB

### ISSUE THREAD

**Issue by danthe3rd** [pypi/support#4168]
### Project URL

https://pypi.org/project/xformers/

### Does this project already exist?

- [X] Yes

### New limit

30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

xFormers is a library used by machine-learning practitioners to speed-up their workloads. It contains specific and optimised low-level components.
It has been active for 3 years now, but gained a lot of exposure within the last few years - it's a *critical project* in Pypi, and has ~50k [downloads per day](https://pepy.tech/project/xformers).

We would like to be able to keep ~30 major releases on pypi - aka 30GB of storage.

(**note**: we were previously granted 20GB of storage https://github.com/pypi/support/issues/2907)

### How large is each release?

Each binary is ~150MB (because we ship CUDA binaries for multiple GPU architectures), and each release contains 8 binaries (`{win, linux} x {cp38, cp39, cp310, cp311}`).
**So each release is about 1GB**

**Binary size reduction:** we're working on further reducing the binary size, but this effort depends on a modification to PyTorch which will make it to PyTorch 2.4, scheduled for September. The space limitation is currently a blocking issue that prevents further releases in the short term (unless we remove older binaries).

### How frequently do you make a release?

Roughly every month, matching the PyTorch release schedule

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @danthe3rd :wave:
I've set the project limit for `xFormers` to 30 GB on PyPI.
Have a nice week :100:
