### ISSUE TITLE
File Limit Request: aspose-pdf - 200 MiB

### ISSUE THREAD

**Issue by AnastasiaRadtsevich** [pypi/support#4169]
### Project URL

https://pypi.org/project/aspose-pdf/

### Does this project already exist?

- [X] Yes

### New Limit

200 

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Aspose.PDF for Python via .NET is a PDF Processing library to perform document management can easily be used to generate, modify, convert, render, secure and print documents without using Adobe Acrobat. Releases have been published every month regularly from December 2022.
https://products.aspose.com/pdf/python-net/
https://releases.aspose.com/pdf/pythonnet/

### Reasons for the request

We are planning to add new features in the product and to support new versions of Python (support of 3.12 version will be included in the coming release). These actions will increase the size. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by AnastasiaRadtsevich** [comment]
Hi @cmaureir could you please help with increasing the file limit? We are unable to release the new version due to this, because we added support for Python 3.12, which led to an increase in the size of the packages.

**Comment by cmaureir** [comment]
Hey @AnastasiaRadtsevich :wave:
I've set the upload limit for `aspose-pdf` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
have a nice week :snake:
