### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by friendlyanon** [pypi/support#4176]
### PyPI Username

`friendlyanon`

### Reason for request

Lost security token due to Google Authenticator not backing them up.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @friendlyanon,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @friendlyanon,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by friendlyanon** [comment]
Thanks. I have indeed completed the process. Now I'm using Aegis with automatic backups to my own self-hosted Nextcloud instance.

For anyone who might read this: Never ever trust Google with anything! Even if their authenticator says the codes are backed up, that clearly is not the case.
