### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by akemalyildirim1** [pypi/support#4178]
### PyPI Username

akemalyildirim1

### Reason for request

My phone is broken and I am not able to access 2FA authentication app.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by akemalyildirim1** [comment]
Also, I know my password and I am able to access my email.

**Comment by Thespi-Brain** [comment]
Hi @akemalyildirim1,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @akemalyildirim1,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
