### ISSUE TITLE
Possible to reset my 2FA?

### ISSUE THREAD

**Issue by max-sixty** [pypi/support#4179]
### PyPI Username

maximilianroos

### Reason for request

Unfortunately my 2FA code doesn't seem to be working. I'm not sure why.

I still have access to my email address; my password still works fine.

Would it be possible to reset the 2FA codes?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by max-sixty** [comment]
Would there be any way of actioning this?

(To the extent you could start charging for requests, that would be great from my end — it can't be fun for unpaid volunteers to handle support requests like these, and people who lose their creds should internalize our externalities... but it's also bad for the ecosystem that we can't publish updates to open-source packages)

**Comment by Thespi-Brain** [comment]
Hi @max-sixty,

Thanks for your patience. I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by max-sixty** [comment]
Thank you very much @Thespi-Brain ! I created the branch and replied to the email.

**Comment by Thespi-Brain** [comment]
Hi @max-sixty,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by max-sixty** [comment]
Thank you!

(not to respond to generosity with entitlement, but would also love to fix #4188!)
