### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by olcaytaner** [pypi/support#4182]
### PyPI Username

`olcaytaner`

### Reason for request

Lost access to mail address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by olcaytaner** [comment]
I move from Isak University to Ozyegin University, but I forgot my e-mail here to update. Mail account is dropped, therefore I cannot receive mails anymore. My current e-mail address is olcay.yildiz@ozyegin.edu.tr My previous e-mail is olcaytaner@isikun.edu.tr

**Comment by Thespi-Brain** [comment]
Hi @olcaytaner,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4182). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @olcaytaner,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @olcaytaner,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by olcaytaner** [comment]
Thanks
