### ISSUE TITLE
Project Limit Request: jax-cuda12-pjrt - 20 GB

### ISSUE THREAD

**Issue by hawkinsp** [pypi/support#4183]
### Project URL

https://pypi.org/project/jax-cuda12-pjrt/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This wheel is a plugin for JAX (https://pypi.org/project/jax/) that provides support for NVIDIA GPUs.

(The main JAX wheel on pypi has never supported CUDA: instead we have previously directed users to a self-hosted bucket on GCS (https://storage.googleapis.com/jax-releases/jax_cuda_releases.html). Now we would like to direct users to install GPU support via this wheel on pypi instead.)

### How large is each release?

Approximately 200MB per release (one Linux x86_64 wheel, one Linux aarch64 wheel).

This wheel is actually one of two wheels needed for JAX CUDA 12 support. This wheel is the Python-version independent parts of the other wheel (jax-cuda12-plugin), which reduces binary size by a factor of 4.

### How frequently do you make a release?

Approximately once per month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @hawkinsp :wave:
I've set the upload limit for `jax-cuda12-pjrt` to 20 GB on PyPI. 
Have a nice week :snake:
