### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pabakertx** [pypi/support#4187]
### PyPI Username

pointwise

### Reason for request

I need to change the primary email address for user "pointwise" to "pbaker@cadence.com". I verified this address, but the site will not let me change the primary address. I do not have access to the old primary address dev@pointwise.com.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @pabakertx,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4187). We will proceed from there. Thanks!

**Comment by pabakertx** [comment]
In reference to ticket #4187<https://urldefense.com/v3/__https:/github.com/pypi/support/issues/4187__;!!EHscmS1ygiU1lA!H5ASPKoFdCcRic9Ms5tjjCbMXnysZOTQ5-XHCN0fD6Jyz6n6RFRDBedBtILPl_7bZcJRktuM-vX_V4OrltSnWhV6$>, my preferred email address is ***@***.******@***.***>.

[Cadence]<https://www.cadence.com/en_US/home.html>
Patrick Baker
Software Engineering Director
T: +1.817.720.1461
M: +1.817.915.8552
[https://signatures.cadence.com/cf/signature_fields/5dea7803e8b0ad196001582a/UIcorrectsize1583179003.png]<https://www.cadence.com/en_US/home.html>
[https://signatures.cadence.com/cf/signature_fields/5dea7803e8b0ad196001582a/J28759FortuneLogoUpdateforSigstrWhite92x1271712250084.jpg]<https://www.cadence.com/en_US/home/company/careers.html>

**Comment by Thespi-Brain** [comment]
Hi @pabakertx,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @pabakertx,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
