### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by HotDogCoder** [pypi/support#4189]
### PyPI Username

HotDogCoder

### Reason for request

Sorry for this problem guys I lost my phone and I just recover my github today. Please help to continue my work with my library its open source and is made to help pleople to enjoy coding, I'm the owner of Acid Jelly (github organization) and the company in Peru, please just ask for any proof you need to verify my identity, I have access to my email and I have the keys to deploy new versions in my local machine
<img width="1027" alt="Screenshot 2024-06-11 at 19 49 03" src="https://github.com/pypi/support/assets/81147209/6ba3a55d-b46c-4014-a96a-f5d83a0c1b57">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @HotDogCoder,

I took a look at your account and it looks like you were able to successfully login recently, which is great. Are you still having issues with login? Let me know, and we will proceed with next steps. Thanks!

**Comment by HotDogCoder** [comment]
no, i found my token so everything is ok now thanks guys

**Comment by Thespi-Brain** [comment]
Good to hear that, I am closing the issue!
