### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ShouWenWang** [pypi/support#4191]
### PyPI Username

`Ascendancy09`

### Reason for request

I lost access to primary email address due to leaving Harvard to start my own group.
Primary email: shouwen_wang@hms.harvard.edu

However, I still have access to my secondary email address: wangsw09@gmail.com, which is stored in this account. 
Can you change my gmail to be the primary email account? Thanks! 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ShouWenWang,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4191). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ShouWenWang,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ShouWenWang,

Thanks for completing the verification process. The verification was successful! I have updated your primary email address to your preferred email. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
