### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by luke-saunders** [pypi/support#4192]
### PyPI Username

`luke-saunders`

### Reason for request

I have lost access to the authentication app

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @luke-saunders,

I went ahead and reset your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
