### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by serban-seeq** [pypi/support#4195]
### PyPI Username

`serbanmarin`

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @serban-seeq,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4195). We will proceed from there. Thanks!

**Comment by serban-seeq** [comment]
hi @Thespi-Brain I will go ahead and close this. I no longer need access to this account. 

Only reason I needed it to begin with was that the account was an `owner` on Pypi project. I've since reached out to another owner of that project and sorted things out.

**Comment by Thespi-Brain** [comment]
Hi @serban-seeq, 

Sounds good, glad you were able to sort things out!
