### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by TahsinCr** [pypi/support#4199]
### PyPI Username

TahsinCr

### Reason for request

(Lost 2FA authentication app or security token)

Dear PYPI Support Team,

I am writing to inform you of my inability to access my PYPI account due to losing my two-factor authentication and account recovery code. As a result, I am unable to log in to my account and require your urgent assistance.

My account details are as follows:

Username: TahsinCr
Email Address: TahsinCr@outlook.com
I kindly request your assistance in regaining access to my account as soon as possible. If you have any questions regarding my situation, please feel free to contact me at TahsinCr@outlook.com.

Thank you for your understanding and support.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @TahsinCr,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by TahsinCr** [comment]
I have followed the instructions sent to my email address. Thank you for your support.

**Comment by TahsinCr** [comment]
@Thespi-Brain

**Comment by Thespi-Brain** [comment]
Hi @TahsinCr,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by TahsinCr** [comment]
Thank you for your support.
