### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bourque** [pypi/support#4203]
### PyPI Username

bourque

### Reason for request

Hi --

I am attempting to log into my account on *test.pypi* after several years, and have forgotten my password. Unfortunately I also no longer have access to the email address associated with the account. Could someone help me?

I am able to access my account just fine on nominal `pypi`, I am just having this issue with `test.pypi`.

Thank you!
-Matthew

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by bourque** [comment]
Tagging @mfixstsci who is awaiting on me to recover my account so I can hand over the keys to a project on test.pypi

**Comment by Thespi-Brain** [comment]
Hi @bourque,

I took a look into your test.pypi account and yes, I noticed that the email address associated with that account is no longer valid. Would you like me to change it to the email address that is associated with your regular pypi account? Let me know, and after that, I will be able to start the account recovery process. Thanks!

**Comment by bourque** [comment]
@Thespi-Brain Yes, that would be perfect, thanks!

**Comment by mfixstsci** [comment]
@Thespi-Brain I was curious if there was any movement with this? Thanks!

**Comment by Thespi-Brain** [comment]
@mfixstsci I have not heard back from @bourque regarding the correct email to use. @bourque, please contact support@pypi.org with an email that you would like to be associated with your test.pypi account and we will get the ball rolling, thanks!

**Comment by mfixstsci** [comment]
Awesome, thank you @Thespi-Brain and @bourque

**Comment by bourque** [comment]
@Thespi-Brain My bad -- the way your message was worded made me think you already had that information on your end.

The email is `Matthew.Bourque@colorado.edu`

Thanks!

**Comment by bourque** [comment]
@Thespi-Brain Thanks for further clarifying, I have sent an email!

**Comment by Thespi-Brain** [comment]
Hi @bourque,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @bourque,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
