### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jrhoads** [pypi/support#4210]
### PyPI Username

`datacite`

### Reason for request

Mystyped the primary email address (I had transposed the last two letters).

Should be info@datacite.org

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jrhoads,

I have updated your primary email address to the correct version. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
