### ISSUE TITLE
Recovery account

### ISSUE THREAD

**Issue by Miguel-bc** [pypi/support#4215]
### PyPI Username

Miguel-bc

### Reason for request

Lost 2fa authentication app

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Duplicate issue https://github.com/pypi/support/issues/4214, closing this one.
