### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vtexier** [pypi/support#4218]
### PyPI Username

'duniter'

### Reason for request

Hello,

I lost access to the email address bot@duniter.org

cause it no longer exists.

I can give you another email to use.

Regards,
Vincent.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi Vincent,

I was unfortunately not able to find any account with the username "duniter." I was, however, able to find an account with the same username as your GitHub. Would you like to update the email address for that account instead? Thanks.

**Comment by vtexier** [comment]
Hi !
Thanks to handle my request ! I was in quite a hurry, so I deleted the account to use the email address on another account. Everything was fine, but I forgot to close this request. Sorry for that.

I close the request.
