### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by zlk-sys** [pypi/support#4219]
### PyPI Username

zenglk

### Reason for request

I accidentally lost my authentication software and couldn't find my recovery key while installing a new system for my computer. My email can be accessed normally, please help me restore my pypi account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @zlk-sys,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @zlk-sys,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
