### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by BirchKwok** [pypi/support#4220]
### PyPI Username

birch.kwok

### Reason for request

 - Lost 2FA authentication app and security token
 I have been using a token to publish and update packages via Twine. Recently, I lost my mobile device and can no longer use 2FA for verification. Unfortunately, I forgot to set up recovery codes when I enabled 2FA, which has resulted in my losing access to my PyPI account. I am requesting assistance to recover my account because it is extremely important to me. The packages on the PyPI platform are the result of my hard work and dedication. Thank you once again to your team for your outstanding contributions to the Python ecosystem!

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by BirchKwok** [comment]
I'm actually not sure if I have a recovery code set, I can't find it at the moment and desperately need your help. If you need me to provide the account token, I still keep it here.

**Comment by Thespi-Brain** [comment]
Hi @BirchKwok,

Thanks for providing the details related to your account. I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @BirchKwok,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
