### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by qm-devops-18** [pypi/support#4228]
### PyPI Username

'qm_devops'

### Reason for request

Lost 2FA authentication app and security tokens

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Duplicate issue https://github.com/pypi/support/issues/4201
