### ISSUE TITLE
File Limit Request: ml_pitch_models_data_crepe_full - 125 MB

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [pypi/support#4229]
### Project URL

https://pypi.org/project/ml-pitch-models-data-crepe-full/

### Does this project already exist?

- [X] Yes

### New Limit

125

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This package is a part of a new project to provide ML-based human voice pitch detectors (the main package is to be released). It aims to offer a couple TensorFlow-based models. This package is intended to be a single-version data-only package, and its role of is to provide the neural net weights of one preset model as an optional dependency.

### Reasons for the request

This package hosts the coefficient data of a large preset neural-net model. The project size will not increase in the future as the model is set in stone.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @tikuma-lsuhsc :wave:
I've set the upload limit for `ml_pitch_models_data_crepe_full` to 200 MB on PyPI.
have a nice week :tada:
