### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by russelldj** [pypi/support#4230]
### PyPI Username

`russelldj`

### Reason for request

My primary email was a work address from a company I am no longer with. I also have a personal address associated with the account but it's not the primary one. My primary account was unverified so now I can't perform some actions.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @russelldj,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4230). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @russelldj,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @russelldj,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
