### ISSUE TITLE
File Limit Request: imfusion-sdk - 200 MB

### ISSUE THREAD

**Issue by IljaManakov** [pypi/support#4231]
### Project URL

https://pypi.org/project/imfusion-sdk/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

imfusion-sdk consists for the most part of Python bindings to the ImFusion SDK (+ dependencies). The ImFusion SDK is a toolkit for working with medical image data, including images, meshes, pointclouds, etc. We want to release a version of our Python bindings which is free for non-commercial use, hence the desire to upload to PyPI.

Since this package consists of mostly bindings to C++ code, we also have to ship the dynamic libraries that the ImFusion SDK depends on + the things we link in statically. 
A big chunk of the size is also due to the inclusion of custom ML models, which are part of some of our algorithms, in the binaries.

### Reasons for the request

As mentioned above, our wheel has to include many precompiled binaries, therefore it exceeds the size limit. Our current sizes are ~75MB on Windows, ~110MB on Linux and ~150MB on macOS. We are not yet including all of our plugins, in the wheel and we have not yet decided if we are going to include some of the more specialized ones in the public wheel. If we decide to include them in the future the wheels would grow in size accordingly. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by IljaManakov** [comment]
I stand corrected, the biggest one is actually our own MachineLearning binary at ~60MB probably due to the template meta stuff in there + static dependencies.

**Comment by cmaureir** [comment]
Hey @IljaManakov :wave:
I've set the upload limit for `imfusion-sdk` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
have a nice week :snake:

**Comment by IljaManakov** [comment]
Many thanks!
