### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by zooba** [pypi/support#4232]
### PyPI Username

`DocumentDB`

### Reason for request

Account was owned by a former employee and we have no way to access it.

Our `microsoft` account is already a maintainer on some packages owned by `DocumentDB`, but we have no ownership of them. There are also some packages solely owned by `DocumentDB` that are ours.

We still own the (incoming msgs only) email addresses listed in package metadata, but they don't appear to be on the account. We would be happy with reassigning the account email (pinging the current owner should be fast because emails will likely bounce) to either of those (`askdocdb@` or `ascl@`) and we can recover from there, or else promoting/adding `microsoft` to Owner on the four packages (`azure-cosmos`, `azure-cosmosdb-table`, `azure-cosmosdb-nspkg` and `pydocumentdb`).

The `ipython-cosmos-extension` package has another owner, who is welcome to keep it.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @zooba,

Thanks for providing the details. I think the best course of action would be to change the primary email address of this account. Please contact support@pypi.org with an email address that you would like the account to be associated with and please reference this link (https://github.com/pypi/support/issues/4232). We will proceed from there. Thanks!

**Comment by zooba** [comment]
Sent

**Comment by Thespi-Brain** [comment]
Hi @zooba,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @zooba,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
