### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by zooba** [pypi/support#4233]
### PyPI Username

`xclientdev`

### Reason for request

We have lost access to the primary email address, but still have access (incoming msgs only) to a secondary one. It has been verified, but apparently we cannot switch the primary email without verifying the current one.

I'm happy to confirm ownership of the verified email address through another message. The unverified ones ought to bounce, but I'm not sure if we send bounce messages to external recipients or not.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @zooba,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4233). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @zooba,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @zooba,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
