### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by aperullo** [pypi/support#4234]
### PyPI Username

`aperullo`

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @aperullo.

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4234). We will proceed from there. Thanks!

**Comment by aperullo** [comment]
I was able recover access to the email and update to a new I'll be able to keep access to. Thank you!
