### ISSUE TITLE
Project Limit Request: `biotite` - 20 GB

### ISSUE THREAD

**Issue by padix-key** [pypi/support#4239]
### Project URL

https://pypi.org/project/biotite/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project provides a comprehensive set of functionalities for bioinformatics. It exists for ~6.5 years.

### How large is each release?

~300 MB. Each distribution bundles a reduced and compressed version of the [*Chemical Component Dictionary*](http://www.wwpdb.org/data/ccd) required for a number of functionalities, which increases the wheel size. Furthermore each wheel contains compiled Cython modules.

### How frequently do you make a release?

Approximately every 2-3 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @padix-key :wave:
I've set the project limit for `biotite` to 20 GB on PyPI.
Have a nice week :tada:

**Comment by padix-key** [comment]
Thanks a lot!
