### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kamilrybacki** [pypi/support#4251]
### PyPI Username

kamil.rybacki

### Reason for request

Lost 2FA authentication app or security token: got new phone and forgot to setup Google Auth app

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by kamilrybacki** [comment]
Managed to migrate to new Auth app, closing

**Comment by Thespi-Brain** [comment]
Hi @kamilrybacki, 
That's great, closing the issue.
