### ISSUE TITLE
Limit Request: atoti-server - 160 MiB

### ISSUE THREAD

**Issue by tibdex** [pypi/support#4259]
### Project URL

https://pypi.org/project/atoti-server

### Does this project already exist?

- [X] Yes

### New Limit

160 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Atoti is a Python library for aggregating data and creating dataviz widgets such as pivot tables and charts in a Jupyter notebook. It comes with a collaborative BI web application. There is a free community edition.

For performance reasons, the server is implemented in Java so we have to ship a JAR to our users.

_Note_: this limit was already granted to `atoti` in https://github.com/pypi/support/issues/300 but the next minor release (0.9.0) will split this package in two: `atoti-client` for client-only code (pure Python), and `atoti-server` to embed the JAR required to start a new session. This will allow users only interested in the client part to not have to download the JAR. We would need to keep the 160 MiB limit on `atoti` just in case we have to publish a couple 0.8.x bugfix releases.

### Reasons for the request

This request abide by:

https://github.com/pypi/support/blob/f62f0ee62096ecefda543bb69bc48cd1126bfffa/README.md?plain=1#L30-L33

and does NOT fall in this category:

https://github.com/pypi/support/blob/f62f0ee62096ecefda543bb69bc48cd1126bfffa/README.md?plain=1#L43

since we use https://pypi.org/project/jdk4py for that.

We do not expect release size to increase (#300 was opened more than 3 years ago and we're requesting the same limit here). The frequency of releases may actually slow down (from monthly to every 6 weeks).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @tibdex :wave:
I've set the upload limit for `atoti-server` to 200 MB on PyPI but not on TestPyPI, because the project doesn't exist. In case you still require that, feel free to open a new request.
have a nice week :tada:

**Comment by tibdex** [comment]
Thank you Cristián!
