### ISSUE TITLE
Project Limit Request: uv - 40 GB

### ISSUE THREAD

**Issue by zanieb** [pypi/support#4260]
### Project URL

https://pypi.org/project/uv

### Does this project already exist?

- [X] Yes

### New limit

40GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

uv is a Python packaging tool maintained by Astral and is used by many major projects. It was released in February. A similar increase was granted for Ruff (https://github.com/pypi/support/issues/2545), though that was limited to 20GB I think it's reasonable to request 40GB here as the wheels are larger than discussed in that issue.

### How large is each release?

uv is built in Rust and we consequently build wheels for many platforms.

We publish [17 wheels](https://pypi.org/project/uv/0.2.13/#files) for each release, each is ~12 MB bringing us to a total of ~200 MB per release. We also publish a source distribution that is ~1 MB.

We do not bundle other packages or data in our project. We generally attempt to reduce the size of our binaries, but a special effort has not been made to make it as small as possible. These wheels are comparably sized to those in [Ruff](https://pypi.org/project/ruff/#files).

We have considered publishing less wheels, as some can be redundant, but this caused problems for consumers e.g. https://github.com/astral-sh/uv/issues/4122.

### How frequently do you make a release?

At least once a week, as much as every day. We are adding new functionality quickly and there are lots of packaging edge case bugs to fix!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @zanieb :wave:
I've set the project limit for `uv` to 40 GB on PyPI. Please be mindful of the frequency of releases at that size, and explore options to reduce the amount of wheels by some research on PyO3 and the Python Limited API.
Have a nice week :+1:

**Comment by charliermarsh** [comment]
Thank you so much.

**Comment by zanieb** [comment]
Thank you!
