### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by umittadelen** [pypi/support#4265]
### PyPI Username

umittadelen

### Reason for request

I lost the recovery codes and authenticator for my TestPyPI account

>i can login to my main PyPI account and i need to publish my update as soon as possible

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @umittadelen,

I have initiated an account recovery process for your test pypi account and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @umittadelen,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued on your test.pypi account. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
