### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by git-foysal-1** [pypi/support#4267]
### PyPI Username

foysalf

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by git-foysal-1** [comment]
Please help

**Comment by iamfoysal** [comment]
**I'm actually not sure if I have a recovery code set, I can't find it at the moment and desperately need your help. If you need me to provide the account token, I still keep it here.**

**Comment by Thespi-Brain** [comment]
Hi @git-foysal-1,

Thanks for your patience. I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @iamfoysal,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
