### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lasarux** [pypi/support#4269]
### PyPI Username

lasarux

### Reason for request

I no longer have access to the domain neuroomante.com. I have a verified secondary email address, pedro@impulso.xyz. Could you please update my primary email address to this one?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @lasarux,

I have gone ahead and updated your primary email address and also reset your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
