### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sbrunato** [pypi/support#4274]
### PyPI Username

geostorm

### Reason for request

Lost access to email address.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @sbrunato,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4274). We will proceed from there. Thanks!

**Comment by sbrunato** [comment]
thanks @Thespi-Brain , we finally recovered the access to this email
