### ISSUE TITLE
我想恢复我的账号登录，因为目前我无法使用双验证登录

### ISSUE THREAD

**Issue by leslie110** [pypi/support#4279]
### PyPI Username

leslie110

### Reason for request

我丢失了我的code生成程序，并且当时忘记了保存恢复码，我是可以登录成功，以此证明是我的账号

![Snipaste_2024-06-25_16-28-18](https://github.com/pypi/support/assets/33894471/18229018-4172-494a-9388-9e315559e524)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by cmaureir** [comment]
Hey @leslie110 :wave:
In order for the admins to reply to your issue, can you please edit your post and use English? We sadly cannot provide support in other languages

**Comment by Thespi-Brain** [comment]
Closing, duplicate to this issue https://github.com/pypi/support/issues/4284
