### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by alanlivio** [pypi/support#4280]
### PyPI Username

alanlivio

### Reason for request

Lost 2FA authentication app and recovery codes
But not Lost access to the email address
But not Lost access passwords
I just Lost the 2FA authentication app and recovery codes when setup new devices

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by alanlivio** [comment]
Hi @ewdurbin. I understand that you are helping people with the account-recovery label. I just imagine how much your workload is. But can ask for your help in my issue. I really appreciate. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @alanlivio,

Thanks for your patience. I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @alanlivio,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
