### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by emilleishida** [pypi/support#4285]
### PyPI Username

emilleishida

### Reason for request

Lost 2FA authentication app 

I do not remember setting it up. I have an authenticator app that I have been using for a long time but the pypi does not appear as one of the registered servers. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @emilleishida,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
