### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kiasar** [pypi/support#4288]
### PyPI Username

Kiasari

### Reason for request

Lost access to email address

Hi there, 
I lost my access to my previous university email. I want to change it to my current university email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by kiasar** [comment]
Hi @ewdurbin, I hope you are doing great.

Would you help me with this please? When I opened the account I used my previous university email. Now that email doesn't exist anymore. Would you please help me change it?

Regards.

**Comment by Thespi-Brain** [comment]
Hi @kiasar,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4288). We will proceed from there. Thanks!
