### ISSUE TITLE
File Limit Request:sc3dg - 150 MB

### ISSUE THREAD

**Issue by CCCKW** [pypi/support#4291]
### Project URL

https://pypi.org/project/sc3dg/

### Does this project already exist?

- [X] Yes

### New Limit

200m

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

I boudle other package like bwa bowite2 minimap2 fastp to my  package, for avoiding the error

### Reasons for the request

I boudle other package like bwa bowite2 minimap2 fastp to my  package, for avoiding the error

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @CCCKW :wave:
There was a discrepancy on the request size of the title and the information of the project, but I set the file upload limit of `sc3dg` to 200M.
Have a nice week :rocket:
