### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by WhitePoodleMoth** [pypi/support#4293]
### PyPI Username

cauapb

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @WhitePoodleMoth,

I was unfortunately unable to find any account with the username 'cauapb.' Is there any other username that you could have possibly used for your PyPI account? Thanks!

**Comment by WhitePoodleMoth** [comment]
I’ve already sent an email requesting account deletion. After attempting to delete it, I realized I needed to recover my password, but now the account has been deleted. Thank you!
