### ISSUE TITLE
Project Limit Request: aws-cdk-lib - 50 GiB

### ISSUE THREAD

**Issue by scanlonp** [pypi/support#4294]
### Project URL

https://pypi.org/project/aws-cdk-lib/

### Does this project already exist?

- [X] Yes

### New limit

50 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Project on github: https://github.com/aws/aws-cdk

We started releasing aws-cdk-lib weekly since 01/21/2021, and the total size of all published artifacts is just under 20 GiB. The current package size is ~34 MiB, and we expect that to remain generally the same. 

We have hit the 20 GiB limit with our last release, which is blocking the source distribution upload, so requesting an increase.

### How large is each release?

~ 34 MiB
A package that bundles all of the JavaScript code that the python source calls through a technology called JSII. This package is essentially the aws-cdk-lib npm package.

We have reduced our package size since our last size limit (#1642) request by almost half by reducing bundled dependencies.

### How frequently do you make a release?

Once per week.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by comcalvi** [comment]
Can we query the PyPI API to get the current package size, as in the number that counts towards the limit? I found this: https://pypistats.org/api/ but it doesn't seem to support getting the current total file size.

**Comment by scanlonp** [comment]
We deleted some of our alpha versions to free up space, and have been able to make our last couple releases. However, we are approaching our limit again, and will likely hit it within the next few weeks.

If the jump to 50 GiB is too big for immediate approval, an increase to 30 GiB would be appreciated.

**Comment by cmaureir** [comment]
Hey @scanlonp :wave:
I've set the project limit for `aws-cdk-lib` to 50 GB on PyPI. Please be mindful of the frequency of releases.
Have a nice week :rocket:
