### ISSUE TITLE
File Limit Request: triton-pascal - 250 MiB

### ISSUE THREAD

**Issue by sasha0552** [pypi/support#4295]
### Project URL

https://pypi.org/project/triton-pascal/

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a fork of the [Triton](https://github.com/triton-lang/triton) ([PyPI](https://pypi.org/project/triton/)) project, which provides support for NVIDIA GPUs with the Pascal microarchitecture, such as NVIDIA Tesla P40, since the Triton developers [don't want to cooperate](https://github.com/triton-lang/triton/pull/3874#issuecomment-2106856229) with support for such older GPUs.

### Reasons for the request

Triton wheels are ~~160~~ 209 MiB and cannot be uploaded without expanding the limit.

I don't expect frequent releases, and will only upload packages starting with the `2.2.0` release (~~three~~ four releases total, `2.2.0`, `2.3.0`, `2.3.1` and `3.0.0`, ~3450 MiB total for 5 python versions).

I tried reducing the wheel size, but even with stripped debug info `triton==3.0.0` can't be uploaded.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sasha0552** [comment]
I found a way to reduce the size of the `triton` wheels, but it is still 95 MiB, and these wheels will probably be harder to debug because `assert`s was removed along with the debug info. Also, future releases of `triton` may increase the size, so I would appreciate it if this request is approved. Thanks!

**Comment by cmaureir** [comment]
Hey @sasha0552 :wave:
I've set the upload limit for `triton-pascal` to 250 MB on PyPI. Please be mindful of the frequency of releases at that size and maybe explore the Python's Limited API to reduce the amount of wheel per release.
Have a nice week :rocket:
