### ISSUE TITLE
File Limit Request: sc3dg - 250 MB

### ISSUE THREAD

**Issue by CCCKW** [pypi/support#4297]
### Project URL

https://pypi.org/project/sc3dg/

### Does this project already exist?

- [X] Yes

### New Limit

250MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a software for single cell Hi-C processing.I don't have any bundled data, mainly because my package encapsulates other software, and these software need to be recompiled according to my software. I modified their compilation conditions, so there is no data, all are compiled software

### Reasons for the request

To prevent installation dependency errors, I packaged some packages into my package to ensure normal installation.I would like to have a limit of 250Mb per time

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
I addressed this on the other issue you created @CCCKW so I'm closing this.
https://github.com/pypi/support/issues/4291
