### ISSUE TITLE
File Limit Request: etched-blitz - 200 MB

### ISSUE THREAD

**Issue by zolinthecow** [pypi/support#4298]
### Project URL

https://pypi.org/project/etched-blitz/

### Does this project already exist?

- [X] Yes

### New Limit

200 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Blitz is a fork of vLLM which is being developed for the company [Etched](etched.com). We are developing this package to allow any customers to switch over from vLLM to our chips as smoothly as possible. It has all the same functionality as vLLM, except built for our hardware. For now it is closed-source, but we have plans to open-source it as soon as sales begin.

Since this is a fork meant to mirror vLLM, the file size cannot really be reduced much. The temporary build I have published right now is just a CPU-only build to reduce file size.

### Reasons for the request

We need the additional limit so we can publish the package ASAP and begin using it in demos for sales. I want to be able to use it in a colab environment to do testing/demos, which requires it to be published ASAP. This will have to be published anyways eventually.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @zolinthecow :wave:
I've set the upload limit for `etched-blitz` to 200 MB on PyPI. 
Have a nice week :rocket:
