### ISSUE TITLE
File Limit Request: bigdl-core-cpp - 200 MiB

### ISSUE THREAD

**Issue by liu-shaojun** [pypi/support#4303]
### Project URL

https://pypi.org/project/bigdl-core-cpp/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`bigdl-core-cpp` is providing acceleration for LLM inference on Intel GPUs. It has been active for 2 months.

### Reasons for the request

We request increase release size for bigdl-core-cpp is because we are adding new shared libraries for kernels, and the file size has already been ~90MB, which could be easily exceeded.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by liu-shaojun** [comment]
cc: @rnwang04

**Comment by cmaureir** [comment]
Hello @liu-shaojun :wave:
I've set the upload limit for `bigdl-core-cpp` to 200 MB on PyPI. 
Have a nice week :rocket:

**Comment by liu-shaojun** [comment]
Thanks! @cmaureir
