### ISSUE TITLE
File Limit Request: groupdocs-metadata-net - 300 MiB

### ISSUE THREAD

**Issue by yuriy-mazurchuk** [pypi/support#4306]
### Project URL

https://pypi.org/project/groupdocs-metadata-net/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

It's the first official release of the GroupDocs.Metadata library (Aspose Pty)
https://products.groupdocs.com/metadata/python-net/
https://releases.groupdocs.com/metadata/python-net/

### Reasons for the request

The package includes the necessary DLL files which use neural networks that are essential for the core functionality of our package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @yuriy-mazurchuk :wave:
I've set the upload limit for `groupdocs-metadata-net` to 300 MB on PyPI only, because the project doesn't exist on TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
