### ISSUE TITLE
File Limit Request: groupdocs-watermark-net - 300 MiB

### ISSUE THREAD

**Issue by yuriy-mazurchuk** [pypi/support#4307]
### Project URL

https://pypi.org/project/groupdocs-watermark-net/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

It's the first official release of the GroupDocs.Watermark library (Aspose Pty)
https://products.groupdocs.com/watermark/python-net/
https://releases.groupdocs.com/watermark/python-net/

### Reasons for the request

The package includes the necessary DLL files which use neural networks that are essential for the core functionality of our package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @yuriy-mazurchuk :wave:
Like the other issue, I have set the file limit of `groupdocs-watermark-net` to 300MB on PyPI and TestPyPI.
Have a nice week :rocket:
