### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Sema4ka0** [pypi/support#4309]
### PyPI Username

Sema4ka0

### Reason for request

Lost access to email address.
change to: seem.git@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Sema4ka0** [comment]
I solved it myself, thanks

**Comment by Thespi-Brain** [comment]
Hi @Sema4ka0,

Great to hear that! Closing this issue.
