### ISSUE TITLE
Project Limit Request: mlpack - 100 GB

### ISSUE THREAD

**Issue by rcurtin** [pypi/support#4312]
### Project URL

https://pypi.org/project/mlpack/

### Does this project already exist?

- [X] Yes

### New limit

100 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

mlpack is a comprehensive C++ machine learning library that has extensive bindings to Python.  As part of the wheel-building process, we make lots of shared libraries that get bundled with each wheel.

In the past we have stayed under the size limit by deleting old releases, but this is not a great solution.

### How large is each release?

We typically produce close to 100 different wheels for different configurations with cibuildwheel, each of which is typically somewhere around 20-25 MiB, totaling 2-2.5 GiB per release.

### How frequently do you make a release?

About once every four or five months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @rcurtin :wave:
The project have the default limit of 10GB at the moment, and a jump to 100GB is a lot.
Would you be OK with an increase to 20-30GB for example?
Have you tried somethin to reduce the amount of wheels you currently have per-release? (for example the use of the Python's limited API)

Let me know

**Comment by rcurtin** [comment]
Hey @cmaureir, thanks for the response and sorry it took so long to get back to you---I have been a bit underwater with other things.

20-30GB would definitely still be helpful. I am interested in the limited API to reduce the number of wheels, but maintenance time is limited for us. I hope to try it via cibuildwheel soon, and that will definitely help but given the size of each individual wheel, size will still be something of a concern (especially as the number of released versions increases).

Thanks so much!

**Comment by cmaureir** [comment]
@rcurtin I have set the project limit to 30G, in case you ran out of space, feel free to open a new issue so we can continue this discussion :rocket:

**Comment by rcurtin** [comment]
Thanks!  Much appreciated.
