### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ksamuel** [pypi/support#4315]
### PyPI Username

tetricoins

### Reason for request

I use the old way of authenticating with username/password with twine to upload new versions. But I never confirmed my email, which is now invalid (old domain name).

I can connect to my account, but can't do anything with it, and can't push a new version to the repository.

If this is too much work, you can freeze the repository forever and I can open a new one with a different name, it's an old software few people use anyway and the update is incompatible with 1.3.

Cheers

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ksamuel,

Thanks for providing some details regarding your account. Let's start with updating your primary email address so that we can begin the account recovery process. Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4315). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ksamuel,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ksamuel 

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by ksamuel** [comment]
Thank you, I recovered the account and this ticket is successfully resolved.
