### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by artur-trzesiok** [pypi/support#4317]
### PyPI Username

k3d

### Reason for request

Lost 2FA authentication app and recovery codes. I have login and password 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by artur-trzesiok** [comment]
Can I do anything to make easier a recovery?

**Comment by Thespi-Brain** [comment]
Hi @artur-trzesiok,

Thanks for your patience. I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by artur-trzesiok** [comment]
First of all - many thanks. Done. Waiting for the email now.

**Comment by Thespi-Brain** [comment]
Hi @artur-trzesiok,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by artur-trzesiok** [comment]
Thanks a lot. Everything is working! You are awesome!
