### ISSUE TITLE
File Limit Request: libtpu-nightly - 350 MB

### ISSUE THREAD

**Issue by learning-to-play** [pypi/support#4318]
### Project URL

https://pypi.org/project/libtpu-nightly

### Does this project already exist?

- [X] Yes

### New Limit

350 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project will release Google's TPU library. The project has been active for years.
For example, see libtpu release for JAX at https://storage.googleapis.com/jax-releases/libtpu_releases.html.

### Reasons for the request

Publishing TPU libraries on PyPI isn't currently possible because the packages are larger than the file size limit. Publishing libtpu to PyPI will simplify the installation process for TensorFlow and JAX users who need to install libtpu for using Cloud TPUs.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @learning-to-play :wave:
I've set the upload limit for `libtpu-nightly` to 350 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:

**Comment by learning-to-play** [comment]
Hi @cmaureir , Great! Thank you very much! Will do.
