### ISSUE TITLE
Project Limit Request: DSGRN - 20 GB

### ISSUE THREAD

**Issue by marciogameiro** [pypi/support#4327]
### Project URL

https://pypi.org/project/DSGRN/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project uses computational dynamics to produce dynamical surveys of switching models of regulatory networks. The resulting data is stored into a database which can then be queried for further research. The project has been active on PyPI since March 2021.

It is possible that the total project size will increase in the future.

### How large is each release?

~800 MiB total. About 50 linux wheels and 30 Windows/macOS wheels of about 10 MiB each. The wheels contain the binary files from C++ code and there are many wheels because of different versions of Python and PyPy. Future releases will stop distributing muslinux and pypy wheels to decrease the size of each release.

### How frequently do you make a release?

About every 3 months or so.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @marciogameiro :wave:
I've set the project limit for `DSGRN` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
