### ISSUE TITLE
File Limit Request: NeuroMANCER - 120 MB

### ISSUE THREAD

**Issue by RBirmiwal** [pypi/support#4339]
### Project URL

https://pypi.org/project/neuromancer/

### Does this project already exist?

- [X] Yes

### New Limit

120

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

PyTorch scientific machine learning library

### Reasons for the request

Project growing 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @RBirmiwal :wave:
I've set the upload limit for `NeuroMANCER` to 150 MB on PyPI. Please be mindful for future requests to provide more useful information, specifically on the "reason for requests" that could include the inclusion of new files, new features, ways you have tried to reduce the wheel the size and have not worked, etc.

Have  a nice week :rocket:
