### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by djwooten** [pypi/support#4343]
### PyPI Username

wooten

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by djwooten** [comment]
I previously updated my primary email for my test.pypi.org account name `wootentest`, but failed to update my email for my main account `wooten` on pypi.org, and now the old primary email address does not exist anymore.

Both accounts show that I am only the maintainer of the https://pypi.org/project/synergy/ project, the homepage of which is my github https://github.com/djwooten/synergy.

Please let me know if there is any additional information I can provide. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @djwooten,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4343). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @djwooten,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @djwooten,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
