### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by leoncardi** [pypi/support#4351]
### PyPI Username

leoncardi

### Reason for request

(Lost access to 2FA authentication app)

Recently, my device was damaged beyond repair, and I had to switch to a new one. As a result, I lost access to my 2FA authentication app, making it impossible to log in to my PyPI account. This issue cannot be resolved by recovering the authenticator from the damaged device. 

I would greatly appreciate assistance in helping me regain access to my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @leoncardi,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by leoncardi** [comment]
Hello, I have read and replied to the email now. I am still waiting for the solution. Thank you!

**Comment by Thespi-Brain** [comment]
Hi @leoncardi,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
