### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by devxpy** [pypi/support#4354]
### PyPI Username

devxpy

### Reason for request

Lost access to primary email address. secondary email address has been verified

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @devxpy,

I took a look into your account and it seems like you were able to successfully update your preferred email address, which is great. Are you still having issues logging in? Let me know, and we will go from there. Thanks!
