### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by YenochQin** [pypi/support#4357]
### PyPI Username

Yenoch

### Reason for request

I forget my password, and I can't receive the Reset email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @YenochQin 

We don't have an existing username for you on PyPI, however, there is an existing username on test.pypi.org. Did you mean to refer to that account for your login issue? Please clarify.

**Comment by Thespi-Brain** [comment]
Hi @YenochQin,

We haven't heard back from you, but I noticed that you were able to create an account for yourself on PyPI and were able to successfully login, which is great! I am closing this issue, but let us know if you are having any future problems. Thanks!
