### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by fredg0** [pypi/support#436]
Request for account recovery.

## PyPI Username

`fredg`

---

##  Reason for request

Reason:
Hello,

I have no longer access to the emails used.

After a break learning Python, I have now time to learn again.
This first little project was a tiny contribution for the slackware linux community 👍 https://pypi.org/project/ParsePkgtxt/
It seems nothing but I would like to update it with some others ones I have begin to work on.
Here is the code hosted on a gitlab repo : https://framagit.org/fredg/ParsePkgtxt
It was used with that one https://framagit.org/fredg/pkgtxt2db

My account is https://pypi.org/user/fredg/
I can create a new one but, please, it is important to me to recover this one with my alias.

Best regards.

Frédéric Galusik.

**Comment by ewdurbin** [comment]
To confirm you've lost access to the @gmail.com address associated with the user account?

Also neither of the repositories linked are publicly accessible for verification.

**Comment by fredg0** [comment]
Hi,

At first, thanks for watching at this.

Then yes, I confirm I have closed my gmail account.
My repositories are now self hosted : 
- https://dev.galusik.fr/cgi-bin/gotweb/gotweb?path=ParsePkgtxt.git&action=summary
- https://dev.galusik.fr/cgi-bin/gotweb/gotweb?path=pkgtxt2db.git&action=summary

Best regards.

**Comment by ewdurbin** [comment]
Attempted to contact via primary email address on the account, if it bounces or there is no response in 7 days we will proceed with recovery.

**Comment by ewdurbin** [comment]
@fredg0 do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: fredg" to proceed

**Comment by fredg0** [comment]
@ewdurbin Yes I do.
But, sorry, I do not received any mail.
Which one did you choose ?
( dev AT galusik dot fr )

Best regards.

**Comment by ewdurbin** [comment]
The user account is associated with an @gmail.com address. Message has subject "PyPI Account Recovery Request: fredg" and was delivered from an @python.org email address.

**Comment by fredg0** [comment]
Hi,

As said in the first post, the reason that I made this request is because I have no longer access to the email used for the account.

Cheers.

**Comment by ewdurbin** [comment]
There's no record that the address bounced. Do you believe it has been re-registered?

**Comment by fredg0** [comment]
I don't think so.

**Comment by Thespi-Brain** [comment]
Hi @fredg0,

I am following up regarding your request. Are you still having an issue regarding logging in and your email address? Let us know, and we will go from there. I will keep this issue open for another week unless I hear from you earlier. After that, feel free to open a new request if you are still having login issues. Thanks.

**Comment by fredg0** [comment]
Hi @Thespi-Brain 
Yes, the issue is still present ;)

**Comment by Thespi-Brain** [comment]
Hi @fredg0,

Thanks for replying back. Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/436). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @fredg0,

Thanks for sending over your preferred email address. However, in order to start the account recovery process to reset your 2FA and recovery codes, your account needs to have a valid/active link to a public repo of your project. Unfortunately, when I took a look into your account, there was no such active link. 

What I can offer as a workaround is for you to send an email to support@pypi.org confirming your intent to reset your 2FA and recovery codes with a link to this issue (https://github.com/pypi/support/issues/436). There will be a 7 day wait period from that email as part of our verification/security policy, after which we will go ahead and reset your account and update your email address. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @fredg0,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by fredg0** [comment]
All is OK !!
A very big thank you.
Best regards :)
