### ISSUE TITLE
PEP 541 Request: conduct

### ISSUE THREAD

**Issue by asmacdo** [pypi/support#4360]
### Project to be claimed

`conduct`: https://pypi.org/project/conduct/

### Your PyPI username

`asmacdo`: https://pypi.org/user/asmacdo/

## Evidence that project has been abandoned: 
 - Only [1 commit ](https://github.com/lnbits/conduct/commit/dffc1cb27c887a77120df592c37f5335f71a6509) 4 years ago
 - Only 1 release [0.0.0](https://pypi.org/project/conduct/0.0.0/) 4 years ago 0.0.0 May 2, 2020
 - Only [1 issue ](https://github.com/lnbits/conduct/issues/2)(mine asking if project name is unused, no response)
 - PyPI project owner @eillarra believes it is abandoned, but is no longer part of the Inbits org and wants to proceed respectfully of the org.

## Replacement Project: 
The [Center for Open Neuroscience](https://centerforopenneuroscience.org/) has created  https://github.com/con/duct  for collecting runtime information of arbitrary commands  (similar to time). It is designed specifically for scientific use cases, ie collecting information (wall clock time, resource usage, etc) to facilitate replication and reuse of scientific analysis software.

The tool has been in development for several months, is tested, is documented, and is ready to be released and used.

## Alternative Solution: Bypass "name similarity" validation

We do not specifically need the name `conduct`, we originally intended to publish as `con-duct`, but this failed validation "too similar to existing project". @di is there a way to manually bypass that validation? , that might be the easiest/quickest solution. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: https://github.com/lnbits/conduct
Replacement: https://github.com/con/duct

### Contact and additional research

- Attempt 1: Email the PyPI project owner 
    - 2024/06/8 Contacted https://github.com/eillarra via PyPI listed email
    - @eillarra was responsive, but is no longer a part of the [Inbits organization](https://github.com/lnbits)
    - @eillarra suggested reaching out to [@arc](https://github.com/arcbtc)
- Attempt 2: File issue
   - 2024/06/10 Filed https://github.com/lnbits/conduct/issues/2
   - Tagged  @arcbtc
   - No response
- Attempt 3: Contacting @arcbtc
   - No email is listed on [gh profile](https://github.com/arcbtc)
   - Reached out via Twitter DM  2024/06/13
   - (no response) 
- Attempt 4: Ask PyPI owner to reach out
   - 2024/06/21 @eillarra reached out through "another channel" 
   - No response

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by arc** [comment]
Hi, it looks like the intention here was apparently to tag @arcbtc, not me (@arc)? I'm stopping watching this issue. Thanks.

**Comment by di** [comment]
Hi @asmacdo, if you prefer the project name `con-duct` we can just release that to you instead.

**Comment by asmacdo** [comment]
@di `con-duct` works for me (better than a lengthy 541 request). 

Thanks for the incredible response time and everything you do for this community <3

**Comment by di** [comment]
@asmacdo Your `asmacdo` user should be able to publish `con-duct` now.
