### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by SunnyYYLin** [pypi/support#4366]
### PyPI Username

SunnyYYLin

### Reason for request

Lost 2FA authentication app or security token. Actually I forgot to connect it to a 2FA application after I generated the recovery codes and I lost the recovery codes in accident then.
The username of my PyPi account "SunnyYYLin" is the same as the username of my GitHub account  "SunnyYYLin". Moreover, my outlook mail accout "sunnylinyy@outlook.com" is connected with this PyPi account. Those can prove my ownership to the PyPi account “SunnyYYLin"

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @SunnyYYLin,

Thanks for providing details regarding your account. I have gone ahead and reset your 2FA and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
