### ISSUE TITLE
File Limit Request: igibson-eval - 200MB

### ISSUE THREAD

**Issue by JamesKrW** [pypi/support#4369]
### Project URL

https://pypi.org/project/igibson-eval/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

I bundeled some projects which extremely increased the size of this package:
Openvr
https://github.com/ValveSoftware/openvr

### Reasons for the request

The zip file of the release 1.0.0 is 187 MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @JamesKrW :wave:
I've set the upload limit for `igibson-eval` to 200 MB on PyPI.
Have a nice week :rocket:
