### ISSUE TITLE
File Limit Request: PVBM - 200 MB

### ISSUE THREAD

**Issue by johnfhima** [pypi/support#4371]
### Project URL

https://pypi.org/project/pvbm/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project include a segmentation model that is too much heavy.
I tried to make the overall size of the project smaller but it doesn't change...

### Reasons for the request

I would like to share this model as well as the package to our user community which are mainly medical staff. The fact that their main work is not around software development stress the need of a ready to use package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @johnfhima :wave:
I adjusted the title of the issue, because it stated 115M and on the body of the message you requested 200M.
I have set the file upload limit to 200M for `pvbm` on PyPI.
Have a nice week :rocket:
