### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Its-VrxxDev** [pypi/support#4375]
### PyPI Username

Vexx

### Reason for request

My account has a Session invalidated error when logging in, why and how can I recover my account? The account's most recent activity is uploading zaloapi version 1.0.3 and suspend version 1.0.2 due to pypi descriptor error.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Its-VrxxDev 

Your account was found to not be in compliance with our [Acceptable Use Policy](https://policies.python.org/pypi.org/Acceptable-Use-Policy/). If you think this is an error, please contact admin@pypi.org. Thanks.
