### ISSUE TITLE
File Limit Request: torch_cpp - 1000 MiB

### ISSUE THREAD

**Issue by PaliC** [pypi/support#4378]
### Project URL

https://pypi.org/project/torch-cpp/

### Does this project already exist?

- [X] Yes

### New Limit

1000 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

torch-cpp is a package containing the non-Python components of PyTorch. It was created to reduce the size of the main torch package, which was approaching its project size limit. By separating these Python-independent parts into torch-cpp:

We avoid redundant builds for different Python versions.
The main torch package's memory footprint is significantly reduced.
We distribute these core components only once.
torch-cpp is designed to be a standalone dependency for the torch package. This project is an active effort to optimize PyTorch's distribution and storage efficiency.

### Reasons for the request

Our binaries are typically around 800 MiB and are expected to increase in size over the coming years. We require a per-file size limit comparable to that of torch (1000 MiB) to adequately house this package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by PaliC** [comment]
cc: @malfet @seemethere @atalman @albanD

**Comment by cmaureir** [comment]
Hey @PaliC :wave:
I've set the upload limit for `torch_cpp` to  1000 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
