### ISSUE TITLE
Project Limit Request: torch_cpp - 50 GiB

### ISSUE THREAD

**Issue by PaliC** [pypi/support#4379]
### Project URL

pypi.org/project/torch-cpp

### Does this project already exist?

- [X] Yes

### New limit

100 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

torch-cpp is a package containing the non-Python components of PyTorch. It was created to reduce the size of the main torch package, which was approaching its project size limit. By separating these Python-independent parts into torch-cpp:

We avoid redundant builds for different Python versions.
The main torch package's memory footprint is significantly reduced.
We distribute these core components only once.
torch-cpp is designed to be a standalone dependency for the torch package. This project is an active effort to optimize PyTorch's distribution and storage efficiency.

### How large is each release?

We expect each release to be roughly 800 MiB to 1 GiB as a standalone wheel. 25 GB should give us runway for about 25 releases.
We have made efforts to reduce the package size of torch, which this is part of. (The project description should give you more information.)

### How frequently do you make a release?

Monthly (in line with torch)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by PaliC** [comment]
cc: @malfet @seemethere @atalman @albanD

**Comment by cmaureir** [comment]
Hello @PaliC :wave:
I've set the project limit for `torch_cpp` to 50 GB on PyPI, the amount on the issue title. Please be mindful of the frequency of releases at that size.

In case you would like to re-open the request for 100GB, the amount on the issue's body, feel free to re-open.

Have a nice week :rocket:
