### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gab-25** [pypi/support#4381]
### PyPI Username

Gab25

### Reason for request

Hi PyPI Support Team,

I am writing to request assistance in accessing my PyPI account. I have enabled two-factor authentication (2FA) on my account, but I have lost my recovery codes and I am no longer able to access my primary authentication method (my authenticator app).

I have tried to generate new recovery codes, but I am unable to do so. I have also tried contacting my email provider to recover my email address, but I have been unsuccessful.

I would appreciate it if you could please help me to regain access to my account. I am happy to provide any additional information that you may need.

Thank you for your time and assistance.

Sincerely, Gabriele Sorci

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @gab-25,

Thanks for providing details regarding your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
