### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Mr-SuperInsane** [pypi/support#4384]
### PyPI Username

Mr.Insane

### Reason for request

Lost 2FA authentication app and security token

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Mr-SuperInsane,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @Mr-SuperInsane,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by Mr-SuperInsane** [comment]
After resetting my password I logged in. But it asked for 2FA.” Enter
authentication code”
I was asked to “Enter authentication code”.

2024年8月15日(木) 9:49 thespibrain ***@***.***>:
