### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gotec** [pypi/support#4386]
### PyPI Username

cgote

### Reason for request

To whom it may concern,

As I am no longer affiliated with ETH Zurich I do not have access to the email registered as "primary email" in my account. Please kindly remove this email and make the second verified email the primary one.

Many thanks for your support!
Christoph

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @gotec,

Thanks for informing us what your preferred email is for your account. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4386). We will proceed from there. Thanks!

**Comment by gotec** [comment]
Hi @Thespi-Brain, many thanks for your response. I have contacted [support@pypi.org](mailto:support@pypi.org) as per your suggestion. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @gotec,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @gotec,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
