### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Coding-Noob-Jimmy** [pypi/support#4394]
### PyPI Username

Coding-Noob-Jimmy

### Reason for request

I typed in 2FA token shown on my authentication app, but can't login.
And I forget my recovery codes.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Coding-Noob-Jimmy,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @Coding-Noob-Jimmy,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
