### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by WRKampi** [pypi/support#4397]
### PyPI Username

WRKampi

### Reason for request

I see that this form now has the option to check: "I never generated or have lost access to the recovery codes for my account". This is applicable for my situation. I already did submit issue #4250, a few weeks ago. Hopefully, checking this option makes it easier to solve the issue. The issue is that I need to fill in an authentication code, but I don't recall setting up 2FA and haven't got pypi entries in my authenticators.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Duplicate issue https://github.com/pypi/support/issues/4250
