### ISSUE TITLE
Lost 2FA Access

### ISSUE THREAD

**Issue by Perphin** [pypi/support#4398]
### PyPI Username

perphin

### Reason for request

Dear PyPI Support Team,

I am a high school student in South Korea studying Python at school. I signed up for Pypi to learn how to use the Python library with my friends, but the following problem occurred:

I am writing to request assistance with recovering access to my PyPI account. Unfortunately, I have lost access to my Two-Factor Authentication (2FA) app due to accidental deletion, and I do not have my recovery codes available.

Emails of my account: jeyonghu0710@gmail.com

I have attempted to log in, but I am unable to obtain the necessary authentication codes. Additionally, I do not have my recovery codes, which has left me locked out of my account.

I promise to provide as much information as possible to support team to help them verify my identity.

Please let me know what steps I need to take to regain access to my account. I appreciate your assistance in this matter.

Thank you for your understanding and support.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Perphin,

Thanks for providing details regarding your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
