### ISSUE TITLE
File Limit Request: transformer-engine-cu12 - 500 MiB

### ISSUE THREAD

**Issue by ksivaman** [pypi/support#4401]
### Project URL

https://pypi.org/project/transformer-engine-cu12/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

TransformerEngine is a library for accelerating Transformer models on NVIDIA GPUs, including using 8-bit floating point (FP8) precision on Hopper and Ada GPUs, to provide better performance with lower memory utilization in both training and inference.

Although it is new to PyPI (May 2023), it has existed as an open source project on GitHub since 28th September 2022.

### Reasons for the request

The size of our binary per wheel per platform is 500MiB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ksivaman** [comment]
@cmaureir This is a follow-up request to #4052 to get us underway for publishing wheels!

**Comment by cmaureir** [comment]
Hey @ksivaman :wave:
I have set the limit of `transformer-engine-cu12` to 500MB on PyPI, but please be mindful with the frequency of the releases, otherwise you will hit the project limit after a couple of releases.
Have a nice week :rocket:
