### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by KomoriDev** [pypi/support#4404]
### PyPI Username

`mute23`

### Reason for request

I cannot find which 2FA authentication app I used to configure my 2FA on PyPI. However, I still have access to my email account. Could you please assist me in recovering access to my account?

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @KomoriDev,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by KomoriDev** [comment]
I have followed the instructions. Thank you for your help.

**Comment by Thespi-Brain** [comment]
Hi @KomoriDev,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
