### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by eneftci** [pypi/support#4405]
### PyPI Username

eneftci

### Reason for request

I do not have access to my primary email anymore ([eneftci@uci.edu](mailto:eneftci@uci.edu)) and without verifying it I cannot proceed further. Please help!. The secondary email on the account was added a while ago and should be the primary one.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @eneftci,

I took a look at your account and it seems like you were able to change the primary email address on your account yourself, which is great. Are you still having trouble accessing your account? Let me know, and we will go from there, thanks!

**Comment by eneftci** [comment]
Hi, looks like somebody did it for me. Problem is solved. Thank you!
