### ISSUE TITLE
Project Limit Request: pyarrow - 40 GiB

### ISSUE THREAD

**Issue by raulcd** [pypi/support#4409]
### Project URL

https://pypi.org/project/pyarrow/

### Does this project already exist?

- [X] Yes

### New limit

40 GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Apache Arrow bindings for Python. Active since 2017.

### How large is each release?

Source: ~1 MiB
Binaries: ~1200 MiB (Windows, macOS, Linux, CPython 3.{8,9,10,11 12})

### How frequently do you make a release?

We do major releases every 3 months and eventually some patch releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by raulcd** [comment]
@cmaureir FYI

**Comment by cmaureir** [comment]
Hello @raulcd :wave:
I've set the project limit for `pyarrow` to 40 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week! :snake:
