### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by christiam** [pypi/support#4411]
### PyPI Username

christiame

### Reason for request

Hi, I have lost access to email address that is listed as my primary email address in test.pypi.org . I have another email address associated with that account that has been verified, but I cannot set it as the primary account. 

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @christiam,

Can you please confirm your preferred email address for your test.pypi account at support@pypi.org and please reference this link (https://github.com/pypi/support/issues/4411). We will proceed from there. Thanks!

**Comment by christiam** [comment]
Done, thanks for looking into this!

**Comment by Thespi-Brain** [comment]
Hi @christiam,

Thanks for sending over your preferred email. I have initiated an account recovery process for your test.pypi account and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by christiam** [comment]
Thanks, I got the email and followed its instructions.

**Comment by Thespi-Brain** [comment]
Hi @christiam,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the test.pypi account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
