### ISSUE TITLE
Account recovery request for cosmic-api.com

### ISSUE THREAD

**Issue by boronine** [pypi/support#4413]
### PyPI Username

cosmic

### Reason for request

My primary email address, alexei.boronine@cosmic-api.com, is unaccessible because I let my old cosmic-api.com domain lapse. (UPDATE: My new email is alexei@boronine.com)

When this domain belonged to me the website looked like this:
https://web.archive.org/web/20160309234503/http://www.cosmic-api.com/

I now maintain what remains of this project as an open source GitHub organization:
https://github.com/cosmic-api

But I am unable to publish a new version until I restore access.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by danijar** [comment]
@Thespi-Brain Would you mind taking a look at this, please?

**Comment by danijar** [comment]
@Thespi-Brain Gentle ping! :)

Alexei offered transferring a PyPi name to me so that I can release a library, but needs to restore account access to do so.

**Comment by Thespi-Brain** [comment]
Hi @danijar and @boronine,

Thanks for your patience. We are working through issues in the order they were opened to make the process fair for everyone. I will definitely get to your issue soon and will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @boronine,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4413). We will proceed from there. Thanks!

**Comment by boronine** [comment]
Just sent you an email from alexei@boronine.com. Thanks in advance!

**Comment by Thespi-Brain** [comment]
Hi @boronine,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @boronine,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by boronine** [comment]
I was able to restore access, thank you!
