### ISSUE TITLE
Account recovery request - test.pypi

### ISSUE THREAD

**Issue by rebeccafair** [pypi/support#4414]
### PyPI Username

rebeccafair

### Reason for request

I never verified the primary email associated with my test.pypi account, I've now lost access to that primary email and I can't do anything else with my test.pypi account until the email is verified. Is it possible to set a new primary email? Note I've had to tick the box 'I never generated or have lost access to the recovery codes for my account' in order to post this, but I still have my recovery codes, I just can't see a way to change my primary email, even with access to the recovery codes. Thanks.

### Recovery Codes

- [ ] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @rebeccafair,

Yes, we can definitely update your primary email address on your test.pypi account. Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4414). We will proceed from there. Thanks!

**Comment by rebeccafair** [comment]
Thank you! I have sent an email to support and am awaiting a response.

**Comment by Thespi-Brain** [comment]
Hi @rebeccafair,

Thanks for sending over your preferred email. I have initiated an account recovery process for your Test.PyPI account and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @rebeccafair,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on your Test.PyPI account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
