### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by chordzero** [pypi/support#4416]
### PyPI Username

chordzero

### Reason for request

I realized only after clicking the sign-up button that I had entered `@gmail.com` as `@gmai.com`. Also, I couldn’t find a way to add a new email address.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @chordzero,

I have updated the primary email address on the account with the correct version. I have also reset your 2FA and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
