### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dmah42** [pypi/support#4418]
### PyPI Username

`benchmark-py`

### Reason for request

email address was added incorrectly and does not map to a real inbox.  i cannot add a new email or verify the current email.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @dmah42,

Could you please confirm the correct email address by sending an email support@pypi.org? Please reference this link (https://github.com/pypi/support/issues/4418) and we will proceed from there. Thanks!

**Comment by dmah42** [comment]
i have recovered the password from my password manager.  thank you.
