### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bendemeo** [pypi/support#4420]
### PyPI Username

`bdemeo`

### Reason for request

I have lost access to the institutional e-mail address associated with my account (bdemeo@g.harvard.edu) and this account has not been verified. I have only one repository (shannonca), which is associated with this github account.  Would you be able to help me recover this account so that I can update my package? Many thanks!

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @bendemeo,

Sure! Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4420). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @bendemeo,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @bendemeo,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
