### ISSUE TITLE
PEP 541 Request: ts-cli

### ISSUE THREAD

**Issue by braxtonhall** [pypi/support#4422]
### Project to be claimed

`ts-cli`: https://pypi.org/project/ts-cli

### Your PyPI username

`tetrascience`: https://pypi.org/user/tetrascience

### Reasons for the request

The name `ts-cli` is currently not in use. https://pypi.org/project/ts-cli redirects to a 404 page.

In the meantime, we are using https://pypi.org/project/tetrascience-cli/

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no existing source code available as `ts-cli` does not currently exist.

Source code for the replacement project can be found here: https://github.com/tetrascience/ts-cli

### Contact and additional research

As there is no existing owner, there was no one to contact :)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ppfeister** [comment]
If you got the error `The name 'ts-cli' is too similar to an existing project.` it was probably blocked by [__tscli__](https://pypi.org/project/tscli/)

Just linking to it in case it's useful. Hopefully these requests start being resolved soon

**Comment by braxtonhall** [comment]
We have decided never mind :)
