### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Dexerix** [pypi/support#4431]
### PyPI Username

Dexerix

### Reason for request

I misstyped the email I used to register myself and now I can't add a correct one to activate my account

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Dexerix,

Please contact support@pypi.org with the correct email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4431). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @Dexerix,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
