### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mpkocher** [pypi/support#4432]
### PyPI Username

`mkocher`

### Reason for request

Lost 2FA authentication app

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @mpkocher,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
