### ISSUE TITLE
Project Limit Request: tract - 100 GB

### ISSUE THREAD

**Issue by kali** [pypi/support#4442]
### Project URL

https://pypi.org/project/tract/

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

tract is an neural network inference engine. Somewhat like ONNXRuntime or  TensorflowLite. These are its python bindings. tract is a big beast to build (build works from source, but it takes a while on a big machine) so I feel like offering pre-built wheels is a must. 

### How large is each release?

Each wheel weights around 7MB, most of it is the actual tract dylib (22MB unzipped), the binding are pretty thin, and there are no extra data in the bundle.

### How frequently do you make a release?

About 10/year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by kali** [comment]
Hello, yeah, 30GB is a pretty good start actually. Thanks for considering it.

**Comment by cmaureir** [comment]
Got it. @kali 
I've set the project limit for `tract` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:
