### ISSUE TITLE
Project Limit Request: fbgemm-gpu - 30 GB

### ISSUE THREAD

**Issue by q10** [pypi/support#4446]
### Project URL

https://pypi.org/project/fbgemm-gpu/

### Does this project already exist?

- [X] Yes

### New limit

30 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

FBGEMM_GPU (FBGEMM GPU kernel library) is a collection of high-performance CUDA GPU operator library for GPU training and inference.

### How large is each release?

fbgemm-gpu performs a large amount of code generation prior to compilation, which is why the built packages can be very large.

5 Linux wheels (one for each of the currently supported Python versions)
~250 MB per wheel

This is roughly 1.3 - 1.5 GB per release. To provide backward compatibility guarantees for users, we intend to keep both RC and final releases for at least 2 years, but that is estimated to require more storage than the 10 GB that the project is currently alloted.

### How frequently do you make a release?

Roughly one point release every 3 months, but during each release cycle, there would be 2-3 RC releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @q10 :wave:
I've set the project limit for `fbgemm-gpu` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
