### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ben-mathu** [pypi/support#4449]
### PyPI Username

benatt

### Reason for request

Lost my 2FA authentication app and security codes

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ben-mathu,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by ben-mathu** [comment]
Thank you @Thespi-Brain.
