### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MuelNova** [pypi/support#4452]
### PyPI Username

Nova-Noir

### Reason for request

Lost access to email address

I was using mail `mail@novanoir.dev` as my primary email, which, the domain `novanoir.dev` was already expired, I'm now using another domain `ova.moe`

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @MuelNova,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4452). We will proceed from there. Thanks!

**Comment by MuelNova** [comment]
> Hi @MuelNova,
> 
> Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4452). We will proceed from there. Thanks!

I have sent the email.

Thanks for your support.

**Comment by Thespi-Brain** [comment]
Hi @MuelNova,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @MuelNova,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by MuelNova** [comment]
I have successfully logged and change the primary email, thank you!
