### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by asyrjasalo** [pypi/support#4457]
### PyPI Username

raas

### Reason for request

Lost access to the email address and unable to perform changes.

I don't have use for this PyPI account and will delete it as soon as it is recovered.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @asyrjasalo,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4457). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @asyrjasalo,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
