### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by petermat** [pypi/support#4461]
### PyPI Username

petermmm

### Reason for request

Hello, my account was blocked after I uploaded package for testing detection methods. Everything was transparent and well documented. No shady stuff. Please recover my account.

Kind regards, 
Peter Matkovski [p.matkovski@gmail.com] 

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @petermat,

Your account was found to not be in compliance with our [Acceptable Use Policy](https://policies.python.org/pypi.org/Acceptable-Use-Policy/). If you think this is an error, please contact admin@pypi.org. Thanks.
