### ISSUE TITLE
Project Limit Request: SciPy - 70 GiB

### ISSUE THREAD

**Issue by rgommers** [pypi/support#4468]
### Project URL

https://pypi.org/project/scipy/

### Does this project already exist?

- [X] Yes

### New limit

70

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

SciPy is one of the most widely used libraries for scientific computing with Python.

### How large is each release?

~1 GB per release total: 24-32 wheels (depending on whether the release supports 3 or 4 Python versions) with average size of 32 MB, one sdist of 60 MB).

We are actually actively working on decreasing wheel sizes, however that's going to be yielding a max 25% reduction I expect, and we also expect an increase in the number of wheels because of adding support for new platforms and for free-threaded CPython over time. So releases will likely stay around 1 GB in total size.

We are close to the current 50 GB limit. With 6-8 feature or bugfix release per year (I'm not counting pre-releases, because we tend to delete those), a 20 GB bump gives us room for another ~3 years.

### How frequently do you make a release?

Roughly once every 6-8 weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @rgommers :wave:
I've set the project limit for `scipy` to 70 GB on PyPI. 
Have a nice week :rocket:

**Comment by rgommers** [comment]
Thank you @cmaureir, much appreciated.

> Have a nice week 🚀

Same to you!
