### ISSUE TITLE
Project Limit Request: `marimo` - 20 GB (or delete old releases)

### ISSUE THREAD

**Issue by mscolnick** [pypi/support#4469]
### Project URL

https://test.pypi.org/project/marimo/

### Does this project already exist?

- [X] Yes

### New limit

20GB

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

Github repo: https://github.com/marimo-team/marimo

Another option would be to remove old releases. I dont see a way to automate this. 

### How large is each release?

11.6mb per release

### How frequently do you make a release?

twice a day

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @mscolnick :wave:
I've set the project limit for `marimo` to 20 GB on TestPyPI.
Have a nice week :rocket:
