### ISSUE TITLE
Project Limit Request: libtpu-nightly - 50 GB

### ISSUE THREAD

**Issue by learning-to-play** [pypi/support#4472]
### Project URL

https://pypi.org/project/libtpu-nightly

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project will release Google's TPU library. The project has been active for more than 3 years. See libtpu releases for JAX at https://storage.googleapis.com/jax-releases/libtpu_releases.html.

### How large is each release?

~ 350 MiB. The releases will be nightly. Storing packages released in 2 quarters will require 50 GB of storage.

### How frequently do you make a release?

Nightly.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @learning-to-play :wave:
Like the other issue you created, I increased the project limit of `libtpu-nightly` to 50GB on PyPI. Be mindful with the frequency of the releases with that size.
Have a nice week :rocket:
