### ISSUE TITLE
PEP 541 Request: wat

### ISSUE THREAD

**Issue by igrek51** [pypi/support#4475]
### Project to be claimed

`wat`: https://pypi.org/project/wat

### Your PyPI username

`igrek51`: https://pypi.org/user/igrek51

### Reasons for the request

`wat` name seems to be available since https://pypi.org/project/wat/ returns 404 Not Found,
but whenever I try to upload I keep getting:
`HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'igrek51' isn't allowed to upload to project 'wat'`

Moreover, I successfully uploaded my package to Test PyPI https://test.pypi.org/project/wat/ so I suppose this name doesn't violate any naming policy.
However, I still can't do the same to the real PyPI for some reason.
I'm kindly asking for a transfer or at least an explanation.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

My project: https://github.com/igrek51/wat

### Contact and additional research

Initially, the package was submitted to Test PyPI by someone else, so I contacted previous owner of `wat` package in Test PyPI. He deleted the project and after my successful submission, now I am the owner of a package `wat` in Test PyPI.
I thought that was the reason, but now I still can't upload to the real PyPI index for unknown reasons. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by igrek51** [comment]
I did a bit of research and I found out that this package might have been claimed before, but it doesn't have any releases or it has been deleted, according to https://libraries.io/pypi/wat

> This package has been removed from Pypi and cannot be used anymore.

> Total releases 0
> Latest release Mar 21, 2023
> First release Jan 21, 2015

Please, I'd like to claim this name.

**Comment by Thespi-Brain** [comment]
Hi @igrek51,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by merwok** [comment]
Yea I’ll give you the name!

**Comment by igrek51** [comment]
This is awesome! Thanks to all of you for your help. I have released the project at https://pypi.org/project/wat and I will remove the former, temporary `wat-inspector` name.
