### ISSUE TITLE
File Limit Request: gpustack - 300 MiB

### ISSUE THREAD

**Issue by gitlawr** [pypi/support#4478]
### Project URL

https://pypi.org/project/gpustack

### Does this project already exist?

- [X] Yes

### New Limit

300 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

GPUStack is an open-source GPU cluster manager for running large language models(LLMs). It has been active since July.

### Reasons for the request

We build with CUDA libraries so that users can use Nvidia GPUs. In the first release, we minimized the GPU compatibility to avoid exceeding the default file limit. However, we would like to extend the support matrix so that it works with more Nvidia GPU families out of the box. Therefore, we request an increase in the file size limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @gitlawr :wave:
I've set the upload limit for `gpustack` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
