### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cyschneck** [pypi/support#4480]
### PyPI Username

`cyschneck`

### Reason for request

Lost access to email address for `TestPyPI` account before I could verify the account, so I cannot change the email address or add a new one

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @cyschneck,

I wasn't able to find your test.pypi account with the username you provided. Do you have another username for your test.pypi account, since the one you provided was for the regular PyPI account. Thanks!

**Comment by cyschneck** [comment]
I misspelled my username, but was not able to correct it, test-pypi username `cyscshneck`

**Comment by Thespi-Brain** [comment]
Hi @cyschneck,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
