### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gregbell26** [pypi/support#4483]
### PyPI Username

TriHardStudios

### Reason for request

Hello!
I no longer have access to my gjbell@trihardstudios.com email address (I stopped paying for Microsoft a while ago and forgot to update my pypi account).

I verified one of my backup emails, but am unable to change the primary email address on my account.
If my primary email could be changed to trihard.studios@outlook.com that would be great.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @gregbell26,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4483). We will proceed from there. Thanks!

**Comment by gregbell26** [comment]
I emailed support from my desired email address!

**Comment by Thespi-Brain** [comment]
Hi @gregbell26,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @gregbell26,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
