### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by slarse** [pypi/support#4490]
### PyPI Username

slarse

### Reason for request

I have lost access to my primary email address, and so cannot verify it. My secondary email address `slarse@slar.se` is verified, and I would like to make that my primary instead.

As my primary address is not verified, I am unable to make any changes to my PyPi account.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by slarse** [comment]
If it's any help in identification, I've [added a signed commit](https://github.com/repobee/repobee/commit/467569be2cd7d61bc356f641429c4a2536b500eb) to one of my projects that's [hosted on PyPi](https://pypi.org/project/repobee/).

**Comment by Thespi-Brain** [comment]
Hi @slarse,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4490). We will proceed from there. Thanks!

**Comment by slarse** [comment]
@Thespi-Brain Done, sent an email referencing this issue from `slarse@slar.se`!

I wasn't expecting a response this quickly given the huge influx of account recovery requests, thanks a bunch for your work. I really appreciate it.

**Comment by Thespi-Brain** [comment]
Hi @slarse,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @slarse,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
