### ISSUE TITLE
File Limit Request: aspose-imaging-python-net - 150 MB

### ISSUE THREAD

**Issue by ESidenko** [pypi/support#4495]
### Project URL

https://pypi.org/project/aspose-imaging-python-net/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

**Aspose.Imaging for Python via .NET** is Another Python Imaging Library offering advanced image processing features. You could easily create, load, manipulate, convert, compress images or photos using this API. Also Aspose.Imaging library supports drawing and work with graphic primitives. Image export and conversion (including uniform multi-page image processing) is the one of API core features along with image transformations (resize, crop, flip&rotate, binarization, grayscale, adjust, etc.), advanced image manipulation features (filtering, dithering, masking, deskewing) and memory optimization strategies.
The first release: 23.5.0 - May 23 2023
Our team tried to minimize out package but for Linux it still have about 100Mb

### Reasons for the request

The package for Linux is about 100MB. The packages for other platforms are smaller.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @ESidenko :wave:
I've set the upload limit for `aspose-imaging-python-net` to 150 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
