### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by statick88** [pypi/support#4496]
### PyPI Username

statick

### Reason for request

Mi correo electrónico está mal:

Este no es:  dsaaveddra88@gmail.com 
Este si es: dsaavedra88@gmail.com

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @statick88,

I took a look at your account and it seems like you were able to change your email address yourself, which is great! Let us know if you have any other login issues. Closing this case!
