### ISSUE TITLE
Project Limit Request: vLLM - 30 GiB

### ISSUE THREAD

**Issue by simon-mo** [pypi/support#4499]
### Project URL

https://pypi.org/project/vllm/

### Does this project already exist?

- [X] Yes

### New limit

30GiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

See https://github.com/pypi/support/issues/3792 for our wheel size limit request. We have made significant progress in reducing the load on PyPI, but we do anticipate the biweekly release schedule will hit the total limit of 10GiB soon.

### How large is each release?

~200MiB for each release. We have 
* reduced the binary size from 200MiB to 124MiB. 
* changed the build process to be python version agnostic so we are only releasing one wheel. 

### How frequently do you make a release?

Every two weeks. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @simon-mo :wave:
I've set the project limit for `vllm` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
