### ISSUE TITLE
File Limit Request: premise - 200 MB

### ISSUE THREAD

**Issue by romainsacchi** [pypi/support#4501]
### Project URL

https://pypi.org/project/premise/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Active for over two years. It's a tool used in prospective environmental impact assessment, with hundreds of users.
I removed all unnecessary files from the project, except for a dozen CSV files which are needed.

### Reasons for the request

As we bundle more scenarios in the library (1 scenario = 1 CSV file of size 6-10 Mb), the size is expected to increase in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @romainsacchi :wave:
I've set the upload limit for `premise` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
