### ISSUE TITLE
File Limit Request: gpt4all - 300 MiB

### ISSUE THREAD

**Issue by cebtenzzre** [pypi/support#4502]
### Project URL

https://pypi.org/project/gpt4all/

### Does this project already exist?

- [X] Yes

### New Limit

300 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The [GPT4All Python binding](https://github.com/nomic-ai/gpt4all) is a convenient way to run local LLMs from Python, using either LLMs hosted by Nomic or any GGUF file compatible with [llama.cpp](https://github.com/ggerganov/llama.cpp). Our first PyPI release was in May of 2023.

### Reasons for the request

The Linux and Windows builds of the package include a CUDA build of llama.cpp, which contains kernels compiled for different GPU architectures. Since the last package version, llama.cpp [expanded](https://github.com/ggerganov/llama.cpp/pull/8075/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR427) this list, which increases the size of the build by nearly 33%. Also, I discovered an [issue](https://github.com/nomic-ai/gpt4all/pull/2421) that meant some of these architectures may have been skipped in previous releases, resulting in less optimal kernels being used at runtime. And the quantity and size of the kernels has grown over time.

The Linux wheel as built is currently 213 MiB. The smallest I have been able to get this release is 124 MiB, which required disabling pre-compilation of PTX code into binary kernels (CUBIN). This doesn't reduce functionality, but it has been shown to [not be backwards-compatible](https://github.com/nomic-ai/gpt4all/issues/2378) with older GPU drivers, and may have a runtime performance penalty because the GPU code has to be compiled from PTX on-the-fly.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cebtenzzre** [comment]
In order to avoid running into the project limit I think we're going to try shipping just PTX code in the next release, without CUBINs. If users report trouble we can change that later. But that still doesn't get us under the per-upload limit.

In that case, even a 200MiB limit would be sufficient for now if that's more amenable.

cc @cmaureir

**Comment by cmaureir** [comment]
Hello @cebtenzzre :wave:
I've set the upload limit for `gpt4all` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice week :rocket:
