### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by padthaitofuhot** [pypi/support#4503]
### PyPI Username

padthaitofuhot

### Reason for request

I can login to my PyPI account, but it is asking me to verify the Gmail account (same name as my GitHub account) I no longer have access to.  Despite having used that Gmail account for many years, Google disabled it when I tried to change the recovery email address and won't give me access to it.  Additionally, I also no longer have access to my secondary PyPI email address since I don't work there anymore.  I would like to use a different email address.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @padthaitofuhot,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4503). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @padthaitofuhot,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @padthaitofuhot,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
