### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by TheBuilderJR** [pypi/support#4510]
### PyPI Username

thebuilderjr

### Reason for request

When I signed up I had a typo in my email.  I used "thebuildejr93@gmail.com" when I meant to use "thebuilderjr93@gmail.com"

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @TheBuilderJR,

I have updated the primary email address on the account to the correct version. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. I will keep this issue open for another week unless I hear from you earlier. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to no new response from user.
