### ISSUE TITLE
Project Limit Request: viktor - 25 GB

### ISSUE THREAD

**Issue by khameeteman** [pypi/support#4513]
### Project URL

https://pypi.org/project/viktor/

### Does this project already exist?

- [X] Yes

### New limit

25

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

VIKTOR is a platform that makes it easy to create powerful and user-friendly web apps, all with pure Python. Create apps to automate your workflow, integrate with different software packages, and get better insights into your project through interactive visualizations.

The project has been active on PyPI for 2 years.

We do not expect the total size to increase in the future, since we will remove deprecated releases.

### How large is each release?

Total 250 MiB
- 5 linux wheels at 40 MiB
- 5 windows wheels at 10 MiB

These wheels contain cython compiled files.

We vendor the following packages:
- requests
- requests_toolbelt
- libcst
- tomli
- tomli-w
- trimesh
- filetype

### How frequently do you make a release?

Once or twice a month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @khameeteman :wave:
I've set the project limit for `viktor` to 25 GB on PyPI. 
Have a nice week :rocket:
