### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ARiftin** [pypi/support#4516]
### PyPI Username

`NokodSecurity`

### Reason for request

Lost access to email address before verification. Valid address is `amit@nokodsecurity.com`

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ARiftin,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4516). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ARiftin,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
