### ISSUE TITLE
Project Limit Request: pyspark - 40 GB

### ISSUE THREAD

**Issue by yaooqinn** [pypi/support#4529]
### Project URL

https://pypi.org/project/pyspark/

### Does this project already exist?

- [X] Yes

### New limit

40 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

PySpark is the Python API for Apache Spark, an open source, distributed computing framework and set of libraries for real-time, large-scale data processing. It has been active for 12 years ([first commit](https://github.com/apache/spark/commit/886b39de557b4d5f54f5ca11559fca9799534280))

We expect the total project size to increase by about 1 ~ 2 GB in 2024H2, including the potential scheduled releases 

- 3.5.2
- 3.4.4
- 4.0.0-previev2
- 4.0.0
- ...

### How large is each release?

~ 320 MiB

### How frequently do you make a release?

Roughly once every two months

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @yaooqinn :wave:
I've set the project limit for `pyspark` to 40 GB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:

**Comment by yaooqinn** [comment]
Thank you very much!
