### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jefurbee** [pypi/support#4544]
### PyPI Username

sas-institute

### Reason for request

Hi,
This is our corporate account and we set up 2FA. When I attempt to log in I get a prompt to enter a verification code; however, I don't have pypi set up in my authenticator app, so I don't receive the code. I do not have the recovery code.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jefurbee,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @jefurbee,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by jefurbee** [comment]
I have access again and I've reactivated 2FA and made sure to save off my recovery codes. Thank you. This issue can be closed.
