### ISSUE TITLE
Project Limit Request: Polars lts cpu - 100 GB

### ISSUE THREAD

**Issue by ritchie46** [pypi/support#4557]
### Project URL

https://pypi.org/manage/project/polars-lts-cpu/

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Polars is a DataFrame library/ query engine that enables fast data processing. The project has been active for 5 years.

See more: https://github.com/pola-rs/polars

### How large is each release?

Total ~150 MB: 5 wheels of ~30MB

```
[polars_lts_cpu-1.5.0-cp38-abi3-macosx_10_12_x86_64.whl](https://files.pythonhosted.org/packages/79/83/4e13fead3be478e2a9e35999eb6fae0227e21e2525630657622228cf03b1/polars_lts_cpu-1.5.0-cp38-abi3-macosx_10_12_x86_64.whl) (30.0 MB)
	Wheel 	cp38 	about 1 hour ago 	

[polars_lts_cpu-1.5.0-cp38-abi3-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/6f/8f/afdbd21d0c70da94ab3283d7735dd2d73b96ee363e10fa67eb8c02e76d68/polars_lts_cpu-1.5.0-cp38-abi3-macosx_11_0_arm64.whl) (26.6 MB)
	Wheel 	cp38 	about 1 hour ago 	

[polars_lts_cpu-1.5.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/2b/03/56325cc32676c063325a9085e13ff9b4aa195daf6c5551895d2434dec916/polars_lts_cpu-1.5.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) (31.3 MB)
	Wheel 	cp38 	about 1 hour ago 	

[polars_lts_cpu-1.5.0-cp38-abi3-manylinux_2_24_aarch64.whl](https://files.pythonhosted.org/packages/b1/b9/c71e95257557295bdb4357aa4146d0a27f08ae79e9196421fc1afe460128/polars_lts_cpu-1.5.0-cp38-abi3-manylinux_2_24_aarch64.whl) (28.9 MB)
	Wheel 	cp38 	about 1 hour ago 	

[polars_lts_cpu-1.5.0-cp38-abi3-win_amd64.whl](https://files.pythonhosted.org/packages/83/c8/e88fb9ab8e5c576c02013183d9e203495284a6a8ebd438278bbedb5b5ade/polars_lts_cpu-1.5.0-cp38-abi3-win_amd64.whl) (31.4 MB)
	Wheel 	cp38 	about 1 hour ago 	

[polars_lts_cpu-1.5.0.tar.gz](https://files.pythonhosted.org/packages/a4/3e/cd7b625e6c633d128c2c86d1ea4330e71b00fc8d86e04bffe6f6b486b8fb/polars_lts_cpu-1.5.0.tar.gz) (3.9 MB)
	Source 	None 	2 minutes ago
```

### How frequently do you make a release?

Once every 1/2 week(s).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Same comment from https://github.com/pypi/support/issues/4558

Hello @ritchie46 👋
A jump from the 10 GB to 100 GB seems very large in my opinion.
Would you be OK with an increase to 30G ? It's completely fine if in the future you reach the limit and can approach us for with another request.

**Comment by ritchie46** [comment]
Sure, that would unblock us. :+1:

**Comment by cmaureir** [comment]
Perfect, thanks @ritchie46 
I have set the new project limit to 30GB on PyPI.
Have a nice week :rocket:
