### ISSUE TITLE
Project Limit Request: Polars u64 idx - 100 GiB

### ISSUE THREAD

**Issue by ritchie46** [pypi/support#4558]
### Project URL

https://pypi.org/manage/project/polars-u64-idx

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Polars is a DataFrame library/ query engine that enables fast data processing. The project has been active for 5 years.

See more: https://github.com/pola-rs/polars

### How large is each release?

Total ~150 MB: 5 wheels of ~30MB

```
[polars_u64_idx-1.5.0-cp38-abi3-macosx_10_12_x86_64.whl](https://files.pythonhosted.org/packages/9a/a4/4dcbd082b26f05fac15406e2f8524fcdd064891b0d93945c86ef9eb908cb/polars_u64_idx-1.5.0-cp38-abi3-macosx_10_12_x86_64.whl) (30.3 MB)
	Wheel 	cp38 	about 1 hour ago 	

[polars_u64_idx-1.5.0-cp38-abi3-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/5f/10/66f895e3ac36ab10a28af185266719ef3a5cafcee7a96fd4f66b18563d00/polars_u64_idx-1.5.0-cp38-abi3-macosx_11_0_arm64.whl) (26.6 MB)
	Wheel 	cp38 	about 1 hour ago 	

[polars_u64_idx-1.5.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/c5/70/bd7c6d218812a17e1c8e50fe23c6b7f4c9c996f2e37f3363d802fbb2aff3/polars_u64_idx-1.5.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) (31.6 MB)
	Wheel 	cp38 	4 minutes ago 	

[polars_u64_idx-1.5.0-cp38-abi3-manylinux_2_24_aarch64.whl](https://files.pythonhosted.org/packages/50/30/76487e3550bd43d363d9fb9b2ca9ab8541ff308fc471a876aec6cb3af542/polars_u64_idx-1.5.0-cp38-abi3-manylinux_2_24_aarch64.whl) (28.9 MB)
	Wheel 	cp38 	4 minutes ago 	

[polars_u64_idx-1.5.0-cp38-abi3-win_amd64.whl](https://files.pythonhosted.org/packages/c2/eb/3ec72c0881bdd667d8503d520584b88356c3c11cbf7ae790540b9d00bc6b/polars_u64_idx-1.5.0-cp38-abi3-win_amd64.whl) (31.5 MB)
	Wheel 	cp38 	4 minutes ago 	

[polars_u64_idx-1.5.0.tar.gz](https://files.pythonhosted.org/packages/3b/fe/993123ddc7227a2aea786b4239eaa66a755650685c77279efa54004c06ee/polars_u64_idx-1.5.0.tar.gz) (3.9 MB)
```

### How frequently do you make a release?

Once every 1/2 week(s).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @ritchie46 :wave:
A jump from the 10 GB to 100 GB seems very large in my opinion.
Would you be OK with an increase to 30G ? It's completely fine if in the future you reach the limit and can approach us for with another request.

**Comment by ritchie46** [comment]
Sure, that would unblock us. :+1:

**Comment by cmaureir** [comment]
Perfect, thanks @ritchie46 
I have set the new project limit to 30GB on PyPI.
Have a nice week :rocket:
