### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by OfirCnvrg** [pypi/support#4573]
### PyPI Username

leah4kosh

### Reason for request

Hey,
I'm working at cnvrg, and we have a package we are managing at pypi:
https://pypi.org/project/cnvrgv2/

Currently there are two maintainers to this package:
cnvrg-runner
leah4kosh

As cnvrg-runner is only a maintainer, leah4kosh is probably the owner.
leah4kosh doesn't work in our organization anymore, and we try to make cnvrg-runner the owner of the package.
Our organization admin has access to both [cnvrg-runner@cnvrg.io](mailto:cnvrg-runner@cnvrg.io) and [leah@cnvrg.io](mailto:leah@cnvrg.io). The latter should be the mail of leah4kosh as we know it.

When trying to reset the password for leah4kosh we do not get any mail.
Not at [leah@cnvrg.io](mailto:leah@cnvrg.io) and not in [cnvrg-runner@cnvrg.io](mailto:cnvrg-runner@cnvrg.io).
It is not arriving to [support@cnvrg.io](mailto:support@cnvrg.io) as well, which is registered as the author of the package.

Please help us define cnvrg-runner as the owner of this package.
Our admin can get access to any @cnvrg.io email, in case that leah4kosh is registered with a different email than [leah@cnvrg.io](mailto:leah@cnvrg.io)

Thank you for your help,

Ofir Pe'er,
R&D manager at [cnvrg.io](http://cnvrg.io/)
Reachable at [ofir.peer@cnvrg.io](mailto:ofir.peer@cnvrg.io)

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @OfirCnvrg,

I checked the account logs and the email address [leah@cnvrg.io](mailto:leah@cnvrg.io) is bouncing, which is probably why you didn't receive the password reset email. I suggest that you send over an alternate email to support@pypi.org, and we will start the steps needed for the account recovery process from there. Once you have access to this account, you can change ownership. Thanks!

**Comment by OfirCnvrg** [comment]
This is weird since we are able to get mails from leah@cnvrg.io
Will contact support. Thanks

**Comment by Thespi-Brain** [comment]
Hi @OfirCnvrg,

Thanks for sending over an alternate email. I have initiated an account recovery process and instructions are being sent to that email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @OfirCnvrg,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
