### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by robberwick** [pypi/support#4574]
### PyPI Username

robberwick

### Reason for request

test pypi password reset emails not being delivered. i have tried using username and email address, and nothing is delivered. I have checked the spam folder.

HAve tried multiple times, and now have a 429 too many requests error.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by weinrank** [comment]
I have the same issue...
