### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by marian-vignau** [pypi/support#4575]
### PyPI Username

mavignau

### Reason for request

I tried to recover using the password reset procedure but it didn't send me anything. 
https://pypi.org/project/certmailer/
I'm using the same email registered in my package mavignau@gmail.com 
I have also checked my spam folder and tried the procedure many times

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by marian-vignau** [comment]
I have also checked my spam folder and tried the procedure many times

**Comment by Thespi-Brain** [comment]
Hi @marian-vignau,

The primary email address associated with your account is actually not your gmail address, it is your protonmail address, fyi. Are you trying to reset your password, or trying to reset 2FA and recovery codes as well? Just needed some more clarification before I can proceed to next steps, thanks!

**Comment by marian-vignau** [comment]
The account was recovered. Thanks!
