### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by he-yaowen** [pypi/support#4578]
### PyPI Username

garrett-he

### Reason for request

Lost access to primary email address. Now I can neither activate my account with my primary email address nor add a new one.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @garrett-he,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4578). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @garrett-he,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by garrett-he** [comment]
> Hi @garrett-he,
> 
> Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

Hi @Thespi-Brain 

Thanks a lot for helping me, my new email address has been verified, but it's not the primary one. Still I got the errors attached and not able to manage my projects. Please help, thanks!

![20240922014107](https://github.com/user-attachments/assets/75f5424d-db2a-49c5-b009-ec86b0caa5ea)

**Comment by Thespi-Brain** [comment]
Hi @garrett-he,

You need to complete the verification instructions first before your email address gets updated. The instructions were sent to your preferred email address. Once you complete the verification process, your primary email address will be updated and your account will be reset.

**Comment by garrett-he** [comment]
> Hi @garrett-he,
> 
> You need to complete the verification instructions first before your email address gets updated. The instructions were sent to your preferred email address. Once you complete the verification process, your primary email address will be updated and your account will be reset.

Hi @Thespi-Brain 

Thank you for help. I missed up the email and the verification link is expired, would you please resend me a new one, thanks!

**Comment by Thespi-Brain** [comment]
Hi @garrett-he,

There is no verification "link", rather, it's an email with instructions for you on how to verify! The instructions are not timed, so they don't expire. Please check your preferred email address to look for the instructions and we will go from there, thanks!

**Comment by garrett-he** [comment]
> Hi @garrett-he,
> 
> There is no verification "link", rather, it's an email with instructions for you on how to verify! The instructions are not timed, so they don't expire. Please check your preferred email address to look for the instructions and we will go from there, thanks!

Hi @Thespi-Brain 

I double-checked my email inbox and junk box, no new email with instructions. Which email address did you send to? 

BTW, allow me to clarify my request:

Currently my primary email address on PyPI account is garrett.he@hotmail.com (which not accessible, and can't be activated), I would like the email address to be changed to garrett.he@outlook.com (my preferred primary email address). 

Now the problem is, garrett.he@outlook.com is activated but it's secondary, garrett.he@hotmail.com is primary but can't be activated (because it's not accessible). My account status is locked and I can't do more operations on my projects.

Would you please help? Thanks!

**Comment by Thespi-Brain** [comment]
Hi @he-yaowen,

I had sent the instructions to your new, preferred email address at xxx@outlook.com. The instructions are still valid as they don't expire. Please check your outlook email again and let me know, thanks.

**Comment by Thespi-Brain** [comment]
Hi @he-yaowen,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
