### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pstarkov** [pypi/support#4582]
### PyPI Username

`EChirkova`

### Reason for request

Hello, trying to verify email for the username EChirkova (chirkova@knoema.com), but we can't get any email verification in our inbox (or in spam). We checked that from other email providers we can get emails (google, outlook).

Please help in advance. 

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @pstarkov,

I wanted to confirm that this is for your test.pypi account, correct? I wasn't able to find any account with the username you provided for our regular PyPI account. Looking at the test.pypi account, it seems like you were able to verify the email address in question, which is great. Are you still having issues with login and verification? Let me know, thanks!

**Comment by pstarkov** [comment]
Thanks, we have confirmed account!
