### ISSUE TITLE
帐户恢复请求

### ISSUE THREAD

**Issue by hk4170** [pypi/support#4583]
### PyPI Username

hk4170

### Reason for request

Lost 2FA authentication app or security token

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @hk4170,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
