### ISSUE TITLE
File Limit Request: nexaai - 200 MiB

### ISSUE THREAD

**Issue by AgainstEntropy** [pypi/support#4589]
### Project URL

https://pypi.org/project/nexaai/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

We are developing an SDK for on-device inference of generative models.
The nexa SDK will bundle some open-sourced projects, such as llama.cpp and stable-diffusion.cpp. We aim to facilite users from all platform to get hands on nexa SDK smoothly, so shared library files will be bundled into the wheels, thus exceeding the size limit.
We have made some effort to reduce package size, such as removing unused example data and bundling libraries.

### Reasons for the request

We would like to add more dependencies to nexa SDK, such as whisper.cpp, bark.cpp, etc.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Closing this because it was handled in https://github.com/pypi/support/issues/4590 remember to always check if there is another issue @AgainstEntropy
Have a nice week :snake:
