### ISSUE TITLE
Project Limit Request: deltachat - 15 GB

### ISSUE THREAD

**Issue by missytake** [pypi/support#4591]
### Project URL

https://pypi.org/project/deltachat/

### Does this project already exist?

- [X] Yes

### New limit

15

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This package provides CFFI bindings to the [Delta Chat Rust Core](https://github.com/deltachat/deltachat-core-rust/), several other PyPI packages depend on it, mostly chat bots.

It has been active since 2018, although it will be deprecated soon(tm) in favor of https://pypi.org/project/deltachat-rpc-client/, a new library that provides RPC bindings instead of CFFI bindings to the Delta Chat Rust Core.

### How large is each release?

Every release is about 350 MB, containing about 30 wheels which are 10-11MB each, due to the bundled rust binaries. It can't be reduced further easily; we already try to keep the Rust core as small as possible already, because it is shipped with the Delta Chat apps as well, which many people download over metered mobile data connections.

### How frequently do you make a release?

The Rust core gets released [every few days](https://github.com/deltachat/deltachat-core-rust/releases/), but nowadays this doesn't lead to us uploading a new PyPI package every time, as most new chat bots use the new library already; only when an old chat bot needs an update we push a new release to this project. This should not happen too often, our last PyPI release was in March, so almost half a year ago. We now hit the limit in such a situation, where a depending library needs a new update.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @missytake :wave:
I've set the project limit for `deltachat` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:
