### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sonichi** [pypi/support#4599]
### PyPI Username

`automl`

### Reason for request

Lost access to email address

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @sonichi,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4599). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Closing issue due to security issue: user no longer associated with the PyPI account or original project, alerted by original user.
