### ISSUE TITLE
File Limit Request: cufinufft - 200 MB

### ISSUE THREAD

**Issue by janden** [pypi/support#4603]
### Project URL

https://pypi.org/project/cufinufft/

### Does this project already exist?

- [X] Yes

### New Limit

200 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This is a Python package that wraps the [cufinufft](https://finufft.readthedocs.io/en/latest/c_gpu.html) library, a GPU implementation of a non-uniform fast Fourier transform (NUFFT) developed at the Flatiron Institute. Since this is a GPU library, it depends on various lower-level CUDA libraries, which we link into our binary to increase compatibility for our users. (We also plan to offer a source distribution with our next release, but this relies on users having a working CUDA compilation toolchain, which is not always the case.) As a result, the resulting wheels are somewhat large.

Our current approach to mitigating this is to limit the number of compute architectures that are used for the code. Previously, we were able to include sm_50, sm_60, sm_70 and sm_80, but with the latest release, this is over the limit, so we are forced to reduce the number of architectures further.

### Reasons for the request

With a small increase in our file size limit, we would be able to support a wider range of compute architectures (say, sm_50, sm_60, sm_70, sm_80, and sm_90), allowing users to experience higher performance out of the box when using our package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @janden :wave:
I've set the upload limit for `cufinufft` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:

**Comment by janden** [comment]
Thank you! Have a nice week!
