### ISSUE TITLE
File Limit Request: livekit-plugins-browser - 200 MB

### ISSUE THREAD

**Issue by theomonnom** [pypi/support#4614]
### Project URL

https://pypi.org/project/livekit-plugins-browser/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

We're developing a method to stream Chromium's video and audio output in real-time for AI applications. (For example, providing a browser as a tool for an LLM, or enabling access to an interactive remote browser.)

The current required size would be around 165MB. But it would be safer for us to set the limit to 200MB.

This project is open-source: https://github.com/livekit/agents

Capturing the rendered frames is straightforward:
```python
    ctx = browser.BrowserContext(dev_mode=True)
    await ctx.initialize()

    page = await ctx.new_page(url="https://pypi.org/")

    @page.on("paint")
    def on_paint(paint_data):
        # use paint_data.frame for RGBA data
        pass
```

### Reasons for the request

The reason is that the[ Chromium Embedded Framework ](https://github.com/chromiumembedded/cef)is quite big by default. (it is embedding Chromium).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @theomonnom :wave:
I've set the upload limit for `livekit-plugins-browser` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size and also try to evaluate a way to avoid including chromium binaries (which are heavy indeed)
Have a nice week :rocket:
