### ISSUE TITLE
Project Limit Request: siliconcompiler - 20 GB

### ISSUE THREAD

**Issue by gadfort** [pypi/support#4616]
### Project URL

https://pypi.org/project/siliconcompiler/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

siliconcompiler is a modular hardware build system for hardware. The project has been active for the last 3.5 years.
We expect the size of the project to decrease in the future as we migrate away from the bundled binary we current package and need.

### How large is each release?

~130 MB total across 25 wheels. Mainly due to the inclusion of a required binary file. The plan is to publish that binary separately going forward so this becomes a pure python release, but we have not gotten there yet.

```
siliconcompiler-0.26.3-cp312-cp312-win_amd64.whl (2.5 MB view hashes)
siliconcompiler-0.26.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp312-cp312-macosx_11_0_arm64.whl (7.6 MB view hashes)
siliconcompiler-0.26.3-cp312-cp312-macosx_10_15_x86_64.whl (7.3 MB view hashes)
siliconcompiler-0.26.3-cp311-cp311-win_amd64.whl (2.5 MB view hashes)
siliconcompiler-0.26.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp311-cp311-macosx_11_0_arm64.whl (7.6 MB view hashes)
siliconcompiler-0.26.3-cp311-cp311-macosx_10_15_x86_64.whl (7.3 MB view hashes)
siliconcompiler-0.26.3-cp310-cp310-win_amd64.whl (2.5 MB view hashes)
siliconcompiler-0.26.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp310-cp310-macosx_11_0_arm64.whl (7.5 MB view hashes)
siliconcompiler-0.26.3-cp310-cp310-macosx_10_15_x86_64.whl (7.3 MB view hashes)
siliconcompiler-0.26.3-cp39-cp39-win_amd64.whl (2.5 MB view hashes)
siliconcompiler-0.26.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp39-cp39-macosx_11_0_arm64.whl (7.5 MB view hashes)
siliconcompiler-0.26.3-cp39-cp39-macosx_10_15_x86_64.whl (7.3 MB view hashes)
siliconcompiler-0.26.3-cp38-cp38-win_amd64.whl (2.5 MB view hashes)
siliconcompiler-0.26.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.8 MB view hashes)
siliconcompiler-0.26.3-cp38-cp38-macosx_11_0_arm64.whl (7.5 MB view hashes)
siliconcompiler-0.26.3-cp38-cp38-macosx_10_15_x86_64.whl (7.3 MB view hashes)
```

### How frequently do you make a release?

~2 per month (sometimes a little more frequent)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @gadfort :wave:
I've set the project limit for `siliconcompiler` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size and maybe explore [Python's Limited API](https://docs.python.org/3/c-api/stable.html) to avoid having 1-wheel-per-python-version and by using the `abi3` tag you will be reducing that to one-wheel per architecture and OS.
Have a nice week :rocket:

**Comment by gadfort** [comment]
@cmaureir thank you
