### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Chen-Po** [pypi/support#4618]
### PyPI Username

Chen-po

### Reason for request

Lost 2FA authentication app or security token

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Chen-Po,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
