### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ASEIDEL77** [pypi/support#4636]
### PyPI Username

cecliteam_ibm

### Reason for request

Lost access to email address.

I am one of the technical owners in IBM of the following pypi project:
Package: https://pypi.org/project/ibm-code-engine-sdk/
Github source: https://github.com/IBM/code-engine-python-sdk

This project currently has 4 validated maintainers listed. 3 of them are personal userIDs of former IBM colleagues that have left the company. The 4th validated maintainer is a functional userID (**cecliteam**), whose E-Mail address is no longer valid. Due to constraints put into place recently at our company, we had to create a new E-Mail address (`CE.CLI.Team@ibm.com`) for this functional user. Since we also don't have access to any 2FA recovery codes of the old E-Mail address, we are asking to replace the existing functional user with the new user, so we can regain access to our pypi project. 

The new username is **cecliteam_ibm**. You can easily verify that the old user's E-Mail (**CE.CLI.Team@de.ibm.com**) is no longer active, by sending an E-Mail to it. Within a few hours you'll receive a Postmaster reply stating that the E-Mail could not be delivered.

Over a year ago, my fellow colleague Enrico Regge had opened another request for transferring project ownership, by adding his user as a maintainer. Unfortunately, this request has not been processed yet. https://github.com/pypi/support/issues/2923 

We really want to avoid creating a duplicate project on pypi. Therefore, regaining access to the project is our preferred option!

Thank you!

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ASEIDEL77,

Thanks for providing all the background info regarding the different accounts. The best way to go forward is to actually reset the **cecliteam** account. That way, you and your team can have access to it and transfer/change owners of the projects as you wish. This will actually be a faster process (in this case) plus we don't "replace" old accounts with new accounts. They both will still continue to exist unless the original owners decides to delete their own accounts as we like to give agency to users over their own accounts.

The first step to resetting the **cecliteam** account would be for you to please send a new email address that you would like associated with this account to [support@pypi.org](url) and please reference this issue link (https://github.com/pypi/support/issues/4636). We will proceed from there. Thanks!

**Comment by ASEIDEL77** [comment]
I sent a response to support@pypi.org as requested.

**Comment by Thespi-Brain** [comment]
Hi @ASEIDEL77,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by ASEIDEL77** [comment]
Hi @Thespi-Brain, I received the E-Mail and performed the steps as instructed.

**Comment by Thespi-Brain** [comment]
Hi @ASEIDEL77,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
