### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by PauloSanto** [pypi/support#4639]
### PyPI Username

Paulo Santo

### Reason for request

I made a typing mistake.
I typed gamil and should have typed gmail.
That's why I'm not receiving the confirmation email

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @PauloSanto,

This was for your Test.PyPI account, correct? I went ahead and corrected the email address. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks!
