### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by TriaDeveloper** [pypi/support#4646]
### PyPI Username

TriaDeveloper

### Reason for request

Não estou conseguindo acessar o pypi utilizando o token cadastrado

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Duplicate of #(https://github.com/pypi/support/issues/4610)
