### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dtmhdev89** [pypi/support#4654]
### PyPI Username

hieuDev.89

### Reason for request

I can't log into my account although the correct authentication code inputted from google authenticator. It keeps show invalid code.
I tried to reset my password as well, but it has have same error.
I also tried on different browser like Chrome, Firefox, Safari. But it didn't work as well.

![error_pypi](https://github.com/user-attachments/assets/334c068b-23b3-488d-8d9e-24c7eb6d4871)

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @dtmhdev89,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. 

I would also suggest that once your account recovery process is complete and your 2FA and recovery codes are reset, that you try with a different auth app other than Google Authenticator. Often, that solves the problem as well. I would also check your device to see if the the time is exact using [this](https://time.is/) website. Thanks!

**Comment by dtmhdev89** [comment]
@Thespi-Brain 
This is my time from the website:
![image](https://github.com/user-attachments/assets/b94def9a-9906-449b-9443-7bbd811dc26c)

**Comment by Thespi-Brain** [comment]
Hi @dtmhdev89,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
