### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by maopengg** [pypi/support#4659]
### PyPI Username

'maopeng'

### Reason for request

- I've lost both the two-factor authentication and the recovery code, thus I can't log in to this account. Please help me cancel this account so that I can create a new one. Thank you!

- My email address is：729164035@qq.com

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Duplicate of #4628
