### ISSUE TITLE
Project Limit Request: tencentcloud-sdk-python - 20 GB

### ISSUE THREAD

**Issue by sesky4** [pypi/support#4663]
### Project URL

https://pypi.org/project/tencentcloud-sdk-python

### Does this project already exist?

- [x] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Tencent Cloud Python SDK is the official software development kit, which allows Python developers to write software that makes use of Tencent Cloud services.

### How large is each release?

~20 MiB each release

10 MiB for source
10 MiB for whl

### How frequently do you make a release?

everyday

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @sesky4 :wave:
I've set the project limit for `tencentcloud-sdk-python` to 20 GB on PyPI.
Have a nice week :snake:

**Comment by sesky4** [comment]
@cmaureir thanks :)
Have a nice week.
