### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by surajpowar** [pypi/support#4674]
### PyPI Username

suraj_powar_1980

### Reason for request

I have by mistake given an incorrect email. I need to rectify the email such that I can verify my email credentials. Any help is appreciated.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @surajpowar,

I found the typo-ed email associated with your Test.PyPI account and I went ahead and updated it. Your 2FA has also been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
