### ISSUE TITLE
Project Limit Request: llama-cpp-cffi - 50 GB

### ISSUE THREAD

**Issue by mtasic85** [pypi/support#4679]
### Project URL

https://pypi.org/project/llama-cpp-cffi/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Python binding for llama.cpp using cffi. Supports CPU, CUDA 12.6 and Vulkan execution.

Project is active for two months.

### How large is each release?

CPU/Vulkan version is 10-20 MiB.
CUDA version is ~150 MiB.

We already applied UPX and ZIP re-compression with higher rate, so we can fit wheels under 200 MiB file limit.

### How frequently do you make a release?

1-2 times a week in average.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @mtasic85 :wave:
I've set the project limit for `llama-cpp-cffi` to 50 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:
