### ISSUE TITLE
PEP 541 Request: pay

### ISSUE THREAD

**Issue by vovchic17** [pypi/support#4682]
### Project to be claimed

`pay`: https://pypi.org/project/pay

### Your PyPI username

`VoVcHiC`: https://pypi.org/user/VoVcHiC

### Reasons for the request

The `pay` project on PyPI seems to be abandoned. It has only 1 release from 2019, no description and the source repository has only 3 commits and consists of only `setup.py` file.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/pipname/pay
https://github.com/vovchic17/aiocpa

### Contact and additional research

I have contacted the owner of the PyPI project, but have received no reply.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
This request is declined due to user abuse.

**Comment by vovchic17** [comment]
Excuse me, what abuse are you talking about? I didn't abuse anything.
