### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by XieJunWei666** [pypi/support#4684]
### PyPI Username

xiejunwei

### Reason for request

丢失 2FA 身份验证应用程序或安全令牌

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @XieJunWei666,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by XieJunWei666** [comment]
confirming intent to reset 2FA.

**Comment by XieJunWei666** [comment]
confirming intent to reset 2FA. 



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pypi/support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 凌晨5:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pypi/support] Account recovery request (Issue #4684)





 
Hi @XieJunWei666,
 
I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @XieJunWei666,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
