### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MS-AutoML-Team** [pypi/support#4694]
### PyPI Username

`automl`

### Reason for request

We are requesting the update of the email address associated with the account from a former employee work account (that has now been disabled since the employee departed) to a more neutral team email address

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @MS-AutoML-Team,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @MS-AutoML-Team,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
