### ISSUE TITLE
Project Limit Request: XGBoost - 20 GiB

### ISSUE THREAD

**Issue by hcho3** [pypi/support#4695]
### Project URL

https://pypi.org/project/xgboost

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

XGBoost is a popular machine learning library active since 2015.

### How large is each release?

~ 280 MiB total (Windows wheel 130 MiB, Linux wheel 150 MiB). Starting from 2.1.0, XGBoost no longer embeds a copy of NCCL and uses `nvidia-nccl-cu12` instead. As a result, the size of Linux wheel was halved (300 MiB -> 150 MiB).

### How frequently do you make a release?

Roughly once in every 3 months

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by hcho3** [comment]
Any updates on this issue?

**Comment by cmaureir** [comment]
Hello @hcho3 :wave:
I've set the project limit for `XGBoost` to 20 GB on PyPI. 
Have a nice weekend :rocket:
