### ISSUE TITLE
Account recovery request for DemoGPT

### ISSUE THREAD

**Issue by melih-unsal** [pypi/support#4699]
### PyPI Username

`melih-unsal`

### Reason for request

I have 2 email addresses which are `melih@demogpt.io` and `melihunsal.ai@gmail.com`
`melih@demogpt.io` was the primary email address but it was suspended before.
Even if I verified my second email address `melihunsal.ai@gmail.com` i cannot make it the primary one 
I don't have an access to my primary email but I have access to the second and I have already verified it as you can see below
How can I recover my account? 
![image](https://github.com/user-attachments/assets/6b2a98a3-0e63-4cfb-bbc0-6b5261989ef6)

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by melih-unsal** [comment]
I have a good repo called [DemoGPT](https://github.com/melih-unsal/DemoGPT) having 1.7k stars and I cannot update my library because of this issue.

My primary email melih@demogpt.io has expired and I cannot activate it. I have already had another email saved in PyPi called melihunsal.ai@gmail.com and I've verified it. I haven't generated any recovery code before.

Please urgently resolve this issue.

**Comment by Thespi-Brain** [comment]
Hi @melih-unsal,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4699). We will proceed from there. Thanks!

**Comment by melih-unsal** [comment]
Thank you @Thespi-Brain .
I've just sent an email to [support@pypi.org](mailto:support@pypi.org)
I hope I can recover my account soon.

**Comment by Thespi-Brain** [comment]
Hi @melih-unsal,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by melih-unsal** [comment]
Hi @Thespi-Brain 
Thank you for the quick response!
I've applied the step that is included in the email yesterday and waiting for the next action.
Thank you!

**Comment by Thespi-Brain** [comment]
Hi @melih-unsal,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
