### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by matteolucchi** [pypi/support#4703]
### PyPI Username

matteol

### Reason for request

Lost access to primary email address

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by jr-b-reiterer** [comment]
Dear PyPI team,

in case it's helpful with any doubts that may be there: @matteolucchi is a former member of our organization, and his now inactive primary email address was from our company. We cannot reactivate it. Feel free to reach out to current members of our organization if you need further confirmation that this claim is legit. 

We are grateful for the effort to restore access to projects that have been maintained by @matteolucchi aka matteol on PyPI.

TIA

**Comment by Thespi-Brain** [comment]
Hi @matteolucchi,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4703). We will proceed from there. Thanks!

**Comment by matteolucchi** [comment]
Thank you, I just sent the email

**Comment by Thespi-Brain** [comment]
Hi @matteolucchi, 

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @matteolucchi,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
