### ISSUE TITLE
Account recovery request - Primary email does not properly receive emails

### ISSUE THREAD

**Issue by ECGomes** [pypi/support#4707]
### PyPI Username

`ECGomes`

### Reason for request

Primary email does not seem to support emails (internal institution changes)

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ECGomes,

Please contact support@pypi.org with an alternate email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4707). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ECGomes,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
