### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jenca-adam** [pypi/support#4728]
### PyPI Username

`jenca.adam`

### Reason for request

Lost 2FA authentication app or security token

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jenca-adam,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by jenca-adam** [comment]
When i reply to the email i get this:
![Screenshot_20240911_154734](https://github.com/user-attachments/assets/33bab41e-693c-4a4c-8da4-d17b0b1693c3)
is this intended or have i done something wrong?

**Comment by Thespi-Brain** [comment]
Hi @jenca-adam,

I did receive your reply to the email, although it was empty. I am not sure why you received a failed mail delivery msg. Can you please reply again to the email that was sent to you with your intent to reset your account's 2FA? We will go from there, thanks.

**Comment by Thespi-Brain** [comment]
Hi @jenca-adam,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
