### ISSUE TITLE
File Limit Request: TDAtaframe - 200 MB

### ISSUE THREAD

**Issue by jackruder** [pypi/support#4737]
### Project URL

https://pypi.org/project/TDAtaframe/

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is a library extension to polars which aims to provide computational tools for topological data analysis within polars dataframes. The backend of the project is written in rust, and includes many linked libraries. Notably, faer-rs, polars, and libtorch (via tch-rs) are the main contributors to size, especially since on manylinux cuda support is enabled, so the compiled size is large to maintain compatability.

TDAtaframe is a new project (from the CompTaG group at Montana State University), and will mostly be used by researchers in computational topology.

### Reasons for the request

The Manylinux wheel I would like to upload is ~120MB. I expect it to increase in the future, however not by a lot. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @jackruder :wave:
I've set the upload limit for `TDAtaframe` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :rocket:
