### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gregmuellegger** [pypi/support#4740]
### PyPI Username

gremu

### Reason for request

Hi there,

I haven't used my account in a while and have lost access to my 2FA TOTP config.

I'm currently in the process of transfering https://github.com/jazzband/django-superform/ over to Jazzband and therefore want to add jazzband as a contributor to the project.

I hope you can help me!
Thanks so much!

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @gregmuellegger,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
