### ISSUE TITLE
Project Limit Request: TileDB - 30 GB

### ISSUE THREAD

**Issue by dudoslav** [pypi/support#4744]
### Project URL

https://pypi.org/project/tiledb/

### Does this project already exist?

- [X] Yes

### New limit

30GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

TileDB is an embeddable database for storing and accessing dense and sparse multi-dimensional arrays. The core is a C++ library that works on Linux, macOS, and Windows, with a Python binding layer (https://github.com/TileDB-Inc/TileDB-Py). It is open-sourced under the permissive MIT License, and maintained by [TileDB, Inc](https://tiledb.com/).

The project has been active since 2017. We do not expect release sizes to increase in the future.

### How large is each release?

Around 200MiB since we release for a wide range of platforms + source distribution as can be seen here: https://pypi.org/project/tiledb/0.31.1/#files . Looking at the release history the package size does not really increase. We do our best to keep the wheel size as small as possible, for example, we strip binaries.

### How frequently do you make a release?

About every two weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @dudoslav :wave:
I've set the proejct limit for `TileDB` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :rocket:
