### ISSUE TITLE
File Limit Request: roaring-landmask - 250 MB

### ISSUE THREAD

**Issue by gauteh** [pypi/support#4748]
### Project URL

https://pypi.org/project/roaring-landmask/

### Does this project already exist?

- [X] Yes

### New Limit

250 mb

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project provides an efficient landmask for checking whether a point is in the ocean or on land. It is used by several other projects. It has been active for about 3 years. We are compressing all data and trying to keep the size as low as possible, but the included files are very slow to generate and would be difficult to generate on the fly. We include processed map data from GSHHG and OpenStreetMap (with license information). 

### Reasons for the request

We have recently added the OpenStreetMap as well to this package. This increased the size to just over 100 mb, we therefore request 250 mb to have some margin.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @gauteh  :wave:
I've set the upload limit for `roaring-landmask` to 250 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :rocket:
