### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by amw007** [pypi/support#4755]
### PyPI Username

amw007

### Reason for request

Lost Mobile where I've 2FA authentication app 

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @amw007,

Your 2FA on your test.pypi account has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
