### ISSUE TITLE
File Limit Request: gi-loadouts - 500 MB

### ISSUE THREAD

**Issue by gridhead** [pypi/support#4765]
### Project URL

https://pypi.org/project/gi-loadouts/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

## Project info

This is a desktop application that allows travelers to manage their custom equipment of artifacts and weapons for playable characters and makes it convenient for travelers to calculate the associated statistics based on their equipment using the semantic understanding of how the gameplay works. Travelers can create their bespoke loadouts consisting of characters, artifacts and weapons and share them with their fellow travelers. Supported file formats include a human-readable <b>Yet Another Markup Language (YAML)</b> serialization format and a JSON-based <b>Genshin Open Object Definition (GOOD)</b> serialization format.

## Efforts made

1. The project assets have been compressed to their highest order of the compression level.
2. Repeated project static assets have been removed with the introduction of modularity.
3. We do not bundle any other packages in the project as we get them externally on installation.
4. Example data includes assets like images, fonts and training data required for functionality.

## Home page

https://github.com/gridhead/gi-loadouts/

### Reasons for the request

The initial release i.e. 0.1.0a1 was 90.2-93.6MB in size while the newer ones have gone up to 104-108MB. With the release of new versions, we expect the sizes to increase but we know that it will stay well under 500MB of size. Please note that we are doing our best to ensure that we consume a minimal amount of storage. Thank you in advance for your consideration. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @gridhead :wave:
I've set the upload limit for `gi-loadouts` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a great week :snake:

**Comment by gridhead** [comment]
Thank you, @cmaureir!
