### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by timmc-edx** [pypi/support#4768]
### PyPI Username

`edX`

### Reason for request

We've lost track of our Test PyPI account's email and password -- we still have a valid upload token, but recently discovered that we don't even know what email addresses the `edX` user account is registered under, let alone the password. (Our regular PyPI account is fine, it's just the https://test.pypi.org account we're trying to get back into.)

I think if we could just find out what email address the account is registered under we could do the rest. Could you send that info to security@edx.org? Thank you, and apologies for the trouble!

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
If you'd like we can set the primary email address for the test.pypi.org edx user to the address used for the pypi.org edx user, then you'll just need to proceed with a password reset and email verification.

**Comment by timmc-edx** [comment]
That should work as well, thank you!

**Comment by ewdurbin** [comment]
Address has been updated.
