### ISSUE TITLE
Project Limit Request: tmlt.core - 20 GiB

### ISSUE THREAD

**Issue by tmager** [pypi/support#4776]
### Project URL

https://pypi.org/project/tmlt.core/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Tumult Core is a programming framework for implementing differentially-private algorithms, and has been making public releases for a bit over two years.

### How large is each release?

Recent releases are ~300 MiB total:
* 5 manylinux wheels, one per supported Python version (~40 MiB each)
* 10 macOS wheels, one each for ARM and x86 per supported Python version (~9 MiB each)

The majority of the wheel size is due to bundling a compiled version of [FLINT](https://flintlib.org/) and its dependencies.

We have considered spinning off our FLINT bindings into a separate package that would release much less frequently, but we do not currently have the bandwidth to make this change.  We've got roughly 4 releases left before hitting the project limit; an increase would buy us some time to look at this further.

### How frequently do you make a release?

We've averaged ~2 releases per month this year, but this varies considerably.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @tmager :wave:
I've set the upload limit for `tmlt.core` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :rocket:
