### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ygorpontelo** [pypi/support#4777]
### PyPI Username

ygorpontelo

### Reason for request

Hey, i updated my phone and the prior 2FA app doesn't work anymore, i forgot to generate the recovery codes, so i can't access my account. Sorry for the inconvenience. 

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ygorpontelo,

Not a problem! I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ygorpontelo,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
