### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by YongcaiHuang** [pypi/support#4781]
### PyPI Username

HUANG.Eric_Python-1030211

### Reason for request

My account has been deleted by other people accidentally. Could you help recover my account (HUANG.Eric_Python-1030211)? Thank you so much for your help!!

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @YongcaiHuang,

If the account with the username you provided has been deleted, we can't retrieve the original account. But, you can always create a new account. Let me know if this helps answer your question. I will keep this issue open for a week unless I hear from you earlier, thanks.

**Comment by YongcaiHuang** [comment]
I have tried to create a new account with the same email address as the one being deleted before, but I am not allowed to create an account with this email. I am not sure what's going on.

<img width="381" alt="image" src="https://github.com/user-attachments/assets/d2c476ef-8fce-406a-a230-4d609f09931b">

**Comment by Thespi-Brain** [comment]
Hi @YongcaiHuang,

We unfortunately don't allow account creations with emails that have either an Outlook domain or a Hotmail domain to safeguard against bot account registrations and other possible security threats. I suggest you create an account using an alternate email address that you might have.

**Comment by YongcaiHuang** [comment]
thanks for the explaination and I'll try with another email address.
