### ISSUE TITLE
Project Limit Request: oasislmf - 20 GB

### ISSUE THREAD

**Issue by sambles** [pypi/support#4790]
### Project URL

https://pypi.org/project/oasislmf/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Hi we're an open source  catastrophe modelling project on GitHub (https://github.com/OasisLMF), this project is our main python package 

### How large is each release?

1 Linux wheel about 130MB~  and the source package 305.5 kB~

### How frequently do you make a release?

Once per month  

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @sambles :wave:
I've set the project limit for `oasislmf` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend :rocket:
