### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Lifailon** [pypi/support#4794]
### PyPI Username

Lifailon

### Reason for request

My problem: **Accidentally registered with an email address you cannot verify**

When creating an account, I specified an incorrect mailbox address (error in the domain name `gamil` instead of `gmail`), so I can not confirm it, to change the address in the settings is impossible, and the account name is already taken to create a new one (and would not want to do it), how to solve this problem?

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Lifailon,

Can you please confirm the correct email address and send an email to support@pypi.org? We will go from there and update it to the correct one, thanks!

**Comment by Thespi-Brain** [comment]
Hi @Lifailon,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by Lifailon** [comment]
> Hi @Lifailon,
> 
> I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

Thank you, everything worked out!
