### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MadSchemas** [pypi/support#4800]
### PyPI Username

olegator77

### Reason for request

I've lost access to the email address linked to the account. This email was linked to the account a long time ago and for the most of this time it was possible to publish projects (the single project actually) without email verification, but now publishing is unavailable and I'm unable to activate account. I.e. I have access to the account, but unable to change or verify current email address in it.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @MadSchemas,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4800). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @MadSchemas,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by MadSchemas** [comment]
Hi @Thespi-Brain,
Not sure what is the problem, but I have not received any responses on my email message. Could you please send the response once again or maybe I could contact you from different email address?

**Comment by Thespi-Brain** [comment]
Hi @MadSchemas,

I received your new email address update request and have sent account recovery instructions to that email. Let me know if you have received it, and please follow the instructions in that email and reply to it. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @MadSchemas,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
