### ISSUE TITLE
Project Limit Request: groupdocs-merger-net - 300 MiB

### ISSUE THREAD

**Issue by yuriy-mazurchuk** [pypi/support#4801]
### Project URL

https://test.pypi.org/project/groupdocs-merger-net/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

It's the first official release of the GroupDocs.Comparison library (Aspose Pty)
https://products-qa.groupdocs.com/merger/python-net/
https://releases.groupdocs.com/merger/python-net/

### Reasons for the request

The package includes the necessary DLL files which use neural networks that are essential for the core functionality of our package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey again @yuriy-mazurchuk :wave:
Now I have set the limit to `groupdocs-merger-net` to 300 MB on TestPyPI
Cheers
