### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by klamann** [pypi/support#4803]
### PyPI Username

klamann

### Reason for request

Hi, I lost access to my 2FA credentials and recovery codes on `test.pypi.org` and therefore can't log in anymore. I still have the password and access to my email account.

Access to `pypi.org` is also fine, only my access to `test.pypi.org` is affected due to a failed sync between devices that can write to my password database...

sorry to bother you with this, my credential management usually works very well but here it has failed.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @klamann,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by klamann** [comment]
Hi @Thespi-Brain, thanks for your help! I don't have push access to the cookiecutter-server project anymore, since I don't work at the company which owns that GitHub org any longer. Can you send me the challenge for raspi-poe-mon instead? This project is owned by me.
