### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Sulayman** [pypi/support#4811]
### PyPI Username

Sulayman

### Reason for request

Lost 2FA authentication app or security token

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Sulayman,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Sulayman** [comment]
Dear PyPI Support,

I have completed the required steps for account recovery verification. I have successfully pushed a branch named vUdYdoGXh2ebsT7H to the public source code repository for the project uighur-reshaper on PyPI, as requested.

Here is the repository link: https://github.com/Sulayman/uighur_reshaper

Please proceed with resetting the 2FA for my account and issuing the password reset email.

Thank you for your assistance.

Best regards,
Sulayman

**Comment by Thespi-Brain** [comment]
Hi @Sulayman,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
