### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jakle-23er** [pypi/support#4817]
### PyPI Username

`jakle-23er`

### Reason for request

put in wrong email address that I don't have access to when creating account so I can't verify my access. I accidently did loganmaguire25@gmail.com instead of logan.maguire52@gmail.com

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jakle-23er,

I have updated the primary email address on the account and also reset your 2FA and password reset. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
