### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by reactive-firewall** [pypi/support#4819]
### PyPI Username

`reactive-firewall`

### Reason for request

Accidentally registered with an email address you cannot verify.

Oops! Primary email entered contains a dash "-" where there should be a dot "."

![tempImageyf9VVt](https://github.com/user-attachments/assets/4f5aac7b-d9b4-44b6-9130-741d69b72d02)

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @reactive-firewall,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4819). We will proceed from there. Thanks!

**Comment by reactive-firewall** [comment]
- [x] I have contacted [support@pypi.org](mailto:support@pypi.org) as instructed. @Thespi-Brain, thank you for your assistance on this issue!
