### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dgasmith** [pypi/support#4823]
### PyPI Username

dgasmith

### Reason for request

It looks like I added 2FA on 7/9/22 which was before I had a good recovery key setup and have apparently lost access in the meantime due to transitioning phones.

I'm looking to release a new version of [opt_einsum](https://github.com/dgasmith/opt_einsum) which sees about 12M downloads/month. I can reach out to another maintainer in the meantime, but it would be very helpful to regain access to my account.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @dgasmith,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @dgasmith,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
