### ISSUE TITLE
File Limit Request: shiboken6-generator 150 MiB

### ISSUE THREAD

**Issue by faltsi** [pypi/support#4830]
### Project URL

https://pypi.org/project/shiboken6-generator/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Shiboken is the generator used by the Qt for Python project. It outputs C++ code for CPython extensions, which can be compiled and transformed into a Python module.
The problem is only with the MacOS universal wheels. At some point we will split the wheel or will make the fat binary thinner, but that is not completely in our hands.

### Reasons for the request

The was updates into our dependencies, which had a slight size incerease causing mac wheel to go over the limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @faltsi 
I've set the upload limit for `shiboken6-generator` to 150 MB on PyPI.
Have a great weekend! :rocket:
