### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sydarb** [pypi/support#4831]
### PyPI Username

sydarb

### Reason for request

cannot verify primary email as misspelled it. (should be `areebsyed237@gmail.com` instead of `areebsyed238@gmail.com`)

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @sydarb,

I have updated the primary email address on the account. Your 2FA has also been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
