### ISSUE TITLE
File Limit Request: posebench - 300 MB

### ISSUE THREAD

**Issue by amorehead** [pypi/support#4845]
### Project URL

https://pypi.org/project/posebench/

### Does this project already exist?

- [X] Yes

### New Limit

300 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

PoseBench is a GitHub repository for comprehensive benchmarking of protein-ligand structure generation methods. It contains many nested GitHub repositories required for benchmarking individual methods, which necessitates requesting a larger allowed PyPI upload size.

### Reasons for the request

PoseBench requires many hundreds of megabytes of storage, since it necessarily contains many nested GitHub repositories required for benchmarking individual deep learning methods.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @amorehead :wave:
I've set the upload limit for `posebench` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:

**Comment by amorehead** [comment]
Thanks!
