### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Blackbee85** [pypi/support#4850]
### PyPI Username

blackbee_085

### Reason for request

lost access to email address and my new email is Obiomaogwuegbu89@gmail.com

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Blackbee85,

I have updated the primary email address on the account to the preferred one you have sent over. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
