### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by r0kym** [pypi/support#4859]
### PyPI Username

`r0kym`

### Reason for request

I lost access to my 2FA application when my phone got destroyed and recovery codes are nowhere to be found.

I still have the pypi token I am using to upload packages to the website if it can help prove my identity.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @r0kym,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @r0kym,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by r0kym** [comment]
Password has been changed successfully. Thank you
