### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gaf3** [pypi/support#4864]
### PyPI Username

gaf3

### Reason for request

My Authenticator App vanished from my phone.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @gaf3,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by gaf3** [comment]
Hello! I (just) initiated it because I was on vaca. Haven't seen anything
in 10 min or so. Should we try again?

My apologies. I'm a Director of SRE and should do better with this. I just
hadn't worked on anything in awhile.

Thanks for all your help!

Gaf

**Comment by Thespi-Brain** [comment]
Hi @gaf3,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
