### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rspencer01** [pypi/support#4868]
### PyPI Username

`ahldev`

### Reason for request

We have lost the 2FA for our account as a former employee didn't record the recovery codes. We have access to the username and password and a number of tokens.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @rspencer01,

I have initiated an account recovery process and an email is being sent to the primary email address associated with the account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by rspencer01** [comment]
Account recovered by other means
