### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by minikomi** [pypi/support#4874]
### PyPI Username

mcdigital_adam 

### Reason for request

When I left the company I lost access to the email address, but want to pass ownership of a package on to someone else who still works at the company. I have been in contact with someone at the company, but the mail address has since been removed.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @minikomi,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4874). We will proceed from there. Thanks!

**Comment by minikomi** [comment]
Sorry for the run-around, looks like they were able to re-instate the email address in the meantime. No need for mail address change.

**Comment by Thespi-Brain** [comment]
Hi @minikomi,

I received your new email address request after you closed this issue, so I added in the new email address as a secondary email. A password reset has been issued, as well as a 2FA and recovery code reset. It is always good to set up 2FA for your account for security purposes. Thanks!

**Comment by minikomi** [comment]
Perfect thanks Brian.

Sorry it was all a bit sloshing around in a typical Async communication fashion. Glad it wasn't a hassle on your end.

**Comment by Thespi-Brain** [comment]
You are welcome! fyi, my name is Maria, not Brian! 🫠
