### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ilan-gold** [pypi/support#4878]
### PyPI Username

ilan-gold

### Reason for request

Lost access to my harvard email, need it to publish: https://github.com/hms-dbmi/generate-tiff-offsets re https://github.com/hms-dbmi/generate-tiff-offsets/pull/6

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ilan-gold,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4878). We will proceed from there. Thanks!

**Comment by ilan-gold** [comment]
@flying-sheep I am on a 7 day wait at the moment.  They will (and have) email(ed) me.

**Comment by flying-sheep** [comment]
Ah sorry for jumping the gun here!

**Comment by Thespi-Brain** [comment]
Hi @ilan-gold,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
