### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by joajfreitas** [pypi/support#4882]
### PyPI Username

joajfreitas

### Reason for request

Lost access to unverified primary email

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @joajfreitas,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4882). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @joajfreitas,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!
