### ISSUE TITLE
File Limit Request: libcudf-cu12 - 600 MiB

### ISSUE THREAD

**Issue by jameslamb** [pypi/support#4893]
### Project URL

https://pypi.org/project/libcudf-cu12/

### Does this project already exist?

- [X] Yes

### New Limit

600 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`libcudf` is a fast C++/CUDA dataframe library. It is part of the RAPIDS suite of libraries.

The RAPIDS team has worked to reduce the size in numerous ways including splitting components into separate wheels.

### Reasons for the request

[cuDF](https://github.com/rapidsai/cudf) has built and published wheels in some form to a private index (pypi.nvidia.com) since October 2022. Since then, more projects are depending on `cudf` / `libcudf` now and it would significantly improve the developer experience if the wheels were available directly from PyPI.

Two wheels (one for each `x86_64` & `aarch64`) will be published for each release every two months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by vyasr** [comment]
Thanks James!

**Comment by cmaureir** [comment]
Hello @jameslamb :wave:
I've set the upload limit for `libcudf-cu12` to 600 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:
