### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by apsocarras** [pypi/support#4894]
### PyPI Username

`apsocarras201`

### Reason for request

Lost 2FA authentication app
- Purchased new phone
- Microsoft Authenticator account issue (only generating 8 digit codes, incompatible with my work email)
- Had to remove Authenticator from phone 
- Realized I did not save personal access tokens for this PyPI account!

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @apsocarras,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
