### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by parv06** [pypi/support#4896]
### PyPI Username

c9lab

### Reason for request

I am reaching out because I have lost access to my PyPI account. Unfortunately, I no longer have access to my authenticator app or recovery codes, which has left me unable to log in and update my package.
Could you please assist me in recovering my account so that I can regain access and continue maintaining my packages?

### Recovery Codes

- [ ] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @parv06,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by parv06** [comment]
Dear @Thespi-Brain ,

Thank you for your response to my account recovery request. I have received the email regarding the 2FA reset process and confirm my intent to proceed with resetting the 2FA for my PyPI account (username: c9lab).

I understand that the next steps will involve a 7-day waiting period before the 2FA reset and password reset instructions are issued. I appreciate your assistance in this process and look forward to regaining access to my account.

If any additional information is needed from my side, please let me know.

**Comment by Thespi-Brain** [comment]
Hi @parv06,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
