### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by hshmeng** [pypi/support#4897]
### PyPI Username

hshmeng

### Reason for request

无法访问电子邮件地址
丢失 2FA 身份验证应用程序或安全令牌

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @hshmeng,

Could you please put your request in English? We unfortunately don't provide support in other languages yet. Thank you.

**Comment by hshmeng** [comment]
I lost my recovery code and my phone validator. Can you help me recover my account?

________________________________
发件人: thespibrain ***@***.***>
发送时间: 2024年10月11日 7:09
收件人: pypi/support ***@***.***>
抄送: HSHMENG ***@***.***>; Mention ***@***.***>
主题: Re: [pypi/support] Account recovery request (Issue #4897)


Hi @hshmeng<https://github.com/hshmeng>,

Could you please put your request in English? We unfortunately don't provide support in other languages yet. Thank you.

―

**Comment by hshmeng** [comment]
Sorry, I couldn't find the corresponding email in my mailbox. My account name is hshmeng and the bound email is hshmeng@Foxmail.com

**Comment by hshmeng** [comment]
And I checked my junk mailbox, but couldn't find it

**Comment by hshmeng** [comment]
Thank you, I saw it on my hshmeng@foxmail.com I saw an email in my mailbox

**Comment by Thespi-Brain** [comment]
Hi @hshmeng,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
