### ISSUE TITLE
File Limit Request: dynamsoft-capture-vision-bundle - 200 MB

### ISSUE THREAD

**Issue by DMGithubPublisher** [pypi/support#4902]
### Project URL

https://pypi.org/project/dynamsoft-capture-vision-bundle/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It is a new project developed by Dynamsoft which is an aggregating SDK of a series of specific functional products for image capturing, content understanding, result parsing, and interactive workflow. It supports Windows, Linux and macOS. Yes, we have made efforts to reduce the size but the Source Distributions are still larger than the per-file limit.

### Reasons for the request

We do need to increase the limit to upload the source distributions so that the users can download and install the project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @DMGithubPublisher :wave:
I've set the upload limit for `dynamsoft-capture-vision-bundle` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a great week :snake:
