### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by t03i** [pypi/support#4905]
### PyPI Username

rostlab

### Reason for request

E-mail delivery to primary address admin@rostlab.org is not successful. 

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @t03i,

Please contact support@pypi.org with a new, working email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4905). We will proceed from there. Thanks!

**Comment by t03i** [comment]
Hi @Thespi-Brain,
 
Thank you for taking care of the recovery!
I followed the instructions accordingly and replied to the email.

**Comment by Thespi-Brain** [comment]
Hi @theacodes,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
