### ISSUE TITLE
File Limit Request: eclipse-sumo - 150 MB

### ISSUE THREAD

**Issue by angelobanse** [pypi/support#4907]
### Project URL

https://pypi.org/project/eclipse-sumo/

### Does this project already exist?

- [X] Yes

### New Limit

150 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

[Eclipse SUMO](https://eclipse.dev/sumo) is an open source traffic simulation package, that started in 2001. In 2018 SUMO became [a project at the Eclipse Foundation](https://projects.eclipse.org/projects/automotive.sumo). Today, the main development continues to be driven by employees at the German Aerospace Center (DLR), with contributions from our growing user community! Since the end of 2020, we also started distributing our releases through pip.

### Reasons for the request

The macOS wheels for our latest release (version 1.21.0 - released yesterday) slightly exceeded the limit this time (111MB), as we have added more features. We think that having a new 150MB limit should be enough and future proof, as we don't really expect to get close to it in the coming releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @angelobanse :wave:
I've set the upload limit for `eclipse-sumo` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a great week :snake:

**Comment by angelobanse** [comment]
Thanks!
