### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by colinta** [pypi/support#4910]
### PyPI Username

colinta

### Reason for request

I use 1password for TOTP and recovery codes, so it's really surprising to me that both of these methods of verification are failing. 

I'm very attached to my pypi account, and really hope I can verify myself another way! My pypi account is connected to my GitHub acxount (both use colinta as the username) so hopefully that's a good start. 

I already reached out to support@ (I didn't know you had this convenient issue template).

Thank you all for the tireless and often thankless work that you do on pypi and for open source. ❤️ 

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @colinta,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by colinta** [comment]
Amazing thank you! So glad to be able to get this account restored. 😅

**Comment by Thespi-Brain** [comment]
Hi @colinta,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by colinta** [comment]
Thank you again - access restored, and I created new recovery codes and 2FA.
