### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by solderpunk** [pypi/support#4914]
### PyPI Username

`solderpunk`

### Reason for request

Lost access to email address.  Have *not* lost password for PyPi account and *have* successfully logged in today from same IP address that this request is being opened from.

I request that the address `solderpunk@posteo.net` be added as a new primary email address and am happy to verify that address.

Please see gopher://zaibatsu.circumlunar.space:70/0/~solderpunk/phlog/new-email-address.txt to confirm continuity of identity from `solderpunk@sdf.org` to `solderpunk@posteo.net`.

Please also note that `solderpunk@posteo.net` is the publically visible email address of the GitHub account I am using to open this request, and that this same account owns the `solderpunk/VF-1` repository, which is listed as the homepage for the `VF-1` PyPi project which is owned by the `solderpunk` username.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @solderpunk,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4914). We will proceed from there. Thanks!

**Comment by solderpunk** [comment]
Thank you for the quick response!  I have sent the email as instructed.

**Comment by Thespi-Brain** [comment]
Hi @solderpunk,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @solderpunk,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
