### ISSUE TITLE
Project Limit Request: jupyterlab - 20 GB

### ISSUE THREAD

**Issue by jtpio** [pypi/support#4916]
### Project URL

https://pypi.org/project/jupyterlab/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

JupyterLab is an extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture.

The first release was published to PyPI on December 1st, 2015. 

### How large is each release?

The jupyterlab releases include JavaScript assets for the frontend, which account for a large chunk of the size.

Currently the sdist and wheels together are around 33MB, but this may slowly increase over time as new features keep being added.

![image](https://github.com/user-attachments/assets/4a31bae3-1200-4bfb-a205-3fc1c96ac43e)

### How frequently do you make a release?

Every 1 or 2 weeks, as we also publish pre-releases and backport releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @jtpio :wave:
I've set the project limit for `jupyterlab` to 20 GB on PyPI.
Have a great week :snake:
