### ISSUE TITLE
PEP 541 Request: determined (test index)

### ISSUE THREAD

**Issue by davidfluck-hpe** [pypi/support#4921]
### Project to be claimed

`determined`: https://test.pypi.org/project/determined/

### Your PyPI username

`determined-ai`: https://test.pypi.org/user/determined-ai

### Reasons for the request

Good afternoon. My name is David Fluck, and I would like to request a Test PyPI package transfer for [determined](https://test.pypi.org/project/determined/) on behalf of Hewlett Packard Enterprise. We currently control the production [determined](https://pypi.org/project/determined/) package, but the test version was initially claimed by someone who no longer works for the company, using his personal Test PyPI account, [dzhu](https://test.pypi.org/user/dzhu/). I believe this fits the PEP-541 criteria for project abandonment as follows:

1. The owner of the project is not reachable. We attempted to e-mail the former employee on August 21st, 2024, and have so far received no response. (We can provide visible proof of attempted e-mail contact, if need be.)
1. The project has had no releases in the past 12 months. Its last release was April 8th, 2020.
1. The homepage is the product homepage, https://determined.ai. Although it's technically "active" in that it's receiving regular updates and the product is under active development, I don't believe it's relevant because it's not directly related to the `determined` Python package itself.

We would like to assume ownership of the Test PyPI package, by the following PEP-541 criteria:

1. The project is abandoned.
1. We have tried and failed to contact the original owner.
1. The production version of the package still receives regular releases by us, and the product, [Determined AI](https://github.com/determined-ai/determined), is still under active development.
1. A fork under a different name is undesirable because it bifurcates our release process in complex ways, and makes testing more difficult. HPE owns and controls the production package already; I believe we should be able to control the test package by the same name.

Ultimately, this was an unfortunate oversight four years ago that wasn't fixed when an employee left, causing a bit of an ownership snafu. It would make testing our release process so much easier if we could maintain the Test PyPI version of our production package. I hope this is enough information to convince the index maintainers to transfer ownership of the [determined](https://test.pypi.org/project/determined/) test package to the [determined-ai](https://test.pypi.org/user/determined-ai/) test user.

Please let me know if you need any more information.

Thank you.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/determined-ai/determined

### Contact and additional research

My colleague, [Danny Sauer](https://github.com/dannysauer), attempted to reach out to the former employee on August 21st, 2024, and has not heard back. We can provide visible proof of attempted e-mail contact, if need be.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by davidfluck-hpe** [comment]
Tagging @dzhu here, the current [determined](https://test.pypi.org/project/determined/) owner, for transparency.

**Comment by dzhu** [comment]
Whoops, I'm so sorry! That message came in while I was on a long international trip and I managed to lose track of it. I've now invited the `determined-ai` user on as an owner on `determined` and `determined-cli`. Of course, please go ahead and remove me as an owner once you accept those.

**Comment by davidfluck-hpe** [comment]
@dzhu No worries, truly! It's great to hear from you, and I hope you had a good trip. I've gone ahead and accepted the invitations and removed you as owner. Thanks again, and I hope you're doing well!
