### ISSUE TITLE
File Limit Request: pyside6-addons - 400 MB

### ISSUE THREAD

**Issue by faltsi** [pypi/support#4931]
### Project URL

https://pypi.org/project/PySide6-Addons/

### Does this project already exist?

- [X] Yes

### New Limit

400

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a complementary wheel for [PySide6](https://pypi.org/project/PySide6) 
As part of the effort of splitiing pyside6, this wheel was introduced more than 2 years ago.

### Reasons for the request

The latest released universal mac wheel was already the size of the current limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @faltsi :wave:
I've set the upload limit for `pyside6-addons` to 400 MB on PyPI. 
Have a great week :snake:
