### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MinSong2** [pypi/support#494]
Request for account recovery.

## PyPI Username

`minsong_yonsei`

---

##  Reason for request

Reason:

**Comment by MinSong2** [comment]
I do not recall my authentication code. Please help.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@MinSong2 do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: minsong_yonsei" to proceed
