### ISSUE TITLE
Project Limit Request: Gradio - 30 GB

### ISSUE THREAD

**Issue by freddyaboulton** [pypi/support#4941]
### Project URL

https://pypi.org/project/gradio/

### Does this project already exist?

- [X] Yes

### New limit

100 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Gradio is a popular package for building ai-powered interactive web apps entirely in python. About 1 million unique developers build Gradio apps every month! 

It has been active for about 4 years and in that time a vibrant community of Gradio developers has emerged. Popular github repositories like Automatic1111 are powered by Gradio and the community has published hundreds of custom Gradio components for others to use.

### How large is each release?

Our releases are about 100mb across the wheel and source distribution. We don't expect increases in the futre. The size is because Gradio ships with pre-built javascript assets for both client-side and server-side rendering.

### How frequently do you make a release?

Roughly once every two weeks. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @freddyaboulton :wave:
The project currently has a limit of 10G, and an increase makes sense, but I'm always hesitant of increasing the size so much. Normally, projects with a 10G limit jump to 20 or 30 GB, which I would prefer. The motivation of this is to avoid many projects asking for a high limit just to be safe, and instead see if we could keep the project sizes at minimum. It would be totally OK if in some months/years you need another +10/20GB for the project :)

Would a jump to 30GB be OK for you?

**Comment by freddyaboulton** [comment]
Hi @cmaureir - yes 30 gb would work for us! Thank you!!

**Comment by freddyaboulton** [comment]
Hi @cmaureir , @pradyunsg - any updates on our request? We are hitting the limit actively and have to yank old versions in order to release new versions.

**Comment by cmaureir** [comment]
Hey @freddyaboulton 
I've set the project limit for `gradio` to 30 GB on PyPI.
Have a nice week!

**Comment by freddyaboulton** [comment]
Thank you so much!
