### ISSUE TITLE
Account recovery request For My account UserName: reddyprasade

### ISSUE THREAD

**Issue by reddyprasade** [pypi/support#4944]
### PyPI Username

reddyprasade

### Reason for request

I hope this message finds you well.

I am writing to request assistance regarding my two-factor authentication (2FA) and recovery code, which I have unfortunately lost. As a result, I am currently unable to access my account.

Could you please guide me through the process to either recover or reset my 2FA settings? If additional identification or verification is required to proceed with this request, please let me know, and I will provide the necessary information as quickly as possible.

I appreciate your prompt attention to this matter and look forward to your guidance.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @reddyprasade,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
