### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by conqp** [pypi/support#4947]
### PyPI Username

coNQP

### Reason for request

I got a new phone and reset my old one before backing up my 2FA app.
Unfortunately I can neither find my recovery tokens.
Please advise whether I can regain access to my PyPI account by other means.

I am, amongst a few other packages, the maintainer of rcon

- https://github.com/conqp/rcon/
- https://pypi.org/project/rcon/

and just wanted to publish a bugfix for it.

Thank you

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @conqp,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by conqp** [comment]
Hey. I followed the instructions in the mail, an created the branch with the nonce name immediately.
Unfortunately I skipped the part with replying to the email and only did that on 01.11.2024, 10:17.
I suspect that the nonce had already timed out by then, since I did not receive any further email since then.
Please advise.

**Comment by Thespi-Brain** [comment]
Hi @conqp,

Thanks for completing the verification process. The verification was successful! Nothing timed out. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
