### ISSUE TITLE
File Limit Request: bodosql - 200 MiB

### ISSUE THREAD

**Issue by njriasan** [pypi/support#4948]
### Project URL

https://pypi.org/project/bodosql/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

BodoSQL is a 2+ year old project that provides SQL support for the Bodo project. To do this we rely on some java dependencies, namely apache calcite as a SQL optimizer and this requires us to bundle other packages from Java. In particular, due to larger package sizes for our catalogs (Apache Iceberg, AWS, Snowflake) the java package has grown in size.

We are making attempts to shrink the underlying JAR size by removing unused dependencies, but we have hit issue due to dynamic loading which means we do not have a reasonable timeline to stay within the 100MiB limit.

### Reasons for the request

Right now our package size is around 120 MiB. If we upgrade some of our core dependencies (which we plan to do soon) it will increase to 150 MiB before we have the option to reduce the size. We would like a limit of 200 MiB as a buffer until we have more resource to improve our build process. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @njriasan :wave:
I've set the upload limit for `bodosql` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a great week :snake:
