### ISSUE TITLE
Account recovery request - I do have recovery codes

### ISSUE THREAD

**Issue by nandoabreu** [pypi/support#4955]
### PyPI Username

nandoabreu

### Reason for request

Hello! I no longer have the e-mail account set as my primary email for pypy. I added a new e-mail to **replace the primary** one (using my 2FA), but I can't remove it.

**I DO have** my pypy recovery codes. _I marked as not having because the form wouldn't allow me to submit and I didn't see other forms to use._

Thanks for your support <3

**Recap:**
- I DO have 2FA
- I DO have recovery codes
- I do NOT have the primary e-mail account any more

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @nandoabreu,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4955). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @nandoabreu,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @nandoabreu,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
