### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sametcopur** [pypi/support#4958]
### PyPI Username

`sametcopur`

### Reason for request

Hello,

After resetting my old phone, a Huawei P20 Pro, I lost access to my Microsoft Authenticator app, which contained my PyPI account. Unfortunately, I am unable to recover the account through any means. As I do not use my PyPI account very actively, this issue went unnoticed for some time. Currently, I am unable to access the authenticator for my account. If necessary, I am willing to provide any required evidence to prove ownership of the account.

Thank you for your assistance.

Best regards,
Samet Çopur

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @sametcopur,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @sametcopur,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
