### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by marketcalls** [pypi/support#4959]
### PyPI Username

'openalgo'

### Reason for request

Dear [Support Team/Account Recovery Team],

I hope this message finds you well.

I am writing to request assistance in restoring access to my account. Here are the account details:

Email ID: rajandran@marketcalls.in
Username: openalgo
Unfortunately, I have lost access to both the recovery codes and the authenticator app associated with my account. As a result, I am unable to complete the 2FA process to log in. I kindly request guidance on how I can regain access to my account.

Please let me know if any further information or documentation is required to verify my identity and proceed with the recovery process. I am available to provide any necessary verification.

Thank you for your prompt assistance.

Sincerely,
Rajandran R.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @marketcalls,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @marketcalls,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
