### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by LouisFaure** [pypi/support#4980]
### PyPI Username

LouisFaure

### Reason for request

Dear PyPi team,

I can connect to my account, however my primary mail is not accessible anymore as I changed job (the account has been disable since one year). This prevents me to do any changes on my account despite the fact that I have:
1. 2FA enabled with functioning TOTP (I actually have the recovery codes, but they have no use for my case)
2. another functioning mail registered in the account.

Please allow me to remove the primary mail and set the other mail as primary.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @LouisFaure,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4980). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @LouisFaure,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by LouisFaure** [comment]
Hi, just letting you know that I have sent the response by mail, was this well received?

**Comment by Thespi-Brain** [comment]
Hi @LouisFaure,

Yes, I received your email. I just got back from GitHub Universe, so responses are going to be slightly delayed! Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
