### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ansipunk** [pypi/support#4984]
### PyPI Username

`ansipunk`

### Reason for request

Lost access to primary email. Still have my password and 2FA keys. Have extra email attached. Need the current primary one to be removed and the extra one to be the primary one.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ansipunk,

Thanks for indicating your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4984). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ansipunk,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
