### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by AaronBandt** [pypi/support#4989]
### PyPI Username

`citygrid_open`

### Reason for request

Hello, I have lost access to the primary email address associated with this account and am trying to regain it so that I can upload newer versions of of this project to pypi. This is an open source project that was started at my former company CityGrid but has seen numerous updates over the last 9 years. The GitHub url for the project is: https://github.com/UnblockedByOps/arsenal. Please let me know if there is any additional information that would be helpful.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @AaronBandt,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4989). We will proceed from there. Thanks!

**Comment by AaronBandt** [comment]
Ok thank you! Done.

**Comment by Thespi-Brain** [comment]
Hi @AaronBandt,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by AaronBandt** [comment]
I have completed the request and replied to the email. Thank you again!

**Comment by Thespi-Brain** [comment]
Hi @AaronBandt,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by AaronBandt** [comment]
Thank you for all your help in this matter!
