### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by qstokkink** [pypi/support#4991]
### PyPI Username

`TriblerCI`

### Reason for request

Lost access to email address, please add the unverified e-mail `triblertester@gmail.com` to the account.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @qstokkink,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4991). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @qstokkink,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by qstokkink** [comment]
Thank you! I now have my preferred e-mail address tied to the account. I also verified the new address. However, the old e-mail address is still set as the primary e-mail. So, I can't do anything (I get the `Error You must verify your **primary** email address before you can perform this action` warning).

Could you set the new, now verified, e-mail address as the primary e-mail addresss?

**Comment by Thespi-Brain** [comment]
Hi @qstokkink,

The email gets updated once the branch verification is complete. Could you please push the branch again according to the instructions that were sent to you? I was unable to find the branch that you pushed to the repo. I also sent you an email. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @qstokkink,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
