### ISSUE TITLE
File Limit Request: casaplotserver - 300 MB

### ISSUE THREAD

**Issue by vsuorant** [pypi/support#4997]
### Project URL

https://pypi.org/project/casaplotserver

### Does this project already exist?

- [X] Yes

### New Limit

300 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

CASA plotserver makes Qwt plotting available from C++ and Python via gRPC. This is used for interactive flagging in Casa ( https://casa.nrao.edu/ ). The project has been active since 2020

### Reasons for the request

The project is dependent on Qt libraries and the size of those libraries grew significantly with Qt6.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @vsuorant :wave:
Long time I haven't heard about CASA :tada: I remember it from when I was a student 👯 

I've set the upload limit for `casaplotserver` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:

**Comment by vsuorant** [comment]
Thank you very much @cmaureir ! Sorry about the deluge of tickets.
