### ISSUE TITLE
File Limit Request: casafeather - 300 MB

### ISSUE THREAD

**Issue by vsuorant** [pypi/support#4998]
### Project URL

https://pypi.org/project/casafeather/

### Does this project already exist?

- [X] Yes

### New Limit

300 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Combine two images using their Fourier transforms in Casa ( https://casa.nrao.edu/ ). The project has been active since 2021.

### Reasons for the request

The project is dependent on Qt libraries and the size of those libraries grew significantly with Qt6.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Same here as your [other issue](https://github.com/pypi/support/issues/4997) ;)
Cheers
