### ISSUE TITLE
File Limit Request: casalogger - 300 MB 

### ISSUE THREAD

**Issue by vsuorant** [pypi/support#4999]
### Project URL

https://pypi.org/project/casalogger

### Does this project already exist?

- [X] Yes

### New Limit

300 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Logging UI for Casa ( https://casa.nrao.edu/ ). The project has been active since 2022

### Reasons for the request

The project is dependent on Qt libraries and the size of those libraries grew significantly with Qt6.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
...and also here as your other two issues.
