### ISSUE TITLE
File Limit Request: casatablebrowser - 300 MB

### ISSUE THREAD

**Issue by vsuorant** [pypi/support#5000]
### Project URL

https://pypi.org/project/casatablebrowser

### Does this project already exist?

- [X] Yes

### New Limit

300 MiB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The casatablebrowser package provides a GUI for examining CASA( https://casa.nrao.edu/  ) and  casacore ( https://github.com/casacore/casacore ) table data. The project has been active since 2020

### Reasons for the request

The project is dependent on Qt libraries and the size of those libraries grew significantly with Qt6.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
phew...and here after your other 3 issues!
Cheers
