### ISSUE TITLE
Project Limit Request: Flatterer - 20 GB

### ISSUE THREAD

**Issue by kindly** [pypi/support#5001]
### Project URL

https://github.com/kindly/flatterer/
https://pypi.org/project/flatterer/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It's a tool to convert JSON into relational databases/files.  It's been around for about 3/4 years and used as a library and command line tool.

### How large is each release?

Each release is around 800MB.  This is due to creating wheels for a lot of platforms and having a lot of targets for data conversion (postgres, sqlite, parquet, xlsx, duckdb). I try and make the binaries as small as I can.

I regularly delete old versions that I don't think are used (very much) but it is getting harder and recently got a complaint: https://github.com/kindly/flatterer/issues/72

### How frequently do you make a release?

6 times a year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @kindly :wave:
I've set the project limit for `flatterer` to 20 GB on PyPI.
Have a nice week! :snake:
