### ISSUE TITLE
File Limit Request: mobsf - 250 MB

### ISSUE THREAD

**Issue by ajinabraham** [pypi/support#5008]
### Project URL

https://pypi.org/project/mobsf/

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The size update is due to a bundled database which takes a considerable amount of size. We tried optimizing the by compressing most of the files, but at our wits end with this one.

Some of our users do not have internet access after the install, making it difficult to dynamically download these assets.

Mobile Security Framework (MobSF) is an automated, all-in-one mobile application (Android/iOS/Windows) pen-testing, malware analysis and security assessment framework capable of performing static and dynamic analysis.

### Reasons for the request

We don't expect the size to grow above 200 MB

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @ajinabraham :wave:
The title says `110` and the description says `250` how many MB are you requesting?

**Comment by ajinabraham** [comment]
Apologies , it is 250 MB.

**Comment by cmaureir** [comment]
Thanks,
I've set the upload limit for `mobsf` to 250 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:

**Comment by ajinabraham** [comment]
Thanks, I will do my best to optimize file size.
