### ISSUE TITLE
File Limit Request: PyJHora - 120 MB

### ISSUE THREAD

**Issue by naturalstupid** [pypi/support#5009]
### Project URL

https://pypi.org/project/PyJHora

### Does this project already exist?

- [X] Yes

### New Limit

120 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Complete Vedic Astrology Python package.

### Reasons for the request

Main file size come from ephemeris data files. Those files will not increase in size. For now 120 MB is adequate.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @naturalstupid :wave:
I've set the upload limit for `pyjhora` to 150 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:

**Comment by naturalstupid** [comment]
Thank you. I faced this issue in my 2nd release. Since then I am not including data files in the releases which are 100MB+. Instead I am stating in my README. to get them from previous releases. So hopefully I will stay within original limit anyways. I may use the upgraded limit only infrequently in future releases. Thanks again
