### ISSUE TITLE
File Limit Request: HOPP - 150 MB

### ISSUE THREAD

**Issue by johnjasa** [pypi/support#5017]
### Project URL

https://pypi.org/project/hopp/

### Does this project already exist?

- [X] Yes

### New Limit

150 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The project is an open-source tool made by the National Renewable Energy Laboratory to model hybrid power plants and has been active since 2020. This release includes large .xlsm files that contain price data for renewable systems.

### Reasons for the request

This release includes large .xlsm files that contain complex price data for different renewable energies. By bundling these files in with our release we can streamline and automate the process for users to determine the investment and operating costs of renewable energy plants. These files are not available easily elsewhere so we include them in our project.

We do not expect our project size to increase appreciably in the future; this is a one-time addition.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @johnjasa :wave:
I've set the upload limit for `hopp` to 150 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size, and consider to deploy that  xlsm file in a different way in case the size keep increasing.
Have a nicee week!
