### ISSUE TITLE
File Limit Request: daal-devel  300 MB

### ISSUE THREAD

**Issue by napetrov** [pypi/support#5020]
### Project URL

https://pypi.org/project/daal-devel/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

oneDAL is machine learning library accelerating x86 architecture - https://github.com/oneapi-src/oneDAL
There are several flavors of packages  on PyPi - runtimes, includes, devel, static. 

This library used by upstream projects like scikit-learn-intelex

### Reasons for the request

We are adding more functionality in to the package that extends it's size significantly and this is native library content that large in size comparing to pure python packages.
In this particular request we would like to extend devel package limit to prepare for restructuring contents of packages. 
In longerterm plan we would be splitting develop package to cpu and GPU portions similar to split done with MKL library 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @napetrov :wave:
I've set the upload limit for `daal-devel` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week! :snake:
