### ISSUE TITLE
File Limit Request: passagemath-gap - 300 MiB

### ISSUE THREAD

**Issue by mkoeppe** [pypi/support#5021]
### Project URL

https://pypi.org/project/passagemath-gap/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

passagemath (https://github.com/passagemath) is a fork of SageMath offering modularized installation from PyPI instead of monolithic installation from source. SageMath has been developed since 2005, the modularization is in progress since 2020, the fork has been created in October 2024.
passagemath-gap is one component. Its binary wheels ship a copy of GAP (https://www.gap-system.org/; developed since 1986) in the minimal configuration of packages needed by SageMath. This brings the current size of the macOS wheel to 230MB.

### Reasons for the request

Provide self-contained installation of SageMath via pip.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @mkoeppe :wave:
I've set the upload limit for `passagemath-gap` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:

**Comment by mkoeppe** [comment]
Thank you!
