### ISSUE TITLE
Account recovery reset request

### ISSUE THREAD

**Issue by droodev** [pypi/support#5023]
### PyPI Username

`droodev`

### Reason for request

My 2FA stopped working. I use FreeOTP+ on Android and it generates codes that turn out to be invalid.

Couple of days ago I was migrating FreeOTP+ from one phone to another. Afterwards I double-checked that my 2FA works. Today I wanted to log-in and I could not. Interestingly, the same day I migrated my TestPyPi and this is still working well---which rather excludes problems with time synchronization on my end.

I think just a plain recovery is the best option here. If there are better ones, I am happy to take other advice to get to my account.

By the way, when trying to get in I also changed the password of my account, which was successful.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @droodev,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by droodev** [comment]
Hi,

Thanks, I got the e-mail proceeded accordingly.

Interestingly, it is quite confusing that the email says that "there are no projects with public source code repositories associated with your account".  I am (/have a role of) an "owner" in organization "science-for-democracy", which has four PyPi open-source projects published (mapof, mapof-elections, mapof-roommates, mapof-marriages). Could you elaborate on what exactly means "associated with (...) account"? Intuitively, it seems that I must be somehow associated with the code that I'm an owner of, isn't it?

**Comment by Thespi-Brain** [comment]
Hi @droodev,

What that email meant was there were no public repo links connected to your PyPI account. But since the 7 day wait period is over, your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by droodev** [comment]
Hi,

everything works, got my access back, thank you!!!

For future reference, can we tell me how to connect some public repo with my PyPI  account?
