### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by oliverandrich** [pypi/support#5028]
### PyPI Username

oliverandrich

### Reason for request

Can you please reset my account on test.pypi.org? Sadly, Apples password "manager" has mixed the accounts for pypi.org and test.pypi.org. Now I only have a working account, but not for test.pypi.org. During this "merge" I lost the totp settings and the recovery codes for test.pypi.org.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @oliverandrich,

Your 2FA has been reset and a password reset has been issued for your Test.PyPI account. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by oliverandrich** [comment]
Thanks a lot, @Thespi-Brain.
