### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by yuvlar** [pypi/support#5031]
### PyPI Username

cosmo-admin

### Reason for request

Our @cloudify.co domain was removed (due to being acquired by Dell)
We need your help in switching the primary email address to a dell one.
yuval.rapaport@dell.com is good.

I still have the username/password/api-token to login to the account.

This is blocking us from uploading a new version to Pypi because our primary email is not verified

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @yuvlar,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @yuvlar,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
