### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ako1983** [pypi/support#5032]
### PyPI Username

`ako_1983`

### Reason for request

would you mind changing my old email (aheidari@gmu.edu) to my new email ( ako.heidari@gmail.com)
I don't have access to my school email any more, but my gmail (linked to my gmail as well) is active, and secure with MFA
---
also, if there is a way to change the email address or add another email, I can do that myself too,

thanks

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ako1983,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by ako1983** [comment]
Thank you for your assistance.
