### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bartosz-bok** [pypi/support#5033]
### PyPI Username

ai-traders-org

### Reason for request

I accidentally wrote `aitradersorg@gmai.com` email, instead of `aitradersorg@gmail.com`

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @bartosz-bok,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
