### ISSUE TITLE
File Limit Request: robosuite - 300 MB

### ISSUE THREAD

**Issue by yukezhu** [pypi/support#5037]
### Project URL

https://pypi.org/project/robosuite/

### Does this project already exist?

- [x] Yes

### New Limit

300

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

**robosuite** is a simulation framework powered by the MuJoCo physics engine for robot learning. It also offers a suite of benchmark environments for reproducible research. This project has been active since 2018 (for 6 years). 

### Reasons for the request

We are providing support for a variety of new robot models in our latest version (v1.5) of robosuite. The total package size went up from 200MB to 250MB. So, we kindly request an increase in the file size limit that will allow us to upload our new package.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @yukezhu :wave:
Considering you mentioned the package went from 200 to 250M, would an increase to 300M be more accurate than 500M ?
Have you considering providing the models for new robots as a runtime feature, so people can download it if they needed, similar to what NLTK does for the data https://www.nltk.org/install.html#installing-nltk-data ?

Have you tried other techniques to reduce the package size?

**Comment by yukezhu** [comment]
Thank you for getting back to me on this. I agreed that an increase to 300M would be more accurate. We have added scripts to download on-demand 3D assets for our simulation environments. However, we hope to include these new robot models as part of the package so that the users can run our demo scripts to simulate them out of the box.

**Comment by cmaureir** [comment]
Hello @yukezhu :wave:
so I changed the file limit for `robosuite` to 300M on PyPI and TestPyPI.
Have a good one! :snake:
