### ISSUE TITLE
File Limit Request: ai-edge-model-explorer-adapter - 120 MB

### ISSUE THREAD

**Issue by yijie-yang** [pypi/support#5039]
### Project URL

https://pypi.org/project/ai-edge-model-explorer-adapter/

### Does this project already exist?

- [x] Yes

### New Limit

120

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Model Explorer is a visualization and debugging tool designed to handle large machine learning graphs. It was initially launched in May 2024. This particular PyPI package provides the backend adapter that facilitates communication with the Model Explorer server.

This adapter is implemented in C++ for performance reasons and utilizes pybind11 to create Python bindings. Due to the inherent complexities of interacting with large ML graphs, the C++ codebase has dependencies on the TensorFlow repository. These dependencies contribute significantly to the overall size of the package.

This package does not bundle any additional packages or example data. It primarily focuses on providing the core backend functionality for Model Explorer.

### Reasons for the request

We kindly request an increase in the size limit for this PyPI package due to the necessary inclusion of TensorFlow dependencies. These dependencies are crucial for enabling the core functionality of Model Explorer and its ability to effectively handle large and complex machine learning graphs.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by yijie-yang** [comment]
Hello, friendly ping. Is there any update on the status? This issue is blocking our new release for pypi packages. Let you know if there is any concerns, happy to discuss. Thanks!

**Comment by cmaureir** [comment]
Hello @yijie-yang :wave:
I've set the upload limit for `ai-edge-model-explorer-adapter` to 150 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:
