### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gosiao** [pypi/support#5041]
### PyPI Username

`gosia`

### Reason for request

Lost 2FA authentication app or security token

Dear Colleagues,

I have a password to www and a token ("pypi-XXX") related to my test.pypi account, but I did not set up 2FA (I must have missed the information about it), and now I cannot access it.

Could you please help me to recover it? 
I'd then set up 2FA straightaway.

Thank you for your assistance!

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @gosiao,

I have initiated an account recovery process for your Test.PyPI account and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by gosiao** [comment]
Thank you, I will do that.

sob., 2 lis 2024 o 01:52 thespibrain ***@***.***> napisał(a):

**Comment by Thespi-Brain** [comment]
Hi @gosiao,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your Test.PyPI account after completing the password reset. Let us know if you have any more issues. Thanks.
