### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dippatel1994** [pypi/support#5042]
### PyPI Username

dippatel1994

### Reason for request

I used the wrong email address to sign up, there was a spelling mistake. I use the email address "dipaptel1994@gmail.com" but my correct email address is "dippatel1994@gmail.com".

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @dippatel1994,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
