### ISSUE TITLE
Account recovery request for TestPyPI

### ISSUE THREAD

**Issue by hamedbh** [pypi/support#5048]
### PyPI Username

`hamedbh`

### Reason for request

This issue relates to my TestPyPI account **only**.

I cannot login to TestPyPI. I didn't realise that PyPI and TestPyPI use different login credentials, so when I set up my PyPI account I overwrote my login details for TestPyPI in my password manager. That meant that I lost my two-factor authentication setup and the recovery codes for TestPyPI.

I still have control of the email address that I used to register, and I can still login to PyPI OK. I would really appreciate your help with this, thank you!

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @hamedbh,

Your 2FA has been reset and a password reset has been issued for your Test.PyPI account. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
