### ISSUE TITLE
File Limit Request: satellite-weather-downloader - 250 MB

### ISSUE THREAD

**Issue by luabida** [pypi/support#5049]
### Project URL

https://pypi.org/project/satellite-weather-downloader/

### Does this project already exist?

- [x] Yes

### New Limit

250Mb

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Satellite Weather Downloader is a Xarray extensions & a python API to download climate data from Copernicus. It calculates the climate data for a specific region (currently for Brazil and Argentina only) based on the shapes of the geo locations (ADM0, ADM1 and/or ADM2).

### Reasons for the request

In the release 1.11.0 some `.gpkg` files containing the polygons were included in the project they must be added in the package to be fetched via PyPi

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @luabida :wave:
I've set the upload limit for `satellite-weather-downloader` to 250 MB on PyPI, it didn't exist in TestPyPI so in case you need it, please open a new issue once that's created. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:
