### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Dardasaba** [pypi/support#5055]
### PyPI Username

`dardasaba`

### Reason for request

Lost 2FA authentication app or security token.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Dardasaba,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
