### ISSUE TITLE
File Limit Request: kivy-webview.deps - 200 MB

### ISSUE THREAD

**Issue by DexerBR** [pypi/support#5057]
### Project URL

https://pypi.org/project/kivy-webview.deps

### Does this project already exist?

- [x] Yes

### New Limit

200 MB

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

`kivy_webview` will be a Kivy widget that allows developers to embed web content directly into their applications. It will support multiple platforms and utilize specific backends to render web views. **The binary files will be provided through `kivy_webview.deps`.**
### Reasons for the request

Dear PyPI team,

I am requesting an upload limit increase for the `kivy_webview.deps` package, currently in development, as it requires more than 100 MB to include all essential dependencies. The size exceeds 100 MB due to the binaries of the backends used in the `kivy-webview` project.

I explored some options to reduce the size of the dependencies, but they are still larger than 100MB.

Thank you for your consideration!

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @DexerBR :wave:
I've set the upload limit for `kivy-webview.deps` to 200 MB on PyPI, but it didn't exist in TestPyPI so in case you still need it, please open a new issue if you create it. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:
