### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by BobTheBuidler** [pypi/support#5058]
### PyPI Username

bubthebuidler

### Reason for request

I broke the phone on which I had my authentication set up. I am unable to log in or manage any of my repositories. 
Hopefully this isn't the end of my PyPI account!

Thanks,
Bob

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @BobTheBuidler,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
