### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by travisgk** [pypi/support#5059]
### PyPI Username

`travisgk` 

### Reason for request

I entered my email incorrectly and now my newly-created account can't be verified and I can't add a new email either.

I used travisgk@users.noreply.github.com on accident, whereas I should've used:
162270915+travisgk@users.noreply.github.com

I'm hoping someone can manually change the email to the correct one so I can verify the address. Thank you for your time.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @travisgk,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by travisgk** [comment]
Okay. Could you actually change my email address once more? To:
githubtravisgk@gmail.com

I'm having a lot of hassles trying to mess with the GitHub email so I just made a new email altogether.
