### ISSUE TITLE
File Limit Request: CityLearn - 500 MB

### ISSUE THREAD

**Issue by kingsleynweye** [pypi/support#5064]
### Project URL

https://pypi.org/project/CityLearn

### Does this project already exist?

- [x] Yes

### New Limit

500

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

The project is CityLearn, a reinforcement learning environment for training agents to manage building energy systems in a district of buildings. It was [created in 2019](https://www.citylearn.net) but only active on PyPi since July 20, 2022 for ease of use as the core part of the [NeurIPS Competition Track CityLearn Challenge 2022](https://www.aicrowd.com/challenges/neurips-2022-citylearn-challenge).

The reason for the increased size are trained scikit-learn decision trees that are referenced during runtime in one of the simulation datasets. There is also a `csv` file that contains solar and battery metadata needed to customize the environment. These are new additions that did not exist in the last uploaded version of the project.

### Reasons for the request

An attempt to upload the latest version of the project via GitHub Actions failed because the file size limit was exceeded. This is from the GitHub Actions log showing the file size:

```
Uploading distributions to https://upload.pypi.org/legacy/
INFO     dist/CityLearn-2.2.0-py3-none-any.whl (232.8 MB)                       
INFO     dist/CityLearn-2.2.0.tar.gz (221.4 MB)  
```

We don't expect the file size to exceed more than double the current size in the near future hence, our request for 500 MB.

We will please, like an increase in the file size limit to continue to make the project readily available for installation to the research community that uses it.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @kingsleynweye :wave:
Checking at the sizes, I believe an increase to 250M will be enough for your project considering you mentioned the size will not increase. Remember the limit is per-file and not per-release.
Would that size be OK for you?

**Comment by kingsleynweye** [comment]
Hi @cmaureir, thanks for the response. Yes, 250M will be okay.

**Comment by cmaureir** [comment]
I have set 250M as the new file limit for `citylearn` on PyPI.
Have a nice week :snake:
