### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by samadpls** [pypi/support#5065]
### PyPI Username

samadpls

### Reason for request

I am currently unable to access my account because I have previously connected using the Microsoft Authenticator app, but it is no longer providing me with a code.

I know my password; however, when I attempt to log in with the access code I have, I receive an "invalid code" error. This issue is preventing me from pushing my library, and I would greatly appreciate your help in resetting my account access or resolving this issue.

Thank you for your attention to this matter. I'm looking forward to your help as soon as possible.

Best regards,

A. Samad

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @samadpls,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @samadpls,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
