### ISSUE TITLE
Project Limit Request: onnxruntime-gpu - 40 GiB

### ISSUE THREAD

**Issue by sophies927** [pypi/support#5067]
### Project URL

https://pypi.org/project/onnxruntime-gpu/

### Does this project already exist?

- [x] Yes

### New limit

40 GiB

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

ONNX Runtime is a cross-platform runtime accelerator for machine learning models and has been active since 2018.

We need to publish a 1.20.1 patch release but are going to hit our 30GB project limit since we needed to add thread-free Python 3.13 packages. The primary value-add of our project is that we make it possible to accelerate machine learning models across a variety of hardware and platforms.

Increasing limit to 40GB should support the next several releases.

### How large is each release?

~2500 MB total

Python 3.10, Python 3.11, Python 3.12, Python 3.13, and Python 3.13 thread-free Linux wheels (~380 MB each)
Python 3.10, Python 3.11, Python 3.12, and Python 3.13 Windows wheels (~280 MB each)

### How frequently do you make a release?

We complete a major release quarterly with the occasional patch release in between.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by sophies927** [comment]
@cmaureir can you help us with this?

Worth noting that we have stopped publishing our onnxruntime-training package, so this is now the only package we have reached our package limit for! We had an unforeseen project size increase since [Python has started to provide support for free threading](https://docs.python.org/3/howto/free-threading-python.html), and we needed to publish a thread-free Python 3.13 package.

**Comment by cmaureir** [comment]
Hello @sophies927 :wave:
I have set 40G as the new limit, but please consider either using [Python's stable api ](https://docs.python.org/3/c-api/stable.html) to reduce the amount of wheels (300M per wheel is a lot/).
Have a nice week :snake:
