### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gcalacoci** [pypi/support#5069]
### PyPI Username

gcalacoci

### Reason for request

 I'm trying to recover this old account of mine,

When I try to log in with the username and password, it says that the password is compromised, and I cannot reset it as the mail associated with the account doesn't exist anymore 

I've created another account a couple of months ago and I've been added to the projects the other account was managing, 
but still, I would like to know if it is possible to recover this one.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @gcalacoci,

If you wish to recover this account, please contact support@pypi.org with an email address that you would like the account to be associated with and please reference this link (https://github.com/pypi/support/issues/5069). We will proceed from there.Just an FYI, we have a one unique email per one unique account policy. Thanks!

**Comment by gcalacoci** [comment]
Email sent to support@pypi.org

**Comment by Thespi-Brain** [comment]
Hi @gcalacoci,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
