### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by wn0x00** [pypi/support#5070]
### PyPI Username

wn0x00

### Reason for request

Lost two-factor authentication [application](https://pypi.org/help/#totp), [device](https://pypi.org/help/#utfkey), and [recovery codes](https://pypi.org/help/#recoverycodes)

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @wn0x00,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @wn0x00,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
