### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by NOTBGVAI** [pypi/support#5071]
### PyPI Username

biraj3208

### Reason for request

          Hello! Man I want to recover my Gmail account but I accidently formatted the device and lost the access. Can you please help me 😭. This is the gmail -  no8422341@gmail.com.I had this  gmail on my POCO C31. Please add the recovery gmail - titangaming33l6@gmail.com If you can.

### Recovery Codes

- [ ] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @NOTBGVAI,

Could you please clarify your request, because it sounds like you are having an issue getting your Gmail account recovered for your personal Gmail address. It doesn't sound like it has anything to do with PyPI. Some more clarification regarding your issue would be helpful, thanks.

**Comment by NOTBGVAI** [comment]
I thought you guys recover lost or hacked Gmail account 😕
