### ISSUE TITLE
Request to Correct Account Email Address Typo

### ISSUE THREAD

**Issue by juyoung9653** [pypi/support#5073]
### PyPI Username

Chinu9653

### Reason for request

When signing up, I entered @gmail.com incorrectly as @gamil.com. I want to fix this

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @juyoung9653,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
