### ISSUE TITLE
PEP 541 Request: wt

### ISSUE THREAD

**Issue by llama-for3ver** [pypi/support#5074]
### Project to be claimed

https://pypi.org/project/wt

### Your PyPI username

llama-for3ver

### Reasons for the request

The project has stated in its [README](https://github.com/ysegorov/wt) that it has been archived. The developer @ysegorov seems mostly inactive, and the project hasn't been touched in over 4 years. I think it's reasonable to believe that it's abandoned, and the owner would be happy with replacing if contactable.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

As linked above, [https://github.com/ysegorov/wt](https://github.com/ysegorov/wt)

In terms of what its replacement will be, can't be published currently. I can however guarantee it will happen soon and be useful, though. ( I will update to add a link)

### Contact and additional research

I have emailed the owner several times with their listed address to no response. They don't seem to have any other form of contact, even in their linked CV.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by llama-for3ver** [comment]
Sorry for bothering you then.
But I’m just wondering, why say if it’s archived despite future plans? From how I interpret it, I thought the opposite.

**Comment by ysegorov** [comment]
Not sure this is the right place to discuss it. You can always create feature request [here](https://github.com/ysegorov/wt/issues) in case you have to. Thanks for the understanding.
