### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by DedInc** [pypi/support#5091]
### PyPI Username

Maehdakvan

### Reason for request

Hello PyPI Support Team,

I am reaching out for assistance with recovering my PyPI account. I have lost access to my Two-Factor Authentication (2FA) device and, as a result, am unable to complete the login process. I still have access to all other account credentials, including my email, username, and password.

Could you please guide me through the process of recovering my account or disabling 2FA temporarily so I can regain access?

Thank you very much for your assistance and time.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @DedInc,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @DedInc,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
