### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by da-h** [pypi/support#5092]
### PyPI Username

da-h

### Reason for request

Hi team,

Unfortunately, I cannot apply any changes to my account anymore, because I forgot to verify my primary e-mail address, which I lost access to.
Is there any possibility of changing the primary e-mail address? 

**In summary**:
- The e-mail address in use was my previous work e-mail address that does not exist anymore.
- The e-mail has not been verified.
- I did not setup 2FA.
- But I do have access using the password + email method.

The repositories under that account do have secondary accounts attached (da-h-pybison-bot, da-h-miniflask-bot) that I use from within Github actions for publication.
I did want to transition today to "trusted publishers" instead, and noticed that my primary account is locked.

In case legitimization is needed to verify that my name matches the primary e-mail address, please let me know.

Best,
*da-h*

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @da-h,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/5092). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @da-h,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @da-h,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
