### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sidd6p** [pypi/support#5097]
### PyPI Username

siddp6

### Reason for request

MFA is not working
Lost the recovery key

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @sidd6p,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by sidd6p** [comment]
Hi @Thespi-Brain 

Thank you so much for helping me out.
I have already replied to the email. Kindly let me know if you need anything else from my end.

**Comment by Thespi-Brain** [comment]
Hi @sidd6p,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by sidd6p** [comment]
Hello @Thespi-Brain ,

Thank you for assisting me with this. I have reset my password, am now able to access my account, and have saved the details correctly this time :)  . Thanks a lot, and I hope not to trouble you with this in the future. Have a lovely day.
