### ISSUE TITLE
File Limit Request: groupdocs-conversion-net - 300 MiB

### ISSUE THREAD

**Issue by vladimir-litvinchik** [pypi/support#5100]
### Project URL

https://pypi.org/project/groupdocs-conversion-net/

### Does this project already exist?

- [x] Yes

### New Limit

300

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

It's the first official release of the GroupDocs.Conversion library (Aspose Pty)

https://products.groupdocs.com/conversion/python-net/
https://releases.groupdocs.com/conversion/python-net/

### Reasons for the request

The package includes the necessary dlls that are essential for the core functionality of our package.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @vladimir-litvinchik :wave:
I've set the upload limit for `groupdocs-conversion-net` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:

**Comment by vladimir-litvinchik** [comment]
@cmaureir 

Sure, thanks!
