### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jlowpsc** [pypi/support#5109]
### PyPI Username

janice_low

### Reason for request

my email address is incorrect, and there is no way to fix it, or add a new one.
it should be janice.low@pscconsulting.com, not jaince.low

Thank you.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @jlowpsc,

I have updated the primary email address on your Test.PyPI account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
