### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bipsec** [pypi/support#5110]
### PyPI Username

(bipsec) bip.sec22@gmail.com

### Reason for request

# I have lost the authenticator access as well as my recovery code due to the sudden crash of my laptop. I need to upgrade my PyPI module and upload a new module as soon as possible. Please let me know how should I proceed.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @bipsec,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by bipsec** [comment]
Thank you so much. I have reponded according to the instructions.

Regards,
Biplab (@bipsec )

**Comment by bipsec** [comment]
Hello @Thespi-Brain 

I hope you are doing well. I would like to request to get any update on this issue. As I have submitted all the necessary details and it's been a week now. Please let me know if you need any more information. I look forward to hearing from you soon.

Regards,
Biplab

**Comment by bipsec** [comment]
Hello @Thespi-Brain 

I hope you are well. It's been 3 weeks and I did not receive any update. I would like to request you to resolve the issue and let me know if you need any more information about the verification process. I am badly in need of getting the access. I hope you will take this into your consideration.

Best Regards,
Biplab

**Comment by Thespi-Brain** [comment]
Hi @bipsec,

I did not receive a confirmation email from you regarding the next steps for account verification. Did you send an email to support@pypi.org? Thanks

**Comment by Thespi-Brain** [comment]
Hi @bipsec,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
