### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dirkpetersen** [pypi/support#5111]
### PyPI Username

`dirkpetersen`

### Reason for request

I lost access to that email address (which was petersen@fredhutch.org or petersen@fhcrc.org)

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @dirkpetersen,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/5111). We will proceed from there. Thanks!

**Comment by dirkpetersen** [comment]
Thanks, i sent the email

**Comment by Thespi-Brain** [comment]
Hi @dirkpetersen,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by dirkpetersen** [comment]
Thanks much. I have replied but needed to push to a different repos (dirkpetersen/power-of-defaults) than the suggested one as I no longer have access to lf-backup

**Comment by Thespi-Brain** [comment]
Hi @dirkpetersen,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
