### ISSUE TITLE
PEP 541 Request: openmpi

### ISSUE THREAD

**Issue by dalcinl** [pypi/support#5112]
### Project to be claimed

`openmpi`: https://pypi.org/project/openmpi

### Your PyPI username

`dalcinl`: https://pypi.org/user/dalcinl

### Reasons for the request

I'm the owner/maintainer of many PyPI packages related to MPI, in particular https://pypi.org/project/mpi4py/
I'm planning to upload PyPI packages for both MPICH and Open MPI, which are implementation of the MPI specification.
All the code required to generate the mpich and openmpi wheels is hosted here: https://github.com/mpi4py/mpi-publish

The "openmpi" entry in PyPI is already claimed. However, the package is actually empty, and the upload was done (as stated in the description) to prevent dependency confusion attacks.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

AFAICT, there is no public repository for the dummy package that is already uploaded 
The source code with build scripts for what I plan to upload is here: https://github.com/mpi4py/mpi-publish
Preview wheels are hosted here: https://anaconda.org/mpi4py/openmpi, although I'm planning to eventually upload fresh builds to PyPI.

### Contact and additional research

I contacted [research@cycode.com](mailto:research@cycode.com) stating my interest in taking ownership of the "openmpi" entry, but they have not replied so far. This email address is not mentioned in the package, but in other similar-looking dummy packages uploaded by the same PyPI user.

The core project for which I'm planning to maintain wheels is https://www.open-mpi.org/.
The GitHub repository is https://github.com/open-mpi/ompi.

**Comment by leofang** [comment]
@elad-pticha Are you the Cycode project developer and the owner of the mentioned PyPI project?

**Comment by elad-pticha** [comment]
Hey!

Yes we are, we claimed this project in order to prevent dependency
confusion attacks.

Should this Project be transferred to another owner?

**Comment by leofang** [comment]
Great, thanks for speedy response @elad-pticha! Could you kindly transfer ownership to the mpi4py maintainer @dalcinl (same ID on PyPI) or grant admin access to him, so that Lisandro can take over the maintenance of this package in collaboration with the MPI community?

**Comment by elad-pticha** [comment]
We just replied to him also.
Is this validated and confirmed that he is the true maintainer of this
package?

We will happily transfer the ownership!

Thank you!

**Comment by dalcinl** [comment]
@elad-pticha I'm not actually a develper/maintainer of the upstream project, although I'm an occasional contributor, you can quickly check history yourself https://github.com/open-mpi/ompi/issues?q=author%3Adalcinl. My actual role would be that of packager, taking care of downstream wheel builds for use within Python, pretty much as I already do for the conda-forge organization: https://github.com/conda-forge/openmpi-feedstock
