### ISSUE TITLE
File Limit Request: groupdocs-signature-net - 300 MiB

### ISSUE THREAD

**Issue by yuriy-mazurchuk** [pypi/support#5113]
### Project URL

https://pypi.org/project/groupdocs-signature-net/

### Does this project already exist?

- [x] Yes

### New Limit

300

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

It's the first official release of the GroupDocs.Comparison library (Aspose Pty)
https://products-qa.groupdocs.com/signature/python-net/

### Reasons for the request

The package includes the necessary DLL files which use neural networks that are essential for the core functionality of our package.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @yuriy-mazurchuk :wave:
I've set the upload limit for `groupdocs-signature-net` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:
