### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dbaxa** [pypi/support#5119]
### PyPI Username

dblack

### Reason for request

Hi, a while back I managed to reset my yubikey and I also seem to have misplaced my pypi recover codes. I have my old 2020 pypi recovery codes but not the newer set that I re/generated in 2022.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi, a while back I managed to reset my yubikey and I also seem to have misplaced my pypi recover codes. I have my old 2020 pypi recovery codes but not the newer set that I re/generated in 2022.
-----BEGIN PGP SIGNATURE-----

iHUEARYKAB0WIQTXR/K1wbroyg3QRnl1pvQpiBtiNgUCZzXS0wAKCRB1pvQpiBti
NoQTAQD87XeeZkIUit5L8IR45+5/ma64NPeyddjXbEjTl568hgEAnG1ezI4Mjmgc
aNreF8GWPiW8CFoAOK7S2pCI+y9tNAU=
=Yo1j
-----END PGP SIGNATURE-----
```

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @dbaxa,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @dbaxa,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
