### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by YakshHaranwala** [pypi/support#5129]
### PyPI Username

`MobilityLab`

### Reason for request

Hello!

I have lost my access to my email address as it was being previously created under a research lab that I was a part of during my university days and we only published 1 package called PTRAIL. However, the lab has since disbanded and I am the sole maintainer of the package and none of us have access to that email.

Can we please associate the account with email: yjharanwala@mun.ca?

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @YakshHaranwala,

Thanks for sending over your preferred email in this issue. However, we do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/5129). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @YakshHaranwala,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @YakshHaranwala,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
