### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Skumarr53** [pypi/support#5130]
### PyPI Username

skumarr53

### Reason for request

I attempted to log in to my account, but I am prompted to enter a TOTP code for two-factor authentication. However, I have not yet set up 2FA, and I am unable to access my account without this code. This has created a situation where I cannot log in or enable two-factor authentication.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Skumarr53,

I took at a look into your account and the logs did show that you had set up 2FA earlier in the year. But not to worry, your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
