### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by frymanofer** [pypi/support#5141]
### PyPI Username

frymanofer@gmail.com

### Reason for request

There are two issues:
1. I have no idea which application I used for authentication. I thought that the application will notify me when I try to login not vice versa. So I will do it again and this time I will remember.
2. When I try to access using my tokens it invalidates the session and I cannot login to my account at all.
Please help.

I have clicked the "I never generated or have lost access to the recovery codes for my account" however it is not true. I did generate and have recovery codes however when I try to use them the session gets invalidated .

Many thanks,
Ofer

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @frymanofer,

Your account was found to not be in compliance with our [Acceptable Use Policy](https://policies.python.org/pypi.org/Acceptable-Use-Policy/). If you think this is an error, please contact [admin@pypi.org](mailto:admin@pypi.org). Thanks.
