### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cako** [pypi/support#5147]
### PyPI Username

`cako`

### Reason for request

I am not able to recover my TestPyPI account. I simply do not get the verification email, not matter how many times I try to get it. It also doesn't show up in my Spam folder. I have tried to register other account and none of them are getting verification emails from PyPI.

I have another account with the same username on PyPI and I have been able to reset my password and verify my email.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @cako,

I took a look into your Test.PyPI account and it looks like you were able to login and verify the primary email address on the account. Are you still having trouble? Let me know and we will go from there, thanks.
