### ISSUE TITLE
PEP 541 Request: affinity

### ISSUE THREAD

**Issue by liquidcarbon** [pypi/support#5148]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/affinity

### Your PyPI username

`USER_NAME`: https://pypi.org/user/liquidcarbon

### Reasons for the request

This project was published in 2006 and saw no updates.

My project https://github.com/liquidcarbon/affinity/ is in active use and ready to be published to PyPI, which would greatly help its distribution.

The name matters: affinity is about building well-documented datasets from vector data; the term is used in linear algebra and many branches of science.  The term indicates a similarity of characteristics suggesting a relationship.  It's associated with databases, binding, unity.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

my project: https://github.com/liquidcarbon/affinity/
not clear where the original is

### Contact and additional research

Address not found
Your message wasn't delivered to sidnei@enfoldsystems.com because the address couldn't be found, or is unable to receive mail.
The response from the remote server was:
550 5.4.1 Recipient address rejected: Access denied. [CO1PEPF000042AC.namprd03.prod.outlook.com 2024-11-20T03:50:09.746Z 08DD06A36373E43D]

---------- Forwarded message ----------
From: Alexander Kislukhin <...@gmail.com>
To: sidnei@enfoldsystems.com
Cc: 
Bcc: 
Date: Tue, 19 Nov 2024 20:49:55 -0700
Subject: test for pypi
test

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by liquidcarbon** [comment]
ping?

**Comment by sidnei** [comment]
Hi! I'm the original author of the affinity package. I have no intent on maintaining it so unless this would cause confusion to anybody that has previously downloaded the package I'm up for giving away ownership.

**Comment by liquidcarbon** [comment]
@sidnei thanks for your response!  If you're up for it, simply transfer the project to me (liquidcarbon) on PyPI.org, and we can close this one.  Appreciate it!
