### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by TanujairamV** [pypi/support#5154]
### PyPI Username

Tanujairam.V

### Reason for request

I have entered the wrong email which I am unable to verify.
The email I have entered is tanujairam@gmail.com
The email I need to add is tanujairam.v@gmail.com

I request you to kindly help me to recover my account.
This is my first Pypi account 🥲

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @TanujairamV,

It looks like you already have another PyPI account with the correct email address. Would you like to add an alternate email address to your **Tanujairam.V** account so that you can login and delete it if you wish? If so, please send an email to support@pypi.org. Thanks!

**Comment by TanujairamV** [comment]
I would like to delete the account in which the username associated with Tanujairam.V as you said I need a alternate email to delete my account that account here it is tanujairam.edu@gmal.com

**Comment by TanujairamV** [comment]
Email sent sir Thank you 👍

**Comment by Thespi-Brain** [comment]
Hi @TanujairamV,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
