### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gawbul** [pypi/support#5163]
### PyPI Username

gawbul

### Reason for request

Lost 2FA authentication app or security token

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @gawbul,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by gawbul** [comment]
Thanks, @Thespi-Brain. I have received the email. The repository for the PyPi project in question has moved to my personal GitHub, however, so I can't create the required branch just yet. I'm trying to discuss with the new owners of the pyOpenSci project, to see if I can get things sorted 🤞

**Comment by gawbul** [comment]
I've managed to get things sorted with the pyOpenSci team and the branch now exists in the relevant repository.

**Comment by Thespi-Brain** [comment]
Hi @gawbul,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
