### ISSUE TITLE
Project Limit Request: docling-parse - 200 GB

### ISSUE THREAD

**Issue by dolfim-ibm** [pypi/support#5164]
### Project URL

https://pypi.org/project/docling-parse

### Does this project already exist?

- [x] Yes

### New limit

200

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

The project exists since August and we reached the current 10GB limit.
This project contains binary compiled wheels for multiple architectures and python versions, hence the size.
We expect more releases in the future, hence the requested 200GB new quota.

### How large is each release?

˜950 MB total

24MB sdist
10 Windows built, 24MB each
10 Linux builds, 23MB each
20 Mac builds, 22MB each

### How frequently do you make a release?

On average, 2 per week.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by dolfim-ibm** [comment]
Is there any update for this request?

On our side we just managed to reduce a bit the file size for new releases, i.e. reducing the mac builds.

**Comment by cmaureir** [comment]
Hello @dolfim-ibm :wave:
It seems that the adoption of Python's Stable API https://docs.python.org/3/c-api/stable.html will reduce significantly the amount of wheels you release. Have you considered?

It's very rare to give an increase that goes beyond 40-50G per projects, and that's usually for projects that have been around for a long time and have been getting project increases time to time, a jump to 200G is too much.

**Comment by dolfim-ibm** [comment]
Hi @cmaureir, thanks for looking at our case. It would be great if we could start with a lower increase, e.g. 40GB. We already had to (sadly) delete previous releases because of the current quota.

We know about Python's Stable API, but our initial search found that pybind11 cannot use it effectively. We will anyway continue to look for a solution to lower the single of a single release.

**Comment by cmaureir** [comment]
Understood.
I have set the project limit to 40G on PyPI @dolfim-ibm in the meantime, I hope you can find ways to reduce the wheels
or distribute the binaries within each wheel in a different way.
Have a nice week 🐍
