### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gidden** [pypi/support#5165]
### PyPI Username

`gidden`

### Reason for request

I do not have access to my current primary email address on PyPi and would like to change it

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Closing as user has found alternate resolution
