### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by AshkanFeyzollahi** [pypi/support#5166]
### PyPI Username

shijian-wow (VenzTechnolo)

### Reason for request

I want to remove my Gmail account from this pypi account, because i want to add it to my other pypi account

Gmail account:
ashkanfeyzollahi@gmail.com

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @AshkanFeyzollahi,

Please contact support@pypi.org with an alternate email address that you would like your **shijian-wow** account to be associated with and please reference this link (https://github.com/pypi/support/issues/5166). We will proceed from there. Thanks!

**Comment by AshkanFeyzollahi** [comment]
Hey @Thespi-Brain,

I sent an email to the email address support@pypi.org with the email address mrslayest.acc@gmail.com. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @AshkanFeyzollahi,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
