### ISSUE TITLE
Project Limit Request: ncert_learn - 20 GB

### ISSUE THREAD

**Issue by hejhdiss** [pypi/support#5171]
### Project URL

https://pypi.org/project/ncert-learn

### Does this project already exist?

- [x] Yes

### New limit

20 GB

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

A Python Module for NCERT Class 12 Computer Science - Learn Python and MySQL with ease!

### How large is each release?

~600MB

### How frequently do you make a release?

When I Got Free Times.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @hejhdiss :wave:
I've set the upload limit for `ncert_learn` to 20 GB on PyPI, but please remember that PyPI is not a repository to have class material on packages, but a way of distributing modules for the python ecosystem. Please consider using another service to host class material for future inquires.
Have a nice week :snake:
