### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gabrielg5** [pypi/support#5173]
### PyPI Username

`coresecurity`

### Reason for request

Hi,
Gabriel Gonzalez, software development manager at Fortra here

Trying to recover control of `coresecurity` pypi account, I have control over oss@coresecurity.com but have lost access to oss@secureauth.com - which is the principal email for the account -, so can't make any changes there

Is there a way I could move the _principal_ flag to the other account?
Thanks

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @gabrielg5,

Yes, you can update the primary email address on the account. Since we do have an account verification as due diligence before we can update your email, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/5173). We will proceed from there. Thanks!

**Comment by gabrielg5** [comment]
Hi @Thespi-Brain, thanks!

Sent email. Waiting for support then

Thank you

**Comment by Thespi-Brain** [comment]
Hi @gabrielg5,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @gabrielg5,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
