### ISSUE TITLE
Project Limit Request: quarchpy- 20 GiB

### ISSUE THREAD

**Issue by SBQuarch** [pypi/support#5175]
### Project URL

https://pypi.org/project/quarchpy/

### Does this project already exist?

- [x] Yes

### New limit

20gb

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

QuarchPy is a python package designed to provide an easy-to-use API which will work seamlessly over any connection option: USB, Serial and LAN. With it, you can create your own scripts for controlling Quarch devices - without having to worry about the low-level code involved with communication.

The package contains all prerequisites needed as a single PyPI project, which can be installed from the python online repository using PIP. This makes it easy to install and update, while also providing you with full access to the source code if you want to make changes or additions.

QuarchPy can also communicate to the device via QIS (Quarch Instrument Server), QPS (Quarch Power Studio), or simply using Python scripts. Both QIS and QPS are included with the QuarchPy Package - they are ready to use (Java and drivers may also be needed).

It is increasing due to java libs being packaged with it for QPS and QIS.

We have stripped back the java libs to only the necessary libs, and we only ship one jar that works with windows, linux and mac OS.

### How large is each release?

Currently each release is 300mb we have requested for it to be 500mb as we would like to use a different distro of java.
https://github.com/pypi/support/issues/5174

We have a 2 java applications one uses javafx for which we have one jar but libs for each os.

### How frequently do you make a release?

One public release every 2 months.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Handled in https://github.com/pypi/support/issues/4159 please don't open more than 1 issue per request.
