### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by drgroot** [pypi/support#5181]
### PyPI Username

servc

### Reason for request

I have lost email and 2FA. I still have the tokens and currently publishing to this repo
https://github.com/serv-c/servc-python

which is this pypi location:
https://pypi.org/project/servc/

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @drgroot,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/5181). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @drgroot,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
