### ISSUE TITLE
Project Limit Request: tach - 50 GB

### ISSUE THREAD

**Issue by emdoyle** [pypi/support#5184]
### Project URL

https://pypi.org/project/tach/

### Does this project already exist?

- [x] Yes

### New limit

50GB

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

This project is a linting tool for modular architecture and has been active since April 2024. It has 1.25M+ installs through PyPI so far, and ~1.2k stars on GitHub.

It is developed by Gauge, backed by Y Combinator.

We expect that releases will decrease in size in the future after migrating all inner logic to Rust and eliminating the dependence on the Python ABI, thus going from 90+ wheels down to ~10 wheels. This increase gives us a bit of breathing room until then.

### How large is each release?

~280MB per release

92 wheels due to cross-matrix of Python ABI and OS/architecture (3.7-3.13, Linux/Mac/Windows, various CPU arch)
~3MB each wheel

### How frequently do you make a release?

Roughly 3-5 times a week.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @emdoyle :wave:
Considering your request and that you are on 10G for the project limit, I was about to consider abi3 wheels, but can see you also implemented that.

Does the increase is still relevant? and considering that you reduced the amount of wheels, maybe a lower increase would be good for you. Does 30 G sounds like a good new limit? I rarely do a 5x size bump on projects, so I'd like to do a smaller increase if possible.

Let me know!

**Comment by emdoyle** [comment]
> Hello [@emdoyle](https://github.com/emdoyle) 👋 Considering your request and that you are on 10G for the project limit, I was about to consider abi3 wheels, but can see you also implemented that.
> 
> Does the increase is still relevant? and considering that you reduced the amount of wheels, maybe a lower increase would be good for you. Does 30 G sounds like a good new limit? I rarely do a 5x size bump on projects, so I'd like to do a smaller increase if possible.
> 
> Let me know!

Hi @cmaureir ! Thanks for your response.

Yes, 30GB would be great for now. The abi3 wheels have made a dramatic impact on our release size, but we do anticipate shipping releases often.

Please let me know if you need anything else from us in the meantime!
