### ISSUE TITLE
PEP 541 Request: roocs-utils, clisops, daops

### ISSUE THREAD

**Issue by Zeitsperre** [pypi/support#5185]
### Project to be claimed

`roocs-utils`: https://test.pypi.org/project/roocs-utils `clisops`: https://test.pypi.org/project/clisops `daops`: https://test.pypi.org/project/daops

### Your PyPI username

`Zeitsperre`: https://pypi.org/user/Zeitsperre

### Reasons for the request

I am an admin for the [`ROOCS`](https://github.com/roocs) project and was hoping to gain access to the following **TestPyPI** projects:
- clisops
- daops
- roocs-utils

I actively maintain the `clisops` and `roocs-utils` projects and have done so for years (I have contributed to the `daops` project as well). Originally, a maintainer I collaborated with (@ellesmith88) created these entries in TestPyPI, but never shared or transferred ownership before she left the organization. I would like to have these projects transferred over to me so that I can actively maintain them.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/roocs/clisops
https://github.com/roocs/daops
https://github.com/roocs/roocs-utils

### Contact and additional research

On November 26, 2024, I attempted to email @ellesmith88's listed address (eleanor.smith@stfc.ac.uk) the following message:

> Hi Elle,
> 
> I'm not sure if this email is still active for you. Hope you're well.
> 
> I'm writing to ask if it would be possible to gain access to any ROOCS projects that you retain sole ownership over, specifically the TestPyPI entries for:
> 
>     clisops
>     daops
>     roocs-utils
>
> If it were possible to share ownership with me (@zeistperre), that would be great. Carsten (CC'd) and I are trying to perform a major refactoring of these projects, and it would be good to reestablish control over those projects.
> 
> All the best

However, the email has long since been deactivated:
![Image](https://github.com/user-attachments/assets/da3939b2-c5c6-4c64-92bc-206cded40468)
(translation: "We did not find eleanor.smith on sftc.ac.uk")

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by ellesmith88** [comment]
@Zeitsperre I've just seen this, sorry it wasn't transferred. I've tried to gain access to my account to transfer the projects but I don't know the password and obviously can't access the email address to reset the password. I can open an account recovery request, but since I don't need access hopefully they can just be transferred to you.

**Comment by Zeitsperre** [comment]
Hi @ellesmith88 happy to hear from you! Hope things are going well!

I think the best way forward would be to open an account recovery request. Perhaps there's something they can do if you can explain to them that your email was associated with a job post that you left a few years ago. There must be some other way to authenticate you.

The only projects you were maintaining were associated with ROOCS, so it works fine for me if transferring ownership of everything on pypi and testpypi is simpler.

Thanks again for reaching out!

**Comment by ellesmith88** [comment]
@Zeitsperre No problem - I've opened an account recovery request so will keep an eye on that and hopefully get this sorted out. Hope all is well with you too!

**Comment by ellesmith88** [comment]
@Zeitsperre I've now got access to my account and have invited you to be an owner for all those packages. Once you have access, I can remove myself or you can remove me from them.

**Comment by Zeitsperre** [comment]
@ellesmith88 That's great! I'll keep you there for now until I can add @cehbrecht as a secondary owner. Thanks again and happy holidays!
