### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vanshb03** [pypi/support#5202]
### PyPI Username

vanshb03

### Reason for request

- Lost 2FA auth access on app due to phone reset and lost access to recovery codes

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @vanshb03,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
