### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by GEOEGII555** [pypi/support#5227]
### PyPI Username

GEOEGII555

### Reason for request

Lost 2FA authentication app or security token

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @GEOEGII555,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by GEOEGII555** [comment]
I followed the instructions in the email. Thanks.

чт, 5 дек. 2024 г., 21:32 thespibrain ***@***.***>:

**Comment by Thespi-Brain** [comment]
Hi @GEOEGII555,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
