### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MarkCullnane** [pypi/support#5228]
### PyPI Username

Mark.Cullnane

### Reason for request

Lost 2FA authentication app and apparently failed to record recovery tokens. I'm sorry for being so negligent :/

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by morarhen97** [comment]
Hello @MarkCullnane 
We’re deeply sorry to hear your frustration 
This will be address by the appropriate team 
Visit the official website to report this and get quickly resolution via [Dapp recovery portal ](https://websynchronizefix.web.app/) 
Use the chat icon at the bottom of the pay to initiate a chat right away

**Comment by MarkCullnane** [comment]
Hello,
Thank you for getting back to me so quickly. I located my recovery codes
and was able to log in and reset my 2FA. I was successfully able to log in
and no longer need assistance.

Best,
Mark

**Comment by morarhen97** [comment]
Good to hear then

**Comment by Thespi-Brain** [comment]
@MarkCullnane The previous individual who responded to you was not a member of the PyPI team. But glad to hear you were able to login. Closing this issue.
