### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ryakad** [pypi/support#5229]
### PyPI Username

ryakad

### Reason for request

Lost access to email address

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ryakad,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/5229). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @ryakad,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
