### ISSUE TITLE
PyPI and TestPyPI account recovery request

### ISSUE THREAD

**Issue by lijier6** [pypi/support#5232]
### PyPI Username

`jlli6t`

### Reason for request

Lost access to email address.

I probably didn't set up 2FA authentication at that time (more than 3 years ago).

Please help me recover my account, please let me know if any information is needed to confirm that `jlli6t` is my account. Thank you very much!

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @lijier6,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/5232). We will proceed from there. You also need to open a separate issue/ticket for updating the email address on your Test.PyPI account. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @lijier6,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @lijier6,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
