### ISSUE TITLE
PEP 541 Request: tempo

### ISSUE THREAD

**Issue by emeryberger** [pypi/support#5244]
This project has been abandoned since September 2011. The homepage link is dead. The project description is "unknown." It only supports Python 2.6. The maintainer's last contribution to any PyPi project was in 2016. Searching for the project "tempo" on OpenStack.org turns up no matches.

**Comment by miketheman** [comment]
Please see the https://github.com/pypi/support/issues/new?template=pep541-request.yml template for the appropriate form and details for the request.
