### ISSUE TITLE
Project Limit Request: amalgam-lang - 20 GB

### ISSUE THREAD

**Issue by apbassett** [pypi/support#5246]
### Project URL

https://pypi.org/project/amalgam-lang/

### Does this project already exist?

- [x] Yes

### New limit

20

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

This project is a Python [wrapper ](https://github.com/howsoai/amalgam-lang-py/)for the [Amalgam](https://github.com/howsoai/amalgam) programming language developed by [Howso](https://www.howso.com/). We open-sourced the project in September 2023, with our first PyPi release dating to September 12, 2023.

While we have started pruning older releases that are unlikely to see use at this point, we expect the total project size to continue to grow steadily as we continue making new releases.

### How large is each release?

Each release is approximately 250mb. We do not expect our releases to decrease in size, but it is possible that, as we support more platforms, we may _sparingly_ add other .whl files of ~5-50mb in size in the future, though there are no current plans to do so. We currently support 6 OS/architecture combinations, where each .whl is between ~5-50mb (not including the ~67mb platform-agnostic `none-any` .whl and the source distribution tarball of a similar size).

### How frequently do you make a release?

Roughly 2x/week.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @apbassett :wave:
I've set the project limit for `amalgam-lang` to 20 GB on PyPI. Please be mindful of the frequency of releases at that wheel size.
Have a nice week 🐍
