### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by chineseluo** [pypi/support#5248]
### PyPI Username

chineseluo

### Reason for request

I lost 2FA authentication app and recover codes,I need to restore my account permissions through email,thank you

### Recovery Codes

- [ ] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by chineseluo** [comment]
I really need your help. I have a new open source library that is about to be released, but it is currently blocked and cannot be launched in a timely manner

**Comment by Thespi-Brain** [comment]
Hi @chineseluo,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
