### ISSUE TITLE
File Limit Request: Open WebUI - 200 MB

### ISSUE THREAD

**Issue by tjbck** [pypi/support#5250]
### Project URL

https://pypi.org/project/open-webui

### Does this project already exist?

- [x] Yes

### New Limit

200

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

Open WebUI is a self-hosted, extensible, and offline-friendly AI interface supporting multiple LLM runners like Ollama and OpenAI-compatible APIs. It is user-friendly, feature-rich, and focused on operating entirely offline.

The project is actively maintained, with continuous efforts to minimize PyPI release sizes by removing unnecessary dependencies and bundling only essential components. While example data and modules may be included for seamless setup, the software remains as lightweight as possible.

To support its robust AI functionality, the project requires a file limit of 200 MB for PyPI releases.

### Reasons for the request

The additional file size limit of 200 MB is requested due to the need to package essential dependencies, model support files, and potentially example data required for Open WebUI to function seamlessly. These components are critical for providing out-of-the-box usability and ensuring compatibility with various LLM runners like Ollama and OpenAI-compatible APIs.

While efforts are made to minimize release sizes, the nature of the project—supporting advanced AI functionality, user extensibility, and offline operation—requires bundling certain assets that may push the total release size near this limit. Future updates may see moderate increases in size as new features, optimizations, and support for additional LLM runners are introduced, but size management will remain a priority.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by i0ntempest** [comment]
To whoever is reviewing this: open webui is a rather big project that really needs more space. Hope this can be approved soon.

**Comment by hashms0a** [comment]
Unable to install the new version of Open WebUI (v0.4.8) in pip, Open-Webui reached the pip package 100MB limit.

**Comment by mazvi** [comment]
Please update on PIP https://pypi.org/project/open-webui/

**Comment by peuportier** [comment]
Dear Friend,

We hope this message finds you well. We wanted to kindly inquire if it would be possible to update the open-webui package on PyPI to include version 0.48. This update would greatly benefit the community and significantly support our ongoing work.

We understand you may have a busy schedule, and we truly appreciate all the effort and support you’ve provided so far. Thank you in advance for considering this request, and we remain grateful for your contributions.

Warm regards,

**Comment by c-hoffmann** [comment]
Dear PyPi support,
open-webui is the highest rated chatbot UI on GitHub. It is updated frequently, often multiple times per week. Please take care of this issue soon, as it concerns a great number of users, waiting for this to be resolved.
Thank you and have a great holiday season!

**Comment by medul6** [comment]
Hello PyPI maintainers,
I also need open-webui to be updated thru pip and am stuck at version 0.4.7. open-webui is a fantastic way of accessing open source llm models with a nice interface. Please raise the pip package limit. Thank for considering. Have a merry christmas!

**Comment by ramazangur** [comment]
Hello @Thespi-Brain, could you please help us here?

**Comment by cmaureir** [comment]
Hello @tjbck :wave:
I've set the upload limit for `open-webui` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:

**Comment by dannys-platformsh** [comment]
Hi pypi - this is has broken our automation to stay on latest - please can you allow more space for open-webui updates
