### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by D-inspiration** [pypi/support#5255]
### PyPI Username

_D-inspiration_

### Reason for request

My main issue is verifying my email as I still have access to the email, but u dint receive the verification mail request 

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @D-inspiration, 

I took a look into your account and it seems like the verification emails for your test.pypi account were sent out. Are you still having trouble regarding this? Let me know!

**Comment by D-inspiration** [comment]
I've received the mails thank you very much

**Comment by Thespi-Brain** [comment]
Wonderful to hear that! Closing issue.
