### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JonasScharpf** [pypi/support#5258]
### PyPI Username

`checkmk`

### Reason for request

Dear PyPI support,
I've used the wrong mail address during creation of the **Test PyPI** account. 
The verification mail was thereby never received by us and it is of course not possible to change the mail address without verification.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @JonasScharpf,

Please contact support@pypi.org with an email address that you would like your Test.PyPI account to be associated with and please reference this link (https://github.com/pypi/support/issues/5258). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @JonasScharpf,

I have updated the primary email address on the Test.PyPI  account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
