### ISSUE TITLE
Account recovery request - Can't receive email

### ISSUE THREAD

**Issue by Anttonii** [pypi/support#5259]
### PyPI Username

Anttonii

### Reason for request

Hi

I've been trying to create a test PYPI account but I have never received a verification email despite attempting to resend it 3 times.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Anttonii,

I took a look into your Test.PyPI account and it shows that the verification emails were eventually sent out. Are you still having trouble? Let me know!

**Comment by Anttonii** [comment]
> Hi [@Anttonii](https://github.com/Anttonii),
> 
> I took a look into your Test.PyPI account and it shows that the verification emails were eventually sent out. Are you still having trouble? Let me know!

Hi

not long after sending this issue the emails came through. I'm sorry for the inconvenience.

**Comment by Thespi-Brain** [comment]
No worries, glad your issue is resolved.
