### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sysucai2024** [pypi/support#5260]
### PyPI Username

sysucai

### Reason for request

Lost 2FA authentication app or security token.
I lost my 2fa device.
So i  Login using recovery codes, but when i commit, not work: >>ErrorSession invalidated
Now I have no other recovery codes (all is used)。I don't know how to do next. 
please help me.
account:  sysucai

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @sysucai2024,

Your account was found to not be in compliance with our [Acceptable Use Policy](https://policies.python.org/pypi.org/Acceptable-Use-Policy/) and is frozen. If you think this is an error, please contact [admin@pypi.org](mailto:admin@pypi.org). Thanks.
