### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dreamerhyde** [pypi/support#5265]
### PyPI Username

albert.liu

### Reason for request

Hello Pypi team!

My account cannot log in through 2FA because my 2FA app was not successfully transferred when I switched phones. 
Could your team assist me in recovering my account and temporarily disabling 2FA for me?

Albert

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @dreamerhyde,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
