### ISSUE TITLE
File Limit Request: cvcuda - 200 MiB

### ISSUE THREAD

**Issue by milesp-nvidia** [pypi/support#5267]
### Project URL

https://pypi.org/project/cvcuda

### Does this project already exist?

- [x] Yes

### New Limit

200 MiB

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

cvcuda is the PyPi project corresponding the the CV-CUDA GitHub project located here https://github.com/CVCUDA/CV-CUDA/. With CV-CUDA release v0.13.0, we begin publishing our wheels to PyPi.

### Reasons for the request

Our fully built python wheels, with all required libraries packaged in, end up getting to a minimum size of 100 MiB and a max size of 200 MiB at the moment. 

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @milesp-nvidia :wave:
I've set the upload limit for `cvcuda` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :snake:

**Comment by milesp-nvidia** [comment]
Hi @cmaureir, I have two more requests that were connected to this one for a size limit increase to 200 MiB.
- https://github.com/pypi/support/issues/5336
- https://github.com/pypi/support/issues/5337
