### ISSUE TITLE
Wrong email correction request

### ISSUE THREAD

**Issue by TokynBlast** [pypi/support#5279]
### PyPI Username

TokynBlast

### Reason for request

I don't have access to the email I put on my account.
It had a typo, and doesn't exist.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @TokynBlast,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
