### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by benopp99** [pypi/support#5280]
### PyPI Username

benopp99

### Reason for request

I made an account about 3 months ago, and now I cannot find it on google authenticator and I cannot find my recovery codes.  If you can send me new recovery codes, I should be able to recover my account.  

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @benopp99,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
