### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vovchic17** [pypi/support#5281]
### PyPI Username

VoVcHiC

### Reason for request

My PyPI account was accessed by another person and the attacker added malicious code to my [project](https://github.com/vovchic17/aiocpa).
Now the project is deleted and I can't log into my account due to this error.
How do I remove the malicious version of the project and continue its development?

![Image](https://github.com/user-attachments/assets/77e4fabe-b8e9-4dd7-8d20-9175fb988780)

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @vovchic17,

Your account was found to not be in compliance with our [Acceptable Use Policy](https://policies.python.org/pypi.org/Acceptable-Use-Policy/). If you think this is an error, please contact [admin@pypi.org](mailto:admin@pypi.org). Thanks.

**Comment by vovchic17** [comment]
Hello, it's been a month, I've contacted [admin@pypi.org](mailto:admin@pypi.org) but didn't receive any response. How do I restore access to my account?
