### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vladislavkruglikov** [pypi/support#5285]
### PyPI Username

vladislavkruglikov

### Reason for request

Lost 2FA authentication app and recovery keys

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by vladislavkruglikov** [comment]
Found recovery keys

**Comment by Thespi-Brain** [comment]
@vladislavkruglikov wonderful. Glad to hear you resolved the issue on your own.
