### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by xyin-anl** [pypi/support#5287]
### PyPI Username

shawnyin

### Reason for request

Hi I am a new developer and am not familiar with PyPI's platform, I generated the two factor authentication QR code and forgot to scan it using a device and I did not save the recovery codes either, now I don't have access to the account. The account is empty, can I recover it or I have to register a new account for this. Thank you.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @xyin-anl,

Your 2FA and recovery codes have been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
