### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by evallesp** [pypi/support#5290]
### PyPI Username

'evallesp'

### Reason for request

I've written wrong the email address and I don't see the way to fix that, so I cannot verify my account

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @evallesp,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/5290). We will proceed from there. Thanks!

**Comment by evallesp** [comment]
Done, thanks

**Comment by Thespi-Brain** [comment]
Hi @evallesp,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
