### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by m-boschini** [pypi/support#5291]
### PyPI Username

m-boschini

### Reason for request

I cannot verify my email because during registration I accidentally made a mistake when typing it.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @m-boschini,

Is this for your test.pypi account? Please contact support@pypi.org with an email address that you would like your test.pypi account to be associated with and please reference this link (https://github.com/pypi/support/issues/5291). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @m-boschini,

I have updated the primary email address on the test.pypi account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
