### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by am486dx** [pypi/support#5307]
### PyPI Username

`usmai`

### Reason for request

I accidentally registered with the email address 'libapps.umd.edu', when it should have been 'libclas-apps@umd.edu'. Now I cannot verify the email and I don't see an option to add a new email. 

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @am486dx,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by am486dx** [comment]
Thanks so much - I was able to get everything up and running!
