### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by BastiTee** [pypi/support#5312]
### PyPI Username

'basti-tee'

### Reason for request

Lost access to email address.
But I can still log-in with my existing credentials. However I get asked to verify or add a new e-mail address. 
The latter however doesn't seem to be self-servicable.

![Image](https://github.com/user-attachments/assets/2ffaafa7-3464-41db-a27e-df4be14c156e)

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @BastiTee,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/5312). We will proceed from there. Thanks!

**Comment by BastiTee** [comment]
Hi @Thespi-Brain 
I did that already yesterday with a link to this issue. As it says "Awaiting Response", is there anything else needed?

**Comment by Thespi-Brain** [comment]
Hi @BastiTee,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @BastiTee,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
