### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by AxZeRxD** [pypi/support#5313]
### PyPI Username

mohitcodez

### Lost 2FA Authentication App or Security Token

A few days ago, I reset my PC and forgot to download a backup of my 2FA settings. I was using a Chrome extension for 2FA, and now I can't access my account.

I can provide any required information about my account, including my email or other necessary details, to regain access.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @AxZeRxD,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @AxZeRxD,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
