### ISSUE TITLE
File Limit Request: ai2-olmo - 200 MB

### ISSUE THREAD

**Issue by epwalsh** [pypi/support#5315]
### Project URL

https://pypi.org/project/ai2-olmo

### Does this project already exist?

- [x] Yes

### New Limit

200

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

This projects contains the official modeling and pretraining code for the open source OLMo family of language models. The reason for the large package size is that we include data files for evaluation tasks with the package. It's important for reproducibility that these files are bundled with the package to ensure that users have the exact versions they need at the time of reproduction.

### Reasons for the request

This will probably be the final release from this project as we're currently migrating to a new codebase. But we feel it's important for the open source community that we get this release on PyPI for ease of access.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @epwalsh :wave:
I've set the upload limit for `ai2-olmo` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice day! :snake:
