### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by prasants** [pypi/support#5316]
### PyPI Username

`prasant`

### Reason for request

I have access to recovery codes and 2FA for the pypi test account, but not for the main account. I do not recall setting one up. How can my 2FA for the main account be reset?

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @prasants,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
