### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by etodd** [pypi/support#5321]
### PyPI Username

brittsdm

### Reason for request

Our PyPi account is registered to an employee's email address who no longer works here (britt@strongdm.com).

Could you please change the primary email address to infra@strongdm.com? We can validate that one.

We do have the 2FA codes for this account.

### Recovery Codes

- [ ] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @etodd,

It looks like your email address is already set to the infra@strongdm.com. Are you still having trouble? Let me know, and we will go from there.

**Comment by etodd** [comment]
I think we got it resolved via other means, thank you!
