### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by hentai-chan** [pypi/support#5328]
### PyPI Username

hentaichan

### Reason for request

Lost 2FA authentication app or security token (because I upgraded my cell phone and made a mistake while transferring my authenticator backup)

See also: https://github.com/pypi/support/issues/2552

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @hentai-chan,

Could you please confirm what your primary email address is for your account and send it to support@pypi.org with. Please reference this link (https://github.com/pypi/support/issues/5328). We will proceed from there. Thanks!

**Comment by hentai-chan** [comment]
@Thespi-Brain done!

**Comment by Thespi-Brain** [comment]
Hi @hentai-chan,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @hentai-chan,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
