### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by alexanderivrii** [pypi/support#5329]
### PyPI Username

`alexanderivrii`

### Reason for request

Hi, 

I have recently changed both my laptop and my phone, and I have only now realized that I do not have access to my old phone's 2FA software (DuoMobile) and I do not have the recovery codes. I do remember the password I created, but this is not enough. If it helps, here is the python package https://pypi.org/project/qiskit-sat-synthesis/ that I wanted to push a new version of to PyPI.

Sincerely,
Alexander Ivrii

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @alexanderivrii,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @alexanderivrii,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
