### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by memchr** [pypi/support#5356]
### PyPI Username

`memchr`

### Reason for request

I made a typo in the domain name of my primary email address, it is currently `memchr@proton.em`, but the correct domain name should be `proton.me`. I cannot change the email address myself because, for obvious reasons, I need to verify this incorrect email address first.

I would like to correct the error, thank you.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @memchr,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
