### ISSUE TITLE
Mass name squat by user: fbasurto

### ISSUE THREAD

**Issue by WattsUp** [pypi/support#5359]
### PyPI user performing the mass project name squatting

https://pypi.org/user/fbasurto

### Additional information

fbasurto has published 12 packages on Dec 17 2024, all with the same description and files. The setup.py only differs by project name.

The github links go to https://github.com/fbasurto which has no commits or repositories.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by miketheman** [comment]
These projects have now been prohibited as malware.

**Comment by miketheman** [comment]
Please file a new name transfer request for consideration: https://github.com/pypi/support/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=pep541-request.yml
