### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Sebagabones** [pypi/support#5360]
### PyPI Username

`Sebagabones`

### Reason for request

Accidentally registered with an email address you cannot verify - i added a '.au' to my email out of habit, which was in fact not meant to be there lol

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Sebagabones,

I took a look into your account and it seems like your email address is already in the correct form. Are you still having any other login related issues? Let me know and we will go from there, thanks.

**Comment by Sebagabones** [comment]
Heya, yeah I just decided to create a different account with the correct email as it wasn't the end of the world, thanks :)
