### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by prateekt** [pypi/support#600]
Request for account recovery.

## PyPI Username

`prateekt`

---

##  Reason for request

Reason:
  - Lost 2FA authentication app or security token

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@prateekt do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: prateekt" to proceed
