### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bih** [pypi/support#718]
Request for account recovery.

## PyPI Username

`bil`

---

##  Reason for request

Lost 2FA authentication app

Reason: No idea, it's no longer showing in my 2FA authenticator app (Duo Mobile). Never had to me before

**Comment by OrkoHunter** [comment]
Hi @ewdurbin! I wonder if this is the right way to approach account recovery or should we send an email somewhere else? Thank you!

(Bil and I are co-maintainers of our concerned package on PyPI)

**Comment by ewdurbin** [comment]
It is, there’s just a large backlog of these at the moment.

**Comment by OrkoHunter** [comment]
Thank you for the response! :)

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@bih do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: bil" to proceed
