### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by junos** [pypi/support#787]
Request for account recovery.

## PyPI Username

`junos`

have issue for both https://test.pypi.org/ and https://pypi.org/

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:
2FA device deleted by accidentally

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@junos do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: junos" to proceed
