### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dgarros** [pypi/support#908]
Request for account recovery.

## PyPI Username

`dgarros`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:
Hi 
My previous phone died and I lost all my 2FA codes. 
The Authenticator App I was using at the time wasn't offering a good backup solution. 
Please could you help me to reset my account ?
Thanks

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
