### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cthart** [pypi/support#943]
### PyPI Username

cthart

### Reason for request

Lost 2FA authentication app or security token.
Upgraded to a new iPhone and Google Authenticator data didn't come across. Factory reset my iPhone when Apple instructed me to. Have now switched to Authy so this shouldn't happen again!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
